In [1]:
import requests
import pandas as pd
import os
import re

C:\Users\10475\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\10475\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
C:\Users\10475\AppData\Local\Temp\ipykernel_25860\903929269.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
url = 'https://materialsdb.cn/2dsdb/index.html?'
headers = {
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.51'
}
response = requests.get(url=url,headers=headers)
print(response)

<Response [200]>

In [3]:
html_data = re.findall('<li><p><a class="reference external" href="(.*?).html">(.*?)</a></p></li>',response.text)
print(len(html_data))

274

In [4]:
filename = 'materials\\'
if not os.path.exists(filename):
    os.mkdir(filename)

In [5]:
materials_id = []
materials_num = re.sub(r'\^','/',str(html_data[0][0]))
num = re.sub(r'\^','%5E',str(html_data[0][0]))

In [6]:
materials_id = []
for num_id in html_data:
    materials_num = re.sub(r'\^','/',str(num_id[0]))
    materials_id.append(materials_num)
    num = re.sub(r'\^','%5E',str(num_id[0]))
    materials_url = f'https://materialsdb.cn/2dsdb/{num}.html'
    print(materials_url)

https://materialsdb.cn/2dsdb/As_P21-m.html
https://materialsdb.cn/2dsdb/As_P-3m1.html
https://materialsdb.cn/2dsdb/As_Pca21.html
https://materialsdb.cn/2dsdb/As_Pmn2_1.html
https://materialsdb.cn/2dsdb/As_Pmna.html
https://materialsdb.cn/2dsdb/C_P6%5Emmm.html
https://materialsdb.cn/2dsdb/Ge_P-3m1.html
https://materialsdb.cn/2dsdb/P_P21-m.html
https://materialsdb.cn/2dsdb/P_Pca21.html
https://materialsdb.cn/2dsdb/P_Pmna.html
https://materialsdb.cn/2dsdb/Si_P-3m1.html
https://materialsdb.cn/2dsdb/AlN_P-6m2.html
https://materialsdb.cn/2dsdb/AuSe_P2%5Em.html
https://materialsdb.cn/2dsdb/BN_P-6m2.html
https://materialsdb.cn/2dsdb/GaN_P-6m2.html
https://materialsdb.cn/2dsdb/GaSe_P-6m2.html
https://materialsdb.cn/2dsdb/GaS_P-3m1.html
https://materialsdb.cn/2dsdb/GaS_P-6m2.html
https://materialsdb.cn/2dsdb/GeAs_P-6m2.html
https://materialsdb.cn/2dsdb/GeP_P-6m2.html
https://materialsdb.cn/2dsdb/GeSe_Pmn2_1.html
https://materialsdb.cn/2dsdb/InN_P-6m2.html
https://materialsdb.cn/2dsdb/InSe_P3m1.html
https://materialsdb.cn/2dsdb/PbS_Aem2.html
https://materialsdb.cn/2dsdb/SiAs_P-6m2.html
https://materialsdb.cn/2dsdb/SiH_P-3m1.html
https://materialsdb.cn/2dsdb/SiP_P-6m2.html
https://materialsdb.cn/2dsdb/SiSb_P-6m2.html
https://materialsdb.cn/2dsdb/SnAs_P-6m2.html
https://materialsdb.cn/2dsdb/SnO_P4%5Enmm.html
https://materialsdb.cn/2dsdb/SnO_Pmmn.html
https://materialsdb.cn/2dsdb/SnP_P-6m2.html
https://materialsdb.cn/2dsdb/SnSe_Pmn2_1.html
https://materialsdb.cn/2dsdb/SnS_Pmn2_1.html
https://materialsdb.cn/2dsdb/TlF_Pbcm.html
https://materialsdb.cn/2dsdb/BaO2_P4%5Emmm.html
https://materialsdb.cn/2dsdb/BrTe2_Pmn2_1.html
https://materialsdb.cn/2dsdb/CdBr2_P-3m1.html
https://materialsdb.cn/2dsdb/CdCl2_P-1.html
https://materialsdb.cn/2dsdb/CdCl2_P-3m1.html
https://materialsdb.cn/2dsdb/CrO2_P-6m2.html
https://materialsdb.cn/2dsdb/CrS2_P-6m2.html
https://materialsdb.cn/2dsdb/CrSe2_P-6m2.html
https://materialsdb.cn/2dsdb/FeS2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/FeSe2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/FeTe2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/GeAs2_Pmc2_1.html
https://materialsdb.cn/2dsdb/GeI2_P-3m1.html
https://materialsdb.cn/2dsdb/GeO2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/GeO2_P-3m1.html
https://materialsdb.cn/2dsdb/GeS2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/HfO2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/HfS2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/HfS2_P-3m1.html
https://materialsdb.cn/2dsdb/HfSe2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/HfSe2_P-3m1.html
https://materialsdb.cn/2dsdb/HfTe2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/HfTe2_P-3m1.html
https://materialsdb.cn/2dsdb/HgBr2_Cm.html
https://materialsdb.cn/2dsdb/MgBr2_P-3m1.html
https://materialsdb.cn/2dsdb/MgCl2_P-3m1.html
https://materialsdb.cn/2dsdb/MoO2_P-6m2.html
https://materialsdb.cn/2dsdb/MoS2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/MoS2_P-6m2.html
https://materialsdb.cn/2dsdb/MoSe2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/MoSe2_P-6m2.html
https://materialsdb.cn/2dsdb/MoTe2_P-6m2.html
https://materialsdb.cn/2dsdb/NiO2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/NiS2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/NiS2_P-3m1.html
https://materialsdb.cn/2dsdb/NiSe2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/NiSe2_P-3m1.html
https://materialsdb.cn/2dsdb/NiTe2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/OsO2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/OsS2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/OsSe2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/PbI2_P-3m1.html
https://materialsdb.cn/2dsdb/PbO2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/PbO2_P-3m1.html
https://materialsdb.cn/2dsdb/PbS2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/PbSe2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/PdO2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/PdO2_P-3m1.html
https://materialsdb.cn/2dsdb/PdS2_P2_1%5Ec.html
https://materialsdb.cn/2dsdb/PdS2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/PdS2_P-3m1.html
https://materialsdb.cn/2dsdb/PdSe2_P2_1%5Ec.html
https://materialsdb.cn/2dsdb/PdSe2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/PdSe2_P-3m1.html
https://materialsdb.cn/2dsdb/PdTe2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/PdTe2_P-3m1.html
https://materialsdb.cn/2dsdb/PtI2_P2_1%5Ec.html
https://materialsdb.cn/2dsdb/PtO2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/PtO2_P-3m1.html
https://materialsdb.cn/2dsdb/PtS2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/PtS2_P-3m1.html
https://materialsdb.cn/2dsdb/PtSe2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/PtSe2_P-3m1.html
https://materialsdb.cn/2dsdb/PtTe2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/PtTe2_P-3m1.html
https://materialsdb.cn/2dsdb/RuO2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/RuS2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/RuSe2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/RuTe2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/SiAs2_Pmc2_1.html
https://materialsdb.cn/2dsdb/SiO2_P6%5Emmm.html
https://materialsdb.cn/2dsdb/SiO2_Pm.html
https://materialsdb.cn/2dsdb/SiP2_Pmc2_1.html
https://materialsdb.cn/2dsdb/SnO2_P1.html
https://materialsdb.cn/2dsdb/SnO2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/SnO2_P-3m1.html
https://materialsdb.cn/2dsdb/SnS2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/SnS2_P-3m1.html
https://materialsdb.cn/2dsdb/SnSe2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/SnSe2_P-3m1.html
https://materialsdb.cn/2dsdb/SrO2_P4%5Emmm.html
https://materialsdb.cn/2dsdb/Te2Br_Pmn2_1.html
https://materialsdb.cn/2dsdb/Te2Mo_P-6m2.html
https://materialsdb.cn/2dsdb/Te2Pd_P-3m1.html
https://materialsdb.cn/2dsdb/Te2Pt_P-3m1.html
https://materialsdb.cn/2dsdb/TiO2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/TiSe2_P-6m2.html
https://materialsdb.cn/2dsdb/WO2_P-6m2.html
https://materialsdb.cn/2dsdb/WS2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/WS2_P-6m2.html
https://materialsdb.cn/2dsdb/WSe2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/WSe2_P-6m2.html
https://materialsdb.cn/2dsdb/WTe2_P-6m2.html
https://materialsdb.cn/2dsdb/ZnCl2_P-4m2.html
https://materialsdb.cn/2dsdb/ZrCl2_P-6m2.html
https://materialsdb.cn/2dsdb/ZrI2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/ZrO2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/ZrO2_P-3m1.html
https://materialsdb.cn/2dsdb/ZrS2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/ZrS2_P-3m1.html
https://materialsdb.cn/2dsdb/ZrSe2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/ZrSe2_P-3m1.html
https://materialsdb.cn/2dsdb/ZrTe2_P-6m2.html
https://materialsdb.cn/2dsdb/AlCl3_C2%5Em.html
https://materialsdb.cn/2dsdb/BiBr3_P2_1%5Ec.html
https://materialsdb.cn/2dsdb/DyCl3_Pmmn.html
https://materialsdb.cn/2dsdb/GdBr3_P-1.html
https://materialsdb.cn/2dsdb/HfS3_P2_1%5Em.html
https://materialsdb.cn/2dsdb/HfSe3_P2_1%5Em.html
https://materialsdb.cn/2dsdb/InBr3_C2%5Em.html
https://materialsdb.cn/2dsdb/IrBr3_C2%5Em.html
https://materialsdb.cn/2dsdb/IrCl3_C2%5Em.html
https://materialsdb.cn/2dsdb/LaI3_Pmmn.html
https://materialsdb.cn/2dsdb/MoO3_P2_1%5Em.html
https://materialsdb.cn/2dsdb/NdBr3_Pmmn.html
https://materialsdb.cn/2dsdb/RhBr3_C2%5Em.html
https://materialsdb.cn/2dsdb/ScCl3_P-3.html
https://materialsdb.cn/2dsdb/Si3H_P-3m1.html
https://materialsdb.cn/2dsdb/SmBr3_Pmmn.html
https://materialsdb.cn/2dsdb/TaSe3_P2_1%5Em.html
https://materialsdb.cn/2dsdb/TbCl3_Pmmn.html
https://materialsdb.cn/2dsdb/TiS3_P2_1%5Em.html
https://materialsdb.cn/2dsdb/YBr3_C2%5Em.html
https://materialsdb.cn/2dsdb/YI3_P-3.html
https://materialsdb.cn/2dsdb/ZrS3_P2_1%5Em.html
https://materialsdb.cn/2dsdb/ZrSe3_P2_1%5Em.html
https://materialsdb.cn/2dsdb/Al2Te3_P2_1%5Ec.html
https://materialsdb.cn/2dsdb/V2O5_Pmmn.html
https://materialsdb.cn/2dsdb/ZrTe5_Pmmn.html
https://materialsdb.cn/2dsdb/AlClO_Pmmn.html
https://materialsdb.cn/2dsdb/BaBrCl_P2_1%5Em.html
https://materialsdb.cn/2dsdb/BaIF_P4%5Enmm.html
https://materialsdb.cn/2dsdb/BiBrO_P4%5Enmm.html
https://materialsdb.cn/2dsdb/BiClO_P4%5Enmm.html
https://materialsdb.cn/2dsdb/BiOF_P-3m1.html
https://materialsdb.cn/2dsdb/BiTeCl_P3m1.html
https://materialsdb.cn/2dsdb/CaClF_P4%5Enmm.html
https://materialsdb.cn/2dsdb/CaHBr_P4%5Enmm.html
https://materialsdb.cn/2dsdb/CaHI_P4%5Enmm.html
https://materialsdb.cn/2dsdb/DySBr_Pmmn.html
https://materialsdb.cn/2dsdb/DySI_Pmmn.html
https://materialsdb.cn/2dsdb/ErSCl_Pmmn.html
https://materialsdb.cn/2dsdb/ErSeI_Pmmn.html
https://materialsdb.cn/2dsdb/GaTeCl_Pmn2_1.html
https://materialsdb.cn/2dsdb/GdBrO_P4%5Enmm.html
https://materialsdb.cn/2dsdb/HfBrN_P-3m1.html
https://materialsdb.cn/2dsdb/HfBrN_Pmmn.html
https://materialsdb.cn/2dsdb/HfIN_P-3m1.html
https://materialsdb.cn/2dsdb/HfNCl_P-3m1.html
https://materialsdb.cn/2dsdb/HoBrO_P-3m1.html
https://materialsdb.cn/2dsdb/InBrO_Pmmn.html
https://materialsdb.cn/2dsdb/InClO_Pmmn.html
https://materialsdb.cn/2dsdb/KMgSb_P4%5Enmm.html
https://materialsdb.cn/2dsdb/KTlO_P2_1%5Em.html
https://materialsdb.cn/2dsdb/LaIO_P4%5Enmm.html
https://materialsdb.cn/2dsdb/LuSBr_Pmmn.html
https://materialsdb.cn/2dsdb/NaZnP_P4%5Enmm.html
https://materialsdb.cn/2dsdb/NdBrO_P4%5Enmm.html
https://materialsdb.cn/2dsdb/NdIO_P4%5Enmm.html
https://materialsdb.cn/2dsdb/PbClF_P4%5Enmm.html
https://materialsdb.cn/2dsdb/PbIF_P4%5Enmm.html
https://materialsdb.cn/2dsdb/PPdSe_P2%5Ec.html
https://materialsdb.cn/2dsdb/PPdS_P2%5Ec.html
https://materialsdb.cn/2dsdb/PrBrO_P-3m1.html
https://materialsdb.cn/2dsdb/PrIO_P4%5Enmm.html
https://materialsdb.cn/2dsdb/RbLiSe_P4%5Enmm.html
https://materialsdb.cn/2dsdb/RbLiS_P4%5Enmm.html
https://materialsdb.cn/2dsdb/SbSeI_Pmn2_1.html
https://materialsdb.cn/2dsdb/ScBrO_Pmmn.html
https://materialsdb.cn/2dsdb/ScIO_P2_1%5Em.html
https://materialsdb.cn/2dsdb/SmBrO_P4%5Enmm.html
https://materialsdb.cn/2dsdb/SrHBr_P4%5Enmm.html
https://materialsdb.cn/2dsdb/SrHI_P4%5Enmm.html
https://materialsdb.cn/2dsdb/SrIF_P4%5Enmm.html
https://materialsdb.cn/2dsdb/TeBiBr_P3m1.html
https://materialsdb.cn/2dsdb/TeRhCl_P2_1%5Em.html
https://materialsdb.cn/2dsdb/TiBrN_Pmmn.html
https://materialsdb.cn/2dsdb/TiNCl_Pmmn.html
https://materialsdb.cn/2dsdb/TmBrO_P4%5Enmm.html
https://materialsdb.cn/2dsdb/YBrO_P-3m1.html
https://materialsdb.cn/2dsdb/YBrO_P4%5Enmm.html
https://materialsdb.cn/2dsdb/YIO_P4%5Enmm.html
https://materialsdb.cn/2dsdb/ZrBrN_Pmmn.html
https://materialsdb.cn/2dsdb/ZrNCl_P-3m1.html
https://materialsdb.cn/2dsdb/AuClO2_P222_1.html
https://materialsdb.cn/2dsdb/CuHO2_Pmn2_1.html
https://materialsdb.cn/2dsdb/CuSe2Br_P2_1.html
https://materialsdb.cn/2dsdb/CuSe2Cl_P2_1.html
https://materialsdb.cn/2dsdb/CuTe2Br_P2_1.html
https://materialsdb.cn/2dsdb/LiBiO2_Pbcm.html
https://materialsdb.cn/2dsdb/TaI2O_P2%5Em.html
https://materialsdb.cn/2dsdb/CdPS3_C2%5Em.html
https://materialsdb.cn/2dsdb/CdPS3_P-3.html
https://materialsdb.cn/2dsdb/MgPSe3_P-3.html
https://materialsdb.cn/2dsdb/PdSeO3_P2_1%5Em.html
https://materialsdb.cn/2dsdb/TiPbO3_P4mm.html
https://materialsdb.cn/2dsdb/TlSbO3_P-31m.html
https://materialsdb.cn/2dsdb/Al2Mg2Se5_P-3m1.html
https://materialsdb.cn/2dsdb/As2SO6_P2_12_12.html
https://materialsdb.cn/2dsdb/Ba4Sb2O_P4%5Emmm.html
https://materialsdb.cn/2dsdb/BaCaI4_P2%5Em.html
https://materialsdb.cn/2dsdb/BaTe2O6_Pmma.html
https://materialsdb.cn/2dsdb/Bi2Pb2Se5_P-3m1.html
https://materialsdb.cn/2dsdb/Bi2Te2S_P-3m1.html
https://materialsdb.cn/2dsdb/CaPbI4_P2%5Em.html
https://materialsdb.cn/2dsdb/CdPS3_C2%5Em.html
https://materialsdb.cn/2dsdb/CdPS3_P-3.html
https://materialsdb.cn/2dsdb/GeY2I2_P-3m1.html
https://materialsdb.cn/2dsdb/HfTeSe4_P2%5Em.html
https://materialsdb.cn/2dsdb/K4HgAs2_P-3m1.html
https://materialsdb.cn/2dsdb/Li2CeAs2_P-3m1.html
https://materialsdb.cn/2dsdb/Li2S4W_P-42m.html
https://materialsdb.cn/2dsdb/Lu2CCl2_P-3m1.html
https://materialsdb.cn/2dsdb/MgAl2S4_P-3m1.html
https://materialsdb.cn/2dsdb/MgPSe3_P-3.html
https://materialsdb.cn/2dsdb/Na4CdP2_P3m1.html
https://materialsdb.cn/2dsdb/Nb3SBr7_P3m1.html
https://materialsdb.cn/2dsdb/Nb3TeCl7_P3m1.html
https://materialsdb.cn/2dsdb/NiTa2S5_Pmmn.html
https://materialsdb.cn/2dsdb/Pd3P2S8_P-3m1.html
https://materialsdb.cn/2dsdb/PdSeO3_P2_1%5Em.html
https://materialsdb.cn/2dsdb/Rb2Pd3S4_P6%5Emmm.html
https://materialsdb.cn/2dsdb/RbBrF4_P4%5Embm.html
https://materialsdb.cn/2dsdb/Sb2Ge2Te5_P-3m1.html
https://materialsdb.cn/2dsdb/Sb2Te2Se_P-3m1.html
https://materialsdb.cn/2dsdb/Sb4S5Cl2_P2_1%5Em.html
https://materialsdb.cn/2dsdb/Sc2CCl2_P-3m1.html
https://materialsdb.cn/2dsdb/SnP2S6_P312.html
https://materialsdb.cn/2dsdb/Ta3SBr7_Cm.html
https://materialsdb.cn/2dsdb/TaTe4Ir_P2_1%5Em.html
https://materialsdb.cn/2dsdb/TiPbO3_P4mm.html
https://materialsdb.cn/2dsdb/TlPd2Se3_P-3m1.html
https://materialsdb.cn/2dsdb/TlPt2S3_P-3m1.html
https://materialsdb.cn/2dsdb/TlSbO3_P-31m.html
https://materialsdb.cn/2dsdb/TlTe3Pt2_P-3m1.html
https://materialsdb.cn/2dsdb/VPO5_P4%5En.html
https://materialsdb.cn/2dsdb/WCu2S4_P-42m.html
https://materialsdb.cn/2dsdb/ZnAs2O4_P2_1.html
https://materialsdb.cn/2dsdb/ZnIn2S4_P2%5Em.html

In [7]:
#获取dos图
filename = 'graph\\'
if not os.path.exists(filename):
    os.mkdir(filename)

In [ ]:
for num_id in html_data:
    graph_url = f'https://materialsdb.cn/_images/BAND_LDOS-{num_id[0]}.png'
    graph_content = requests.get(url=graph_url,headers=headers).content
    with open('graph\\' + num_id[0] + '.png',mode='wb') as f:
        f.write(graph_content)

In [ ]:
#获取空间群
materials_id = []
space_group = []
for num_id in html_data:
    materials_num = re.sub(r'\^','/',str(num_id[0]))
    materials_id.append(materials_num)
    num = re.sub(r'\^','%5E',str(num_id[0]))
    materials_url = f'https://materialsdb.cn/2dsdb/{num}.html'
    response = requests.get(url=materials_url,headers=headers)
    soup = BeautifulSoup(response.content,'html.parser')
    paragraphs = [p.text for p in soup.find_all('p')]
    space_group.append(paragraphs[12])
    print(space_group)

In [ ]:
materials_space_group = pd.DataFrame({"name":materials_id,"space_group":space_group})
materials_space_group.to_csv("materials_space_group.csv",index=False)

# matminer自动提取材料特征

In [8]:
from pymatgen.ext.matproj import MPRester #短API
#from mp_api.client import MPRester #长API

In [12]:
with MPRester("DxTbWWBsxEID35nq")as mpr:
    criteria = {"elements":{"$all":['O','Li','Fe']},"nelements":3}
    property = ["material_id","pretty_formula","energy_per_atom","spacegroup","structure","density"]
    data = (mpr.query(criteria=criteria,properties=property))
    print(data)

[{'material_id': 'mp-756155', 'pretty_formula': 'Li6FeO4', 'energy_per_atom': -5.117325523181818, 'spacegroup': {'symprec': 0.1, 'source': 'spglib', 'symbol': 'P4_2/nmc', 'number': 137, 'point_group': 'mmm', 'crystal_system': 'tetragonal', 'hall': 'P 4n 2n -1n'}, 'structure': Structure Summary
Lattice
    abc : 6.686419029417614 8.160871258593042 8.159255157088115
 angles : 110.17051264942266 89.99800706143297 90.01037625621055
 volume : 417.9206613437442
      A : 6.686419 -0.000441 -0.000446
      B : -0.000725 6.691772 4.671189
      C : 0.000154 -6.690807 4.669748
    pbc : True True True
PeriodicSite: Li (1.671, 1.673, 3.261) [0.25, 0.4742, 0.2241]
PeriodicSite: Li (1.671, 1.674, 7.932) [0.25, 0.9742, 0.7241]
PeriodicSite: Li (1.671, -5.018, 5.596) [0.25, 0.2242, 0.9741]
PeriodicSite: Li (1.671, 1.674, 5.597) [0.25, 0.7242, 0.4741]
PeriodicSite: Li (5.015, -1.672, 6.079) [0.75, 0.5259, 0.7758]
PeriodicSite: Li (5.015, -1.673, 1.409) [0.75, 0.02587, 0.2758]
PeriodicSite: Li (5.014, 5.019, 3.745) [0.75, 0.7759, 0.02586]
PeriodicSite: Li (5.015, -1.673, 3.744) [0.7501, 0.2759, 0.5259]
PeriodicSite: Li (0.2345, 3.582, 3.503) [0.03514, 0.6426, 0.1073]
PeriodicSite: Li (0.2353, -3.109, 3.502) [0.03519, 0.1426, 0.6074]
PeriodicSite: Li (0.2343, -0.2336, 8.173) [0.03511, 0.8575, 0.8925]
PeriodicSite: Li (0.2347, -0.2341, 3.503) [0.03513, 0.3575, 0.3925]
PeriodicSite: Li (3.108, 3.581, 3.503) [0.465, 0.6426, 0.1074]
PeriodicSite: Li (3.109, -3.11, 3.502) [0.4649, 0.1426, 0.6074]
PeriodicSite: Li (3.107, -0.2345, 8.173) [0.4648, 0.8574, 0.8926]
PeriodicSite: Li (3.108, -0.2349, 3.503) [0.4648, 0.3574, 0.3926]
PeriodicSite: Li (3.577, 0.2349, 1.168) [0.535, 0.1426, 0.1075]
PeriodicSite: Li (3.577, 0.2354, 5.838) [0.5351, 0.6426, 0.6075]
PeriodicSite: Li (3.578, -3.58, 5.838) [0.5352, 0.3574, 0.8926]
PeriodicSite: Li (3.578, 3.111, 5.838) [0.5352, 0.8574, 0.3926]
PeriodicSite: Li (6.451, 0.2355, 1.167) [0.9648, 0.1426, 0.1074]
PeriodicSite: Li (6.451, 0.236, 5.838) [0.9648, 0.6426, 0.6074]
PeriodicSite: Li (6.452, -3.58, 5.837) [0.9649, 0.3575, 0.8925]
PeriodicSite: Li (6.451, 3.111, 5.838) [0.9649, 0.8575, 0.3925]
PeriodicSite: Fe (1.673, 5.017, 5.839) [0.2502, 0.9998, 0.2502]
PeriodicSite: Fe (5.012, 1.671, 8.172) [0.7496, 0.9997, 0.7501]
PeriodicSite: Fe (1.674, -1.671, 5.838) [0.2504, 0.5001, 0.75]
PeriodicSite: Fe (5.013, 1.67, 3.502) [0.7497, 0.4997, 0.2502]
PeriodicSite: O (0.1083, 1.674, 4.488) [0.01626, 0.6054, 0.3554]
PeriodicSite: O (0.1086, -5.018, 4.487) [0.01624, 0.1054, 0.8554]
PeriodicSite: O (1.672, 0.1076, 2.152) [0.2501, 0.2384, 0.2224]
PeriodicSite: O (1.672, 0.1102, 6.822) [0.2501, 0.7386, 0.7222]
PeriodicSite: O (1.672, -3.452, 6.822) [0.2501, 0.4724, 0.9884]
PeriodicSite: O (1.672, 3.237, 6.823) [0.2501, 0.9723, 0.4885]
PeriodicSite: O (3.233, 1.674, 4.486) [0.4836, 0.6054, 0.3552]
PeriodicSite: O (3.234, -5.017, 4.486) [0.4836, 0.1054, 0.8552]
PeriodicSite: O (3.453, -1.671, 4.854) [0.5165, 0.3948, 0.6446]
PeriodicSite: O (3.451, 5.02, 4.854) [0.5163, 0.8947, 0.1446]
PeriodicSite: O (5.014, -0.1113, 7.189) [0.75, 0.7613, 0.778]
PeriodicSite: O (5.014, -0.1102, 2.518) [0.7499, 0.2614, 0.2779]
PeriodicSite: O (5.014, 3.453, 2.518) [0.7499, 0.5276, 0.01158]
PeriodicSite: O (5.015, -3.238, 2.518) [0.75, 0.02761, 0.5116]
PeriodicSite: O (6.578, -1.672, 4.853) [0.9838, 0.3947, 0.6446]
PeriodicSite: O (6.577, 5.019, 4.854) [0.9837, 0.8946, 0.1446], 'density': 2.566593651994418}, {'material_id': 'mp-756856', 'pretty_formula': 'Li5Fe7O12', 'energy_per_atom': -6.183321642916667, 'spacegroup': {'symprec': 0.1, 'source': 'spglib', 'symbol': 'C2', 'number': 5, 'point_group': '2', 'crystal_system': 'monoclinic', 'hall': 'C 2y'}, 'structure': Structure Summary
Lattice
    abc : 5.202903771418899 5.202903771418899 9.873448152530148
 angles : 84.80911320401908 84.80911320401908 120.23472065521308
 volume : 227.07934423923032
      A : 4.511166 2.592217 0.0
      B : -4.511166 2.592217 0.0
      C : 0.0 1.792949 9.70929
    pbc : True True True
PeriodicSite: Li (0.7446, 4.348, 2.48) [0.8329, 0.6678, 0.2555]
PeriodicSite: Li (-0.7381, 5.261, 7.231) [0.6754, 0.839, 0.7447]
PeriodicSite: Li (0.7446, 2.629, 7.229) [0.3322, 0.1671, 0.7445]
PeriodicSite: Li (-0.7381, 1.716, 2.479) [0.161, 0.3246, 0.2553]
PeriodicSite: Li (-3.754, 3.489, 4.855) [0.08391, 0.9161, 0.5]
PeriodicSite: Fe (3.824, 2.592, 0.0) [0.9238, 0.0762, 0.0]
PeriodicSite: Fe (-2.294, 2.678, 7.271) [0.003314, 0.5119, 0.7488]
PeriodicSite: Fe (2.256, 3.489, 4.855) [0.7501, 0.2499, 0.5]
PeriodicSite: Fe (-2.294, 4.299, 2.439) [0.4881, 0.9967, 0.2512]
PeriodicSite: Fe (0.695, 2.592, 0.0) [0.577, 0.423, 0.0]
PeriodicSite: Fe (-0.7212, 3.489, 4.855) [0.4201, 0.5799, 0.5]
PeriodicSite: Fe (-2.292, 2.592, 0.0) [0.2459, 0.7541, 0.0]
PeriodicSite: O (-0.8774, 1.839, 6.019) [0.04306, 0.2376, 0.6199]
PeriodicSite: O (-0.8774, 5.138, 3.69) [0.7624, 0.9569, 0.3801]
PeriodicSite: O (2.313, 3.367, 1.188) [0.8634, 0.3507, 0.1224]
PeriodicSite: O (2.313, 3.611, 8.521) [0.6493, 0.1366, 0.8776]
PeriodicSite: O (0.825, 4.318, 6.014) [0.7102, 0.5273, 0.6194]
PeriodicSite: O (0.825, 2.659, 3.695) [0.4727, 0.2898, 0.3806]
PeriodicSite: O (-0.8032, 3.557, 1.209) [0.5541, 0.7321, 0.1245]
PeriodicSite: O (-0.8032, 3.42, 8.5) [0.2679, 0.4459, 0.8755]
PeriodicSite: O (-2.165, 4.328, 6.05) [0.3795, 0.8593, 0.6231]
PeriodicSite: O (-2.165, 2.649, 3.66) [0.1407, 0.6205, 0.3769]
PeriodicSite: O (0.7361, 0.8601, 1.278) [0.202, 0.0388, 0.1316]
PeriodicSite: O (0.7361, 6.117, 8.432) [0.9612, 0.798, 0.8684], 'density': 4.516351700187067}, {'material_id': 'mp-762529', 'pretty_formula': 'Li2(FeO2)5', 'energy_per_atom': -5.740311930588235, 'spacegroup': {'symprec': 0.1, 'source': 'spglib', 'symbol': 'P-1', 'number': 2, 'point_group': '-1', 'crystal_system': 'triclinic', 'hall': '-P 1'}, 'structure': Structure Summary
Lattice
    abc : 5.1587265109696405 5.14108406297631 7.863559120023261
 angles : 109.15005001136917 100.73781788360941 101.34705273763839
 volume : 185.94137611058665
      A : 5.158348 -0.042521 0.045794
      B : -0.969666 5.048693 -0.034528
      C : -1.55241 -2.87604 7.152201
    pbc : True True True
PeriodicSite: Li (-0.3534, 3.483, 3.021) [0.2351, 0.9342, 0.4254]
PeriodicSite: Li (2.99, -1.353, 4.142) [0.7649, 0.06584, 0.5746]
PeriodicSite: Fe (-1.157, 1.537, 4.914) [0.1145, 0.6982, 0.6896]
PeriodicSite: Fe (-0.4848, 2.524, -0.01726) [0.0, 0.5, 0.0]
PeriodicSite: Fe (1.322, 1.846, 6.345) [0.688, 0.8766, 0.8869]
PeriodicSite: Fe (1.314, 0.2843, 0.8189) [0.312, 0.1234, 0.1131]
PeriodicSite: Fe (3.793, 0.5935, 2.25) [0.8855, 0.3018, 0.3104]
PeriodicSite: O (-1.265, -1.971, 6.179) [0.0341, 0.1023, 0.8642]
PeriodicSite: O (-0.63, -0.02964, 3.705) [0.08862, 0.2904, 0.5189]
PeriodicSite: O (-0.4653, 0.9405, 6.642) [0.3248, 0.7188, 0.93]
PeriodicSite: O (0.1888, 1.726, 1.615) [0.1937, 0.4727, 0.2269]
PeriodicSite: O (0.4004, 2.544, 4.792) [0.447, 0.8901, 0.6715]
PeriodicSite: O (2.236, -0.4134, 2.371) [0.553, 0.1099, 0.3285]
PeriodicSite: O (2.447, 0.4044, 5.548) [0.8063, 0.5273, 0.7731]
PeriodicSite: O (3.102, 1.19, 0.5219) [0.6752, 0.2812, 0.07]
PeriodicSite: O (3.266, 2.16, 3.458) [0.9114, 0.7096, 0.4811]
PeriodicSite: O (3.901, 4.101, 0.9842) [0.9659, 0.8977, 0.1358], 'density': 4.046393155486004}, {'material_id': 'mp-18782', 'pretty_formula': 'LiFeO2', 'energy_per_atom': -6.08593135625, 'spacegroup': {'symprec': 0.1, 'source': 'spglib', 'symbol': 'I4_1/amd', 'number': 141, 'point_group': '4/mmm', 'crystal_system': 'tetragonal', 'hall': 'I 4bw 2bw -1bw'}, 'structure': Structure Summary
Lattice
    abc : 5.258908168563319 5.258908168563319 5.258908168563319
 angles : 133.8477977525743 133.8477977525743 67.32583090158086
 volume : 74.3879115337108
      A : -2.061247 2.061247 4.377058
      B : 2.061247 -2.061247 4.377058
      C : 2.061247 2.061247 -4.377058
    pbc : True True True
PeriodicSite: Li (0.0, 0.0, 4.377) [0.5, 0.5, 0.0]
PeriodicSite: Li (2.061, 0.0, 2.189) [0.25, 0.75, 0.5]
PeriodicSite: Fe (0.0, 2.061, 2.189) [0.75, 0.25, 0.5]
PeriodicSite: Fe (0.0, 0.0, 0.0) [0.0, 0.0, 0.0]
PeriodicSite: O (0.0, 0.0, 6.719) [0.7675, 0.7675, 0.0]
PeriodicSite: O (0.0, 2.061, 0.1535) [0.5175, 0.01753, 0.5]
PeriodicSite: O (0.0, 2.061, 4.224) [0.9825, 0.4825, 0.5]
PeriodicSite: O (0.0, 0.0, 2.035) [0.2325, 0.2325, 0.0], 'density': 4.231705396072065}, {'material_id': 'mp-756497', 'pretty_formula': 'LiFeO2', 'energy_per_atom': -6.0787704605, 'spacegroup': {'symprec': 0.1, 'source': 'spglib', 'symbol': 'P-1', 'number': 2, 'point_group': '-1', 'crystal_system': 'triclinic', 'hall': '-P 1'}, 'structure': Structure Summary
Lattice
    abc : 5.149673 5.179132928927776 7.961024725376124
 angles : 71.12525293218096 71.5388616155062 79.83580346654168
 volume : 189.9215280745178
      A : 5.149673 0.0 0.0
      B : 0.91396 5.097852 0.0
      C : 2.520949 2.164493 7.23448
    pbc : True True True
PeriodicSite: Li (3.05, 3.811, 4.241) [0.2167, 0.4987, 0.5863]
PeriodicSite: Li (3.013, 2.968, 1.613) [0.3894, 0.4875, 0.223]
PeriodicSite: Li (3.835, 1.082, 3.617) [0.5, 0.0, 0.5]
PeriodicSite: Li (5.571, 4.295, 5.621) [0.6106, 0.5125, 0.777]
PeriodicSite: Li (5.535, 3.451, 2.993) [0.7833, 0.5013, 0.4137]
PeriodicSite: Fe (2.21, 5.732, 2.276) [0.09928, 0.9909, 0.3146]
PeriodicSite: Fe (0.457, 2.549, 0.0) [0.0, 0.5, 0.0]
PeriodicSite: Fe (4.742, 5.326, 0.8015) [0.6894, 0.9977, 0.1108]
PeriodicSite: Fe (3.843, 1.936, 6.433) [0.3106, 0.002261, 0.8892]
PeriodicSite: Fe (6.375, 1.53, 4.958) [0.9007, 0.009096, 0.6854]
PeriodicSite: O (1.287, 4.174, 1.0) [0.0474, 0.7601, 0.1383]
PeriodicSite: O (2.086, 1.307, 0.4031) [0.3366, 0.2328, 0.05572]
PeriodicSite: O (2.063, 2.173, 3.296) [0.1363, 0.2328, 0.4556]
PeriodicSite: O (3.803, 5.492, 5.562) [0.229, 0.7508, 0.7688]
PeriodicSite: O (3.872, 4.634, 2.422) [0.4518, 0.7669, 0.3348]
PeriodicSite: O (4.713, 2.628, 4.813) [0.5482, 0.2331, 0.6652]
PeriodicSite: O (4.781, 1.771, 1.672) [0.771, 0.2492, 0.2312]
PeriodicSite: O (6.521, 5.089, 3.938) [0.8637, 0.7672, 0.5444]
PeriodicSite: O (6.498, 5.955, 6.831) [0.6634, 0.7672, 0.9443]
PeriodicSite: O (7.297, 3.088, 6.234) [0.9526, 0.2399, 0.8617], 'density': 4.143655143141868}, {'material_id': 'mp-850511', 'pretty_formula': 'LiFeO2', 'energy_per_atom': -5.33774119453125, 'spacegroup': {'symprec': 0.1, 'source': 'spglib', 'symbol': 'Pbca', 'number': 61, 'point_group': 'mmm', 'crystal_system': 'orthorhombic', 'hall': '-P 2ac 2ab'}, 'structure': Structure Summary
Lattice
    abc : 5.257937 10.784181 13.48683
 angles : 90.0 90.0 90.0
 volume : 764.7375754686997
      A : 5.257937 0.0 0.0
      B : 0.0 10.784181 0.0
      C : 0.0 0.0 13.48683
    pbc : True True True
PeriodicSite: Li (1.072, 8.482, 4.134) [0.2039, 0.7865, 0.3065]
PeriodicSite: Li (1.072, 7.694, 10.88) [0.2039, 0.7135, 0.8065]
PeriodicSite: Li (1.659, 4.947, 5.924) [0.3156, 0.4587, 0.4393]
PeriodicSite: Li (1.659, 0.4454, 12.67) [0.3156, 0.04131, 0.9393]
PeriodicSite: Li (0.9697, 10.34, 5.924) [0.1844, 0.9587, 0.4393]
PeriodicSite: Li (0.9697, 5.838, 12.67) [0.1844, 0.5413, 0.9393]
PeriodicSite: Li (1.557, 3.09, 4.134) [0.2961, 0.2865, 0.3065]
PeriodicSite: Li (1.557, 2.302, 10.88) [0.2961, 0.2135, 0.8065]
PeriodicSite: Li (3.701, 8.482, 2.61) [0.7039, 0.7865, 0.1935]
PeriodicSite: Li (3.701, 7.694, 9.353) [0.7039, 0.7135, 0.6935]
PeriodicSite: Li (4.288, 4.947, 0.8191) [0.8156, 0.4587, 0.06073]
PeriodicSite: Li (4.288, 0.4454, 7.562) [0.8156, 0.04131, 0.5607]
PeriodicSite: Li (3.599, 10.34, 0.8191) [0.6844, 0.9587, 0.06073]
PeriodicSite: Li (3.599, 5.838, 7.562) [0.6844, 0.5413, 0.5607]
PeriodicSite: Li (4.186, 3.09, 2.61) [0.7961, 0.2865, 0.1935]
PeriodicSite: Li (4.186, 2.302, 9.353) [0.7961, 0.2135, 0.6935]
PeriodicSite: Fe (1.041, 8.532, 0.831) [0.198, 0.7911, 0.06162]
PeriodicSite: Fe (1.041, 7.644, 7.574) [0.198, 0.7089, 0.5616]
PeriodicSite: Fe (0.84, 0.4227, 2.494) [0.1598, 0.0392, 0.1849]
PeriodicSite: Fe (0.84, 4.969, 9.238) [0.1598, 0.4608, 0.6849]
PeriodicSite: Fe (1.789, 5.815, 2.494) [0.3402, 0.5392, 0.1849]
PeriodicSite: Fe (1.789, 10.36, 9.238) [0.3402, 0.9608, 0.6849]
PeriodicSite: Fe (1.588, 3.14, 0.831) [0.302, 0.2911, 0.06162]
PeriodicSite: Fe (1.588, 2.252, 7.574) [0.302, 0.2089, 0.5616]
PeriodicSite: Fe (3.67, 8.532, 5.912) [0.698, 0.7911, 0.4384]
PeriodicSite: Fe (3.67, 7.644, 12.66) [0.698, 0.7089, 0.9384]
PeriodicSite: Fe (3.469, 4.969, 10.99) [0.6598, 0.4608, 0.8151]
PeriodicSite: Fe (3.469, 0.4227, 4.249) [0.6598, 0.0392, 0.3151]
PeriodicSite: Fe (4.418, 5.815, 4.249) [0.8402, 0.5392, 0.3151]
PeriodicSite: Fe (4.418, 10.36, 10.99) [0.8402, 0.9608, 0.8151]
PeriodicSite: Fe (4.217, 3.14, 5.912) [0.802, 0.2911, 0.4384]
PeriodicSite: Fe (4.217, 2.252, 12.66) [0.802, 0.2089, 0.9384]
PeriodicSite: O (0.8706, 3.057, 6.015) [0.1656, 0.2835, 0.446]
PeriodicSite: O (0.8706, 2.335, 12.76) [0.1656, 0.2165, 0.946]
PeriodicSite: O (0.9502, 5.183, 4.085) [0.1807, 0.4806, 0.3029]
PeriodicSite: O (0.9502, 0.2095, 10.83) [0.1807, 0.01943, 0.8029]
PeriodicSite: O (1.051, 4.968, 0.9451) [0.1999, 0.4607, 0.07008]
PeriodicSite: O (1.051, 0.4243, 7.689) [0.1999, 0.03934, 0.5701]
PeriodicSite: O (1.734, 7.725, 2.424) [0.3297, 0.7163, 0.1797]
PeriodicSite: O (1.734, 8.451, 9.167) [0.3297, 0.7837, 0.6797]
PeriodicSite: O (0.8954, 3.059, 9.167) [0.1703, 0.2837, 0.6797]
PeriodicSite: O (0.8954, 2.333, 2.424) [0.1703, 0.2163, 0.1797]
PeriodicSite: O (1.578, 10.36, 0.9451) [0.3001, 0.9607, 0.07008]
PeriodicSite: O (1.578, 5.816, 7.689) [0.3001, 0.5393, 0.5701]
PeriodicSite: O (1.679, 5.602, 10.83) [0.3193, 0.5194, 0.8029]
PeriodicSite: O (1.679, 10.57, 4.085) [0.3193, 0.9806, 0.3029]
PeriodicSite: O (1.758, 8.449, 6.015) [0.3344, 0.7835, 0.446]
PeriodicSite: O (1.758, 7.727, 12.76) [0.3344, 0.7165, 0.946]
PeriodicSite: O (3.5, 3.057, 0.7288) [0.6656, 0.2835, 0.05404]
PeriodicSite: O (3.5, 2.335, 7.472) [0.6656, 0.2165, 0.554]
PeriodicSite: O (3.579, 0.2095, 9.402) [0.6807, 0.01943, 0.6971]
PeriodicSite: O (3.579, 5.183, 2.658) [0.6807, 0.4806, 0.1971]
PeriodicSite: O (3.68, 0.4243, 12.54) [0.6999, 0.03934, 0.9299]
PeriodicSite: O (3.68, 4.968, 5.798) [0.6999, 0.4607, 0.4299]
PeriodicSite: O (4.363, 7.725, 4.32) [0.8297, 0.7163, 0.3203]
PeriodicSite: O (4.363, 8.451, 11.06) [0.8297, 0.7837, 0.8203]
PeriodicSite: O (3.524, 2.333, 4.32) [0.6703, 0.2163, 0.3203]
PeriodicSite: O (3.524, 3.059, 11.06) [0.6703, 0.2837, 0.8203]
PeriodicSite: O (4.207, 5.816, 12.54) [0.8001, 0.5393, 0.9299]
PeriodicSite: O (4.207, 10.36, 5.798) [0.8001, 0.9607, 0.4299]
PeriodicSite: O (4.308, 5.602, 9.402) [0.8193, 0.5194, 0.6971]
PeriodicSite: O (4.308, 10.57, 2.658) [0.8193, 0.9806, 0.1971]
PeriodicSite: O (4.387, 7.727, 7.472) [0.8344, 0.7165, 0.554]
PeriodicSite: O (4.387, 8.449, 0.7288) [0.8344, 0.7835, 0.05404], 'density': 3.2930274304547438}, {'material_id': 'mp-780312', 'pretty_formula': 'Li5(FeO2)4', 'energy_per_atom': -5.695383365588235, 'spacegroup': {'symprec': 0.1, 'source': 'spglib', 'symbol': 'Cc', 'number': 9, 'point_group': 'm', 'crystal_system': 'monoclinic', 'hall': 'C -2yc'}, 'structure': Structure Summary
Lattice
    abc : 6.008735230746983 6.008735230746983 9.918451393580755
 angles : 89.83584826938531 89.83584826938531 119.70698242568182
 volume : 311.0343303644278
      A : 5.196018 3.017664 0.0
      B : -5.196018 3.017664 0.0
      C : 0.0 0.056582 9.91829
    pbc : True True True
PeriodicSite: Li (3.154, 3.113, 9.488) [0.8103, 0.2033, 0.9567]
PeriodicSite: Li (1.025, 1.843, 9.525) [0.3951, 0.1977, 0.9603]
PeriodicSite: Li (1.727, 3.038, 7.34) [0.6627, 0.3303, 0.7401]
PeriodicSite: Li (1.013, 4.326, 9.492) [0.8053, 0.6103, 0.957]
PeriodicSite: Li (-1.025, 1.815, 4.566) [0.1977, 0.3951, 0.4603]
PeriodicSite: Li (-1.013, 4.298, 4.533) [0.6103, 0.8053, 0.457]
PeriodicSite: Li (0.01462, 6.054, 5.217) [0.9995, 0.9967, 0.526]
PeriodicSite: Li (-1.727, 3.01, 2.381) [0.3303, 0.6627, 0.2401]
PeriodicSite: Li (-0.01462, 6.025, 0.258) [0.9967, 0.9995, 0.02601]
PeriodicSite: Li (-3.154, 3.085, 4.529) [0.2033, 0.8103, 0.4567]
PeriodicSite: Fe (1.76, 3.008, 4.81) [0.6633, 0.3245, 0.485]
PeriodicSite: Fe (-1.76, 3.037, 9.769) [0.3245, 0.6633, 0.985]
PeriodicSite: Fe (3.455, 3.018, 2.25) [0.8304, 0.1654, 0.2268]
PeriodicSite: Fe (0.8811, 1.53, 2.241) [0.3362, 0.1666, 0.226]
PeriodicSite: Fe (0.8952, 4.491, 2.261) [0.828, 0.6558, 0.228]
PeriodicSite: Fe (-0.8811, 1.559, 7.2) [0.1666, 0.3362, 0.726]
PeriodicSite: Fe (-0.8952, 4.519, 7.22) [0.6558, 0.828, 0.728]
PeriodicSite: Fe (-3.455, 3.046, 7.209) [0.1654, 0.8304, 0.7268]
PeriodicSite: O (3.49, 3.003, 5.976) [0.8277, 0.1561, 0.6025]
PeriodicSite: O (2.594, 1.63, 3.467) [0.5165, 0.01719, 0.3495]
PeriodicSite: O (1.788, 3.083, 1.062) [0.6819, 0.3378, 0.1071]
PeriodicSite: O (0.9332, 1.494, 5.933) [0.3318, 0.1522, 0.5982]
PeriodicSite: O (2.581, 4.455, 3.478) [0.9832, 0.4866, 0.3507]
PeriodicSite: O (0.1222, 3.093, 3.536) [0.5209, 0.4973, 0.3566]
PeriodicSite: O (-0.9332, 1.466, 0.9742) [0.1522, 0.3318, 0.09822]
PeriodicSite: O (0.8817, 4.557, 6.018) [0.8341, 0.6645, 0.6068]
PeriodicSite: O (-0.1222, 3.121, 8.496) [0.4973, 0.5209, 0.8566]
PeriodicSite: O (-0.8817, 4.528, 1.059) [0.6645, 0.8341, 0.1068]
PeriodicSite: O (-1.788, 3.112, 6.021) [0.3378, 0.6819, 0.6071]
PeriodicSite: O (0.05203, 5.983, 8.303) [0.9884, 0.9784, 0.8371]
PeriodicSite: O (-2.594, 1.658, 8.426) [0.01719, 0.5165, 0.8495]
PeriodicSite: O (-2.581, 4.484, 8.437) [0.4866, 0.9832, 0.8507]
PeriodicSite: O (-3.49, 2.975, 1.017) [0.1561, 0.8277, 0.1025]
PeriodicSite: O (-0.05203, 5.954, 3.344) [0.9784, 0.9884, 0.3371], 'density': 4.122382594806084}, {'material_id': 'mp-780203', 'pretty_formula': 'Li9(FeO4)2', 'energy_per_atom': -5.141026137105263, 'spacegroup': {'symprec': 0.1, 'source': 'spglib', 'symbol': 'P1', 'number': 1, 'point_group': '1', 'crystal_system': 'triclinic', 'hall': 'P 1'}, 'structure': Structure Summary
Lattice
    abc : 5.538512 6.774155710546518 10.871061735215747
 angles : 90.69319436653348 101.51839965198717 90.51974250250198
 volume : 399.5976379868073
      A : 5.538512 0.0 0.0
      B : -0.061449 6.773877 0.0
      C : -2.170762 -0.151218 10.651052
    pbc : True True True
PeriodicSite: Li (-0.9333, 5.544, 7.578) [0.1196, 0.8344, 0.7115]
PeriodicSite: Li (-0.5393, 5.01, 3.599) [0.04337, 0.7472, 0.3379]
PeriodicSite: Li (0.04221, 3.126, 2.111) [0.09047, 0.4659, 0.1982]
PeriodicSite: Li (-0.4258, 0.1438, 9.913) [0.2884, 0.04201, 0.9307]
PeriodicSite: Li (-0.09782, 3.459, 6.07) [0.2115, 0.5233, 0.5699]
PeriodicSite: Li (-0.3962, 3.102, 10.03) [0.303, 0.479, 0.9419]
PeriodicSite: Li (0.4831, 1.89, 8.352) [0.3978, 0.2965, 0.7841]
PeriodicSite: Li (0.9727, 4.94, 8.971) [0.514, 0.748, 0.8423]
PeriodicSite: Li (1.508, 0.06294, 7.317) [0.5419, 0.02463, 0.6869]
PeriodicSite: Li (2.146, 1.583, 1.915) [0.4605, 0.2377, 0.1798]
PeriodicSite: Li (2.653, 5.024, 2.442) [0.5772, 0.7468, 0.2293]
PeriodicSite: Li (3.54, 0.04101, 4.731) [0.8134, 0.01597, 0.4442]
PeriodicSite: Li (3.475, 3.033, 4.563) [0.8005, 0.4573, 0.4284]
PeriodicSite: Li (3.609, 3.522, 0.7721) [0.6858, 0.5215, 0.07249]
PeriodicSite: Li (3.236, 3.571, 8.553) [0.9051, 0.5451, 0.803]
PeriodicSite: Li (3.731, 6.568, 0.8314) [0.7151, 0.9713, 0.07806]
PeriodicSite: Li (3.96, 1.501, 7.083) [0.9783, 0.2364, 0.665]
PeriodicSite: Li (4.36, 1.368, 3.015) [0.9005, 0.2083, 0.283]
PeriodicSite: Fe (2.487, 1.529, 9.951) [0.8181, 0.2466, 0.9343]
PeriodicSite: Fe (0.7564, 5.145, 0.6876) [0.1703, 0.761, 0.06456]
PeriodicSite: Fe (0.8389, 1.446, 4.674) [0.3259, 0.2232, 0.4388]
PeriodicSite: Fe (2.484, 4.881, 6.05) [0.6793, 0.7332, 0.5681]
PeriodicSite: O (-1.353, 1.735, 9.098) [0.09362, 0.2752, 0.8542]
PeriodicSite: O (-1.105, 4.926, 9.444) [0.1563, 0.7469, 0.8866]
PeriodicSite: O (-0.1832, 0.09649, 4.052) [0.1163, 0.02274, 0.3804]
PeriodicSite: O (-0.1731, 2.966, 4.039) [0.1223, 0.4463, 0.3792]
PeriodicSite: O (0.4478, 1.551, 6.493) [0.3225, 0.2426, 0.6096]
PeriodicSite: O (0.8894, 4.933, 6.927) [0.4237, 0.7428, 0.6504]
PeriodicSite: O (1.725, 3.573, 1.3) [0.3652, 0.5303, 0.1221]

In [13]:
data = pd.DataFrame(data)
data

,material_id,pretty_formula,energy_per_atom,spacegroup,structure,density
0,mp-756155,Li6FeO4,-5.117326,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[1.67125537 1.67346391 3.26141012] Li, [1.670...",2.566594
1,mp-756856,Li5Fe7O12,-6.183322,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[0.74461757 4.34819314 2.48026726] Li, [-0.73...",4.516352
2,mp-762529,Li2(FeO2)5,-5.740312,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[-0.35339594 3.48269285 3.02141686] Li, [ 2...",4.046393
3,mp-18782,LiFeO2,-6.085931,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[0. 0. 4.377058] Li, [2.061247 0....",4.231705
4,mp-756497,LiFeO2,-6.078770,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[3.04987747 3.81109335 4.24134412] Li, [3.013...",4.143655
...,...,...,...,...,...,...
155,mp-1101736,LiFe3O4,-6.351436,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[-1.48982311 2.19943369 -1.43482144] Li, [-1...",5.018471
156,mp-780216,Li5Fe3O8,-5.304033,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[ 1.33531488 -4.11912064 -0.49520662] Li, [-0...",3.757134
157,mp-759394,Li2FeO3,-5.613536,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[1.244898 0. 4.9203229] Li, [1.244898...",3.651901
158,mp-1314324,LiFe2O3,-6.267500,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[ 1.52274007 -2.68996763 3.71993333] Li, [ 3...",4.625861
159,mp-1279318,Li3FeO4,-5.370547,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...",[[ 3.44876738e+00 2.15699951e+00 -5.36130908e...,3.233877

In [14]:
from matminer.featurizers.structure import XRDPowderPattern

xrd = XRDPowderPattern(two_theta_range=[0,299])
xrd.feature_labels()
data = xrd.featurize_dataframe(data,"structure")
data

XRDPowderPattern:   0%|          | 0/160 [00:00<?, ?it/s]

,material_id,pretty_formula,energy_per_atom,spacegroup,structure,density,xrd_0,xrd_1,xrd_2,xrd_3,...,xrd_290,xrd_291,xrd_292,xrd_293,xrd_294,xrd_295,xrd_296,xrd_297,xrd_298,xrd_299
0,mp-756155,Li6FeO4,-5.117326,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[1.67125537 1.67346391 3.26141012] Li, [1.670...",2.566594,5.977826e-179,1.379972e-160,3.144998e-143,7.076099e-127,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,mp-756856,Li5Fe7O12,-6.183322,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[0.74461757 4.34819314 2.48026726] Li, [-0.73...",4.516352,1.186238e-56,2.163227e-45,1.940292e-35,8.559855e-27,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,mp-762529,Li2(FeO2)5,-5.740312,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[-0.35339594 3.48269285 3.02141686] Li, [ 2...",4.046393,1.552619e-78,1.175554e-66,8.898801e-56,6.734917e-46,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,mp-18782,LiFeO2,-6.085931,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[0. 0. 4.377058] Li, [2.061247 0....",4.231705,0.000000e+00,0.000000e+00,9.881313e-322,3.397916e-293,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,mp-756497,LiFeO2,-6.078770,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[3.04987747 3.81109335 4.24134412] Li, [3.013...",4.143655,3.678547e-82,1.400721e-69,4.517527e-58,1.234025e-47,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,mp-1101736,LiFe3O4,-6.351436,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[-1.48982311 2.19943369 -1.43482144] Li, [-1...",5.018471,2.624011e-228,1.241719e-203,2.209240e-180,1.478050e-158,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
156,mp-780216,Li5Fe3O8,-5.304033,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[ 1.33531488 -4.11912064 -0.49520662] Li, [-0...",3.757134,6.358424e-144,2.845674e-128,1.529721e-113,9.882739e-100,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
157,mp-759394,Li2FeO3,-5.613536,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[1.244898 0. 4.9203229] Li, [1.244898...",3.651901,1.407637e-221,1.260348e-200,1.010579e-180,7.256715e-162,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
158,mp-1314324,LiFe2O3,-6.267500,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[ 1.52274007 -2.68996763 3.71993333] Li, [ 3...",4.625861,4.635395e-58,4.953273e-49,8.621947e-41,2.444703e-33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
159,mp-1279318,Li3FeO4,-5.370547,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...",[[ 3.44876738e+00 2.15699951e+00 -5.36130908e...,3.233877,5.531360e-248,1.479640e-224,2.667413e-202,3.240667e-181,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
from matminer.featurizers.conversions import StrToComposition

data = StrToComposition().featurize_dataframe(data,"pretty_formula")
data

StrToComposition:   0%|          | 0/160 [00:00<?, ?it/s]

,material_id,pretty_formula,energy_per_atom,spacegroup,structure,density,xrd_0,xrd_1,xrd_2,xrd_3,...,xrd_291,xrd_292,xrd_293,xrd_294,xrd_295,xrd_296,xrd_297,xrd_298,xrd_299,composition
0,mp-756155,Li6FeO4,-5.117326,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[1.67125537 1.67346391 3.26141012] Li, [1.670...",2.566594,5.977826e-179,1.379972e-160,3.144998e-143,7.076099e-127,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"(Li, Fe, O)"
1,mp-756856,Li5Fe7O12,-6.183322,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[0.74461757 4.34819314 2.48026726] Li, [-0.73...",4.516352,1.186238e-56,2.163227e-45,1.940292e-35,8.559855e-27,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"(Li, Fe, O)"
2,mp-762529,Li2(FeO2)5,-5.740312,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[-0.35339594 3.48269285 3.02141686] Li, [ 2...",4.046393,1.552619e-78,1.175554e-66,8.898801e-56,6.734917e-46,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"(Li, Fe, O)"
3,mp-18782,LiFeO2,-6.085931,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[0. 0. 4.377058] Li, [2.061247 0....",4.231705,0.000000e+00,0.000000e+00,9.881313e-322,3.397916e-293,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"(Li, Fe, O)"
4,mp-756497,LiFeO2,-6.078770,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[3.04987747 3.81109335 4.24134412] Li, [3.013...",4.143655,3.678547e-82,1.400721e-69,4.517527e-58,1.234025e-47,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"(Li, Fe, O)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,mp-1101736,LiFe3O4,-6.351436,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[-1.48982311 2.19943369 -1.43482144] Li, [-1...",5.018471,2.624011e-228,1.241719e-203,2.209240e-180,1.478050e-158,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"(Li, Fe, O)"
156,mp-780216,Li5Fe3O8,-5.304033,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[ 1.33531488 -4.11912064 -0.49520662] Li, [-0...",3.757134,6.358424e-144,2.845674e-128,1.529721e-113,9.882739e-100,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"(Li, Fe, O)"
157,mp-759394,Li2FeO3,-5.613536,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[1.244898 0. 4.9203229] Li, [1.244898...",3.651901,1.407637e-221,1.260348e-200,1.010579e-180,7.256715e-162,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"(Li, Fe, O)"
158,mp-1314324,LiFe2O3,-6.267500,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[ 1.52274007 -2.68996763 3.71993333] Li, [ 3...",4.625861,4.635395e-58,4.953273e-49,8.621947e-41,2.444703e-33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"(Li, Fe, O)"
159,mp-1279318,Li3FeO4,-5.370547,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...",[[ 3.44876738e+00 2.15699951e+00 -5.36130908e...,3.233877,5.531360e-248,1.479640e-224,2.667413e-202,3.240667e-181,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"(Li, Fe, O)"

In [16]:
from matminer.featurizers.composition import ElementProperty

ep_feat = ElementProperty.from_preset(preset_name="magpie")
data = ep_feat.featurize_dataframe(data,col_id="composition")
data

ElementProperty:   0%|          | 0/160 [00:00<?, ?it/s]

,material_id,pretty_formula,energy_per_atom,spacegroup,structure,density,xrd_0,xrd_1,xrd_2,xrd_3,...,MagpieData range GSmagmom,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber
0,mp-756155,Li6FeO4,-5.117326,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[1.67125537 1.67346391 3.26141012] Li, [1.670...",2.566594,5.977826e-179,1.379972e-160,3.144998e-143,7.076099e-127,...,2.110663,0.191878,0.348870,0.0,12.0,229.0,217.0,150.090909,100.429752,229.0
1,mp-756856,Li5Fe7O12,-6.183322,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[0.74461757 4.34819314 2.48026726] Li, [-0.73...",4.516352,1.186238e-56,2.163227e-45,1.940292e-35,8.559855e-27,...,2.110663,0.615610,0.872114,0.0,12.0,229.0,217.0,120.500000,108.500000,12.0
2,mp-762529,Li2(FeO2)5,-5.740312,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[-0.35339594 3.48269285 3.02141686] Li, [ 2...",4.046393,1.552619e-78,1.175554e-66,8.898801e-56,6.734917e-46,...,2.110663,0.620783,0.876400,0.0,12.0,229.0,217.0,101.352941,105.121107,12.0
3,mp-18782,LiFeO2,-6.085931,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[0. 0. 4.377058] Li, [2.061247 0....",4.231705,0.000000e+00,0.000000e+00,9.881313e-322,3.397916e-293,...,2.110663,0.527666,0.791499,0.0,12.0,229.0,217.0,120.500000,108.500000,12.0
4,mp-756497,LiFeO2,-6.078770,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[3.04987747 3.81109335 4.24134412] Li, [3.013...",4.143655,3.678547e-82,1.400721e-69,4.517527e-58,1.234025e-47,...,2.110663,0.527666,0.791499,0.0,12.0,229.0,217.0,120.500000,108.500000,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,mp-1101736,LiFe3O4,-6.351436,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[-1.48982311 2.19943369 -1.43482144] Li, [-1...",5.018471,2.624011e-228,1.241719e-203,2.209240e-180,1.478050e-158,...,2.110663,0.791499,0.989373,0.0,12.0,229.0,217.0,120.500000,108.500000,12.0
156,mp-780216,Li5Fe3O8,-5.304033,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[ 1.33531488 -4.11912064 -0.49520662] Li, [-0...",3.757134,6.358424e-144,2.845674e-128,1.529721e-113,9.882739e-100,...,2.110663,0.395749,0.643093,0.0,12.0,229.0,217.0,120.500000,108.500000,12.0
157,mp-759394,Li2FeO3,-5.613536,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[1.244898 0. 4.9203229] Li, [1.244898...",3.651901,1.407637e-221,1.260348e-200,1.010579e-180,7.256715e-162,...,2.110663,0.351777,0.586295,0.0,12.0,229.0,217.0,120.500000,108.500000,12.0
158,mp-1314324,LiFe2O3,-6.267500,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[ 1.52274007 -2.68996763 3.71993333] Li, [ 3...",4.625861,4.635395e-58,4.953273e-49,8.621947e-41,2.444703e-33,...,2.110663,0.703554,0.938072,0.0,12.0,229.0,217.0,120.500000,108.500000,12.0
159,mp-1279318,Li3FeO4,-5.370547,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...",[[ 3.44876738e+00 2.15699951e+00 -5.36130908e...,3.233877,5.531360e-248,1.479640e-224,2.667413e-202,3.240667e-181,...,2.110663,0.263833,0.461707,0.0,12.0,229.0,217.0,120.500000,108.500000,12.0

In [17]:
from matminer.featurizers.conversions import CompositionToOxidComposition

data = CompositionToOxidComposition().featurize_dataframe(data,"composition",ignore_errors = True)
data

CompositionToOxidComposition:   0%|          | 0/160 [00:00<?, ?it/s]

,material_id,pretty_formula,energy_per_atom,spacegroup,structure,density,xrd_0,xrd_1,xrd_2,xrd_3,...,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber,composition_oxid
0,mp-756155,Li6FeO4,-5.117326,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[1.67125537 1.67346391 3.26141012] Li, [1.670...",2.566594,5.977826e-179,1.379972e-160,3.144998e-143,7.076099e-127,...,0.191878,0.348870,0.0,12.0,229.0,217.0,150.090909,100.429752,229.0,"(Li+, Fe2+, O2-)"
1,mp-756856,Li5Fe7O12,-6.183322,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[0.74461757 4.34819314 2.48026726] Li, [-0.73...",4.516352,1.186238e-56,2.163227e-45,1.940292e-35,8.559855e-27,...,0.615610,0.872114,0.0,12.0,229.0,217.0,120.500000,108.500000,12.0,"(Li+, Fe2+, Fe3+, O2-)"
2,mp-762529,Li2(FeO2)5,-5.740312,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[-0.35339594 3.48269285 3.02141686] Li, [ 2...",4.046393,1.552619e-78,1.175554e-66,8.898801e-56,6.734917e-46,...,0.620783,0.876400,0.0,12.0,229.0,217.0,101.352941,105.121107,12.0,"(Li0+, Fe0+, O0+)"
3,mp-18782,LiFeO2,-6.085931,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[0. 0. 4.377058] Li, [2.061247 0....",4.231705,0.000000e+00,0.000000e+00,9.881313e-322,3.397916e-293,...,0.527666,0.791499,0.0,12.0,229.0,217.0,120.500000,108.500000,12.0,"(Li+, Fe3+, O2-)"
4,mp-756497,LiFeO2,-6.078770,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[3.04987747 3.81109335 4.24134412] Li, [3.013...",4.143655,3.678547e-82,1.400721e-69,4.517527e-58,1.234025e-47,...,0.527666,0.791499,0.0,12.0,229.0,217.0,120.500000,108.500000,12.0,"(Li+, Fe3+, O2-)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,mp-1101736,LiFe3O4,-6.351436,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[-1.48982311 2.19943369 -1.43482144] Li, [-1...",5.018471,2.624011e-228,1.241719e-203,2.209240e-180,1.478050e-158,...,0.791499,0.989373,0.0,12.0,229.0,217.0,120.500000,108.500000,12.0,"(Li+, Fe2+, Fe3+, O2-)"
156,mp-780216,Li5Fe3O8,-5.304033,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[ 1.33531488 -4.11912064 -0.49520662] Li, [-0...",3.757134,6.358424e-144,2.845674e-128,1.529721e-113,9.882739e-100,...,0.395749,0.643093,0.0,12.0,229.0,217.0,120.500000,108.500000,12.0,"(Li0+, Fe0+, O0+)"
157,mp-759394,Li2FeO3,-5.613536,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[1.244898 0. 4.9203229] Li, [1.244898...",3.651901,1.407637e-221,1.260348e-200,1.010579e-180,7.256715e-162,...,0.351777,0.586295,0.0,12.0,229.0,217.0,120.500000,108.500000,12.0,"(Li0+, Fe0+, O0+)"
158,mp-1314324,LiFe2O3,-6.267500,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[ 1.52274007 -2.68996763 3.71993333] Li, [ 3...",4.625861,4.635395e-58,4.953273e-49,8.621947e-41,2.444703e-33,...,0.703554,0.938072,0.0,12.0,229.0,217.0,120.500000,108.500000,12.0,"(Li+, Fe2+, Fe3+, O2-)"
159,mp-1279318,Li3FeO4,-5.370547,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...",[[ 3.44876738e+00 2.15699951e+00 -5.36130908e...,3.233877,5.531360e-248,1.479640e-224,2.667413e-202,3.240667e-181,...,0.263833,0.461707,0.0,12.0,229.0,217.0,120.500000,108.500000,12.0,"(Li0+, Fe0+, O0+)"

In [18]:
from matminer.featurizers.composition.ion import OxidationStates

os_feat = OxidationStates()
data = os_feat.featurize_dataframe(data,"composition_oxid",ignore_errors=True)
data

OxidationStates:   0%|          | 0/160 [00:00<?, ?it/s]

,material_id,pretty_formula,energy_per_atom,spacegroup,structure,density,xrd_0,xrd_1,xrd_2,xrd_3,...,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber,composition_oxid,minimum oxidation state,maximum oxidation state,range oxidation state,std_dev oxidation state
0,mp-756155,Li6FeO4,-5.117326,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[1.67125537 1.67346391 3.26141012] Li, [1.670...",2.566594,5.977826e-179,1.379972e-160,3.144998e-143,7.076099e-127,...,229.0,217.0,150.090909,100.429752,229.0,"(Li+, Fe2+, O2-)",-2.0,2.0,4.0,2.050825
1,mp-756856,Li5Fe7O12,-6.183322,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[0.74461757 4.34819314 2.48026726] Li, [-0.73...",4.516352,1.186238e-56,2.163227e-45,1.940292e-35,8.559855e-27,...,229.0,217.0,120.500000,108.500000,12.0,"(Li+, Fe2+, Fe3+, O2-)",-2.0,3.0,5.0,2.594255
2,mp-762529,Li2(FeO2)5,-5.740312,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[-0.35339594 3.48269285 3.02141686] Li, [ 2...",4.046393,1.552619e-78,1.175554e-66,8.898801e-56,6.734917e-46,...,229.0,217.0,101.352941,105.121107,12.0,"(Li0+, Fe0+, O0+)",0.0,0.0,0.0,0.000000
3,mp-18782,LiFeO2,-6.085931,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[0. 0. 4.377058] Li, [2.061247 0....",4.231705,0.000000e+00,0.000000e+00,9.881313e-322,3.397916e-293,...,229.0,217.0,120.500000,108.500000,12.0,"(Li+, Fe3+, O2-)",-2.0,3.0,5.0,2.683282
4,mp-756497,LiFeO2,-6.078770,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[3.04987747 3.81109335 4.24134412] Li, [3.013...",4.143655,3.678547e-82,1.400721e-69,4.517527e-58,1.234025e-47,...,229.0,217.0,120.500000,108.500000,12.0,"(Li+, Fe3+, O2-)",-2.0,3.0,5.0,2.683282
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,mp-1101736,LiFe3O4,-6.351436,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[-1.48982311 2.19943369 -1.43482144] Li, [-1...",5.018471,2.624011e-228,1.241719e-203,2.209240e-180,1.478050e-158,...,229.0,217.0,120.500000,108.500000,12.0,"(Li+, Fe2+, Fe3+, O2-)",-2.0,3.0,5.0,2.544836
156,mp-780216,Li5Fe3O8,-5.304033,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[ 1.33531488 -4.11912064 -0.49520662] Li, [-0...",3.757134,6.358424e-144,2.845674e-128,1.529721e-113,9.882739e-100,...,229.0,217.0,120.500000,108.500000,12.0,"(Li0+, Fe0+, O0+)",0.0,0.0,0.0,0.000000
157,mp-759394,Li2FeO3,-5.613536,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[1.244898 0. 4.9203229] Li, [1.244898...",3.651901,1.407637e-221,1.260348e-200,1.010579e-180,7.256715e-162,...,229.0,217.0,120.500000,108.500000,12.0,"(Li0+, Fe0+, O0+)",0.0,0.0,0.0,0.000000
158,mp-1314324,LiFe2O3,-6.267500,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[ 1.52274007 -2.68996763 3.71993333] Li, [ 3...",4.625861,4.635395e-58,4.953273e-49,8.621947e-41,2.444703e-33,...,229.0,217.0,120.500000,108.500000,12.0,"(Li+, Fe2+, Fe3+, O2-)",-2.0,3.0,5.0,2.549510
159,mp-1279318,Li3FeO4,-5.370547,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...",[[ 3.44876738e+00 2.15699951e+00 -5.36130908e...,3.233877,5.531360e-248,1.479640e-224,2.667413e-202,3.240667e-181,...,229.0,217.0,120.500000,108.500000,12.0,"(Li0+, Fe0+, O0+)",0.0,0.0,0.0,0.000000

In [19]:
data = data.drop(["density"],axis=1)
data

,material_id,pretty_formula,energy_per_atom,spacegroup,structure,xrd_0,xrd_1,xrd_2,xrd_3,xrd_4,...,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber,composition_oxid,minimum oxidation state,maximum oxidation state,range oxidation state,std_dev oxidation state
0,mp-756155,Li6FeO4,-5.117326,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[1.67125537 1.67346391 3.26141012] Li, [1.670...",5.977826e-179,1.379972e-160,3.144998e-143,7.076099e-127,1.571777e-111,...,229.0,217.0,150.090909,100.429752,229.0,"(Li+, Fe2+, O2-)",-2.0,2.0,4.0,2.050825
1,mp-756856,Li5Fe7O12,-6.183322,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[0.74461757 4.34819314 2.48026726] Li, [-0.73...",1.186238e-56,2.163227e-45,1.940292e-35,8.559855e-27,1.857379e-19,...,229.0,217.0,120.500000,108.500000,12.0,"(Li+, Fe2+, Fe3+, O2-)",-2.0,3.0,5.0,2.594255
2,mp-762529,Li2(FeO2)5,-5.740312,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[-0.35339594 3.48269285 3.02141686] Li, [ 2...",1.552619e-78,1.175554e-66,8.898801e-56,6.734917e-46,5.096179e-37,...,229.0,217.0,101.352941,105.121107,12.0,"(Li0+, Fe0+, O0+)",0.0,0.0,0.0,0.000000
3,mp-18782,LiFeO2,-6.085931,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[0. 0. 4.377058] Li, [2.061247 0....",0.000000e+00,0.000000e+00,9.881313e-322,3.397916e-293,7.084615e-266,...,229.0,217.0,120.500000,108.500000,12.0,"(Li+, Fe3+, O2-)",-2.0,3.0,5.0,2.683282
4,mp-756497,LiFeO2,-6.078770,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[3.04987747 3.81109335 4.24134412] Li, [3.013...",3.678547e-82,1.400721e-69,4.517527e-58,1.234025e-47,2.855097e-38,...,229.0,217.0,120.500000,108.500000,12.0,"(Li+, Fe3+, O2-)",-2.0,3.0,5.0,2.683282
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,mp-1101736,LiFe3O4,-6.351436,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[-1.48982311 2.19943369 -1.43482144] Li, [-1...",2.624011e-228,1.241719e-203,2.209240e-180,1.478050e-158,3.719262e-138,...,229.0,217.0,120.500000,108.500000,12.0,"(Li+, Fe2+, Fe3+, O2-)",-2.0,3.0,5.0,2.544836
156,mp-780216,Li5Fe3O8,-5.304033,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[ 1.33531488 -4.11912064 -0.49520662] Li, [-0...",6.358424e-144,2.845674e-128,1.529721e-113,9.882739e-100,7.678617e-87,...,229.0,217.0,120.500000,108.500000,12.0,"(Li0+, Fe0+, O0+)",0.0,0.0,0.0,0.000000
157,mp-759394,Li2FeO3,-5.613536,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[1.244898 0. 4.9203229] Li, [1.244898...",1.407637e-221,1.260348e-200,1.010579e-180,7.256715e-162,4.666737e-144,...,229.0,217.0,120.500000,108.500000,12.0,"(Li0+, Fe0+, O0+)",0.0,0.0,0.0,0.000000
158,mp-1314324,LiFe2O3,-6.267500,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[ 1.52274007 -2.68996763 3.71993333] Li, [ 3...",4.635395e-58,4.953273e-49,8.621947e-41,2.444703e-33,1.129157e-26,...,229.0,217.0,120.500000,108.500000,12.0,"(Li+, Fe2+, Fe3+, O2-)",-2.0,3.0,5.0,2.549510
159,mp-1279318,Li3FeO4,-5.370547,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...",[[ 3.44876738e+00 2.15699951e+00 -5.36130908e...,5.531360e-248,1.479640e-224,2.667413e-202,3.240667e-181,2.653312e-161,...,229.0,217.0,120.500000,108.500000,12.0,"(Li0+, Fe0+, O0+)",0.0,0.0,0.0,0.000000

In [20]:
from matminer.featurizers.structure import DensityFeatures

de_feat = DensityFeatures()
data = de_feat.featurize_dataframe(data,"structure")
data

DensityFeatures:   0%|          | 0/160 [00:00<?, ?it/s]

,material_id,pretty_formula,energy_per_atom,spacegroup,structure,xrd_0,xrd_1,xrd_2,xrd_3,xrd_4,...,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber,composition_oxid,minimum oxidation state,maximum oxidation state,range oxidation state,std_dev oxidation state,density,vpa,packing fraction
0,mp-756155,Li6FeO4,-5.117326,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[1.67125537 1.67346391 3.26141012] Li, [1.670...",5.977826e-179,1.379972e-160,3.144998e-143,7.076099e-127,1.571777e-111,...,100.429752,229.0,"(Li+, Fe2+, O2-)",-2.0,2.0,4.0,2.050825,2.566594,9.498197,0.877999
1,mp-756856,Li5Fe7O12,-6.183322,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[0.74461757 4.34819314 2.48026726] Li, [-0.73...",1.186238e-56,2.163227e-45,1.940292e-35,8.559855e-27,1.857379e-19,...,108.500000,12.0,"(Li+, Fe2+, Fe3+, O2-)",-2.0,3.0,5.0,2.594255,4.516352,9.461639,0.683311
2,mp-762529,Li2(FeO2)5,-5.740312,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[-0.35339594 3.48269285 3.02141686] Li, [ 2...",1.552619e-78,1.175554e-66,8.898801e-56,6.734917e-46,5.096179e-37,...,105.121107,12.0,"(Li0+, Fe0+, O0+)",0.0,0.0,0.0,0.000000,4.046393,10.937728,0.495092
3,mp-18782,LiFeO2,-6.085931,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[0. 0. 4.377058] Li, [2.061247 0....",0.000000e+00,0.000000e+00,9.881313e-322,3.397916e-293,7.084615e-266,...,108.500000,12.0,"(Li+, Fe3+, O2-)",-2.0,3.0,5.0,2.683282,4.231705,9.298489,0.701018
4,mp-756497,LiFeO2,-6.078770,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[3.04987747 3.81109335 4.24134412] Li, [3.013...",3.678547e-82,1.400721e-69,4.517527e-58,1.234025e-47,2.855097e-38,...,108.500000,12.0,"(Li+, Fe3+, O2-)",-2.0,3.0,5.0,2.683282,4.143655,9.496076,0.686432
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,mp-1101736,LiFe3O4,-6.351436,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[-1.48982311 2.19943369 -1.43482144] Li, [-1...",2.624011e-228,1.241719e-203,2.209240e-180,1.478050e-158,3.719262e-138,...,108.500000,12.0,"(Li+, Fe2+, Fe3+, O2-)",-2.0,3.0,5.0,2.544836,5.018471,9.863432,0.644696
156,mp-780216,Li5Fe3O8,-5.304033,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[ 1.33531488 -4.11912064 -0.49520662] Li, [-0...",6.358424e-144,2.845674e-128,1.529721e-113,9.882739e-100,7.678617e-87,...,108.500000,12.0,"(Li0+, Fe0+, O0+)",0.0,0.0,0.0,0.000000,3.757134,9.122119,0.723315
157,mp-759394,Li2FeO3,-5.613536,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[1.244898 0. 4.9203229] Li, [1.244898...",1.407637e-221,1.260348e-200,1.010579e-180,7.256715e-162,4.666737e-144,...,108.500000,12.0,"(Li0+, Fe0+, O0+)",0.0,0.0,0.0,0.000000,3.651901,8.921715,0.742542
158,mp-1314324,LiFe2O3,-6.267500,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...","[[ 1.52274007 -2.68996763 3.71993333] Li, [ 3...",4.635395e-58,4.953273e-49,8.621947e-41,2.444703e-33,1.129157e-26,...,108.500000,12.0,"(Li+, Fe2+, Fe3+, O2-)",-2.0,3.0,5.0,2.549510,4.625861,9.969109,0.643195
159,mp-1279318,Li3FeO4,-5.370547,"{'symprec': 0.1, 'source': 'spglib', 'symbol':...",[[ 3.44876738e+00 2.15699951e+00 -5.36130908e...,5.531360e-248,1.479640e-224,2.667413e-202,3.240667e-181,2.653312e-161,...,108.500000,12.0,"(Li0+, Fe0+, O0+)",0.0,0.0,0.0,0.000000,3.233877,9.028665,0.739635

In [21]:
from matminer.datasets import load_dataset

df = load_dataset("matbench_log_kvrh")
df

                                               structure  log10(K_VRH)
0      [[0. 0. 0.] Ca, [1.37728887 1.57871271 3.73949...      1.707570
1      [[3.14048493 1.09300401 1.64101398] Mg, [0.625...      1.633468
2      [[ 2.06884519  2.40627241 -0.45891585] Si, [1....      1.908485
3      [[2.06428082 0.         2.06428082] Pd, [0.   ...      2.117271
4      [[3.09635262 1.0689416  1.53602403] Mg, [0.593...      1.690196
...                                                  ...           ...
10982  [[0. 0. 0.] Rh, [3.2029368  3.2029368  2.09459...      1.778151
10983  [[-1.51157821  4.4173925   1.21553922] Mg, [3....      1.724276
10984  [[4.37546772 4.51128393 6.81784473] H, [0.4573...      1.342423
10985  [[0. 0. 0.] Si, [ 4.55195829  4.55195829 -4.55...      1.770852
10986  [[1.44565668 0.         2.05259079] Al, [1.445...      1.954243

[10987 rows x 2 columns]

In [ ]:
df_feat = DensityFeatures()
df = df_feat.featurize_dataframe(df,"structure")
df

DensityFeatures:   0%|          | 0/10987 [00:00<?, ?it/s]

In [ ]:
y = df['log10(K_VRH)'].values
y

In [ ]:
excluded = ["structure","log10(K_VRH)"]
features = df.drop(excluded,axis=1)
features

# 机器学习

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
lr = LinearRegression
lr.fit(features,y)

In [ ]:
from pymatgen.ext.matproj import MPRester
from pymatgen.apps.borg.hive import VaspToComputedEntryDrone
from pymatgen.apps.borg.queen import BorgQueen
from pymatgen.entries.compatibility import MaterialsProjectCompatibility
from pymatgen.analysis.phase_diagram import PhaseDiagram, PDPlotter

# Assimilate VASP calculations into ComputedEntry object. Let's assume that
# the calculations are for a series of new LixFeyOz phases that we want to
# know the phase stability.
drone = VaspToComputedEntryDrone()
queen = BorgQueen(drone, rootpath=".")
entries = queen.get_data()

# Obtain all existing Li-Fe-O phases using the Materials Project REST API
with MPRester("DxTbWWBsxEID35nq") as m:
    mp_entries = m.get_entries_in_chemsys(["Li", "Fe", "O"])

# Combined entry from calculated run with Materials Project entries
entries.extend(mp_entries)

# Process entries using the MaterialsProjectCompatibility
compat = MaterialsProjectCompatibility()
entries = compat.process_entries(entries)

# Generate and plot Li-Fe-O phase diagram
pd = PhaseDiagram(entries)
plotter = PDPlotter(pd)
plotter.show()