# 数据获取、特征生成dscribe、matminer、算法训练

In [1]:
import requests
import re
import os
import pandas as pd

C:\Users\10475\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\10475\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
C:\Users\10475\AppData\Local\Temp\ipykernel_13092\485201528.py:4: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
url = 'https://materialsdb.cn/2dsdb/index.html'
headers = {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0'}
resopnse = requests.get(url=url,headers=headers)
print(resopnse.text)

<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>2D Semiconductor Database &#8212; Materials Database  documentation</title>
    <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
    <link rel="stylesheet" href="../_static/pyramid.css" type="text/css" />
    <script id="documentation_options" data-url_root="../" src="../_static/documentation_options.js"></script>
    <script src="../_static/jquery.js"></script>
    <script src="../_static/underscore.js"></script>
    <script src="../_static/doctools.js"></script>
    <link rel="index" title="Index" href="../genindex.html" />
    <link rel="search" title="Search" href="../search.html" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Neuton&amp;subset=latin" type="text/css" media="screen" charset="utf-8" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nobile:regular,italic,bold,bolditalic&amp;subset=latin" type="text/css" media="screen" charset="utf-8" />
<!--[if lte IE 6]>
<link rel="stylesheet" href="../_static/ie6.css" type="text/css" media="screen" charset="utf-8" />
<![endif]-->

  </head><body>

    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="General Index"
             accesskey="I">index</a></li>
        <li class="nav-item nav-item-0"><a href="../index.html">Materials Database  documentation</a> &#187;</li>
        <li class="nav-item nav-item-this"><a href="">2D Semiconductor Database</a></li>
      </ul>
    </div>

    <div class="document">
      <div class="documentwrapper">
        <div class="bodywrapper">
          <div class="body" role="main">

  <div class="section" id="d-semiconductor-database">
<h1>2D Semiconductor Database<a class="headerlink" href="#d-semiconductor-database" title="Permalink to this headline">¶</a></h1>
<p>The database contains structural, elastic, electronic, thermodynamic, and optical properties of around 270 two-dimensional semiconductors. The workflow for the calculation of the different properties is provided below.</p>
<a class="reference internal image-reference" href="../_images/workflow.png"><img alt="../_images/workflow.png" class="align-center" src="../_images/workflow.png" style="width: 400px;" /></a>
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>If you are using data from this database in your research, please cite the following paper:</p>
<p>[1] V. Wang, G. Tang, Y.-C. Liu, R.-T. Wang, H. Mizuseki, Y. Kawazeo, J. Nara, W.-T. Geng, High-Throughput Computational Screening of Two-Dimensional Semiconductors, <a class="reference external" href="https://doi.org/10.1021/acs.jpclett.2c02972">Journal of Physical Chemistry Letters 13, 11581 (2022).</a></p>
</div>
</div>
<div class="section" id="list-of-data">
<h1>List of Data<a class="headerlink" href="#list-of-data" title="Permalink to this headline">¶</a></h1>
<div class="admonition caution">
<p class="admonition-title">Caution</p>
<p>The data were generated by automated first-principles DFT calculations. Basically these data in every entry are not well examined and some might be wrong. Please report the abnormal data to <a class="reference external" href="mailto:wangvei&#37;&#52;&#48;icloud&#46;com">wangvei<span>&#64;</span>icloud<span>&#46;</span>com</a>.</p>
</div>
<ul class="simple">
<li><p>Prototype: [ <strong>A</strong> ]</p>
<ul>
<li><p><a class="reference external" href="As_P21-m.html">As - P21-m</a></p></li>
<li><p><a class="reference external" href="As_P-3m1.html">As - P-3m1</a></p></li>
<li><p><a class="reference external" href="As_Pca21.html">As - Pca21</a></p></li>
<li><p><a class="reference external" href="As_Pmn2_1.html">As - Pmn2</a></p></li>
<li><p><a class="reference external" href="As_Pmna.html">As - Pmna</a></p></li>
<li><p><a class="reference external" href="C_P6^mmm.html">C - P6/mmm</a></p></li>
<li><p><a class="reference external" href="Ge_P-3m1.html">Ge - P-3m1</a></p></li>
<li><p><a class="reference external" href="P_P21-m.html">P - P21-m</a></p></li>
<li><p><a class="reference external" href="P_Pca21.html">P - Pca21</a></p></li>
<li><p><a class="reference external" href="P_Pmna.html">P - Pmna</a></p></li>
<li><p><a class="reference external" href="Si_P-3m1.html">Si - P-3m1</a></p></li>
</ul>
</li>
<li><p>Prototype: [ <strong>AB</strong> ]</p>
<ul>
<li><p><a class="reference external" href="AlN_P-6m2.html">AlN - P-6m2</a></p></li>
<li><p><a class="reference external" href="AuSe_P2^m.html">AuSe - P2/m</a></p></li>
<li><p><a class="reference external" href="BN_P-6m2.html">BN - P-6m2</a></p></li>
<li><p><a class="reference external" href="GaN_P-6m2.html">GaN - P-6m2</a></p></li>
<li><p><a class="reference external" href="GaSe_P-6m2.html">GaSe - P-6m2</a></p></li>
<li><p><a class="reference external" href="GaS_P-3m1.html">GaS - P-3m1</a></p></li>
<li><p><a class="reference external" href="GaS_P-6m2.html">GaS - P-6m2</a></p></li>
<li><p><a class="reference external" href="GeAs_P-6m2.html">GeAs - P-6m2</a></p></li>
<li><p><a class="reference external" href="GeP_P-6m2.html">GeP - P-6m2</a></p></li>
<li><p><a class="reference external" href="GeSe_Pmn2_1.html">GeSe - Pmn2</a></p></li>
<li><p><a class="reference external" href="InN_P-6m2.html">InN - P-6m2</a></p></li>
<li><p><a class="reference external" href="InSe_P3m1.html">InSe - P3m1</a></p></li>
<li><p><a class="reference external" href="PbS_Aem2.html">PbS - Aem2</a></p></li>
<li><p><a class="reference external" href="SiAs_P-6m2.html">SiAs - P-6m2</a></p></li>
<li><p><a class="reference external" href="SiH_P-3m1.html">SiH - P-3m1</a></p></li>
<li><p><a class="reference external" href="SiP_P-6m2.html">SiP - P-6m2</a></p></li>
<li><p><a class="reference external" href="SiSb_P-6m2.html">SiSb - P-6m2</a></p></li>
<li><p><a class="reference external" href="SnAs_P-6m2.html">SnAs - P-6m2</a></p></li>
<li><p><a class="reference external" href="SnO_P4^nmm.html">SnO - P4/nmm</a></p></li>
<li><p><a class="reference external" href="SnO_Pmmn.html">SnO - Pmmn</a></p></li>
<li><p><a class="reference external" href="SnP_P-6m2.html">SnP - P-6m2</a></p></li>
<li><p><a class="reference external" href="SnSe_Pmn2_1.html">SnSe - Pmn2</a></p></li>
<li><p><a class="reference external" href="SnS_Pmn2_1.html">SnS - Pmn2</a></p></li>
<li><p><a class="reference external" href="TlF_Pbcm.html">TlF - Pbcm</a></p></li>
</ul>
</li>
<li><p>Prototype: [ <strong>AB2</strong> ]</p>
<ul>
<li><p><a class="reference external" href="BaO2_P4^mmm.html">BaO2 - P4/mmm</a></p></li>
<li><p><a class="reference external" href="BrTe2_Pmn2_1.html">BrTe2 - Pmn2</a></p></li>
<li><p><a class="reference external" href="CdBr2_P-3m1.html">CdBr2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="CdCl2_P-1.html">CdCl2 - P-1</a></p></li>
<li><p><a class="reference external" href="CdCl2_P-3m1.html">CdCl2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="CrO2_P-6m2.html">CrO2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="CrS2_P-6m2.html">CrS2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="CrSe2_P-6m2.html">CrSe2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="FeS2_P2_1^m.html">FeS2 - P2</a></p></li>
<li><p><a class="reference external" href="FeSe2_P2_1^m.html">FeSe2 - P2</a></p></li>
<li><p><a class="reference external" href="FeTe2_P2_1^m.html">FeTe2 - P2</a></p></li>
<li><p><a class="reference external" href="GeAs2_Pmc2_1.html">GeAs2 - Pmc2</a></p></li>
<li><p><a class="reference external" href="GeI2_P-3m1.html">GeI2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="GeO2_P2_1^m.html">GeO2 - P2</a></p></li>
<li><p><a class="reference external" href="GeO2_P-3m1.html">GeO2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="GeS2_P2_1^m.html">GeS2 - P2</a></p></li>
<li><p><a class="reference external" href="HfO2_P2_1^m.html">HfO2 - P2</a></p></li>
<li><p><a class="reference external" href="HfS2_P2_1^m.html">HfS2 - P2</a></p></li>
<li><p><a class="reference external" href="HfS2_P-3m1.html">HfS2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="HfSe2_P2_1^m.html">HfSe2 - P2</a></p></li>
<li><p><a class="reference external" href="HfSe2_P-3m1.html">HfSe2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="HfTe2_P2_1^m.html">HfTe2 - P2</a></p></li>
<li><p><a class="reference external" href="HfTe2_P-3m1.html">HfTe2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="HgBr2_Cm.html">HgBr2 - Cm</a></p></li>
<li><p><a class="reference external" href="MgBr2_P-3m1.html">MgBr2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="MgCl2_P-3m1.html">MgCl2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="MoO2_P-6m2.html">MoO2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="MoS2_P2_1^m.html">MoS2 - P2</a></p></li>
<li><p><a class="reference external" href="MoS2_P-6m2.html">MoS2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="MoSe2_P2_1^m.html">MoSe2 - P2</a></p></li>
<li><p><a class="reference external" href="MoSe2_P-6m2.html">MoSe2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="MoTe2_P-6m2.html">MoTe2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="NiO2_P2_1^m.html">NiO2 - P2</a></p></li>
<li><p><a class="reference external" href="NiS2_P2_1^m.html">NiS2 - P2</a></p></li>
<li><p><a class="reference external" href="NiS2_P-3m1.html">NiS2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="NiSe2_P2_1^m.html">NiSe2 - P2</a></p></li>
<li><p><a class="reference external" href="NiSe2_P-3m1.html">NiSe2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="NiTe2_P2_1^m.html">NiTe2 - P2</a></p></li>
<li><p><a class="reference external" href="OsO2_P2_1^m.html">OsO2 - P2</a></p></li>
<li><p><a class="reference external" href="OsS2_P2_1^m.html">OsS2 - P2</a></p></li>
<li><p><a class="reference external" href="OsSe2_P2_1^m.html">OsSe2 - P2</a></p></li>
<li><p><a class="reference external" href="PbI2_P-3m1.html">PbI2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="PbO2_P2_1^m.html">PbO2 - P2</a></p></li>
<li><p><a class="reference external" href="PbO2_P-3m1.html">PbO2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="PbS2_P2_1^m.html">PbS2 - P2</a></p></li>
<li><p><a class="reference external" href="PbSe2_P2_1^m.html">PbSe2 - P2</a></p></li>
<li><p><a class="reference external" href="PdO2_P2_1^m.html">PdO2 - P2</a></p></li>
<li><p><a class="reference external" href="PdO2_P-3m1.html">PdO2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="PdS2_P2_1^c.html">PdS2 - P2</a></p></li>
<li><p><a class="reference external" href="PdS2_P2_1^m.html">PdS2 - P2</a></p></li>
<li><p><a class="reference external" href="PdS2_P-3m1.html">PdS2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="PdSe2_P2_1^c.html">PdSe2 - P2</a></p></li>
<li><p><a class="reference external" href="PdSe2_P2_1^m.html">PdSe2 - P2</a></p></li>
<li><p><a class="reference external" href="PdSe2_P-3m1.html">PdSe2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="PdTe2_P2_1^m.html">PdTe2 - P2</a></p></li>
<li><p><a class="reference external" href="PdTe2_P-3m1.html">PdTe2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="PtI2_P2_1^c.html">PtI2 - P2</a></p></li>
<li><p><a class="reference external" href="PtO2_P2_1^m.html">PtO2 - P2</a></p></li>
<li><p><a class="reference external" href="PtO2_P-3m1.html">PtO2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="PtS2_P2_1^m.html">PtS2 - P2</a></p></li>
<li><p><a class="reference external" href="PtS2_P-3m1.html">PtS2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="PtSe2_P2_1^m.html">PtSe2 - P2</a></p></li>
<li><p><a class="reference external" href="PtSe2_P-3m1.html">PtSe2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="PtTe2_P2_1^m.html">PtTe2 - P2</a></p></li>
<li><p><a class="reference external" href="PtTe2_P-3m1.html">PtTe2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="RuO2_P2_1^m.html">RuO2 - P2</a></p></li>
<li><p><a class="reference external" href="RuS2_P2_1^m.html">RuS2 - P2</a></p></li>
<li><p><a class="reference external" href="RuSe2_P2_1^m.html">RuSe2 - P2</a></p></li>
<li><p><a class="reference external" href="RuTe2_P2_1^m.html">RuTe2 - P2</a></p></li>
<li><p><a class="reference external" href="SiAs2_Pmc2_1.html">SiAs2 - Pmc2</a></p></li>
<li><p><a class="reference external" href="SiO2_P6^mmm.html">SiO2 - P6/mmm</a></p></li>
<li><p><a class="reference external" href="SiO2_Pm.html">SiO2 - Pm</a></p></li>
<li><p><a class="reference external" href="SiP2_Pmc2_1.html">SiP2 - Pmc2</a></p></li>
<li><p><a class="reference external" href="SnO2_P1.html">SnO2 - P1</a></p></li>
<li><p><a class="reference external" href="SnO2_P2_1^m.html">SnO2 - P2</a></p></li>
<li><p><a class="reference external" href="SnO2_P-3m1.html">SnO2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="SnS2_P2_1^m.html">SnS2 - P2</a></p></li>
<li><p><a class="reference external" href="SnS2_P-3m1.html">SnS2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="SnSe2_P2_1^m.html">SnSe2 - P2</a></p></li>
<li><p><a class="reference external" href="SnSe2_P-3m1.html">SnSe2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="SrO2_P4^mmm.html">SrO2 - P4/mmm</a></p></li>
<li><p><a class="reference external" href="Te2Br_Pmn2_1.html">Te2Br - Pmn2</a></p></li>
<li><p><a class="reference external" href="Te2Mo_P-6m2.html">Te2Mo - P-6m2</a></p></li>
<li><p><a class="reference external" href="Te2Pd_P-3m1.html">Te2Pd - P-3m1</a></p></li>
<li><p><a class="reference external" href="Te2Pt_P-3m1.html">Te2Pt - P-3m1</a></p></li>
<li><p><a class="reference external" href="TiO2_P2_1^m.html">TiO2 - P2</a></p></li>
<li><p><a class="reference external" href="TiSe2_P-6m2.html">TiSe2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="WO2_P-6m2.html">WO2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="WS2_P2_1^m.html">WS2 - P2</a></p></li>
<li><p><a class="reference external" href="WS2_P-6m2.html">WS2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="WSe2_P2_1^m.html">WSe2 - P2</a></p></li>
<li><p><a class="reference external" href="WSe2_P-6m2.html">WSe2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="WTe2_P-6m2.html">WTe2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="ZnCl2_P-4m2.html">ZnCl2 - P-4m2</a></p></li>
<li><p><a class="reference external" href="ZrCl2_P-6m2.html">ZrCl2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="ZrI2_P2_1^m.html">ZrI2 - P2</a></p></li>
<li><p><a class="reference external" href="ZrO2_P2_1^m.html">ZrO2 - P2</a></p></li>
<li><p><a class="reference external" href="ZrO2_P-3m1.html">ZrO2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="ZrS2_P2_1^m.html">ZrS2 - P2</a></p></li>
<li><p><a class="reference external" href="ZrS2_P-3m1.html">ZrS2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="ZrSe2_P2_1^m.html">ZrSe2 - P2</a></p></li>
<li><p><a class="reference external" href="ZrSe2_P-3m1.html">ZrSe2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="ZrTe2_P-6m2.html">ZrTe2 - P-6m2</a></p></li>
</ul>
</li>
<li><p>Prototype: [ <strong>AB3</strong> ]</p>
<ul>
<li><p><a class="reference external" href="AlCl3_C2^m.html">AlCl3 - C2/m</a></p></li>
<li><p><a class="reference external" href="BiBr3_P2_1^c.html">BiBr3 - P2</a></p></li>
<li><p><a class="reference external" href="DyCl3_Pmmn.html">DyCl3 - Pmmn</a></p></li>
<li><p><a class="reference external" href="GdBr3_P-1.html">GdBr3 - P-1</a></p></li>
<li><p><a class="reference external" href="HfS3_P2_1^m.html">HfS3 - P2</a></p></li>
<li><p><a class="reference external" href="HfSe3_P2_1^m.html">HfSe3 - P2</a></p></li>
<li><p><a class="reference external" href="InBr3_C2^m.html">InBr3 - C2/m</a></p></li>
<li><p><a class="reference external" href="IrBr3_C2^m.html">IrBr3 - C2/m</a></p></li>
<li><p><a class="reference external" href="IrCl3_C2^m.html">IrCl3 - C2/m</a></p></li>
<li><p><a class="reference external" href="LaI3_Pmmn.html">LaI3 - Pmmn</a></p></li>
<li><p><a class="reference external" href="MoO3_P2_1^m.html">MoO3 - P2</a></p></li>
<li><p><a class="reference external" href="NdBr3_Pmmn.html">NdBr3 - Pmmn</a></p></li>
<li><p><a class="reference external" href="RhBr3_C2^m.html">RhBr3 - C2/m</a></p></li>
<li><p><a class="reference external" href="ScCl3_P-3.html">ScCl3 - P-3</a></p></li>
<li><p><a class="reference external" href="Si3H_P-3m1.html">Si3H - P-3m1</a></p></li>
<li><p><a class="reference external" href="SmBr3_Pmmn.html">SmBr3 - Pmmn</a></p></li>
<li><p><a class="reference external" href="TaSe3_P2_1^m.html">TaSe3 - P2</a></p></li>
<li><p><a class="reference external" href="TbCl3_Pmmn.html">TbCl3 - Pmmn</a></p></li>
<li><p><a class="reference external" href="TiS3_P2_1^m.html">TiS3 - P2</a></p></li>
<li><p><a class="reference external" href="YBr3_C2^m.html">YBr3 - C2/m</a></p></li>
<li><p><a class="reference external" href="YI3_P-3.html">YI3 - P-3</a></p></li>
<li><p><a class="reference external" href="ZrS3_P2_1^m.html">ZrS3 - P2</a></p></li>
<li><p><a class="reference external" href="ZrSe3_P2_1^m.html">ZrSe3 - P2</a></p></li>
</ul>
</li>
<li><p>Prototype: [ <strong>AmBn</strong> ]</p>
<ul>
<li><p><a class="reference external" href="Al2Te3_P2_1^c.html">Al2Te3 - P2</a></p></li>
<li><p><a class="reference external" href="V2O5_Pmmn.html">V2O5 - Pmmn</a></p></li>
<li><p><a class="reference external" href="ZrTe5_Pmmn.html">ZrTe5 - Pmmn</a></p></li>
</ul>
</li>
<li><p>Prototype: [ <strong>ABC</strong> ]</p>
<ul>
<li><p><a class="reference external" href="AlClO_Pmmn.html">AlClO - Pmmn</a></p></li>
<li><p><a class="reference external" href="BaBrCl_P2_1^m.html">BaBrCl - P2</a></p></li>
<li><p><a class="reference external" href="BaIF_P4^nmm.html">BaIF - P4/nmm</a></p></li>
<li><p><a class="reference external" href="BiBrO_P4^nmm.html">BiBrO - P4/nmm</a></p></li>
<li><p><a class="reference external" href="BiClO_P4^nmm.html">BiClO - P4/nmm</a></p></li>
<li><p><a class="reference external" href="BiOF_P-3m1.html">BiOF - P-3m1</a></p></li>
<li><p><a class="reference external" href="BiTeCl_P3m1.html">BiTeCl - P3m1</a></p></li>
<li><p><a class="reference external" href="CaClF_P4^nmm.html">CaClF - P4/nmm</a></p></li>
<li><p><a class="reference external" href="CaHBr_P4^nmm.html">CaHBr - P4/nmm</a></p></li>
<li><p><a class="reference external" href="CaHI_P4^nmm.html">CaHI - P4/nmm</a></p></li>
<li><p><a class="reference external" href="DySBr_Pmmn.html">DySBr - Pmmn</a></p></li>
<li><p><a class="reference external" href="DySI_Pmmn.html">DySI - Pmmn</a></p></li>
<li><p><a class="reference external" href="ErSCl_Pmmn.html">ErSCl - Pmmn</a></p></li>
<li><p><a class="reference external" href="ErSeI_Pmmn.html">ErSeI - Pmmn</a></p></li>
<li><p><a class="reference external" href="GaTeCl_Pmn2_1.html">GaTeCl - Pmn2</a></p></li>
<li><p><a class="reference external" href="GdBrO_P4^nmm.html">GdBrO - P4/nmm</a></p></li>
<li><p><a class="reference external" href="HfBrN_P-3m1.html">HfBrN - P-3m1</a></p></li>
<li><p><a class="reference external" href="HfBrN_Pmmn.html">HfBrN - Pmmn</a></p></li>
<li><p><a class="reference external" href="HfIN_P-3m1.html">HfIN - P-3m1</a></p></li>
<li><p><a class="reference external" href="HfNCl_P-3m1.html">HfNCl - P-3m1</a></p></li>
<li><p><a class="reference external" href="HoBrO_P-3m1.html">HoBrO - P-3m1</a></p></li>
<li><p><a class="reference external" href="InBrO_Pmmn.html">InBrO - Pmmn</a></p></li>
<li><p><a class="reference external" href="InClO_Pmmn.html">InClO - Pmmn</a></p></li>
<li><p><a class="reference external" href="KMgSb_P4^nmm.html">KMgSb - P4/nmm</a></p></li>

In [3]:
<li><p><a class="reference external" href="As_P21-m.html">As - P21-m</a></p></li>
<li><p><a class="reference external" href="As_P-3m1.html">As - P-3m1</a></p></li>
<li><p><a class="reference external" href="As_Pca21.html">As - Pca21</a></p></li>
<li><p><a class="reference external" href="As_Pmn2_1.html">As - Pmn2</a></p></li>
<li><p><a class="reference external" href="As_Pmna.html">As - Pmna</a></p></li>
<li><p><a class="reference external" href="C_P6^mmm.html">C - P6/mmm</a></p></li>

SyntaxError: invalid syntax (3969412432.py, line 1)

In [ ]:
html_data = re.findall('<li><p><a class="reference external" href="(.*?)">(.*?)</a></p></li>',resopnse.text)
print(html_data)

In [ ]:
print(len(html_data))

In [ ]:
from bs4 import BeautifulSoup

materials_url = f'https://materialsdb.cn/2dsdb/index.html'
response = requests.get(materials_url)
soup = BeautifulSoup(resopnse.content,'html.parser')
print(soup)

In [ ]:
paragraphs = [p.text for p in soup.find_all('p')]
paragraphs

In [ ]:
filename = 'materials\\'
if not os.path.exists(filename):
    os.mkdir(filename)

In [ ]:
for num_id in html_data:
    material_id_url = f'https://materialsdb.cn/2dsdb/{num_id[0]}'
    material_content = requests.get(url = material_id_url,headers = headers).content
    print("当前获取：",num_id[0])
    with open('materials\\' + num_id[0] + '.json',mode = 'wb') as f:
        f.write(material_content)

In [20]:
filename = 'graph\\'
if not os.path.exists(filename):
    os.mkdir(filename)

In [41]:
for num_id in html_data:
    idd = num_id[0]
    idd = idd.split('.')[0]
    material_id_url = f'https://materialsdb.cn/_images/BAND_LDOS-{idd}.png'
    material_content = requests.get(url = material_id_url,headers = headers).content
    print("当前获取：",idd)
    with open('graph\\' + idd + '.png',mode = 'wb') as f:
        f.write(material_content)

当前获取： As_P21-m
当前获取： As_P-3m1
当前获取： As_Pca21
当前获取： As_Pmn2_1
当前获取： As_Pmna
当前获取： C_P6^mmm
当前获取： Ge_P-3m1
当前获取： P_P21-m
当前获取： P_Pca21
当前获取： P_Pmna
当前获取： Si_P-3m1
当前获取： AlN_P-6m2
当前获取： AuSe_P2^m
当前获取： BN_P-6m2
当前获取： GaN_P-6m2
当前获取： GaSe_P-6m2
当前获取： GaS_P-3m1
当前获取： GaS_P-6m2
当前获取： GeAs_P-6m2
当前获取： GeP_P-6m2
当前获取： GeSe_Pmn2_1
当前获取： InN_P-6m2
当前获取： InSe_P3m1
当前获取： PbS_Aem2
当前获取： SiAs_P-6m2
当前获取： SiH_P-3m1
当前获取： SiP_P-6m2
当前获取： SiSb_P-6m2
当前获取： SnAs_P-6m2
当前获取： SnO_P4^nmm
当前获取： SnO_Pmmn
当前获取： SnP_P-6m2
当前获取： SnSe_Pmn2_1
当前获取： SnS_Pmn2_1
当前获取： TlF_Pbcm
当前获取： BaO2_P4^mmm
当前获取： BrTe2_Pmn2_1
当前获取： CdBr2_P-3m1
当前获取： CdCl2_P-1
当前获取： CdCl2_P-3m1
当前获取： CrO2_P-6m2
当前获取： CrS2_P-6m2
当前获取： CrSe2_P-6m2
当前获取： FeS2_P2_1^m
当前获取： FeSe2_P2_1^m
当前获取： FeTe2_P2_1^m
当前获取： GeAs2_Pmc2_1
当前获取： GeI2_P-3m1
当前获取： GeO2_P2_1^m
当前获取： GeO2_P-3m1
当前获取： GeS2_P2_1^m
当前获取： HfO2_P2_1^m
当前获取： HfS2_P2_1^m
当前获取： HfS2_P-3m1
当前获取： HfSe2_P2_1^m
当前获取： HfSe2_P-3m1
当前获取： HfTe2_P2_1^m
当前获取： HfTe2_P-3m1
当前获取： HgBr2_Cm
当前获取： MgBr2_P-3m1
当前获取： MgCl2_P-3m1
当前获取： MoO2_P-6m2
当前获取： MoS2_P2_1^m
当前获取： MoS2_P-6m2
当前获取： MoSe2_P2_1^m
当前获取： MoSe2_P-6m2
当前获取： MoTe2_P-6m2
当前获取： NiO2_P2_1^m
当前获取： NiS2_P2_1^m
当前获取： NiS2_P-3m1
当前获取： NiSe2_P2_1^m
当前获取： NiSe2_P-3m1
当前获取： NiTe2_P2_1^m
当前获取： OsO2_P2_1^m
当前获取： OsS2_P2_1^m
当前获取： OsSe2_P2_1^m
当前获取： PbI2_P-3m1
当前获取： PbO2_P2_1^m
当前获取： PbO2_P-3m1
当前获取： PbS2_P2_1^m
当前获取： PbSe2_P2_1^m
当前获取： PdO2_P2_1^m
当前获取： PdO2_P-3m1
当前获取： PdS2_P2_1^c
当前获取： PdS2_P2_1^m
当前获取： PdS2_P-3m1
当前获取： PdSe2_P2_1^c
当前获取： PdSe2_P2_1^m
当前获取： PdSe2_P-3m1
当前获取： PdTe2_P2_1^m
当前获取： PdTe2_P-3m1
当前获取： PtI2_P2_1^c
当前获取： PtO2_P2_1^m
当前获取： PtO2_P-3m1
当前获取： PtS2_P2_1^m
当前获取： PtS2_P-3m1
当前获取： PtSe2_P2_1^m
当前获取： PtSe2_P-3m1
当前获取： PtTe2_P2_1^m
当前获取： PtTe2_P-3m1
当前获取： RuO2_P2_1^m
当前获取： RuS2_P2_1^m
当前获取： RuSe2_P2_1^m
当前获取： RuTe2_P2_1^m
当前获取： SiAs2_Pmc2_1
当前获取： SiO2_P6^mmm
当前获取： SiO2_Pm
当前获取： SiP2_Pmc2_1
当前获取： SnO2_P1
当前获取： SnO2_P2_1^m
当前获取： SnO2_P-3m1
当前获取： SnS2_P2_1^m
当前获取： SnS2_P-3m1
当前获取： SnSe2_P2_1^m
当前获取： SnSe2_P-3m1
当前获取： SrO2_P4^mmm
当前获取： Te2Br_Pmn2_1
当前获取： Te2Mo_P-6m2
当前获取： Te2Pd_P-3m1
当前获取： Te2Pt_P-3m1
当前获取： TiO2_P2_1^m
当前获取： TiSe2_P-6m2
当前获取： WO2_P-6m2
当前获取： WS2_P2_1^m
当前获取： WS2_P-6m2
当前获取： WSe2_P2_1^m
当前获取： WSe2_P-6m2
当前获取： WTe2_P-6m2
当前获取： ZnCl2_P-4m2
当前获取： ZrCl2_P-6m2
当前获取： ZrI2_P2_1^m
当前获取： ZrO2_P2_1^m
当前获取： ZrO2_P-3m1
当前获取： ZrS2_P2_1^m
当前获取： ZrS2_P-3m1
当前获取： ZrSe2_P2_1^m
当前获取： ZrSe2_P-3m1
当前获取： ZrTe2_P-6m2
当前获取： AlCl3_C2^m
当前获取： BiBr3_P2_1^c
当前获取： DyCl3_Pmmn
当前获取： GdBr3_P-1
当前获取： HfS3_P2_1^m
当前获取： HfSe3_P2_1^m
当前获取： InBr3_C2^m
当前获取： IrBr3_C2^m
当前获取： IrCl3_C2^m
当前获取： LaI3_Pmmn
当前获取： MoO3_P2_1^m
当前获取： NdBr3_Pmmn
当前获取： RhBr3_C2^m
当前获取： ScCl3_P-3
当前获取： Si3H_P-3m1
当前获取： SmBr3_Pmmn
当前获取： TaSe3_P2_1^m
当前获取： TbCl3_Pmmn
当前获取： TiS3_P2_1^m
当前获取： YBr3_C2^m
当前获取： YI3_P-3
当前获取： ZrS3_P2_1^m
当前获取： ZrSe3_P2_1^m
当前获取： Al2Te3_P2_1^c
当前获取： V2O5_Pmmn
当前获取： ZrTe5_Pmmn
当前获取： AlClO_Pmmn
当前获取： BaBrCl_P2_1^m
当前获取： BaIF_P4^nmm
当前获取： BiBrO_P4^nmm
当前获取： BiClO_P4^nmm
当前获取： BiOF_P-3m1
当前获取： BiTeCl_P3m1
当前获取： CaClF_P4^nmm
当前获取： CaHBr_P4^nmm
当前获取： CaHI_P4^nmm
当前获取： DySBr_Pmmn
当前获取： DySI_Pmmn
当前获取： ErSCl_Pmmn
当前获取： ErSeI_Pmmn
当前获取： GaTeCl_Pmn2_1
当前获取： GdBrO_P4^nmm
当前获取： HfBrN_P-3m1
当前获取： HfBrN_Pmmn
当前获取： HfIN_P-3m1
当前获取： HfNCl_P-3m1
当前获取： HoBrO_P-3m1
当前获取： InBrO_Pmmn
当前获取： InClO_Pmmn
当前获取： KMgSb_P4^nmm
当前获取： KTlO_P2_1^m
当前获取： LaIO_P4^nmm
当前获取： LuSBr_Pmmn
当前获取： NaZnP_P4^nmm
当前获取： NdBrO_P4^nmm
当前获取： NdIO_P4^nmm
当前获取： PbClF_P4^nmm
当前获取： PbIF_P4^nmm
当前获取： PPdSe_P2^c
当前获取： PPdS_P2^c
当前获取： PrBrO_P-3m1
当前获取： PrIO_P4^nmm
当前获取： RbLiSe_P4^nmm
当前获取： RbLiS_P4^nmm
当前获取： SbSeI_Pmn2_1
当前获取： ScBrO_Pmmn
当前获取： ScIO_P2_1^m
当前获取： SmBrO_P4^nmm
当前获取： SrHBr_P4^nmm
当前获取： SrHI_P4^nmm
当前获取： SrIF_P4^nmm
当前获取： TeBiBr_P3m1
当前获取： TeRhCl_P2_1^m
当前获取： TiBrN_Pmmn
当前获取： TiNCl_Pmmn
当前获取： TmBrO_P4^nmm
当前获取： YBrO_P-3m1
当前获取： YBrO_P4^nmm
当前获取： YIO_P4^nmm
当前获取： ZrBrN_Pmmn
当前获取： ZrNCl_P-3m1
当前获取： AuClO2_P222_1
当前获取： CuHO2_Pmn2_1
当前获取： CuSe2Br_P2_1
当前获取： CuSe2Cl_P2_1
当前获取： CuTe2Br_P2_1
当前获取： LiBiO2_Pbcm
当前获取： TaI2O_P2^m
当前获取： CdPS3_C2^m
当前获取： CdPS3_P-3
当前获取： MgPSe3_P-3
当前获取： PdSeO3_P2_1^m
当前获取： TiPbO3_P4mm
当前获取： TlSbO3_P-31m
当前获取： Al2Mg2Se5_P-3m1
当前获取： As2SO6_P2_12_12
当前获取： Ba4Sb2O_P4^mmm
当前获取： BaCaI4_P2^m
当前获取： BaTe2O6_Pmma
当前获取： Bi2Pb2Se5_P-3m1
当前获取： Bi2Te2S_P-3m1
当前获取： CaPbI4_P2^m
当前获取： CdPS3_C2^m
当前获取： CdPS3_P-3
当前获取： GeY2I2_P-3m1
当前获取： HfTeSe4_P2^m
当前获取： K4HgAs2_P-3m1
当前获取： Li2CeAs2_P-3m1
当前获取： Li2S4W_P-42m
当前获取： Lu2CCl2_P-3m1
当前获取： MgAl2S4_P-3m1
当前获取： MgPSe3_P-3
当前获取： Na4CdP2_P3m1
当前获取： Nb3SBr7_P3m1
当前获取： Nb3TeCl7_P3m1
当前获取： NiTa2S5_Pmmn
当前获取： Pd3P2S8_P-3m1
当前获取： PdSeO3_P2_1^m
当前获取： Rb2Pd3S4_P6^mmm
当前获取： RbBrF4_P4^mbm
当前获取： Sb2Ge2Te5_P-3m1
当前获取： Sb2Te2Se_P-3m1
当前获取： Sb4S5Cl2_P2_1^m
当前获取： Sc2CCl2_P-3m1
当前获取： SnP2S6_P312
当前获取： Ta3SBr7_Cm
当前获取： TaTe4Ir_P2_1^m
当前获取： TiPbO3_P4mm
当前获取： TlPd2Se3_P-3m1
当前获取： TlPt2S3_P-3m1
当前获取： TlSbO3_P-31m
当前获取： TlTe3Pt2_P-3m1
当前获取： VPO5_P4^n
当前获取： WCu2S4_P-42m
当前获取： ZnAs2O4_P2_1
当前获取： ZnIn2S4_P2^m

In [64]:
fe = 'https://materialsdb.cn/2dsdb/P_P21-m.html'
response = requests.get(url = fe)
soup = BeautifulSoup(response.content,'html.parser')
title = soup.title.string
materials_formation_energy = [p.text for p in soup.find_all('p')]
print(materials_formation_energy[14])

0.1949

In [52]:
import requests
import re
import os
import pandas as pd
from bs4 import BeautifulSoup

url = 'https://materialsdb.cn/2dsdb/index.html?'
headers = {
	'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.69'
}
response = requests.get(url=url, headers=headers)
print(response.text)

html_data = re.findall('<li><p><a class="reference external" href="(.*?).html">(.*?)</a></p></li>', response.text)
print(html_data)

filename = 'materials\\'
if not os.path.exists(filename):
	os.mkdir(filename)

materials_id = []
space_group = []
for num_id in html_data:
	materials_num = re.sub(r'\^', '/', str(num_id[0]))
	materials_id.append(materials_num)

	num = re.sub(r'\^', '%5E', str(num_id[0]))

	materials_url = f'https://materialsdb.cn/2dsdb/{num}.html'
	response = requests.get(materials_url)
	soup = BeautifulSoup(response.content, 'html.parser')
	title = soup.title.string
	paragraphs = [p.text for p in soup.find_all('p')]
	space_group.append(paragraphs[12])
	print(space_group)

<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>2D Semiconductor Database &#8212; Materials Database  documentation</title>
    <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
    <link rel="stylesheet" href="../_static/pyramid.css" type="text/css" />
    <script id="documentation_options" data-url_root="../" src="../_static/documentation_options.js"></script>
    <script src="../_static/jquery.js"></script>
    <script src="../_static/underscore.js"></script>
    <script src="../_static/doctools.js"></script>
    <link rel="index" title="Index" href="../genindex.html" />
    <link rel="search" title="Search" href="../search.html" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Neuton&amp;subset=latin" type="text/css" media="screen" charset="utf-8" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nobile:regular,italic,bold,bolditalic&amp;subset=latin" type="text/css" media="screen" charset="utf-8" />
<!--[if lte IE 6]>
<link rel="stylesheet" href="../_static/ie6.css" type="text/css" media="screen" charset="utf-8" />
<![endif]-->

  </head><body>

    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="General Index"
             accesskey="I">index</a></li>
        <li class="nav-item nav-item-0"><a href="../index.html">Materials Database  documentation</a> &#187;</li>
        <li class="nav-item nav-item-this"><a href="">2D Semiconductor Database</a></li>
      </ul>
    </div>

    <div class="document">
      <div class="documentwrapper">
        <div class="bodywrapper">
          <div class="body" role="main">

  <div class="section" id="d-semiconductor-database">
<h1>2D Semiconductor Database<a class="headerlink" href="#d-semiconductor-database" title="Permalink to this headline">¶</a></h1>
<p>The database contains structural, elastic, electronic, thermodynamic, and optical properties of around 270 two-dimensional semiconductors. The workflow for the calculation of the different properties is provided below.</p>
<a class="reference internal image-reference" href="../_images/workflow.png"><img alt="../_images/workflow.png" class="align-center" src="../_images/workflow.png" style="width: 400px;" /></a>
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>If you are using data from this database in your research, please cite the following paper:</p>
<p>[1] V. Wang, G. Tang, Y.-C. Liu, R.-T. Wang, H. Mizuseki, Y. Kawazeo, J. Nara, W.-T. Geng, High-Throughput Computational Screening of Two-Dimensional Semiconductors, <a class="reference external" href="https://doi.org/10.1021/acs.jpclett.2c02972">Journal of Physical Chemistry Letters 13, 11581 (2022).</a></p>
</div>
</div>
<div class="section" id="list-of-data">
<h1>List of Data<a class="headerlink" href="#list-of-data" title="Permalink to this headline">¶</a></h1>
<div class="admonition caution">
<p class="admonition-title">Caution</p>
<p>The data were generated by automated first-principles DFT calculations. Basically these data in every entry are not well examined and some might be wrong. Please report the abnormal data to <a class="reference external" href="mailto:wangvei&#37;&#52;&#48;icloud&#46;com">wangvei<span>&#64;</span>icloud<span>&#46;</span>com</a>.</p>
</div>
<ul class="simple">
<li><p>Prototype: [ <strong>A</strong> ]</p>
<ul>
<li><p><a class="reference external" href="As_P21-m.html">As - P21-m</a></p></li>
<li><p><a class="reference external" href="As_P-3m1.html">As - P-3m1</a></p></li>
<li><p><a class="reference external" href="As_Pca21.html">As - Pca21</a></p></li>
<li><p><a class="reference external" href="As_Pmn2_1.html">As - Pmn2</a></p></li>
<li><p><a class="reference external" href="As_Pmna.html">As - Pmna</a></p></li>
<li><p><a class="reference external" href="C_P6^mmm.html">C - P6/mmm</a></p></li>
<li><p><a class="reference external" href="Ge_P-3m1.html">Ge - P-3m1</a></p></li>
<li><p><a class="reference external" href="P_P21-m.html">P - P21-m</a></p></li>
<li><p><a class="reference external" href="P_Pca21.html">P - Pca21</a></p></li>
<li><p><a class="reference external" href="P_Pmna.html">P - Pmna</a></p></li>
<li><p><a class="reference external" href="Si_P-3m1.html">Si - P-3m1</a></p></li>
</ul>
</li>
<li><p>Prototype: [ <strong>AB</strong> ]</p>
<ul>
<li><p><a class="reference external" href="AlN_P-6m2.html">AlN - P-6m2</a></p></li>
<li><p><a class="reference external" href="AuSe_P2^m.html">AuSe - P2/m</a></p></li>
<li><p><a class="reference external" href="BN_P-6m2.html">BN - P-6m2</a></p></li>
<li><p><a class="reference external" href="GaN_P-6m2.html">GaN - P-6m2</a></p></li>
<li><p><a class="reference external" href="GaSe_P-6m2.html">GaSe - P-6m2</a></p></li>
<li><p><a class="reference external" href="GaS_P-3m1.html">GaS - P-3m1</a></p></li>
<li><p><a class="reference external" href="GaS_P-6m2.html">GaS - P-6m2</a></p></li>
<li><p><a class="reference external" href="GeAs_P-6m2.html">GeAs - P-6m2</a></p></li>
<li><p><a class="reference external" href="GeP_P-6m2.html">GeP - P-6m2</a></p></li>
<li><p><a class="reference external" href="GeSe_Pmn2_1.html">GeSe - Pmn2</a></p></li>
<li><p><a class="reference external" href="InN_P-6m2.html">InN - P-6m2</a></p></li>
<li><p><a class="reference external" href="InSe_P3m1.html">InSe - P3m1</a></p></li>
<li><p><a class="reference external" href="PbS_Aem2.html">PbS - Aem2</a></p></li>
<li><p><a class="reference external" href="SiAs_P-6m2.html">SiAs - P-6m2</a></p></li>
<li><p><a class="reference external" href="SiH_P-3m1.html">SiH - P-3m1</a></p></li>
<li><p><a class="reference external" href="SiP_P-6m2.html">SiP - P-6m2</a></p></li>
<li><p><a class="reference external" href="SiSb_P-6m2.html">SiSb - P-6m2</a></p></li>
<li><p><a class="reference external" href="SnAs_P-6m2.html">SnAs - P-6m2</a></p></li>
<li><p><a class="reference external" href="SnO_P4^nmm.html">SnO - P4/nmm</a></p></li>
<li><p><a class="reference external" href="SnO_Pmmn.html">SnO - Pmmn</a></p></li>
<li><p><a class="reference external" href="SnP_P-6m2.html">SnP - P-6m2</a></p></li>
<li><p><a class="reference external" href="SnSe_Pmn2_1.html">SnSe - Pmn2</a></p></li>
<li><p><a class="reference external" href="SnS_Pmn2_1.html">SnS - Pmn2</a></p></li>
<li><p><a class="reference external" href="TlF_Pbcm.html">TlF - Pbcm</a></p></li>
</ul>
</li>
<li><p>Prototype: [ <strong>AB2</strong> ]</p>
<ul>
<li><p><a class="reference external" href="BaO2_P4^mmm.html">BaO2 - P4/mmm</a></p></li>
<li><p><a class="reference external" href="BrTe2_Pmn2_1.html">BrTe2 - Pmn2</a></p></li>
<li><p><a class="reference external" href="CdBr2_P-3m1.html">CdBr2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="CdCl2_P-1.html">CdCl2 - P-1</a></p></li>
<li><p><a class="reference external" href="CdCl2_P-3m1.html">CdCl2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="CrO2_P-6m2.html">CrO2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="CrS2_P-6m2.html">CrS2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="CrSe2_P-6m2.html">CrSe2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="FeS2_P2_1^m.html">FeS2 - P2</a></p></li>
<li><p><a class="reference external" href="FeSe2_P2_1^m.html">FeSe2 - P2</a></p></li>
<li><p><a class="reference external" href="FeTe2_P2_1^m.html">FeTe2 - P2</a></p></li>
<li><p><a class="reference external" href="GeAs2_Pmc2_1.html">GeAs2 - Pmc2</a></p></li>
<li><p><a class="reference external" href="GeI2_P-3m1.html">GeI2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="GeO2_P2_1^m.html">GeO2 - P2</a></p></li>
<li><p><a class="reference external" href="GeO2_P-3m1.html">GeO2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="GeS2_P2_1^m.html">GeS2 - P2</a></p></li>
<li><p><a class="reference external" href="HfO2_P2_1^m.html">HfO2 - P2</a></p></li>
<li><p><a class="reference external" href="HfS2_P2_1^m.html">HfS2 - P2</a></p></li>
<li><p><a class="reference external" href="HfS2_P-3m1.html">HfS2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="HfSe2_P2_1^m.html">HfSe2 - P2</a></p></li>
<li><p><a class="reference external" href="HfSe2_P-3m1.html">HfSe2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="HfTe2_P2_1^m.html">HfTe2 - P2</a></p></li>
<li><p><a class="reference external" href="HfTe2_P-3m1.html">HfTe2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="HgBr2_Cm.html">HgBr2 - Cm</a></p></li>
<li><p><a class="reference external" href="MgBr2_P-3m1.html">MgBr2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="MgCl2_P-3m1.html">MgCl2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="MoO2_P-6m2.html">MoO2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="MoS2_P2_1^m.html">MoS2 - P2</a></p></li>
<li><p><a class="reference external" href="MoS2_P-6m2.html">MoS2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="MoSe2_P2_1^m.html">MoSe2 - P2</a></p></li>
<li><p><a class="reference external" href="MoSe2_P-6m2.html">MoSe2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="MoTe2_P-6m2.html">MoTe2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="NiO2_P2_1^m.html">NiO2 - P2</a></p></li>
<li><p><a class="reference external" href="NiS2_P2_1^m.html">NiS2 - P2</a></p></li>
<li><p><a class="reference external" href="NiS2_P-3m1.html">NiS2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="NiSe2_P2_1^m.html">NiSe2 - P2</a></p></li>
<li><p><a class="reference external" href="NiSe2_P-3m1.html">NiSe2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="NiTe2_P2_1^m.html">NiTe2 - P2</a></p></li>
<li><p><a class="reference external" href="OsO2_P2_1^m.html">OsO2 - P2</a></p></li>
<li><p><a class="reference external" href="OsS2_P2_1^m.html">OsS2 - P2</a></p></li>
<li><p><a class="reference external" href="OsSe2_P2_1^m.html">OsSe2 - P2</a></p></li>
<li><p><a class="reference external" href="PbI2_P-3m1.html">PbI2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="PbO2_P2_1^m.html">PbO2 - P2</a></p></li>
<li><p><a class="reference external" href="PbO2_P-3m1.html">PbO2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="PbS2_P2_1^m.html">PbS2 - P2</a></p></li>
<li><p><a class="reference external" href="PbSe2_P2_1^m.html">PbSe2 - P2</a></p></li>
<li><p><a class="reference external" href="PdO2_P2_1^m.html">PdO2 - P2</a></p></li>
<li><p><a class="reference external" href="PdO2_P-3m1.html">PdO2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="PdS2_P2_1^c.html">PdS2 - P2</a></p></li>
<li><p><a class="reference external" href="PdS2_P2_1^m.html">PdS2 - P2</a></p></li>
<li><p><a class="reference external" href="PdS2_P-3m1.html">PdS2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="PdSe2_P2_1^c.html">PdSe2 - P2</a></p></li>
<li><p><a class="reference external" href="PdSe2_P2_1^m.html">PdSe2 - P2</a></p></li>
<li><p><a class="reference external" href="PdSe2_P-3m1.html">PdSe2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="PdTe2_P2_1^m.html">PdTe2 - P2</a></p></li>
<li><p><a class="reference external" href="PdTe2_P-3m1.html">PdTe2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="PtI2_P2_1^c.html">PtI2 - P2</a></p></li>
<li><p><a class="reference external" href="PtO2_P2_1^m.html">PtO2 - P2</a></p></li>
<li><p><a class="reference external" href="PtO2_P-3m1.html">PtO2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="PtS2_P2_1^m.html">PtS2 - P2</a></p></li>
<li><p><a class="reference external" href="PtS2_P-3m1.html">PtS2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="PtSe2_P2_1^m.html">PtSe2 - P2</a></p></li>
<li><p><a class="reference external" href="PtSe2_P-3m1.html">PtSe2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="PtTe2_P2_1^m.html">PtTe2 - P2</a></p></li>
<li><p><a class="reference external" href="PtTe2_P-3m1.html">PtTe2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="RuO2_P2_1^m.html">RuO2 - P2</a></p></li>
<li><p><a class="reference external" href="RuS2_P2_1^m.html">RuS2 - P2</a></p></li>
<li><p><a class="reference external" href="RuSe2_P2_1^m.html">RuSe2 - P2</a></p></li>
<li><p><a class="reference external" href="RuTe2_P2_1^m.html">RuTe2 - P2</a></p></li>
<li><p><a class="reference external" href="SiAs2_Pmc2_1.html">SiAs2 - Pmc2</a></p></li>
<li><p><a class="reference external" href="SiO2_P6^mmm.html">SiO2 - P6/mmm</a></p></li>
<li><p><a class="reference external" href="SiO2_Pm.html">SiO2 - Pm</a></p></li>
<li><p><a class="reference external" href="SiP2_Pmc2_1.html">SiP2 - Pmc2</a></p></li>
<li><p><a class="reference external" href="SnO2_P1.html">SnO2 - P1</a></p></li>
<li><p><a class="reference external" href="SnO2_P2_1^m.html">SnO2 - P2</a></p></li>
<li><p><a class="reference external" href="SnO2_P-3m1.html">SnO2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="SnS2_P2_1^m.html">SnS2 - P2</a></p></li>
<li><p><a class="reference external" href="SnS2_P-3m1.html">SnS2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="SnSe2_P2_1^m.html">SnSe2 - P2</a></p></li>
<li><p><a class="reference external" href="SnSe2_P-3m1.html">SnSe2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="SrO2_P4^mmm.html">SrO2 - P4/mmm</a></p></li>
<li><p><a class="reference external" href="Te2Br_Pmn2_1.html">Te2Br - Pmn2</a></p></li>
<li><p><a class="reference external" href="Te2Mo_P-6m2.html">Te2Mo - P-6m2</a></p></li>
<li><p><a class="reference external" href="Te2Pd_P-3m1.html">Te2Pd - P-3m1</a></p></li>
<li><p><a class="reference external" href="Te2Pt_P-3m1.html">Te2Pt - P-3m1</a></p></li>
<li><p><a class="reference external" href="TiO2_P2_1^m.html">TiO2 - P2</a></p></li>
<li><p><a class="reference external" href="TiSe2_P-6m2.html">TiSe2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="WO2_P-6m2.html">WO2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="WS2_P2_1^m.html">WS2 - P2</a></p></li>
<li><p><a class="reference external" href="WS2_P-6m2.html">WS2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="WSe2_P2_1^m.html">WSe2 - P2</a></p></li>
<li><p><a class="reference external" href="WSe2_P-6m2.html">WSe2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="WTe2_P-6m2.html">WTe2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="ZnCl2_P-4m2.html">ZnCl2 - P-4m2</a></p></li>
<li><p><a class="reference external" href="ZrCl2_P-6m2.html">ZrCl2 - P-6m2</a></p></li>
<li><p><a class="reference external" href="ZrI2_P2_1^m.html">ZrI2 - P2</a></p></li>
<li><p><a class="reference external" href="ZrO2_P2_1^m.html">ZrO2 - P2</a></p></li>
<li><p><a class="reference external" href="ZrO2_P-3m1.html">ZrO2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="ZrS2_P2_1^m.html">ZrS2 - P2</a></p></li>
<li><p><a class="reference external" href="ZrS2_P-3m1.html">ZrS2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="ZrSe2_P2_1^m.html">ZrSe2 - P2</a></p></li>
<li><p><a class="reference external" href="ZrSe2_P-3m1.html">ZrSe2 - P-3m1</a></p></li>
<li><p><a class="reference external" href="ZrTe2_P-6m2.html">ZrTe2 - P-6m2</a></p></li>
</ul>
</li>
<li><p>Prototype: [ <strong>AB3</strong> ]</p>
<ul>
<li><p><a class="reference external" href="AlCl3_C2^m.html">AlCl3 - C2/m</a></p></li>
<li><p><a class="reference external" href="BiBr3_P2_1^c.html">BiBr3 - P2</a></p></li>
<li><p><a class="reference external" href="DyCl3_Pmmn.html">DyCl3 - Pmmn</a></p></li>
<li><p><a class="reference external" href="GdBr3_P-1.html">GdBr3 - P-1</a></p></li>
<li><p><a class="reference external" href="HfS3_P2_1^m.html">HfS3 - P2</a></p></li>
<li><p><a class="reference external" href="HfSe3_P2_1^m.html">HfSe3 - P2</a></p></li>
<li><p><a class="reference external" href="InBr3_C2^m.html">InBr3 - C2/m</a></p></li>
<li><p><a class="reference external" href="IrBr3_C2^m.html">IrBr3 - C2/m</a></p></li>
<li><p><a class="reference external" href="IrCl3_C2^m.html">IrCl3 - C2/m</a></p></li>
<li><p><a class="reference external" href="LaI3_Pmmn.html">LaI3 - Pmmn</a></p></li>
<li><p><a class="reference external" href="MoO3_P2_1^m.html">MoO3 - P2</a></p></li>
<li><p><a class="reference external" href="NdBr3_Pmmn.html">NdBr3 - Pmmn</a></p></li>
<li><p><a class="reference external" href="RhBr3_C2^m.html">RhBr3 - C2/m</a></p></li>
<li><p><a class="reference external" href="ScCl3_P-3.html">ScCl3 - P-3</a></p></li>
<li><p><a class="reference external" href="Si3H_P-3m1.html">Si3H - P-3m1</a></p></li>
<li><p><a class="reference external" href="SmBr3_Pmmn.html">SmBr3 - Pmmn</a></p></li>
<li><p><a class="reference external" href="TaSe3_P2_1^m.html">TaSe3 - P2</a></p></li>
<li><p><a class="reference external" href="TbCl3_Pmmn.html">TbCl3 - Pmmn</a></p></li>
<li><p><a class="reference external" href="TiS3_P2_1^m.html">TiS3 - P2</a></p></li>
<li><p><a class="reference external" href="YBr3_C2^m.html">YBr3 - C2/m</a></p></li>
<li><p><a class="reference external" href="YI3_P-3.html">YI3 - P-3</a></p></li>
<li><p><a class="reference external" href="ZrS3_P2_1^m.html">ZrS3 - P2</a></p></li>
<li><p><a class="reference external" href="ZrSe3_P2_1^m.html">ZrSe3 - P2</a></p></li>
</ul>
</li>
<li><p>Prototype: [ <strong>AmBn</strong> ]</p>
<ul>
<li><p><a class="reference external" href="Al2Te3_P2_1^c.html">Al2Te3 - P2</a></p></li>
<li><p><a class="reference external" href="V2O5_Pmmn.html">V2O5 - Pmmn</a></p></li>
<li><p><a class="reference external" href="ZrTe5_Pmmn.html">ZrTe5 - Pmmn</a></p></li>
</ul>
</li>
<li><p>Prototype: [ <strong>ABC</strong> ]</p>
<ul>
<li><p><a class="reference external" href="AlClO_Pmmn.html">AlClO - Pmmn</a></p></li>
<li><p><a class="reference external" href="BaBrCl_P2_1^m.html">BaBrCl - P2</a></p></li>
<li><p><a class="reference external" href="BaIF_P4^nmm.html">BaIF - P4/nmm</a></p></li>
<li><p><a class="reference external" href="BiBrO_P4^nmm.html">BiBrO - P4/nmm</a></p></li>
<li><p><a class="reference external" href="BiClO_P4^nmm.html">BiClO - P4/nmm</a></p></li>
<li><p><a class="reference external" href="BiOF_P-3m1.html">BiOF - P-3m1</a></p></li>
<li><p><a class="reference external" href="BiTeCl_P3m1.html">BiTeCl - P3m1</a></p></li>
<li><p><a class="reference external" href="CaClF_P4^nmm.html">CaClF - P4/nmm</a></p></li>
<li><p><a class="reference external" href="CaHBr_P4^nmm.html">CaHBr - P4/nmm</a></p></li>
<li><p><a class="reference external" href="CaHI_P4^nmm.html">CaHI - P4/nmm</a></p></li>
<li><p><a class="reference external" href="DySBr_Pmmn.html">DySBr - Pmmn</a></p></li>
<li><p><a class="reference external" href="DySI_Pmmn.html">DySI - Pmmn</a></p></li>
<li><p><a class="reference external" href="ErSCl_Pmmn.html">ErSCl - Pmmn</a></p></li>
<li><p><a class="reference external" href="ErSeI_Pmmn.html">ErSeI - Pmmn</a></p></li>
<li><p><a class="reference external" href="GaTeCl_Pmn2_1.html">GaTeCl - Pmn2</a></p></li>
<li><p><a class="reference external" href="GdBrO_P4^nmm.html">GdBrO - P4/nmm</a></p></li>
<li><p><a class="reference external" href="HfBrN_P-3m1.html">HfBrN - P-3m1</a></p></li>
<li><p><a class="reference external" href="HfBrN_Pmmn.html">HfBrN - Pmmn</a></p></li>
<li><p><a class="reference external" href="HfIN_P-3m1.html">HfIN - P-3m1</a></p></li>
<li><p><a class="reference external" href="HfNCl_P-3m1.html">HfNCl - P-3m1</a></p></li>
<li><p><a class="reference external" href="HoBrO_P-3m1.html">HoBrO - P-3m1</a></p></li>
<li><p><a class="reference external" href="InBrO_Pmmn.html">InBrO - Pmmn</a></p></li>
<li><p><a class="reference external" href="InClO_Pmmn.html">InClO - Pmmn</a></p></li>
<li><p><a class="reference external" href="KMgSb_P4^nmm.html">KMgSb - P4/nmm</a></p></li>

['P21-m']
['P21-m', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1', 'P-3']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1', 'P-3', 'P3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1', 'P-3', 'P3m1', 'P3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1', 'P-3', 'P3m1', 'P3m1', 'P3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1', 'P-3', 'P3m1', 'P3m1', 'P3m1', 'Pmmn']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1', 'P-3', 'P3m1', 'P3m1', 'P3m1', 'Pmmn', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1', 'P-3', 'P3m1', 'P3m1', 'P3m1', 'Pmmn', 'P-3m1', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1', 'P-3', 'P3m1', 'P3m1', 'P3m1', 'Pmmn', 'P-3m1', 'P2', 'P6/mmm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1', 'P-3', 'P3m1', 'P3m1', 'P3m1', 'Pmmn', 'P-3m1', 'P2', 'P6/mmm', 'P4/mbm']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1', 'P-3', 'P3m1', 'P3m1', 'P3m1', 'Pmmn', 'P-3m1', 'P2', 'P6/mmm', 'P4/mbm', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1', 'P-3', 'P3m1', 'P3m1', 'P3m1', 'Pmmn', 'P-3m1', 'P2', 'P6/mmm', 'P4/mbm', 'P-3m1', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1', 'P-3', 'P3m1', 'P3m1', 'P3m1', 'Pmmn', 'P-3m1', 'P2', 'P6/mmm', 'P4/mbm', 'P-3m1', 'P-3m1', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1', 'P-3', 'P3m1', 'P3m1', 'P3m1', 'Pmmn', 'P-3m1', 'P2', 'P6/mmm', 'P4/mbm', 'P-3m1', 'P-3m1', 'P2', 'P-3m1']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1', 'P-3', 'P3m1', 'P3m1', 'P3m1', 'Pmmn', 'P-3m1', 'P2', 'P6/mmm', 'P4/mbm', 'P-3m1', 'P-3m1', 'P2', 'P-3m1', 'P312']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1', 'P-3', 'P3m1', 'P3m1', 'P3m1', 'Pmmn', 'P-3m1', 'P2', 'P6/mmm', 'P4/mbm', 'P-3m1', 'P-3m1', 'P2', 'P-3m1', 'P312', 'Cm']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1', 'P-3', 'P3m1', 'P3m1', 'P3m1', 'Pmmn', 'P-3m1', 'P2', 'P6/mmm', 'P4/mbm', 'P-3m1', 'P-3m1', 'P2', 'P-3m1', 'P312', 'Cm', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1', 'P-3', 'P3m1', 'P3m1', 'P3m1', 'Pmmn', 'P-3m1', 'P2', 'P6/mmm', 'P4/mbm', 'P-3m1', 'P-3m1', 'P2', 'P-3m1', 'P312', 'Cm', 'P2', 'P4mm']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1', 'P-3', 'P3m1', 'P3m1', 'P3m1', 'Pmmn', 'P-3m1', 'P2', 'P6/mmm', 'P4/mbm', 'P-3m1', 'P-3m1', 'P2', 'P-3m1', 'P312', 'Cm', 'P2', 'P4mm', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1', 'P-3', 'P3m1', 'P3m1', 'P3m1', 'Pmmn', 'P-3m1', 'P2', 'P6/mmm', 'P4/mbm', 'P-3m1', 'P-3m1', 'P2', 'P-3m1', 'P312', 'Cm', 'P2', 'P4mm', 'P-3m1', 'P-3m1']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1', 'P-3', 'P3m1', 'P3m1', 'P3m1', 'Pmmn', 'P-3m1', 'P2', 'P6/mmm', 'P4/mbm', 'P-3m1', 'P-3m1', 'P2', 'P-3m1', 'P312', 'Cm', 'P2', 'P4mm', 'P-3m1', 'P-3m1', 'P-31m']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1', 'P-3', 'P3m1', 'P3m1', 'P3m1', 'Pmmn', 'P-3m1', 'P2', 'P6/mmm', 'P4/mbm', 'P-3m1', 'P-3m1', 'P2', 'P-3m1', 'P312', 'Cm', 'P2', 'P4mm', 'P-3m1', 'P-3m1', 'P-31m', 'P-3m1']

['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1', 'P-3', 'P3m1', 'P3m1', 'P3m1', 'Pmmn', 'P-3m1', 'P2', 'P6/mmm', 'P4/mbm', 'P-3m1', 'P-3m1', 'P2', 'P-3m1', 'P312', 'Cm', 'P2', 'P4mm', 'P-3m1', 'P-3m1', 'P-31m', 'P-3m1', 'P4/n']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1', 'P-3', 'P3m1', 'P3m1', 'P3m1', 'Pmmn', 'P-3m1', 'P2', 'P6/mmm', 'P4/mbm', 'P-3m1', 'P-3m1', 'P2', 'P-3m1', 'P312', 'Cm', 'P2', 'P4mm', 'P-3m1', 'P-3m1', 'P-31m', 'P-3m1', 'P4/n', 'P-42m']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1', 'P-3', 'P3m1', 'P3m1', 'P3m1', 'Pmmn', 'P-3m1', 'P2', 'P6/mmm', 'P4/mbm', 'P-3m1', 'P-3m1', 'P2', 'P-3m1', 'P312', 'Cm', 'P2', 'P4mm', 'P-3m1', 'P-3m1', 'P-31m', 'P-3m1', 'P4/n', 'P-42m', 'P2']
['P21-m', 'P-3m1', 'Pca21', 'Pmn2', 'Pmna', 'P6/mmm', 'P-3m1', 'P21-m', 'Pca21', 'Pmna', 'P-3m1', 'P-6m2', 'P2/m', 'P-6m2', 'P-6m2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'Pmn2', 'P-6m2', 'P3m1', 'Aem2', 'P-6m2', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P4/nmm', 'Pmmn', 'P-6m2', 'Pmn2', 'Pmn2', 'Pbcm', 'P4/mmm', 'Pmn2', 'P-3m1', 'P-1', 'P-3m1', 'P-6m2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P2', 'Pmc2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'Cm', 'P-3m1', 'P-3m1', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P2', 'P2', 'P2', 'Pmc2', 'P6/mmm', 'Pm', 'Pmc2', 'P1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P4/mmm', 'Pmn2', 'P-6m2', 'P-3m1', 'P-3m1', 'P2', 'P-6m2', 'P-6m2', 'P2', 'P-6m2', 'P2', 'P-6m2', 'P-6m2', 'P-4m2', 'P-6m2', 'P2', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P2', 'P-3m1', 'P-6m2', 'C2/m', 'P2', 'Pmmn', 'P-1', 'P2', 'P2', 'C2/m', 'C2/m', 'C2/m', 'Pmmn', 'P2', 'Pmmn', 'C2/m', 'P-3', 'P-3m1', 'Pmmn', 'P2', 'Pmmn', 'P2', 'C2/m', 'P-3', 'P2', 'P2', 'P2', 'Pmmn', 'Pmmn', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P-3m1', 'P3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmmn', 'Pmn2', 'P4/nmm', 'P-3m1', 'Pmmn', 'P-3m1', 'P-3m1', 'P-3m1', 'Pmmn', 'Pmmn', 'P4/nmm', 'P2', 'P4/nmm', 'Pmmn', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P2/c', 'P2/c', 'P-3m1', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'Pmn2', 'Pmmn', 'P2', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P4/nmm', 'P3m1', 'P2', 'Pmmn', 'Pmmn', 'P4/nmm', 'P-3m1', 'P4/nmm', 'P4/nmm', 'Pmmn', 'P-3m1', 'P222', 'Pmn2', 'P2', 'P2', 'P2', 'Pbcm', 'P2/m', 'C2/m', 'P-3', 'P-3', 'P2', 'P4mm', 'P-31m', 'P-3m1', 'P2', 'P4/mmm', 'P2/m', 'Pmma', 'P-3m1', 'P-3m1', 'P2/m', 'C2/m', 'P-3', 'P-3m1', 'P2/m', 'P-3m1', 'P-3m1', 'P-42m', 'P-3m1', 'P-3m1', 'P-3', 'P3m1', 'P3m1', 'P3m1', 'Pmmn', 'P-3m1', 'P2', 'P6/mmm', 'P4/mbm', 'P-3m1', 'P-3m1', 'P2', 'P-3m1', 'P312', 'Cm', 'P2', 'P4mm', 'P-3m1', 'P-3m1', 'P-31m', 'P-3m1', 'P4/n', 'P-42m', 'P2', 'P2/m']

In [57]:
zip(materials_id,space_group)

In [58]:
for i in zip(materials_id,space_group):
    print(i)

('As_P21-m', 'P21-m')
('As_P-3m1', 'P-3m1')
('As_Pca21', 'Pca21')
('As_Pmn2_1', 'Pmn2')
('As_Pmna', 'Pmna')
('C_P6/mmm', 'P6/mmm')
('Ge_P-3m1', 'P-3m1')
('P_P21-m', 'P21-m')
('P_Pca21', 'Pca21')
('P_Pmna', 'Pmna')
('Si_P-3m1', 'P-3m1')
('AlN_P-6m2', 'P-6m2')
('AuSe_P2/m', 'P2/m')
('BN_P-6m2', 'P-6m2')
('GaN_P-6m2', 'P-6m2')
('GaSe_P-6m2', 'P-6m2')
('GaS_P-3m1', 'P-3m1')
('GaS_P-6m2', 'P-6m2')
('GeAs_P-6m2', 'P-6m2')
('GeP_P-6m2', 'P-6m2')
('GeSe_Pmn2_1', 'Pmn2')
('InN_P-6m2', 'P-6m2')
('InSe_P3m1', 'P3m1')
('PbS_Aem2', 'Aem2')
('SiAs_P-6m2', 'P-6m2')
('SiH_P-3m1', 'P-3m1')
('SiP_P-6m2', 'P-6m2')
('SiSb_P-6m2', 'P-6m2')
('SnAs_P-6m2', 'P-6m2')
('SnO_P4/nmm', 'P4/nmm')
('SnO_Pmmn', 'Pmmn')
('SnP_P-6m2', 'P-6m2')
('SnSe_Pmn2_1', 'Pmn2')
('SnS_Pmn2_1', 'Pmn2')
('TlF_Pbcm', 'Pbcm')
('BaO2_P4/mmm', 'P4/mmm')
('BrTe2_Pmn2_1', 'Pmn2')
('CdBr2_P-3m1', 'P-3m1')
('CdCl2_P-1', 'P-1')
('CdCl2_P-3m1', 'P-3m1')
('CrO2_P-6m2', 'P-6m2')
('CrS2_P-6m2', 'P-6m2')
('CrSe2_P-6m2', 'P-6m2')
('FeS2_P2_1/m', 'P2')
('FeSe2_P2_1/m', 'P2')
('FeTe2_P2_1/m', 'P2')
('GeAs2_Pmc2_1', 'Pmc2')
('GeI2_P-3m1', 'P-3m1')
('GeO2_P2_1/m', 'P2')
('GeO2_P-3m1', 'P-3m1')
('GeS2_P2_1/m', 'P2')
('HfO2_P2_1/m', 'P2')
('HfS2_P2_1/m', 'P2')
('HfS2_P-3m1', 'P-3m1')
('HfSe2_P2_1/m', 'P2')
('HfSe2_P-3m1', 'P-3m1')
('HfTe2_P2_1/m', 'P2')
('HfTe2_P-3m1', 'P-3m1')
('HgBr2_Cm', 'Cm')
('MgBr2_P-3m1', 'P-3m1')
('MgCl2_P-3m1', 'P-3m1')
('MoO2_P-6m2', 'P-6m2')
('MoS2_P2_1/m', 'P2')
('MoS2_P-6m2', 'P-6m2')
('MoSe2_P2_1/m', 'P2')
('MoSe2_P-6m2', 'P-6m2')
('MoTe2_P-6m2', 'P-6m2')
('NiO2_P2_1/m', 'P2')
('NiS2_P2_1/m', 'P2')
('NiS2_P-3m1', 'P-3m1')
('NiSe2_P2_1/m', 'P2')
('NiSe2_P-3m1', 'P-3m1')
('NiTe2_P2_1/m', 'P2')
('OsO2_P2_1/m', 'P2')
('OsS2_P2_1/m', 'P2')
('OsSe2_P2_1/m', 'P2')
('PbI2_P-3m1', 'P-3m1')
('PbO2_P2_1/m', 'P2')
('PbO2_P-3m1', 'P-3m1')
('PbS2_P2_1/m', 'P2')
('PbSe2_P2_1/m', 'P2')
('PdO2_P2_1/m', 'P2')
('PdO2_P-3m1', 'P-3m1')
('PdS2_P2_1/c', 'P2')
('PdS2_P2_1/m', 'P2')
('PdS2_P-3m1', 'P-3m1')
('PdSe2_P2_1/c', 'P2')
('PdSe2_P2_1/m', 'P2')
('PdSe2_P-3m1', 'P-3m1')
('PdTe2_P2_1/m', 'P2')
('PdTe2_P-3m1', 'P-3m1')
('PtI2_P2_1/c', 'P2')
('PtO2_P2_1/m', 'P2')
('PtO2_P-3m1', 'P-3m1')
('PtS2_P2_1/m', 'P2')
('PtS2_P-3m1', 'P-3m1')
('PtSe2_P2_1/m', 'P2')
('PtSe2_P-3m1', 'P-3m1')
('PtTe2_P2_1/m', 'P2')
('PtTe2_P-3m1', 'P-3m1')
('RuO2_P2_1/m', 'P2')
('RuS2_P2_1/m', 'P2')
('RuSe2_P2_1/m', 'P2')
('RuTe2_P2_1/m', 'P2')
('SiAs2_Pmc2_1', 'Pmc2')
('SiO2_P6/mmm', 'P6/mmm')
('SiO2_Pm', 'Pm')
('SiP2_Pmc2_1', 'Pmc2')
('SnO2_P1', 'P1')
('SnO2_P2_1/m', 'P2')
('SnO2_P-3m1', 'P-3m1')
('SnS2_P2_1/m', 'P2')
('SnS2_P-3m1', 'P-3m1')
('SnSe2_P2_1/m', 'P2')
('SnSe2_P-3m1', 'P-3m1')
('SrO2_P4/mmm', 'P4/mmm')
('Te2Br_Pmn2_1', 'Pmn2')
('Te2Mo_P-6m2', 'P-6m2')
('Te2Pd_P-3m1', 'P-3m1')
('Te2Pt_P-3m1', 'P-3m1')
('TiO2_P2_1/m', 'P2')
('TiSe2_P-6m2', 'P-6m2')
('WO2_P-6m2', 'P-6m2')
('WS2_P2_1/m', 'P2')
('WS2_P-6m2', 'P-6m2')
('WSe2_P2_1/m', 'P2')
('WSe2_P-6m2', 'P-6m2')
('WTe2_P-6m2', 'P-6m2')
('ZnCl2_P-4m2', 'P-4m2')
('ZrCl2_P-6m2', 'P-6m2')
('ZrI2_P2_1/m', 'P2')
('ZrO2_P2_1/m', 'P2')
('ZrO2_P-3m1', 'P-3m1')
('ZrS2_P2_1/m', 'P2')
('ZrS2_P-3m1', 'P-3m1')
('ZrSe2_P2_1/m', 'P2')
('ZrSe2_P-3m1', 'P-3m1')
('ZrTe2_P-6m2', 'P-6m2')
('AlCl3_C2/m', 'C2/m')
('BiBr3_P2_1/c', 'P2')
('DyCl3_Pmmn', 'Pmmn')
('GdBr3_P-1', 'P-1')
('HfS3_P2_1/m', 'P2')
('HfSe3_P2_1/m', 'P2')
('InBr3_C2/m', 'C2/m')
('IrBr3_C2/m', 'C2/m')
('IrCl3_C2/m', 'C2/m')
('LaI3_Pmmn', 'Pmmn')
('MoO3_P2_1/m', 'P2')
('NdBr3_Pmmn', 'Pmmn')
('RhBr3_C2/m', 'C2/m')
('ScCl3_P-3', 'P-3')
('Si3H_P-3m1', 'P-3m1')
('SmBr3_Pmmn', 'Pmmn')
('TaSe3_P2_1/m', 'P2')
('TbCl3_Pmmn', 'Pmmn')
('TiS3_P2_1/m', 'P2')
('YBr3_C2/m', 'C2/m')
('YI3_P-3', 'P-3')
('ZrS3_P2_1/m', 'P2')
('ZrSe3_P2_1/m', 'P2')
('Al2Te3_P2_1/c', 'P2')
('V2O5_Pmmn', 'Pmmn')
('ZrTe5_Pmmn', 'Pmmn')
('AlClO_Pmmn', 'Pmmn')
('BaBrCl_P2_1/m', 'P2')
('BaIF_P4/nmm', 'P4/nmm')
('BiBrO_P4/nmm', 'P4/nmm')
('BiClO_P4/nmm', 'P4/nmm')
('BiOF_P-3m1', 'P-3m1')
('BiTeCl_P3m1', 'P3m1')
('CaClF_P4/nmm', 'P4/nmm')
('CaHBr_P4/nmm', 'P4/nmm')
('CaHI_P4/nmm', 'P4/nmm')
('DySBr_Pmmn', 'Pmmn')
('DySI_Pmmn', 'Pmmn')
('ErSCl_Pmmn', 'Pmmn')
('ErSeI_Pmmn', 'Pmmn')
('GaTeCl_Pmn2_1', 'Pmn2')
('GdBrO_P4/nmm', 'P4/nmm')
('HfBrN_P-3m1', 'P-3m1')
('HfBrN_Pmmn', 'Pmmn')
('HfIN_P-3m1', 'P-3m1')
('HfNCl_P-3m1', 'P-3m1')
('HoBrO_P-3m1', 'P-3m1')
('InBrO_Pmmn', 'Pmmn')
('InClO_Pmmn', 'Pmmn')
('KMgSb_P4/nmm', 'P4/nmm')
('KTlO_P2_1/m', 'P2')
('LaIO_P4/nmm', 'P4/nmm')
('LuSBr_Pmmn', 'Pmmn')
('NaZnP_P4/nmm', 'P4/nmm')
('NdBrO_P4/nmm', 'P4/nmm')
('NdIO_P4/nmm', 'P4/nmm')
('PbClF_P4/nmm', 'P4/nmm')
('PbIF_P4/nmm', 'P4/nmm')
('PPdSe_P2/c', 'P2/c')
('PPdS_P2/c', 'P2/c')
('PrBrO_P-3m1', 'P-3m1')
('PrIO_P4/nmm', 'P4/nmm')
('RbLiSe_P4/nmm', 'P4/nmm')
('RbLiS_P4/nmm', 'P4/nmm')
('SbSeI_Pmn2_1', 'Pmn2')
('ScBrO_Pmmn', 'Pmmn')
('ScIO_P2_1/m', 'P2')
('SmBrO_P4/nmm', 'P4/nmm')
('SrHBr_P4/nmm', 'P4/nmm')
('SrHI_P4/nmm', 'P4/nmm')
('SrIF_P4/nmm', 'P4/nmm')
('TeBiBr_P3m1', 'P3m1')
('TeRhCl_P2_1/m', 'P2')
('TiBrN_Pmmn', 'Pmmn')
('TiNCl_Pmmn', 'Pmmn')
('TmBrO_P4/nmm', 'P4/nmm')
('YBrO_P-3m1', 'P-3m1')
('YBrO_P4/nmm', 'P4/nmm')
('YIO_P4/nmm', 'P4/nmm')
('ZrBrN_Pmmn', 'Pmmn')
('ZrNCl_P-3m1', 'P-3m1')
('AuClO2_P222_1', 'P222')
('CuHO2_Pmn2_1', 'Pmn2')
('CuSe2Br_P2_1', 'P2')
('CuSe2Cl_P2_1', 'P2')
('CuTe2Br_P2_1', 'P2')
('LiBiO2_Pbcm', 'Pbcm')
('TaI2O_P2/m', 'P2/m')
('CdPS3_C2/m', 'C2/m')
('CdPS3_P-3', 'P-3')
('MgPSe3_P-3', 'P-3')
('PdSeO3_P2_1/m', 'P2')
('TiPbO3_P4mm', 'P4mm')
('TlSbO3_P-31m', 'P-31m')
('Al2Mg2Se5_P-3m1', 'P-3m1')
('As2SO6_P2_12_12', 'P2')
('Ba4Sb2O_P4/mmm', 'P4/mmm')
('BaCaI4_P2/m', 'P2/m')
('BaTe2O6_Pmma', 'Pmma')
('Bi2Pb2Se5_P-3m1', 'P-3m1')
('Bi2Te2S_P-3m1', 'P-3m1')
('CaPbI4_P2/m', 'P2/m')
('CdPS3_C2/m', 'C2/m')
('CdPS3_P-3', 'P-3')
('GeY2I2_P-3m1', 'P-3m1')
('HfTeSe4_P2/m', 'P2/m')
('K4HgAs2_P-3m1', 'P-3m1')
('Li2CeAs2_P-3m1', 'P-3m1')
('Li2S4W_P-42m', 'P-42m')
('Lu2CCl2_P-3m1', 'P-3m1')
('MgAl2S4_P-3m1', 'P-3m1')
('MgPSe3_P-3', 'P-3')
('Na4CdP2_P3m1', 'P3m1')
('Nb3SBr7_P3m1', 'P3m1')
('Nb3TeCl7_P3m1', 'P3m1')
('NiTa2S5_Pmmn', 'Pmmn')
('Pd3P2S8_P-3m1', 'P-3m1')
('PdSeO3_P2_1/m', 'P2')
('Rb2Pd3S4_P6/mmm', 'P6/mmm')
('RbBrF4_P4/mbm', 'P4/mbm')
('Sb2Ge2Te5_P-3m1', 'P-3m1')
('Sb2Te2Se_P-3m1', 'P-3m1')
('Sb4S5Cl2_P2_1/m', 'P2')
('Sc2CCl2_P-3m1', 'P-3m1')
('SnP2S6_P312', 'P312')
('Ta3SBr7_Cm', 'Cm')
('TaTe4Ir_P2_1/m', 'P2')
('TiPbO3_P4mm', 'P4mm')
('TlPd2Se3_P-3m1', 'P-3m1')
('TlPt2S3_P-3m1', 'P-3m1')
('TlSbO3_P-31m', 'P-31m')
('TlTe3Pt2_P-3m1', 'P-3m1')
('VPO5_P4/n', 'P4/n')
('WCu2S4_P-42m', 'P-42m')
('ZnAs2O4_P2_1', 'P2')
('ZnIn2S4_P2/m', 'P2/m')

In [59]:
data = pd.DataFrame(materials_id,space_group)
data

                    0
P21-m        As_P21-m
P-3m1        As_P-3m1
Pca21        As_Pca21
Pmn2        As_Pmn2_1
Pmna          As_Pmna
...               ...
P-3m1  TlTe3Pt2_P-3m1
P4/n        VPO5_P4/n
P-42m    WCu2S4_P-42m
P2       ZnAs2O4_P2_1
P2/m     ZnIn2S4_P2/m

[274 rows x 1 columns]

In [51]:
from urllib.parse import quote
url_text = quote("^")
print(url_text)

%5E

# cif数据读取

In [65]:
import json

f = open("jdft_3d-12-12-2022.json",'r')
data_3d = json.load(f)
f.close()
df = pd.DataFrame(data_3d)
df

,jid,spg_number,spg_symbol,formula,formation_energy_peratom,func,optb88vdw_bandgap,atoms,slme,magmom_oszicar,...,density,poisson,raw_files,nat,bulk_modulus_kv,shear_modulus_gv,mbj_bandgap,hse_gap,reference,search
0,JVASP-90856,129,P4/nmm,TiCuSiAs,-0.42762,OptB88vdW,0.000,"{'lattice_mat': [[3.566933224304235, 0.0, -0.0...",na,0.0,...,5.956,na,[],8,na,na,na,na,mp-1080455,-As-Cu-Si-Ti
1,JVASP-86097,221,Pm-3m,DyB6,-0.41596,OptB88vdW,0.000,"{'lattice_mat': [[4.089078911208881, 0.0, 0.0]...",na,0.0,...,5.522,na,"[OPT-LOPTICS,JVASP-86097.zip,https://ndownload...",7,na,na,na,na,mp-568319,-B-Dy
2,JVASP-64906,119,I-4m2,Be2OsRu,0.04847,OptB88vdW,0.000,"{'lattice_mat': [[-1.833590720595598, 1.833590...",na,0.0,...,10.960,na,"[OPT-LOPTICS,JVASP-64906.zip,https://ndownload...",4,na,na,na,na,auid-3eaf68dd483bf4f4,-Be-Os-Ru
3,JVASP-98225,14,P2_1/c,KBi,-0.44140,OptB88vdW,0.472,"{'lattice_mat': [[7.2963518353359165, 0.0, 0.0...",na,0.0,...,5.145,na,[],32,na,na,na,na,mp-31104,-Bi-K
4,JVASP-10,164,P-3m1,VSe2,-0.71026,OptB88vdW,0.000,"{'lattice_mat': [[1.6777483798834445, -2.90594...",na,0.0,...,5.718,0.23,"[FD-ELAST,JVASP-10.zip,https://ndownloader.fig...",3,48.79,33.05,0.0,na,mp-694,-Se-V
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75988,JVASP-156020,139,I4/mmm,AcRh2Pb2,-0.30652,OptB88vdW,0.000,"{'lattice_mat': [[-2.374509402119681, 2.374509...",na,0.0,...,11.194,na,[],5,na,na,na,na,1206834,-Ac-Pb-Rh
75989,JVASP-156398,216,F-43m,PrTlZn,-0.34112,OptB88vdW,0.000,"{'lattice_mat': [[-0.0, 3.4210598347774503, 3....",na,0.0,...,8.517,na,[],3,na,na,na,na,915022,-Pr-Tl-Zn
75990,JVASP-156099,139,I4/mmm,BaIn2Bi2,-0.39352,OptB88vdW,0.000,"{'lattice_mat': [[4.082347574975881, -4.076131...",na,0.0,...,7.460,0.67,[],5,30.67,-11.44,na,na,1214095,-Ba-Bi-In
75991,JVASP-156007,139,I4/mmm,TmSi2Tc2,-0.54853,OptB88vdW,0.000,"{'lattice_mat': [[2.90400678672412, -2.9037689...",na,0.0,...,8.212,na,[],5,na,na,na,na,1206745,-Si-Tc-Tm
75992,JVASP-156008,139,I4/mmm,ThSn2Ru2,-0.28045,OptB88vdW,0.000,"{'lattice_mat': [[-2.272566257257212, 2.272566...",na,0.0,...,10.185,na,[],5,na,na,na,na,1206746,-Ru-Sn-Th

In [66]:
df.to_csv("jdft_3d-12-12-2022.csv",index=False)

In [67]:
print([column for column in df])

['jid', 'spg_number', 'spg_symbol', 'formula', 'formation_energy_peratom', 'func', 'optb88vdw_bandgap', 'atoms', 'slme', 'magmom_oszicar', 'spillage', 'elastic_tensor', 'effective_masses_300K', 'kpoint_length_unit', 'maxdiff_mesh', 'maxdiff_bz', 'encut', 'optb88vdw_total_energy', 'epsx', 'epsy', 'epsz', 'mepsx', 'mepsy', 'mepsz', 'modes', 'magmom_outcar', 'max_efg', 'avg_elec_mass', 'avg_hole_mass', 'icsd', 'dfpt_piezo_max_eij', 'dfpt_piezo_max_dij', 'dfpt_piezo_max_dielectric', 'dfpt_piezo_max_dielectric_electronic', 'dfpt_piezo_max_dielectric_ionic', 'max_ir_mode', 'min_ir_mode', 'n-Seebeck', 'p-Seebeck', 'n-powerfact', 'p-powerfact', 'ncond', 'pcond', 'nkappa', 'pkappa', 'ehull', 'Tc_supercon', 'dimensionality', 'efg', 'xml_data_link', 'typ', 'exfoliation_energy', 'spg', 'crys', 'density', 'poisson', 'raw_files', 'nat', 'bulk_modulus_kv', 'shear_modulus_gv', 'mbj_bandgap', 'hse_gap', 'reference', 'search']

In [68]:
print(len([column for column in df]))

64

In [69]:
file_cif_name = 'jdft_3d-12-12-2022'+ '_cif'
if not os.path.exists(file_cif_name):
    os.mkdir(file_cif_name)

In [75]:
from jarvis.core.atoms import Atoms

Atom = Atoms.from_dict(data_3d[0]['atoms'])
Atom.write_cif("1.cif")
print(Atom)

Ti2Cu2Si2As2
1.0
3.566933224304235 0.0 -0.0
0.0 3.566933224304235 -0.0
-0.0 -0.0 9.397075454186664
Ti Cu Si As
2 2 2 2
Cartesian
2.6751975000000003 2.6751975000000003 7.376101754328542
0.8917325 0.8917325 2.0209782456714573
0.8917325 2.6751975000000003 4.69854
2.6751975000000003 0.8917325 4.69854
0.8917325 2.6751975000000003 0.0
2.6751975000000003 0.8917325 0.0
2.6751975000000003 2.6751975000000003 2.8894795605846353
0.8917325 0.8917325 6.507600439415366

In [77]:
for  i in range(len(data_3d)):
    Atom = Atoms.from_dict(data_3d[i]['atoms'])
    mp_id = data_3d[i]['jid']+ '.cif'
    Atom.write_cif(os.path.join('./'+file_cif_name,mp_id))

KeyboardInterrupt:

In [85]:
file_cif_name = "jdft_3d-6-6-2019" + '_cif'
if not os.path.exists(file_cif_name):
    os.mkdir(file_cif_name)

In [79]:
f = open("jdft_3d-6-6-2019.json",'r')
data = json.load(f)
f.close()

In [81]:
df = pd.DataFrame(data)
df

,gv,mpid,encut,icsd,form_enp,final_str,mbj_gap,fin_en,jid,elastic,...,epsy,eff_mass,op_gap,initial_str,magmom,mepsz,mepsx,mepsy,kv,spillage
0,na,mp-10006,500,43284,-0.029,"{'@module': 'pymatgen.core.structure', '@class...",na,-1.329663,JVASP-4663,na,...,na,"{'p': [4.0173731541135154e-07, 4.0174484327093...",na,"{'@module': 'pymatgen.core.structure', '@class...","{'magmom_out': 0.0, 'magmom_osz': 0.0}",na,na,na,na,na
1,16.673,mp-10009,700,None,-0.343,"{'@module': 'pymatgen.core.structure', '@class...",1.0468,-5.262569,JVASP-4666,"68.0,18.6,8.8,0.0,0.0,0.0,18.6,68.0,8.8,0.0,0....",...,11.3343,"{'p': [0.0008287139654377279, 0.00323606388457...",0.2169,"{'@module': 'pymatgen.core.structure', '@class...","{'magmom_out': 0.0, 'magmom_osz': 0.0}",7.7336,8.3345,8.3318,26.356,0.120257
2,na,mp-10014,600,43410,-1.144,"{'@module': 'pymatgen.core.structure', '@class...",na,-17.378164,JVASP-588,na,...,10.5706,"{'p': [1.137461380516098e-06, 1.13746446791445...",0.0263,"{'@module': 'pymatgen.core.structure', '@class...","{'magmom_out': 0.0, 'magmom_osz': 0.0}",na,na,na,na,na
3,57.66,mp-10027,550,None,-0.908,"{'@module': 'pymatgen.core.structure', '@class...",na,-17.527299,JVASP-332,"160.3,59.3,81.6,0.0,0.0,0.0,59.3,160.3,81.6,0....",...,70.8342,"{'p': [4.711706308361336e-06, 4.71170812033814...",0.0012,"{'@module': 'pymatgen.core.structure', '@class...","{'magmom_out': 0.0, 'magmom_osz': 0.0}",106.7637,260.1319,246.4669,107.167,na
4,37.273,mp-10033,650,43697,-1.123,"{'@module': 'pymatgen.core.structure', '@class...",na,-31.376499,JVASP-66,"172.3,60.4,11.2,0.0,0.0,0.0,60.4,172.3,11.2,0....",...,21.2627,"{'p': [1.215365059321779e-06, 1.21536574075813...",0.0206,"{'@module': 'pymatgen.core.structure', '@class...","{'magmom_out': 0.0, 'magmom_osz': 0.0}",15.5521,76.6318,79.8456,61.622,na
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32481,87.653,auid-fe234bf83f4b3556,1050,None,-0.058,"{'@module': 'pymatgen.core.structure', '@class...",na,-10.203832,JVASP-75037,"220.3,97.4,122.4,0.0,-0.0,-0.0,97.4,220.3,122....",...,101.9103,"{'p': 'na', 'n': 'na'}",0.0035,"{'@module': 'pymatgen.core.structure', '@class...","{'magmom_out': 2.0729157, 'magmom_osz': 2.0729}",na,na,na,143.689,na
32482,na,auid-fef235f7454aed91,700,None,0.507,"{'@module': 'pymatgen.core.structure', '@class...",na,-3.502093,JVASP-75040,na,...,108.079,"{'p': 'na', 'n': 'na'}",0.0011,"{'@module': 'pymatgen.core.structure', '@class...","{'magmom_out': -0.0, 'magmom_osz': 0.0}",na,na,na,na,na
32483,na,auid-ffc5aafeb3f9a228,650,None,0.323,"{'@module': 'pymatgen.core.structure', '@class...",na,-3.233638,JVASP-75041,na,...,28.5845,"{'p': 'na', 'n': 'na'}",0.0048,"{'@module': 'pymatgen.core.structure', '@class...","{'magmom_out': -0.0, 'magmom_osz': -0.0}",na,na,na,na,na
32484,na,ICSD-52578,900,None,-0.455,"{'@module': 'pymatgen.core.structure', '@class...",na,-23.251584,JVASP-72476,na,...,9.4413,"{'p': 'na', 'n': 'na'}",0.4536,"{'@module': 'pymatgen.core.structure', '@class...","{'magmom_out': 0.0, 'magmom_osz': -0.0}",na,na,na,na,na
32485,na,ICSD-605236,500,None,-0.239,"{'@module': 'pymatgen.core.structure', '@class...",na,-9.754229,JVASP-72481,na,...,20.7179,"{'p': 'na', 'n': 'na'}",0.6061,"{'@module': 'pymatgen.core.structure', '@class...","{'magmom_out': 0.0, 'magmom_osz': 0.0}",na,na,na,na,na

In [83]:
from pymatgen.core.structure import Structure
from pymatgen.io.cif import CifWriter

structure = Structure.from_dict(data[0]['final_str'])
cif_file = CifWriter(structure)
cif_file.write_file("3.cif")

In [86]:
for i in range(len(data)):
    structure = Structure.from_dict(data[i]['final_str'])
    cif_file = CifWriter(structure)
    mp_id = data[i]['mpid'] + ".cif"
    cif_file.write_file("./jdft_3d-6-6-2019_cif/" + mp_id)
    print("正在转换%s"%mp_id)

正在转换mp-10006.cif
正在转换mp-10009.cif
正在转换mp-10014.cif
正在转换mp-10027.cif
正在转换mp-10033.cif
正在转换mp-10065.cif
正在转换mp-10128.cif
正在转换mp-10144.cif
正在转换mp-10145.cif
正在转换mp-1016.cif
正在转换mp-10188.cif
正在转换mp-10228.cif
正在转换mp-10259.cif
正在转换mp-10569.cif
正在转换mp-10614.cif
正在转换mp-10628.cif
正在转换mp-10656.cif
正在转换mp-10678.cif
正在转换mp-10681.cif
正在转换mp-10728.cif
正在转换mp-10838.cif
正在转换mp-10897.cif
正在转换mp-10913.cif
正在转换mp-1103.cif
正在转换mp-1115.cif
正在转换mp-11232.cif
正在转换mp-11324.cif
正在转换mp-1136.cif
正在转换mp-1143.cif
正在转换mp-11493.cif
正在转换mp-11524.cif
正在转换mp-11620.cif
正在转换mp-1170.cif
正在转换mp-11714.cif
正在转换mp-11722.cif
正在转换mp-11786.cif
正在转换mp-11787.cif
正在转换mp-11788.cif
正在转换mp-11826.cif
正在转换mp-1186.cif
正在转换mp-1190.cif
正在转换mp-12062.cif
正在转换mp-12085.cif
正在转换mp-12091.cif
正在转换mp-12120.cif
正在转换mp-1213.cif
正在转换mp-1214.cif
正在转换mp-1215.cif
正在转换mp-12351.cif
正在转换mp-12406.cif
正在转换mp-12581.cif
正在转换mp-12597.cif
正在转换mp-1265.cif
正在转换mp-12682.cif
正在转换mp-12707.cif
正在转换mp-12769.cif
正在转换mp-12770.cif
正在转换mp-12776.cif
正在转换mp-12910.cif
正在转换mp-12948.cif
正在转换mp-13051.cif
正在转换mp-13134.cif
正在转换mp-13146.cif
正在转换mp-13150.cif
正在转换mp-13152.cif
正在转换mp-13173.cif
正在转换mp-13178.cif
正在转换mp-1319.cif
正在转换mp-13383.cif
正在转换mp-13384.cif
正在转换mp-13385.cif
正在转换mp-13449.cif
正在转换mp-13682.cif
正在转换mp-13870.cif
正在转换mp-13976.cif
正在转换mp-1404.cif
正在转换mp-1419.cif
正在转换mp-1434.cif
正在转换mp-1469.cif
正在转换mp-1507.cif
正在转换mp-1566.cif
正在转换mp-15679.cif
正在转换mp-1572.cif
正在转换mp-1581.cif
正在转换mp-1582.cif
正在转换mp-1602.cif
正在转换mp-1634.cif
正在转换mp-1641.cif
正在转换mp-1644.cif
正在转换mp-16755.cif
正在转换mp-1683.cif
正在转换mp-1690.cif
正在转换mp-16911.cif
正在转换mp-17146.cif
正在转换mp-17287.cif
正在转换mp-1754.cif
正在转换mp-1797.cif
正在转换mp-1802.cif
正在转换mp-1821.cif
正在转换mp-1863.cif
正在转换mp-19052.cif
正在转换mp-19074.cif
正在转换mp-19079.cif
正在转换mp-1907.cif
正在转换mp-19405.cif
正在转换mp-1943.cif
正在转换mp-19443.cif
正在转换mp-1967.cif
正在转换mp-19715.cif
正在转换mp-19744.cif
正在转换mp-19790.cif
正在转换mp-19845.cif
正在转换mp-19846.cif
正在转换mp-1984.cif
正在转换mp-19888.cif
正在转换mp-19921.cif
正在转换mp-19933.cif
正在转换mp-19990.cif
正在转换mp-20130.cif
正在转换mp-20175.cif
正在转换mp-20210.cif
正在转换mp-20242.cif
正在转换mp-20305.cif
正在转换mp-20307.cif
正在转换mp-20311.cif
正在转换mp-20351.cif
正在转换mp-20422.cif
正在转换mp-2076.cif
正在转换mp-2089.cif
正在转换mp-20902.cif
正在转换mp-2097.cif
正在转换mp-21038.cif
正在转换mp-21096.cif
正在转换mp-21183.cif
正在转换mp-21208.cif
正在转换mp-21260.cif
正在转换mp-21273.cif
正在转换mp-21276.cif
正在转换mp-2129.cif
正在转换mp-21325.cif
正在转换mp-21335.cif
正在转换mp-21363.cif
正在转换mp-21380.cif
正在转换mp-21409.cif
正在转换mp-21468.cif
正在转换mp-2156.cif
正在转换mp-2168.cif
正在转换mp-2189.cif
正在转换mp-2194.cif
正在转换mp-2201.cif
正在转换mp-2207.cif
正在转换mp-2232.cif
正在转换mp-2237.cif
正在转换mp-22392.cif
正在转换mp-22412.cif
正在转换mp-224.cif
正在转换mp-22582.cif
正在转换mp-22661.cif
正在转换mp-22693.cif
正在转换mp-22813.cif
正在转换mp-22853.cif
正在转换mp-22855.cif
正在转换mp-2285.cif
正在转换mp-22861.cif
正在转换mp-22863.cif
正在转换mp-22868.cif
正在转换mp-22878.cif
正在转换mp-22883.cif
正在转换mp-22893.cif
正在转换mp-228.cif
正在转换mp-22917.cif
正在转换mp-22923.cif
正在转换mp-22966.cif
正在转换mp-22969.cif
正在转换mp-22971.cif
正在转换mp-22996.cif
正在转换mp-23007.cif
正在转换mp-23020.cif
正在转换mp-23041.cif
正在转换mp-23150.cif
正在转换mp-23164.cif
正在转换mp-23176.cif
正在转换mp-23184.cif
正在转换mp-23192.cif
正在转换mp-23204.cif
正在转换mp-23205.cif
正在转换mp-23210.cif
正在转换mp-23216.cif
正在转换mp-23225.cif
正在转换mp-23229.cif
正在转换mp-23230.cif
正在转换mp-23250.cif
正在转换mp-23264.cif
正在转换mp-23267.cif
正在转换mp-23269.cif
正在转换mp-23280.cif
正在转换mp-23281.cif
正在转换mp-23288.cif
正在转换mp-23290.cif
正在转换mp-23294.cif
正在转换mp-23312.cif
正在转换mp-23317.cif
正在转换mp-23324.cif
正在转换mp-2336.cif
正在转换mp-23376.cif
正在转换mp-23435.cif
正在转换mp-23504.cif
正在转换mp-23514.cif
正在转换mp-235.cif
正在转换mp-23697.cif
正在转换mp-236.cif
正在转换mp-23724.cif
正在转换mp-23739.cif
正在转换mp-23759.cif
正在转换mp-2418.cif
正在转换mp-24290.cif
正在转换mp-24416.cif
正在转换mp-2447.cif
正在转换mp-2450.cif
正在转换mp-24809.cif
正在转换mp-24814.cif
正在转换mp-24944.cif
正在转换mp-24972.cif
正在转换mp-2507.cif
正在转换mp-25433.cif
正在转换mp-25558.cif
正在转换mp-2556.cif
正在转换mp-2574.cif
正在转换mp-2578.cif
正在转换mp-2593.cif
正在转换mp-2657.cif
正在转换mp-2693.cif
正在转换mp-27178.cif
正在转换mp-27215.cif
正在转换mp-27240.cif
正在转换mp-27249.cif
正在转换mp-27257.cif
正在转换mp-27296.cif
正在转换mp-27302.cif
正在转换mp-27319.cif
正在转换mp-27337.cif
正在转换mp-27340.cif
正在转换mp-27361.cif
正在转换mp-27362.cif
正在转换mp-27399.cif
正在转换mp-27440.cif
正在转换mp-27462.cif
正在转换mp-27465.cif
正在转换mp-27507.cif
正在转换mp-27543.cif
正在转换mp-2755.cif
正在转换mp-27630.cif
正在转换mp-27634.cif
正在转换mp-27647.cif
正在转换mp-27648.cif
正在转换mp-27655.cif
正在转换mp-27699.cif
正在转换mp-27708.cif
正在转换mp-27734.cif
正在转换mp-27785.cif
正在转换mp-27814.cif
正在转换mp-27815.cif
正在转换mp-27848.cif
正在转换mp-27868.cif
正在转换mp-27901.cif
正在转换mp-27902.cif
正在转换mp-27922.cif
正在转换mp-27924.cif
正在转换mp-27928.cif
正在转换mp-27948.cif
正在转换mp-27952.cif
正在转换mp-27989.cif
正在转换mp-28049.cif
正在转换mp-28064.cif
正在转换mp-28077.cif
正在转换mp-2809.cif
正在转换mp-28116.cif
正在转换mp-28117.cif
正在转换mp-28118.cif
正在转换mp-2815.cif
正在转换mp-28192.cif
正在转换mp-28208.cif
正在转换mp-28220.cif
正在转换mp-28240.cif
正在转换mp-28248.cif
正在转换mp-28256.cif
正在转换mp-28301.cif
正在转换mp-28330.cif
正在转换mp-28372.cif
正在转换mp-28384.cif
正在转换mp-28390.cif
正在转换mp-28393.cif
正在转换mp-28405.cif
正在转换mp-28406.cif
正在转换mp-2841.cif
正在转换mp-28480.cif
正在转换mp-28491.cif
正在转换mp-28544.cif
正在转换mp-2858.cif
正在转换mp-28667.cif
正在转换mp-28683.cif
正在转换mp-28693.cif
正在转换mp-28745.cif
正在转换mp-28753.cif
正在转换mp-28754.cif
正在转换mp-28838.cif
正在转换mp-28860.cif
正在转换mp-28866.cif
正在转换mp-28885.cif
正在转换mp-28910.cif
正在转换mp-28919.cif
正在转换mp-28938.cif
正在转换mp-28940.cif
正在转换mp-29016.cif
正在转换mp-29117.cif
正在转换mp-29179.cif
正在转换mp-29249.cif
正在转换mp-29263.cif
正在转换mp-2928.cif
正在转换mp-29407.cif
正在转换mp-29408.cif
正在转换mp-29422.cif
正在转换mp-29427.cif
正在转换mp-29428.cif
正在转换mp-29465.cif
正在转换mp-29487.cif
正在转换mp-29502.cif
正在转换mp-29510.cif
正在转换mp-29541.cif
正在转换mp-29567.cif
正在转换mp-29643.cif
正在转换mp-29659.cif
正在转换mp-29663.cif
正在转换mp-29671.cif
正在转换mp-29689.cif
正在转换mp-29713.cif
正在转换mp-2977.cif
正在转换mp-29803.cif
正在转换mp-29866.cif
正在转换mp-29870.cif
正在转换mp-29928.cif
正在转换mp-29941.cif
正在转换mp-29950.cif
正在转换mp-30025.cif
正在转换mp-30033.cif
正在转换mp-30058.cif
正在转换mp-30068.cif
正在转换mp-30092.cif
正在转换mp-30099.cif
正在转换mp-30106.cif
正在转换mp-30302.cif
正在转换mp-30341.cif
正在转换mp-30409.cif
正在转换mp-30908.cif
正在转换mp-30930.cif
正在转换mp-30938.cif
正在转换mp-30943.cif
正在转换mp-30945.cif
正在转换mp-30946.cif
正在转换mp-30953.cif
正在转换mp-30954.cif
正在转换mp-30979.cif
正在转换mp-30984.cif
正在转换mp-31015.cif
正在转换mp-31038.cif
正在转换mp-31070.cif
正在转换mp-31220.cif
正在转换mp-3123.cif
正在转换mp-31487.cif
正在转换mp-31495.cif
正在转换mp-31725.cif
正在转换mp-32450.cif
正在转换mp-32536.cif
正在转换mp-32887.cif
正在转换mp-3342.cif
正在转换mp-3382.cif
正在转换mp-34202.cif
正在转换mp-3468.cif
正在转换mp-368.cif
正在转换mp-3779.cif
正在转换mp-383.cif
正在转换mp-390.cif
正在转换mp-396.cif
正在转换mp-399.cif
正在转换mp-406.cif
正在转换mp-4246.cif
正在转换mp-4384.cif
正在转换mp-441.cif
正在转换mp-449.cif
正在转换mp-4608.cif
正在转换mp-4651.cif
正在转换mp-4853.cif
正在转换mp-48.cif
正在转换mp-500.cif
正在转换mp-5096.cif
正在转换mp-510536.cif
正在转换mp-523.cif
正在转换mp-5328.cif
正在转换mp-541582.cif
正在转换mp-5489.cif
正在转换mp-558110.cif
正在转换mp-558544.cif
正在转换mp-567724.cif
正在转换mp-567832.cif
正在转换mp-569544.cif
正在转换mp-571033.cif
正在转换mp-571133.cif
正在转换mp-572822.cif
正在转换mp-5745.cif
正在转换mp-5864.cif
正在转换mp-5986.cif
正在转换mp-599.cif
正在转换mp-602.cif
正在转换mp-604915.cif
正在转换mp-612.cif
正在转换mp-617.cif
正在转换mp-618883.cif
正在转换mp-632475.cif
正在转换mp-6543.cif
正在转换mp-661.cif
正在转换mp-662.cif
正在转换mp-665.cif
正在转换mp-66.cif
正在转换mp-672271.cif
正在转换mp-672.cif
正在转换mp-685055.cif
正在转换mp-691.cif
正在转换mp-6920.cif
正在转换mp-6930.cif
正在转换mp-694.cif
正在转换mp-6999.cif
正在转换mp-7007.cif
正在转换mp-7008.cif
正在转换mp-7029.cif
正在转换mp-7038.cif
正在转换mp-715324.cif
正在转换mp-715436.cif
正在转换mp-7208.cif
正在转换mp-7260.cif
正在转换mp-7280.cif
正在转换mp-740.cif
正在转换mp-7459.cif
正在转换mp-7487.cif
正在转换mp-755263.cif
正在转换mp-7581.cif
正在转换mp-7597.cif
正在转换mp-7617.cif
正在转换mp-762.cif
正在转换mp-7631.cif
正在转换mp-7705.cif
正在转换mp-7715.cif
正在转换mp-7760.cif
正在转换mp-7814.cif
正在转换mp-782.cif
正在转换mp-7834.cif
正在转换mp-7848.cif
正在转换mp-7859.cif
正在转换mp-7868.cif
正在转换mp-7926.cif
正在转换mp-794.cif
正在转换mp-7964.cif
正在转换mp-7991.cif
正在转换mp-8035.cif
正在转换mp-804.cif
正在转换mp-8374.cif
正在转换mp-8387.cif
正在转换mp-8390.cif
正在转换mp-8415.cif
正在转换mp-849079.cif
正在转换mp-8613.cif
正在转换mp-8616.cif
正在转换mp-8695.cif
正在转换mp-8911.cif
正在转换mp-8953.cif
正在转换mp-8954.cif
正在转换mp-9247.cif
正在转换mp-9251.cif
正在转换mp-9272.cif
正在转换mp-9330.cif
正在转换mp-9399.cif
正在转换mp-9429.cif
正在转换mp-9479.cif
正在转换mp-9481.cif
正在转换mp-9519.cif
正在转换mp-9561.cif
正在转换mp-960.cif
正在转换mp-9622.cif
正在转换mp-966.cif
正在转换mp-976058.cif
正在转换mp-9776.cif
正在转换mp-980.cif
正在转换mp-9813.cif
正在转换mp-9830.cif
正在转换mp-984.cif
正在转换mp-985829.cif
正在转换mp-985831.cif
正在转换mp-9889.cif
正在转换mp-9921.cif
正在转换mp-9936.cif
正在转换mp-995122.cif
正在转换mp-9984.cif
正在转换mp-9996.cif
正在转换mp-MoTe2Td.cif
正在转换mp-blackP.cif
正在转换mp-icsd-14390.cif
正在转换mp-icsd-152836.cif
正在转换mp-icsd-603582.cif
正在转换mp-icsd-625401.cif
正在转换mp-icsd-626718.cif
正在转换mp-icsd-645529.cif
正在转换mp-icsd-651404.cif
正在转换mvc-11221.cif
正在转换mvc-11238.cif
正在转换mvc-13245.cif
正在转换mvc-13391.cif
正在转换mvc-13555.cif
正在转换mvc-6929.cif
正在转换mvc-6931.cif
正在转换mvc-6946.cif
正在转换mp-10326.cif
正在转换mp-11973.cif
正在转换mp-12523.cif
正在转换mp-13024.cif
正在转换mp-13680.cif
正在转换mp-1411.cif
正在转换mp-18609.cif
正在转换mp-20356.cif

正在转换mp-20526.cif
正在转换mp-20579.cif
正在转换mp-20747.cif
正在转换mp-22272.cif
正在转换mp-22424.cif
正在转换mp-23178.cif
正在转换mp-23307.cif
正在转换mp-27391.cif
正在转换mp-27857.cif
正在转换mp-27941.cif
正在转换mp-28153.cif
正在转换mp-28251.cif
正在转换mp-28414.cif
正在转换mp-28575.cif
正在转换mp-29116.cif
正在转换mp-29305.cif
正在转换mp-29831.cif
正在转换mp-31198.cif
正在转换mp-3387.cif
正在转换mp-4004.cif
正在转换mp-525.cif
正在转换mp-7149.cif
正在转换mp-8124.cif
正在转换mp-8482.cif
正在转换mp-9228.cif
正在转换mp-13963.cif
正在转换mp-158.cif
正在转换mp-15951.cif
正在转换mp-1640.cif
正在转换mp-16765.cif
正在转换mp-17173.cif
正在转换mp-1778.cif
正在转换mp-20066.cif
正在转换mp-20506.cif
正在转换mp-20826.cif
正在转换mp-2125.cif
正在转换mp-2284.cif
正在转换mp-22904.cif
正在转换mp-22957.cif
正在转换mp-22992.cif
正在转换mp-23002.cif
正在转换mp-23024.cif
正在转换mp-23209.cif
正在转换mp-23214.cif
正在转换mp-23232.cif
正在转换mp-23313.cif
正在转换mp-23559.cif
正在转换mp-23896.cif
正在转换mp-24242.cif
正在转换mp-25214.cif
正在转换mp-27127.cif
正在转换mp-27153.cif
正在转换mp-27393.cif
正在转换mp-27546.cif
正在转换mp-27638.cif
正在转换mp-27652.cif
正在转换mp-27697.cif
正在转换mp-27837.cif
正在转换mp-27891.cif
正在转换mp-27987.cif
正在转换mp-27988.cif
正在转换mp-27994.cif
正在转换mp-28019.cif
正在转换mp-28027.cif
正在转换mp-28095.cif
正在转换mp-28109.cif
正在转换mp-28243.cif
正在转换mp-28308.cif
正在转换mp-28439.cif
正在转换mp-28473.cif
正在转换mp-29535.cif
正在转换mp-30002.cif
正在转换mp-31212.cif
正在转换mp-3208.cif
正在转换mp-3250.cif
正在转换mp-36111.cif
正在转换mp-36248.cif
正在转换mp-36582.cif
正在转换mp-37091.cif
正在转换mp-37153.cif
正在转换mp-37879.cif
正在转换mp-37906.cif
正在转换mp-38117.cif
正在转换mp-38220.cif
正在转换mp-38970.cif
正在转换mp-4782.cif
正在转换mp-504769.cif
正在转换mp-505297.cif
正在转换mp-505366.cif
正在转换mp-505531.cif
正在转换mp-510281.cif
正在转换mp-510584.cif
正在转换mp-510624.cif
正在转换mp-510625.cif
正在转换mp-510733.cif
正在转换mp-5347.cif
正在转换mp-540570.cif
正在转换mp-540584.cif
正在转换mp-540957.cif
正在转换mp-541449.cif
正在转换mp-541911.cif
正在转换mp-541912.cif
正在转换mp-541989.cif
正在转换mp-542096.cif
正在转换mp-542846.cif
正在转换mp-545482.cif
正在转换mp-545820.cif
正在转换mp-546279.cif
正在转换mp-546684.cif
正在转换mp-5479.cif
正在转换mp-550070.cif
正在转换mp-550172.cif
正在转换mp-552729.cif
正在转换mp-552787.cif
正在转换mp-553303.cif
正在转换mp-553896.cif
正在转换mp-554089.cif
正在转换mp-554151.cif
正在转换mp-554278.cif
正在转换mp-554573.cif
正在转换mp-554955.cif
正在转换mp-555123.cif
正在转换mp-555235.cif
正在转换mp-555359.cif
正在转换mp-555403.cif
正在转换mp-555410.cif
正在转换mp-555763.cif
正在转换mp-555911.cif
正在转换mp-555934.cif
正在转换mp-556194.cif
正在转换mp-556197.cif
正在转换mp-556417.cif
正在转换mp-556424.cif
正在转换mp-556520.cif
正在转换mp-556582.cif
正在转换mp-556585.cif
正在转换mp-556742.cif
正在转换mp-556750.cif
正在转换mp-556767.cif
正在转换mp-556911.cif
正在转换mp-556953.cif
正在转换mp-557158.cif
正在转换mp-557257.cif
正在转换mp-557266.cif
正在转换mp-557308.cif
正在转换mp-557373.cif
正在转换mp-557397.cif
正在转换mp-557500.cif
正在转换mp-557519.cif
正在转换mp-557539.cif
正在转换mp-557592.cif
正在转换mp-557668.cif
正在转换mp-557772.cif
正在转换mp-557938.cif
正在转换mp-558071.cif
正在转换mp-558111.cif
正在转换mp-558118.cif
正在转换mp-558134.cif
正在转换mp-558380.cif
正在转换mp-558749.cif
正在转换mp-558761.cif
正在转换mp-558836.cif
正在转换mp-558838.cif
正在转换mp-558852.cif
正在转换mp-558864.cif
正在转换mp-559091.cif
正在转换mp-559161.cif
正在转换mp-559408.cif
正在转换mp-559550.cif
正在转换mp-559760.cif
正在转换mp-559798.cif
正在转换mp-560008.cif
正在转换mp-560023.cif
正在转换mp-560161.cif
正在转换mp-560588.cif
正在转换mp-560902.cif
正在转换mp-560976.cif
正在转换mp-561078.cif
正在转换mp-561238.cif
正在转换mp-561258.cif
正在转换mp-561317.cif
正在转换mp-561397.cif
正在转换mp-561591.cif
正在转换mp-561664.cif
正在转换mp-561800.cif
正在转换mp-562100.cif
正在转换mp-565784.cif
正在转换mp-566179.cif
正在转换mp-566285.cif
正在转换mp-566641.cif
正在转换mp-566755.cif
正在转换mp-567259.cif
正在转换mp-567279.cif
正在转换mp-567354.cif
正在转换mp-567441.cif
正在转换mp-567478.cif
正在转换mp-567504.cif
正在转换mp-567505.cif
正在转换mp-567525.cif
正在转换mp-567809.cif
正在转换mp-567817.cif
正在转换mp-567907.cif
正在转换mp-567931.cif
正在转换mp-568018.cif
正在转换mp-568032.cif
正在转换mp-568233.cif
正在转换mp-568264.cif
正在转换mp-568342.cif
正在转换mp-568536.cif
正在转换mp-568592.cif
正在转换mp-568598.cif
正在转换mp-568619.cif
正在转换mp-568656.cif
正在转换mp-568661.cif
正在转换mp-568690.cif
正在转换mp-568722.cif
正在转换mp-568971.cif
正在转换mp-569028.cif
正在转换mp-569066.cif
正在转换mp-569152.cif
正在转换mp-569581.cif
正在转换mp-569610.cif
正在转换mp-569623.cif
正在转换mp-569715.cif
正在转换mp-569779.cif
正在转换mp-570008.cif
正在转换mp-570062.cif
正在转换mp-570081.cif
正在转换mp-570099.cif
正在转换mp-570157.cif
正在转换mp-570172.cif
正在转换mp-570213.cif
正在转换mp-570219.cif
正在转换mp-570256.cif
正在转换mp-570259.cif
正在转换mp-570268.cif
正在转换mp-570324.cif
正在转换mp-570538.cif
正在转换mp-570553.cif
正在转换mp-570589.cif
正在转换mp-570823.cif
正在转换mp-570886.cif
正在转换mp-571035.cif
正在转换mp-571122.cif
正在转换mp-571166.cif
正在转换mp-571210.cif
正在转换mp-571279.cif
正在转换mp-571442.cif
正在转换mp-571461.cif
正在转换mp-571471.cif
正在转换mp-571518.cif
正在转换mp-571550.cif
正在转换mp-571648.cif
正在转换mp-578614.cif
正在转换mp-580226.cif
正在转换mp-581024.cif
正在转换mp-604884.cif
正在转换mp-604908.cif
正在转换mp-604910.cif
正在转换mp-605034.cif
正在转换mp-614013.cif
正在转换mp-616481.cif
正在转换mp-625055.cif
正在转换mp-625199.cif
正在转换mp-626794.cif
正在转换mp-627151.cif
正在转换mp-632326.cif
正在转换mp-634859.cif
正在转换mp-643101.cif
正在转换mp-643257.cif
正在转换mp-643367.cif
正在转换mp-644203.cif
正在转换mp-644225.cif
正在转换mp-6462.cif
正在转换mp-676284.cif
正在转换mp-676315.cif
正在转换mp-685146.cif
正在转换mp-690785.cif
正在转换mp-690794.cif
正在转换mp-697030.cif
正在转换mp-697038.cif
正在转换mp-697044.cif
正在转换mp-697096.cif
正在转换mp-707135.cif
正在转换mp-714882.cif
正在转换mp-714976.cif
正在转换mp-715434.cif
正在转换mp-715460.cif
正在转换mp-7293.cif
正在转换mp-752602.cif
正在转换mp-752658.cif
正在转换mp-752753.cif
正在转换mp-752927.cif
正在转换mp-753575.cif
正在转换mp-753594.cif
正在转换mp-753746.cif
正在转换mp-754031.cif
正在转换mp-754065.cif
正在转换mp-754311.cif
正在转换mp-754540.cif
正在转换mp-754596.cif
正在转换mp-754658.cif
正在转换mp-754815.cif
正在转换mp-755287.cif
正在转换mp-755293.cif
正在转换mp-755336.cif
正在转换mp-755565.cif
正在转换mp-755689.cif
正在转换mp-759883.cif
正在转换mp-760375.cif
正在转换mp-760403.cif
正在转换mp-760417.cif
正在转换mp-761554.cif
正在转换mp-7623.cif
正在转换mp-764362.cif
正在转换mp-764673.cif
正在转换mp-765885.cif
正在转换mp-766862.cif
正在转换mp-768368.cif
正在转换mp-768680.cif
正在转换mp-771247.cif
正在转换mp-772231.cif
正在转换mp-772359.cif
正在转换mp-773137.cif
正在转换mp-773602.cif
正在转换mp-774160.cif
正在转换mp-776230.cif
正在转换mp-7825.cif
正在转换mp-7949.cif
正在转换mp-80.cif
正在转换mp-8402.cif
正在转换mp-862631.cif
正在转换mp-862868.cif
正在转换mp-864746.cif
正在转换mp-864954.cif
正在转换mp-865101.cif
正在转换mp-866062.cif
正在转换mp-866132.cif
正在转换mp-866141.cif
正在转换mp-866818.cif
正在转换mp-867168.cif
正在转换mp-867192.cif
正在转换mp-867194.cif
正在转换mp-867339.cif
正在转换mp-867695.cif
正在转换mp-867785.cif
正在转换mp-8677.cif
正在转换mp-8732.cif
正在转换mp-909.cif
正在转换mp-935811.cif
正在转换mp-945077.cif
正在转换mp-961684.cif
正在转换mp-961685.cif
正在转换mp-971787.cif
正在转换mp-972794.cif
正在转换mp-973199.cif
正在转换mp-978553.cif
正在转换mp-978567.cif
正在转换mp-995193.cif
正在转换mp-996956.cif
正在转换mp-997011.cif
正在转换mp-997020.cif
正在转换mp-997092.cif
正在转换mp-998912.cif
正在转换mvc-10954.cif
正在转换mvc-11573.cif
正在转换mvc-13985.cif
正在转换mvc-14413.cif
正在转换mvc-14734.cif
正在转换mvc-15971.cif
正在转换mp-10058.cif
正在转换mp-10213.cif
正在转换mp-10231.cif
正在转换mp-10371.cif
正在转换mp-10553.cif
正在转换mp-10643.cif
正在转换mp-10645.cif
正在转换mp-10648.cif
正在转换mp-10676.cif
正在转换mp-10761.cif
正在转换mp-10900.cif
正在转换mp-10906.cif
正在转换mp-11209.cif
正在转换mp-11213.cif
正在转换mp-11217.cif
正在转换mp-11251.cif
正在转换mp-11342.cif
正在转换mp-11364.cif
正在转换mp-11433.cif
正在转换mp-11553.cif
正在转换mp-11701.cif
正在转换mp-11815.cif
正在转换mp-12372.cif
正在转换mp-12546.cif
正在转换mp-12672.cif
正在转换mp-12750.cif
正在转换mp-12794.cif
正在转换mp-13126.cif
正在转换mp-13357.cif
正在转换mp-13497.cif
正在转换mp-13498.cif
正在转换mp-14112.cif
正在转换mp-14815.cif
正在转换mp-1563.cif
正在转换mp-1667.cif
正在转换mp-16762.cif
正在转换mp-17438.cif
正在转换mp-1752.cif
正在转换mp-17939.cif
正在转换mp-18075.cif
正在转换mp-1814.cif
正在转换mp-18305.cif
正在转换mp-1834.cif
正在转换mp-18407.cif
正在转换mp-1861.cif
正在转换mp-18637.cif
正在转换mp-18731.cif
正在转换mp-19431.cif
正在转换mp-19433.cif
正在转换mp-1948.cif
正在转换mp-19755.cif
正在转换mp-19849.cif
正在转换mp-19878.cif
正在转换mp-19984.cif
正在转换mp-20004.cif
正在转换mp-20106.cif
正在转换mp-20107.cif
正在转换mp-20120.cif
正在转换mp-20122.cif
正在转换mp-20134.cif
正在转换mp-20169.cif
正在转换mp-20177.cif
正在转换mp-20184.cif
正在转换mp-20203.cif
正在转换mp-20315.cif
正在转换mp-20494.cif
正在转换mp-20518.cif
正在转换mp-20551.cif
正在转换mp-20560.cif
正在转换mp-20597.cif
正在转换mp-20617.cif
正在转换mp-20629.cif
正在转换mp-20754.cif
正在转换mp-20762.cif
正在转换mp-20765.cif
正在转换mp-20779.cif
正在转换mp-20797.cif
正在转换mp-20994.cif
正在转换mp-21020.cif
正在转换mp-21055.cif
正在转换mp-21062.cif
正在转换mp-21103.cif
正在转换mp-21188.cif
正在转换mp-21204.cif
正在转换mp-21210.cif
正在转换mp-21239.cif
正在转换mp-21264.cif
正在转换mp-21267.cif
正在转换mp-21358.cif
正在转换mp-2136.cif
正在转换mp-21413.cif
正在转换mp-21439.cif
正在转换mp-2145.cif
正在转换mp-22125.cif
正在转换mp-22144.cif
正在转换mp-22210.cif
正在转换mp-22217.cif
正在转换mp-22310.cif
正在转换mp-22449.cif
正在转换mp-22558.cif
正在转换mp-22667.cif
正在转换mp-22701.cif
正在转换mp-22753.cif
正在转换mp-22850.cif
正在转换mp-22892.cif
正在转换mp-22932.cif
正在转换mp-22959.cif
正在转换mp-23121.cif
正在转换mp-23219.cif
正在转换mp-23223.cif
正在转换mp-23228.cif
正在转换mp-23247.cif
正在转换mp-23412.cif
正在转换mp-23521.cif
正在转换mp-23694.cif
正在转换mp-23866.cif
正在转换mp-2416.cif
正在转换mp-24810.cif
正在转换mp-24848.cif
正在转换mp-24877.cif
正在转换mp-25469.cif
正在转换mp-25470.cif
正在转换mp-27219.cif
正在转换mp-27411.cif
正在转换mp-27449.cif
正在转换mp-27656.cif
正在转换mp-27664.cif
正在转换mp-27682.cif
正在转换mp-27683.cif
正在转换mp-27863.cif
正在转换mp-27935.cif
正在转换mp-27943.cif
正在转换mp-28011.cif
正在转换mp-28096.cif
正在转换mp-28100.cif
正在转换mp-28128.cif
正在转换mp-28136.cif
正在转换mp-28175.cif
正在转换mp-28282.cif
正在转换mp-28341.cif
正在转换mp-28357.cif
正在转换mp-28429.cif
正在转换mp-28553.cif
正在转换mp-28757.cif
正在转换mp-28832.cif
正在转换mp-28878.cif
正在转换mp-28947.cif
正在转换mp-28963.cif
正在转换mp-29015.cif
正在转换mp-29057.cif
正在转换mp-29154.cif
正在转换mp-29238.cif

正在转换mp-29458.cif
正在转换mp-29459.cif
正在转换mp-29607.cif
正在转换mp-29694.cif
正在转换mp-29744.cif
正在转换mp-29863.cif
正在转换mp-29881.cif
正在转换mp-30139.cif
正在转换mp-30228.cif
正在转换mp-30287.cif
正在转换mp-30332.cif
正在转换mp-30362.cif
正在转换mp-30427.cif
正在转换mp-3047.cif
正在转换mp-306.cif
正在转换mp-30777.cif
正在转换mp-30913.cif
正在转换mp-31040.cif
正在转换mp-31045.cif
正在转换mp-31053.cif
正在转换mp-31406.cif
正在转换mp-31474.cif
正在转换mp-31900.cif
正在转换mp-31999.cif
正在转换mp-32131.cif
正在转换mp-32541.cif
正在转换mp-3257.cif
正在转换mp-3392.cif
正在转换mp-349.cif
正在转换mp-3700.cif
正在转换mp-37514.cif
正在转换mp-3871.cif
正在转换mp-3886.cif
正在转换mp-4391.cif
正在转换mp-4488.cif
正在转换mp-4571.cif
正在转换mp-4662.cif
正在转换mp-4663.cif
正在转换mp-4674.cif
正在转换mp-4678.cif
正在转换mp-5045.cif
正在转换mp-5443.cif
正在转换mp-5446.cif
正在转换mp-5603.cif
正在转换mp-6094.cif
正在转换mp-641.cif
正在转换mp-6669.cif
正在转换mp-6789.cif
正在转换mp-6907.cif
正在转换mp-6913.cif
正在转换mp-726.cif
正在转换mp-7483.cif
正在转换mp-7558.cif
正在转换mp-7559.cif
正在转换mp-7645.cif
正在转换mp-7701.cif
正在转换mp-7708.cif
正在转换mp-7744.cif
正在转换mp-7794.cif
正在转换mp-7925.cif
正在转换mp-7932.cif
正在转换mp-7954.cif
正在转换mp-7962.cif
正在转换mp-8045.cif
正在转换mp-8132.cif
正在转换mp-8140.cif
正在转换mp-8315.cif
正在转换mp-8435.cif
正在转换mp-8644.cif
正在转换mp-9102.cif
正在转换mp-9371.cif
正在转换mp-9390.cif
正在转换mp-9592.cif
正在转换mp-974.cif
正在转换mp-9810.cif
正在转换mp-9828.cif
正在转换mp-9948.cif
正在转换mp-9950.cif
正在转换mp-1001080.cif
正在转换mp-1006118.cif
正在转换mp-1007824.cif
正在转换mp-1007857.cif
正在转换mp-1008600.cif
正在转换mp-1008626.cif
正在转换mp-1008682.cif
正在转换mp-1008860.cif
正在转换mp-1008902.cif
正在转换mp-1009071.cif
正在转换mp-1009581.cif
正在转换mp-1009641.cif
正在转换mp-1009757.cif
正在转换mp-1011374.cif
正在转换mp-1012435.cif
正在转换mp-1013525.cif
正在转换mp-1013526.cif
正在转换mp-1013750.cif
正在转换mp-1013900.cif
正在转换mp-1014296.cif
正在转换mp-1014298.cif
正在转换mp-1014509.cif
正在转换mp-1017565.cif
正在转换mp-1017630.cif
正在转换mp-1018107.cif
正在转换mp-1018115.cif
正在转换mp-1018138.cif
正在转换mp-1018150.cif
正在转换mp-1018275.cif
正在转换mp-1018648.cif
正在转换mp-1018655.cif
正在转换mp-1018731.cif
正在转换mp-1018806.cif
正在转换mp-1018807.cif
正在转换mp-1018808.cif
正在转换mp-1018809.cif
正在转换mp-1018813.cif
正在转换mp-1018891.cif
正在转换mp-1018897.cif
正在转换mp-1019086.cif
正在转换mp-1019099.cif
正在转换mp-1019276.cif
正在转换mp-1019322.cif
正在转换mp-1019509.cif
正在转换mp-1019779.cif
正在转换mp-1021328.cif
正在转换mp-1021464.cif
正在转换mp-1021503.cif
正在转换mp-1021511.cif
正在转换mp-1022730.cif
正在转换mp-1022732.cif
正在转换mp-1023900.cif
正在转换mp-1023925.cif
正在转换mp-1023926.cif
正在转换mp-1023928.cif
正在转换mp-1023929.cif
正在转换mp-1023931.cif
正在转换mp-1023933.cif
正在转换mp-1023935.cif
正在转换mp-1023936.cif
正在转换mp-1023939.cif
正在转换mp-1023940.cif
正在转换mp-1023942.cif
正在转换mp-1023943.cif
正在转换mp-1023945.cif
正在转换mp-1023953.cif
正在转换mp-1023955.cif
正在转换mp-1023959.cif
正在转换mp-1024958.cif
正在转换mp-1025099.cif
正在转换mp-1025115.cif
正在转换mp-1025166.cif
正在转换mp-1025168.cif
正在转换mp-1025204.cif
正在转换mp-1025250.cif
正在转换mp-1025305.cif
正在转换mp-1025312.cif
正在转换mp-1025314.cif
正在转换mp-1025340.cif
正在转换mp-1025350.cif
正在转换mp-1025373.cif
正在转换mp-1025374.cif
正在转换mp-1025388.cif
正在转换mp-1025395.cif
正在转换mp-1025400.cif
正在转换mp-1025442.cif
正在转换mp-1025459.cif
正在转换mp-1025470.cif
正在转换mp-1025482.cif
正在转换mp-1025520.cif
正在转换mp-1025522.cif
正在转换mp-1025537.cif
正在转换mp-1025567.cif
正在转换mp-1025571.cif
正在转换mp-1025572.cif
正在转换mp-1025573.cif
正在转换mp-1025574.cif
正在转换mp-1025575.cif
正在转换mp-1025576.cif
正在转换mp-1025578.cif
正在转换mp-1025583.cif
正在转换mp-1025584.cif
正在转换mp-1025585.cif
正在转换mp-1025586.cif
正在转换mp-1025587.cif
正在转换mp-1025588.cif
正在转换mp-1025589.cif
正在转换mp-1025598.cif
正在转换mp-1025626.cif
正在转换mp-1025637.cif
正在转换mp-1025649.cif
正在转换mp-1025652.cif
正在转换mp-1025654.cif
正在转换mp-1025656.cif
正在转换mp-1025663.cif
正在转换mp-1025668.cif
正在转换mp-1025675.cif
正在转换mp-1025678.cif
正在转换mp-1025685.cif
正在转换mp-1025689.cif
正在转换mp-1025691.cif
正在转换mp-1025702.cif
正在转换mp-1025705.cif
正在转换mp-1025716.cif
正在转换mp-1025722.cif
正在转换mp-1025728.cif
正在转换mp-1025732.cif
正在转换mp-1025740.cif
正在转换mp-1025743.cif
正在转换mp-1025747.cif
正在转换mp-1025748.cif
正在转换mp-1025752.cif
正在转换mp-1025768.cif
正在转换mp-1025769.cif
正在转换mp-1025772.cif
正在转换mp-1025774.cif
正在转换mp-1025779.cif
正在转换mp-1025781.cif
正在转换mp-1025787.cif
正在转换mp-1025799.cif
正在转换mp-1025806.cif
正在转换mp-1025815.cif
正在转换mp-1025816.cif
正在转换mp-1025819.cif
正在转换mp-1025824.cif
正在转换mp-1025838.cif
正在转换mp-1025856.cif
正在转换mp-1025866.cif
正在转换mp-1025870.cif
正在转换mp-1025879.cif
正在转换mp-1025881.cif
正在转换mp-1025888.cif
正在转换mp-1025895.cif
正在转换mp-1025896.cif
正在转换mp-1025898.cif
正在转换mp-1025906.cif
正在转换mp-1025910.cif
正在转换mp-1025911.cif
正在转换mp-1025917.cif
正在转换mp-1025919.cif
正在转换mp-1025921.cif
正在转换mp-1025923.cif
正在转换mp-1025925.cif
正在转换mp-1025926.cif
正在转换mp-1025933.cif
正在转换mp-1025934.cif
正在转换mp-1025937.cif
正在转换mp-1025941.cif
正在转换mp-1025948.cif
正在转换mp-1025986.cif
正在转换mp-1026002.cif
正在转换mp-1026016.cif
正在转换mp-1026020.cif
正在转换mp-1026027.cif
正在转换mp-1026034.cif
正在转换mp-1026347.cif
正在转换mp-1026348.cif
正在转换mp-1026349.cif
正在转换mp-1026350.cif
正在转换mp-1026351.cif
正在转换mp-1026352.cif
正在转换mp-1026356.cif
正在转换mp-1026362.cif
正在转换mp-1026909.cif
正在转换mp-1026910.cif
正在转换mp-1026911.cif
正在转换mp-1026912.cif
正在转换mp-1026916.cif
正在转换mp-1026917.cif
正在转换mp-1026927.cif
正在转换mp-1026929.cif
正在转换mp-1026933.cif
正在转换mp-1026941.cif
正在转换mp-1026946.cif
正在转换mp-1026958.cif
正在转换mp-1026969.cif
正在转换mp-1026974.cif
正在转换mp-1026975.cif
正在转换mp-1026976.cif
正在转换mp-1026979.cif
正在转换mp-1026980.cif
正在转换mp-1026988.cif
正在转换mp-1027001.cif
正在转换mp-1027015.cif
正在转换mp-1027051.cif
正在转换mp-1027058.cif
正在转换mp-1027061.cif
正在转换mp-1027070.cif
正在转换mp-1027080.cif
正在转换mp-1027091.cif
正在转换mp-1027096.cif
正在转换mp-1027115.cif
正在转换mp-1027127.cif
正在转换mp-1027129.cif
正在转换mp-1027132.cif
正在转换mp-1027134.cif
正在转换mp-1027138.cif
正在转换mp-1027139.cif
正在转换mp-1027141.cif
正在转换mp-1027143.cif
正在转换mp-1027144.cif
正在转换mp-1027145.cif
正在转换mp-1027147.cif
正在转换mp-1027149.cif
正在转换mp-1027152.cif
正在转换mp-1027153.cif
正在转换mp-1027159.cif
正在转换mp-1027164.cif
正在转换mp-1027170.cif
正在转换mp-1027269.cif
正在转换mp-1027273.cif
正在转换mp-1027274.cif
正在转换mp-1027281.cif
正在转换mp-1027292.cif
正在转换mp-1027293.cif
正在转换mp-1027294.cif
正在转换mp-1027303.cif
正在转换mp-1027309.cif
正在转换mp-1027311.cif
正在转换mp-1027328.cif
正在转换mp-1027334.cif
正在转换mp-1027335.cif
正在转换mp-1027337.cif
正在转换mp-1027339.cif
正在转换mp-1027352.cif
正在转换mp-1027358.cif
正在转换mp-1027359.cif
正在转换mp-1027375.cif
正在转换mp-1027376.cif
正在转换mp-1027379.cif
正在转换mp-1027391.cif
正在转换mp-1027404.cif
正在转换mp-1027407.cif
正在转换mp-1027409.cif
正在转换mp-1027412.cif
正在转换mp-1027424.cif
正在转换mp-1027437.cif
正在转换mp-1027440.cif
正在转换mp-1027443.cif
正在转换mp-1027461.cif
正在转换mp-1027472.cif
正在转换mp-1027473.cif
正在转换mp-1027474.cif
正在转换mp-1027480.cif
正在转换mp-1027483.cif
正在转换mp-1027486.cif
正在转换mp-1027492.cif
正在转换mp-1027512.cif
正在转换mp-1027517.cif
正在转换mp-1027524.cif
正在转换mp-1027525.cif
正在转换mp-1027526.cif
正在转换mp-1027530.cif
正在转换mp-1027537.cif
正在转换mp-1027547.cif
正在转换mp-1027549.cif
正在转换mp-1027550.cif
正在转换mp-1027551.cif
正在转换mp-1027569.cif
正在转换mp-1027576.cif
正在转换mp-1027579.cif
正在转换mp-1027580.cif
正在转换mp-1027594.cif
正在转换mp-1027600.cif
正在转换mp-1027607.cif
正在转换mp-1027608.cif
正在转换mp-1027609.cif
正在转换mp-1027624.cif
正在转换mp-1027634.cif
正在转换mp-1027641.cif
正在转换mp-1027646.cif
正在转换mp-1027647.cif
正在转换mp-1027658.cif
正在转换mp-1027663.cif
正在转换mp-1027671.cif
正在转换mp-1027672.cif
正在转换mp-1027682.cif
正在转换mp-1027687.cif
正在转换mp-1027692.cif
正在转换mp-1027700.cif
正在转换mp-1027711.cif
正在转换mp-1027714.cif
正在转换mp-1027721.cif
正在转换mp-1027722.cif
正在转换mp-1027729.cif
正在转换mp-1027765.cif
正在转换mp-1027780.cif
正在转换mp-1027795.cif
正在转换mp-1027801.cif
正在转换mp-1027802.cif
正在转换mp-1027818.cif
正在转换mp-1027890.cif
正在转换mp-1027894.cif
正在转换mp-1027916.cif
正在转换mp-1027980.cif
正在转换mp-1028409.cif
正在转换mp-1028414.cif
正在转换mp-1028416.cif
正在转换mp-1028419.cif
正在转换mp-1028420.cif
正在转换mp-1028434.cif
正在转换mp-1028439.cif
正在转换mp-1028441.cif
正在转换mp-1028445.cif
正在转换mp-1028452.cif
正在转换mp-1028459.cif
正在转换mp-1028467.cif
正在转换mp-1028468.cif
正在转换mp-1028478.cif
正在转换mp-1028483.cif
正在转换mp-1028487.cif
正在转换mp-1028488.cif
正在转换mp-1028492.cif
正在转换mp-1028505.cif
正在转换mp-1028510.cif
正在转换mp-1028512.cif
正在转换mp-1028514.cif
正在转换mp-1028525.cif
正在转换mp-1028526.cif
正在转换mp-1028531.cif
正在转换mp-1028535.cif
正在转换mp-1028539.cif
正在转换mp-1028541.cif
正在转换mp-1028542.cif
正在转换mp-1028544.cif
正在转换mp-1028558.cif
正在转换mp-1028570.cif
正在转换mp-1028576.cif
正在转换mp-1028583.cif
正在转换mp-1028586.cif
正在转换mp-1028589.cif
正在转换mp-1028592.cif
正在转换mp-1028594.cif
正在转换mp-1028598.cif
正在转换mp-1028622.cif
正在转换mp-1028626.cif
正在转换mp-1028635.cif
正在转换mp-1028642.cif
正在转换mp-1028643.cif
正在转换mp-1028646.cif
正在转换mp-1028653.cif
正在转换mp-1028654.cif
正在转换mp-1028663.cif
正在转换mp-1028669.cif
正在转换mp-1028683.cif
正在转换mp-1028686.cif
正在转换mp-1028698.cif
正在转换mp-1028704.cif
正在转换mp-1028728.cif
正在转换mp-1028729.cif
正在转换mp-1028732.cif
正在转换mp-1028743.cif
正在转换mp-1028748.cif
正在转换mp-1028761.cif
正在转换mp-1028762.cif
正在转换mp-1028764.cif
正在转换mp-1028765.cif
正在转换mp-1028768.cif
正在转换mp-1028769.cif
正在转换mp-1028771.cif
正在转换mp-1028772.cif
正在转换mp-1028793.cif
正在转换mp-1028821.cif
正在转换mp-1028823.cif
正在转换mp-1028827.cif
正在转换mp-1028828.cif
正在转换mp-1028832.cif
正在转换mp-1028848.cif
正在转换mp-1028851.cif
正在转换mp-1028869.cif
正在转换mp-1028872.cif
正在转换mp-1028887.cif
正在转换mp-1028901.cif
正在转换mp-1028911.cif
正在转换mp-1028912.cif
正在转换mp-1028919.cif
正在转换mp-1028922.cif
正在转换mp-1028931.cif
正在转换mp-1028939.cif
正在转换mp-1028947.cif
正在转换mp-1028948.cif
正在转换mp-1028951.cif
正在转换mp-1028952.cif
正在转换mp-1028959.cif
正在转换mp-1028971.cif
正在转换mp-1028975.cif
正在转换mp-1028978.cif
正在转换mp-1028979.cif
正在转换mp-1028980.cif
正在转换mp-1028998.cif
正在转换mp-1028999.cif
正在转换mp-1029015.cif
正在转换mp-1029025.cif
正在转换mp-1029031.cif
正在转换mp-1029037.cif
正在转换mp-1029043.cif
正在转换mp-1029044.cif
正在转换mp-1029059.cif
正在转换mp-1029062.cif
正在转换mp-1029063.cif

正在转换mp-1029066.cif
正在转换mp-1029069.cif
正在转换mp-1029072.cif
正在转换mp-1029073.cif
正在转换mp-1029076.cif
正在转换mp-1029077.cif
正在转换mp-1029101.cif
正在转换mp-1029102.cif
正在转换mp-1029112.cif
正在转换mp-1029113.cif
正在转换mp-1029116.cif
正在转换mp-1029140.cif
正在转换mp-1029141.cif
正在转换mp-1029144.cif
正在转换mp-1029145.cif
正在转换mp-1029147.cif
正在转换mp-1029148.cif
正在转换mp-1029155.cif
正在转换mp-1029166.cif
正在转换mp-1029176.cif
正在转换mp-1029189.cif
正在转换mp-1029190.cif
正在转换mp-1029213.cif
正在转换mp-1029232.cif
正在转换mp-1029234.cif
正在转换mp-1029236.cif
正在转换mp-1029245.cif
正在转换mp-1029246.cif
正在转换mp-1029248.cif
正在转换mp-1029252.cif
正在转换mp-1029255.cif
正在转换mp-1029256.cif
正在转换mp-1029259.cif
正在转换mp-1029264.cif
正在转换mp-1029281.cif
正在转换mp-1029284.cif
正在转换mp-1029306.cif
正在转换mp-1029307.cif
正在转换mp-1029379.cif
正在转换mp-1029421.cif
正在转换mp-1029945.cif
正在转换mp-1029948.cif
正在转换mp-1029950.cif
正在转换mp-1029951.cif
正在转换mp-1029952.cif
正在转换mp-1030106.cif
正在转换mp-1030107.cif
正在转换mp-1030108.cif
正在转换mp-1030119.cif
正在转换mp-1030120.cif
正在转换mp-1030128.cif
正在转换mp-1030146.cif
正在转换mp-1030155.cif
正在转换mp-1030156.cif
正在转换mp-1030163.cif
正在转换mp-1030164.cif
正在转换mp-1030195.cif
正在转换mp-1030196.cif
正在转换mp-1030201.cif
正在转换mp-1030212.cif
正在转换mp-1030239.cif
正在转换mp-1030240.cif
正在转换mp-1030252.cif
正在转换mp-1030268.cif
正在转换mp-1030269.cif
正在转换mp-1030281.cif
正在转换mp-1030286.cif
正在转换mp-1030289.cif
正在转换mp-1030292.cif
正在转换mp-1030309.cif
正在转换mp-1030319.cif
正在转换mp-1030327.cif
正在转换mp-1030331.cif
正在转换mp-1030332.cif
正在转换mp-1030333.cif
正在转换mp-1030335.cif
正在转换mp-1030340.cif
正在转换mp-1030353.cif
正在转换mp-1030354.cif
正在转换mp-1030389.cif
正在转换mp-1030392.cif
正在转换mp-1030393.cif
正在转换mp-1030404.cif
正在转换mp-1030409.cif
正在转换mp-1030449.cif
正在转换mp-1030453.cif
正在转换mp-1030454.cif
正在转换mp-1030459.cif
正在转换mp-1030462.cif
正在转换mp-1030465.cif
正在转换mp-1030466.cif
正在转换mp-1030504.cif
正在转换mp-1030508.cif
正在转换mp-1030509.cif
正在转换mp-1030512.cif
正在转换mp-1030513.cif
正在转换mp-1030516.cif
正在转换mp-1030517.cif
正在转换mp-1030519.cif
正在转换mp-1030522.cif
正在转换mp-1030523.cif
正在转换mp-1030524.cif
正在转换mp-1030533.cif
正在转换mp-1030535.cif
正在转换mp-1030536.cif
正在转换mp-1030565.cif
正在转换mp-1030566.cif
正在转换mp-1030567.cif
正在转换mp-1030568.cif
正在转换mp-1030571.cif
正在转换mp-1030573.cif
正在转换mp-1030574.cif
正在转换mp-1030576.cif
正在转换mp-1030577.cif
正在转换mp-1030596.cif
正在转换mp-1030605.cif
正在转换mp-1030613.cif
正在转换mp-1030614.cif
正在转换mp-1030615.cif
正在转换mp-1030616.cif
正在转换mp-1030617.cif
正在转换mp-1030682.cif
正在转换mp-1030685.cif
正在转换mp-1030695.cif
正在转换mp-1030709.cif
正在转换mp-1030721.cif
正在转换mp-1030722.cif
正在转换mp-1030732.cif
正在转换mp-1030750.cif
正在转换mp-1030784.cif
正在转换mp-1030827.cif
正在转换mp-1030961.cif
正在转换mp-1040425.cif
正在转换mp-1040468.cif
正在转换mp-10412.cif
正在转换mp-13938.cif
正在转换mp-16977.cif
正在转换mp-19893.cif
正在转换mp-20244.cif
正在转换mp-20316.cif
正在转换mp-21365.cif
正在转换mp-23174.cif
正在转换mp-23224.cif
正在转换mp-23261.cif
正在转换mp-23444.cif
正在转换mp-23858.cif
正在转换mp-23888.cif
正在转换mp-24037.cif
正在转换mp-24087.cif
正在转换mp-24128.cif
正在转换mp-24156.cif
正在转换mp-24294.cif
正在转换mp-24316.cif
正在转换mp-24528.cif
正在转换mp-24638.cif
正在转换mp-24714.cif
正在转换mp-25062.cif
正在转换mp-25107.cif
正在转换mp-25485.cif
正在转换mp-25540.cif
正在转换mp-25580.cif
正在转换mp-25607.cif
正在转换mp-27164.cif
正在转换mp-27195.cif
正在转换mp-27218.cif
正在转换mp-27314.cif
正在转换mp-27317.cif
正在转换mp-27356.cif
正在转换mp-27445.cif
正在转换mp-27452.cif
正在转换mp-27523.cif
正在转换mp-27700.cif
正在转换mp-27723.cif
正在转换mp-27742.cif
正在转换mp-27996.cif
正在转换mp-28167.cif
正在转换mp-28194.cif
正在转换mp-28289.cif
正在转换mp-28813.cif
正在转换mp-28874.cif
正在转换mp-28912.cif
正在转换mp-29218.cif
正在转换mp-29232.cif
正在转换mp-29315.cif
正在转换mp-29320.cif
正在转换mp-29357.cif
正在转换mp-29409.cif
正在转换mp-29412.cif
正在转换mp-29483.cif
正在转换mp-29579.cif
正在转换mp-29688.cif
正在转换mp-29716.cif
正在转换mp-29839.cif
正在转换mp-29849.cif
正在转换mp-30013.cif
正在转换mp-30086.cif
正在转换mp-30103.cif
正在转换mp-30109.cif
正在转换mp-30529.cif
正在转换mp-30934.cif
正在转换mp-31007.cif
正在转换mp-31024.cif
正在转换mp-31025.cif
正在转换mp-32532.cif
正在转换mp-33112.cif
正在转换mp-34656.cif
正在转换mp-35751.cif
正在转换mp-35925.cif
正在转换mp-36381.cif
正在转换mp-36940.cif
正在转换mp-38605.cif
正在转换mp-39008.cif
正在转换mp-39540.cif
正在转换mp-4077.cif
正在转换mp-40886.cif
正在转换mp-501.cif
正在转换mp-504474.cif
正在转换mp-504630.cif
正在转换mp-504818.cif
正在转换mp-504820.cif
正在转换mp-504825.cif
正在转换mp-504922.cif
正在转换mp-505000.cif
正在转换mp-505105.cif
正在转换mp-505127.cif
正在转换mp-505137.cif
正在转换mp-505206.cif
正在转换mp-505208.cif
正在转换mp-505258.cif
正在转换mp-505259.cif
正在转换mp-505610.cif
正在转换mp-510128.cif
正在转换mp-510293.cif
正在转换mp-510350.cif
正在转换mp-510456.cif
正在转换mp-510568.cif
正在转换mp-5245.cif
正在转换mp-540789.cif
正在转换mp-540793.cif
正在转换mp-540884.cif
正在转换mp-540940.cif
正在转换mp-540966.cif
正在转换mp-541067.cif
正在转换mp-541073.cif
正在转换mp-541152.cif
正在转换mp-541201.cif
正在转换mp-541240.cif
正在转换mp-541487.cif
正在转换mp-541667.cif
正在转换mp-541761.cif
正在转换mp-541774.cif
正在转换mp-541877.cif
正在转换mp-541937.cif
正在转换mp-542152.cif
正在转换mp-542180.cif
正在转换mp-542449.cif
正在转换mp-542452.cif
正在转换mp-542495.cif
正在转换mp-542634.cif
正在转换mp-542644.cif
正在转换mp-542700.cif
正在转换mp-542769.cif
正在转换mp-542791.cif
正在转换mp-542802.cif
正在转换mp-542812.cif
正在转换mp-542967.cif
正在转换mp-542977.cif
正在转换mp-543057.cif
正在转换mp-543072.cif
正在转换mp-543096.cif
正在转换mp-543104.cif
正在转换mp-545479.cif
正在转换mp-545552.cif
正在转换mp-545659.cif
正在转换mp-545730.cif
正在转换mp-546292.cif
正在转换mp-546568.cif
正在转换mp-546862.cif
正在转换mp-547094.cif
正在转换mp-549720.cif
正在转换mp-550469.cif
正在转换mp-550553.cif
正在转换mp-550714.cif
正在转换mp-550998.cif
正在转换mp-551470.cif
正在转换mp-551685.cif
正在转换mp-552120.cif
正在转换mp-552265.cif
正在转换mp-553890.cif
正在转换mp-553909.cif
正在转换mp-553956.cif
正在转换mp-554002.cif
正在转换mp-554061.cif
正在转换mp-554137.cif
正在转换mp-554238.cif
正在转换mp-554340.cif
正在转换mp-554361.cif
正在转换mp-554370.cif
正在转换mp-554491.cif
正在转换mp-554570.cif
正在转换mp-554659.cif
正在转换mp-554701.cif
正在转换mp-554799.cif
正在转换mp-554833.cif
正在转换mp-554840.cif
正在转换mp-554852.cif
正在转换mp-554883.cif
正在转换mp-554921.cif
正在转换mp-554950.cif
正在转换mp-555003.cif
正在转换mp-555037.cif
正在转换mp-555052.cif
正在转换mp-555056.cif
正在转换mp-555074.cif
正在转换mp-555153.cif
正在转换mp-555229.cif
正在转换mp-555236.cif
正在转换mp-555292.cif
正在转换mp-555390.cif
正在转换mp-555462.cif
正在转换mp-555513.cif
正在转换mp-555844.cif
正在转换mp-555902.cif
正在转换mp-555940.cif
正在转换mp-555997.cif
正在转换mp-556094.cif
正在转换mp-556127.cif
正在转换mp-556231.cif
正在转换mp-556389.cif
正在转换mp-556485.cif
正在转换mp-556516.cif
正在转换mp-556541.cif
正在转换mp-556842.cif
正在转换mp-556845.cif
正在转换mp-556939.cif
正在转换mp-557049.cif
正在转换mp-557136.cif
正在转换mp-557183.cif
正在转换mp-557438.cif
正在转换mp-557480.cif
正在转换mp-557523.cif
正在转换mp-557580.cif
正在转换mp-557619.cif
正在转换mp-557685.cif
正在转换mp-557687.cif
正在转换mp-557705.cif
正在转换mp-557739.cif
正在转换mp-557787.cif
正在转换mp-557805.cif
正在转换mp-557908.cif
正在转换mp-557911.cif
正在转换mp-557950.cif
正在转换mp-557980.cif
正在转换mp-557992.cif
正在转换mp-558279.cif
正在转换mp-558387.cif
正在转换mp-558456.cif
正在转换mp-558506.cif
正在转换mp-558672.cif
正在转换mp-559094.cif
正在转换mp-559143.cif
正在转换mp-559235.cif
正在转换mp-559332.cif
正在转换mp-559355.cif
正在转换mp-559470.cif
正在转换mp-559562.cif
正在转换mp-559585.cif
正在转换mp-559588.cif
正在转换mp-559676.cif
正在转换mp-559864.cif
正在转换mp-559911.cif
正在转换mp-559923.cif
正在转换mp-559976.cif
正在转换mp-560054.cif
正在转换mp-560196.cif
正在转换mp-560262.cif
正在转换mp-560333.cif
正在转换mp-560354.cif
正在转换mp-560370.cif
正在转换mp-560411.cif
正在转换mp-560549.cif
正在转换mp-560553.cif
正在转换mp-560572.cif
正在转换mp-560607.cif
正在转换mp-560676.cif
正在转换mp-560806.cif
正在转换mp-560845.cif
正在转换mp-560923.cif
正在转换mp-561079.cif
正在转换mp-561112.cif
正在转换mp-561153.cif
正在转换mp-561299.cif
正在转换mp-561300.cif
正在转换mp-561320.cif
正在转换mp-561350.cif
正在转换mp-561392.cif
正在转换mp-561465.cif
正在转换mp-561475.cif
正在转换mp-561492.cif
正在转换mp-561708.cif
正在转换mp-561779.cif
正在转换mp-562018.cif
正在转换mp-562090.cif
正在转换mp-565932.cif
正在转换mp-566054.cif
正在转换mp-566172.cif
正在转换mp-566304.cif
正在转换mp-566312.cif
正在转换mp-566762.cif
正在转换mp-566831.cif
正在转换mp-566857.cif
正在转换mp-567019.cif
正在转换mp-567148.cif
正在转换mp-567178.cif
正在转换mp-567199.cif
正在转换mp-567246.cif
正在转换mp-567296.cif
正在转换mp-567330.cif
正在转换mp-567336.cif
正在转换mp-567359.cif
正在转换mp-567402.cif
正在转换mp-567442.cif
正在转换mp-567483.cif
正在转换mp-567503.cif
正在转换mp-567534.cif
正在转换mp-567537.cif
正在转换mp-567542.cif
正在转换mp-567556.cif
正在转换mp-567567.cif
正在转换mp-567624.cif
正在转换mp-567687.cif
正在转换mp-567699.cif
正在转换mp-567713.cif
正在转换mp-567789.cif
正在转换mp-567885.cif
正在转换mp-567949.cif
正在转换mp-567975.cif
正在转换mp-567989.cif
正在转换mp-568002.cif
正在转换mp-568100.cif
正在转换mp-568128.cif
正在转换mp-568146.cif
正在转换mp-568230.cif
正在转换mp-568263.cif
正在转换mp-568301.cif
正在转换mp-568313.cif
正在转换mp-568328.cif
正在转换mp-568346.cif
正在转换mp-568388.cif
正在转换mp-568443.cif
正在转换mp-568517.cif
正在转换mp-568532.cif
正在转换mp-568726.cif
正在转换mp-568742.cif
正在转换mp-568758.cif

正在转换mp-568806.cif
正在转换mp-568948.cif
正在转换mp-568998.cif
正在转换mp-569005.cif
正在转换mp-569044.cif
正在转换mp-569059.cif
正在转换mp-569126.cif
正在转换mp-569129.cif
正在转换mp-569157.cif
正在转换mp-569175.cif
正在转换mp-569240.cif
正在转换mp-569303.cif
正在转换mp-569358.cif
正在转换mp-569391.cif
正在转换mp-569436.cif
正在转换mp-569454.cif
正在转换mp-569569.cif
正在转换mp-569595.cif
正在转换mp-569626.cif
正在转换mp-569655.cif
正在转换mp-569662.cif
正在转换mp-569679.cif
正在转换mp-569687.cif
正在转换mp-569701.cif
正在转换mp-569704.cif
正在转换mp-569707.cif
正在转换mp-569756.cif
正在转换mp-569787.cif
正在转换mp-569824.cif
正在转换mp-569843.cif
正在转换mp-569890.cif
正在转换mp-569960.cif
正在转换mp-569964.cif
正在转换mp-569994.cif
正在转换mp-570005.cif
正在转换mp-570019.cif
正在转换mp-570054.cif
正在转换mp-570084.cif
正在转换mp-570122.cif
正在转换mp-570127.cif
正在转换mp-570136.cif
正在转换mp-570165.cif
正在转换mp-570197.cif
正在转换mp-570225.cif
正在转换mp-570270.cif
正在转换mp-570286.cif
正在转换mp-570314.cif
正在转换mp-570321.cif
正在转换mp-570325.cif
正在转换mp-570340.cif
正在转换mp-570355.cif
正在转换mp-570370.cif
正在转换mp-570410.cif
正在转换mp-570418.cif
正在转换mp-570437.cif
正在转换mp-570472.cif
正在转换mp-570498.cif
正在转换mp-570506.cif
正在转换mp-570511.cif
正在转换mp-570559.cif
正在转换mp-570562.cif
正在转换mp-570572.cif
正在转换mp-570613.cif
正在转换mp-570671.cif
正在转换mp-570695.cif
正在转换mp-5706.cif
正在转换mp-570722.cif
正在转换mp-570781.cif
正在转换mp-570782.cif
正在转换mp-570848.cif
正在转换mp-570873.cif
正在转换mp-570882.cif
正在转换mp-570922.cif
正在转换mp-570930.cif
正在转换mp-570939.cif
正在转换mp-570962.cif
正在转换mp-570964.cif
正在转换mp-570997.cif
正在转换mp-571006.cif
正在转换mp-571015.cif
正在转换mp-571037.cif
正在转换mp-571065.cif
正在转换mp-571091.cif
正在转换mp-571096.cif
正在转换mp-571134.cif
正在转换mp-571146.cif
正在转换mp-571197.cif
正在转换mp-571225.cif
正在转换mp-571235.cif
正在转换mp-571258.cif
正在转换mp-571266.cif
正在转换mp-571270.cif
正在转换mp-571297.cif
正在转换mp-571324.cif
正在转换mp-571424.cif
正在转换mp-571436.cif
正在转换mp-571465.cif
正在转换mp-571514.cif
正在转换mp-571519.cif
正在转换mp-571535.cif
正在转换mp-571538.cif
正在转换mp-571539.cif
正在转换mp-571555.cif
正在转换mp-571558.cif
正在转换mp-571559.cif
正在转换mp-571567.cif
正在转换mp-571568.cif
正在转换mp-571569.cif
正在转换mp-571579.cif
正在转换mp-571583.cif
正在转换mp-571592.cif
正在转换mp-571593.cif
正在转换mp-571595.cif
正在转换mp-571605.cif
正在转换mp-572313.cif
正在转换mp-573045.cif
正在转换mp-573321.cif
正在转换mp-573376.cif
正在转换mp-573567.cif
正在转换mp-574086.cif
正在转换mp-574250.cif
正在转换mp-579909.cif
正在转换mp-580748.cif
正在转换mp-580886.cif
正在转换mp-580941.cif
正在转换mp-581990.cif
正在转换mp-582060.cif
正在转换mp-582444.cif
正在转换mp-582549.cif
正在转换mp-583463.cif
正在转换mp-600159.cif
正在转换mp-601403.cif
正在转换mp-601661.cif
正在转换mp-601693.cif
正在转换mp-601716.cif
正在转换mp-601823.cif
正在转换mp-602355.cif
正在转换mp-604315.cif
正在转换mp-604914.cif
正在转换mp-605912.cif
正在转换mp-606393.cif
正在转换mp-607031.cif
正在转换mp-607399.cif
正在转换mp-607953.cif
正在转换mp-608071.cif
正在转换mp-608254.cif
正在转换mp-608439.cif
正在转换mp-608823.cif
正在转换mp-610430.cif
正在转换mp-610491.cif
正在转换mp-610992.cif
正在转换mp-611316.cif
正在转换mp-613235.cif
正在转换mp-613314.cif
正在转换mp-613652.cif
正在转换mp-614006.cif
正在转换mp-616218.cif
正在转换mp-616514.cif
正在转换mp-616672.cif
正在转换mp-617165.cif
正在转换mp-619032.cif
正在转换mp-619928.cif
正在转换mp-620029.cif
正在转换mp-620190.cif
正在转换mp-620404.cif
正在转换mp-621092.cif
正在转换mp-621694.cif
正在转换mp-623958.cif
正在转换mp-624190.cif
正在转换mp-624399.cif
正在转换mp-624689.cif
正在转换mp-624889.cif
正在转换mp-624929.cif
正在转换mp-625054.cif
正在转换mp-625056.cif
正在转换mp-625072.cif
正在转换mp-625074.cif
正在转换mp-625075.cif
正在转换mp-625081.cif
正在转换mp-625087.cif
正在转换mp-625150.cif
正在转换mp-625179.cif
正在转换mp-625284.cif
正在转换mp-625316.cif
正在转换mp-625318.cif
正在转换mp-625320.cif
正在转换mp-625321.cif
正在转换mp-625385.cif
正在转换mp-625405.cif
正在转换mp-625420.cif
正在转换mp-625474.cif
正在转换mp-625487.cif
正在转换mp-625488.cif
正在转换mp-625513.cif
正在转换mp-625526.cif
正在转换mp-625548.cif
正在转换mp-625557.cif
正在转换mp-625565.cif
正在转换mp-625630.cif
正在转换mp-625635.cif
正在转换mp-625668.cif
正在转换mp-625717.cif
正在转换mp-625762.cif
正在转换mp-625927.cif
正在转换mp-625950.cif
正在转换mp-625953.cif
正在转换mp-625956.cif
正在转换mp-626102.cif
正在转换mp-626143.cif
正在转换mp-626169.cif
正在转换mp-626378.cif
正在转换mp-626414.cif
正在转换mp-626431.cif
正在转换mp-626435.cif
正在转换mp-626497.cif
正在转换mp-626500.cif
正在转换mp-626504.cif
正在转换mp-626512.cif
正在转换mp-626557.cif
正在转换mp-626568.cif
正在转换mp-626605.cif
正在转换mp-626680.cif
正在转换mp-626689.cif
正在转换mp-626701.cif
正在转换mp-626708.cif
正在转换mp-626813.cif
正在转换mp-626843.cif
正在转换mp-626864.cif
正在转换mp-626881.cif
正在转换mp-626885.cif
正在转换mp-626902.cif
正在转换mp-627380.cif
正在转换mp-627601.cif
正在转换mp-628773.cif
正在转换mp-629015.cif
正在转换mp-630329.cif
正在转换mp-630773.cif
正在转换mp-631589.cif
正在转换mp-632296.cif
正在转换mp-632329.cif
正在转换mp-632403.cif
正在转换mp-632413.cif
正在转换mp-632657.cif
正在转换mp-632706.cif
正在转换mp-632724.cif
正在转换mp-634059.cif
正在转换mp-634117.cif
正在转换mp-634466.cif
正在转换mp-634716.cif
正在转换mp-634755.cif
正在转换mp-635322.cif
正在转换mp-636839.cif
正在转换mp-637206.cif
正在转换mp-637232.cif
正在转换mp-637614.cif
正在转换mp-642462.cif
正在转换mp-642807.cif
正在转换mp-642810.cif
正在转换mp-643013.cif
正在转换mp-643052.cif
正在转换mp-643063.cif
正在转换mp-643277.cif
正在转换mp-643387.cif
正在转换mp-643579.cif
正在转换mp-643735.cif
正在转换mp-643743.cif
正在转换mp-643759.cif
正在转换mp-643902.cif
正在转换mp-644222.cif
正在转换mp-645282.cif
正在转换mp-647343.cif
正在转换mp-647489.cif
正在转换mp-648932.cif
正在转换mp-649213.cif
正在转换mp-649950.cif
正在转换mp-651723.cif
正在转换mp-652180.cif
正在转换mp-652695.cif
正在转换mp-655353.cif
正在转换mp-655489.cif
正在转换mp-669325.cif
正在转换mp-669326.cif
正在转换mp-669328.cif
正在转换mp-669425.cif
正在转换mp-672302.cif
正在转换mp-672350.cif
正在转换mp-672671.cif
正在转换mp-672986.cif
正在转换mp-673118.cif
正在转换mp-673698.cif
正在转换mp-673848.cif
正在转换mp-674324.cif
正在转换mp-674537.cif
正在转换mp-675066.cif
正在转换mp-675098.cif
正在转换mp-675152.cif
正在转换mp-675295.cif
正在转换mp-675332.cif
正在转换mp-675342.cif
正在转换mp-675543.cif
正在转换mp-675654.cif
正在转换mp-675942.cif
正在转换mp-676040.cif
正在转换mp-676050.cif
正在转换mp-676121.cif
正在转换mp-676250.cif
正在转换mp-676437.cif
正在转换mp-676572.cif
正在转换mp-676611.cif
正在转换mp-676712.cif
正在转换mp-677065.cif
正在转换mp-680055.cif
正在转换mp-680111.cif
正在转换mp-680550.cif
正在转换mp-680579.cif
正在转换mp-680599.cif
正在转换mp-684592.cif
正在转换mp-684670.cif
正在转换mp-685068.cif
正在转换mp-685136.cif
正在转换mp-685145.cif
正在转换mp-685155.cif
正在转换mp-690012.cif
正在转换mp-690578.cif
正在转换mp-690650.cif
正在转换mp-690687.cif
正在转换mp-690727.cif
正在转换mp-695850.cif
正在转换mp-695878.cif
正在转换mp-695946.cif
正在转换mp-696114.cif
正在转换mp-696152.cif
正在转换mp-696210.cif
正在转换mp-696298.cif
正在转换mp-696308.cif
正在转换mp-696379.cif
正在转换mp-696420.cif
正在转换mp-696597.cif
正在转换mp-696616.cif
正在转换mp-696656.cif
正在转换mp-696666.cif
正在转换mp-696940.cif
正在转换mp-697077.cif
正在转换mp-697120.cif
正在转换mp-697253.cif
正在转换mp-697451.cif
正在转换mp-697873.cif
正在转换mp-697921.cif
正在转换mp-698357.cif
正在转换mp-699208.cif
正在转换mp-699431.cif
正在转换mp-703297.cif
正在转换mp-703531.cif
正在转换mp-703914.cif
正在转换mp-705538.cif
正在转换mp-706622.cif
正在转换mp-706979.cif
正在转换mp-707273.cif
正在转换mp-707940.cif
正在转换mp-714873.cif
正在转换mp-714874.cif
正在转换mp-714929.cif
正在转换mp-714944.cif
正在转换mp-715160.cif
正在转换mp-715463.cif
正在转换mp-715474.cif
正在转换mp-715479.cif
正在转换mp-715480.cif
正在转换mp-715574.cif
正在转换mp-720391.cif
正在转换mp-720897.cif
正在转换mp-722246.cif
正在转换mp-733932.cif
正在转换mp-735524.cif
正在转换mp-742819.cif
正在转换mp-743614.cif
正在转换mp-743618.cif
正在转换mp-743987.cif
正在转换mp-744574.cif
正在转换mp-744930.cif
正在转换mp-745106.cif
正在转换mp-745159.cif
正在转换mp-745180.cif
正在转换mp-752422.cif
正在转换mp-752474.cif
正在转换mp-752637.cif
正在转换mp-752949.cif
正在转换mp-753059.cif
正在转换mp-753173.cif
正在转换mp-753211.cif
正在转换mp-753445.cif
正在转换mp-753614.cif
正在转换mp-753661.cif
正在转换mp-753712.cif
正在转换mp-753727.cif
正在转换mp-753800.cif
正在转换mp-753858.cif
正在转换mp-754005.cif
正在转换mp-754008.cif
正在转换mp-754038.cif
正在转换mp-754112.cif
正在转换mp-754113.cif
正在转换mp-754217.cif
正在转换mp-754246.cif
正在转换mp-754355.cif
正在转换mp-754459.cif
正在转换mp-754462.cif
正在转换mp-754526.cif
正在转换mp-754645.cif
正在转换mp-754960.cif
正在转换mp-754969.cif
正在转换mp-755380.cif
正在转换mp-755382.cif
正在转换mp-755455.cif
正在转换mp-755829.cif
正在转换mp-755831.cif
正在转换mp-755856.cif
正在转换mp-756273.cif
正在转换mp-756342.cif
正在转换mp-756593.cif
正在转换mp-756654.cif
正在转换mp-756702.cif
正在转换mp-756758.cif
正在转换mp-757111.cif
正在转换mp-757145.cif
正在转换mp-757480.cif
正在转换mp-758203.cif
正在转换mp-759288.cif
正在转换mp-760421.cif
正在转换mp-760482.cif
正在转换mp-760489.cif
正在转换mp-760599.cif
正在转换mp-761501.cif
正在转换mp-761530.cif
正在转换mp-761557.cif
正在转换mp-761662.cif
正在转换mp-762227.cif
正在转换mp-762239.cif
正在转换mp-763057.cif
正在转换mp-763352.cif
正在转换mp-763482.cif
正在转换mp-763854.cif
正在转换mp-764219.cif
正在转换mp-764228.cif
正在转换mp-764243.cif
正在转换mp-764258.cif
正在转换mp-764283.cif
正在转换mp-764303.cif
正在转换mp-764309.cif
正在转换mp-764312.cif
正在转换mp-764315.cif
正在转换mp-764325.cif
正在转换mp-764365.cif
正在转换mp-765237.cif
正在转换mp-765332.cif
正在转换mp-765838.cif
正在转换mp-765847.cif
正在转换mp-765848.cif
正在转换mp-765852.cif
正在转换mp-765864.cif
正在转换mp-765892.cif
正在转换mp-765906.cif
正在转换mp-765912.cif
正在转换mp-765919.cif
正在转换mp-765921.cif
正在转换mp-765922.cif
正在转换mp-765923.cif
正在转换mp-765936.cif
正在转换mp-765939.cif
正在转换mp-766259.cif
正在转换mp-766429.cif
正在转换mp-766515.cif
正在转换mp-766790.cif
正在转换mp-766870.cif
正在转换mp-767120.cif
正在转换mp-767122.cif
正在转换mp-767158.cif
正在转换mp-767279.cif
正在转换mp-767357.cif
正在转换mp-768036.cif
正在转换mp-768069.cif
正在转换mp-768141.cif
正在转换mp-768906.cif
正在转换mp-769028.cif
正在转换mp-769096.cif
正在转换mp-769108.cif
正在转换mp-769218.cif
正在转换mp-769642.cif
正在转换mp-769839.cif
正在转换mp-769958.cif
正在转换mp-770063.cif
正在转换mp-770401.cif
正在转换mp-770718.cif
正在转换mp-770751.cif
正在转换mp-771380.cif
正在转换mp-771458.cif
正在转换mp-771460.cif
正在转换mp-771464.cif
正在转换mp-771662.cif
正在转换mp-771676.cif
正在转换mp-771809.cif
正在转换mp-771871.cif
正在转换mp-771938.cif
正在转换mp-771994.cif
正在转换mp-772282.cif
正在转换mp-772295.cif
正在转换mp-772598.cif

正在转换mp-772667.cif
正在转换mp-773237.cif
正在转换mp-773280.cif
正在转换mp-773303.cif
正在转换mp-773306.cif
正在转换mp-773333.cif
正在转换mp-773510.cif
正在转换mp-773511.cif
正在转换mp-773550.cif
正在转换mp-774146.cif
正在转换mp-774147.cif
正在转换mp-774191.cif
正在转换mp-774873.cif
正在转换mp-775117.cif
正在转换mp-775464.cif
正在转换mp-775831.cif
正在转换mp-775847.cif
正在转换mp-776083.cif
正在转换mp-776354.cif
正在转换mp-776661.cif
正在转换mp-776707.cif
正在转换mp-777080.cif
正在转换mp-777100.cif
正在转换mp-777738.cif
正在转换mp-778781.cif
正在转换mp-779212.cif
正在转换mp-779664.cif
正在转换mp-779966.cif
正在转换mp-780260.cif
正在转换mp-780738.cif
正在转换mp-849325.cif
正在转换mp-849597.cif
正在转换mp-849598.cif
正在转换mp-849702.cif
正在转换mp-850009.cif
正在转换mp-850032.cif
正在转换mp-850937.cif
正在转换mp-853132.cif
正在转换mp-861867.cif
正在转换mp-861871.cif
正在转换mp-861891.cif
正在转换mp-861911.cif
正在转换mp-862539.cif
正在转换mp-862678.cif
正在转换mp-862687.cif
正在转换mp-862773.cif
正在转换mp-862800.cif
正在转换mp-862853.cif
正在转换mp-862983.cif
正在转换mp-862986.cif
正在转换mp-863658.cif
正在转换mp-863695.cif
正在转换mp-863878.cif
正在转换mp-864617.cif
正在转换mp-864657.cif
正在转换mp-864662.cif
正在转换mp-864733.cif
正在转换mp-864887.cif
正在转换mp-864888.cif
正在转换mp-864899.cif
正在转换mp-864928.cif
正在转换mp-864982.cif
正在转换mp-865005.cif
正在转换mp-865301.cif
正在转换mp-865324.cif
正在转换mp-865353.cif
正在转换mp-865428.cif
正在转换mp-865466.cif
正在转换mp-865493.cif
正在转换mp-865521.cif
正在转换mp-865580.cif
正在转换mp-865581.cif
正在转换mp-865880.cif
正在转换mp-866003.cif
正在转换mp-866066.cif
正在转换mp-866214.cif
正在转换mp-866658.cif
正在转换mp-867231.cif
正在转换mp-867247.cif
正在转换mp-867355.cif
正在转换mp-867360.cif
正在转换mp-867675.cif
正在转换mp-867724.cif
正在转换mp-867875.cif
正在转换mp-867891.cif
正在转换mp-867893.cif
正在转换mp-868389.cif
正在转换mp-868610.cif
正在转换mp-9130.cif
正在转换mp-937760.cif
正在转换mp-9540.cif
正在转换mp-971673.cif
正在转换mp-971683.cif
正在转换mp-971684.cif
正在转换mp-971794.cif
正在转换mp-971820.cif
正在转换mp-971920.cif
正在转换mp-972032.cif
正在转换mp-972093.cif
正在转换mp-972454.cif
正在转换mp-972472.cif
正在转换mp-972494.cif
正在转换mp-972591.cif
正在转换mp-972825.cif
正在转换mp-972848.cif
正在转换mp-972874.cif
正在转换mp-972889.cif
正在转换mp-973175.cif
正在转换mp-973585.cif
正在转换mp-973684.cif
正在转换mp-973736.cif
正在转换mp-973981.cif
正在转换mp-974035.cif
正在转换mp-974434.cif
正在转换mp-975666.cif
正在转换mp-976349.cif
正在转换mp-976425.cif
正在转换mp-976713.cif
正在转换mp-977368.cif
正在转换mp-977371.cif
正在转换mp-977375.cif
正在转换mp-978114.cif
正在转换mp-978259.cif
正在转换mp-978268.cif
正在转换mp-978499.cif
正在转换mp-978928.cif
正在转换mp-979264.cif
正在转换mp-979964.cif
正在转换mp-981375.cif
正在转换mp-983357.cif
正在转换mp-983411.cif
正在转换mp-984696.cif
正在转换mp-985288.cif
正在转换mp-985304.cif
正在转换mp-985782.cif
正在转换mp-989190.cif
正在转换mp-989194.cif
正在转换mp-989460.cif
正在转换mp-989461.cif
正在转换mp-989472.cif
正在转换mp-989651.cif
正在转换mp-990424.cif
正在转换mp-990436.cif
正在转换mp-990448.cif
正在转换mp-995195.cif
正在转换mp-995198.cif
正在转换mp-995221.cif
正在转换mp-996953.cif
正在转换mp-996955.cif
正在转换mp-996958.cif
正在转换mp-996960.cif
正在转换mp-996968.cif
正在转换mp-996969.cif
正在转换mp-996993.cif
正在转换mp-996999.cif
正在转换mp-997027.cif
正在转换mp-997028.cif
正在转换mp-997033.cif
正在转换mp-997035.cif
正在转换mp-997052.cif
正在转换mp-997088.cif
正在转换mp-997101.cif
正在转换mp-997182.cif
正在转换mp-997394.cif
正在转换mp-997569.cif
正在转换mp-998233.cif
正在转换mp-998560.cif
正在转换mp-999300.cif
正在转换mp-999337.cif
正在转换mvc-10067.cif
正在转换mvc-10084.cif
正在转换mvc-10451.cif
正在转换mvc-10587.cif
正在转换mvc-10701.cif
正在转换mvc-10706.cif
正在转换mvc-10862.cif
正在转换mvc-10952.cif
正在转换mvc-10961.cif
正在转换mvc-10966.cif
正在转换mvc-11096.cif
正在转换mvc-11097.cif
正在转换mvc-11154.cif
正在转换mvc-11233.cif
正在转换mvc-11234.cif
正在转换mvc-11241.cif
正在转换mvc-11309.cif
正在转换mvc-11317.cif
正在转换mvc-11394.cif
正在转换mvc-11457.cif
正在转换mvc-11458.cif
正在转换mvc-11542.cif
正在转换mvc-11544.cif
正在转换mvc-11545.cif
正在转换mvc-11547.cif
正在转换mvc-11564.cif
正在转换mvc-11598.cif
正在转换mvc-11600.cif
正在转换mvc-11630.cif
正在转换mvc-11647.cif
正在转换mvc-11686.cif
正在转换mvc-11754.cif
正在转换mvc-11944.cif
正在转换mvc-11980.cif
正在转换mvc-12009.cif
正在转换mvc-12466.cif
正在转换mvc-12777.cif
正在转换mvc-12792.cif
正在转换mvc-12823.cif
正在转换mvc-12841.cif
正在转换mvc-12866.cif
正在转换mvc-12939.cif
正在转换mvc-13105.cif
正在转换mvc-13107.cif
正在转换mvc-13108.cif
正在转换mvc-13110.cif
正在转换mvc-13111.cif
正在转换mvc-13239.cif
正在转换mvc-13496.cif
正在转换mvc-13531.cif
正在转换mvc-13534.cif
正在转换mvc-13540.cif
正在转换mvc-13836.cif
正在转换mvc-13958.cif
正在转换mvc-13999.cif
正在转换mvc-14047.cif
正在转换mvc-14195.cif
正在转换mvc-14257.cif
正在转换mvc-14313.cif
正在转换mvc-14348.cif
正在转换mvc-14464.cif
正在转换mvc-14582.cif
正在转换mvc-14624.cif
正在转换mvc-1472.cif
正在转换mvc-14775.cif
正在转换mvc-14925.cif
正在转换mvc-15081.cif
正在转换mvc-15178.cif
正在转换mvc-15331.cif
正在转换mvc-15384.cif
正在转换mvc-15431.cif
正在转换mvc-15486.cif
正在转换mvc-15496.cif
正在转换mvc-15785.cif
正在转换mvc-15812.cif
正在转换mvc-15892.cif
正在转换mvc-15968.cif
正在转换mvc-15980.cif
正在转换mvc-15991.cif
正在转换mvc-16010.cif
正在转换mvc-16061.cif
正在转换mvc-16271.cif
正在转换mvc-2446.cif
正在转换mvc-2858.cif
正在转换mvc-2876.cif
正在转换mvc-2968.cif
正在转换mvc-2971.cif
正在转换mvc-3272.cif
正在转换mvc-3381.cif
正在转换mvc-3449.cif
正在转换mvc-3451.cif
正在转换mvc-3500.cif
正在转换mvc-3506.cif
正在转换mvc-3515.cif
正在转换mvc-3524.cif
正在转换mvc-366.cif
正在转换mvc-4425.cif
正在转换mvc-4607.cif
正在转换mvc-4767.cif
正在转换mvc-479.cif
正在转换mvc-486.cif
正在转换mvc-4962.cif
正在转换mvc-5544.cif
正在转换mvc-5746.cif
正在转换mvc-6034.cif
正在转换mvc-6067.cif
正在转换mvc-6083.cif
正在转换mvc-6141.cif
正在转换mvc-6273.cif
正在转换mvc-6351.cif
正在转换mvc-6522.cif
正在转换mvc-668.cif
正在转换mvc-678.cif
正在转换mvc-6826.cif
正在转换mvc-6945.cif
正在转换mvc-708.cif
正在转换mvc-7191.cif
正在转换mvc-7254.cif
正在转换mvc-7295.cif
正在转换mvc-7302.cif
正在转换mvc-8038.cif
正在转换mvc-8154.cif
正在转换mvc-8162.cif
正在转换mvc-8179.cif
正在转换mvc-8406.cif
正在转换mvc-8418.cif
正在转换mvc-8429.cif
正在转换mvc-8453.cif
正在转换mvc-8590.cif
正在转换mvc-8765.cif
正在转换mvc-8775.cif
正在转换mvc-8898.cif
正在转换mvc-8976.cif
正在转换mvc-9206.cif
正在转换mvc-9236.cif
正在转换mvc-9246.cif
正在转换mvc-9397.cif
正在转换mvc-9477.cif
正在转换mvc-9642.cif
正在转换mvc-9648.cif
正在转换Ben-100332.cif
正在转换Ben-1004.cif
正在转换Ben-100681.cif
正在转换Ben-102.cif
正在转换Ben-1081.cif
正在转换Ben-1088.cif
正在转换Ben-10.cif
正在转换Ben-115.cif
正在转换Ben-1203.cif
正在转换Ben-1255.cif
正在转换Ben-139.cif
正在转换Ben-140.cif
正在转换Ben-16224.cif
正在转换Ben-184.cif
正在转换Ben-187.cif
正在转换Ben-1962.cif
正在转换Ben-214.cif
正在转换Ben-2374.cif
正在转换Ben-244.cif
正在转换Ben-255.cif
正在转换Ben-2620.cif
正在转换Ben-2845.cif
正在转换Ben-3001.cif
正在转换Ben-3012.cif
正在转换Ben-3016.cif
正在转换Ben-3020.cif
正在转换Ben-3069.cif
正在转换Ben-3073.cif
正在转换Ben-3134.cif
正在转换Ben-3328.cif
正在转换Ben-333.cif
正在转换Ben-33.cif
正在转换Ben-3423.cif
正在转换Ben-3580.cif
正在转换Ben-3786.cif
正在转换Ben-3826.cif
正在转换Ben-3884.cif
正在转换Ben-3987.cif
正在转换Ben-3.cif
正在转换Ben-4222.cif
正在转换Ben-43.cif
正在转换Ben-4.cif
正在转换Ben-5.cif
正在转换Ben-619.cif
正在转换Ben-63182.cif
正在转换Ben-66751.cif
正在转换Ben-6.cif
正在转换Ben-79.cif
正在转换Ben-89158.cif
正在转换Ben-96198.cif
正在转换Ben-96424.cif
正在转换Ben-97968.cif
正在转换Ben-98122.cif
正在转换12.cif
正在转换16.cif
正在转换16774.cif
正在转换174.cif
正在转换20.cif
正在转换23.cif
正在转换2373.cif
正在转换24.cif
正在转换25.cif
正在转换26.cif
正在转换27.cif
正在转换28.cif
正在转换3.cif
正在转换47269.cif
正在转换54.cif
正在转换554.cif
正在转换NbSe2.cif
正在转换WSe2.cif
正在转换mp-1001011.cif
正在转换mp-1001012.cif
正在转换mp-1001015.cif
正在转换mp-1001016.cif
正在转换mp-1001017.cif
正在转换mp-1001019.cif
正在转换mp-1001021.cif
正在转换mp-1001023.cif
正在转换mp-1001024.cif
正在转换mp-1001034.cif
正在转换mp-1001079.cif
正在转换mp-1001117.cif
正在转换mp-1001571.cif
正在转换mp-1001581.cif
正在转换mp-1001600.cif
正在转换mp-1001602.cif
正在转换mp-1001603.cif
正在转换mp-1001604.cif
正在转换mp-1001605.cif
正在转换mp-1001606.cif
正在转换mp-1001611.cif
正在转换mp-1001612.cif
正在转换mp-1001613.cif
正在转换mp-1001614.cif
正在转换mp-1001615.cif
正在转换mp-1001780.cif
正在转换mp-1001783.cif
正在转换mp-1001784.cif
正在转换mp-1001785.cif
正在转换mp-1001786.cif
正在转换mp-1001788.cif
正在转换mp-1001789.cif
正在转换mp-1001793.cif
正在转换mp-1001824.cif
正在转换mp-1001825.cif
正在转换mp-1001826.cif
正在转换mp-1001827.cif
正在转换mp-1001828.cif
正在转换mp-1001831.cif
正在转换mp-1001833.cif
正在转换mp-1001834.cif
正在转换mp-1001835.cif
正在转换mp-1001836.cif
正在转换mp-1001837.cif
正在转换mp-1001843.cif
正在转换mp-1001844.cif
正在转换mp-1001913.cif
正在转换mp-1001914.cif
正在转换mp-1001916.cif
正在转换mp-1001917.cif
正在转换mp-1001918.cif
正在转换mp-1001925.cif
正在转换mp-1002063.cif
正在转换mp-1002069.cif
正在转换mp-1002081.cif
正在转换mp-1002105.cif
正在转换mp-1002106.cif
正在转换mp-1002109.cif
正在转换mp-1002114.cif
正在转换mp-1002117.cif
正在转换mp-1002122.cif
正在转换mp-1002123.cif
正在转换mp-1002124.cif
正在转换mp-1002164.cif
正在转换mp-1002165.cif
正在转换mp-1002181.cif
正在转换mp-1002182.cif
正在转换mp-1002183.cif
正在转换mp-1002184.cif
正在转换mp-1002187.cif
正在转换mp-1002188.cif
正在转换mp-1002197.cif
正在转换mp-1002206.cif
正在转换mp-1002219.cif
正在转换mp-1002220.cif
正在转换mp-1002221.cif
正在转换mp-1002222.cif
正在转换mp-1002223.cif
正在转换mp-1002224.cif
正在转换mp-1002226.cif
正在转换mp-1002227.cif
正在转换mp-1002228.cif
正在转换mp-1002229.cif
正在转换mp-1002230.cif
正在转换mp-1004377.cif
正在转换mp-1004526.cif
正在转换mp-1005689.cif
正在转换mp-1005690.cif
正在转换mp-1005693.cif
正在转换mp-1005719.cif
正在转换mp-1005727.cif
正在转换mp-1005752.cif
正在转换mp-1005762.cif
正在转换mp-1005829.cif
正在转换mp-1006056.cif
正在转换mp-1006058.cif
正在转换mp-1006112.cif
正在转换mp-1006115.cif
正在转换mp-1006127.cif
正在转换mp-1006132.cif
正在转换mp-1006245.cif
正在转换mp-1006246.cif
正在转换mp-1006256.cif
正在转换mp-1006258.cif
正在转换mp-1006277.cif
正在转换mp-1006283.cif
正在转换mp-1006321.cif
正在转换mp-1006324.cif
正在转换mp-1006330.cif
正在转换mp-1006352.cif
正在转换mp-1006372.cif
正在转换mp-1006399.cif
正在转换mp-1006878.cif
正在转换mp-1006880.cif
正在转换mp-1006882.cif
正在转换mp-1006884.cif
正在转换mp-1006885.cif
正在转换mp-1006886.cif
正在转换mp-1006887.cif
正在转换mp-1006888.cif
正在转换mp-1006891.cif
正在转换mp-1007636.cif
正在转换mp-1007637.cif
正在转换mp-1007652.cif
正在转换mp-1007656.cif
正在转换mp-1007657.cif
正在转换mp-1007661.cif
正在转换mp-1007663.cif
正在转换mp-1007664.cif
正在转换mp-1007665.cif
正在转换mp-1007685.cif
正在转换mp-1007690.cif
正在转换mp-1007691.cif
正在转换mp-1007692.cif
正在转换mp-1007693.cif
正在转换mp-1007730.cif
正在转换mp-1007755.cif
正在转换mp-1007758.cif
正在转换mp-1007761.cif
正在转换mp-1007770.cif
正在转换mp-1007776.cif

正在转换mp-1007778.cif
正在转换mp-1007786.cif
正在转换mp-1007819.cif
正在转换mp-1007821.cif
正在转换mp-1007823.cif
正在转换mp-1007852.cif
正在转换mp-1007853.cif
正在转换mp-1007854.cif
正在转换mp-1007855.cif
正在转换mp-1007862.cif
正在转换mp-1007881.cif
正在转换mp-1007906.cif
正在转换mp-1007907.cif
正在转换mp-1007908.cif
正在转换mp-1007918.cif
正在转换mp-1007922.cif
正在转换mp-1007923.cif
正在转换mp-1007924.cif
正在转换mp-1007961.cif
正在转换mp-1007974.cif
正在转换mp-1007975.cif
正在转换mp-1007991.cif
正在转换mp-1007992.cif
正在转换mp-1008223.cif
正在转换mp-1008224.cif
正在转换mp-1008225.cif
正在转换mp-1008226.cif
正在转换mp-1008274.cif
正在转换mp-1008275.cif
正在转换mp-1008277.cif
正在转换mp-1008278.cif
正在转换mp-1008279.cif
正在转换mp-1008280.cif
正在转换mp-1008282.cif
正在转换mp-1008284.cif
正在转换mp-1008285.cif
正在转换mp-1008376.cif
正在转换mp-1008472.cif
正在转换mp-1008483.cif
正在转换mp-1008487.cif
正在转换mp-1008488.cif
正在转换mp-1008489.cif
正在转换mp-1008490.cif
正在转换mp-1008491.cif
正在转换mp-1008492.cif
正在转换mp-1008500.cif
正在转换mp-1008506.cif
正在转换mp-1008511.cif
正在转换mp-1008523.cif
正在转换mp-1008524.cif
正在转换mp-1008525.cif
正在转换mp-1008526.cif
正在转换mp-1008527.cif
正在转换mp-1008528.cif
正在转换mp-1008530.cif
正在转换mp-1008554.cif
正在转换mp-1008555.cif
正在转换mp-1008556.cif
正在转换mp-1008557.cif
正在转换mp-1008558.cif
正在转换mp-1008559.cif
正在转换mp-1008561.cif
正在转换mp-1008568.cif
正在转换mp-1008601.cif
正在转换mp-1008610.cif
正在转换mp-1008624.cif
正在转换mp-1008625.cif
正在转换mp-1008630.cif
正在转换mp-1008631.cif
正在转换mp-1008632.cif
正在转换mp-1008635.cif
正在转换mp-1008642.cif
正在转换mp-1008650.cif
正在转换mp-1008653.cif
正在转换mp-1008661.cif
正在转换mp-1008673.cif
正在转换mp-1008676.cif
正在转换mp-1008677.cif
正在转换mp-1008680.cif
正在转换mp-1008688.cif
正在转换mp-1008689.cif
正在转换mp-1008702.cif
正在转换mp-1008726.cif
正在转换mp-1008727.cif
正在转换mp-1008734.cif
正在转换mp-1008752.cif
正在转换mp-1008753.cif
正在转换mp-1008754.cif
正在转换mp-1008755.cif
正在转换mp-1008762.cif
正在转换mp-1008776.cif
正在转换mp-1008785.cif
正在转换mp-1008786.cif
正在转换mp-1008798.cif
正在转换mp-1008805.cif
正在转换mp-1008807.cif
正在转换mp-1008809.cif
正在转换mp-1008813.cif
正在转换mp-1008820.cif
正在转换mp-1008823.cif
正在转换mp-1008826.cif
正在转换mp-1008832.cif
正在转换mp-1008833.cif
正在转换mp-1008835.cif
正在转换mp-1008858.cif
正在转换mp-1008866.cif
正在转换mp-1008867.cif
正在转换mp-1008872.cif
正在转换mp-1008873.cif
正在转换mp-1008874.cif
正在转换mp-1008875.cif
正在转换mp-1008876.cif
正在转换mp-1008881.cif
正在转换mp-1008901.cif
正在转换mp-1008903.cif
正在转换mp-1008910.cif
正在转换mp-1008911.cif
正在转换mp-1008912.cif
正在转换mp-1008920.cif
正在转换mp-1008921.cif
正在转换mp-1008922.cif
正在转换mp-1008924.cif
正在转换mp-1008925.cif
正在转换mp-1008926.cif
正在转换mp-1008927.cif
正在转换mp-1008929.cif
正在转换mp-1008931.cif
正在转换mp-1008965.cif
正在转换mp-1008985.cif
正在转换mp-1008987.cif
正在转换mp-1008998.cif
正在转换mp-1008999.cif
正在转换mp-1009005.cif
正在转换mp-1009006.cif
正在转换mp-1009007.cif
正在转换mp-1009009.cif
正在转换mp-1009014.cif
正在转换mp-1009015.cif
正在转换mp-1009016.cif
正在转换mp-1009017.cif
正在转换mp-1009018.cif
正在转换mp-1009019.cif
正在转换mp-1009020.cif
正在转换mp-1009048.cif
正在转换mp-1009077.cif
正在转换mp-1009078.cif
正在转换mp-1009079.cif
正在转换mp-1009080.cif
正在转换mp-1009082.cif
正在转换mp-1009083.cif
正在转换mp-1009084.cif
正在转换mp-1009085.cif
正在转换mp-1009086.cif
正在转换mp-1009087.cif
正在转换mp-1009088.cif
正在转换mp-1009127.cif
正在转换mp-1009128.cif
正在转换mp-1009129.cif
正在转换mp-1009130.cif
正在转换mp-1009131.cif
正在转换mp-1009132.cif
正在转换mp-1009133.cif
正在转换mp-1009135.cif
正在转换mp-1009206.cif
正在转换mp-1009207.cif
正在转换mp-1009213.cif
正在转换mp-1009217.cif
正在转换mp-1009218.cif
正在转换mp-1009219.cif
正在转换mp-1009220.cif
正在转换mp-1009221.cif
正在转换mp-1009222.cif
正在转换mp-1009223.cif
正在转换mp-1009230.cif
正在转换mp-1009237.cif
正在转换mp-1009458.cif
正在转换mp-1009459.cif
正在转换mp-1009471.cif
正在转换mp-1009483.cif
正在转换mp-1009485.cif
正在转换mp-1009488.cif
正在转换mp-1009489.cif
正在转换mp-1009491.cif
正在转换mp-1009493.cif
正在转换mp-1009494.cif
正在转换mp-1009495.cif
正在转换mp-1009496.cif
正在转换mp-1009533.cif
正在转换mp-1009537.cif
正在转换mp-1009538.cif
正在转换mp-1009539.cif
正在转换mp-1009540.cif
正在转换mp-1009543.cif
正在转换mp-1009545.cif
正在转换mp-1009548.cif
正在转换mp-1009551.cif
正在转换mp-1009555.cif
正在转换mp-1009582.cif
正在转换mp-1009583.cif
正在转换mp-1009592.cif
正在转换mp-1009593.cif
正在转换mp-1009596.cif
正在转换mp-1009601.cif
正在转换mp-1009639.cif
正在转换mp-1009640.cif
正在转换mp-1009646.cif
正在转换mp-1009648.cif
正在转换mp-1009649.cif
正在转换mp-1009650.cif
正在转换mp-1009652.cif
正在转换mp-1009653.cif
正在转换mp-1009654.cif
正在转换mp-1009655.cif
正在转换mp-1009657.cif
正在转换mp-1009663.cif
正在转换mp-1009695.cif
正在转换mp-1009696.cif
正在转换mp-1009720.cif
正在转换mp-1009730.cif
正在转换mp-1009732.cif
正在转换mp-1009733.cif
正在转换mp-1009734.cif
正在转换mp-1009735.cif
正在转换mp-1009746.cif
正在转换mp-1009747.cif
正在转换mp-1009748.cif
正在转换mp-1009750.cif
正在转换mp-1009751.cif
正在转换mp-1009752.cif
正在转换mp-1009753.cif
正在转换mp-1009755.cif
正在转换mp-1009756.cif
正在转换mp-1009766.cif
正在转换mp-1009767.cif
正在转换mp-1009769.cif
正在转换mp-1009770.cif
正在转换mp-1009787.cif
正在转换mp-1009792.cif
正在转换mp-1009813.cif
正在转换mp-1009814.cif
正在转换mp-1009817.cif
正在转换mp-1009818.cif
正在转换mp-1009819.cif
正在转换mp-1009820.cif
正在转换mp-1009822.cif
正在转换mp-1009823.cif
正在转换mp-1009826.cif
正在转换mp-1009827.cif
正在转换mp-1009828.cif
正在转换mp-1009829.cif
正在转换mp-1009830.cif
正在转换mp-1009831.cif
正在转换mp-1009832.cif
正在转换mp-1009833.cif
正在转换mp-1009834.cif
正在转换mp-1009835.cif
正在转换mp-1009836.cif
正在转换mp-1009837.cif
正在转换mp-1009838.cif
正在转换mp-1009839.cif
正在转换mp-1009848.cif
正在转换mp-1009878.cif
正在转换mp-1009885.cif
正在转换mp-1009894.cif
正在转换mp-1010071.cif
正在转换mp-1010161.cif
正在转换mp-1011031.cif
正在转换mp-1011375.cif
正在转换mp-1011376.cif
正在转换mp-1011710.cif
正在转换mp-1012551.cif
正在转换mp-1013524.cif
正在转换mp-1013527.cif
正在转换mp-1013528.cif
正在转换mp-1013529.cif
正在转换mp-1013530.cif
正在转换mp-1013531.cif
正在转换mp-1013532.cif
正在转换mp-1013533.cif
正在转换mp-1013534.cif
正在转换mp-1013535.cif
正在转换mp-1013536.cif
正在转换mp-1013537.cif
正在转换mp-1013540.cif
正在转换mp-1013541.cif
正在转换mp-1013542.cif
正在转换mp-1013543.cif
正在转换mp-1013544.cif
正在转换mp-1013545.cif
正在转换mp-1013546.cif
正在转换mp-1013547.cif
正在转换mp-1013548.cif
正在转换mp-1013549.cif
正在转换mp-1013550.cif
正在转换mp-1013551.cif
正在转换mp-1013552.cif
正在转换mp-1013553.cif
正在转换mp-1013554.cif
正在转换mp-1013555.cif
正在转换mp-1013557.cif
正在转换mp-1013558.cif
正在转换mp-1013559.cif
正在转换mp-1013560.cif
正在转换mp-1013561.cif
正在转换mp-1013562.cif
正在转换mp-1013563.cif
正在转换mp-1013564.cif
正在转换mp-1013582.cif
正在转换mp-1013583.cif
正在转换mp-1013584.cif
正在转换mp-1013585.cif
正在转换mp-1013586.cif
正在转换mp-1013587.cif
正在转换mp-1013588.cif
正在转换mp-1013642.cif
正在转换mp-1013643.cif
正在转换mp-1013691.cif
正在转换mp-1013703.cif
正在转换mp-1013704.cif
正在转换mp-1013705.cif
正在转换mp-1013706.cif
正在转换mp-1013707.cif
正在转换mp-1013708.cif
正在转换mp-1013709.cif
正在转换mp-1013710.cif
正在转换mp-1013711.cif
正在转换mp-1013712.cif
正在转换mp-1013713.cif
正在转换mp-1013714.cif
正在转换mp-1013716.cif
正在转换mp-1013719.cif
正在转换mp-1013726.cif
正在转换mp-1013730.cif
正在转换mp-1013733.cif
正在转换mp-1013734.cif
正在转换mp-1013735.cif
正在转换mp-1013736.cif
正在转换mp-1013737.cif
正在转换mp-1013738.cif
正在转换mp-1013760.cif
正在转换mp-1013911.cif
正在转换mp-1014005.cif
正在转换mp-1014138.cif
正在转换mp-1014160.cif
正在转换mp-1014214.cif
正在转换mp-1014219.cif
正在转换mp-1014226.cif
正在转换mp-1014227.cif
正在转换mp-1014229.cif
正在转换mp-1014230.cif
正在转换mp-1014231.cif
正在转换mp-1014244.cif
正在转换mp-1014246.cif
正在转换mp-1014251.cif
正在转换mp-1014252.cif
正在转换mp-1014264.cif
正在转换mp-1014265.cif
正在转换mp-1014297.cif
正在转换mp-1014303.cif
正在转换mp-1014307.cif
正在转换mp-1014311.cif
正在转换mp-1014316.cif
正在转换mp-1014347.cif
正在转换mp-1014366.cif
正在转换mp-1014373.cif
正在转换mp-1014379.cif
正在转换mp-1014444.cif
正在转换mp-1014454.cif
正在转换mp-1014460.cif
正在转换mp-1014462.cif
正在转换mp-1014478.cif
正在转换mp-1014873.cif
正在转换mp-1014993.cif
正在转换mp-1015076.cif
正在转换mp-1015567.cif
正在转换mp-1015582.cif
正在转换mp-1015612.cif
正在转换mp-1015811.cif
正在转换mp-1015814.cif
正在转换mp-1015908.cif
正在转换mp-1016058.cif
正在转换mp-1016069.cif
正在转换mp-1016076.cif
正在转换mp-1016107.cif
正在转换mp-1016108.cif
正在转换mp-1016197.cif
正在转换mp-1016200.cif
正在转换mp-1016819.cif
正在转换mp-1016820.cif
正在转换mp-1016821.cif
正在转换mp-1016823.cif
正在转换mp-1016825.cif
正在转换mp-1016826.cif
正在转换mp-1016827.cif
正在转换mp-1016828.cif
正在转换mp-1016829.cif
正在转换mp-1016830.cif
正在转换mp-1016833.cif
正在转换mp-1016835.cif
正在转换mp-1016836.cif
正在转换mp-1016837.cif
正在转换mp-1016840.cif
正在转换mp-1016841.cif
正在转换mp-1016842.cif
正在转换mp-1016843.cif
正在转换mp-1016845.cif
正在转换mp-1016846.cif
正在转换mp-1016848.cif
正在转换mp-1016849.cif
正在转换mp-1016850.cif
正在转换mp-1016851.cif
正在转换mp-1016852.cif
正在转换mp-1016853.cif
正在转换mp-1016854.cif
正在转换mp-1016871.cif
正在转换mp-1016872.cif
正在转换mp-1016873.cif
正在转换mp-1016874.cif
正在转换mp-1016875.cif
正在转换mp-1016876.cif
正在转换mp-1016877.cif
正在转换mp-1016879.cif
正在转换mp-1016880.cif
正在转换mp-1016881.cif
正在转换mp-1016882.cif
正在转换mp-1016883.cif
正在转换mp-1016884.cif
正在转换mp-1016886.cif
正在转换mp-1016900.cif
正在转换mp-1016902.cif
正在转换mp-1016903.cif
正在转换mp-1016904.cif
正在转换mp-1016926.cif
正在转换mp-1016927.cif
正在转换mp-1016928.cif
正在转换mp-1016929.cif
正在转换mp-1016930.cif
正在转换mp-1016931.cif
正在转换mp-1016932.cif
正在转换mp-1016938.cif
正在转换mp-1016999.cif
正在转换mp-1017000.cif
正在转换mp-1017439.cif
正在转换mp-1017441.cif
正在转换mp-1017446.cif
正在转换mp-1017447.cif
正在转换mp-1017465.cif
正在转换mp-1017466.cif
正在转换mp-1017467.cif
正在转换mp-1017507.cif
正在转换mp-1017508.cif
正在转换mp-1017509.cif
正在转换mp-1017510.cif
正在转换mp-1017514.cif
正在转换mp-1017515.cif
正在转换mp-1017516.cif
正在转换mp-1017519.cif
正在转换mp-1017529.cif
正在转换mp-1017530.cif
正在转换mp-1017531.cif
正在转换mp-1017532.cif
正在转换mp-1017533.cif
正在转换mp-1017534.cif
正在转换mp-1017539.cif
正在转换mp-1017540.cif
正在转换mp-1017541.cif
正在转换mp-1017542.cif
正在转换mp-1017543.cif
正在转换mp-1017544.cif
正在转换mp-1017545.cif
正在转换mp-1017546.cif
正在转换mp-1017548.cif
正在转换mp-1017549.cif
正在转换mp-1017550.cif
正在转换mp-1017551.cif
正在转换mp-1017552.cif
正在转换mp-1017553.cif
正在转换mp-1017554.cif
正在转换mp-1017556.cif
正在转换mp-1017557.cif
正在转换mp-1017558.cif
正在转换mp-1017563.cif
正在转换mp-1017566.cif
正在转换mp-1017567.cif
正在转换mp-1017577.cif
正在转换mp-1017578.cif

正在转换mp-1017580.cif
正在转换mp-1017581.cif
正在转换mp-1017591.cif
正在转换mp-1017626.cif
正在转换mp-1017627.cif
正在转换mp-1017628.cif
正在转换mp-1017629.cif
正在转换mp-1017631.cif
正在转换mp-1017632.cif
正在转换mp-1017982.cif
正在转换mp-1017985.cif
正在转换mp-1017987.cif
正在转换mp-1017988.cif
正在转换mp-1018009.cif
正在转换mp-1018012.cif
正在转换mp-1018013.cif
正在转换mp-1018015.cif
正在转换mp-1018018.cif
正在转换mp-1018019.cif
正在转换mp-1018020.cif
正在转换mp-1018021.cif
正在转换mp-1018022.cif
正在转换mp-1018024.cif
正在转换mp-1018025.cif
正在转换mp-1018027.cif
正在转换mp-1018028.cif
正在转换mp-1018029.cif
正在转换mp-1018030.cif
正在转换mp-1018031.cif
正在转换mp-1018032.cif
正在转换mp-1018033.cif
正在转换mp-1018040.cif
正在转换mp-1018041.cif
正在转换mp-1018042.cif
正在转换mp-1018043.cif
正在转换mp-1018046.cif
正在转换mp-1018050.cif
正在转换mp-1018051.cif
正在转换mp-1018052.cif
正在转换mp-1018054.cif
正在转换mp-1018057.cif
正在转换mp-1018059.cif
正在转换mp-1018061.cif
正在转换mp-1018062.cif
正在转换mp-1018063.cif
正在转换mp-1018064.cif
正在转换mp-1018065.cif
正在转换mp-1018066.cif
正在转换mp-1018067.cif
正在转换mp-1018068.cif
正在转换mp-1018070.cif
正在转换mp-1018071.cif
正在转换mp-1018072.cif
正在转换mp-1018073.cif
正在转换mp-1018074.cif
正在转换mp-1018075.cif
正在转换mp-1018076.cif
正在转换mp-1018077.cif
正在转换mp-1018079.cif
正在转换mp-1018080.cif
正在转换mp-1018081.cif
正在转换mp-1018082.cif
正在转换mp-1018083.cif
正在转换mp-1018084.cif
正在转换mp-1018085.cif
正在转换mp-1018086.cif
正在转换mp-1018087.cif
正在转换mp-1018089.cif
正在转换mp-1018090.cif
正在转换mp-1018091.cif
正在转换mp-1018093.cif
正在转换mp-1018094.cif
正在转换mp-1018095.cif
正在转换mp-1018096.cif
正在转换mp-1018097.cif
正在转换mp-1018098.cif
正在转换mp-1018099.cif
正在转换mp-1018100.cif
正在转换mp-1018101.cif
正在转换mp-1018102.cif
正在转换mp-1018103.cif
正在转换mp-1018104.cif
正在转换mp-1018105.cif
正在转换mp-1018106.cif
正在转换mp-1018112.cif
正在转换mp-1018113.cif
正在转换mp-1018116.cif
正在转换mp-1018117.cif
正在转换mp-1018118.cif
正在转换mp-1018119.cif
正在转换mp-1018121.cif
正在转换mp-1018123.cif
正在转换mp-1018124.cif
正在转换mp-1018125.cif
正在转换mp-1018126.cif
正在转换mp-1018127.cif
正在转换mp-1018128.cif
正在转换mp-1018130.cif
正在转换mp-1018131.cif
正在转换mp-1018132.cif
正在转换mp-1018133.cif
正在转换mp-1018135.cif
正在转换mp-1018136.cif
正在转换mp-1018139.cif
正在转换mp-1018140.cif
正在转换mp-1018141.cif
正在转换mp-1018142.cif
正在转换mp-1018145.cif
正在转换mp-1018148.cif
正在转换mp-1018149.cif
正在转换mp-1018151.cif
正在转换mp-1018153.cif
正在转换mp-1018154.cif
正在转换mp-1018155.cif
正在转换mp-1018156.cif
正在转换mp-1018157.cif
正在转换mp-1018158.cif
正在转换mp-1018159.cif
正在转换mp-1018160.cif
正在转换mp-1018161.cif
正在转换mp-1018162.cif
正在转换mp-1018164.cif
正在转换mp-1018165.cif
正在转换mp-1018166.cif
正在转换mp-1018175.cif
正在转换mp-1018178.cif
正在转换mp-1018627.cif
正在转换mp-1018628.cif
正在转换mp-1018629.cif
正在转换mp-1018630.cif
正在转换mp-1018635.cif
正在转换mp-1018636.cif
正在转换mp-1018637.cif
正在转换mp-1018638.cif
正在转换mp-1018639.cif
正在转换mp-1018640.cif
正在转换mp-1018641.cif
正在转换mp-1018642.cif
正在转换mp-1018643.cif
正在转换mp-1018644.cif
正在转换mp-1018645.cif
正在转换mp-1018646.cif
正在转换mp-1018647.cif
正在转换mp-1018649.cif
正在转换mp-1018650.cif
正在转换mp-1018651.cif
正在转换mp-1018652.cif
正在转换mp-1018653.cif
正在转换mp-1018654.cif
正在转换mp-1018656.cif
正在转换mp-1018657.cif
正在转换mp-1018658.cif
正在转换mp-1018659.cif
正在转换mp-1018660.cif
正在转换mp-1018661.cif
正在转换mp-1018662.cif
正在转换mp-1018663.cif
正在转换mp-1018664.cif
正在转换mp-1018665.cif
正在转换mp-1018666.cif
正在转换mp-1018667.cif
正在转换mp-1018668.cif
正在转换mp-1018671.cif
正在转换mp-1018672.cif
正在转换mp-1018673.cif
正在转换mp-1018674.cif
正在转换mp-1018675.cif
正在转换mp-1018676.cif
正在转换mp-1018677.cif
正在转换mp-1018679.cif
正在转换mp-1018680.cif
正在转换mp-1018681.cif
正在转换mp-1018682.cif
正在转换mp-1018684.cif
正在转换mp-1018685.cif
正在转换mp-1018686.cif
正在转换mp-1018687.cif
正在转换mp-1018689.cif
正在转换mp-1018690.cif
正在转换mp-1018692.cif
正在转换mp-1018694.cif
正在转换mp-1018709.cif
正在转换mp-1018710.cif
正在转换mp-1018712.cif
正在转换mp-1018713.cif
正在转换mp-1018714.cif
正在转换mp-1018715.cif
正在转换mp-1018716.cif
正在转换mp-1018717.cif
正在转换mp-1018719.cif
正在转换mp-1018720.cif
正在转换mp-1018721.cif
正在转换mp-1018722.cif
正在转换mp-1018723.cif
正在转换mp-1018724.cif
正在转换mp-1018725.cif
正在转换mp-1018726.cif
正在转换mp-1018727.cif
正在转换mp-1018728.cif
正在转换mp-1018729.cif
正在转换mp-1018732.cif
正在转换mp-1018733.cif
正在转换mp-1018734.cif
正在转换mp-1018735.cif
正在转换mp-1018736.cif
正在转换mp-1018737.cif
正在转换mp-1018739.cif
正在转换mp-1018742.cif
正在转换mp-1018761.cif
正在转换mp-1018762.cif
正在转换mp-1018763.cif
正在转换mp-1018764.cif
正在转换mp-1018768.cif
正在转换mp-1018769.cif
正在转换mp-1018770.cif
正在转换mp-1018779.cif
正在转换mp-1018780.cif
正在转换mp-1018781.cif
正在转换mp-1018782.cif
正在转换mp-1018783.cif
正在转换mp-1018784.cif
正在转换mp-1018785.cif
正在转换mp-1018786.cif
正在转换mp-1018789.cif
正在转换mp-1018791.cif
正在转换mp-1018792.cif
正在转换mp-1018793.cif
正在转换mp-1018794.cif
正在转换mp-1018795.cif
正在转换mp-1018796.cif
正在转换mp-1018797.cif
正在转换mp-1018798.cif
正在转换mp-1018799.cif
正在转换mp-1018800.cif
正在转换mp-1018802.cif
正在转换mp-1018803.cif
正在转换mp-1018804.cif
正在转换mp-1018810.cif
正在转换mp-1018811.cif
正在转换mp-1018812.cif
正在转换mp-1018814.cif
正在转换mp-1018815.cif
正在转换mp-1018817.cif
正在转换mp-1018818.cif
正在转换mp-1018819.cif
正在转换mp-1018822.cif
正在转换mp-1018823.cif
正在转换mp-1018824.cif
正在转换mp-1018825.cif
正在转换mp-1018826.cif
正在转换mp-1018828.cif
正在转换mp-1018849.cif
正在转换mp-1018850.cif
正在转换mp-1018851.cif
正在转换mp-1018852.cif
正在转换mp-1018880.cif
正在转换mp-1018886.cif
正在转换mp-1018888.cif
正在转换mp-1018890.cif
正在转换mp-1018892.cif
正在转换mp-1018893.cif
正在转换mp-1018895.cif
正在转换mp-1018896.cif
正在转换mp-1018899.cif
正在转换mp-1018900.cif
正在转换mp-1018902.cif
正在转换mp-1018936.cif
正在转换mp-1018940.cif
正在转换mp-1018941.cif
正在转换mp-1018942.cif
正在转换mp-1018946.cif
正在转换mp-1018947.cif
正在转换mp-1018948.cif
正在转换mp-1018949.cif
正在转换mp-1018952.cif
正在转换mp-1019051.cif
正在转换mp-1019052.cif
正在转换mp-1019054.cif
正在转换mp-1019055.cif
正在转换mp-1019077.cif
正在转换mp-1019080.cif
正在转换mp-1019082.cif
正在转换mp-1019083.cif
正在转换mp-1019087.cif
正在转换mp-1019089.cif
正在转换mp-1019093.cif
正在转换mp-1019094.cif
正在转换mp-1019097.cif
正在转换mp-1019100.cif
正在转换mp-1019101.cif
正在转换mp-1019102.cif
正在转换mp-1019103.cif
正在转换mp-1019104.cif
正在转换mp-1019105.cif
正在转换mp-1019108.cif
正在转换mp-1019109.cif
正在转换mp-1019110.cif
正在转换mp-1019138.cif
正在转换mp-1019238.cif
正在转换mp-1019253.cif
正在转换mp-1019255.cif
正在转换mp-1019256.cif
正在转换mp-1019257.cif
正在转换mp-1019258.cif
正在转换mp-1019259.cif
正在转换mp-1019262.cif
正在转换mp-1019266.cif
正在转换mp-1019269.cif
正在转换mp-1019270.cif
正在转换mp-1019271.cif
正在转换mp-1019272.cif
正在转换mp-1019273.cif
正在转换mp-1019275.cif
正在转换mp-1019277.cif
正在转换mp-1019278.cif
正在转换mp-1019279.cif
正在转换mp-1019280.cif
正在转换mp-1019281.cif
正在转换mp-1019315.cif
正在转换mp-1019316.cif
正在转换mp-1019317.cif
正在转换mp-1019319.cif
正在转换mp-1019323.cif
正在转换mp-1019324.cif
正在转换mp-1019357.cif
正在转换mp-1019358.cif
正在转换mp-1019359.cif
正在转换mp-1019360.cif
正在转换mp-1019361.cif
正在转换mp-1019362.cif
正在转换mp-1019363.cif
正在转换mp-1019378.cif
正在转换mp-1019379.cif
正在转换mp-1019380.cif
正在转换mp-1019508.cif
正在转换mp-1019520.cif
正在转换mp-1019524.cif
正在转换mp-1019526.cif
正在转换mp-1019528.cif
正在转换mp-1019531.cif
正在转换mp-1019535.cif
正在转换mp-1019536.cif
正在转换mp-1019537.cif
正在转换mp-1019541.cif
正在转换mp-1019544.cif
正在转换mp-1019547.cif
正在转换mp-1019550.cif
正在转换mp-1019551.cif
正在转换mp-1019558.cif
正在转换mp-1019561.cif
正在转换mp-1019562.cif
正在转换mp-1019563.cif
正在转换mp-1019564.cif
正在转换mp-1019566.cif
正在转换mp-1019578.cif
正在转换mp-1019586.cif
正在转换mp-1019587.cif
正在转换mp-1019589.cif
正在转换mp-1019591.cif
正在转换mp-1019595.cif
正在转换mp-1019596.cif
正在转换mp-1019599.cif
正在转换mp-1019600.cif
正在转换mp-1019601.cif
正在转换mp-1019740.cif
正在转换mp-1019742.cif
正在转换mp-1019743.cif
正在转换mp-1019794.cif
正在转换mp-1019796.cif
正在转换mp-1019799.cif
正在转换mp-1019800.cif
正在转换mp-1019801.cif
正在转换mp-1019888.cif
正在转换mp-1019898.cif
正在转换mp-1020011.cif
正在转换mp-1020016.cif
正在转换mp-1020019.cif
正在转换mp-1020020.cif

C:\Users\mk\AppData\Roaming\Python\Python39\site-packages\pymatgen\core\periodic_table.py:212: UserWarning: No electronegativity for He. Setting to NaN. This has no physical meaning, and is mainly done to avoid errors caused by the code expecting a float.
  warnings.warn(

正在转换mp-1020022.cif
正在转换mp-1020026.cif
正在转换mp-1020029.cif
正在转换mp-1020031.cif
正在转换mp-1020032.cif
正在转换mp-1020059.cif
正在转换mp-1020108.cif
正在转换mp-1020110.cif
正在转换mp-1020112.cif
正在转换mp-1020122.cif
正在转换mp-1020164.cif
正在转换mp-1020193.cif
正在转换mp-1020578.cif
正在转换mp-1020588.cif
正在转换mp-1020590.cif
正在转换mp-1020591.cif
正在转换mp-1020594.cif
正在转换mp-1020595.cif
正在转换mp-1020596.cif
正在转换mp-1020608.cif
正在转换mp-1020609.cif
正在转换mp-1020610.cif
正在转换mp-1020622.cif
正在转换mp-1020623.cif
正在转换mp-1020625.cif
正在转换mp-1020628.cif
正在转换mp-1020631.cif
正在转换mp-1020633.cif
正在转换mp-1020638.cif
正在转换mp-1020645.cif
正在转换mp-1020646.cif
正在转换mp-1020650.cif
正在转换mp-1020657.cif
正在转换mp-1020658.cif
正在转换mp-1020663.cif
正在转换mp-1020666.cif
正在转换mp-1020683.cif
正在转换mp-1020703.cif
正在转换mp-1020712.cif
正在转换mp-1020715.cif
正在转换mp-1020717.cif
正在转换mp-1020721.cif
正在转换mp-1020797.cif
正在转换mp-1021323.cif
正在转换mp-1021327.cif
正在转换mp-1021465.cif
正在转换mp-1021484.cif
正在转换mp-1021489.cif
正在转换mp-1021490.cif
正在转换mp-1021492.cif
正在转换mp-1021494.cif
正在转换mp-1021497.cif
正在转换mp-1021498.cif
正在转换mp-1021499.cif
正在转换mp-1021504.cif
正在转换mp-1021505.cif
正在转换mp-1021507.cif
正在转换mp-1021508.cif
正在转换mp-1021509.cif
正在转换mp-1021512.cif
正在转换mp-1021516.cif
正在转换mp-1021659.cif
正在转换mp-1021660.cif
正在转换mp-1021666.cif
正在转换mp-1021667.cif
正在转换mp-1021668.cif
正在转换mp-1021669.cif
正在转换mp-1021670.cif
正在转换mp-1021672.cif
正在转换mp-1021674.cif
正在转换mp-1022721.cif
正在转换mp-1022723.cif
正在转换mp-1022726.cif
正在转换mp-1022728.cif
正在转换mp-1022729.cif
正在转换mp-1023124.cif
正在转换mp-1023128.cif
正在转换mp-1023132.cif
正在转换mp-1023918.cif
正在转换mp-1024047.cif
正在转换mp-1024049.cif
正在转换mp-1024050.cif
正在转换mp-1024051.cif
正在转换mp-1024052.cif
正在转换mp-1024054.cif
正在转换mp-1024067.cif
正在转换mp-1024069.cif
正在转换mp-1024071.cif
正在转换mp-1024940.cif
正在转换mp-1024951.cif
正在转换mp-1024954.cif
正在转换mp-1024955.cif
正在转换mp-1024957.cif
正在转换mp-1024960.cif
正在转换mp-1024962.cif
正在转换mp-1024964.cif
正在转换mp-1024972.cif
正在转换mp-1024974.cif
正在转换mp-1024975.cif
正在转换mp-1024977.cif
正在转换mp-1024983.cif
正在转换mp-1025009.cif
正在转换mp-1025010.cif
正在转换mp-1025021.cif
正在转换mp-1025022.cif
正在转换mp-1025029.cif
正在转换mp-1025033.cif
正在转换mp-1025039.cif
正在转换mp-1025044.cif
正在转换mp-1025045.cif
正在转换mp-1025047.cif
正在转换mp-1025053.cif
正在转换mp-1025056.cif
正在转换mp-1025066.cif
正在转换mp-1025077.cif
正在转换mp-1025087.cif
正在转换mp-1025095.cif
正在转换mp-1025098.cif
正在转换mp-1025102.cif
正在转换mp-1025105.cif
正在转换mp-1025113.cif
正在转换mp-1025116.cif
正在转换mp-1025122.cif
正在转换mp-1025123.cif
正在转换mp-1025124.cif
正在转换mp-1025126.cif
正在转换mp-1025127.cif
正在转换mp-1025128.cif
正在转换mp-1025129.cif
正在转换mp-1025134.cif
正在转换mp-1025137.cif
正在转换mp-1025140.cif
正在转换mp-1025143.cif
正在转换mp-1025144.cif
正在转换mp-1025149.cif
正在转换mp-1025150.cif
正在转换mp-1025151.cif
正在转换mp-1025154.cif
正在转换mp-1025155.cif
正在转换mp-1025156.cif
正在转换mp-1025158.cif
正在转换mp-1025159.cif
正在转换mp-1025161.cif
正在转换mp-1025162.cif
正在转换mp-1025165.cif
正在转换mp-1025167.cif
正在转换mp-1025170.cif
正在转换mp-1025172.cif
正在转换mp-1025173.cif
正在转换mp-1025174.cif
正在转换mp-1025175.cif
正在转换mp-1025176.cif
正在转换mp-1025177.cif
正在转换mp-1025179.cif
正在转换mp-1025180.cif
正在转换mp-1025181.cif
正在转换mp-1025182.cif
正在转换mp-1025183.cif
正在转换mp-1025187.cif
正在转换mp-1025189.cif
正在转换mp-1025190.cif
正在转换mp-1025191.cif
正在转换mp-1025192.cif
正在转换mp-1025193.cif
正在转换mp-1025195.cif
正在转换mp-1025198.cif
正在转换mp-1025201.cif
正在转换mp-1025203.cif
正在转换mp-1025205.cif
正在转换mp-1025207.cif
正在转换mp-1025210.cif
正在转换mp-1025212.cif
正在转换mp-1025213.cif
正在转换mp-1025218.cif
正在转换mp-1025219.cif
正在转换mp-1025220.cif
正在转换mp-1025221.cif
正在转换mp-1025222.cif
正在转换mp-1025223.cif
正在转换mp-1025224.cif
正在转换mp-1025225.cif
正在转换mp-1025227.cif
正在转换mp-1025229.cif
正在转换mp-1025231.cif
正在转换mp-1025232.cif
正在转换mp-1025235.cif
正在转换mp-1025236.cif
正在转换mp-1025237.cif
正在转换mp-1025238.cif
正在转换mp-1025239.cif
正在转换mp-1025240.cif
正在转换mp-1025241.cif
正在转换mp-1025242.cif
正在转换mp-1025246.cif
正在转换mp-1025248.cif
正在转换mp-1025249.cif
正在转换mp-1025253.cif
正在转换mp-1025257.cif
正在转换mp-1025258.cif
正在转换mp-1025261.cif
正在转换mp-1025262.cif
正在转换mp-1025263.cif
正在转换mp-1025264.cif
正在转换mp-1025266.cif
正在转换mp-1025268.cif
正在转换mp-1025269.cif
正在转换mp-1025270.cif
正在转换mp-1025271.cif
正在转换mp-1025272.cif
正在转换mp-1025275.cif
正在转换mp-1025276.cif
正在转换mp-1025277.cif
正在转换mp-1025278.cif
正在转换mp-1025279.cif
正在转换mp-1025280.cif
正在转换mp-1025281.cif
正在转换mp-1025282.cif
正在转换mp-1025283.cif
正在转换mp-1025286.cif
正在转换mp-1025288.cif
正在转换mp-1025289.cif
正在转换mp-1025291.cif
正在转换mp-1025293.cif
正在转换mp-1025294.cif
正在转换mp-1025296.cif
正在转换mp-1025297.cif
正在转换mp-1025299.cif
正在转换mp-1025301.cif
正在转换mp-1025302.cif
正在转换mp-1025304.cif
正在转换mp-1025306.cif
正在转换mp-1025309.cif
正在转换mp-1025311.cif
正在转换mp-1025313.cif
正在转换mp-1025315.cif
正在转换mp-1025316.cif
正在转换mp-1025318.cif
正在转换mp-1025321.cif
正在转换mp-1025322.cif
正在转换mp-1025323.cif
正在转换mp-1025324.cif
正在转换mp-1025325.cif
正在转换mp-1025329.cif
正在转换mp-1025331.cif
正在转换mp-1025333.cif
正在转换mp-1025335.cif
正在转换mp-1025337.cif
正在转换mp-1025338.cif
正在转换mp-1025339.cif
正在转换mp-1025341.cif
正在转换mp-1025343.cif
正在转换mp-1025344.cif
正在转换mp-1025345.cif
正在转换mp-1025346.cif
正在转换mp-1025347.cif
正在转换mp-1025348.cif
正在转换mp-1025349.cif
正在转换mp-1025351.cif
正在转换mp-1025352.cif
正在转换mp-1025353.cif
正在转换mp-1025354.cif
正在转换mp-1025355.cif
正在转换mp-1025356.cif
正在转换mp-1025357.cif
正在转换mp-1025358.cif
正在转换mp-1025359.cif
正在转换mp-1025360.cif
正在转换mp-1025362.cif
正在转换mp-1025364.cif
正在转换mp-1025365.cif
正在转换mp-1025366.cif
正在转换mp-1025368.cif
正在转换mp-1025370.cif
正在转换mp-1025371.cif
正在转换mp-1025372.cif
正在转换mp-1025375.cif
正在转换mp-1025377.cif
正在转换mp-1025378.cif
正在转换mp-1025379.cif
正在转换mp-1025380.cif
正在转换mp-1025382.cif
正在转换mp-1025383.cif
正在转换mp-1025384.cif
正在转换mp-1025385.cif
正在转换mp-1025386.cif
正在转换mp-1025387.cif
正在转换mp-1025389.cif
正在转换mp-1025393.cif
正在转换mp-1025396.cif
正在转换mp-1025397.cif
正在转换mp-1025402.cif
正在转换mp-1025496.cif
正在转换mp-1025497.cif
正在转换mp-1025498.cif
正在转换mp-1025500.cif
正在转换mp-1025503.cif
正在转换mp-1025509.cif
正在转换mp-1025510.cif
正在转换mp-1025511.cif
正在转换mp-1025517.cif
正在转换mp-1025519.cif
正在转换mp-1025521.cif
正在转换mp-1025524.cif
正在转换mp-1025540.cif
正在转换mp-1025549.cif
正在转换mp-1025550.cif
正在转换mp-1025551.cif
正在转换mp-1025565.cif
正在转换mp-1025568.cif
正在转换mp-1040450.cif
正在转换mp-1040464.cif
正在转换mp-1040467.cif
正在转换mp-1040472.cif
正在转换mp-1040497.cif
正在转换mp-861639.cif
正在转换mp-861640.cif
正在转换mp-861643.cif
正在转换mp-861644.cif
正在转换mp-861645.cif
正在转换mp-861646.cif
正在转换mp-861651.cif
正在转换mp-861652.cif
正在转换mp-861653.cif
正在转换mp-861654.cif
正在转换mp-861656.cif
正在转换mp-861657.cif
正在转换mp-861658.cif
正在转换mp-861660.cif
正在转换mp-861661.cif
正在转换mp-861662.cif
正在转换mp-861663.cif
正在转换mp-861664.cif
正在转换mp-861665.cif
正在转换mp-861666.cif
正在转换mp-861667.cif
正在转换mp-861672.cif
正在转换mp-861724.cif
正在转换mp-861725.cif
正在转换mp-861733.cif
正在转换mp-861734.cif
正在转换mp-861735.cif
正在转换mp-861736.cif
正在转换mp-861738.cif
正在转换mp-861869.cif
正在转换mp-861872.cif
正在转换mp-861873.cif
正在转换mp-861874.cif
正在转换mp-861875.cif
正在转换mp-861876.cif
正在转换mp-861877.cif
正在转换mp-861878.cif
正在转换mp-861880.cif
正在转换mp-861881.cif
正在转换mp-861882.cif
正在转换mp-861883.cif
正在转换mp-861884.cif
正在转换mp-861885.cif
正在转换mp-861886.cif
正在转换mp-861888.cif
正在转换mp-861889.cif
正在转换mp-861892.cif
正在转换mp-861896.cif
正在转换mp-861900.cif
正在转换mp-861901.cif
正在转换mp-861903.cif
正在转换mp-861905.cif
正在转换mp-861906.cif
正在转换mp-861908.cif
正在转换mp-861909.cif
正在转换mp-861910.cif
正在转换mp-861912.cif
正在转换mp-861913.cif
正在转换mp-861915.cif
正在转换mp-861918.cif
正在转换mp-861930.cif
正在转换mp-861931.cif
正在转换mp-861932.cif
正在转换mp-861933.cif
正在转换mp-861934.cif
正在转换mp-861935.cif
正在转换mp-861936.cif
正在转换mp-861937.cif
正在转换mp-861939.cif
正在转换mp-861940.cif
正在转换mp-861946.cif
正在转换mp-861947.cif
正在转换mp-861948.cif
正在转换mp-861950.cif
正在转换mp-861951.cif
正在转换mp-861953.cif
正在转换mp-861954.cif
正在转换mp-861955.cif
正在转换mp-861956.cif
正在转换mp-861958.cif
正在转换mp-861960.cif
正在转换mp-861964.cif
正在转换mp-861966.cif
正在转换mp-861968.cif
正在转换mp-861969.cif
正在转换mp-861973.cif
正在转换mp-861974.cif
正在转换mp-861975.cif
正在转换mp-861976.cif
正在转换mp-861978.cif
正在转换mp-861979.cif
正在转换mp-861980.cif
正在转换mp-861981.cif
正在转换mp-861982.cif
正在转换mp-861984.cif
正在转换mp-861985.cif
正在转换mp-861988.cif
正在转换mp-861991.cif
正在转换mp-861992.cif
正在转换mp-861993.cif
正在转换mp-861994.cif
正在转换mp-862256.cif
正在转换mp-862257.cif
正在转换mp-862258.cif
正在转换mp-862259.cif
正在转换mp-862260.cif
正在转换mp-862261.cif
正在转换mp-862263.cif
正在转换mp-862264.cif
正在转换mp-862287.cif
正在转换mp-862288.cif
正在转换mp-862291.cif
正在转换mp-862296.cif
正在转换mp-862297.cif
正在转换mp-862300.cif
正在转换mp-862311.cif
正在转换mp-862312.cif
正在转换mp-862316.cif
正在转换mp-862318.cif
正在转换mp-862319.cif
正在转换mp-862321.cif
正在转换mp-862324.cif
正在转换mp-862329.cif
正在转换mp-862335.cif
正在转换mp-862336.cif
正在转换mp-862337.cif
正在转换mp-862338.cif
正在转换mp-862339.cif
正在转换mp-862340.cif
正在转换mp-862360.cif
正在转换mp-862361.cif
正在转换mp-862362.cif
正在转换mp-862363.cif
正在转换mp-862364.cif
正在转换mp-862365.cif
正在转换mp-862366.cif
正在转换mp-862367.cif
正在转换mp-862368.cif
正在转换mp-862369.cif
正在转换mp-862370.cif
正在转换mp-862371.cif
正在转换mp-862372.cif
正在转换mp-862373.cif
正在转换mp-862374.cif
正在转换mp-862375.cif
正在转换mp-862376.cif
正在转换mp-862377.cif
正在转换mp-862378.cif
正在转换mp-862379.cif
正在转换mp-862423.cif
正在转换mp-862424.cif
正在转换mp-862431.cif
正在转换mp-862432.cif
正在转换mp-862445.cif
正在转换mp-862446.cif
正在转换mp-862473.cif
正在转换mp-862485.cif
正在转换mp-862486.cif
正在转换mp-862492.cif
正在转换mp-862493.cif
正在转换mp-862536.cif
正在转换mp-862543.cif
正在转换mp-862545.cif
正在转换mp-862546.cif
正在转换mp-862548.cif
正在转换mp-862549.cif
正在转换mp-862554.cif
正在转换mp-862555.cif
正在转换mp-862556.cif
正在转换mp-862558.cif

正在转换mp-862561.cif
正在转换mp-862563.cif
正在转换mp-862565.cif
正在转换mp-862586.cif
正在转换mp-862588.cif
正在转换mp-862589.cif
正在转换mp-862599.cif
正在转换mp-862600.cif
正在转换mp-862601.cif
正在转换mp-862602.cif
正在转换mp-862609.cif
正在转换mp-862610.cif
正在转换mp-862612.cif
正在转换mp-862613.cif
正在转换mp-862614.cif
正在转换mp-862615.cif
正在转换mp-862617.cif
正在转换mp-862619.cif
正在转换mp-862620.cif
正在转换mp-862621.cif
正在转换mp-862622.cif
正在转换mp-862629.cif
正在转换mp-862630.cif
正在转换mp-862632.cif
正在转换mp-862635.cif
正在转换mp-862654.cif
正在转换mp-862655.cif
正在转换mp-862657.cif
正在转换mp-862658.cif
正在转换mp-862660.cif
正在转换mp-862661.cif
正在转换mp-862662.cif
正在转换mp-862664.cif
正在转换mp-862666.cif
正在转换mp-862667.cif
正在转换mp-862669.cif
正在转换mp-862670.cif
正在转换mp-862672.cif
正在转换mp-862673.cif
正在转换mp-862676.cif
正在转换mp-862677.cif
正在转换mp-862680.cif
正在转换mp-862681.cif
正在转换mp-862683.cif
正在转换mp-862684.cif
正在转换mp-862685.cif
正在转换mp-862691.cif
正在转换mp-862692.cif
正在转换mp-862693.cif
正在转换mp-862694.cif
正在转换mp-862695.cif
正在转换mp-862699.cif
正在转换mp-862700.cif
正在转换mp-862702.cif
正在转换mp-862703.cif
正在转换mp-862704.cif
正在转换mp-862705.cif
正在转换mp-862706.cif
正在转换mp-862710.cif
正在转换mp-862711.cif
正在转换mp-862713.cif
正在转换mp-862714.cif
正在转换mp-862715.cif
正在转换mp-862716.cif
正在转换mp-862717.cif
正在转换mp-862719.cif
正在转换mp-862720.cif
正在转换mp-862721.cif
正在转换mp-862722.cif
正在转换mp-862723.cif
正在转换mp-862725.cif
正在转换mp-862727.cif
正在转换mp-862728.cif
正在转换mp-862730.cif
正在转换mp-862731.cif
正在转换mp-862732.cif
正在转换mp-862733.cif
正在转换mp-862734.cif
正在转换mp-862735.cif
正在转换mp-862736.cif
正在转换mp-862737.cif
正在转换mp-862738.cif
正在转换mp-862740.cif
正在转换mp-862742.cif
正在转换mp-862744.cif
正在转换mp-862745.cif
正在转换mp-862746.cif
正在转换mp-862747.cif
正在转换mp-862749.cif
正在转换mp-862752.cif
正在转换mp-862754.cif
正在转换mp-862755.cif
正在转换mp-862756.cif
正在转换mp-862757.cif
正在转换mp-862758.cif
正在转换mp-862759.cif
正在转换mp-862760.cif
正在转换mp-862761.cif
正在转换mp-862763.cif
正在转换mp-862764.cif
正在转换mp-862767.cif
正在转换mp-862770.cif
正在转换mp-862774.cif
正在转换mp-862777.cif
正在转换mp-862778.cif
正在转换mp-862779.cif
正在转换mp-862780.cif
正在转换mp-862781.cif
正在转换mp-862783.cif
正在转换mp-862786.cif
正在转换mp-862788.cif
正在转换mp-862789.cif
正在转换mp-862790.cif
正在转换mp-862792.cif
正在转换mp-862795.cif
正在转换mp-862797.cif
正在转换mp-862805.cif
正在转换mp-862806.cif
正在转换mp-862813.cif
正在转换mp-862816.cif
正在转换mp-862820.cif
正在转换mp-862822.cif
正在转换mp-862824.cif
正在转换mp-862831.cif
正在转换mp-862832.cif
正在转换mp-862833.cif
正在转换mp-862835.cif
正在转换mp-862836.cif
正在转换mp-862837.cif
正在转换mp-862838.cif
正在转换mp-862842.cif
正在转换mp-862843.cif
正在转换mp-862845.cif
正在转换mp-862846.cif
正在转换mp-862847.cif
正在转换mp-862848.cif
正在转换mp-862849.cif
正在转换mp-862850.cif
正在转换mp-862854.cif
正在转换mp-862855.cif
正在转换mp-862858.cif
正在转换mp-862860.cif
正在转换mp-862861.cif
正在转换mp-862862.cif
正在转换mp-862863.cif
正在转换mp-862866.cif
正在转换mp-862867.cif
正在转换mp-862869.cif
正在转换mp-862870.cif
正在转换mp-862871.cif
正在转换mp-862872.cif
正在转换mp-862873.cif
正在转换mp-862874.cif
正在转换mp-862875.cif
正在转换mp-862877.cif
正在转换mp-862878.cif
正在转换mp-862879.cif
正在转换mp-862880.cif
正在转换mp-862881.cif
正在转换mp-862882.cif
正在转换mp-862883.cif
正在转换mp-862884.cif
正在转换mp-862885.cif
正在转换mp-862886.cif
正在转换mp-862887.cif
正在转换mp-862888.cif
正在转换mp-862889.cif
正在转换mp-862890.cif
正在转换mp-862891.cif
正在转换mp-862892.cif
正在转换mp-862894.cif
正在转换mp-862897.cif
正在转换mp-862898.cif
正在转换mp-862899.cif
正在转换mp-862900.cif
正在转换mp-862901.cif
正在转换mp-862902.cif
正在转换mp-862903.cif
正在转换mp-862905.cif
正在转换mp-862906.cif
正在转换mp-862909.cif
正在转换mp-862910.cif
正在转换mp-862912.cif
正在转换mp-862913.cif
正在转换mp-862914.cif
正在转换mp-862915.cif
正在转换mp-862916.cif
正在转换mp-862917.cif
正在转换mp-862918.cif
正在转换mp-862921.cif
正在转换mp-862922.cif
正在转换mp-862923.cif
正在转换mp-862924.cif
正在转换mp-862928.cif
正在转换mp-862929.cif
正在转换mp-862930.cif
正在转换mp-862932.cif
正在转换mp-862933.cif
正在转换mp-862934.cif
正在转换mp-862935.cif
正在转换mp-862936.cif
正在转换mp-862937.cif
正在转换mp-862938.cif
正在转换mp-862939.cif
正在转换mp-862940.cif
正在转换mp-862941.cif
正在转换mp-862942.cif
正在转换mp-862943.cif
正在转换mp-862944.cif
正在转换mp-862946.cif
正在转换mp-862947.cif
正在转换mp-862948.cif
正在转换mp-862949.cif
正在转换mp-862950.cif
正在转换mp-862951.cif
正在转换mp-862952.cif
正在转换mp-862953.cif
正在转换mp-862954.cif
正在转换mp-862955.cif
正在转换mp-862956.cif
正在转换mp-862957.cif
正在转换mp-862958.cif
正在转换mp-862959.cif
正在转换mp-862960.cif
正在转换mp-862961.cif
正在转换mp-862962.cif
正在转换mp-862963.cif
正在转换mp-862964.cif
正在转换mp-862965.cif
正在转换mp-862966.cif
正在转换mp-862967.cif
正在转换mp-862968.cif
正在转换mp-862969.cif
正在转换mp-862970.cif
正在转换mp-862972.cif
正在转换mp-862973.cif
正在转换mp-862974.cif
正在转换mp-862975.cif
正在转换mp-862976.cif
正在转换mp-862977.cif
正在转换mp-862978.cif
正在转换mp-862979.cif
正在转换mp-862980.cif
正在转换mp-862981.cif
正在转换mp-862984.cif
正在转换mp-862985.cif
正在转换mp-862989.cif
正在转换mp-862990.cif
正在转换mp-862991.cif
正在转换mp-862992.cif
正在转换mp-862993.cif
正在转换mp-863062.cif
正在转换mp-863076.cif
正在转换mp-863374.cif
正在转换mp-863403.cif
正在转换mp-863404.cif
正在转换mp-863648.cif
正在转换mp-863651.cif
正在转换mp-863652.cif
正在转换mp-863654.cif
正在转换mp-863655.cif
正在转换mp-863656.cif
正在转换mp-863657.cif
正在转换mp-863660.cif
正在转换mp-863664.cif
正在转换mp-863666.cif
正在转换mp-863667.cif
正在转换mp-863668.cif
正在转换mp-863669.cif
正在转换mp-863670.cif
正在转换mp-863671.cif
正在转换mp-863672.cif
正在转换mp-863673.cif
正在转换mp-863674.cif
正在转换mp-863675.cif
正在转换mp-863677.cif
正在转换mp-863678.cif
正在转换mp-863679.cif
正在转换mp-863681.cif
正在转换mp-863685.cif
正在转换mp-863686.cif
正在转换mp-863690.cif
正在转换mp-863696.cif
正在转换mp-863697.cif
正在转换mp-863698.cif
正在转换mp-863701.cif
正在转换mp-863702.cif
正在转换mp-863703.cif
正在转换mp-863704.cif
正在转换mp-863705.cif
正在转换mp-863707.cif
正在转换mp-863708.cif
正在转换mp-863709.cif
正在转换mp-863710.cif
正在转换mp-863711.cif
正在转换mp-863715.cif
正在转换mp-863716.cif
正在转换mp-863718.cif
正在转换mp-863720.cif
正在转换mp-863721.cif
正在转换mp-863722.cif
正在转换mp-863723.cif
正在转换mp-863724.cif
正在转换mp-863725.cif
正在转换mp-863726.cif
正在转换mp-863727.cif
正在转换mp-863729.cif
正在转换mp-863730.cif
正在转换mp-863732.cif
正在转换mp-863733.cif
正在转换mp-863734.cif
正在转换mp-863735.cif
正在转换mp-863736.cif
正在转换mp-863737.cif
正在转换mp-863738.cif
正在转换mp-863739.cif
正在转换mp-863740.cif
正在转换mp-863741.cif
正在转换mp-863743.cif
正在转换mp-863744.cif
正在转换mp-863851.cif
正在转换mp-863856.cif
正在转换mp-863942.cif
正在转换mp-863961.cif
正在转换mp-864241.cif
正在转换mp-864597.cif
正在转换mp-864598.cif
正在转换mp-864599.cif
正在转换mp-864600.cif
正在转换mp-864601.cif
正在转换mp-864602.cif
正在转换mp-864603.cif
正在转换mp-864606.cif
正在转换mp-864607.cif
正在转换mp-864608.cif
正在转换mp-864610.cif
正在转换mp-864611.cif
正在转换mp-864612.cif
正在转换mp-864613.cif
正在转换mp-864615.cif
正在转换mp-864618.cif
正在转换mp-864620.cif
正在转换mp-864622.cif
正在转换mp-864623.cif
正在转换mp-864624.cif
正在转换mp-864625.cif
正在转换mp-864626.cif
正在转换mp-864628.cif
正在转换mp-864629.cif
正在转换mp-864630.cif
正在转换mp-864631.cif
正在转换mp-864633.cif
正在转换mp-864635.cif
正在转换mp-864637.cif
正在转换mp-864638.cif
正在转换mp-864639.cif
正在转换mp-864640.cif
正在转换mp-864641.cif
正在转换mp-864642.cif
正在转换mp-864644.cif
正在转换mp-864645.cif
正在转换mp-864646.cif
正在转换mp-864647.cif
正在转换mp-864650.cif
正在转换mp-864651.cif
正在转换mp-864653.cif
正在转换mp-864654.cif
正在转换mp-864655.cif
正在转换mp-864659.cif
正在转换mp-864660.cif
正在转换mp-864661.cif
正在转换mp-864667.cif
正在转换mp-864669.cif
正在转换mp-864670.cif
正在转换mp-864671.cif
正在转换mp-864675.cif
正在转换mp-864676.cif
正在转换mp-864715.cif
正在转换mp-864743.cif
正在转换mp-864744.cif
正在转换mp-864753.cif
正在转换mp-864755.cif
正在转换mp-864759.cif
正在转换mp-864760.cif
正在转换mp-864761.cif
正在转换mp-864762.cif
正在转换mp-864763.cif
正在转换mp-864768.cif
正在转换mp-864769.cif
正在转换mp-864771.cif
正在转换mp-864782.cif
正在转换mp-864787.cif
正在转换mp-864789.cif
正在转换mp-864791.cif
正在转换mp-864793.cif
正在转换mp-864798.cif
正在转换mp-864799.cif
正在转换mp-864800.cif
正在转换mp-864801.cif
正在转换mp-864803.cif
正在转换mp-864804.cif
正在转换mp-864805.cif
正在转换mp-864806.cif
正在转换mp-864807.cif
正在转换mp-864835.cif
正在转换mp-864839.cif
正在转换mp-864844.cif
正在转换mp-864876.cif
正在转换mp-864877.cif
正在转换mp-864878.cif
正在转换mp-864882.cif
正在转换mp-864883.cif
正在转换mp-864884.cif
正在转换mp-864886.cif
正在转换mp-864889.cif
正在转换mp-864893.cif
正在转换mp-864895.cif
正在转换mp-864896.cif
正在转换mp-864897.cif
正在转换mp-864898.cif
正在转换mp-864903.cif
正在转换mp-864906.cif
正在转换mp-864907.cif
正在转换mp-864908.cif
正在转换mp-864909.cif
正在转换mp-864910.cif
正在转换mp-864913.cif
正在转换mp-864920.cif
正在转换mp-864921.cif
正在转换mp-864924.cif
正在转换mp-864925.cif
正在转换mp-864926.cif
正在转换mp-864930.cif
正在转换mp-864933.cif
正在转换mp-864936.cif
正在转换mp-864937.cif
正在转换mp-864940.cif
正在转换mp-864942.cif
正在转换mp-864943.cif
正在转换mp-864944.cif
正在转换mp-864945.cif
正在转换mp-864946.cif
正在转换mp-864947.cif
正在转换mp-864948.cif
正在转换mp-864949.cif
正在转换mp-864950.cif
正在转换mp-864951.cif
正在转换mp-864953.cif
正在转换mp-864957.cif
正在转换mp-864959.cif
正在转换mp-864961.cif
正在转换mp-864962.cif
正在转换mp-864965.cif
正在转换mp-864966.cif
正在转换mp-864968.cif
正在转换mp-864970.cif
正在转换mp-864971.cif
正在转换mp-864972.cif
正在转换mp-864973.cif
正在转换mp-864974.cif
正在转换mp-864975.cif
正在转换mp-864976.cif
正在转换mp-864977.cif
正在转换mp-864978.cif
正在转换mp-864981.cif
正在转换mp-864983.cif
正在转换mp-864984.cif
正在转换mp-864985.cif
正在转换mp-864987.cif
正在转换mp-864988.cif
正在转换mp-864989.cif
正在转换mp-864990.cif
正在转换mp-864991.cif
正在转换mp-864993.cif
正在转换mp-864994.cif
正在转换mp-864995.cif
正在转换mp-864996.cif
正在转换mp-864997.cif
正在转换mp-864998.cif
正在转换mp-864999.cif
正在转换mp-865000.cif
正在转换mp-865001.cif
正在转换mp-865002.cif
正在转换mp-865003.cif
正在转换mp-865004.cif
正在转换mp-865006.cif
正在转换mp-865007.cif
正在转换mp-865008.cif
正在转换mp-865010.cif
正在转换mp-865011.cif
正在转换mp-865014.cif
正在转换mp-865015.cif
正在转换mp-865017.cif
正在转换mp-865019.cif
正在转换mp-865020.cif
正在转换mp-865021.cif
正在转换mp-865022.cif
正在转换mp-865023.cif
正在转换mp-865025.cif
正在转换mp-865026.cif
正在转换mp-865027.cif
正在转换mp-865028.cif
正在转换mp-865029.cif
正在转换mp-865030.cif
正在转换mp-865031.cif
正在转换mp-865032.cif
正在转换mp-865037.cif
正在转换mp-865038.cif
正在转换mp-865039.cif
正在转换mp-865041.cif
正在转换mp-865043.cif
正在转换mp-865044.cif
正在转换mp-865046.cif
正在转换mp-865047.cif
正在转换mp-865048.cif
正在转换mp-865049.cif
正在转换mp-865050.cif
正在转换mp-865051.cif
正在转换mp-865066.cif
正在转换mp-865076.cif
正在转换mp-865077.cif
正在转换mp-865079.cif
正在转换mp-865080.cif
正在转换mp-865081.cif
正在转换mp-865082.cif
正在转换mp-865088.cif
正在转换mp-865090.cif
正在转换mp-865091.cif
正在转换mp-865092.cif
正在转换mp-865093.cif
正在转换mp-865094.cif
正在转换mp-865095.cif
正在转换mp-865096.cif
正在转换mp-865097.cif

正在转换mp-865100.cif
正在转换mp-865103.cif
正在转换mp-865107.cif
正在转换mp-865108.cif
正在转换mp-865109.cif
正在转换mp-865110.cif
正在转换mp-865111.cif
正在转换mp-865112.cif
正在转换mp-865113.cif
正在转换mp-865114.cif
正在转换mp-865115.cif
正在转换mp-865116.cif
正在转换mp-865117.cif
正在转换mp-865118.cif
正在转换mp-865119.cif
正在转换mp-865120.cif
正在转换mp-865121.cif
正在转换mp-865122.cif
正在转换mp-865123.cif
正在转换mp-865124.cif
正在转换mp-865125.cif
正在转换mp-865126.cif
正在转换mp-865127.cif
正在转换mp-865128.cif
正在转换mp-865129.cif
正在转换mp-865130.cif
正在转换mp-865131.cif
正在转换mp-865132.cif
正在转换mp-865135.cif
正在转换mp-865140.cif
正在转换mp-865142.cif
正在转换mp-865143.cif
正在转换mp-865144.cif
正在转换mp-865145.cif
正在转换mp-865146.cif
正在转换mp-865147.cif
正在转换mp-865148.cif
正在转换mp-865149.cif
正在转换mp-865150.cif
正在转换mp-865151.cif
正在转换mp-865152.cif
正在转换mp-865155.cif
正在转换mp-865156.cif
正在转换mp-865157.cif
正在转换mp-865158.cif
正在转换mp-865159.cif
正在转换mp-865160.cif
正在转换mp-865161.cif
正在转换mp-865162.cif
正在转换mp-865163.cif
正在转换mp-865164.cif
正在转换mp-865165.cif
正在转换mp-865166.cif
正在转换mp-865167.cif
正在转换mp-865169.cif
正在转换mp-865170.cif
正在转换mp-865172.cif
正在转换mp-865173.cif
正在转换mp-865174.cif
正在转换mp-865176.cif
正在转换mp-865179.cif
正在转换mp-865180.cif
正在转换mp-865183.cif
正在转换mp-865184.cif
正在转换mp-865185.cif
正在转换mp-865186.cif
正在转换mp-865187.cif
正在转换mp-865188.cif
正在转换mp-865190.cif
正在转换mp-865191.cif
正在转换mp-865193.cif
正在转换mp-865194.cif
正在转换mp-865195.cif
正在转换mp-865202.cif
正在转换mp-865206.cif
正在转换mp-865209.cif
正在转换mp-865210.cif
正在转换mp-865211.cif
正在转换mp-865212.cif
正在转换mp-865214.cif
正在转换mp-865215.cif
正在转换mp-865216.cif
正在转换mp-865217.cif
正在转换mp-865218.cif
正在转换mp-865219.cif
正在转换mp-865220.cif
正在转换mp-865221.cif
正在转换mp-865222.cif
正在转换mp-865223.cif
正在转换mp-865224.cif
正在转换mp-865225.cif
正在转换mp-865226.cif
正在转换mp-865227.cif
正在转换mp-865228.cif
正在转换mp-865229.cif
正在转换mp-865230.cif
正在转换mp-865231.cif
正在转换mp-865232.cif
正在转换mp-865233.cif
正在转换mp-865234.cif
正在转换mp-865236.cif
正在转换mp-865237.cif
正在转换mp-865238.cif
正在转换mp-865239.cif
正在转换mp-865240.cif
正在转换mp-865241.cif
正在转换mp-865247.cif
正在转换mp-865248.cif
正在转换mp-865249.cif
正在转换mp-865250.cif
正在转换mp-865251.cif
正在转换mp-865252.cif
正在转换mp-865253.cif
正在转换mp-865254.cif
正在转换mp-865255.cif
正在转换mp-865256.cif
正在转换mp-865257.cif
正在转换mp-865258.cif
正在转换mp-865259.cif
正在转换mp-865260.cif
正在转换mp-865261.cif
正在转换mp-865262.cif
正在转换mp-865269.cif
正在转换mp-865270.cif
正在转换mp-865273.cif
正在转换mp-865275.cif
正在转换mp-865277.cif
正在转换mp-865278.cif
正在转换mp-865279.cif
正在转换mp-865280.cif
正在转换mp-865281.cif
正在转换mp-865282.cif
正在转换mp-865283.cif
正在转换mp-865284.cif
正在转换mp-865288.cif
正在转换mp-865297.cif
正在转换mp-865298.cif
正在转换mp-865299.cif
正在转换mp-865300.cif
正在转换mp-865302.cif
正在转换mp-865303.cif
正在转换mp-865304.cif
正在转换mp-865305.cif
正在转换mp-865306.cif
正在转换mp-865307.cif
正在转换mp-865308.cif
正在转换mp-865309.cif
正在转换mp-865315.cif
正在转换mp-865317.cif
正在转换mp-865318.cif
正在转换mp-865319.cif
正在转换mp-865320.cif
正在转换mp-865321.cif
正在转换mp-865322.cif
正在转换mp-865323.cif
正在转换mp-865325.cif
正在转换mp-865326.cif
正在转换mp-865327.cif
正在转换mp-865329.cif
正在转换mp-865334.cif
正在转换mp-865335.cif
正在转换mp-865336.cif
正在转换mp-865337.cif
正在转换mp-865338.cif
正在转换mp-865339.cif
正在转换mp-865340.cif
正在转换mp-865341.cif
正在转换mp-865342.cif
正在转换mp-865343.cif
正在转换mp-865351.cif
正在转换mp-865354.cif
正在转换mp-865355.cif
正在转换mp-865356.cif
正在转换mp-865358.cif
正在转换mp-865359.cif
正在转换mp-865360.cif
正在转换mp-865361.cif
正在转换mp-865362.cif
正在转换mp-865363.cif
正在转换mp-865364.cif
正在转换mp-865365.cif
正在转换mp-865366.cif
正在转换mp-865367.cif
正在转换mp-865368.cif
正在转换mp-865369.cif
正在转换mp-865373.cif
正在转换mp-865374.cif
正在转换mp-865375.cif
正在转换mp-865376.cif
正在转换mp-865378.cif
正在转换mp-865379.cif
正在转换mp-865380.cif
正在转换mp-865381.cif
正在转换mp-865382.cif
正在转换mp-865383.cif
正在转换mp-865384.cif
正在转换mp-865398.cif
正在转换mp-865401.cif
正在转换mp-865402.cif
正在转换mp-865403.cif
正在转换mp-865406.cif
正在转换mp-865410.cif
正在转换mp-865413.cif
正在转换mp-865414.cif
正在转换mp-865415.cif
正在转换mp-865416.cif
正在转换mp-865419.cif
正在转换mp-865422.cif
正在转换mp-865425.cif
正在转换mp-865426.cif
正在转换mp-865427.cif
正在转换mp-865429.cif
正在转换mp-865430.cif
正在转换mp-865431.cif
正在转换mp-865432.cif
正在转换mp-865433.cif
正在转换mp-865439.cif
正在转换mp-865440.cif
正在转换mp-865441.cif
正在转换mp-865442.cif
正在转换mp-865443.cif
正在转换mp-865444.cif
正在转换mp-865445.cif
正在转换mp-865446.cif
正在转换mp-865447.cif
正在转换mp-865448.cif
正在转换mp-865449.cif
正在转换mp-865451.cif
正在转换mp-865459.cif
正在转换mp-865460.cif
正在转换mp-865462.cif
正在转换mp-865463.cif
正在转换mp-865464.cif
正在转换mp-865465.cif
正在转换mp-865467.cif
正在转换mp-865468.cif
正在转换mp-865469.cif
正在转换mp-865470.cif
正在转换mp-865471.cif
正在转换mp-865472.cif
正在转换mp-865482.cif
正在转换mp-865485.cif
正在转换mp-865486.cif
正在转换mp-865487.cif
正在转换mp-865497.cif
正在转换mp-865501.cif
正在转换mp-865502.cif
正在转换mp-865504.cif
正在转换mp-865507.cif
正在转换mp-865512.cif
正在转换mp-865515.cif
正在转换mp-865518.cif
正在转换mp-865520.cif
正在转换mp-865523.cif
正在转换mp-865524.cif
正在转换mp-865526.cif
正在转换mp-865531.cif
正在转换mp-865532.cif
正在转换mp-865535.cif
正在转换mp-865538.cif
正在转换mp-865546.cif
正在转换mp-865548.cif
正在转换mp-865560.cif
正在转换mp-865569.cif
正在转换mp-865578.cif
正在转换mp-865592.cif
正在转换mp-865599.cif
正在转换mp-865600.cif
正在转换mp-865601.cif
正在转换mp-865602.cif
正在转换mp-865603.cif
正在转换mp-865604.cif
正在转换mp-865605.cif
正在转换mp-865607.cif
正在转换mp-865608.cif
正在转换mp-865609.cif
正在转换mp-865615.cif
正在转换mp-865616.cif
正在转换mp-865622.cif
正在转换mp-865623.cif
正在转换mp-865624.cif
正在转换mp-865625.cif
正在转换mp-865629.cif
正在转换mp-865630.cif
正在转换mp-865640.cif
正在转换mp-865648.cif
正在转换mp-865649.cif
正在转换mp-865652.cif
正在转换mp-865653.cif
正在转换mp-865654.cif
正在转换mp-865655.cif
正在转换mp-865660.cif
正在转换mp-865664.cif
正在转换mp-865665.cif
正在转换mp-865666.cif
正在转换mp-865669.cif
正在转换mp-865671.cif
正在转换mp-865677.cif
正在转换mp-865678.cif
正在转换mp-865679.cif
正在转换mp-865680.cif
正在转换mp-865681.cif
正在转换mp-865708.cif
正在转换mp-865709.cif
正在转换mp-865712.cif
正在转换mp-865713.cif
正在转换mp-865714.cif
正在转换mp-865715.cif
正在转换mp-865716.cif
正在转换mp-865717.cif
正在转换mp-865733.cif
正在转换mp-865734.cif
正在转换mp-865736.cif
正在转换mp-865737.cif
正在转换mp-865738.cif
正在转换mp-865739.cif
正在转换mp-865740.cif
正在转换mp-865742.cif
正在转换mp-865743.cif
正在转换mp-865744.cif
正在转换mp-865746.cif
正在转换mp-865747.cif
正在转换mp-865748.cif
正在转换mp-865752.cif
正在转换mp-865753.cif
正在转换mp-865755.cif
正在转换mp-865756.cif
正在转换mp-865757.cif
正在转换mp-865758.cif
正在转换mp-865759.cif
正在转换mp-865761.cif
正在转换mp-865766.cif
正在转换mp-865768.cif
正在转换mp-865781.cif
正在转换mp-865782.cif
正在转换mp-865785.cif
正在转换mp-865786.cif
正在转换mp-865791.cif
正在转换mp-865792.cif
正在转换mp-865795.cif
正在转换mp-865796.cif
正在转换mp-865797.cif
正在转换mp-865799.cif
正在转换mp-865800.cif
正在转换mp-865801.cif
正在转换mp-865805.cif
正在转换mp-865810.cif
正在转换mp-865814.cif
正在转换mp-865815.cif
正在转换mp-865816.cif
正在转换mp-865828.cif
正在转换mp-865829.cif
正在转换mp-865830.cif
正在转换mp-865834.cif
正在转换mp-865836.cif
正在转换mp-865838.cif
正在转换mp-865840.cif
正在转换mp-865841.cif
正在转换mp-865843.cif
正在转换mp-865845.cif
正在转换mp-865846.cif
正在转换mp-865847.cif
正在转换mp-865848.cif
正在转换mp-865849.cif
正在转换mp-865854.cif
正在转换mp-865855.cif
正在转换mp-865857.cif
正在转换mp-865865.cif
正在转换mp-865866.cif
正在转换mp-865867.cif
正在转换mp-865868.cif
正在转换mp-865869.cif
正在转换mp-865870.cif
正在转换mp-865871.cif
正在转换mp-865872.cif
正在转换mp-865874.cif
正在转换mp-865875.cif
正在转换mp-865876.cif
正在转换mp-865877.cif
正在转换mp-865882.cif
正在转换mp-865884.cif
正在转换mp-865887.cif
正在转换mp-865888.cif
正在转换mp-865889.cif
正在转换mp-865892.cif
正在转换mp-865893.cif
正在转换mp-865894.cif
正在转换mp-865895.cif
正在转换mp-865896.cif
正在转换mp-865897.cif
正在转换mp-865898.cif
正在转换mp-865899.cif
正在转换mp-865900.cif
正在转换mp-865901.cif
正在转换mp-865902.cif
正在转换mp-865903.cif
正在转换mp-865904.cif
正在转换mp-865905.cif
正在转换mp-865906.cif
正在转换mp-865907.cif
正在转换mp-865908.cif
正在转换mp-865909.cif
正在转换mp-865911.cif
正在转换mp-865912.cif
正在转换mp-865913.cif
正在转换mp-865914.cif
正在转换mp-865915.cif
正在转换mp-865916.cif
正在转换mp-865917.cif
正在转换mp-865918.cif
正在转换mp-865919.cif
正在转换mp-865920.cif
正在转换mp-865921.cif
正在转换mp-865922.cif
正在转换mp-865924.cif
正在转换mp-865925.cif
正在转换mp-865926.cif
正在转换mp-865927.cif
正在转换mp-865928.cif
正在转换mp-865929.cif
正在转换mp-865930.cif
正在转换mp-865932.cif
正在转换mp-865933.cif
正在转换mp-865934.cif
正在转换mp-865935.cif
正在转换mp-865936.cif
正在转换mp-865940.cif
正在转换mp-865944.cif
正在转换mp-865947.cif
正在转换mp-865949.cif
正在转换mp-865952.cif
正在转换mp-865954.cif
正在转换mp-865955.cif
正在转换mp-865958.cif
正在转换mp-865959.cif
正在转换mp-865963.cif
正在转换mp-865964.cif
正在转换mp-865965.cif
正在转换mp-865966.cif
正在转换mp-865969.cif
正在转换mp-865971.cif
正在转换mp-865973.cif
正在转换mp-865974.cif
正在转换mp-865977.cif
正在转换mp-865978.cif
正在转换mp-865979.cif
正在转换mp-865981.cif
正在转换mp-865982.cif
正在转换mp-865983.cif
正在转换mp-865984.cif
正在转换mp-865985.cif
正在转换mp-865986.cif
正在转换mp-865987.cif
正在转换mp-865988.cif
正在转换mp-865989.cif
正在转换mp-865990.cif

正在转换mp-865991.cif
正在转换mp-865992.cif
正在转换mp-865993.cif
正在转换mp-865994.cif
正在转换mp-865995.cif
正在转换mp-865996.cif
正在转换mp-865997.cif
正在转换mp-865998.cif
正在转换mp-865999.cif
正在转换mp-866000.cif
正在转换mp-866001.cif
正在转换mp-866002.cif
正在转换mp-866004.cif
正在转换mp-866005.cif
正在转换mp-866006.cif
正在转换mp-866007.cif
正在转换mp-866008.cif
正在转换mp-866009.cif
正在转换mp-866010.cif
正在转换mp-866011.cif
正在转换mp-866012.cif
正在转换mp-866013.cif
正在转换mp-866014.cif
正在转换mp-866015.cif
正在转换mp-866016.cif
正在转换mp-866017.cif
正在转换mp-866018.cif
正在转换mp-866019.cif
正在转换mp-866020.cif
正在转换mp-866022.cif
正在转换mp-866024.cif
正在转换mp-866026.cif
正在转换mp-866027.cif
正在转换mp-866031.cif
正在转换mp-866033.cif
正在转换mp-866046.cif
正在转换mp-866056.cif
正在转换mp-866060.cif
正在转换mp-866061.cif
正在转换mp-866063.cif
正在转换mp-866064.cif
正在转换mp-866065.cif
正在转换mp-866067.cif
正在转换mp-866068.cif
正在转换mp-866069.cif
正在转换mp-866071.cif
正在转换mp-866072.cif
正在转换mp-866073.cif
正在转换mp-866074.cif
正在转换mp-866075.cif
正在转换mp-866077.cif
正在转换mp-866079.cif
正在转换mp-866080.cif
正在转换mp-866081.cif
正在转换mp-866082.cif
正在转换mp-866083.cif
正在转换mp-866085.cif
正在转换mp-866086.cif
正在转换mp-866087.cif
正在转换mp-866088.cif
正在转换mp-866094.cif
正在转换mp-866096.cif
正在转换mp-866100.cif
正在转换mp-866103.cif
正在转换mp-866104.cif
正在转换mp-866105.cif
正在转换mp-866106.cif
正在转换mp-866107.cif
正在转换mp-866108.cif
正在转换mp-866109.cif
正在转换mp-866110.cif
正在转换mp-866111.cif
正在转换mp-866112.cif
正在转换mp-866114.cif
正在转换mp-866115.cif
正在转换mp-866116.cif
正在转换mp-866117.cif
正在转换mp-866119.cif
正在转换mp-866120.cif
正在转换mp-866121.cif
正在转换mp-866122.cif
正在转换mp-866124.cif
正在转换mp-866125.cif
正在转换mp-866126.cif
正在转换mp-866127.cif
正在转换mp-866128.cif
正在转换mp-866131.cif
正在转换mp-866133.cif
正在转换mp-866134.cif
正在转换mp-866137.cif
正在转换mp-866138.cif
正在转换mp-866139.cif
正在转换mp-866140.cif
正在转换mp-866142.cif
正在转换mp-866143.cif
正在转换mp-866145.cif
正在转换mp-866146.cif
正在转换mp-866147.cif
正在转换mp-866150.cif
正在转换mp-866152.cif
正在转换mp-866153.cif
正在转换mp-866154.cif
正在转换mp-866155.cif
正在转换mp-866156.cif
正在转换mp-866157.cif
正在转换mp-866158.cif
正在转换mp-866159.cif
正在转换mp-866160.cif
正在转换mp-866161.cif
正在转换mp-866162.cif
正在转换mp-866163.cif
正在转换mp-866164.cif
正在转换mp-866165.cif
正在转换mp-866166.cif
正在转换mp-866168.cif
正在转换mp-866169.cif
正在转换mp-866171.cif
正在转换mp-866172.cif
正在转换mp-866173.cif
正在转换mp-866174.cif
正在转换mp-866175.cif
正在转换mp-866176.cif
正在转换mp-866177.cif
正在转换mp-866178.cif
正在转换mp-866179.cif
正在转换mp-866180.cif
正在转换mp-866181.cif
正在转换mp-866183.cif
正在转换mp-866184.cif
正在转换mp-866185.cif
正在转换mp-866186.cif
正在转换mp-866187.cif
正在转换mp-866188.cif
正在转换mp-866191.cif
正在转换mp-866192.cif
正在转换mp-866194.cif
正在转换mp-866199.cif
正在转换mp-866200.cif
正在转换mp-866201.cif
正在转换mp-866203.cif
正在转换mp-866204.cif
正在转换mp-866205.cif
正在转换mp-866206.cif
正在转换mp-866207.cif
正在转换mp-866209.cif
正在转换mp-866211.cif
正在转换mp-866212.cif
正在转换mp-866213.cif
正在转换mp-866216.cif
正在转换mp-866218.cif
正在转换mp-866219.cif
正在转换mp-866221.cif
正在转换mp-866223.cif
正在转换mp-866224.cif
正在转换mp-866225.cif
正在转换mp-866226.cif
正在转换mp-866227.cif
正在转换mp-866228.cif
正在转换mp-866229.cif
正在转换mp-866279.cif
正在转换mp-866280.cif
正在转换mp-866281.cif
正在转换mp-866282.cif
正在转换mp-866283.cif
正在转换mp-866284.cif
正在转换mp-866285.cif
正在转换mp-866287.cif
正在转换mp-866288.cif
正在转换mp-866289.cif
正在转换mp-866290.cif
正在转换mp-866291.cif
正在转换mp-866292.cif
正在转换mp-866295.cif
正在转换mp-866311.cif
正在转换mp-866376.cif
正在转换mp-866471.cif
正在转换mp-866580.cif
正在转换mp-866635.cif
正在转换mp-866637.cif
正在转换mp-866645.cif
正在转换mp-866647.cif
正在转换mp-866810.cif
正在转换mp-866819.cif
正在转换mp-866820.cif
正在转换mp-866824.cif
正在转换mp-866826.cif
正在转换mp-866827.cif
正在转换mp-866829.cif
正在转换mp-866830.cif
正在转换mp-866832.cif
正在转换mp-866833.cif
正在转换mp-866834.cif
正在转换mp-866836.cif
正在转换mp-866844.cif
正在转换mp-866845.cif
正在转换mp-866849.cif
正在转换mp-866850.cif
正在转换mp-866871.cif
正在转换mp-866873.cif
正在转换mp-866883.cif
正在转换mp-866894.cif
正在转换mp-866917.cif
正在转换mp-866922.cif
正在转换mp-866936.cif
正在转换mp-866941.cif
正在转换mp-866943.cif
正在转换mp-866951.cif
正在转换mp-866972.cif
正在转换mp-867077.cif
正在转换mp-867107.cif
正在转换mp-867108.cif
正在转换mp-867109.cif
正在转换mp-867110.cif
正在转换mp-867111.cif
正在转换mp-867112.cif
正在转换mp-867113.cif
正在转换mp-867114.cif
正在转换mp-867115.cif
正在转换mp-867116.cif
正在转换mp-867117.cif
正在转换mp-867119.cif
正在转换mp-867120.cif
正在转换mp-867121.cif
正在转换mp-867122.cif
正在转换mp-867123.cif
正在转换mp-867124.cif
正在转换mp-867125.cif
正在转换mp-867127.cif
正在转换mp-867128.cif
正在转换mp-867129.cif
正在转换mp-867131.cif
正在转换mp-867133.cif
正在转换mp-867134.cif
正在转换mp-867135.cif
正在转换mp-867136.cif
正在转换mp-867137.cif
正在转换mp-867139.cif
正在转换mp-867140.cif
正在转换mp-867142.cif
正在转换mp-867144.cif
正在转换mp-867145.cif
正在转换mp-867146.cif
正在转换mp-867147.cif
正在转换mp-867148.cif
正在转换mp-867149.cif
正在转换mp-867156.cif
正在转换mp-867157.cif
正在转换mp-867158.cif
正在转换mp-867159.cif
正在转换mp-867160.cif
正在转换mp-867161.cif
正在转换mp-867162.cif
正在转换mp-867163.cif
正在转换mp-867164.cif
正在转换mp-867165.cif
正在转换mp-867167.cif
正在转换mp-867169.cif
正在转换mp-867170.cif
正在转换mp-867171.cif
正在转换mp-867172.cif
正在转换mp-867173.cif
正在转换mp-867174.cif
正在转换mp-867176.cif
正在转换mp-867177.cif
正在转换mp-867178.cif
正在转换mp-867179.cif
正在转换mp-867180.cif
正在转换mp-867181.cif
正在转换mp-867182.cif
正在转换mp-867185.cif
正在转换mp-867186.cif
正在转换mp-867187.cif
正在转换mp-867189.cif
正在转换mp-867191.cif
正在转换mp-867193.cif
正在转换mp-867195.cif
正在转换mp-867196.cif
正在转换mp-867197.cif
正在转换mp-867198.cif
正在转换mp-867199.cif
正在转换mp-867201.cif
正在转换mp-867203.cif
正在转换mp-867204.cif
正在转换mp-867205.cif
正在转换mp-867206.cif
正在转换mp-867207.cif
正在转换mp-867208.cif
正在转换mp-867210.cif
正在转换mp-867211.cif
正在转换mp-867216.cif
正在转换mp-867217.cif
正在转换mp-867218.cif
正在转换mp-867220.cif
正在转换mp-867222.cif
正在转换mp-867223.cif
正在转换mp-867224.cif
正在转换mp-867225.cif
正在转换mp-867233.cif
正在转换mp-867234.cif
正在转换mp-867235.cif
正在转换mp-867236.cif
正在转换mp-867242.cif
正在转换mp-867243.cif
正在转换mp-867249.cif
正在转换mp-867251.cif
正在转换mp-867252.cif
正在转换mp-867253.cif
正在转换mp-867258.cif
正在转换mp-867260.cif
正在转换mp-867261.cif
正在转换mp-867263.cif
正在转换mp-867265.cif
正在转换mp-867266.cif
正在转换mp-867267.cif
正在转换mp-867268.cif
正在转换mp-867269.cif
正在转换mp-867270.cif
正在转换mp-867271.cif
正在转换mp-867274.cif
正在转换mp-867275.cif
正在转换mp-867276.cif
正在转换mp-867277.cif
正在转换mp-867278.cif
正在转换mp-867280.cif
正在转换mp-867281.cif
正在转换mp-867282.cif
正在转换mp-867283.cif
正在转换mp-867284.cif
正在转换mp-867286.cif
正在转换mp-867287.cif
正在转换mp-867288.cif
正在转换mp-867289.cif
正在转换mp-867290.cif
正在转换mp-867291.cif
正在转换mp-867292.cif
正在转换mp-867293.cif
正在转换mp-867295.cif
正在转换mp-867300.cif
正在转换mp-867306.cif
正在转换mp-867307.cif
正在转换mp-867311.cif
正在转换mp-867319.cif
正在转换mp-867321.cif
正在转换mp-867322.cif
正在转换mp-867323.cif
正在转换mp-867326.cif
正在转换mp-867327.cif
正在转换mp-867328.cif
正在转换mp-867330.cif
正在转换mp-867333.cif
正在转换mp-867334.cif
正在转换mp-867335.cif
正在转换mp-867336.cif
正在转换mp-867338.cif
正在转换mp-867340.cif
正在转换mp-867342.cif
正在转换mp-867343.cif
正在转换mp-867344.cif
正在转换mp-867345.cif
正在转换mp-867346.cif
正在转换mp-867347.cif
正在转换mp-867349.cif
正在转换mp-867350.cif
正在转换mp-867352.cif
正在转换mp-867353.cif
正在转换mp-867356.cif
正在转换mp-867357.cif
正在转换mp-867364.cif
正在转换mp-867372.cif
正在转换mp-867373.cif
正在转换mp-867418.cif
正在转换mp-867422.cif
正在转换mp-867475.cif
正在转换mp-867507.cif
正在转换mp-867544.cif
正在转换mp-867674.cif
正在转换mp-867676.cif
正在转换mp-867681.cif
正在转换mp-867689.cif
正在转换mp-867699.cif
正在转换mp-867700.cif
正在转换mp-867701.cif
正在转换mp-867708.cif
正在转换mp-867712.cif
正在转换mp-867714.cif
正在转换mp-867722.cif
正在转换mp-867725.cif
正在转换mp-867731.cif
正在转换mp-867735.cif
正在转换mp-867739.cif
正在转换mp-867744.cif
正在转换mp-867745.cif
正在转换mp-867748.cif
正在转换mp-867749.cif
正在转换mp-867750.cif
正在转换mp-867751.cif
正在转换mp-867753.cif
正在转换mp-867754.cif
正在转换mp-867756.cif
正在转换mp-867757.cif
正在转换mp-867761.cif
正在转换mp-867762.cif
正在转换mp-867767.cif
正在转换mp-867768.cif
正在转换mp-867769.cif
正在转换mp-867770.cif
正在转换mp-867771.cif
正在转换mp-867773.cif
正在转换mp-867774.cif
正在转换mp-867775.cif
正在转换mp-867776.cif
正在转换mp-867779.cif
正在转换mp-867780.cif
正在转换mp-867781.cif
正在转换mp-867786.cif
正在转换mp-867787.cif
正在转换mp-867788.cif
正在转换mp-867795.cif
正在转换mp-867797.cif
正在转换mp-867798.cif
正在转换mp-867799.cif
正在转换mp-867800.cif
正在转换mp-867801.cif
正在转换mp-867802.cif
正在转换mp-867803.cif
正在转换mp-867805.cif
正在转换mp-867806.cif
正在转换mp-867807.cif
正在转换mp-867810.cif
正在转换mp-867811.cif
正在转换mp-867812.cif
正在转换mp-867813.cif
正在转换mp-867816.cif
正在转换mp-867820.cif
正在转换mp-867821.cif
正在转换mp-867822.cif
正在转换mp-867823.cif
正在转换mp-867826.cif
正在转换mp-867827.cif
正在转换mp-867828.cif
正在转换mp-867829.cif
正在转换mp-867830.cif
正在转换mp-867831.cif
正在转换mp-867833.cif
正在转换mp-867834.cif
正在转换mp-867835.cif
正在转换mp-867837.cif
正在转换mp-867838.cif
正在转换mp-867840.cif
正在转换mp-867842.cif
正在转换mp-867843.cif
正在转换mp-867848.cif
正在转换mp-867849.cif
正在转换mp-867850.cif
正在转换mp-867852.cif
正在转换mp-867853.cif
正在转换mp-867854.cif
正在转换mp-867857.cif
正在转换mp-867860.cif
正在转换mp-867861.cif
正在转换mp-867862.cif
正在转换mp-867863.cif
正在转换mp-867865.cif
正在转换mp-867867.cif
正在转换mp-867868.cif

正在转换mp-867869.cif
正在转换mp-867870.cif
正在转换mp-867871.cif
正在转换mp-867872.cif
正在转换mp-867873.cif
正在转换mp-867876.cif
正在转换mp-867877.cif
正在转换mp-867878.cif
正在转换mp-867881.cif
正在转换mp-867882.cif
正在转换mp-867883.cif
正在转换mp-867884.cif
正在转换mp-867887.cif
正在转换mp-867888.cif
正在转换mp-867890.cif
正在转换mp-867894.cif
正在转换mp-867895.cif
正在转换mp-867896.cif
正在转换mp-867897.cif
正在转换mp-867898.cif
正在转换mp-867899.cif
正在转换mp-867901.cif
正在转换mp-867902.cif
正在转换mp-867903.cif
正在转换mp-867904.cif
正在转换mp-867905.cif
正在转换mp-867907.cif
正在转换mp-867908.cif
正在转换mp-867909.cif
正在转换mp-867911.cif
正在转换mp-867912.cif
正在转换mp-867913.cif
正在转换mp-867914.cif
正在转换mp-867915.cif
正在转换mp-867917.cif
正在转换mp-867918.cif
正在转换mp-867919.cif
正在转换mp-867920.cif
正在转换mp-867921.cif
正在转换mp-867922.cif
正在转换mp-867923.cif
正在转换mp-867924.cif
正在转换mp-867925.cif
正在转换mp-867926.cif
正在转换mp-867927.cif
正在转换mp-867928.cif
正在转换mp-867929.cif
正在转换mp-867930.cif
正在转换mp-867932.cif
正在转换mp-867933.cif
正在转换mp-867958.cif
正在转换mp-867965.cif
正在转换mp-867978.cif
正在转换mp-867985.cif
正在转换mp-868012.cif
正在转换mp-868013.cif
正在转换mp-868046.cif
正在转换mp-868117.cif
正在转换mp-868128.cif
正在转换mp-868136.cif
正在转换mp-868138.cif
正在转换mp-868139.cif
正在转换mp-868141.cif
正在转换mp-868146.cif
正在转换mp-868147.cif
正在转换mp-868149.cif
正在转换mp-868150.cif
正在转换mp-868152.cif
正在转换mp-868168.cif
正在转换mp-868171.cif
正在转换mp-868191.cif
正在转换mp-868255.cif
正在转换mp-868263.cif
正在转换mp-868281.cif
正在转换mp-868286.cif
正在转换mp-868287.cif
正在转换mp-868323.cif
正在转换mp-868325.cif
正在转换mp-868326.cif
正在转换mp-868328.cif
正在转换mp-868333.cif
正在转换mp-868334.cif
正在转换mp-868341.cif
正在转换mp-868343.cif
正在转换mp-868345.cif
正在转换mp-868348.cif
正在转换mp-868349.cif
正在转换mp-868352.cif
正在转换mp-868354.cif
正在转换mp-868360.cif
正在转换mp-868385.cif
正在转换mp-868417.cif
正在转换mp-868528.cif
正在转换mp-868636.cif
正在转换mp-868640.cif
正在转换mp-868647.cif
正在转换mp-868656.cif
正在转换mp-924128.cif
正在转换mp-961648.cif
正在转换mp-961649.cif
正在转换mp-961651.cif
正在转换mp-961652.cif
正在转换mp-961653.cif
正在转换mp-961654.cif
正在转换mp-961655.cif
正在转换mp-961656.cif
正在转换mp-961657.cif
正在转换mp-961658.cif
正在转换mp-961659.cif
正在转换mp-961660.cif
正在转换mp-961661.cif
正在转换mp-961662.cif
正在转换mp-961663.cif
正在转换mp-961664.cif
正在转换mp-961665.cif
正在转换mp-961666.cif
正在转换mp-961667.cif
正在转换mp-961668.cif
正在转换mp-961669.cif
正在转换mp-961670.cif
正在转换mp-961671.cif
正在转换mp-961672.cif
正在转换mp-961673.cif
正在转换mp-961674.cif
正在转换mp-961675.cif
正在转换mp-961676.cif
正在转换mp-961677.cif
正在转换mp-961678.cif
正在转换mp-961679.cif
正在转换mp-961680.cif
正在转换mp-961681.cif
正在转换mp-961682.cif
正在转换mp-961683.cif
正在转换mp-961686.cif
正在转换mp-961687.cif
正在转换mp-961688.cif
正在转换mp-961689.cif
正在转换mp-961690.cif
正在转换mp-961691.cif
正在转换mp-961692.cif
正在转换mp-961693.cif
正在转换mp-961694.cif
正在转换mp-961696.cif
正在转换mp-961697.cif
正在转换mp-961698.cif
正在转换mp-961699.cif
正在转换mp-961700.cif
正在转换mp-961701.cif
正在转换mp-961702.cif
正在转换mp-961703.cif
正在转换mp-961704.cif
正在转换mp-961705.cif
正在转换mp-961706.cif
正在转换mp-961707.cif
正在转换mp-961708.cif
正在转换mp-961709.cif
正在转换mp-961710.cif
正在转换mp-961711.cif
正在转换mp-961712.cif
正在转换mp-961713.cif
正在转换mp-961716.cif
正在转换mp-961717.cif
正在转换mp-961718.cif
正在转换mp-961719.cif
正在转换mp-961720.cif
正在转换mp-961721.cif
正在转换mp-961722.cif
正在转换mp-961723.cif
正在转换mp-961724.cif
正在转换mp-961725.cif
正在转换mp-961726.cif
正在转换mp-961727.cif
正在转换mp-961731.cif
正在转换mp-961732.cif
正在转换mp-961774.cif
正在转换mp-962057.cif
正在转换mp-962058.cif
正在转换mp-962059.cif
正在转换mp-962060.cif
正在转换mp-962062.cif
正在转换mp-962072.cif
正在转换mp-962073.cif
正在转换mp-962074.cif
正在转换mp-962075.cif
正在转换mp-962076.cif
正在转换mp-962078.cif
正在转换mp-971669.cif
正在转换mp-971678.cif
正在转换mp-971682.cif
正在转换mp-971694.cif
正在转换mp-971702.cif
正在转换mp-971703.cif
正在转换mp-971712.cif
正在转换mp-971720.cif
正在转换mp-971733.cif
正在转换mp-971751.cif
正在转换mp-971767.cif
正在转换mp-971768.cif
正在转换mp-971775.cif
正在转换mp-971779.cif
正在转换mp-971788.cif
正在转换mp-971826.cif
正在转换mp-971834.cif
正在转换mp-971835.cif
正在转换mp-971857.cif
正在转换mp-971859.cif
正在转换mp-971863.cif
正在转换mp-971864.cif
正在转换mp-971921.cif
正在转换mp-971933.cif
正在转换mp-972071.cif
正在转换mp-972082.cif
正在转换mp-972084.cif
正在转换mp-972087.cif
正在转换mp-972088.cif
正在转换mp-972095.cif
正在转换mp-972099.cif
正在转换mp-972103.cif
正在转换mp-972112.cif
正在转换mp-972116.cif
正在转换mp-972117.cif
正在转换mp-972120.cif
正在转换mp-972130.cif
正在转换mp-972156.cif
正在转换mp-972160.cif
正在转换mp-972205.cif
正在转换mp-972209.cif
正在转换mp-972220.cif
正在转换mp-972222.cif
正在转换mp-972224.cif
正在转换mp-972323.cif
正在转换mp-972326.cif
正在转换mp-972327.cif
正在转换mp-972395.cif
正在转换mp-972400.cif
正在转换mp-972424.cif
正在转换mp-972439.cif
正在转换mp-972442.cif
正在转换mp-972448.cif
正在转换mp-972455.cif
正在转换mp-972456.cif
正在转换mp-972461.cif
正在转换mp-972463.cif
正在转换mp-972467.cif
正在转换mp-972471.cif
正在转换mp-972478.cif
正在转换mp-972479.cif
正在转换mp-972486.cif
正在转换mp-972493.cif
正在转换mp-972495.cif
正在转换mp-972502.cif
正在转换mp-972504.cif
正在转换mp-972507.cif
正在转换mp-972510.cif
正在转换mp-972514.cif
正在转换mp-972517.cif
正在转换mp-972520.cif
正在转换mp-972521.cif
正在转换mp-972522.cif
正在转换mp-972524.cif
正在转换mp-972526.cif
正在转换mp-972528.cif
正在转换mp-972529.cif
正在转换mp-972530.cif
正在转换mp-972534.cif
正在转换mp-972536.cif
正在转换mp-972539.cif
正在转换mp-972540.cif
正在转换mp-972541.cif
正在转换mp-972542.cif
正在转换mp-972549.cif
正在转换mp-972557.cif
正在转换mp-972569.cif
正在转换mp-972600.cif
正在转换mp-972601.cif
正在转换mp-972607.cif
正在转换mp-972623.cif
正在转换mp-972626.cif
正在转换mp-972630.cif
正在转换mp-972631.cif
正在转换mp-972633.cif
正在转换mp-972635.cif
正在转换mp-972639.cif
正在转换mp-972640.cif
正在转换mp-972641.cif
正在转换mp-972649.cif
正在转换mp-972650.cif
正在转换mp-972653.cif
正在转换mp-972657.cif
正在转换mp-972658.cif
正在转换mp-972659.cif
正在转换mp-972660.cif
正在转换mp-972664.cif
正在转换mp-972680.cif
正在转换mp-972692.cif
正在转换mp-972722.cif
正在转换mp-972741.cif
正在转换mp-972742.cif
正在转换mp-972748.cif
正在转换mp-972751.cif
正在转换mp-972752.cif
正在转换mp-972763.cif
正在转换mp-972767.cif
正在转换mp-972777.cif
正在转换mp-972784.cif
正在转换mp-972793.cif
正在转换mp-972808.cif
正在转换mp-972810.cif
正在转换mp-972822.cif
正在转换mp-972827.cif
正在转换mp-972831.cif
正在转换mp-972837.cif
正在转换mp-972839.cif
正在转换mp-972845.cif
正在转换mp-972861.cif
正在转换mp-972866.cif
正在转换mp-972869.cif
正在转换mp-972876.cif
正在转换mp-972877.cif
正在转换mp-972879.cif
正在转换mp-972882.cif
正在转换mp-972884.cif
正在转换mp-972895.cif
正在转换mp-972898.cif
正在转换mp-972899.cif
正在转换mp-972907.cif
正在转换mp-972914.cif
正在转换mp-972916.cif
正在转换mp-972925.cif
正在转换mp-972935.cif
正在转换mp-972937.cif
正在转换mp-972945.cif
正在转换mp-972957.cif
正在转换mp-972966.cif
正在转换mp-972970.cif
正在转换mp-972984.cif
正在转换mp-972987.cif
正在转换mp-972993.cif
正在转换mp-972997.cif
正在转换mp-973004.cif
正在转换mp-973019.cif
正在转换mp-973055.cif
正在转换mp-973056.cif
正在转换mp-973058.cif
正在转换mp-973060.cif
正在转换mp-973064.cif
正在转换mp-973066.cif
正在转换mp-973067.cif
正在转换mp-973068.cif
正在转换mp-973069.cif
正在转换mp-973071.cif
正在转换mp-973088.cif
正在转换mp-973089.cif
正在转换mp-973091.cif
正在转换mp-973092.cif
正在转换mp-973100.cif
正在转换mp-973109.cif
正在转换mp-973123.cif
正在转换mp-973126.cif
正在转换mp-973136.cif
正在转换mp-973141.cif
正在转换mp-973142.cif
正在转换mp-973143.cif
正在转换mp-973153.cif
正在转换mp-973156.cif
正在转换mp-973170.cif
正在转换mp-973185.cif
正在转换mp-973203.cif
正在转换mp-973229.cif
正在转换mp-973232.cif
正在转换mp-973245.cif
正在转换mp-973256.cif
正在转换mp-973261.cif
正在转换mp-973265.cif
正在转换mp-973266.cif
正在转换mp-973267.cif
正在转换mp-973269.cif
正在转换mp-973270.cif
正在转换mp-973271.cif
正在转换mp-973276.cif
正在转换mp-973278.cif
正在转换mp-973283.cif
正在转换mp-973285.cif
正在转换mp-973286.cif
正在转换mp-973292.cif
正在转换mp-973300.cif
正在转换mp-973308.cif
正在转换mp-973314.cif
正在转换mp-973316.cif
正在转换mp-973325.cif
正在转换mp-973333.cif
正在转换mp-973334.cif
正在转换mp-973339.cif
正在转换mp-973342.cif
正在转换mp-973343.cif
正在转换mp-973352.cif
正在转换mp-973353.cif
正在转换mp-973354.cif
正在转换mp-973372.cif
正在转换mp-973374.cif
正在转换mp-973396.cif
正在转换mp-973402.cif
正在转换mp-973414.cif
正在转换mp-973430.cif
正在转换mp-973432.cif
正在转换mp-973433.cif
正在转换mp-973434.cif
正在转换mp-973442.cif
正在转换mp-973444.cif
正在转换mp-973446.cif
正在转换mp-973447.cif
正在转换mp-973450.cif
正在转换mp-973451.cif
正在转换mp-973455.cif
正在转换mp-973456.cif
正在转换mp-973457.cif
正在转换mp-973461.cif
正在转换mp-973465.cif
正在转换mp-973466.cif
正在转换mp-973471.cif
正在转换mp-973480.cif
正在转换mp-973493.cif
正在转换mp-973508.cif
正在转换mp-973524.cif
正在转换mp-973528.cif
正在转换mp-973529.cif
正在转换mp-973533.cif
正在转换mp-973534.cif
正在转换mp-973535.cif
正在转换mp-973536.cif
正在转换mp-973538.cif
正在转换mp-973539.cif
正在转换mp-973540.cif
正在转换mp-973544.cif
正在转换mp-973545.cif
正在转换mp-973554.cif
正在转换mp-973556.cif
正在转换mp-973557.cif
正在转换mp-973561.cif
正在转换mp-973572.cif
正在转换mp-973579.cif
正在转换mp-973586.cif
正在转换mp-973592.cif
正在转换mp-973599.cif
正在转换mp-973603.cif
正在转换mp-973606.cif
正在转换mp-973613.cif
正在转换mp-973614.cif
正在转换mp-973615.cif
正在转换mp-973622.cif
正在转换mp-973623.cif
正在转换mp-973625.cif
正在转换mp-973626.cif
正在转换mp-973627.cif
正在转换mp-973629.cif
正在转换mp-973631.cif
正在转换mp-973634.cif
正在转换mp-973635.cif
正在转换mp-973636.cif
正在转换mp-973646.cif
正在转换mp-973648.cif
正在转换mp-973653.cif
正在转换mp-973662.cif
正在转换mp-973666.cif
正在转换mp-973668.cif
正在转换mp-973674.cif
正在转换mp-973676.cif
正在转换mp-973681.cif
正在转换mp-973682.cif
正在转换mp-973685.cif
正在转换mp-973689.cif
正在转换mp-973732.cif
正在转换mp-973734.cif
正在转换mp-973738.cif
正在转换mp-973740.cif
正在转换mp-973741.cif
正在转换mp-973748.cif
正在转换mp-973750.cif
正在转换mp-973756.cif
正在转换mp-973757.cif
正在转换mp-973767.cif
正在转换mp-973773.cif
正在转换mp-973777.cif
正在转换mp-973778.cif
正在转换mp-973779.cif
正在转换mp-973785.cif
正在转换mp-973786.cif
正在转换mp-973788.cif
正在转换mp-973792.cif
正在转换mp-973796.cif
正在转换mp-973815.cif
正在转换mp-973818.cif
正在转换mp-973824.cif
正在转换mp-973826.cif
正在转换mp-973830.cif
正在转换mp-973831.cif
正在转换mp-973834.cif
正在转换mp-973835.cif
正在转换mp-973839.cif
正在转换mp-973843.cif
正在转换mp-973865.cif
正在转换mp-973866.cif
正在转换mp-973874.cif
正在转换mp-973875.cif
正在转换mp-973876.cif
正在转换mp-973877.cif
正在转换mp-973878.cif
正在转换mp-973881.cif
正在转换mp-973884.cif
正在转换mp-973886.cif
正在转换mp-973890.cif
正在转换mp-973893.cif
正在转换mp-973894.cif
正在转换mp-973895.cif
正在转换mp-973896.cif
正在转换mp-973908.cif
正在转换mp-973910.cif
正在转换mp-973919.cif
正在转换mp-973920.cif
正在转换mp-973933.cif
正在转换mp-973935.cif
正在转换mp-973936.cif
正在转换mp-973940.cif
正在转换mp-973948.cif
正在转换mp-973951.cif
正在转换mp-973956.cif
正在转换mp-973957.cif
正在转换mp-973958.cif
正在转换mp-973960.cif
正在转换mp-973964.cif
正在转换mp-973965.cif
正在转换mp-973968.cif
正在转换mp-973969.cif
正在转换mp-973974.cif
正在转换mp-973976.cif
正在转换mp-973977.cif
正在转换mp-973979.cif
正在转换mp-973983.cif
正在转换mp-973992.cif
正在转换mp-973994.cif
正在转换mp-973996.cif
正在转换mp-974000.cif

正在转换mp-974002.cif
正在转换mp-974049.cif
正在转换mp-974058.cif
正在转换mp-974059.cif
正在转换mp-974060.cif
正在转换mp-974061.cif
正在转换mp-974062.cif
正在转换mp-974063.cif
正在转换mp-974065.cif
正在转换mp-974066.cif
正在转换mp-974068.cif
正在转换mp-974108.cif
正在转换mp-974221.cif
正在转换mp-974253.cif
正在转换mp-974267.cif
正在转换mp-974270.cif
正在转换mp-974307.cif
正在转换mp-974309.cif
正在转换mp-974310.cif
正在转换mp-974313.cif
正在转换mp-974315.cif
正在转换mp-974322.cif
正在转换mp-974325.cif
正在转换mp-974326.cif
正在转换mp-974330.cif
正在转换mp-974335.cif
正在转换mp-974336.cif
正在转换mp-974337.cif
正在转换mp-974341.cif
正在转换mp-974355.cif
正在转换mp-974358.cif
正在转换mp-974364.cif
正在转换mp-974365.cif
正在转换mp-974368.cif
正在转换mp-974370.cif
正在转换mp-974371.cif
正在转换mp-974372.cif
正在转换mp-974376.cif
正在转换mp-974381.cif
正在转换mp-974386.cif
正在转换mp-974387.cif
正在转换mp-974392.cif
正在转换mp-974395.cif
正在转换mp-974399.cif
正在转换mp-974408.cif
正在转换mp-974411.cif
正在转换mp-974416.cif
正在转换mp-974417.cif
正在转换mp-974420.cif
正在转换mp-974421.cif
正在转换mp-974425.cif
正在转换mp-974426.cif
正在转换mp-974430.cif
正在转换mp-974432.cif
正在转换mp-974435.cif
正在转换mp-974437.cif
正在转换mp-974445.cif
正在转换mp-974451.cif
正在转换mp-974452.cif
正在转换mp-974455.cif
正在转换mp-974457.cif
正在转换mp-974458.cif
正在转换mp-974464.cif
正在转换mp-974467.cif
正在转换mp-974469.cif
正在转换mp-974474.cif
正在转换mp-974482.cif
正在转换mp-974517.cif
正在转换mp-974523.cif
正在转换mp-974525.cif
正在转换mp-974527.cif
正在转换mp-974545.cif
正在转换mp-974571.cif
正在转换mp-974572.cif
正在转换mp-974583.cif
正在转换mp-974586.cif
正在转换mp-974591.cif
正在转换mp-974603.cif
正在转换mp-974611.cif
正在转换mp-974613.cif
正在转换mp-974616.cif
正在转换mp-974617.cif
正在转换mp-974627.cif
正在转换mp-974631.cif
正在转换mp-974634.cif
正在转换mp-974635.cif
正在转换mp-974638.cif
正在转换mp-974641.cif
正在转换mp-974642.cif
正在转换mp-974658.cif
正在转换mp-974662.cif
正在转换mp-974672.cif
正在转换mp-974682.cif
正在转换mp-974708.cif
正在转换mp-974713.cif
正在转换mp-974729.cif
正在转换mp-974732.cif
正在转换mp-974734.cif
正在转换mp-974738.cif
正在转换mp-974739.cif
正在转换mp-974740.cif
正在转换mp-974743.cif
正在转换mp-974744.cif
正在转换mp-974745.cif
正在转换mp-974747.cif
正在转换mp-974748.cif
正在转换mp-974751.cif
正在转换mp-974754.cif
正在转换mp-974757.cif
正在转换mp-974758.cif
正在转换mp-974760.cif
正在转换mp-974768.cif
正在转换mp-974770.cif
正在转换mp-974774.cif
正在转换mp-974779.cif
正在转换mp-974782.cif
正在转换mp-974789.cif
正在转换mp-974795.cif
正在转换mp-974799.cif
正在转换mp-974810.cif
正在转换mp-974816.cif
正在转换mp-974820.cif
正在转换mp-974822.cif
正在转换mp-974827.cif
正在转换mp-974828.cif
正在转换mp-974832.cif
正在转换mp-974842.cif
正在转换mp-974843.cif
正在转换mp-974846.cif
正在转换mp-974850.cif
正在转换mp-974856.cif
正在转换mp-974865.cif
正在转换mp-974866.cif
正在转换mp-974869.cif
正在转换mp-974882.cif
正在转换mp-974883.cif
正在转换mp-974906.cif
正在转换mp-974925.cif
正在转换mp-974933.cif
正在转换mp-974938.cif
正在转换mp-974940.cif
正在转换mp-974943.cif
正在转换mp-974948.cif
正在转换mp-974949.cif
正在转换mp-974950.cif
正在转换mp-974951.cif
正在转换mp-974959.cif
正在转换mp-974962.cif
正在转换mp-974966.cif
正在转换mp-974970.cif
正在转换mp-974972.cif
正在转换mp-974973.cif
正在转换mp-974981.cif
正在转换mp-974982.cif
正在转换mp-974990.cif
正在转换mp-974997.cif
正在转换mp-975013.cif
正在转换mp-975015.cif
正在转换mp-975019.cif
正在转换mp-975028.cif
正在转换mp-975037.cif
正在转换mp-975043.cif
正在转换mp-975044.cif
正在转换mp-975045.cif
正在转换mp-975049.cif
正在转换mp-975050.cif
正在转换mp-975051.cif
正在转换mp-975052.cif
正在转换mp-975053.cif
正在转换mp-975055.cif
正在转换mp-975057.cif
正在转换mp-975059.cif
正在转换mp-975073.cif
正在转换mp-975079.cif
正在转换mp-975110.cif
正在转换mp-975138.cif
正在转换mp-975140.cif
正在转换mp-975142.cif
正在转换mp-975144.cif
正在转换mp-975159.cif
正在转换mp-975176.cif
正在转换mp-975179.cif
正在转换mp-975184.cif
正在转换mp-975190.cif
正在转换mp-975198.cif
正在转换mp-975199.cif
正在转换mp-975200.cif
正在转换mp-975206.cif
正在转换mp-975207.cif
正在转换mp-975208.cif
正在转换mp-975219.cif
正在转换mp-975222.cif
正在转换mp-975237.cif
正在转换mp-975253.cif
正在转换mp-975255.cif
正在转换mp-975256.cif
正在转换mp-975271.cif
正在转换mp-975274.cif
正在转换mp-975275.cif
正在转换mp-975284.cif
正在转换mp-975288.cif
正在转换mp-975291.cif
正在转换mp-975292.cif
正在转换mp-975296.cif
正在转换mp-975299.cif
正在转换mp-975312.cif
正在转换mp-975321.cif
正在转换mp-975322.cif
正在转换mp-975333.cif
正在转换mp-975337.cif
正在转换mp-975346.cif
正在转换mp-975347.cif
正在转换mp-975361.cif
正在转换mp-975364.cif
正在转换mp-975368.cif
正在转换mp-975373.cif
正在转换mp-975380.cif
正在转换mp-975382.cif
正在转换mp-975383.cif
正在转换mp-975384.cif
正在转换mp-975385.cif
正在转换mp-975386.cif
正在转换mp-975387.cif
正在转换mp-975388.cif
正在转换mp-975390.cif
正在转换mp-975394.cif
正在转换mp-975397.cif
正在转换mp-975404.cif
正在转换mp-975421.cif
正在转换mp-975422.cif
正在转换mp-975423.cif
正在转换mp-975425.cif
正在转换mp-975427.cif
正在转换mp-975439.cif
正在转换mp-975463.cif
正在转换mp-975467.cif
正在转换mp-975468.cif
正在转换mp-975509.cif
正在转换mp-975511.cif
正在转换mp-975512.cif
正在转换mp-975518.cif
正在转换mp-975521.cif
正在转换mp-975522.cif
正在转换mp-975524.cif
正在转换mp-975528.cif
正在转换mp-975530.cif
正在转换mp-975537.cif
正在转换mp-975554.cif
正在转换mp-975570.cif
正在转换mp-975579.cif
正在转换mp-975586.cif
正在转换mp-975589.cif
正在转换mp-975591.cif
正在转换mp-975592.cif
正在转换mp-975596.cif
正在转换mp-975599.cif
正在转换mp-975601.cif
正在转换mp-975608.cif
正在转换mp-975609.cif
正在转换mp-975611.cif
正在转换mp-975638.cif
正在转换mp-975639.cif
正在转换mp-975641.cif
正在转换mp-975642.cif
正在转换mp-975644.cif
正在转换mp-975646.cif
正在转换mp-975647.cif
正在转换mp-975649.cif
正在转换mp-975650.cif
正在转换mp-975651.cif
正在转换mp-975652.cif
正在转换mp-975653.cif
正在转换mp-975656.cif
正在转换mp-975657.cif
正在转换mp-975658.cif
正在转换mp-975664.cif
正在转换mp-975729.cif
正在转换mp-975738.cif
正在转换mp-975769.cif
正在转换mp-975780.cif
正在转换mp-975784.cif
正在转换mp-975786.cif
正在转换mp-975787.cif
正在转换mp-975788.cif
正在转换mp-975789.cif
正在转换mp-975793.cif
正在转换mp-975795.cif
正在转换mp-975797.cif
正在转换mp-975801.cif
正在转换mp-975802.cif
正在转换mp-975814.cif
正在转换mp-975821.cif
正在转换mp-975822.cif
正在转换mp-975848.cif
正在转换mp-975868.cif
正在转换mp-975872.cif
正在转换mp-975880.cif
正在转换mp-975882.cif
正在转换mp-975883.cif
正在转换mp-975886.cif
正在转换mp-975887.cif
正在转换mp-975892.cif
正在转换mp-975893.cif
正在转换mp-975896.cif
正在转换mp-975897.cif
正在转换mp-975905.cif
正在转换mp-975906.cif
正在转换mp-975909.cif
正在转换mp-975913.cif
正在转换mp-975914.cif
正在转换mp-975920.cif
正在转换mp-975921.cif
正在转换mp-975932.cif
正在转换mp-975933.cif
正在转换mp-975972.cif
正在转换mp-975990.cif
正在转换mp-975997.cif
正在转换mp-976008.cif
正在转换mp-976010.cif
正在转换mp-976017.cif
正在转换mp-976023.cif
正在转换mp-976030.cif
正在转换mp-976031.cif
正在转换mp-976032.cif
正在转换mp-976047.cif
正在转换mp-976061.cif
正在转换mp-976072.cif
正在转换mp-976076.cif
正在转换mp-976082.cif
正在转换mp-976106.cif
正在转换mp-976111.cif
正在转换mp-976114.cif
正在转换mp-976125.cif
正在转换mp-976126.cif
正在转换mp-976128.cif
正在转换mp-976129.cif
正在转换mp-976133.cif
正在转换mp-976135.cif
正在转换mp-976138.cif
正在转换mp-976142.cif
正在转换mp-976143.cif
正在转换mp-976147.cif
正在转换mp-976148.cif
正在转换mp-976150.cif
正在转换mp-976151.cif
正在转换mp-976155.cif
正在转换mp-976159.cif
正在转换mp-976181.cif
正在转换mp-976185.cif
正在转换mp-976187.cif
正在转换mp-976220.cif
正在转换mp-976221.cif
正在转换mp-976223.cif
正在转换mp-976229.cif
正在转换mp-976236.cif
正在转换mp-976239.cif
正在转换mp-976247.cif
正在转换mp-976249.cif
正在转换mp-976252.cif
正在转换mp-976254.cif
正在转换mp-976256.cif
正在转换mp-976259.cif
正在转换mp-976260.cif
正在转换mp-976261.cif
正在转换mp-976263.cif
正在转换mp-976264.cif
正在转换mp-976265.cif
正在转换mp-976267.cif
正在转换mp-976271.cif
正在转换mp-976273.cif
正在转换mp-976280.cif
正在转换mp-976283.cif
正在转换mp-976286.cif
正在转换mp-976289.cif
正在转换mp-976291.cif
正在转换mp-976292.cif
正在转换mp-976293.cif
正在转换mp-976319.cif
正在转换mp-976321.cif
正在转换mp-976322.cif
正在转换mp-976326.cif
正在转换mp-976330.cif
正在转换mp-976333.cif
正在转换mp-976334.cif
正在转换mp-976341.cif
正在转换mp-976343.cif
正在转换mp-976344.cif
正在转换mp-976356.cif
正在转换mp-976357.cif
正在转换mp-976358.cif
正在转换mp-976373.cif
正在转换mp-976404.cif
正在转换mp-976407.cif
正在转换mp-976409.cif
正在转换mp-976410.cif
正在转换mp-976412.cif
正在转换mp-976417.cif
正在转换mp-976418.cif
正在转换mp-976419.cif
正在转换mp-976420.cif
正在转换mp-976421.cif
正在转换mp-976422.cif
正在转换mp-976426.cif
正在转换mp-976446.cif
正在转换mp-976447.cif
正在转换mp-976578.cif
正在转换mp-976581.cif
正在转换mp-976582.cif
正在转换mp-976583.cif
正在转换mp-976588.cif
正在转换mp-976589.cif
正在转换mp-976590.cif
正在转换mp-976592.cif
正在转换mp-976593.cif
正在转换mp-976595.cif
正在转换mp-976596.cif
正在转换mp-976598.cif
正在转换mp-976599.cif
正在转换mp-976600.cif
正在转换mp-976679.cif
正在转换mp-976722.cif
正在转换mp-976724.cif
正在转换mp-976725.cif
正在转换mp-976727.cif
正在转换mp-976743.cif
正在转换mp-976744.cif
正在转换mp-976762.cif
正在转换mp-976763.cif
正在转换mp-976765.cif
正在转换mp-976772.cif
正在转换mp-976774.cif
正在转换mp-976775.cif
正在转换mp-976784.cif
正在转换mp-976797.cif
正在转换mp-976799.cif
正在转换mp-976802.cif
正在转换mp-976804.cif
正在转换mp-976806.cif
正在转换mp-976829.cif
正在转换mp-976830.cif
正在转换mp-976838.cif
正在转换mp-976847.cif
正在转换mp-976848.cif
正在转换mp-976856.cif
正在转换mp-976863.cif
正在转换mp-976870.cif
正在转换mp-976872.cif
正在转换mp-976876.cif
正在转换mp-976881.cif
正在转换mp-976884.cif
正在转换mp-976903.cif
正在转换mp-976923.cif
正在转换mp-976939.cif
正在转换mp-976943.cif
正在转换mp-976949.cif
正在转换mp-976968.cif
正在转换mp-976972.cif
正在转换mp-976976.cif
正在转换mp-977107.cif
正在转换mp-977112.cif
正在转换mp-977216.cif
正在转换mp-977239.cif
正在转换mp-977242.cif
正在转换mp-977244.cif
正在转换mp-977250.cif
正在转换mp-977264.cif
正在转换mp-977273.cif
正在转换mp-977275.cif
正在转换mp-977286.cif
正在转换mp-977296.cif
正在转换mp-977298.cif
正在转换mp-977310.cif
正在转换mp-977314.cif
正在转换mp-977334.cif
正在转换mp-977343.cif
正在转换mp-977352.cif
正在转换mp-977355.cif
正在转换mp-977360.cif
正在转换mp-977361.cif
正在转换mp-977362.cif
正在转换mp-977364.cif
正在转换mp-977372.cif
正在转换mp-977374.cif
正在转换mp-977376.cif
正在转换mp-977379.cif
正在转换mp-977383.cif
正在转换mp-977388.cif
正在转换mp-977389.cif
正在转换mp-977390.cif
正在转换mp-977391.cif
正在转换mp-977392.cif
正在转换mp-977393.cif
正在转换mp-977394.cif
正在转换mp-977395.cif
正在转换mp-977396.cif
正在转换mp-977397.cif
正在转换mp-977398.cif
正在转换mp-977399.cif
正在转换mp-977400.cif
正在转换mp-977401.cif
正在转换mp-977402.cif
正在转换mp-977404.cif
正在转换mp-977405.cif
正在转换mp-977406.cif
正在转换mp-977408.cif
正在转换mp-977409.cif
正在转换mp-977410.cif
正在转换mp-977413.cif
正在转换mp-977415.cif
正在转换mp-977416.cif
正在转换mp-977417.cif
正在转换mp-977418.cif
正在转换mp-977421.cif
正在转换mp-977422.cif
正在转换mp-977423.cif
正在转换mp-977424.cif
正在转换mp-977425.cif
正在转换mp-977427.cif
正在转换mp-977428.cif
正在转换mp-977430.cif
正在转换mp-977433.cif
正在转换mp-977434.cif
正在转换mp-977435.cif
正在转换mp-977436.cif
正在转换mp-977437.cif
正在转换mp-977438.cif
正在转换mp-977439.cif
正在转换mp-977440.cif
正在转换mp-977441.cif
正在转换mp-977442.cif
正在转换mp-977443.cif
正在转换mp-977444.cif
正在转换mp-977445.cif
正在转换mp-977446.cif
正在转换mp-977453.cif
正在转换mp-977454.cif
正在转换mp-977455.cif
正在转换mp-977462.cif
正在转换mp-977463.cif
正在转换mp-977475.cif
正在转换mp-977534.cif
正在转换mp-977535.cif
正在转换mp-977537.cif
正在转换mp-977538.cif
正在转换mp-977539.cif
正在转换mp-977540.cif
正在转换mp-977541.cif
正在转换mp-977542.cif
正在转换mp-977543.cif
正在转换mp-977545.cif
正在转换mp-977546.cif
正在转换mp-977547.cif
正在转换mp-977548.cif
正在转换mp-977549.cif
正在转换mp-977550.cif
正在转换mp-977551.cif
正在转换mp-977552.cif
正在转换mp-977553.cif
正在转换mp-977554.cif
正在转换mp-977555.cif

正在转换mp-977556.cif
正在转换mp-977557.cif
正在转换mp-977558.cif
正在转换mp-977559.cif
正在转换mp-977561.cif
正在转换mp-977562.cif
正在转换mp-977563.cif
正在转换mp-977564.cif
正在转换mp-977565.cif
正在转换mp-977566.cif
正在转换mp-977567.cif
正在转换mp-977568.cif
正在转换mp-977569.cif
正在转换mp-977570.cif
正在转换mp-977571.cif
正在转换mp-977572.cif
正在转换mp-977573.cif
正在转换mp-977574.cif
正在转换mp-977575.cif
正在转换mp-977576.cif
正在转换mp-977578.cif
正在转换mp-977579.cif
正在转换mp-977580.cif
正在转换mp-977582.cif
正在转换mp-977583.cif
正在转换mp-977584.cif
正在转换mp-977585.cif
正在转换mp-977586.cif
正在转换mp-977588.cif
正在转换mp-977589.cif
正在转换mp-977590.cif
正在转换mp-977592.cif
正在转换mp-977593.cif
正在转换mp-977997.cif
正在转换mp-978008.cif
正在转换mp-978009.cif
正在转换mp-978034.cif
正在转换mp-978039.cif
正在转换mp-978083.cif
正在转换mp-978084.cif
正在转换mp-978085.cif
正在转换mp-978086.cif
正在转换mp-978088.cif
正在转换mp-978089.cif
正在转换mp-978090.cif
正在转换mp-978093.cif
正在转换mp-978094.cif
正在转换mp-978095.cif
正在转换mp-978096.cif
正在转换mp-978098.cif
正在转换mp-978100.cif
正在转换mp-978101.cif
正在转换mp-978102.cif
正在转换mp-978255.cif
正在转换mp-978256.cif
正在转换mp-978257.cif
正在转换mp-978258.cif
正在转换mp-978261.cif
正在转换mp-978262.cif
正在转换mp-978263.cif
正在转换mp-978264.cif
正在转换mp-978265.cif
正在转换mp-978266.cif
正在转换mp-978267.cif
正在转换mp-978270.cif
正在转换mp-978272.cif
正在转换mp-978273.cif
正在转换mp-978280.cif
正在转换mp-978281.cif
正在转换mp-978282.cif
正在转换mp-978283.cif
正在转换mp-978285.cif
正在转换mp-978286.cif
正在转换mp-978287.cif
正在转换mp-978290.cif
正在转换mp-978292.cif
正在转换mp-978293.cif
正在转换mp-978294.cif
正在转换mp-978304.cif
正在转换mp-978489.cif
正在转换mp-978490.cif
正在转换mp-978493.cif
正在转换mp-978494.cif
正在转换mp-978495.cif
正在转换mp-978496.cif
正在转换mp-978497.cif
正在转换mp-978498.cif
正在转换mp-978500.cif
正在转换mp-978501.cif
正在转换mp-978502.cif
正在转换mp-978503.cif
正在转换mp-978504.cif
正在转换mp-978505.cif
正在转换mp-978506.cif
正在转换mp-978507.cif
正在转换mp-978508.cif
正在转换mp-978509.cif
正在转换mp-978510.cif
正在转换mp-978511.cif
正在转换mp-978512.cif
正在转换mp-978513.cif
正在转换mp-978514.cif
正在转换mp-978515.cif
正在转换mp-978516.cif
正在转换mp-978517.cif
正在转换mp-978518.cif
正在转换mp-978519.cif
正在转换mp-978520.cif
正在转换mp-978521.cif
正在转换mp-978522.cif
正在转换mp-978523.cif
正在转换mp-978524.cif
正在转换mp-978525.cif
正在转换mp-978527.cif
正在转换mp-978528.cif
正在转换mp-978529.cif
正在转换mp-978531.cif
正在转换mp-978532.cif
正在转换mp-978533.cif
正在转换mp-978535.cif
正在转换mp-978536.cif
正在转换mp-978537.cif
正在转换mp-978538.cif
正在转换mp-978539.cif
正在转换mp-978542.cif
正在转换mp-978543.cif
正在转换mp-978544.cif
正在转换mp-978545.cif
正在转换mp-978546.cif
正在转换mp-978547.cif
正在转换mp-978548.cif
正在转换mp-978549.cif
正在转换mp-978552.cif
正在转换mp-978554.cif
正在转换mp-978555.cif
正在转换mp-978557.cif
正在转换mp-978558.cif
正在转换mp-978560.cif
正在转换mp-978563.cif
正在转换mp-978564.cif
正在转换mp-978568.cif
正在转换mp-978569.cif
正在转换mp-978596.cif
正在转换mp-978624.cif
正在转换mp-978625.cif
正在转换mp-978640.cif
正在转换mp-978652.cif
正在转换mp-978662.cif
正在转换mp-978678.cif
正在转换mp-978679.cif
正在转换mp-978695.cif
正在转换mp-978744.cif
正在转换mp-978771.cif
正在转换mp-978790.cif
正在转换mp-978795.cif
正在转换mp-978796.cif
正在转换mp-978797.cif
正在转换mp-978798.cif
正在转换mp-978802.cif
正在转换mp-978807.cif
正在转换mp-978808.cif
正在转换mp-978809.cif
正在转换mp-978815.cif
正在转换mp-978823.cif
正在转换mp-978824.cif
正在转换mp-978825.cif
正在转换mp-978828.cif
正在转换mp-978829.cif
正在转换mp-978832.cif
正在转换mp-978833.cif
正在转换mp-978842.cif
正在转换mp-978844.cif
正在转换mp-978845.cif
正在转换mp-978846.cif
正在转换mp-978847.cif
正在转换mp-978849.cif
正在转换mp-978850.cif
正在转换mp-978851.cif
正在转换mp-978852.cif
正在转换mp-978853.cif
正在转换mp-978854.cif
正在转换mp-978855.cif
正在转换mp-978856.cif
正在转换mp-978857.cif
正在转换mp-978862.cif
正在转换mp-978881.cif
正在转换mp-978882.cif
正在转换mp-978885.cif
正在转换mp-978886.cif
正在转换mp-978891.cif
正在转换mp-978906.cif
正在转换mp-978907.cif
正在转换mp-978908.cif
正在转换mp-978910.cif
正在转换mp-978911.cif
正在转换mp-978912.cif
正在转换mp-978917.cif
正在转换mp-978918.cif
正在转换mp-978919.cif
正在转换mp-978920.cif
正在转换mp-978921.cif
正在转换mp-978926.cif
正在转换mp-978927.cif
正在转换mp-978929.cif
正在转换mp-978939.cif
正在转换mp-978949.cif
正在转换mp-978950.cif
正在转换mp-978951.cif
正在转换mp-978952.cif
正在转换mp-978953.cif
正在转换mp-978960.cif
正在转换mp-978962.cif
正在转换mp-978963.cif
正在转换mp-978964.cif
正在转换mp-978965.cif
正在转换mp-978967.cif
正在转换mp-978968.cif
正在转换mp-978969.cif
正在转换mp-978973.cif
正在转换mp-978974.cif
正在转换mp-978975.cif
正在转换mp-978984.cif
正在转换mp-978985.cif
正在转换mp-978987.cif
正在转换mp-978988.cif
正在转换mp-978989.cif
正在转换mp-978990.cif
正在转换mp-978993.cif
正在转换mp-978994.cif
正在转换mp-978995.cif
正在转换mp-978997.cif
正在转换mp-979001.cif
正在转换mp-979009.cif
正在转换mp-979010.cif
正在转换mp-979011.cif
正在转换mp-979012.cif
正在转换mp-979013.cif
正在转换mp-979014.cif
正在转换mp-979026.cif
正在转换mp-979028.cif
正在转换mp-979039.cif
正在转换mp-979040.cif
正在转换mp-979041.cif
正在转换mp-979042.cif
正在转换mp-979043.cif
正在转换mp-979044.cif
正在转换mp-979045.cif
正在转换mp-979057.cif
正在转换mp-979073.cif
正在转换mp-979074.cif
正在转换mp-979081.cif
正在转换mp-979114.cif
正在转换mp-979115.cif
正在转换mp-979116.cif
正在转换mp-979137.cif
正在转换mp-979176.cif
正在转换mp-979234.cif
正在转换mp-979253.cif
正在转换mp-979258.cif
正在转换mp-979261.cif
正在转换mp-979262.cif
正在转换mp-979266.cif
正在转换mp-979268.cif
正在转换mp-979269.cif
正在转换mp-979270.cif
正在转换mp-979271.cif
正在转换mp-979272.cif
正在转换mp-979273.cif
正在转换mp-979274.cif
正在转换mp-979282.cif
正在转换mp-979283.cif
正在转换mp-979287.cif
正在转换mp-979289.cif
正在转换mp-979291.cif
正在转换mp-979292.cif
正在转换mp-979293.cif
正在转换mp-979294.cif
正在转换mp-979339.cif
正在转换mp-979355.cif
正在转换mp-979412.cif
正在转换mp-979413.cif
正在转换mp-979414.cif
正在转换mp-979416.cif
正在转换mp-979417.cif
正在转换mp-979419.cif
正在转换mp-979421.cif
正在转换mp-979422.cif
正在转换mp-979423.cif
正在转换mp-979424.cif
正在转换mp-979425.cif
正在转换mp-979426.cif
正在转换mp-979427.cif
正在转换mp-979429.cif
正在转换mp-979430.cif
正在转换mp-979431.cif
正在转换mp-979432.cif
正在转换mp-979434.cif
正在转换mp-979435.cif
正在转换mp-979436.cif
正在转换mp-979437.cif
正在转换mp-979459.cif
正在转换mp-979465.cif
正在转换mp-979614.cif
正在转换mp-979712.cif
正在转换mp-979713.cif
正在转换mp-979714.cif
正在转换mp-979715.cif
正在转换mp-979751.cif
正在转换mp-979899.cif
正在转换mp-979900.cif
正在转换mp-979910.cif
正在转换mp-979911.cif
正在转换mp-979912.cif
正在转换mp-979917.cif
正在转换mp-979919.cif
正在转换mp-979923.cif
正在转换mp-979924.cif
正在转换mp-979931.cif
正在转换mp-979932.cif
正在转换mp-979933.cif
正在转换mp-979934.cif
正在转换mp-979935.cif
正在转换mp-979936.cif
正在转换mp-979937.cif
正在转换mp-979938.cif
正在转换mp-979939.cif
正在转换mp-979940.cif
正在转换mp-979941.cif
正在转换mp-979942.cif
正在转换mp-979945.cif
正在转换mp-979946.cif
正在转换mp-979948.cif
正在转换mp-979950.cif
正在转换mp-979951.cif
正在转换mp-979952.cif
正在转换mp-979953.cif
正在转换mp-979954.cif
正在转换mp-979955.cif
正在转换mp-979956.cif
正在转换mp-979961.cif
正在转换mp-979962.cif
正在转换mp-979963.cif
正在转换mp-979965.cif
正在转换mp-979966.cif
正在转换mp-979967.cif
正在转换mp-979968.cif
正在转换mp-979972.cif
正在转换mp-979973.cif
正在转换mp-979979.cif
正在转换mp-979980.cif
正在转换mp-979981.cif
正在转换mp-979982.cif
正在转换mp-979984.cif
正在转换mp-979985.cif
正在转换mp-979986.cif
正在转换mp-979987.cif
正在转换mp-979988.cif
正在转换mp-979989.cif
正在转换mp-980001.cif
正在转换mp-980005.cif
正在转换mp-980006.cif
正在转换mp-980014.cif
正在转换mp-980021.cif
正在转换mp-980034.cif
正在转换mp-980038.cif
正在转换mp-980044.cif
正在转换mp-980049.cif
正在转换mp-980052.cif
正在转换mp-980053.cif
正在转换mp-980054.cif
正在转换mp-980055.cif
正在转换mp-980056.cif
正在转换mp-980057.cif
正在转换mp-980058.cif
正在转换mp-980059.cif
正在转换mp-980060.cif
正在转换mp-980061.cif
正在转换mp-980062.cif
正在转换mp-980063.cif
正在转换mp-980064.cif
正在转换mp-980067.cif
正在转换mp-980068.cif
正在转换mp-980069.cif
正在转换mp-980070.cif
正在转换mp-980071.cif
正在转换mp-980082.cif
正在转换mp-980083.cif
正在转换mp-980084.cif
正在转换mp-980094.cif
正在转换mp-980108.cif
正在转换mp-980109.cif
正在转换mp-980110.cif
正在转换mp-980188.cif
正在转换mp-980189.cif
正在转换mp-980190.cif
正在转换mp-980191.cif
正在转换mp-980192.cif
正在转换mp-980193.cif
正在转换mp-980194.cif
正在转换mp-980196.cif
正在转换mp-980197.cif
正在转换mp-980199.cif
正在转换mp-980200.cif
正在转换mp-980201.cif
正在转换mp-980203.cif
正在转换mp-980206.cif
正在转换mp-980384.cif
正在转换mp-980385.cif
正在转换mp-980386.cif
正在转换mp-980426.cif
正在转换mp-980429.cif
正在转换mp-980537.cif
正在转换mp-980645.cif
正在转换mp-980646.cif
正在转换mp-980647.cif
正在转换mp-980648.cif
正在转换mp-980649.cif
正在转换mp-980659.cif
正在转换mp-980660.cif
正在转换mp-980661.cif
正在转换mp-980662.cif
正在转换mp-980664.cif
正在转换mp-980665.cif
正在转换mp-980667.cif
正在转换mp-980669.cif
正在转换mp-980749.cif
正在转换mp-980750.cif
正在转换mp-980752.cif
正在转换mp-980757.cif
正在转换mp-980760.cif
正在转换mp-980769.cif
正在转换mp-980811.cif
正在转换mp-980905.cif
正在转换mp-980938.cif
正在转换mp-980940.cif
正在转换mp-980941.cif
正在转换mp-980942.cif
正在转换mp-980943.cif
正在转换mp-980944.cif
正在转换mp-980945.cif
正在转换mp-980946.cif
正在转换mp-980947.cif
正在转换mp-980948.cif
正在转换mp-981103.cif
正在转换mp-981132.cif
正在转换mp-981200.cif
正在转换mp-981207.cif
正在转换mp-981208.cif
正在转换mp-981209.cif
正在转换mp-981210.cif
正在转换mp-981212.cif
正在转换mp-981213.cif
正在转换mp-981214.cif
正在转换mp-981215.cif
正在转换mp-981232.cif
正在转换mp-981233.cif
正在转换mp-981234.cif
正在转换mp-981247.cif
正在转换mp-981249.cif
正在转换mp-981250.cif
正在转换mp-981251.cif
正在转换mp-981262.cif
正在转换mp-981310.cif
正在转换mp-981311.cif
正在转换mp-981312.cif
正在转换mp-981313.cif
正在转换mp-981314.cif
正在转换mp-981364.cif
正在转换mp-981365.cif
正在转换mp-981367.cif
正在转换mp-981368.cif
正在转换mp-981376.cif
正在转换mp-981378.cif
正在转换mp-981379.cif
正在转换mp-981380.cif
正在转换mp-981381.cif
正在转换mp-981383.cif
正在转换mp-981384.cif
正在转换mp-981385.cif
正在转换mp-981386.cif
正在转换mp-981387.cif
正在转换mp-981390.cif
正在转换mp-981391.cif
正在转换mp-981393.cif
正在转换mp-981397.cif
正在转换mp-981458.cif
正在转换mp-981512.cif
正在转换mp-981541.cif
正在转换mp-981545.cif
正在转换mp-981546.cif
正在转换mp-981547.cif
正在转换mp-981548.cif
正在转换mp-981549.cif
正在转换mp-981550.cif
正在转换mp-981563.cif
正在转换mp-981662.cif
正在转换mp-981933.cif
正在转换mp-981934.cif
正在转换mp-982007.cif
正在转换mp-982008.cif
正在转换mp-982009.cif
正在转换mp-982010.cif
正在转换mp-982013.cif
正在转换mp-982015.cif
正在转换mp-982016.cif
正在转换mp-982017.cif
正在转换mp-982040.cif
正在转换mp-982045.cif
正在转换mp-982048.cif
正在转换mp-982064.cif
正在转换mp-982065.cif
正在转换mp-982070.cif
正在转换mp-982195.cif
正在转换mp-982205.cif
正在转换mp-982243.cif
正在转换mp-982246.cif
正在转换mp-982321.cif
正在转换mp-982367.cif
正在转换mp-982378.cif
正在转换mp-982381.cif
正在转换mp-982384.cif
正在转换mp-982387.cif
正在转换mp-982388.cif
正在转换mp-982393.cif
正在转换mp-982558.cif
正在转换mp-982595.cif
正在转换mp-982596.cif
正在转换mp-982597.cif
正在转换mp-982613.cif
正在转换mp-982615.cif
正在转换mp-982619.cif
正在转换mp-982635.cif
正在转换mp-982637.cif
正在转换mp-982663.cif
正在转换mp-982664.cif

正在转换mp-982665.cif
正在转换mp-982666.cif
正在转换mp-982667.cif
正在转换mp-982724.cif
正在转换mp-982725.cif
正在转换mp-982729.cif
正在转换mp-982730.cif
正在转换mp-982734.cif
正在转换mp-982739.cif
正在转换mp-982772.cif
正在转换mp-982773.cif
正在转换mp-982779.cif
正在转换mp-982780.cif
正在转换mp-982869.cif
正在转换mp-982870.cif
正在转换mp-982871.cif
正在转换mp-982873.cif
正在转换mp-982880.cif
正在转换mp-982881.cif
正在转换mp-982885.cif
正在转换mp-982929.cif
正在转换mp-982930.cif
正在转换mp-982974.cif
正在转换mp-982975.cif
正在转换mp-982980.cif
正在转换mp-982981.cif
正在转换mp-982982.cif
正在转换mp-983061.cif
正在转换mp-983062.cif
正在转换mp-983063.cif
正在转换mp-983123.cif
正在转换mp-983126.cif
正在转换mp-983152.cif
正在转换mp-983154.cif
正在转换mp-983229.cif
正在转换mp-983230.cif
正在转换mp-983234.cif
正在转换mp-983235.cif
正在转换mp-983236.cif
正在转换mp-983237.cif
正在转换mp-983327.cif
正在转换mp-983358.cif
正在转换mp-983359.cif
正在转换mp-983362.cif
正在转换mp-983365.cif
正在转换mp-983409.cif
正在转换mp-983410.cif
正在转换mp-983412.cif
正在转换mp-983425.cif
正在转换mp-983426.cif
正在转换mp-983428.cif
正在转换mp-983429.cif
正在转换mp-983430.cif
正在转换mp-983444.cif
正在转换mp-983445.cif
正在转换mp-983446.cif
正在转换mp-983459.cif
正在转换mp-983460.cif
正在转换mp-983479.cif
正在转换mp-983497.cif
正在转换mp-983513.cif
正在转换mp-983539.cif
正在转换mp-983562.cif
正在转换mp-983566.cif
正在转换mp-983582.cif
正在转换mp-983590.cif
正在转换mp-983594.cif
正在转换mp-983598.cif
正在转换mp-983602.cif
正在转换mp-983603.cif
正在转换mp-983604.cif
正在转换mp-983908.cif
正在转换mp-984104.cif
正在转换mp-984350.cif
正在转换mp-984351.cif
正在转换mp-984352.cif
正在转换mp-984355.cif
正在转换mp-984518.cif
正在转换mp-984534.cif
正在转换mp-984544.cif
正在转换mp-984551.cif
正在转换mp-984552.cif
正在转换mp-984553.cif
正在转换mp-984554.cif
正在转换mp-984597.cif
正在转换mp-984598.cif
正在转换mp-984605.cif
正在转换mp-984612.cif
正在转换mp-984614.cif
正在转换mp-984627.cif
正在转换mp-984628.cif
正在转换mp-984629.cif
正在转换mp-984632.cif
正在转换mp-984660.cif
正在转换mp-984695.cif
正在转换mp-984699.cif
正在转换mp-984700.cif
正在转换mp-984702.cif
正在转换mp-984704.cif
正在转换mp-984705.cif
正在转换mp-984707.cif
正在转换mp-984711.cif
正在转换mp-984712.cif
正在转换mp-984713.cif
正在转换mp-984715.cif
正在转换mp-984717.cif
正在转换mp-984718.cif
正在转换mp-984719.cif
正在转换mp-984720.cif
正在转换mp-984721.cif
正在转换mp-984722.cif
正在转换mp-984723.cif
正在转换mp-984724.cif
正在转换mp-984725.cif
正在转换mp-984726.cif
正在转换mp-984727.cif
正在转换mp-984728.cif
正在转换mp-984729.cif
正在转换mp-984744.cif
正在转换mp-984754.cif
正在转换mp-984765.cif
正在转换mp-984766.cif
正在转换mp-984767.cif
正在转换mp-984769.cif
正在转换mp-984772.cif
正在转换mp-984776.cif
正在转换mp-984779.cif
正在转换mp-984784.cif
正在转换mp-984785.cif
正在转换mp-984788.cif
正在转换mp-984791.cif
正在转换mp-984796.cif
正在转换mp-984806.cif
正在转换mp-984827.cif
正在转换mp-984836.cif
正在转换mp-984873.cif
正在转换mp-984876.cif
正在转换mp-985207.cif
正在转换mp-985278.cif
正在转换mp-985280.cif
正在转换mp-985282.cif
正在转换mp-985283.cif
正在转换mp-985285.cif
正在转换mp-985287.cif
正在转换mp-985289.cif
正在转换mp-985290.cif
正在转换mp-985292.cif
正在转换mp-985293.cif
正在转换mp-985295.cif
正在转换mp-985297.cif
正在转换mp-985299.cif
正在转换mp-985300.cif
正在转换mp-985301.cif
正在转换mp-985302.cif
正在转换mp-985303.cif
正在转换mp-985305.cif
正在转换mp-985437.cif
正在转换mp-985438.cif
正在转换mp-985439.cif
正在转换mp-985440.cif
正在转换mp-985442.cif
正在转换mp-985443.cif
正在转换mp-985450.cif
正在转换mp-985471.cif
正在转换mp-985506.cif
正在转换mp-985545.cif
正在转换mp-985547.cif
正在转换mp-985561.cif
正在转换mp-985564.cif
正在转换mp-985578.cif
正在转换mp-985579.cif
正在转换mp-985582.cif
正在转换mp-985584.cif
正在转换mp-985585.cif
正在转换mp-985586.cif
正在转换mp-985588.cif
正在转换mp-985591.cif
正在转换mp-985592.cif
正在转换mp-985626.cif
正在转换mp-985806.cif
正在转换mp-985825.cif
正在转换mp-985828.cif
正在转换mp-988940.cif
正在转换mp-988945.cif
正在转换mp-988996.cif
正在转换mp-989178.cif
正在转换mp-989189.cif
正在转换mp-989191.cif
正在转换mp-989192.cif
正在转换mp-989193.cif
正在转换mp-989195.cif
正在转换mp-989196.cif
正在转换mp-989197.cif
正在转换mp-989388.cif
正在转换mp-989399.cif
正在转换mp-989400.cif
正在转换mp-989402.cif
正在转换mp-989404.cif
正在转换mp-989407.cif
正在转换mp-989504.cif
正在转换mp-989512.cif
正在转换mp-989518.cif
正在转换mp-989520.cif
正在转换mp-989532.cif
正在转换mp-989533.cif
正在转换mp-989545.cif
正在转换mp-989547.cif
正在转换mp-989548.cif
正在转换mp-989550.cif
正在转换mp-989551.cif
正在转换mp-989555.cif
正在转换mp-989557.cif
正在转换mp-989561.cif
正在转换mp-989563.cif
正在转换mp-989565.cif
正在转换mp-989566.cif
正在转换mp-989578.cif
正在转换mp-989579.cif
正在转换mp-989583.cif
正在转换mp-989588.cif
正在转换mp-989601.cif
正在转换mp-989606.cif
正在转换mp-989609.cif
正在转换mp-989611.cif
正在转换mp-989613.cif
正在转换mp-989615.cif
正在转换mp-989616.cif
正在转换mp-989617.cif
正在转换mp-989622.cif
正在转换mp-989623.cif
正在转换mp-989624.cif
正在转换mp-989625.cif
正在转换mp-989627.cif
正在转换mp-989635.cif
正在转换mp-989636.cif
正在转换mp-989637.cif
正在转换mp-989638.cif
正在转换mp-989645.cif
正在转换mp-990076.cif
正在转换mp-990084.cif
正在转换mp-990430.cif
正在转换mp-990440.cif
正在转换mp-991652.cif
正在转换mp-991676.cif
正在转换mp-995147.cif
正在转换mp-995182.cif
正在转换mp-995190.cif
正在转换mp-995192.cif
正在转换mp-995194.cif
正在转换mp-995196.cif
正在转换mp-995197.cif
正在转换mp-995201.cif
正在转换mp-995205.cif
正在转换mp-995206.cif
正在转换mp-995216.cif
正在转换mp-995282.cif
正在转换mp-996161.cif
正在转换mp-996162.cif
正在转换mp-996940.cif
正在转换mp-996942.cif
正在转换mp-996954.cif
正在转换mp-996957.cif
正在转换mp-996959.cif
正在转换mp-996961.cif
正在转换mp-996962.cif
正在转换mp-996963.cif
正在转换mp-996964.cif
正在转换mp-996965.cif
正在转换mp-996966.cif
正在转换mp-996967.cif
正在转换mp-996970.cif
正在转换mp-996971.cif
正在转换mp-996973.cif
正在转换mp-996975.cif
正在转换mp-996977.cif
正在转换mp-996979.cif
正在转换mp-996980.cif
正在转换mp-996981.cif
正在转换mp-996982.cif
正在转换mp-996983.cif
正在转换mp-996984.cif
正在转换mp-996985.cif
正在转换mp-996986.cif
正在转换mp-996987.cif
正在转换mp-996988.cif
正在转换mp-996989.cif
正在转换mp-996990.cif
正在转换mp-996992.cif
正在转换mp-996994.cif
正在转换mp-996995.cif
正在转换mp-996996.cif
正在转换mp-996997.cif
正在转换mp-996998.cif
正在转换mp-997000.cif
正在转换mp-997001.cif
正在转换mp-997002.cif
正在转换mp-997004.cif
正在转换mp-997005.cif
正在转换mp-997006.cif
正在转换mp-997007.cif
正在转换mp-997008.cif
正在转换mp-997009.cif
正在转换mp-997010.cif
正在转换mp-997012.cif
正在转换mp-997013.cif
正在转换mp-997014.cif
正在转换mp-997015.cif
正在转换mp-997016.cif
正在转换mp-997018.cif
正在转换mp-997019.cif
正在转换mp-997021.cif
正在转换mp-997022.cif
正在转换mp-997023.cif
正在转换mp-997025.cif
正在转换mp-997026.cif
正在转换mp-997029.cif
正在转换mp-997030.cif
正在转换mp-997031.cif
正在转换mp-997032.cif
正在转换mp-997036.cif
正在转换mp-997037.cif
正在转换mp-997038.cif
正在转换mp-997039.cif
正在转换mp-997040.cif
正在转换mp-997041.cif
正在转换mp-997042.cif
正在转换mp-997043.cif
正在转换mp-997044.cif
正在转换mp-997046.cif
正在转换mp-997047.cif
正在转换mp-997048.cif
正在转换mp-997051.cif
正在转换mp-997054.cif
正在转换mp-997055.cif
正在转换mp-997082.cif
正在转换mp-997084.cif
正在转换mp-997085.cif
正在转换mp-997086.cif
正在转换mp-997089.cif
正在转换mp-997090.cif
正在转换mp-997094.cif
正在转换mp-997095.cif
正在转换mp-997098.cif
正在转换mp-997099.cif
正在转换mp-997100.cif
正在转换mp-997102.cif
正在转换mp-997106.cif
正在转换mp-997107.cif
正在转换mp-997108.cif
正在转换mp-997109.cif
正在转换mp-997158.cif
正在转换mp-997159.cif
正在转换mp-997160.cif
正在转换mp-997161.cif
正在转换mp-997162.cif
正在转换mp-997163.cif
正在转换mp-997167.cif
正在转换mp-997180.cif
正在转换mp-997181.cif
正在转换mp-997183.cif
正在转换mp-997184.cif
正在转换mp-997511.cif
正在转换mp-997530.cif
正在转换mp-997571.cif
正在转换mp-997616.cif
正在转换mp-997617.cif
正在转换mp-997618.cif
正在转换mp-997630.cif
正在转换mp-998147.cif
正在转换mp-998150.cif
正在转换mp-998151.cif
正在转换mp-998152.cif
正在转换mp-998153.cif
正在转换mp-998155.cif
正在转换mp-998156.cif
正在转换mp-998157.cif
正在转换mp-998159.cif
正在转换mp-998160.cif
正在转换mp-998176.cif
正在转换mp-998193.cif
正在转换mp-998196.cif
正在转换mp-998197.cif
正在转换mp-998198.cif
正在转换mp-998212.cif
正在转换mp-998227.cif
正在转换mp-998230.cif
正在转换mp-998231.cif
正在转换mp-998241.cif
正在转换mp-998299.cif
正在转换mp-998324.cif
正在转换mp-998325.cif
正在转换mp-998350.cif
正在转换mp-998352.cif
正在转换mp-998358.cif
正在转换mp-998363.cif
正在转换mp-998365.cif
正在转换mp-998391.cif
正在转换mp-998397.cif
正在转换mp-998398.cif
正在转换mp-998412.cif
正在转换mp-998414.cif
正在转换mp-998418.cif
正在转换mp-998419.cif
正在转换mp-998421.cif
正在转换mp-998422.cif
正在转换mp-998427.cif
正在转换mp-998512.cif
正在转换mp-998527.cif
正在转换mp-998535.cif
正在转换mp-998536.cif
正在转换mp-998537.cif
正在转换mp-998543.cif
正在转换mp-998552.cif
正在转换mp-998553.cif
正在转换mp-998554.cif
正在转换mp-998555.cif
正在转换mp-998567.cif
正在转换mp-998568.cif
正在转换mp-998569.cif
正在转换mp-998591.cif
正在转换mp-998592.cif
正在转换mp-998599.cif
正在转换mp-998601.cif
正在转换mp-998602.cif
正在转换mp-998603.cif
正在转换mp-998604.cif
正在转换mp-998605.cif
正在转换mp-998606.cif
正在转换mp-998608.cif
正在转换mp-998610.cif
正在转换mp-998611.cif
正在转换mp-998612.cif
正在转换mp-998613.cif
正在转换mp-998615.cif
正在转换mp-998620.cif
正在转换mp-998623.cif
正在转换mp-998624.cif
正在转换mp-998627.cif
正在转换mp-998710.cif
正在转换mp-998711.cif
正在转换mp-998712.cif
正在转换mp-998713.cif
正在转换mp-998739.cif
正在转换mp-998743.cif
正在转换mp-998744.cif
正在转换mp-998745.cif
正在转换mp-998746.cif
正在转换mp-998748.cif
正在转换mp-998749.cif
正在转换mp-998750.cif
正在转换mp-998755.cif
正在转换mp-998761.cif
正在转换mp-998762.cif
正在转换mp-998778.cif
正在转换mp-998781.cif
正在转换mp-998787.cif
正在转换mp-998800.cif
正在转换mp-998845.cif
正在转换mp-998893.cif
正在转换mp-998894.cif
正在转换mp-998896.cif
正在转换mp-998897.cif
正在转换mp-998899.cif
正在转换mp-998900.cif
正在转换mp-998901.cif
正在转换mp-998903.cif
正在转换mp-998908.cif
正在转换mp-998911.cif
正在转换mp-998913.cif
正在转换mp-998914.cif
正在转换mp-998915.cif
正在转换mp-998916.cif
正在转换mp-998917.cif
正在转换mp-998918.cif
正在转换mp-998919.cif
正在转换mp-998927.cif
正在转换mp-998928.cif
正在转换mp-998929.cif
正在转换mp-998945.cif
正在转换mp-998946.cif
正在转换mp-998947.cif
正在转换mp-998949.cif
正在转换mp-998964.cif
正在转换mp-998965.cif
正在转换mp-998968.cif
正在转换mp-998969.cif
正在转换mp-998970.cif
正在转换mp-998971.cif
正在转换mp-998972.cif
正在转换mp-998973.cif
正在转换mp-998974.cif
正在转换mp-998979.cif
正在转换mp-998980.cif
正在转换mp-998981.cif
正在转换mp-998982.cif
正在转换mp-998985.cif
正在转换mp-998986.cif
正在转换mp-998987.cif
正在转换mp-998988.cif
正在转换mp-999002.cif
正在转换mp-999027.cif
正在转换mp-999046.cif
正在转换mp-999047.cif
正在转换mp-999052.cif
正在转换mp-999053.cif
正在转换mp-999054.cif
正在转换mp-999059.cif

正在转换mp-999060.cif
正在转换mp-999067.cif
正在转换mp-999068.cif
正在转换mp-999069.cif
正在转换mp-999072.cif
正在转换mp-999076.cif
正在转换mp-999079.cif
正在转换mp-999083.cif
正在转换mp-999086.cif
正在转换mp-999088.cif
正在转换mp-999096.cif
正在转换mp-999117.cif
正在转换mp-999118.cif
正在转换mp-999119.cif
正在转换mp-999120.cif
正在转换mp-999121.cif
正在转换mp-999122.cif
正在转换mp-999123.cif
正在转换mp-999124.cif
正在转换mp-999126.cif
正在转换mp-999127.cif
正在转换mp-999129.cif
正在转换mp-999130.cif
正在转换mp-999132.cif
正在转换mp-999133.cif
正在转换mp-999135.cif
正在转换mp-999136.cif
正在转换mp-999137.cif
正在转换mp-999138.cif
正在转换mp-999139.cif
正在转换mp-999141.cif
正在转换mp-999142.cif
正在转换mp-999143.cif
正在转换mp-999144.cif
正在转换mp-999145.cif
正在转换mp-999177.cif
正在转换mp-999178.cif
正在转换mp-999187.cif
正在转换mp-999189.cif
正在转换mp-999190.cif
正在转换mp-999192.cif
正在转换mp-999193.cif
正在转换mp-999195.cif
正在转换mp-999197.cif
正在转换mp-999198.cif
正在转换mp-999201.cif
正在转换mp-999203.cif
正在转换mp-999204.cif
正在转换mp-999205.cif
正在转换mp-999206.cif
正在转换mp-999207.cif
正在转换mp-999208.cif
正在转换mp-999249.cif
正在转换mp-999256.cif
正在转换mp-999257.cif
正在转换mp-999258.cif
正在转换mp-999259.cif
正在转换mp-999263.cif
正在转换mp-999264.cif
正在转换mp-999265.cif
正在转换mp-999266.cif
正在转换mp-999267.cif
正在转换mp-999269.cif
正在转换mp-999274.cif
正在转换mp-999287.cif
正在转换mp-999288.cif
正在转换mp-999289.cif
正在转换mp-999290.cif
正在转换mp-999291.cif
正在转换mp-999292.cif
正在转换mp-999293.cif
正在转换mp-999294.cif
正在转换mp-999295.cif
正在转换mp-999296.cif
正在转换mp-999298.cif
正在转换mp-999303.cif
正在转换mp-999305.cif
正在转换mp-999306.cif
正在转换mp-999307.cif
正在转换mp-999308.cif
正在转换mp-999317.cif
正在转换mp-999318.cif
正在转换mp-999319.cif
正在转换mp-999335.cif
正在转换mp-999336.cif
正在转换mp-999338.cif
正在转换mp-999339.cif
正在转换mp-999355.cif
正在转换mp-999357.cif
正在转换mp-999376.cif
正在转换mp-999377.cif
正在转换mp-999388.cif
正在转换mp-999389.cif
正在转换mp-999390.cif
正在转换mp-999391.cif
正在转换mp-999392.cif
正在转换mp-999393.cif
正在转换mp-999395.cif
正在转换mp-999438.cif
正在转换mp-999439.cif
正在转换mp-999440.cif
正在转换mp-999441.cif
正在转换mp-999446.cif
正在转换mp-999447.cif
正在转换mp-999448.cif
正在转换mp-999450.cif
正在转换mp-999454.cif
正在转换mp-999455.cif
正在转换mp-999460.cif
正在转换mp-999461.cif
正在转换mp-999469.cif
正在转换mp-999470.cif
正在转换mp-999471.cif
正在转换mp-999472.cif
正在转换mp-999473.cif
正在转换mp-999474.cif
正在转换mp-999484.cif
正在转换mp-999485.cif
正在转换mp-999488.cif
正在转换mp-999490.cif
正在转换mp-999491.cif
正在转换mp-999495.cif
正在转换mp-999496.cif
正在转换mp-999502.cif
正在转换mp-999503.cif
正在转换mp-999507.cif
正在转换mp-999508.cif
正在转换mp-999516.cif
正在转换mp-999517.cif
正在转换mp-999539.cif
正在转换mp-999540.cif
正在转换mp-999542.cif
正在转换mp-999543.cif
正在转换mp-999544.cif
正在转换mp-999545.cif
正在转换mp-999549.cif
正在转换mp-999550.cif
正在转换mp-999552.cif
正在转换mp-999557.cif
正在转换mp-999558.cif
正在转换mp-999566.cif
正在转换mp-999576.cif
正在转换mp-4934.cif
正在转换mp-5026.cif
正在转换mp-5487.cif
正在转换mp-5492.cif
正在转换mp-5933.cif
正在转换mp-6008.cif
正在转换mvc-5514.cif
正在转换mvc-5533.cif
正在转换mp-765398.cif
正在转换mp-765399.cif
正在转换mp-765404.cif
正在转换mp-765409.cif
正在转换mp-765424.cif
正在转换mp-765432.cif
正在转换mp-765433.cif
正在转换mp-765436.cif
正在转换mp-765437.cif
正在转换mp-765438.cif
正在转换mp-765439.cif
正在转换mp-765440.cif
正在转换mp-765441.cif
正在转换mp-765443.cif
正在转换mp-765444.cif
正在转换mp-765445.cif
正在转换mp-765450.cif
正在转换mp-765451.cif
正在转换mp-765499.cif
正在转换mp-765502.cif
正在转换mp-765506.cif
正在转换mp-765508.cif
正在转换mp-765513.cif
正在转换mp-765518.cif
正在转换mp-765521.cif
正在转换mp-765525.cif
正在转换mp-765528.cif
正在转换mp-765529.cif
正在转换mp-765530.cif
正在转换mp-765531.cif
正在转换mp-765533.cif
正在转换mp-765538.cif
正在转换mp-765540.cif
正在转换mp-765544.cif
正在转换mp-765545.cif
正在转换mp-765546.cif
正在转换mp-765547.cif
正在转换mp-765548.cif
正在转换mp-765549.cif
正在转换mp-765550.cif
正在转换mp-765551.cif
正在转换mp-765559.cif
正在转换mp-765618.cif
正在转换mp-765668.cif
正在转换mp-765670.cif
正在转换mp-765673.cif
正在转换mp-765682.cif
正在转换mp-765687.cif
正在转换mp-765689.cif
正在转换mp-765695.cif
正在转换mp-765702.cif
正在转换mp-765703.cif
正在转换mp-765719.cif
正在转换mp-765720.cif
正在转换mp-765731.cif
正在转换mp-765734.cif
正在转换mp-765739.cif
正在转换mp-765750.cif
正在转换mp-765756.cif
正在转换mp-765757.cif
正在转换mp-765765.cif
正在转换mp-765775.cif
正在转换mp-765777.cif
正在转换mp-765780.cif
正在转换mp-765784.cif
正在转换mp-765786.cif
正在转换mp-765789.cif
正在转换mp-765792.cif
正在转换mp-765794.cif
正在转换mp-765795.cif
正在转换mp-765796.cif
正在转换mp-765800.cif
正在转换mp-765810.cif
正在转换mp-765813.cif
正在转换mp-765815.cif
正在转换mp-765817.cif
正在转换mp-765818.cif
正在转换mp-765820.cif
正在转换mp-765822.cif
正在转换mp-765825.cif
正在转换mp-765826.cif
正在转换mp-765828.cif
正在转换mp-765829.cif
正在转换mp-765835.cif
正在转换mp-765836.cif
正在转换mp-765837.cif
正在转换mp-765845.cif
正在转换mp-765849.cif
正在转换mp-765851.cif
正在转换mp-765859.cif
正在转换mp-765861.cif
正在转换mp-765862.cif
正在转换mp-765866.cif
正在转换mp-765869.cif
正在转换mp-765875.cif
正在转换mp-765876.cif
正在转换mp-765894.cif
正在转换mp-765899.cif
正在转换mp-765904.cif
正在转换mp-765908.cif
正在转换mp-765909.cif
正在转换mp-765913.cif
正在转换mp-765966.cif
正在转换mp-766115.cif
正在转换mp-766158.cif
正在转换mp-766325.cif
正在转换mp-766734.cif
正在转换mp-766737.cif
正在转换mp-766739.cif
正在转换mp-766761.cif
正在转换mp-766785.cif
正在转换mp-766786.cif
正在转换mp-766791.cif
正在转换mp-766801.cif
正在转换mp-766802.cif
正在转换mp-766803.cif
正在转换mp-766842.cif
正在转换mp-766854.cif
正在转换mp-766866.cif
正在转换mp-766901.cif
正在转换mp-766903.cif
正在转换mp-766906.cif
正在转换mp-766909.cif
正在转换mp-766912.cif
正在转换mp-766917.cif
正在转换mp-766932.cif
正在转换mp-766941.cif
正在转换mp-766949.cif
正在转换mp-766951.cif
正在转换mp-766952.cif
正在转换mp-766953.cif
正在转换mp-766963.cif
正在转换mp-766964.cif
正在转换mp-766992.cif
正在转换mp-767008.cif
正在转换mp-767023.cif
正在转换mp-767026.cif
正在转换mp-767027.cif
正在转换mp-767044.cif
正在转换mp-767112.cif
正在转换mp-767116.cif
正在转换mp-767119.cif
正在转换mp-767124.cif
正在转换mp-767127.cif
正在转换mp-767151.cif
正在转换mp-767160.cif
正在转换mp-767161.cif
正在转换mp-767163.cif
正在转换mp-767166.cif
正在转换mp-767168.cif
正在转换mp-767169.cif
正在转换mp-767172.cif
正在转换mp-767173.cif
正在转换mp-767189.cif
正在转换mp-767190.cif
正在转换mp-767195.cif
正在转换mp-767196.cif
正在转换mp-767197.cif
正在转换mp-767199.cif
正在转换mp-767202.cif
正在转换mp-767203.cif
正在转换mp-767212.cif
正在转换mp-767213.cif
正在转换mp-767214.cif
正在转换mp-767216.cif
正在转换mp-767217.cif
正在转换mp-767222.cif
正在转换mp-767226.cif
正在转换mp-767227.cif
正在转换mp-767228.cif
正在转换mp-767229.cif
正在转换mp-767230.cif
正在转换mp-767231.cif
正在转换mp-767232.cif
正在转换mp-767239.cif
正在转换mp-767241.cif
正在转换mp-767249.cif
正在转换mp-767252.cif
正在转换mp-767253.cif
正在转换mp-767254.cif
正在转换mp-767256.cif
正在转换mp-767260.cif
正在转换mp-767263.cif
正在转换mp-767267.cif
正在转换mp-767274.cif
正在转换mp-767282.cif
正在转换mp-767283.cif
正在转换mp-767285.cif
正在转换mp-767286.cif
正在转换mp-767287.cif
正在转换mp-767288.cif
正在转换mp-767294.cif
正在转换mp-767295.cif
正在转换mp-767296.cif
正在转换mp-767300.cif
正在转换mp-767301.cif
正在转换mp-767302.cif
正在转换mp-767303.cif
正在转换mp-767304.cif
正在转换mp-767309.cif
正在转换mp-767310.cif
正在转换mp-767311.cif
正在转换mp-767313.cif
正在转换mp-767317.cif
正在转换mp-767320.cif
正在转换mp-767321.cif
正在转换mp-767325.cif
正在转换mp-767330.cif
正在转换mp-767331.cif
正在转换mp-767333.cif
正在转换mp-767334.cif
正在转换mp-767340.cif
正在转换mp-767341.cif
正在转换mp-767343.cif
正在转换mp-767344.cif
正在转换mp-767345.cif
正在转换mp-767346.cif
正在转换mp-767348.cif
正在转换mp-767350.cif
正在转换mp-767352.cif
正在转换mp-767356.cif
正在转换mp-767360.cif
正在转换mp-767362.cif
正在转换mp-767367.cif
正在转换mp-767395.cif
正在转换mp-767403.cif
正在转换mp-767408.cif
正在转换mp-767409.cif
正在转换mp-767412.cif
正在转换mp-767415.cif
正在转换mp-767417.cif
正在转换mp-767430.cif
正在转换mp-767431.cif
正在转换mp-767433.cif
正在转换mp-767444.cif
正在转换mp-767447.cif
正在转换mp-767452.cif
正在转换mp-767462.cif
正在转换mp-767473.cif
正在转换mp-767480.cif
正在转换mp-767518.cif
正在转换mp-767521.cif
正在转换mp-767523.cif
正在转换mp-767529.cif
正在转换mp-767545.cif
正在转换mp-767562.cif
正在转换mp-767565.cif
正在转换mp-767566.cif
正在转换mp-767588.cif
正在转换mp-767589.cif
正在转换mp-767608.cif
正在转换mp-767617.cif
正在转换mp-767620.cif
正在转换mp-767622.cif
正在转换mp-767627.cif
正在转换mp-767631.cif
正在转换mp-767632.cif
正在转换mp-767644.cif
正在转换mp-767647.cif
正在转换mp-767649.cif
正在转换mp-767656.cif
正在转换mp-767659.cif
正在转换mp-767664.cif
正在转换mp-767669.cif
正在转换mp-767670.cif
正在转换mp-767678.cif
正在转换mp-767679.cif
正在转换mp-767681.cif
正在转换mp-767686.cif
正在转换mp-767699.cif
正在转换mp-767743.cif
正在转换mp-767772.cif
正在转换mp-767784.cif
正在转换mp-767802.cif
正在转换mp-767850.cif
正在转换mp-767908.cif
正在转换mp-767909.cif
正在转换mp-767921.cif
正在转换mp-767930.cif
正在转换mp-767932.cif
正在转换mp-767933.cif
正在转换mp-767935.cif
正在转换mp-767939.cif
正在转换mp-767943.cif
正在转换mp-767944.cif
正在转换mp-767954.cif
正在转换mp-767955.cif
正在转换mp-767967.cif
正在转换mp-767973.cif
正在转换mp-767979.cif
正在转换mp-767983.cif
正在转换mp-767985.cif
正在转换mp-767987.cif
正在转换mp-767996.cif
正在转换mp-767998.cif
正在转换mp-767999.cif
正在转换mp-768001.cif
正在转换mp-768005.cif
正在转换mp-768007.cif
正在转换mp-768010.cif
正在转换mp-768011.cif
正在转换mp-768014.cif
正在转换mp-768015.cif
正在转换mp-768016.cif
正在转换mp-768018.cif
正在转换mp-768021.cif
正在转换mp-768022.cif
正在转换mp-768023.cif
正在转换mp-768024.cif
正在转换mp-768025.cif
正在转换mp-768026.cif
正在转换mp-768029.cif
正在转换mp-768030.cif
正在转换mp-768031.cif
正在转换mp-768032.cif
正在转换mp-768034.cif
正在转换mp-768037.cif
正在转换mp-768038.cif
正在转换mp-768039.cif
正在转换mp-768041.cif
正在转换mp-768046.cif
正在转换mp-768051.cif
正在转换mp-768052.cif
正在转换mp-768054.cif
正在转换mp-768055.cif
正在转换mp-768057.cif
正在转换mp-768060.cif
正在转换mp-768063.cif
正在转换mp-768068.cif
正在转换mp-768103.cif
正在转换mp-768120.cif
正在转换mp-768146.cif

正在转换mp-768150.cif
正在转换mp-768154.cif
正在转换mp-768161.cif
正在转换mp-768164.cif
正在转换mp-768171.cif
正在转换mp-768175.cif
正在转换mp-768176.cif
正在转换mp-768190.cif
正在转换mp-768197.cif
正在转换mp-768203.cif
正在转换mp-768221.cif
正在转换mp-768227.cif
正在转换mp-768230.cif
正在转换mp-768231.cif
正在转换mp-768232.cif
正在转换mp-768240.cif
正在转换mp-768241.cif
正在转换mp-768242.cif
正在转换mp-768247.cif
正在转换mp-768268.cif
正在转换mp-768269.cif
正在转换mp-768303.cif
正在转换mp-768305.cif
正在转换mp-768307.cif
正在转换mp-768358.cif
正在转换mp-768422.cif
正在转换mp-768479.cif
正在转换mp-768539.cif
正在转换mp-768573.cif
正在转换mp-768766.cif
正在转换mp-768810.cif
正在转换mp-768863.cif
正在转换mp-768864.cif
正在转换mp-768884.cif
正在转换mp-768890.cif
正在转换mp-768907.cif
正在转换mp-768908.cif
正在转换mp-768970.cif
正在转换mp-769025.cif
正在转换mp-769118.cif
正在转换mp-769119.cif
正在转换mp-769173.cif
正在转换mp-769189.cif
正在转换mp-769211.cif
正在转换mp-769222.cif
正在转换mp-769229.cif
正在转换mp-769253.cif
正在转换mp-769277.cif
正在转换mp-769284.cif
正在转换mp-769297.cif
正在转换mp-769348.cif
正在转换mp-769364.cif
正在转换mp-769365.cif
正在转换mp-769391.cif
正在转换mp-769396.cif
正在转换mp-769466.cif
正在转换mp-769558.cif
正在转换mp-769565.cif
正在转换mp-769630.cif
正在转换mp-769631.cif
正在转换mp-769645.cif
正在转换mp-769646.cif
正在转换mp-769647.cif
正在转换mp-769655.cif
正在转换mp-769657.cif
正在转换mp-769660.cif
正在转换mp-769661.cif
正在转换mp-769665.cif
正在转换mp-769674.cif
正在转换mp-769675.cif
正在转换mp-769676.cif
正在转换mp-769680.cif
正在转换mp-769685.cif
正在转换mp-769687.cif
正在转换mp-769691.cif
正在转换mp-769692.cif
正在转换mp-769696.cif
正在转换mp-769697.cif
正在转换mp-769698.cif
正在转换mp-769702.cif
正在转换mp-769703.cif
正在转换mp-769706.cif
正在转换mp-769753.cif
正在转换mp-769754.cif
正在转换mp-769755.cif
正在转换mp-769756.cif
正在转换mp-769757.cif
正在转换mp-769758.cif
正在转换mp-769759.cif
正在转换mp-769760.cif
正在转换mp-769762.cif
正在转换mp-769764.cif
正在转换mp-769765.cif
正在转换mp-769767.cif
正在转换mp-769769.cif
正在转换mp-769771.cif
正在转换mp-769772.cif
正在转换mp-769773.cif
正在转换mp-769779.cif
正在转换mp-769784.cif
正在转换mp-769785.cif
正在转换mp-769786.cif
正在转换mp-769789.cif
正在转换mp-769794.cif
正在转换mp-769801.cif
正在转换mp-769803.cif
正在转换mp-769805.cif
正在转换mp-769810.cif
正在转换mp-769812.cif
正在转换mp-769813.cif
正在转换mp-769820.cif
正在转换mp-769843.cif
正在转换mp-769851.cif
正在转换mp-769857.cif
正在转换mp-769865.cif
正在转换mp-769874.cif
正在转换mp-769887.cif
正在转换mp-769888.cif
正在转换mp-769889.cif
正在转换mp-769895.cif
正在转换mp-769896.cif
正在转换mp-769897.cif
正在转换mp-769899.cif
正在转换mp-769900.cif
正在转换mp-769903.cif
正在转换mp-769904.cif
正在转换mp-769905.cif
正在转换mp-769906.cif
正在转换mp-769918.cif
正在转换mp-769921.cif
正在转换mp-769930.cif
正在转换mp-769931.cif
正在转换mp-769932.cif
正在转换mp-769933.cif
正在转换mp-769934.cif
正在转换mp-769941.cif
正在转换mp-769943.cif
正在转换mp-769946.cif
正在转换mp-769949.cif
正在转换mp-769970.cif
正在转换mp-769980.cif
正在转换mp-769983.cif
正在转换mp-769984.cif
正在转换mp-769990.cif
正在转换mp-769996.cif
正在转换mp-769998.cif
正在转换mp-770000.cif
正在转换mp-770001.cif
正在转换mp-770002.cif
正在转换mp-770003.cif
正在转换mp-770011.cif
正在转换mp-770014.cif
正在转换mp-770018.cif
正在转换mp-770019.cif
正在转换mp-770020.cif
正在转换mp-770024.cif
正在转换mp-770029.cif
正在转换mp-770030.cif
正在转换mp-770031.cif
正在转换mp-770038.cif
正在转换mp-770062.cif
正在转换mp-770068.cif
正在转换mp-770071.cif
正在转换mp-770086.cif
正在转换mp-770094.cif
正在转换mp-770097.cif
正在转换mp-770101.cif
正在转换mp-770102.cif
正在转换mp-770103.cif
正在转换mp-770104.cif
正在转换mp-770112.cif
正在转换mp-770118.cif
正在转换mp-770149.cif
正在转换mp-770150.cif
正在转换mp-770158.cif
正在转换mp-770173.cif
正在转换mp-770174.cif
正在转换mp-770184.cif
正在转换mp-770192.cif
正在转换mp-770523.cif
正在转换mp-770524.cif
正在转换mp-770530.cif
正在转换mp-770543.cif
正在转换mp-770603.cif
正在转换mp-770688.cif
正在转换mp-770797.cif
正在转换mp-770839.cif
正在转换mp-770840.cif
正在转换mp-770845.cif
正在转换mp-770848.cif
正在转换mp-770849.cif
正在转换mp-770851.cif
正在转换mp-770852.cif
正在转换mp-770857.cif
正在转换mp-770957.cif
正在转换mp-770986.cif
正在转换mp-770991.cif
正在转换mp-770997.cif
正在转换mp-771096.cif
正在转换mp-771098.cif
正在转换mp-771111.cif
正在转换mp-771219.cif
正在转换mp-771221.cif
正在转换mp-771287.cif
正在转换mp-771341.cif
正在转换mp-771384.cif
正在转换mp-771385.cif
正在转换mp-771393.cif
正在转换mp-771398.cif
正在转换mp-771401.cif
正在转换mp-771468.cif
正在转换mp-771469.cif
正在转换mp-771470.cif
正在转换mp-771471.cif
正在转换mp-771472.cif
正在转换mp-771476.cif
正在转换mp-771520.cif
正在转换mp-771522.cif
正在转换mp-771523.cif
正在转换mp-771524.cif
正在转换mp-771526.cif
正在转换mp-771532.cif
正在转换mp-771534.cif
正在转换mp-771535.cif
正在转换mp-771572.cif
正在转换mp-771593.cif
正在转换mp-771594.cif
正在转换mp-771600.cif
正在转换mp-771601.cif
正在转换mp-771605.cif
正在转换mp-771606.cif
正在转换mp-771607.cif
正在转换mp-771608.cif
正在转换mp-771609.cif
正在转换mp-771610.cif
正在转换mp-771611.cif
正在转换mp-771612.cif
正在转换mp-771613.cif
正在转换mp-771614.cif
正在转换mp-771615.cif
正在转换mp-771616.cif
正在转换mp-772191.cif
正在转换mp-772222.cif
正在转换mp-772233.cif
正在转换mp-772241.cif
正在转换mp-772244.cif
正在转换mp-772246.cif
正在转换mp-772247.cif
正在转换mp-772248.cif
正在转换mp-772250.cif
正在转换mp-772251.cif
正在转换mp-772252.cif
正在转换mp-772254.cif
正在转换mp-772257.cif
正在转换mp-772263.cif
正在转换mp-772267.cif
正在转换mp-772278.cif
正在转换mp-772280.cif
正在转换mp-772283.cif
正在转换mp-772290.cif
正在转换mp-772296.cif
正在转换mp-772297.cif
正在转换mp-772302.cif
正在转换mp-772304.cif
正在转换mp-772309.cif
正在转换mp-772317.cif
正在转换mp-772319.cif
正在转换mp-772328.cif
正在转换mp-772329.cif
正在转换mp-772331.cif
正在转换mp-772333.cif
正在转换mp-772338.cif
正在转换mp-772339.cif
正在转换mp-772347.cif
正在转换mp-772350.cif
正在转换mp-772353.cif
正在转换mp-772356.cif
正在转换mp-772357.cif
正在转换mp-772362.cif
正在转换mp-772363.cif
正在转换mp-772368.cif
正在转换mp-772369.cif
正在转换mp-772377.cif
正在转换mp-772378.cif
正在转换mp-772381.cif
正在转换mp-772382.cif
正在转换mp-772390.cif
正在转换mp-772391.cif
正在转换mp-772392.cif
正在转换mp-772395.cif
正在转换mp-772397.cif
正在转换mp-772399.cif
正在转换mp-772403.cif
正在转换mp-772417.cif
正在转换mp-772420.cif
正在转换mp-772434.cif
正在转换mp-772435.cif
正在转换mp-772446.cif
正在转换mp-772449.cif
正在转换mp-772456.cif
正在转换mp-772473.cif
正在转换mp-772477.cif
正在转换mp-772480.cif
正在转换mp-772487.cif
正在转换mp-772488.cif
正在转换mp-772510.cif
正在转换mp-772528.cif
正在转换mp-772529.cif
正在转换mp-772548.cif
正在转换mp-772550.cif
正在转换mp-772552.cif
正在转换mp-772561.cif
正在转换mp-772562.cif
正在转换mp-772569.cif
正在转换mp-772578.cif
正在转换mp-772592.cif
正在转换mp-772593.cif
正在转换mp-772594.cif
正在转换mp-772596.cif
正在转换mp-772597.cif
正在转换mp-772603.cif
正在转换mp-772624.cif
正在转换mp-772625.cif
正在转换mp-772635.cif
正在转换mp-772660.cif
正在转换mp-772680.cif
正在转换mp-772689.cif
正在转换mp-772692.cif
正在转换mp-772694.cif
正在转换mp-772696.cif
正在转换mp-772697.cif
正在转换mp-772698.cif
正在转换mp-772700.cif
正在转换mp-772701.cif
正在转换mp-772705.cif
正在转换mp-772713.cif
正在转换mp-772723.cif
正在转换mp-772724.cif
正在转换mp-772725.cif
正在转换mp-772726.cif
正在转换mp-772730.cif
正在转换mp-772731.cif
正在转换mp-772733.cif
正在转换mp-772734.cif
正在转换mp-772741.cif
正在转换mp-772750.cif
正在转换mp-772753.cif
正在转换mp-772754.cif
正在转换mp-772763.cif
正在转换mp-772777.cif
正在转换mp-772778.cif
正在转换mp-772780.cif
正在转换mp-772801.cif
正在转换mp-772809.cif
正在转换mp-772820.cif
正在转换mp-772821.cif
正在转换mp-772822.cif
正在转换mp-772835.cif
正在转换mp-772843.cif
正在转换mp-772844.cif
正在转换mp-772848.cif
正在转换mp-772968.cif
正在转换mp-772986.cif
正在转换mp-773030.cif
正在转换mp-773044.cif
正在转换mp-773087.cif
正在转换mp-773114.cif
正在转换mp-773119.cif
正在转换mp-773120.cif
正在转换mp-773138.cif
正在转换mp-773163.cif
正在转换mp-773167.cif
正在转换mp-773170.cif
正在转换mp-773176.cif
正在转换mp-773178.cif
正在转换mp-773179.cif
正在转换mp-773180.cif
正在转换mp-773181.cif
正在转换mp-773184.cif
正在转换mp-773188.cif
正在转换mp-773190.cif
正在转换mp-773198.cif
正在转换mp-773206.cif
正在转换mp-773208.cif
正在转换mp-773211.cif
正在转换mp-773216.cif
正在转换mp-773218.cif
正在转换mp-773220.cif
正在转换mp-773222.cif
正在转换mp-773224.cif
正在转换mp-773226.cif
正在转换mp-773229.cif
正在转换mp-773233.cif
正在转换mp-773236.cif
正在转换mp-773238.cif
正在转换mp-773239.cif
正在转换mp-773240.cif
正在转换mp-773242.cif
正在转换mp-773243.cif
正在转换mp-773244.cif
正在转换mp-773245.cif
正在转换mp-773247.cif
正在转换mp-773248.cif
正在转换mp-773253.cif
正在转换mp-773255.cif
正在转换mp-773256.cif
正在转换mp-773257.cif
正在转换mp-773258.cif
正在转换mp-773260.cif
正在转换mp-773261.cif
正在转换mp-773263.cif
正在转换mp-773265.cif
正在转换mp-773266.cif
正在转换mp-773267.cif
正在转换mp-773269.cif
正在转换mp-773270.cif
正在转换mp-773272.cif
正在转换mp-773276.cif
正在转换mp-773277.cif
正在转换mp-773282.cif
正在转换mp-773283.cif
正在转换mp-773285.cif
正在转换mp-773293.cif
正在转换mp-773294.cif
正在转换mp-773295.cif
正在转换mp-773296.cif
正在转换mp-773299.cif
正在转换mp-773305.cif
正在转换mp-773307.cif
正在转换mp-773308.cif
正在转换mp-773309.cif
正在转换mp-773310.cif
正在转换mp-773313.cif
正在转换mp-773314.cif
正在转换mp-773317.cif
正在转换mp-773318.cif
正在转换mp-773322.cif
正在转换mp-773326.cif
正在转换mp-773330.cif
正在转换mp-773331.cif
正在转换mp-773337.cif
正在转换mp-773338.cif
正在转换mp-773339.cif
正在转换mp-773340.cif
正在转换mp-773344.cif
正在转换mp-773347.cif
正在转换mp-773352.cif
正在转换mp-773354.cif
正在转换mp-773363.cif
正在转换mp-773366.cif
正在转换mp-773367.cif
正在转换mp-773368.cif
正在转换mp-773369.cif
正在转换mp-773370.cif
正在转换mp-773377.cif
正在转换mp-773383.cif
正在转换mp-773385.cif
正在转换mp-773387.cif
正在转换mp-773393.cif
正在转换mp-773399.cif
正在转换mp-773418.cif
正在转换mp-773439.cif
正在转换mp-773440.cif
正在转换mp-773441.cif
正在转换mp-773450.cif
正在转换mp-773460.cif
正在转换mp-773461.cif
正在转换mp-773465.cif
正在转换mp-773467.cif
正在转换mp-773468.cif
正在转换mp-773470.cif
正在转换mp-773500.cif
正在转换mp-773514.cif
正在转换mp-773515.cif
正在转换mp-773516.cif
正在转换mp-773519.cif
正在转换mp-773525.cif
正在转换mp-773534.cif
正在转换mp-773535.cif
正在转换mp-773536.cif
正在转换mp-773537.cif
正在转换mp-773543.cif
正在转换mp-773544.cif
正在转换mp-773547.cif
正在转换mp-773548.cif
正在转换mp-773554.cif
正在转换mp-773555.cif
正在转换mp-773556.cif
正在转换mp-773560.cif

正在转换mp-773561.cif
正在转换mp-773563.cif
正在转换mp-773564.cif
正在转换mp-773565.cif
正在转换mp-773566.cif
正在转换mp-773569.cif
正在转换mp-773572.cif
正在转换mp-773575.cif
正在转换mp-773588.cif
正在转换mp-773607.cif
正在转换mp-773610.cif
正在转换mp-773617.cif
正在转换mp-773618.cif
正在转换mp-773621.cif
正在转换mp-773626.cif
正在转换mp-773628.cif
正在转换mp-773697.cif
正在转换mp-773708.cif
正在转换mp-773720.cif
正在转换mp-773731.cif
正在转换mp-773736.cif
正在转换mp-773740.cif
正在转换mp-773744.cif
正在转换mp-773748.cif
正在转换mp-773750.cif
正在转换mp-773751.cif
正在转换mp-773754.cif
正在转换mp-773758.cif
正在转换mp-773759.cif
正在转换mp-773760.cif
正在转换mp-773761.cif
正在转换mp-773764.cif
正在转换mp-773769.cif
正在转换mp-773770.cif
正在转换mp-773778.cif
正在转换mp-773864.cif
正在转换mp-773929.cif
正在转换mp-773936.cif
正在转换mp-773957.cif
正在转换mp-773978.cif
正在转换mp-773994.cif
正在转换mp-774003.cif
正在转换mp-774004.cif
正在转换mp-774006.cif
正在转换mp-774012.cif
正在转换mp-774064.cif
正在转换mp-774068.cif
正在转换mp-774070.cif
正在转换mp-774076.cif
正在转换mp-774085.cif
正在转换mp-774086.cif
正在转换mp-774087.cif
正在转换mp-774088.cif
正在转换mp-774090.cif
正在转换mp-774091.cif
正在转换mp-774092.cif
正在转换mp-774093.cif
正在转换mp-774094.cif
正在转换mp-774095.cif
正在转换mp-774096.cif
正在转换mp-774098.cif
正在转换mp-774101.cif
正在转换mp-774104.cif
正在转换mp-774111.cif
正在转换mp-774113.cif
正在转换mp-774116.cif
正在转换mp-774117.cif
正在转换mp-774120.cif
正在转换mp-774121.cif
正在转换mp-774123.cif
正在转换mp-774124.cif
正在转换mp-774127.cif
正在转换mp-774128.cif
正在转换mp-774130.cif
正在转换mp-774133.cif
正在转换mp-774134.cif
正在转换mp-774135.cif
正在转换mp-774138.cif
正在转换mp-774140.cif
正在转换mp-774143.cif
正在转换mp-774145.cif
正在转换mp-774148.cif
正在转换mp-774150.cif
正在转换mp-774153.cif
正在转换mp-774155.cif
正在转换mp-774156.cif
正在转换mp-774172.cif
正在转换mp-774174.cif
正在转换mp-774192.cif
正在转换mp-774234.cif
正在转换mp-774236.cif
正在转换mp-774242.cif
正在转换mp-774243.cif
正在转换mp-774245.cif
正在转换mp-774251.cif
正在转换mp-774289.cif
正在转换mp-774305.cif
正在转换mp-774326.cif
正在转换mp-774328.cif
正在转换mp-774332.cif
正在转换mp-774336.cif
正在转换mp-774371.cif
正在转换mp-774401.cif
正在转换mp-774411.cif
正在转换mp-774415.cif
正在转换mp-774424.cif
正在转换mp-774430.cif
正在转换mp-774472.cif
正在转换mp-774520.cif
正在转换mp-774697.cif
正在转换mp-774702.cif
正在转换mp-774712.cif
正在转换mp-774736.cif
正在转换mp-774883.cif
正在转换mp-774907.cif
正在转换mp-774910.cif
正在转换mp-774922.cif
正在转换mp-774944.cif
正在转换mp-775015.cif
正在转换mp-775020.cif
正在转换mp-775022.cif
正在转换mp-775023.cif
正在转换mp-775027.cif
正在转换mp-775035.cif
正在转换mp-775036.cif
正在转换mp-775047.cif
正在转换mp-775052.cif
正在转换mp-775056.cif
正在转换mp-775057.cif
正在转换mp-775059.cif
正在转换mp-775060.cif
正在转换mp-775079.cif
正在转换mp-775084.cif
正在转换mp-775085.cif
正在转换mp-775086.cif
正在转换mp-775088.cif
正在转换mp-775094.cif
正在转换mp-775095.cif
正在转换mp-775097.cif
正在转换mp-775098.cif
正在转换mp-775105.cif
正在转换mp-775106.cif
正在转换mp-775109.cif
正在转换mp-775112.cif
正在转换mp-775113.cif
正在转换mp-775114.cif
正在转换mp-775115.cif
正在转换mp-775153.cif
正在转换mp-775190.cif
正在转换mp-775196.cif
正在转换mp-775205.cif
正在转换mp-775209.cif
正在转换mp-775236.cif
正在转换mp-775241.cif
正在转换mp-775296.cif
正在转换mp-775430.cif
正在转换mp-775515.cif
正在转换mp-775519.cif
正在转换mp-775530.cif
正在转换mp-775620.cif
正在转换mp-775621.cif
正在转换mp-775651.cif
正在转换mp-775652.cif
正在转换mp-775663.cif
正在转换mp-775721.cif
正在转换mp-775742.cif
正在转换mp-775757.cif
正在转换mp-775761.cif
正在转换mp-775763.cif
正在转换mp-775767.cif
正在转换mp-775774.cif
正在转换mp-775777.cif
正在转换mp-775789.cif
正在转换mp-775792.cif
正在转换mp-775796.cif
正在转换mp-775805.cif
正在转换mp-775808.cif
正在转换mp-775811.cif
正在转换mp-775825.cif
正在转换mp-775846.cif
正在转换mp-775869.cif
正在转换mp-775909.cif
正在转换mp-775916.cif
正在转换mp-775935.cif
正在转换mp-775944.cif
正在转换mp-775983.cif
正在转换mp-775986.cif
正在转换mp-776015.cif
正在转换mp-776016.cif
正在转换mp-776021.cif
正在转换mp-776053.cif
正在转换mp-776054.cif
正在转换mp-776081.cif
正在转换mp-776082.cif
正在转换mp-776092.cif
正在转换mp-776104.cif
正在转换mp-776115.cif
正在转换mp-776136.cif
正在转换mp-776138.cif
正在转换mp-776150.cif
正在转换mp-776165.cif
正在转换mp-776168.cif
正在转换mp-776172.cif
正在转换mp-776185.cif
正在转换mp-776189.cif
正在转换mp-776199.cif
正在转换mp-776204.cif
正在转换mp-776205.cif
正在转换mp-776233.cif
正在转换mp-776250.cif
正在转换mp-776263.cif
正在转换mp-776319.cif
正在转换mp-776366.cif
正在转换mp-776386.cif
正在转换mp-776427.cif
正在转换mp-776439.cif
正在转换mp-776466.cif
正在转换mp-776470.cif
正在转换mp-776486.cif
正在转换mp-776494.cif
正在转换mp-776495.cif
正在转换mp-776496.cif
正在转换mp-776509.cif
正在转换mp-776511.cif
正在转换mp-776512.cif
正在转换mp-776513.cif
正在转换mp-776514.cif
正在转换mp-776528.cif
正在转换mp-776532.cif
正在转换mp-776563.cif
正在转换mp-776593.cif
正在转换mp-776615.cif
正在转换mp-776616.cif
正在转换mp-776618.cif
正在转换mp-776621.cif
正在转换mp-776623.cif
正在转换mp-776624.cif
正在转换mp-776626.cif
正在转换mp-776641.cif
正在转换mp-776646.cif
正在转换mp-776649.cif
正在转换mp-776651.cif
正在转换mp-776654.cif
正在转换mp-776655.cif
正在转换mp-776670.cif
正在转换mp-776671.cif
正在转换mp-776678.cif
正在转换mp-776682.cif
正在转换mp-776687.cif
正在转换mp-776690.cif
正在转换mp-776708.cif
正在转换mp-776710.cif
正在转换mp-776711.cif
正在转换mp-776714.cif
正在转换mp-776732.cif
正在转换mp-776754.cif
正在转换mp-776784.cif
正在转换mp-776785.cif
正在转换mp-776786.cif
正在转换mp-776791.cif
正在转换mp-776794.cif
正在转换mp-776803.cif
正在转换mp-776810.cif
正在转换mp-776813.cif
正在转换mp-776814.cif
正在转换mp-776827.cif
正在转换mp-776836.cif
正在转换mp-776856.cif
正在转换mp-776869.cif
正在转换mp-776870.cif
正在转换mp-776881.cif
正在转换mp-776883.cif
正在转换mp-776890.cif
正在转换mp-776911.cif
正在转换mp-776939.cif
正在转换mp-776952.cif
正在转换mp-776996.cif
正在转换mp-776999.cif
正在转换mp-777005.cif
正在转换mp-777018.cif
正在转换mp-777025.cif
正在转换mp-777026.cif
正在转换mp-777037.cif
正在转换mp-777038.cif
正在转换mp-777039.cif
正在转换mp-777041.cif
正在转换mp-777047.cif
正在转换mp-777052.cif
正在转换mp-777058.cif
正在转换mp-777059.cif
正在转换mp-777076.cif
正在转换mp-777077.cif
正在转换mp-777078.cif
正在转换mp-777085.cif
正在转换mp-777088.cif
正在转换mp-777089.cif
正在转换mp-777096.cif
正在转换mp-777097.cif
正在转换mp-777099.cif
正在转换mp-777133.cif
正在转换mp-777138.cif
正在转换mp-777146.cif
正在转换mp-777150.cif
正在转换mp-777151.cif
正在转换mp-777239.cif
正在转换mp-777240.cif
正在转换mp-777303.cif
正在转换mp-777321.cif
正在转换mp-777322.cif
正在转换mp-777324.cif
正在转换mp-777325.cif
正在转换mp-777362.cif
正在转换mp-777389.cif
正在转换mp-777422.cif
正在转换mp-777432.cif
正在转换mp-777433.cif
正在转换mp-777459.cif
正在转换mp-777460.cif
正在转换mp-777463.cif
正在转换mp-777464.cif
正在转换mp-777469.cif
正在转换mp-777472.cif
正在转换mp-777475.cif
正在转换mp-777483.cif
正在转换mp-777500.cif
正在转换mp-777514.cif
正在转换mp-777522.cif
正在转换mp-777528.cif
正在转换mp-777546.cif
正在转换mp-777551.cif
正在转换mp-777556.cif
正在转换mp-777566.cif
正在转换mp-777580.cif
正在转换mp-777584.cif
正在转换mp-777588.cif
正在转换mp-777591.cif
正在转换mp-777595.cif
正在转换mp-777603.cif
正在转换mp-777604.cif
正在转换mp-777606.cif
正在转换mp-777622.cif
正在转换mp-777625.cif
正在转换mp-777626.cif
正在转换mp-777629.cif
正在转换mp-777630.cif
正在转换mp-777633.cif
正在转换mp-777634.cif
正在转换mp-777635.cif
正在转换mp-777654.cif
正在转换mp-777664.cif
正在转换mp-777672.cif
正在转换mp-777692.cif
正在转换mp-777694.cif
正在转换mp-777697.cif
正在转换mp-777702.cif
正在转换mp-777720.cif
正在转换mp-777724.cif
正在转换mp-777778.cif
正在转换mp-777858.cif
正在转换mp-777894.cif
正在转换mp-777900.cif
正在转换mp-777907.cif
正在转换mp-777912.cif
正在转换mp-777913.cif
正在转换mp-777919.cif
正在转换mp-777926.cif
正在转换mp-777964.cif
正在转换mp-778013.cif
正在转换mp-778022.cif
正在转换mp-778023.cif
正在转换mp-778024.cif
正在转换mp-778026.cif
正在转换mp-778033.cif
正在转换mp-778052.cif
正在转换mp-778060.cif
正在转换mp-778079.cif
正在转换mp-778114.cif
正在转换mp-778194.cif
正在转换mp-778219.cif
正在转换mp-778241.cif
正在转换mp-778280.cif
正在转换mp-778294.cif
正在转换mp-778298.cif
正在转换mp-778344.cif
正在转换mp-778346.cif
正在转换mp-778347.cif
正在转换mp-778348.cif
正在转换mp-778350.cif
正在转换mp-778351.cif
正在转换mp-778392.cif
正在转换mp-778394.cif
正在转换mp-778408.cif
正在转换mp-778409.cif
正在转换mp-778416.cif
正在转换mp-778509.cif
正在转换mp-778528.cif
正在转换mp-778538.cif
正在转换mp-778539.cif
正在转换mp-778543.cif
正在转换mp-778547.cif
正在转换mp-778554.cif
正在转换mp-778563.cif
正在转换mp-778565.cif
正在转换mp-778568.cif
正在转换mp-778569.cif
正在转换mp-778573.cif
正在转换mp-778576.cif
正在转换mp-778591.cif
正在转换mp-778617.cif
正在转换mp-778624.cif
正在转换mp-778632.cif
正在转换mp-778644.cif
正在转换mp-778646.cif
正在转换mp-778655.cif
正在转换mp-778687.cif
正在转换mp-778704.cif
正在转换mp-778707.cif
正在转换mp-778717.cif
正在转换mp-778726.cif
正在转换mp-778729.cif
正在转换mp-778732.cif
正在转换mp-778733.cif
正在转换mp-778746.cif
正在转换mp-778749.cif
正在转换mp-778750.cif
正在转换mp-778756.cif
正在转换mp-778757.cif
正在转换mp-778766.cif
正在转换mp-778767.cif
正在转换mp-778768.cif
正在转换mp-778769.cif
正在转换mp-778779.cif
正在转换mp-778780.cif
正在转换mp-778787.cif
正在转换mp-778793.cif
正在转换mp-778826.cif
正在转换mp-778848.cif
正在转换mp-778924.cif
正在转换mp-778928.cif
正在转换mp-779012.cif
正在转换mp-779083.cif
正在转换mp-779181.cif
正在转换mp-779182.cif
正在转换mp-779190.cif
正在转换mp-779191.cif
正在转换mp-779210.cif
正在转换mp-779211.cif
正在转换mp-779214.cif
正在转换mp-779216.cif
正在转换mp-779235.cif
正在转换mp-779236.cif
正在转换mp-779237.cif
正在转换mp-779242.cif
正在转换mp-779244.cif
正在转换mp-779245.cif
正在转换mp-779246.cif
正在转换mp-779925.cif
正在转换mp-779926.cif
正在转换mp-779929.cif
正在转换mp-779941.cif
正在转换mp-779943.cif
正在转换mp-779948.cif
正在转换mp-779950.cif
正在转换mp-779951.cif
正在转换mp-779963.cif
正在转换mp-779964.cif
正在转换mp-779967.cif
正在转换mp-779970.cif
正在转换mp-779972.cif
正在转换mp-779976.cif

正在转换mp-779978.cif
正在转换mp-779984.cif
正在转换mp-779985.cif
正在转换mp-779997.cif
正在转换mp-779999.cif
正在转换mp-780011.cif
正在转换mp-780023.cif
正在转换mp-780033.cif
正在转换mp-780036.cif
正在转换mp-780042.cif
正在转换mp-780098.cif
正在转换mp-780116.cif
正在转换mp-780153.cif
正在转换mp-780154.cif
正在转换mp-780210.cif
正在转换mp-780211.cif
正在转换mp-780215.cif
正在转换mp-780217.cif
正在转换mp-780243.cif
正在转换mp-780275.cif
正在转换mp-780295.cif
正在转换mp-780303.cif
正在转换mp-780325.cif
正在转换mp-780387.cif
正在转换mp-780486.cif
正在转换mp-780532.cif
正在转换mp-780533.cif
正在转换mp-780535.cif
正在转换mp-780538.cif
正在转换mp-780539.cif
正在转换mp-780540.cif
正在转换mp-780545.cif
正在转换mp-780560.cif
正在转换mp-780589.cif
正在转换mp-780619.cif
正在转换mp-780625.cif
正在转换mp-780633.cif
正在转换mp-780642.cif
正在转换mp-780645.cif
正在转换mp-780646.cif
正在转换mp-780647.cif
正在转换mp-780649.cif
正在转换mp-780656.cif
正在转换mp-780677.cif
正在转换mp-780722.cif
正在转换mp-780742.cif
正在转换mp-780743.cif
正在转换mp-780744.cif
正在转换mp-780746.cif
正在转换mp-780749.cif
正在转换mp-780750.cif
正在转换mp-780751.cif
正在转换mp-780753.cif
正在转换mp-780754.cif
正在转换mp-780755.cif
正在转换mp-780772.cif
正在转换mp-780782.cif
正在转换mp-780798.cif
正在转换mp-780806.cif
正在转换mp-780808.cif
正在转换mp-780810.cif
正在转换mp-780811.cif
正在转换mp-780816.cif
正在转换mp-780817.cif
正在转换mp-780818.cif
正在转换mp-780819.cif
正在转换mp-780820.cif
正在转换mp-780824.cif
正在转换mp-780825.cif
正在转换mp-780826.cif
正在转换mp-780827.cif
正在转换mp-780829.cif
正在转换mp-780831.cif
正在转换mp-780833.cif
正在转换mp-780834.cif
正在转换mp-780838.cif
正在转换mp-780856.cif
正在转换mp-780861.cif
正在转换mp-780865.cif
正在转换mp-780873.cif
正在转换mp-780876.cif
正在转换mp-780881.cif
正在转换mp-780882.cif
正在转换mp-780883.cif
正在转换mp-780888.cif
正在转换mp-780905.cif
正在转换mp-780915.cif
正在转换mp-780919.cif
正在转换mp-780922.cif
正在转换mp-780929.cif
正在转换mp-780935.cif
正在转换mp-780978.cif
正在转换mp-781010.cif
正在转换mp-781048.cif
正在转换mp-781051.cif
正在转换mp-781058.cif
正在转换mp-781059.cif
正在转换mp-781060.cif
正在转换mp-781065.cif
正在转换mp-781069.cif
正在转换mp-781080.cif
正在转换mp-781081.cif
正在转换mp-781495.cif
正在转换mp-781505.cif
正在转换mp-781507.cif
正在转换mp-781601.cif
正在转换mp-781614.cif
正在转换mp-781615.cif
正在转换mp-781625.cif
正在转换mp-781626.cif
正在转换mp-781675.cif
正在转换mp-781677.cif
正在转换mp-781686.cif
正在转换mp-781692.cif
正在转换mp-781693.cif
正在转换mp-781698.cif
正在转换mp-781706.cif
正在转换mp-781712.cif
正在转换mp-781761.cif
正在转换mp-781768.cif
正在转换mp-781958.cif
正在转换mp-781963.cif
正在转换mp-782005.cif
正在转换mp-782050.cif
正在转换mp-782664.cif
正在转换mp-782677.cif
正在转换mp-782678.cif
正在转换mp-782682.cif
正在转换mp-782685.cif
正在转换mp-782688.cif
正在转换mp-782694.cif
正在转换mp-782698.cif
正在转换mp-782714.cif
正在转换mp-782717.cif
正在转换mp-782719.cif
正在转换mp-783902.cif
正在转换mp-783906.cif
正在转换mp-784630.cif
正在转换mp-784631.cif
正在转换mp-793791.cif
正在转换mp-795616.cif
正在转换mp-849057.cif
正在转换mp-849059.cif
正在转换mp-849071.cif
正在转换mp-849081.cif
正在转换mp-849086.cif
正在转换mp-849216.cif
正在转换mp-849223.cif
正在转换mp-849232.cif
正在转换mp-849246.cif
正在转换mp-849318.cif
正在转换mp-849335.cif
正在转换mp-849359.cif
正在转换mp-849402.cif
正在转换mp-849416.cif
正在转换mp-849420.cif
正在转换mp-849435.cif
正在转换mp-849444.cif
正在转换mp-849459.cif
正在转换mp-849465.cif
正在转换mp-849504.cif
正在转换mp-849510.cif
正在转换mp-849511.cif
正在转换mp-849524.cif
正在转换mp-849525.cif
正在转换mp-849526.cif
正在转换mp-849527.cif
正在转换mp-849531.cif
正在转换mp-849533.cif
正在转换mp-849536.cif
正在转换mp-849538.cif
正在转换mp-849586.cif
正在转换mp-849587.cif
正在转换mp-849601.cif
正在转换mp-849604.cif
正在转换mp-849636.cif
正在转换mp-849669.cif
正在转换mp-849680.cif
正在转换mp-849684.cif
正在转换mp-849694.cif
正在转换mp-849695.cif
正在转换mp-849950.cif
正在转换mp-849971.cif
正在转换mp-850010.cif
正在转换mp-850055.cif
正在转换mp-850105.cif
正在转换mp-850106.cif
正在转换mp-850107.cif
正在转换mp-850109.cif
正在转换mp-850110.cif
正在转换mp-850117.cif
正在转换mp-850118.cif
正在转换mp-850121.cif
正在转换mp-850131.cif
正在转换mp-850135.cif
正在转换mp-850136.cif
正在转换mp-850139.cif
正在转换mp-850148.cif
正在转换mp-850149.cif
正在转换mp-850190.cif
正在转换mp-850213.cif
正在转换mp-850222.cif
正在转换mp-850231.cif
正在转换mp-850235.cif
正在转换mp-850247.cif
正在转换mp-850275.cif
正在转换mp-850277.cif
正在转换mp-850279.cif
正在转换mp-850280.cif
正在转换mp-850283.cif
正在转换mp-850305.cif
正在转换mp-850341.cif
正在转换mp-850357.cif
正在转换mp-850358.cif
正在转换mp-850359.cif
正在转换mp-850360.cif
正在转换mp-850361.cif
正在转换mp-850363.cif
正在转换mp-850399.cif
正在转换mp-850404.cif
正在转换mp-850422.cif
正在转换mp-850427.cif
正在转换mp-850443.cif
正在转换mp-850447.cif
正在转换mp-850468.cif
正在转换mp-850469.cif
正在转换mp-850479.cif
正在转换mp-850480.cif
正在转换mp-850481.cif
正在转换mp-850484.cif
正在转换mp-850486.cif
正在转换mp-850518.cif
正在转换mp-850529.cif
正在转换mp-850761.cif
正在转换mp-850767.cif
正在转换mp-850876.cif
正在转换mp-850878.cif
正在转换mp-850886.cif
正在转换mp-850895.cif
正在转换mp-850898.cif
正在转换mp-850901.cif
正在转换mp-850915.cif
正在转换mp-850916.cif
正在转换mp-850917.cif
正在转换mp-850922.cif
正在转换mp-850932.cif
正在转换mp-850934.cif
正在转换mp-850935.cif
正在转换mp-850936.cif
正在转换mp-850947.cif
正在转换mp-850949.cif
正在转换mp-850961.cif
正在转换mp-850964.cif
正在转换mp-850969.cif
正在转换mp-850970.cif
正在转换mp-850971.cif
正在转换mp-850973.cif
正在转换mp-850979.cif
正在转换mp-850982.cif
正在转换mp-850984.cif
正在转换mp-850986.cif
正在转换mp-850987.cif
正在转换mp-850996.cif
正在转换mp-851004.cif
正在转换mp-851009.cif
正在转换mp-851017.cif
正在转换mp-851022.cif
正在转换mp-851027.cif
正在转换mp-851028.cif
正在转换mp-851032.cif
正在转换mp-853130.cif
正在转换mp-853131.cif
正在转换mp-853134.cif
正在转换mp-853142.cif
正在转换mp-853144.cif
正在转换mp-853146.cif
正在转换mp-853150.cif
正在转换mp-853152.cif
正在转换mp-853153.cif
正在转换mp-853154.cif
正在转换mp-853155.cif
正在转换mp-853156.cif
正在转换mp-853157.cif
正在转换mp-853160.cif
正在转换mp-853161.cif
正在转换mp-853163.cif
正在转换mp-853164.cif
正在转换mp-853166.cif
正在转换mp-853167.cif
正在转换mp-853168.cif
正在转换mp-853169.cif
正在转换mp-853170.cif
正在转换mp-853174.cif
正在转换mp-853187.cif
正在转换mp-853190.cif
正在转换mp-853205.cif
正在转换mp-853206.cif
正在转换mp-853210.cif
正在转换mp-853231.cif
正在转换mp-853240.cif
正在转换mp-853248.cif
正在转换mp-853249.cif
正在转换mp-853250.cif
正在转换mp-853260.cif
正在转换mp-853264.cif
正在转换mp-861479.cif
正在转换mp-861481.cif
正在转换mp-861483.cif
正在转换mp-861497.cif
正在转换mp-861498.cif
正在转换mp-861499.cif
正在转换mp-861501.cif
正在转换mp-861503.cif
正在转换mp-861504.cif
正在转换mp-861505.cif
正在转换mp-861506.cif
正在转换mp-861507.cif
正在转换mp-861508.cif
正在转换mp-861510.cif
正在转换mp-861511.cif
正在转换mp-861512.cif
正在转换mp-861588.cif
正在转换mp-861594.cif
正在转换mp-861598.cif
正在转换mp-861600.cif
正在转换mp-861604.cif
正在转换mp-861605.cif
正在转换mp-861616.cif
正在转换mp-861619.cif
正在转换mp-861625.cif
正在转换mp-861626.cif
正在转换mp-861627.cif
正在转换mp-861628.cif
正在转换mp-861629.cif
正在转换mp-861630.cif
正在转换mp-861636.cif
正在转换mp-861637.cif
正在转换mp-761285.cif
正在转换mp-761288.cif
正在转换mp-761325.cif
正在转换mp-761341.cif
正在转换mp-761346.cif
正在转换mp-761352.cif
正在转换mp-761358.cif
正在转换mp-761361.cif
正在转换mp-761390.cif
正在转换mp-761401.cif
正在转换mp-761404.cif
正在转换mp-761415.cif
正在转换mp-761467.cif
正在转换mp-761471.cif
正在转换mp-761472.cif
正在转换mp-761481.cif
正在转换mp-761486.cif
正在转换mp-761517.cif
正在转换mp-761524.cif
正在转换mp-761526.cif
正在转换mp-761540.cif
正在转换mp-761547.cif
正在转换mp-761549.cif
正在转换mp-761552.cif
正在转换mp-761556.cif
正在转换mp-761563.cif
正在转换mp-761568.cif
正在转换mp-761572.cif
正在转换mp-761573.cif
正在转换mp-761574.cif
正在转换mp-761575.cif
正在转换mp-761589.cif
正在转换mp-761592.cif
正在转换mp-761608.cif
正在转换mp-761613.cif
正在转换mp-761615.cif
正在转换mp-761620.cif
正在转换mp-761623.cif
正在转换mp-761633.cif
正在转换mp-761634.cif
正在转换mp-761650.cif
正在转换mp-761651.cif
正在转换mp-761656.cif
正在转换mp-761669.cif
正在转换mp-761673.cif
正在转换mp-761674.cif
正在转换mp-761675.cif
正在转换mp-761676.cif
正在转换mp-761683.cif
正在转换mp-761686.cif
正在转换mp-761709.cif
正在转换mp-761710.cif
正在转换mp-761711.cif
正在转换mp-761718.cif
正在转换mp-761722.cif
正在转换mp-761729.cif
正在转换mp-761738.cif
正在转换mp-761739.cif
正在转换mp-761748.cif
正在转换mp-761752.cif
正在转换mp-761765.cif
正在转换mp-761768.cif
正在转换mp-761777.cif
正在转换mp-761782.cif
正在转换mp-761785.cif
正在转换mp-761806.cif
正在转换mp-761825.cif
正在转换mp-761827.cif
正在转换mp-761828.cif
正在转换mp-761831.cif
正在转换mp-761842.cif
正在转换mp-761872.cif
正在转换mp-761910.cif
正在转换mp-761914.cif
正在转换mp-761968.cif
正在转换mp-761982.cif
正在转换mp-761990.cif
正在转换mp-761997.cif
正在转换mp-762011.cif
正在转换mp-762012.cif
正在转换mp-762018.cif
正在转换mp-762019.cif
正在转换mp-762197.cif
正在转换mp-762218.cif
正在转换mp-762221.cif
正在转换mp-762225.cif
正在转换mp-762232.cif
正在转换mp-762236.cif
正在转换mp-762266.cif
正在转换mp-762268.cif
正在转换mp-762271.cif
正在转换mp-762276.cif
正在转换mp-762277.cif
正在转换mp-762289.cif
正在转换mp-762293.cif
正在转换mp-762304.cif
正在转换mp-762326.cif
正在转换mp-762337.cif
正在转换mp-762371.cif
正在转换mp-762399.cif
正在转换mp-762403.cif
正在转换mp-762410.cif
正在转换mp-762411.cif
正在转换mp-762412.cif
正在转换mp-762413.cif
正在转换mp-762427.cif
正在转换mp-762428.cif
正在转换mp-762454.cif
正在转换mp-762455.cif
正在转换mp-762465.cif
正在转换mp-762473.cif
正在转换mp-762484.cif
正在转换mp-762529.cif
正在转换mp-762566.cif
正在转换mp-762623.cif
正在转换mp-762631.cif
正在转换mp-762633.cif
正在转换mp-762643.cif
正在转换mp-762644.cif
正在转换mp-762687.cif

正在转换mp-762694.cif
正在转换mp-762705.cif
正在转换mp-762851.cif
正在转换mp-762854.cif
正在转换mp-762860.cif
正在转换mp-762866.cif
正在转换mp-762869.cif
正在转换mp-762870.cif
正在转换mp-762872.cif
正在转换mp-762883.cif
正在转换mp-762888.cif
正在转换mp-762894.cif
正在转换mp-762903.cif
正在转换mp-762994.cif
正在转换mp-762995.cif
正在转换mp-763007.cif
正在转换mp-763012.cif
正在转换mp-763039.cif
正在转换mp-763042.cif
正在转换mp-763043.cif
正在转换mp-763044.cif
正在转换mp-763045.cif
正在转换mp-763046.cif
正在转换mp-763049.cif
正在转换mp-763051.cif
正在转换mp-763052.cif
正在转换mp-763054.cif
正在转换mp-763056.cif
正在转换mp-763059.cif
正在转换mp-763061.cif
正在转换mp-763065.cif
正在转换mp-763070.cif
正在转换mp-763073.cif
正在转换mp-763079.cif
正在转换mp-763080.cif
正在转换mp-763090.cif
正在转换mp-763091.cif
正在转换mp-763093.cif
正在转换mp-763094.cif
正在转换mp-763095.cif
正在转换mp-763098.cif
正在转换mp-763101.cif
正在转换mp-763104.cif
正在转换mp-763106.cif
正在转换mp-763108.cif
正在转换mp-763115.cif
正在转换mp-763136.cif
正在转换mp-763137.cif
正在转换mp-763144.cif
正在转换mp-763149.cif
正在转换mp-763186.cif
正在转换mp-763196.cif
正在转换mp-763199.cif
正在转换mp-763202.cif
正在转换mp-763216.cif
正在转换mp-763229.cif
正在转换mp-763240.cif
正在转换mp-763246.cif
正在转换mp-763247.cif
正在转换mp-763252.cif
正在转换mp-763253.cif
正在转换mp-763255.cif
正在转换mp-763256.cif
正在转换mp-763262.cif
正在转换mp-763268.cif
正在转换mp-763274.cif
正在转换mp-763287.cif
正在转换mp-763290.cif
正在转换mp-763291.cif
正在转换mp-763300.cif
正在转换mp-763303.cif
正在转换mp-763313.cif
正在转换mp-763317.cif
正在转换mp-763323.cif
正在转换mp-763326.cif
正在转换mp-763329.cif
正在转换mp-763330.cif
正在转换mp-763331.cif
正在转换mp-763341.cif
正在转换mp-763343.cif
正在转换mp-763344.cif
正在转换mp-763348.cif
正在转换mp-763351.cif
正在转换mp-763353.cif
正在转换mp-763356.cif
正在转换mp-763357.cif
正在转换mp-763358.cif
正在转换mp-763359.cif
正在转换mp-763362.cif
正在转换mp-763365.cif
正在转换mp-763366.cif
正在转换mp-763367.cif
正在转换mp-763373.cif
正在转换mp-763378.cif
正在转换mp-763386.cif
正在转换mp-763387.cif
正在转换mp-763389.cif
正在转换mp-763391.cif
正在转换mp-763405.cif
正在转换mp-763409.cif
正在转换mp-763422.cif
正在转换mp-763428.cif
正在转换mp-763429.cif
正在转换mp-763430.cif
正在转换mp-763431.cif
正在转换mp-763432.cif
正在转换mp-763433.cif
正在转换mp-763434.cif
正在转换mp-763436.cif
正在转换mp-763447.cif
正在转换mp-763454.cif
正在转换mp-763469.cif
正在转换mp-763481.cif
正在转换mp-763484.cif
正在转换mp-763489.cif
正在转换mp-763491.cif
正在转换mp-763497.cif
正在转换mp-763498.cif
正在转换mp-763504.cif
正在转换mp-763507.cif
正在转换mp-763509.cif
正在转换mp-763511.cif
正在转换mp-763516.cif
正在转换mp-763517.cif
正在转换mp-763534.cif
正在转换mp-763536.cif
正在转换mp-763540.cif
正在转换mp-763541.cif
正在转换mp-763542.cif
正在转换mp-763545.cif
正在转换mp-763549.cif
正在转换mp-763551.cif
正在转换mp-763559.cif
正在转换mp-763566.cif
正在转换mp-763576.cif
正在转换mp-763577.cif
正在转换mp-763579.cif
正在转换mp-763580.cif
正在转换mp-763588.cif
正在转换mp-763592.cif
正在转换mp-763593.cif
正在转换mp-763594.cif
正在转换mp-763595.cif
正在转换mp-763597.cif
正在转换mp-763608.cif
正在转换mp-763609.cif
正在转换mp-763610.cif
正在转换mp-763618.cif
正在转换mp-763619.cif
正在转换mp-763631.cif
正在转换mp-763632.cif
正在转换mp-763633.cif
正在转换mp-763634.cif
正在转换mp-763635.cif
正在转换mp-763637.cif
正在转换mp-763640.cif
正在转换mp-763671.cif
正在转换mp-763682.cif
正在转换mp-763684.cif
正在转换mp-763687.cif
正在转换mp-763688.cif
正在转换mp-763689.cif
正在转换mp-763690.cif
正在转换mp-763691.cif
正在转换mp-763696.cif
正在转换mp-763697.cif
正在转换mp-763700.cif
正在转换mp-763702.cif
正在转换mp-763704.cif
正在转换mp-763706.cif
正在转换mp-763710.cif
正在转换mp-763711.cif
正在转换mp-763739.cif
正在转换mp-763740.cif
正在转换mp-763741.cif
正在转换mp-763744.cif
正在转换mp-763749.cif
正在转换mp-763750.cif
正在转换mp-763751.cif
正在转换mp-763753.cif
正在转换mp-763758.cif
正在转换mp-763760.cif
正在转换mp-763769.cif
正在转换mp-763778.cif
正在转换mp-763780.cif
正在转换mp-763783.cif
正在转换mp-763784.cif
正在转换mp-763785.cif
正在转换mp-763786.cif
正在转换mp-763787.cif
正在转换mp-763788.cif
正在转换mp-763792.cif
正在转换mp-763793.cif
正在转换mp-763795.cif
正在转换mp-763804.cif
正在转换mp-763816.cif
正在转换mp-763818.cif
正在转换mp-763819.cif
正在转换mp-763833.cif
正在转换mp-763842.cif
正在转换mp-763860.cif
正在转换mp-763867.cif
正在转换mp-763878.cif
正在转换mp-763883.cif
正在转换mp-763892.cif
正在转换mp-763897.cif
正在转换mp-763901.cif
正在转换mp-763902.cif
正在转换mp-763905.cif
正在转换mp-763906.cif
正在转换mp-763907.cif
正在转换mp-763908.cif
正在转换mp-763909.cif
正在转换mp-763910.cif
正在转换mp-763917.cif
正在转换mp-763921.cif
正在转换mp-763922.cif
正在转换mp-763923.cif
正在转换mp-763924.cif
正在转换mp-763927.cif
正在转换mp-763930.cif
正在转换mp-763935.cif
正在转换mp-763940.cif
正在转换mp-763945.cif
正在转换mp-763946.cif
正在转换mp-763947.cif
正在转换mp-763948.cif
正在转换mp-763950.cif
正在转换mp-763954.cif
正在转换mp-763955.cif
正在转换mp-763956.cif
正在转换mp-763961.cif
正在转换mp-763963.cif
正在转换mp-763967.cif
正在转换mp-763969.cif
正在转换mp-763970.cif
正在转换mp-763976.cif
正在转换mp-763977.cif
正在转换mp-763978.cif
正在转换mp-763982.cif
正在转换mp-763983.cif
正在转换mp-763985.cif
正在转换mp-763986.cif
正在转换mp-763987.cif
正在转换mp-763989.cif
正在转换mp-763990.cif
正在转换mp-763992.cif
正在转换mp-763994.cif
正在转换mp-763995.cif
正在转换mp-763996.cif
正在转换mp-763999.cif
正在转换mp-764000.cif
正在转换mp-764001.cif
正在转换mp-764003.cif
正在转换mp-764004.cif
正在转换mp-764007.cif
正在转换mp-764008.cif
正在转换mp-764019.cif
正在转换mp-764021.cif
正在转换mp-764022.cif
正在转换mp-764025.cif
正在转换mp-764027.cif
正在转换mp-764044.cif
正在转换mp-764046.cif
正在转换mp-764050.cif
正在转换mp-764052.cif
正在转换mp-764055.cif
正在转换mp-764060.cif
正在转换mp-764061.cif
正在转换mp-764063.cif
正在转换mp-764064.cif
正在转换mp-764090.cif
正在转换mp-764098.cif
正在转换mp-764099.cif
正在转换mp-764105.cif
正在转换mp-764130.cif
正在转换mp-764145.cif
正在转换mp-764146.cif
正在转换mp-764148.cif
正在转换mp-764154.cif
正在转换mp-764160.cif
正在转换mp-764161.cif
正在转换mp-764163.cif
正在转换mp-764170.cif
正在转换mp-764207.cif
正在转换mp-764210.cif
正在转换mp-764218.cif
正在转换mp-764220.cif
正在转换mp-764221.cif
正在转换mp-764222.cif
正在转换mp-764223.cif
正在转换mp-764225.cif
正在转换mp-764226.cif
正在转换mp-764227.cif
正在转换mp-764229.cif
正在转换mp-764231.cif
正在转换mp-764232.cif
正在转换mp-764241.cif
正在转换mp-764259.cif
正在转换mp-764275.cif
正在转换mp-764276.cif
正在转换mp-764277.cif
正在转换mp-764279.cif
正在转换mp-764280.cif
正在转换mp-764281.cif
正在转换mp-764285.cif
正在转换mp-764286.cif
正在转换mp-764287.cif
正在转换mp-764288.cif
正在转换mp-764290.cif
正在转换mp-764291.cif
正在转换mp-764292.cif
正在转换mp-764293.cif
正在转换mp-764305.cif
正在转换mp-764314.cif
正在转换mp-764316.cif
正在转换mp-764320.cif
正在转换mp-764324.cif
正在转换mp-764328.cif
正在转换mp-764332.cif
正在转换mp-764333.cif
正在转换mp-764337.cif
正在转换mp-764338.cif
正在转换mp-764339.cif
正在转换mp-764343.cif
正在转换mp-764344.cif
正在转换mp-764345.cif
正在转换mp-764347.cif
正在转换mp-764349.cif
正在转换mp-764350.cif
正在转换mp-764352.cif
正在转换mp-764353.cif
正在转换mp-764355.cif
正在转换mp-764356.cif
正在转换mp-764357.cif
正在转换mp-764360.cif
正在转换mp-764361.cif
正在转换mp-764366.cif
正在转换mp-764368.cif
正在转换mp-764371.cif
正在转换mp-764373.cif
正在转换mp-764387.cif
正在转换mp-764394.cif
正在转换mp-764397.cif
正在转换mp-764398.cif
正在转换mp-764402.cif
正在转换mp-764403.cif
正在转换mp-764407.cif
正在转换mp-764408.cif
正在转换mp-764409.cif
正在转换mp-764425.cif
正在转换mp-764426.cif
正在转换mp-764430.cif
正在转换mp-764431.cif
正在转换mp-764434.cif
正在转换mp-764448.cif
正在转换mp-764452.cif
正在转换mp-764467.cif
正在转换mp-764496.cif
正在转换mp-764509.cif
正在转换mp-764521.cif
正在转换mp-764549.cif
正在转换mp-764551.cif
正在转换mp-764555.cif
正在转换mp-764562.cif
正在转换mp-764563.cif
正在转换mp-764564.cif
正在转换mp-764565.cif
正在转换mp-764569.cif
正在转换mp-764602.cif
正在转换mp-764631.cif
正在转换mp-764632.cif
正在转换mp-764633.cif
正在转换mp-764634.cif
正在转换mp-764635.cif
正在转换mp-764638.cif
正在转换mp-764640.cif
正在转换mp-764642.cif
正在转换mp-764644.cif
正在转换mp-764648.cif
正在转换mp-764666.cif
正在转换mp-764668.cif
正在转换mp-764686.cif
正在转换mp-764689.cif
正在转换mp-764692.cif
正在转换mp-764698.cif
正在转换mp-764716.cif
正在转换mp-764728.cif
正在转换mp-764758.cif
正在转换mp-764786.cif
正在转换mp-764787.cif
正在转换mp-764788.cif
正在转换mp-764806.cif
正在转换mp-764818.cif
正在转换mp-764820.cif
正在转换mp-764821.cif
正在转换mp-764828.cif
正在转换mp-764829.cif
正在转换mp-764830.cif
正在转换mp-764831.cif
正在转换mp-764943.cif
正在转换mp-764949.cif
正在转换mp-764953.cif
正在转换mp-764954.cif
正在转换mp-764956.cif
正在转换mp-764958.cif
正在转换mp-764960.cif
正在转换mp-764961.cif
正在转换mp-764965.cif
正在转换mp-764976.cif
正在转换mp-764983.cif
正在转换mp-764999.cif
正在转换mp-765000.cif
正在转换mp-765003.cif
正在转换mp-765006.cif
正在转换mp-765028.cif
正在转换mp-765031.cif
正在转换mp-765036.cif
正在转换mp-765037.cif
正在转换mp-765039.cif
正在转换mp-765046.cif
正在转换mp-765047.cif
正在转换mp-765048.cif
正在转换mp-765049.cif
正在转换mp-765055.cif
正在转换mp-765073.cif
正在转换mp-765081.cif
正在转换mp-765125.cif
正在转换mp-765133.cif
正在转换mp-765135.cif
正在转换mp-765157.cif
正在转换mp-765182.cif
正在转换mp-765184.cif
正在转换mp-765195.cif
正在转换mp-765198.cif
正在转换mp-765233.cif
正在转换mp-765238.cif
正在转换mp-765253.cif
正在转换mp-765255.cif
正在转换mp-765256.cif
正在转换mp-765258.cif
正在转换mp-765267.cif
正在转换mp-765308.cif
正在转换mp-765309.cif
正在转换mp-765313.cif
正在转换mp-765315.cif
正在转换mp-765331.cif
正在转换mp-754262.cif
正在转换mp-754263.cif
正在转换mp-754266.cif
正在转换mp-754269.cif
正在转换mp-754282.cif
正在转换mp-754283.cif
正在转换mp-754300.cif
正在转换mp-754302.cif
正在转换mp-754307.cif
正在转换mp-754322.cif
正在转换mp-754323.cif
正在转换mp-754326.cif
正在转换mp-754327.cif
正在转换mp-754329.cif
正在转换mp-754333.cif
正在转换mp-754334.cif
正在转换mp-754344.cif
正在转换mp-754345.cif
正在转换mp-754352.cif
正在转换mp-754353.cif
正在转换mp-754354.cif
正在转换mp-754358.cif
正在转换mp-754359.cif
正在转换mp-754363.cif
正在转换mp-754364.cif
正在转换mp-754368.cif
正在转换mp-754369.cif
正在转换mp-754370.cif
正在转换mp-754375.cif
正在转换mp-754377.cif

正在转换mp-754381.cif
正在转换mp-754384.cif
正在转换mp-754401.cif
正在转换mp-754403.cif
正在转换mp-754406.cif
正在转换mp-754407.cif
正在转换mp-754409.cif
正在转换mp-754415.cif
正在转换mp-754429.cif
正在转换mp-754434.cif
正在转换mp-754435.cif
正在转换mp-754444.cif
正在转换mp-754445.cif
正在转换mp-754454.cif
正在转换mp-754455.cif
正在转换mp-754466.cif
正在转换mp-754469.cif
正在转换mp-754472.cif
正在转换mp-754474.cif
正在转换mp-754475.cif
正在转换mp-754478.cif
正在转换mp-754495.cif
正在转换mp-754501.cif
正在转换mp-754515.cif
正在转换mp-754516.cif
正在转换mp-754517.cif
正在转换mp-754519.cif
正在转换mp-754524.cif
正在转换mp-754531.cif
正在转换mp-754534.cif
正在转换mp-754537.cif
正在转换mp-754538.cif
正在转换mp-754541.cif
正在转换mp-754542.cif
正在转换mp-754545.cif
正在转换mp-754550.cif
正在转换mp-754553.cif
正在转换mp-754555.cif
正在转换mp-754556.cif
正在转换mp-754567.cif
正在转换mp-754572.cif
正在转换mp-754578.cif
正在转换mp-754586.cif
正在转换mp-754587.cif
正在转换mp-754597.cif
正在转换mp-754599.cif
正在转换mp-754604.cif
正在转换mp-754605.cif
正在转换mp-754614.cif
正在转换mp-754621.cif
正在转换mp-754624.cif
正在转换mp-754631.cif
正在转换mp-754636.cif
正在转换mp-754638.cif
正在转换mp-754640.cif
正在转换mp-754646.cif
正在转换mp-754659.cif
正在转换mp-754663.cif
正在转换mp-754664.cif
正在转换mp-754668.cif
正在转换mp-754671.cif
正在转换mp-754672.cif
正在转换mp-754673.cif
正在转换mp-754674.cif
正在转换mp-754678.cif
正在转换mp-754684.cif
正在转换mp-754693.cif
正在转换mp-754696.cif
正在转换mp-754699.cif
正在转换mp-754701.cif
正在转换mp-754710.cif
正在转换mp-754711.cif
正在转换mp-754723.cif
正在转换mp-754739.cif
正在转换mp-754741.cif
正在转换mp-754745.cif
正在转换mp-754751.cif
正在转换mp-754752.cif
正在转换mp-754757.cif
正在转换mp-754759.cif
正在转换mp-754761.cif
正在转换mp-754767.cif
正在转换mp-754768.cif
正在转换mp-754769.cif
正在转换mp-754776.cif
正在转换mp-754777.cif
正在转换mp-754779.cif
正在转换mp-754781.cif
正在转换mp-754787.cif
正在转换mp-754790.cif
正在转换mp-754796.cif
正在转换mp-754798.cif
正在转换mp-754812.cif
正在转换mp-754818.cif
正在转换mp-754823.cif
正在转换mp-754824.cif
正在转换mp-754825.cif
正在转换mp-754827.cif
正在转换mp-754833.cif
正在转换mp-754834.cif
正在转换mp-754835.cif
正在转换mp-754837.cif
正在转换mp-754839.cif
正在转换mp-754840.cif
正在转换mp-754841.cif
正在转换mp-754843.cif
正在转换mp-754844.cif
正在转换mp-754846.cif
正在转换mp-754848.cif
正在转换mp-754850.cif
正在转换mp-754852.cif
正在转换mp-754853.cif
正在转换mp-754855.cif
正在转换mp-754870.cif
正在转换mp-754875.cif
正在转换mp-754876.cif
正在转换mp-754878.cif
正在转换mp-754883.cif
正在转换mp-754885.cif
正在转换mp-754892.cif
正在转换mp-754897.cif
正在转换mp-754903.cif
正在转换mp-754912.cif
正在转换mp-754929.cif
正在转换mp-754933.cif
正在转换mp-754936.cif
正在转换mp-754937.cif
正在转换mp-754940.cif
正在转换mp-754942.cif
正在转换mp-754943.cif
正在转换mp-754954.cif
正在转换mp-754955.cif
正在转换mp-754964.cif
正在转换mp-754967.cif
正在转换mp-754978.cif
正在转换mp-754979.cif
正在转换mp-754988.cif
正在转换mp-754989.cif
正在转换mp-754991.cif
正在转换mp-754992.cif
正在转换mp-754998.cif
正在转换mp-755000.cif
正在转换mp-755001.cif
正在转换mp-755007.cif
正在转换mp-755009.cif
正在转换mp-755010.cif
正在转换mp-755013.cif
正在转换mp-755018.cif
正在转换mp-755020.cif
正在转换mp-755021.cif
正在转换mp-755026.cif
正在转换mp-755027.cif
正在转换mp-755043.cif
正在转换mp-755044.cif
正在转换mp-755046.cif
正在转换mp-755047.cif
正在转换mp-755049.cif
正在转换mp-755053.cif
正在转换mp-755054.cif
正在转换mp-755056.cif
正在转换mp-755057.cif
正在转换mp-755061.cif
正在转换mp-755066.cif
正在转换mp-755070.cif
正在转换mp-755071.cif
正在转换mp-755072.cif
正在转换mp-755074.cif
正在转换mp-755078.cif
正在转换mp-755082.cif
正在转换mp-755083.cif
正在转换mp-755084.cif
正在转换mp-755089.cif
正在转换mp-755091.cif
正在转换mp-755104.cif
正在转换mp-755107.cif
正在转换mp-755109.cif
正在转换mp-755116.cif
正在转换mp-755117.cif
正在转换mp-755121.cif
正在转换mp-755127.cif
正在转换mp-755128.cif
正在转换mp-755132.cif
正在转换mp-755137.cif
正在转换mp-755138.cif
正在转换mp-755139.cif
正在转换mp-755141.cif
正在转换mp-755144.cif
正在转换mp-755159.cif
正在转换mp-755165.cif
正在转换mp-755169.cif
正在转换mp-755175.cif
正在转换mp-755183.cif
正在转换mp-755184.cif
正在转换mp-755185.cif
正在转换mp-755210.cif
正在转换mp-755213.cif
正在转换mp-755216.cif
正在转换mp-755219.cif
正在转换mp-755225.cif
正在转换mp-755231.cif
正在转换mp-755236.cif
正在转换mp-755239.cif
正在转换mp-755243.cif
正在转换mp-755245.cif
正在转换mp-755252.cif
正在转换mp-755253.cif
正在转换mp-755256.cif
正在转换mp-755260.cif
正在转换mp-755264.cif
正在转换mp-755266.cif
正在转换mp-755277.cif
正在转换mp-755288.cif
正在转换mp-755289.cif
正在转换mp-755300.cif
正在转换mp-755302.cif
正在转换mp-755309.cif
正在转换mp-755311.cif
正在转换mp-755312.cif
正在转换mp-755313.cif
正在转换mp-755314.cif
正在转换mp-755315.cif
正在转换mp-755316.cif
正在转换mp-755318.cif
正在转换mp-755322.cif
正在转换mp-755323.cif
正在转换mp-755328.cif
正在转换mp-755333.cif
正在转换mp-755340.cif
正在转换mp-755342.cif
正在转换mp-755346.cif
正在转换mp-755347.cif
正在转换mp-755352.cif
正在转换mp-755357.cif
正在转换mp-755358.cif
正在转换mp-755362.cif
正在转换mp-755364.cif
正在转换mp-755367.cif
正在转换mp-755368.cif
正在转换mp-755374.cif
正在转换mp-755378.cif
正在转换mp-755391.cif
正在转换mp-755399.cif
正在转换mp-755413.cif
正在转换mp-755414.cif
正在转换mp-755416.cif
正在转换mp-755417.cif
正在转换mp-755419.cif
正在转换mp-755420.cif
正在转换mp-755421.cif
正在转换mp-755426.cif
正在转换mp-755449.cif
正在转换mp-755459.cif
正在转换mp-755463.cif
正在转换mp-755478.cif
正在转换mp-755480.cif
正在转换mp-755483.cif
正在转换mp-755486.cif
正在转换mp-755505.cif
正在转换mp-755543.cif
正在转换mp-755544.cif
正在转换mp-755546.cif
正在转换mp-755549.cif
正在转换mp-755552.cif
正在转换mp-755556.cif
正在转换mp-755568.cif
正在转换mp-755570.cif
正在转换mp-755574.cif
正在转换mp-755576.cif
正在转换mp-755581.cif
正在转换mp-755585.cif
正在转换mp-755588.cif
正在转换mp-755591.cif
正在转换mp-755594.cif
正在转换mp-755597.cif
正在转换mp-755609.cif
正在转换mp-755610.cif
正在转换mp-755612.cif
正在转换mp-755624.cif
正在转换mp-755634.cif
正在转换mp-755643.cif
正在转换mp-755646.cif
正在转换mp-755652.cif
正在转换mp-755658.cif
正在转换mp-755684.cif
正在转换mp-755703.cif
正在转换mp-755713.cif
正在转换mp-755716.cif
正在转换mp-755738.cif
正在转换mp-755745.cif
正在转换mp-755756.cif
正在转换mp-755759.cif
正在转换mp-755781.cif
正在转换mp-755789.cif
正在转换mp-755792.cif
正在转换mp-755804.cif
正在转换mp-755821.cif
正在转换mp-755834.cif
正在转换mp-755835.cif
正在转换mp-755853.cif
正在转换mp-755877.cif
正在转换mp-755883.cif
正在转换mp-755894.cif
正在转换mp-755895.cif
正在转换mp-755902.cif
正在转换mp-755911.cif
正在转换mp-755941.cif
正在转换mp-755959.cif
正在转换mp-755974.cif
正在转换mp-755988.cif
正在转换mp-755998.cif
正在转换mp-755999.cif
正在转换mp-756009.cif
正在转换mp-756013.cif
正在转换mp-756014.cif
正在转换mp-756018.cif
正在转换mp-756029.cif
正在转换mp-756034.cif
正在转换mp-756035.cif
正在转换mp-756044.cif
正在转换mp-756045.cif
正在转换mp-756048.cif
正在转换mp-756050.cif
正在转换mp-756063.cif
正在转换mp-756066.cif
正在转换mp-756074.cif
正在转换mp-756076.cif
正在转换mp-756084.cif
正在转换mp-756086.cif
正在转换mp-756090.cif
正在转换mp-756094.cif
正在转换mp-756096.cif
正在转换mp-756098.cif
正在转换mp-756103.cif
正在转换mp-756106.cif
正在转换mp-756117.cif
正在转换mp-756118.cif
正在转换mp-756131.cif
正在转换mp-756134.cif
正在转换mp-756135.cif
正在转换mp-756137.cif
正在转换mp-756146.cif
正在转换mp-756148.cif
正在转换mp-756152.cif
正在转换mp-756156.cif
正在转换mp-756160.cif
正在转换mp-756170.cif
正在转换mp-756173.cif
正在转换mp-756175.cif
正在转换mp-756180.cif
正在转换mp-756182.cif
正在转换mp-756190.cif
正在转换mp-756194.cif
正在转换mp-756195.cif
正在转换mp-756213.cif
正在转换mp-756214.cif
正在转换mp-756229.cif
正在转换mp-756235.cif
正在转换mp-756241.cif
正在转换mp-756245.cif
正在转换mp-756246.cif
正在转换mp-756270.cif
正在转换mp-756276.cif
正在转换mp-756277.cif
正在转换mp-756281.cif
正在转换mp-756290.cif
正在转换mp-756294.cif
正在转换mp-756297.cif
正在转换mp-756299.cif
正在转换mp-756309.cif
正在转换mp-756316.cif
正在转换mp-756317.cif
正在转换mp-756334.cif
正在转换mp-756339.cif
正在转换mp-756344.cif
正在转换mp-756347.cif
正在转换mp-756354.cif
正在转换mp-756361.cif
正在转换mp-756372.cif
正在转换mp-756374.cif
正在转换mp-756389.cif
正在转换mp-756392.cif
正在转换mp-756393.cif
正在转换mp-756394.cif
正在转换mp-756400.cif
正在转换mp-756401.cif
正在转换mp-756402.cif
正在转换mp-756406.cif
正在转换mp-756422.cif
正在转换mp-756426.cif
正在转换mp-756427.cif
正在转换mp-756431.cif
正在转换mp-756432.cif
正在转换mp-756440.cif
正在转换mp-756444.cif
正在转换mp-756452.cif
正在转换mp-756457.cif
正在转换mp-756458.cif
正在转换mp-756468.cif
正在转换mp-756477.cif
正在转换mp-756490.cif
正在转换mp-756495.cif
正在转换mp-756500.cif
正在转换mp-756515.cif
正在转换mp-756526.cif
正在转换mp-756545.cif
正在转换mp-756550.cif
正在转换mp-756553.cif
正在转换mp-756560.cif
正在转换mp-756564.cif
正在转换mp-756570.cif
正在转换mp-756580.cif
正在转换mp-756581.cif
正在转换mp-756587.cif
正在转换mp-756591.cif
正在转换mp-756598.cif
正在转换mp-756628.cif
正在转换mp-756630.cif
正在转换mp-756633.cif
正在转换mp-756638.cif
正在转换mp-756645.cif
正在转换mp-756646.cif
正在转换mp-756648.cif
正在转换mp-756655.cif
正在转换mp-756666.cif
正在转换mp-756683.cif
正在转换mp-756686.cif
正在转换mp-756919.cif
正在转换mp-756933.cif
正在转换mp-757031.cif
正在转换mp-757038.cif
正在转换mp-757045.cif
正在转换mp-757070.cif
正在转换mp-757074.cif
正在转换mp-757098.cif
正在转换mp-757100.cif
正在转换mp-757116.cif
正在转换mp-757149.cif
正在转换mp-757150.cif
正在转换mp-757162.cif
正在转换mp-757165.cif
正在转换mp-757176.cif
正在转换mp-757205.cif
正在转换mp-757219.cif
正在转换mp-757235.cif
正在转换mp-757325.cif
正在转换mp-757430.cif
正在转换mp-757450.cif
正在转换mp-757583.cif
正在转换mp-757777.cif
正在转换mp-757872.cif
正在转换mp-757905.cif
正在转换mp-757911.cif
正在转换mp-757915.cif
正在转换mp-757953.cif
正在转换mp-758052.cif
正在转换mp-758054.cif
正在转换mp-758068.cif
正在转换mp-758070.cif
正在转换mp-758089.cif
正在转换mp-758096.cif
正在转换mp-758100.cif
正在转换mp-758134.cif
正在转换mp-758179.cif

正在转换mp-758189.cif
正在转换mp-758192.cif
正在转换mp-758251.cif
正在转换mp-758259.cif
正在转换mp-758265.cif
正在转换mp-758270.cif
正在转换mp-758302.cif
正在转换mp-758320.cif
正在转换mp-758329.cif
正在转换mp-758371.cif
正在转换mp-758389.cif
正在转换mp-758415.cif
正在转换mp-758433.cif
正在转换mp-758492.cif
正在转换mp-758520.cif
正在转换mp-758523.cif
正在转换mp-758531.cif
正在转换mp-758533.cif
正在转换mp-758594.cif
正在转换mp-758662.cif
正在转换mp-758688.cif
正在转换mp-758689.cif
正在转换mp-758715.cif
正在转换mp-758720.cif
正在转换mp-758741.cif
正在转换mp-758750.cif
正在转换mp-758784.cif
正在转换mp-758836.cif
正在转换mp-758848.cif
正在转换mp-758890.cif
正在转换mp-758997.cif
正在转换mp-759066.cif
正在转换mp-759116.cif
正在转换mp-759169.cif
正在转换mp-759198.cif
正在转换mp-759207.cif
正在转换mp-759209.cif
正在转换mp-759224.cif
正在转换mp-759230.cif
正在转换mp-759287.cif
正在转换mp-759367.cif
正在转换mp-759386.cif
正在转换mp-759433.cif
正在转换mp-759541.cif
正在转换mp-759658.cif
正在转换mp-759680.cif
正在转换mp-759825.cif
正在转换mp-759876.cif
正在转换mp-759877.cif
正在转换mp-759897.cif
正在转换mp-759901.cif
正在转换mp-759939.cif
正在转换mp-760052.cif
正在转换mp-642660.cif
正在转换mp-643004.cif
正在转换mp-644092.cif
正在转换mp-644385.cif
正在转换mp-644481.cif
正在转换mp-644483.cif
正在转换mp-644494.cif
正在转换mp-644504.cif
正在转换mp-644607.cif
正在转换mp-644751.cif
正在转换mp-669913.cif
正在转换mp-669914.cif
正在转换mp-672191.cif
正在转换mp-672216.cif
正在转换mp-672221.cif
正在转换mp-672229.cif
正在转换mp-672235.cif
正在转换mp-672250.cif
正在转换mp-672257.cif
正在转换mp-672259.cif
正在转换mp-672285.cif
正在转换mp-672299.cif
正在转换mp-672337.cif
正在转换mp-672339.cif
正在转换mp-672340.cif
正在转换mp-672356.cif
正在转换mp-672368.cif
正在转换mp-672371.cif
正在转换mp-672374.cif
正在转换mp-672375.cif
正在转换mp-672385.cif
正在转换mp-672389.cif
正在转换mp-672645.cif
正在转换mp-672657.cif
正在转换mp-672661.cif
正在转换mp-672698.cif
正在转换mp-672705.cif
正在转换mp-672953.cif
正在转换mp-673165.cif
正在转换mp-673244.cif
正在转换mp-673247.cif
正在转换mp-673252.cif
正在转换mp-673633.cif
正在转换mp-673658.cif
正在转换mp-673673.cif
正在转换mp-673682.cif
正在转换mp-673798.cif
正在转换mp-673808.cif
正在转换mp-673824.cif
正在转换mp-673874.cif
正在转换mp-673875.cif
正在转换mp-674310.cif
正在转换mp-674333.cif
正在转换mp-674355.cif
正在转换mp-674382.cif
正在转换mp-674459.cif
正在转换mp-674463.cif
正在转换mp-674478.cif
正在转换mp-674493.cif
正在转换mp-674508.cif
正在转换mp-674514.cif
正在转换mp-674531.cif
正在转换mp-674783.cif
正在转换mp-674804.cif
正在转换mp-674842.cif
正在转换mp-674849.cif
正在转换mp-674858.cif
正在转换mp-674944.cif
正在转换mp-674981.cif
正在转换mp-675025.cif
正在转换mp-675067.cif
正在转换mp-675078.cif
正在转换mp-675083.cif
正在转换mp-675100.cif
正在转换mp-675104.cif
正在转换mp-675106.cif
正在转换mp-675120.cif
正在转换mp-675124.cif
正在转换mp-675127.cif
正在转换mp-675142.cif
正在转换mp-675146.cif
正在转换mp-675163.cif
正在转换mp-675172.cif
正在转换mp-675179.cif
正在转换mp-675180.cif
正在转换mp-675199.cif
正在转换mp-675209.cif
正在转换mp-675244.cif
正在转换mp-675252.cif
正在转换mp-675271.cif
正在转换mp-675283.cif
正在转换mp-675286.cif
正在转换mp-675293.cif
正在转换mp-675349.cif
正在转换mp-675374.cif
正在转换mp-675406.cif
正在转换mp-675433.cif
正在转换mp-675445.cif
正在转换mp-675460.cif
正在转换mp-675462.cif
正在转换mp-675464.cif
正在转换mp-675488.cif
正在转换mp-675511.cif
正在转换mp-675546.cif
正在转换mp-675553.cif
正在转换mp-675555.cif
正在转换mp-675568.cif
正在转换mp-675569.cif
正在转换mp-675570.cif
正在转换mp-675576.cif
正在转换mp-675577.cif
正在转换mp-675601.cif
正在转换mp-675606.cif
正在转换mp-675628.cif
正在转换mp-675634.cif
正在转换mp-675638.cif
正在转换mp-675644.cif
正在转换mp-675645.cif
正在转换mp-675647.cif
正在转换mp-675650.cif
正在转换mp-675651.cif
正在转换mp-675668.cif
正在转换mp-675677.cif
正在转换mp-675682.cif
正在转换mp-675700.cif
正在转换mp-675701.cif
正在转换mp-675748.cif
正在转换mp-675784.cif
正在转换mp-675798.cif
正在转换mp-675857.cif
正在转换mp-675879.cif
正在转换mp-675892.cif
正在转换mp-675902.cif
正在转换mp-675912.cif
正在转换mp-675930.cif
正在转换mp-676020.cif
正在转换mp-676036.cif
正在转换mp-676058.cif
正在转换mp-676113.cif
正在转换mp-676144.cif
正在转换mp-676154.cif
正在转换mp-676227.cif
正在转换mp-676247.cif
正在转换mp-676249.cif
正在转换mp-676270.cif
正在转换mp-676278.cif
正在转换mp-676310.cif
正在转换mp-676311.cif
正在转换mp-676319.cif
正在转换mp-676333.cif
正在转换mp-676338.cif
正在转换mp-676360.cif
正在转换mp-676370.cif
正在转换mp-676398.cif
正在转换mp-676400.cif
正在转换mp-676410.cif
正在转换mp-676414.cif
正在转换mp-676464.cif
正在转换mp-676483.cif
正在转换mp-676489.cif
正在转换mp-676512.cif
正在转换mp-676540.cif
正在转换mp-676553.cif
正在转换mp-676561.cif
正在转换mp-676562.cif
正在转换mp-676586.cif
正在转换mp-676643.cif
正在转换mp-676650.cif
正在转换mp-676673.cif
正在转换mp-676779.cif
正在转换mp-676851.cif
正在转换mp-676861.cif
正在转换mp-676893.cif
正在转换mp-677010.cif
正在转换mp-677028.cif
正在转换mp-677039.cif
正在转换mp-677072.cif
正在转换mp-677093.cif
正在转换mp-677103.cif
正在转换mp-677162.cif
正在转换mp-677164.cif
正在转换mp-677193.cif
正在转换mp-677237.cif
正在转换mp-677241.cif
正在转换mp-677242.cif
正在转换mp-677335.cif
正在转换mp-677445.cif
正在转换mp-677526.cif
正在转换mp-677732.cif
正在转换mp-679669.cif
正在转换mp-680842.cif
正在转换mp-682067.cif
正在转换mp-684580.cif
正在转换mp-684602.cif
正在转换mp-684609.cif
正在转换mp-684652.cif
正在转换mp-684653.cif
正在转换mp-684654.cif
正在转换mp-684668.cif
正在转换mp-684675.cif
正在转换mp-684704.cif
正在转换mp-684768.cif
正在转换mp-684799.cif
正在转换mp-684903.cif
正在转换mp-684904.cif
正在转换mp-685002.cif
正在转换mp-685022.cif
正在转换mp-685066.cif
正在转换mp-685097.cif
正在转换mp-685148.cif
正在转换mp-685150.cif
正在转换mp-685606.cif
正在转换mp-685991.cif
正在转换mp-685999.cif
正在转换mp-686050.cif
正在转换mp-690475.cif
正在转换mp-690490.cif
正在转换mp-690495.cif
正在转换mp-690504.cif
正在转换mp-690539.cif
正在转换mp-690542.cif
正在转换mp-690617.cif
正在转换mp-690635.cif
正在转换mp-690653.cif
正在转换mp-690684.cif
正在转换mp-690733.cif
正在转换mp-690760.cif
正在转换mp-690789.cif
正在转换mp-690799.cif
正在转换mp-690817.cif
正在转换mp-690866.cif
正在转换mp-691106.cif
正在转换mp-691107.cif
正在转换mp-691145.cif
正在转换mp-691164.cif
正在转换mp-694537.cif
正在转换mp-694855.cif
正在转换mp-694890.cif
正在转换mp-694957.cif
正在转换mp-695170.cif
正在转换mp-695365.cif
正在转换mp-695817.cif
正在转换mp-695829.cif
正在转换mp-695998.cif
正在转换mp-696174.cif
正在转换mp-696175.cif
正在转换mp-696231.cif
正在转换mp-696275.cif
正在转换mp-696288.cif
正在转换mp-696329.cif
正在转换mp-696347.cif
正在转换mp-696353.cif
正在转换mp-696384.cif
正在转换mp-696396.cif
正在转换mp-696470.cif
正在转换mp-696529.cif
正在转换mp-696572.cif
正在转换mp-696618.cif
正在转换mp-696673.cif
正在转换mp-696701.cif
正在转换mp-696736.cif
正在转换mp-696746.cif
正在转换mp-696752.cif
正在转换mp-696804.cif
正在转换mp-696805.cif
正在转换mp-696806.cif
正在转换mp-696842.cif
正在转换mp-696845.cif
正在转换mp-696853.cif
正在转换mp-696867.cif
正在转换mp-696878.cif
正在转换mp-696969.cif
正在转换mp-696983.cif
正在转换mp-697047.cif
正在转换mp-697068.cif
正在转换mp-697084.cif
正在转换mp-697085.cif
正在转换mp-697111.cif
正在转换mp-697126.cif
正在转换mp-697135.cif
正在转换mp-697136.cif
正在转换mp-697139.cif
正在转换mp-697144.cif
正在转换mp-697146.cif
正在转换mp-697168.cif
正在转换mp-697179.cif
正在转换mp-697236.cif
正在转换mp-697263.cif
正在转换mp-697331.cif
正在转换mp-697575.cif
正在转换mp-699136.cif
正在转换mp-699248.cif
正在转换mp-699343.cif
正在转换mp-703260.cif
正在转换mp-703470.cif
正在转换mp-704674.cif
正在转换mp-704745.cif
正在转换mp-705675.cif
正在转换mp-705785.cif
正在转换mp-706272.cif
正在转换mp-714880.cif
正在转换mp-714885.cif
正在转换mp-714896.cif
正在转换mp-714904.cif
正在转换mp-714969.cif
正在转换mp-715262.cif
正在转换mp-715469.cif
正在转换mp-715482.cif
正在转换mp-715488.cif
正在转换mp-715514.cif
正在转换mp-715550.cif
正在转换mp-715581.cif
正在转换mp-715590.cif
正在转换mp-715923.cif
正在转换mp-722243.cif
正在转换mp-722278.cif
正在转换mp-722515.cif
正在转换mp-722516.cif
正在转换mp-722684.cif
正在转换mp-722860.cif
正在转换mp-722912.cif
正在转换mp-722913.cif
正在转换mp-733858.cif
正在转换mp-735523.cif
正在转换mp-735529.cif
正在转换mp-741706.cif
正在转换mp-743557.cif
正在转换mp-743629.cif
正在转换mp-743660.cif
正在转换mp-743731.cif
正在转换mp-743752.cif
正在转换mp-743794.cif
正在转换mp-743839.cif
正在转换mp-743840.cif
正在转换mp-743841.cif
正在转换mp-743876.cif
正在转换mp-743878.cif
正在转换mp-745101.cif
正在转换mp-752393.cif
正在转换mp-752394.cif
正在转换mp-752396.cif
正在转换mp-752397.cif
正在转换mp-752398.cif
正在转换mp-752400.cif
正在转换mp-752401.cif
正在转换mp-752404.cif
正在转换mp-752407.cif
正在转换mp-752411.cif
正在转换mp-752413.cif
正在转换mp-752415.cif
正在转换mp-752423.cif
正在转换mp-752424.cif
正在转换mp-752426.cif
正在转换mp-752429.cif
正在转换mp-752435.cif
正在转换mp-752437.cif
正在转换mp-752442.cif
正在转换mp-752446.cif
正在转换mp-752451.cif
正在转换mp-752460.cif
正在转换mp-752463.cif
正在转换mp-752467.cif
正在转换mp-752473.cif
正在转换mp-752477.cif
正在转换mp-752483.cif
正在转换mp-752484.cif
正在转换mp-752496.cif
正在转换mp-752501.cif
正在转换mp-752512.cif
正在转换mp-752515.cif
正在转换mp-752535.cif
正在转换mp-752537.cif
正在转换mp-752538.cif
正在转换mp-752546.cif
正在转换mp-752549.cif
正在转换mp-752561.cif
正在转换mp-752580.cif
正在转换mp-752581.cif
正在转换mp-752605.cif
正在转换mp-752606.cif
正在转换mp-752636.cif
正在转换mp-752641.cif
正在转换mp-752643.cif
正在转换mp-752645.cif
正在转换mp-752648.cif
正在转换mp-752669.cif
正在转换mp-752670.cif
正在转换mp-752672.cif
正在转换mp-752675.cif
正在转换mp-752676.cif
正在转换mp-752677.cif
正在转换mp-752684.cif
正在转换mp-752686.cif
正在转换mp-752689.cif
正在转换mp-752691.cif
正在转换mp-752692.cif
正在转换mp-752695.cif
正在转换mp-752724.cif
正在转换mp-752725.cif
正在转换mp-752733.cif
正在转换mp-752735.cif
正在转换mp-752755.cif
正在转换mp-752767.cif
正在转换mp-752768.cif
正在转换mp-752773.cif
正在转换mp-752783.cif
正在转换mp-752793.cif
正在转换mp-752798.cif
正在转换mp-752826.cif
正在转换mp-752827.cif
正在转换mp-752840.cif
正在转换mp-752843.cif
正在转换mp-752849.cif
正在转换mp-752851.cif
正在转换mp-752858.cif
正在转换mp-752878.cif
正在转换mp-752879.cif
正在转换mp-752882.cif
正在转换mp-752888.cif
正在转换mp-752895.cif
正在转换mp-752898.cif
正在转换mp-752910.cif
正在转换mp-752922.cif
正在转换mp-752924.cif
正在转换mp-752926.cif
正在转换mp-752930.cif
正在转换mp-752933.cif
正在转换mp-752943.cif
正在转换mp-752947.cif
正在转换mp-752948.cif
正在转换mp-752953.cif
正在转换mp-752959.cif
正在转换mp-752983.cif
正在转换mp-752989.cif
正在转换mp-752998.cif
正在转换mp-753000.cif
正在转换mp-753009.cif
正在转换mp-753031.cif
正在转换mp-753048.cif
正在转换mp-753054.cif
正在转换mp-753055.cif
正在转换mp-753056.cif
正在转换mp-753063.cif
正在转换mp-753081.cif
正在转换mp-753089.cif
正在转换mp-753098.cif
正在转换mp-753123.cif
正在转换mp-753124.cif
正在转换mp-753130.cif
正在转换mp-753131.cif
正在转换mp-753139.cif
正在转换mp-753160.cif
正在转换mp-753162.cif

正在转换mp-753164.cif
正在转换mp-753171.cif
正在转换mp-753175.cif
正在转换mp-753176.cif
正在转换mp-753179.cif
正在转换mp-753183.cif
正在转换mp-753192.cif
正在转换mp-753195.cif
正在转换mp-753197.cif
正在转换mp-753202.cif
正在转换mp-753209.cif
正在转换mp-753216.cif
正在转换mp-753226.cif
正在转换mp-753257.cif
正在转换mp-753260.cif
正在转换mp-753268.cif
正在转换mp-753277.cif
正在转换mp-753279.cif
正在转换mp-753285.cif
正在转换mp-753287.cif
正在转换mp-753298.cif
正在转换mp-753306.cif
正在转换mp-753309.cif
正在转换mp-753315.cif
正在转换mp-753316.cif
正在转换mp-753318.cif
正在转换mp-753326.cif
正在转换mp-753327.cif
正在转换mp-753345.cif
正在转换mp-753353.cif
正在转换mp-753360.cif
正在转换mp-753371.cif
正在转换mp-753378.cif
正在转换mp-753384.cif
正在转换mp-753385.cif
正在转换mp-753387.cif
正在转换mp-753388.cif
正在转换mp-753397.cif
正在转换mp-753401.cif
正在转换mp-753405.cif
正在转换mp-753414.cif
正在转换mp-753416.cif
正在转换mp-753418.cif
正在转换mp-753425.cif
正在转换mp-753443.cif
正在转换mp-753456.cif
正在转换mp-753459.cif
正在转换mp-753460.cif
正在转换mp-753472.cif
正在转换mp-753478.cif
正在转换mp-753486.cif
正在转换mp-753493.cif
正在转换mp-753495.cif
正在转换mp-753506.cif
正在转换mp-753508.cif
正在转换mp-753510.cif
正在转换mp-753511.cif
正在转换mp-753539.cif
正在转换mp-753541.cif
正在转换mp-753544.cif
正在转换mp-753555.cif
正在转换mp-753557.cif
正在转换mp-753581.cif
正在转换mp-753600.cif
正在转换mp-753605.cif
正在转换mp-753610.cif
正在转换mp-753619.cif
正在转换mp-753621.cif
正在转换mp-753632.cif
正在转换mp-753654.cif
正在转换mp-753656.cif
正在转换mp-753657.cif
正在转换mp-753662.cif
正在转换mp-753663.cif
正在转换mp-753669.cif
正在转换mp-753670.cif
正在转换mp-753671.cif
正在转换mp-753673.cif
正在转换mp-753677.cif
正在转换mp-753683.cif
正在转换mp-753690.cif
正在转换mp-753691.cif
正在转换mp-753692.cif
正在转换mp-753693.cif
正在转换mp-753708.cif
正在转换mp-753709.cif
正在转换mp-753711.cif
正在转换mp-753714.cif
正在转换mp-753716.cif
正在转换mp-753719.cif
正在转换mp-753720.cif
正在转换mp-753726.cif
正在转换mp-753731.cif
正在转换mp-753737.cif
正在转换mp-753741.cif
正在转换mp-753747.cif
正在转换mp-753751.cif
正在转换mp-753766.cif
正在转换mp-753774.cif
正在转换mp-753775.cif
正在转换mp-753776.cif
正在转换mp-753783.cif
正在转换mp-753785.cif
正在转换mp-753793.cif
正在转换mp-753794.cif
正在转换mp-753795.cif
正在转换mp-753798.cif
正在转换mp-753802.cif
正在转换mp-753806.cif
正在转换mp-753809.cif
正在转换mp-753813.cif
正在转换mp-753815.cif
正在转换mp-753816.cif
正在转换mp-753821.cif
正在转换mp-753823.cif
正在转换mp-753826.cif
正在转换mp-753830.cif
正在转换mp-753832.cif
正在转换mp-753833.cif
正在转换mp-753842.cif
正在转换mp-753846.cif
正在转换mp-753863.cif
正在转换mp-753864.cif
正在转换mp-753868.cif
正在转换mp-753879.cif
正在转换mp-753881.cif
正在转换mp-753890.cif
正在转换mp-753891.cif
正在转换mp-753901.cif
正在转换mp-753905.cif
正在转换mp-753912.cif
正在转换mp-753917.cif
正在转换mp-753920.cif
正在转换mp-753940.cif
正在转换mp-753943.cif
正在转换mp-753946.cif
正在转换mp-753947.cif
正在转换mp-753948.cif
正在转换mp-753954.cif
正在转换mp-753960.cif
正在转换mp-753982.cif
正在转换mp-753983.cif
正在转换mp-753990.cif
正在转换mp-753995.cif
正在转换mp-754004.cif
正在转换mp-754009.cif
正在转换mp-754010.cif
正在转换mp-754011.cif
正在转换mp-754019.cif
正在转换mp-754021.cif
正在转换mp-754027.cif
正在转换mp-754040.cif
正在转换mp-754043.cif
正在转换mp-754044.cif
正在转换mp-754046.cif
正在转换mp-754047.cif
正在转换mp-754058.cif
正在转换mp-754064.cif
正在转换mp-754071.cif
正在转换mp-754073.cif
正在转换mp-754086.cif
正在转换mp-754092.cif
正在转换mp-754107.cif
正在转换mp-754109.cif
正在转换mp-754110.cif
正在转换mp-754114.cif
正在转换mp-754117.cif
正在转换mp-754118.cif
正在转换mp-754120.cif
正在转换mp-754125.cif
正在转换mp-754126.cif
正在转换mp-754128.cif
正在转换mp-754134.cif
正在转换mp-754140.cif
正在转换mp-754146.cif
正在转换mp-754152.cif
正在转换mp-754153.cif
正在转换mp-754157.cif
正在转换mp-754158.cif
正在转换mp-754161.cif
正在转换mp-754165.cif
正在转换mp-754174.cif
正在转换mp-754184.cif
正在转换mp-754185.cif
正在转换mp-754192.cif
正在转换mp-754196.cif
正在转换mp-754199.cif
正在转换mp-754203.cif
正在转换mp-754206.cif
正在转换mp-754212.cif
正在转换mp-754213.cif
正在转换mp-754218.cif
正在转换mp-754220.cif
正在转换mp-754223.cif
正在转换mp-754224.cif
正在转换mp-754225.cif
正在转换mp-754226.cif
正在转换mp-754227.cif
正在转换mp-754231.cif
正在转换mp-754236.cif
正在转换mp-754237.cif
正在转换mp-754238.cif
正在转换mp-754239.cif
正在转换mp-754240.cif
正在转换mp-754249.cif
正在转换mp-754250.cif
正在转换mp-584134.cif
正在转换mp-600001.cif
正在转换mp-603251.cif
正在转换mp-603907.cif
正在转换mp-604647.cif
正在转换mp-605060.cif
正在转换mp-605437.cif
正在转换mp-607139.cif
正在转换mp-607223.cif
正在转换mp-607225.cif
正在转换mp-607291.cif
正在转换mp-607371.cif
正在转换mp-607409.cif
正在转换mp-607450.cif
正在转换mp-607475.cif
正在转换mp-607712.cif
正在转换mp-607829.cif
正在转换mp-608014.cif
正在转换mp-608156.cif
正在转换mp-608348.cif
正在转换mp-608885.cif
正在转换mp-612946.cif
正在转换mp-613172.cif
正在转换mp-613306.cif
正在转换mp-613327.cif
正在转换mp-613402.cif
正在转换mp-613442.cif
正在转换mp-613523.cif
正在转换mp-613612.cif
正在转换mp-613839.cif
正在转换mp-614005.cif
正在转换mp-614383.cif
正在转换mp-614444.cif
正在转换mp-614565.cif
正在转换mp-614777.cif
正在转换mp-614918.cif
正在转换mp-615141.cif
正在转换mp-615152.cif
正在转换mp-615173.cif
正在转换mp-615314.cif
正在转换mp-615746.cif
正在转换mp-615821.cif
正在转换mp-616019.cif
正在转换mp-616026.cif
正在转换mp-616166.cif
正在转换mp-616185.cif
正在转换mp-616461.cif
正在转换mp-616541.cif
正在转换mp-616544.cif
正在转换mp-616564.cif
正在转换mp-616575.cif
正在转换mp-616607.cif
正在转换mp-616668.cif
正在转换mp-617312.cif
正在转换mp-617543.cif
正在转换mp-619456.cif
正在转换mp-619802.cif
正在转换mp-620069.cif
正在转换mp-620290.cif
正在转换mp-620364.cif
正在转换mp-620372.cif
正在转换mp-620571.cif
正在转换mp-620652.cif
正在转换mp-620812.cif
正在转换mp-620862.cif
正在转换mp-621131.cif
正在转换mp-621132.cif
正在转换mp-621176.cif
正在转换mp-621182.cif
正在转换mp-621348.cif
正在转换mp-621362.cif
正在转换mp-621592.cif
正在转换mp-621612.cif
正在转换mp-621624.cif
正在转换mp-621925.cif
正在转换mp-621964.cif
正在转换mp-622041.cif
正在转换mp-622107.cif
正在转换mp-622126.cif
正在转换mp-622268.cif
正在转换mp-622501.cif
正在转换mp-622565.cif
正在转换mp-622570.cif
正在转换mp-622621.cif
正在转换mp-622636.cif
正在转换mp-622980.cif
正在转换mp-622990.cif
正在转换mp-623006.cif
正在转换mp-623024.cif
正在转换mp-623089.cif
正在转换mp-623134.cif
正在转换mp-623453.cif
正在转换mp-623646.cif
正在转换mp-623751.cif
正在转换mp-624191.cif
正在转换mp-624688.cif
正在转换mp-624739.cif
正在转换mp-625051.cif
正在转换mp-625052.cif
正在转换mp-625094.cif
正在转换mp-625152.cif
正在转换mp-625211.cif
正在转换mp-625233.cif
正在转换mp-625257.cif
正在转换mp-625268.cif
正在转换mp-625269.cif
正在转换mp-625314.cif
正在转换mp-625359.cif
正在转换mp-625367.cif
正在转换mp-625370.cif
正在转换mp-625377.cif
正在转换mp-625392.cif
正在转换mp-625397.cif
正在转换mp-625402.cif
正在转换mp-625403.cif
正在转换mp-625404.cif
正在转换mp-625409.cif
正在转换mp-625414.cif
正在转换mp-625415.cif
正在转换mp-625416.cif
正在转换mp-625445.cif
正在转换mp-625447.cif
正在转换mp-625452.cif
正在转换mp-625465.cif
正在转换mp-625468.cif
正在转换mp-625472.cif
正在转换mp-625475.cif
正在转换mp-625509.cif
正在转换mp-625521.cif
正在转换mp-625530.cif
正在转换mp-625551.cif
正在转换mp-625555.cif
正在转换mp-625560.cif
正在转换mp-625583.cif
正在转换mp-625600.cif
正在转换mp-625619.cif
正在转换mp-625621.cif
正在转换mp-625628.cif
正在转换mp-625663.cif
正在转换mp-625677.cif
正在转换mp-625678.cif
正在转换mp-625711.cif
正在转换mp-625718.cif
正在转换mp-625723.cif
正在转换mp-625735.cif
正在转换mp-625751.cif
正在转换mp-625784.cif
正在转换mp-625809.cif
正在转换mp-625812.cif
正在转换mp-625821.cif
正在转换mp-625823.cif
正在转换mp-625826.cif
正在转换mp-625830.cif
正在转换mp-625832.cif
正在转换mp-625836.cif
正在转换mp-625837.cif
正在转换mp-625857.cif
正在转换mp-625871.cif
正在转换mp-625873.cif
正在转换mp-625886.cif
正在转换mp-625888.cif
正在转换mp-625909.cif
正在转换mp-625915.cif
正在转换mp-625917.cif
正在转换mp-625920.cif
正在转换mp-625924.cif
正在转换mp-625941.cif
正在转换mp-625957.cif
正在转换mp-625959.cif
正在转换mp-625964.cif
正在转换mp-625993.cif
正在转换mp-625996.cif
正在转换mp-625998.cif
正在转换mp-626000.cif
正在转换mp-626012.cif
正在转换mp-626062.cif
正在转换mp-626075.cif
正在转换mp-626113.cif
正在转换mp-626114.cif
正在转换mp-626149.cif
正在转换mp-626151.cif
正在转换mp-626161.cif
正在转换mp-626173.cif
正在转换mp-626182.cif
正在转换mp-626193.cif
正在转换mp-626194.cif
正在转换mp-626218.cif
正在转换mp-626303.cif
正在转换mp-626314.cif
正在转换mp-626361.cif
正在转换mp-626369.cif
正在转换mp-626421.cif
正在转换mp-626423.cif
正在转换mp-626429.cif
正在转换mp-626503.cif
正在转换mp-626506.cif
正在转换mp-626528.cif
正在转换mp-626534.cif
正在转换mp-626577.cif
正在转换mp-626582.cif
正在转换mp-626586.cif
正在转换mp-626607.cif
正在转换mp-626620.cif
正在转换mp-626643.cif
正在转换mp-626644.cif
正在转换mp-626664.cif
正在转换mp-626703.cif
正在转换mp-626716.cif
正在转换mp-626720.cif
正在转换mp-626721.cif
正在转换mp-626726.cif
正在转换mp-626727.cif
正在转换mp-626729.cif
正在转换mp-626735.cif
正在转换mp-626750.cif
正在转换mp-626755.cif
正在转换mp-626778.cif
正在转换mp-626785.cif
正在转换mp-626787.cif
正在转换mp-626791.cif
正在转换mp-626796.cif
正在转换mp-626876.cif
正在转换mp-626878.cif
正在转换mp-627439.cif
正在转换mp-628568.cif
正在转换mp-628583.cif
正在转换mp-628599.cif
正在转换mp-628606.cif
正在转换mp-628616.cif
正在转换mp-628643.cif
正在转换mp-628705.cif
正在转换mp-628726.cif
正在转换mp-628842.cif
正在转换mp-628859.cif
正在转换mp-629397.cif
正在转换mp-629458.cif
正在转换mp-629701.cif
正在转换mp-630511.cif
正在转换mp-630528.cif
正在转换mp-630641.cif
正在转换mp-630976.cif
正在转换mp-631254.cif
正在转换mp-631255.cif
正在转换mp-631256.cif
正在转换mp-631257.cif
正在转换mp-631267.cif
正在转换mp-631269.cif
正在转换mp-631270.cif
正在转换mp-631274.cif
正在转换mp-631277.cif
正在转换mp-631280.cif
正在转换mp-631288.cif
正在转换mp-631293.cif
正在转换mp-631294.cif
正在转换mp-631296.cif
正在转换mp-631299.cif
正在转换mp-631301.cif
正在转换mp-631302.cif
正在转换mp-631303.cif
正在转换mp-631304.cif
正在转换mp-631305.cif
正在转换mp-631308.cif
正在转换mp-631309.cif
正在转换mp-631310.cif
正在转换mp-631311.cif
正在转换mp-631312.cif
正在转换mp-631313.cif
正在转换mp-631314.cif
正在转换mp-631316.cif
正在转换mp-631317.cif
正在转换mp-631318.cif
正在转换mp-631319.cif
正在转换mp-631320.cif
正在转换mp-631322.cif
正在转换mp-631323.cif
正在转换mp-631324.cif
正在转换mp-631325.cif
正在转换mp-631329.cif
正在转换mp-631330.cif
正在转换mp-631333.cif
正在转换mp-631334.cif
正在转换mp-631335.cif
正在转换mp-631337.cif
正在转换mp-631338.cif
正在转换mp-631339.cif
正在转换mp-631342.cif
正在转换mp-631344.cif
正在转换mp-631345.cif
正在转换mp-631346.cif
正在转换mp-631349.cif
正在转换mp-631352.cif
正在转换mp-631353.cif
正在转换mp-631354.cif
正在转换mp-631355.cif
正在转换mp-631356.cif
正在转换mp-631358.cif
正在转换mp-631361.cif
正在转换mp-631362.cif
正在转换mp-631364.cif
正在转换mp-631365.cif
正在转换mp-631366.cif
正在转换mp-631368.cif
正在转换mp-631371.cif
正在转换mp-631373.cif
正在转换mp-631374.cif

正在转换mp-631375.cif
正在转换mp-631376.cif
正在转换mp-631379.cif
正在转换mp-631381.cif
正在转换mp-631382.cif
正在转换mp-631383.cif
正在转换mp-631384.cif
正在转换mp-631386.cif
正在转换mp-631387.cif
正在转换mp-631388.cif
正在转换mp-631389.cif
正在转换mp-631390.cif
正在转换mp-631392.cif
正在转换mp-631394.cif
正在转换mp-631395.cif
正在转换mp-631396.cif
正在转换mp-631398.cif
正在转换mp-631399.cif
正在转换mp-631403.cif
正在转换mp-631404.cif
正在转换mp-631405.cif
正在转换mp-631406.cif
正在转换mp-631409.cif
正在转换mp-631410.cif
正在转换mp-631411.cif
正在转换mp-631412.cif
正在转换mp-631417.cif
正在转换mp-631418.cif
正在转换mp-631420.cif
正在转换mp-631421.cif
正在转换mp-631422.cif
正在转换mp-631423.cif
正在转换mp-631424.cif
正在转换mp-631425.cif
正在转换mp-631427.cif
正在转换mp-631428.cif
正在转换mp-631429.cif
正在转换mp-631431.cif
正在转换mp-631435.cif
正在转换mp-631436.cif
正在转换mp-631440.cif
正在转换mp-631441.cif
正在转换mp-631442.cif
正在转换mp-631449.cif
正在转换mp-631450.cif
正在转换mp-631451.cif
正在转换mp-631452.cif
正在转换mp-631455.cif
正在转换mp-631458.cif
正在转换mp-631462.cif
正在转换mp-631463.cif
正在转换mp-631464.cif
正在转换mp-631465.cif
正在转换mp-631466.cif
正在转换mp-631467.cif
正在转换mp-631468.cif
正在转换mp-631471.cif
正在转换mp-631472.cif
正在转换mp-631473.cif
正在转换mp-631474.cif
正在转换mp-631475.cif
正在转换mp-631478.cif
正在转换mp-631479.cif
正在转换mp-631480.cif
正在转换mp-631481.cif
正在转换mp-631482.cif
正在转换mp-631484.cif
正在转换mp-631487.cif
正在转换mp-631488.cif
正在转换mp-631489.cif
正在转换mp-631491.cif
正在转换mp-631492.cif
正在转换mp-631494.cif
正在转换mp-631495.cif
正在转换mp-631496.cif
正在转换mp-631497.cif
正在转换mp-631498.cif
正在转换mp-631500.cif
正在转换mp-631502.cif
正在转换mp-631503.cif
正在转换mp-631504.cif
正在转换mp-631505.cif
正在转换mp-631507.cif
正在转换mp-631508.cif
正在转换mp-631509.cif
正在转换mp-631510.cif
正在转换mp-631511.cif
正在转换mp-631512.cif
正在转换mp-631513.cif
正在转换mp-631514.cif
正在转换mp-631515.cif
正在转换mp-631516.cif
正在转换mp-631517.cif
正在转换mp-631518.cif
正在转换mp-631519.cif
正在转换mp-631520.cif
正在转换mp-631521.cif
正在转换mp-631523.cif
正在转换mp-631524.cif
正在转换mp-631525.cif
正在转换mp-631526.cif
正在转换mp-631527.cif
正在转换mp-631528.cif
正在转换mp-631529.cif
正在转换mp-631530.cif
正在转换mp-631531.cif
正在转换mp-631532.cif
正在转换mp-631535.cif
正在转换mp-631536.cif
正在转换mp-631537.cif
正在转换mp-631538.cif
正在转换mp-631539.cif
正在转换mp-631540.cif
正在转换mp-631541.cif
正在转换mp-631542.cif
正在转换mp-631543.cif
正在转换mp-631544.cif
正在转换mp-631545.cif
正在转换mp-631546.cif
正在转换mp-631547.cif
正在转换mp-631548.cif
正在转换mp-631549.cif
正在转换mp-631550.cif
正在转换mp-631551.cif
正在转换mp-631552.cif
正在转换mp-631553.cif
正在转换mp-631554.cif
正在转换mp-631555.cif
正在转换mp-631556.cif
正在转换mp-631557.cif
正在转换mp-631558.cif
正在转换mp-631559.cif
正在转换mp-631560.cif
正在转换mp-631561.cif
正在转换mp-631562.cif
正在转换mp-631563.cif
正在转换mp-631564.cif
正在转换mp-631565.cif
正在转换mp-631566.cif
正在转换mp-631567.cif
正在转换mp-631568.cif
正在转换mp-631569.cif
正在转换mp-631570.cif
正在转换mp-631571.cif
正在转换mp-631572.cif
正在转换mp-631573.cif
正在转换mp-631574.cif
正在转换mp-631575.cif
正在转换mp-631576.cif
正在转换mp-631577.cif
正在转换mp-631578.cif
正在转换mp-631580.cif
正在转换mp-631581.cif
正在转换mp-631582.cif
正在转换mp-631586.cif
正在转换mp-631592.cif
正在转换mp-631619.cif
正在转换mp-631633.cif
正在转换mp-631635.cif
正在转换mp-631637.cif
正在转换mp-631661.cif
正在转换mp-631694.cif
正在转换mp-631696.cif
正在转换mp-631754.cif
正在转换mp-631880.cif
正在转换mp-631895.cif
正在转换mp-631946.cif
正在转换mp-632219.cif
正在转换mp-632229.cif
正在转换mp-632282.cif
正在转换mp-632311.cif
正在转换mp-632348.cif
正在转换mp-632394.cif
正在转换mp-632402.cif
正在转换mp-632417.cif
正在转换mp-632442.cif
正在转换mp-632480.cif
正在转换mp-632491.cif
正在转换mp-632532.cif
正在转换mp-632539.cif
正在转换mp-632573.cif
正在转换mp-632656.cif
正在转换mp-632667.cif
正在转换mp-632672.cif
正在转换mp-632684.cif
正在转换mp-632694.cif
正在转换mp-632711.cif
正在转换mp-632734.cif
正在转换mp-632760.cif
正在转换mp-632808.cif
正在转换mp-632812.cif
正在转换mp-633099.cif
正在转换mp-633158.cif
正在转换mp-633442.cif
正在转换mp-634101.cif
正在转换mp-634105.cif
正在转换mp-634113.cif
正在转换mp-634326.cif
正在转换mp-634381.cif
正在转换mp-634410.cif
正在转换mp-634418.cif
正在转换mp-634429.cif
正在转换mp-634431.cif
正在转换mp-634434.cif
正在转换mp-634657.cif
正在转换mp-634676.cif
正在转换mp-634706.cif
正在转换mp-634751.cif
正在转换mp-634805.cif
正在转换mp-634812.cif
正在转换mp-634817.cif
正在转换mp-634855.cif
正在转换mp-634867.cif
正在转换mp-634896.cif
正在转换mp-634930.cif
正在转换mp-634965.cif
正在转换mp-634979.cif
正在转换mp-635327.cif
正在转换mp-635393.cif
正在转换mp-635425.cif
正在转换mp-635460.cif
正在转换mp-635469.cif
正在转换mp-635471.cif
正在转换mp-635713.cif
正在转换mp-636056.cif
正在转换mp-636095.cif
正在转换mp-636212.cif
正在转换mp-636232.cif
正在转换mp-636240.cif
正在转换mp-636273.cif
正在转换mp-636320.cif
正在转换mp-636328.cif
正在转换mp-636331.cif
正在转换mp-636359.cif
正在转换mp-636368.cif
正在转换mp-636461.cif
正在转换mp-636498.cif
正在转换mp-636519.cif
正在转换mp-636565.cif
正在转换mp-636599.cif
正在转换mp-636614.cif
正在转换mp-636698.cif
正在转换mp-636731.cif
正在转换mp-636813.cif
正在转换mp-636921.cif
正在转换mp-637179.cif
正在转换mp-637575.cif
正在转换mp-637576.cif
正在转换mp-637771.cif
正在转换mp-638018.cif
正在转换mp-638035.cif
正在转换mp-638061.cif
正在转换mp-638406.cif
正在转换mp-638632.cif
正在转换mp-639402.cif
正在转换mp-639445.cif
正在转换mp-639463.cif
正在转换mp-639659.cif
正在转换mp-639756.cif
正在转换mp-639876.cif
正在转换mp-639910.cif
正在转换mp-640024.cif
正在转换mp-640039.cif
正在转换mp-640053.cif
正在转换mp-640073.cif
正在转换mp-640075.cif
正在转换mp-640080.cif
正在转换mp-640147.cif
正在转换mp-640372.cif
正在转换mp-640391.cif
正在转换mp-640444.cif
正在转换mp-640553.cif
正在转换mp-640614.cif
正在转换mp-640807.cif
正在转换mp-640827.cif
正在转换mp-640890.cif
正在转换mp-640917.cif
正在转换mp-641069.cif
正在转换mp-641365.cif
正在转换mp-641367.cif
正在转换mp-641534.cif
正在转换mp-641539.cif
正在转换mp-641541.cif
正在转换mp-641564.cif
正在转换mp-641651.cif
正在转换mp-641918.cif
正在转换mp-641924.cif
正在转换mp-642190.cif
正在转换mp-642363.cif
正在转换mp-642426.cif
正在转换mp-642493.cif
正在转换mp-642644.cif
正在转换mp-642646.cif
正在转换mp-642648.cif
正在转换mp-642649.cif
正在转换mp-642650.cif
正在转换mp-642653.cif
正在转换mp-642654.cif
正在转换mp-642659.cif
正在转换mp-642662.cif
正在转换mp-642725.cif
正在转换mp-642731.cif
正在转换mp-642735.cif
正在转换mp-642736.cif
正在转换mp-642737.cif
正在转换mp-642779.cif
正在转换mp-642783.cif
正在转换mp-642787.cif
正在转换mp-642804.cif
正在转换mp-642817.cif
正在转换mp-642821.cif
正在转换mp-642822.cif
正在转换mp-642823.cif
正在转换mp-642824.cif
正在转换mp-642831.cif
正在转换mp-642834.cif
正在转换mp-642844.cif
正在转换mp-642845.cif
正在转换mp-642847.cif
正在转换mp-642991.cif
正在转换mp-642996.cif
正在转换mp-642999.cif
正在转换mp-643001.cif
正在转换mp-643002.cif
正在转换mp-643009.cif
正在转换mp-643022.cif
正在转换mp-643023.cif
正在转换mp-643026.cif
正在转换mp-643033.cif
正在转换mp-643036.cif
正在转换mp-643043.cif
正在转换mp-643047.cif
正在转换mp-643061.cif
正在转换mp-643062.cif
正在转换mp-643066.cif
正在转换mp-643069.cif
正在转换mp-643070.cif
正在转换mp-643108.cif
正在转换mp-643246.cif
正在转换mp-643248.cif
正在转换mp-643259.cif
正在转换mp-643260.cif
正在转换mp-643263.cif
正在转换mp-643264.cif
正在转换mp-643270.cif
正在转换mp-643273.cif
正在转换mp-643279.cif
正在转换mp-643346.cif
正在转换mp-643385.cif
正在转换mp-643392.cif
正在转换mp-643394.cif
正在转换mp-643397.cif
正在转换mp-643427.cif
正在转换mp-643431.cif
正在转换mp-643570.cif
正在转换mp-643791.cif
正在转换mp-644003.cif
正在转换mp-645135.cif
正在转换mp-645159.cif
正在转换mp-645218.cif
正在转换mp-645246.cif
正在转换mp-645295.cif
正在转换mp-645300.cif
正在转换mp-645317.cif
正在转换mp-645418.cif
正在转换mp-645435.cif
正在转换mp-645593.cif
正在转换mp-646426.cif
正在转换mp-646507.cif
正在转换mp-646821.cif
正在转换mp-647164.cif
正在转换mp-647226.cif
正在转换mp-647374.cif
正在转换mp-647452.cif
正在转换mp-647999.cif
正在转换mp-649595.cif
正在转换mp-650727.cif
正在转换mp-654956.cif
正在转换mp-655275.cif
正在转换mp-655360.cif
正在转换mp-655631.cif
正在转换mp-566321.cif
正在转换mp-566323.cif
正在转换mp-566329.cif
正在转换mp-566335.cif
正在转换mp-566337.cif
正在转换mp-566356.cif
正在转换mp-566373.cif
正在转换mp-566404.cif
正在转换mp-566408.cif
正在转换mp-566412.cif
正在转换mp-566425.cif
正在转换mp-566457.cif
正在转换mp-566459.cif
正在转换mp-566460.cif
正在转换mp-566468.cif
正在转换mp-566472.cif
正在转换mp-566483.cif
正在转换mp-566496.cif
正在转换mp-566504.cif
正在转换mp-566513.cif
正在转换mp-566521.cif
正在转换mp-566537.cif
正在转换mp-566574.cif
正在转换mp-566588.cif
正在转换mp-566608.cif
正在转换mp-566636.cif
正在转换mp-566680.cif
正在转换mp-566692.cif
正在转换mp-566693.cif
正在转换mp-566698.cif
正在转换mp-566706.cif
正在转换mp-566749.cif
正在转换mp-566788.cif
正在转换mp-566801.cif
正在转换mp-566811.cif
正在转换mp-566823.cif
正在转换mp-566829.cif
正在转换mp-566848.cif
正在转换mp-566864.cif
正在转换mp-566869.cif
正在转换mp-566886.cif
正在转换mp-566892.cif
正在转换mp-566907.cif
正在转换mp-566925.cif
正在转换mp-566952.cif
正在转换mp-566999.cif
正在转换mp-567037.cif
正在转换mp-567046.cif
正在转换mp-567052.cif
正在转换mp-567057.cif
正在转换mp-567076.cif
正在转换mp-567082.cif
正在转换mp-567084.cif
正在转换mp-567089.cif
正在转换mp-567093.cif
正在转换mp-567097.cif
正在转换mp-567114.cif
正在转换mp-567116.cif
正在转换mp-567125.cif
正在转换mp-567130.cif
正在转换mp-567141.cif
正在转换mp-567164.cif
正在转换mp-567167.cif
正在转换mp-567177.cif
正在转换mp-567191.cif
正在转换mp-567197.cif
正在转换mp-567200.cif
正在转换mp-567203.cif
正在转换mp-567205.cif
正在转换mp-567207.cif
正在转换mp-567210.cif
正在转换mp-567214.cif
正在转换mp-567219.cif
正在转换mp-567220.cif
正在转换mp-567228.cif
正在转换mp-567229.cif
正在转换mp-567240.cif
正在转换mp-567243.cif
正在转换mp-567244.cif
正在转换mp-567248.cif
正在转换mp-567262.cif
正在转换mp-567271.cif

正在转换mp-567276.cif
正在转换mp-567278.cif
正在转换mp-567299.cif
正在转换mp-567305.cif
正在转换mp-567318.cif
正在转换mp-567325.cif
正在转换mp-567338.cif
正在转换mp-567341.cif
正在转换mp-567347.cif
正在转换mp-567348.cif
正在转换mp-567353.cif
正在转换mp-567362.cif
正在转换mp-567369.cif
正在转换mp-567371.cif
正在转换mp-567375.cif
正在转换mp-567389.cif
正在转换mp-567394.cif
正在转换mp-567397.cif
正在转换mp-567406.cif
正在转换mp-567408.cif
正在转换mp-567412.cif
正在转换mp-567413.cif
正在转换mp-567416.cif
正在转换mp-567418.cif
正在转换mp-567427.cif
正在转换mp-567428.cif
正在转换mp-567429.cif
正在转换mp-567431.cif
正在转换mp-567435.cif
正在转换mp-567447.cif
正在转换mp-567454.cif
正在转换mp-567456.cif
正在转换mp-567457.cif
正在转换mp-567458.cif
正在转换mp-567465.cif
正在转换mp-567474.cif
正在转换mp-567479.cif
正在转换mp-567480.cif
正在转换mp-567484.cif
正在转换mp-567510.cif
正在转换mp-567513.cif
正在转换mp-567515.cif
正在转换mp-567517.cif
正在转换mp-567530.cif
正在转换mp-567538.cif
正在转换mp-567545.cif
正在转换mp-567566.cif
正在转换mp-567573.cif
正在转换mp-567574.cif
正在转换mp-567580.cif
正在转换mp-567584.cif
正在转换mp-567589.cif
正在转换mp-567590.cif
正在转换mp-567598.cif
正在转换mp-567600.cif
正在转换mp-567602.cif
正在转换mp-567612.cif
正在转换mp-567614.cif
正在转换mp-567626.cif
正在转换mp-567628.cif
正在转换mp-567636.cif
正在转换mp-567644.cif
正在转换mp-567650.cif
正在转换mp-567653.cif
正在转换mp-567655.cif
正在转换mp-567657.cif
正在转换mp-567658.cif
正在转换mp-567666.cif
正在转换mp-567677.cif
正在转换mp-567678.cif
正在转换mp-567679.cif
正在转换mp-567680.cif
正在转换mp-567703.cif
正在转换mp-567705.cif
正在转换mp-567712.cif
正在转换mp-567723.cif
正在转换mp-567727.cif
正在转换mp-567730.cif
正在转换mp-567735.cif
正在转换mp-567736.cif
正在转换mp-567744.cif
正在转换mp-567749.cif
正在转换mp-567767.cif
正在转换mp-567768.cif
正在转换mp-567769.cif
正在转换mp-567771.cif
正在转换mp-567780.cif
正在转换mp-567787.cif
正在转换mp-567807.cif
正在转换mp-567808.cif
正在转换mp-567818.cif
正在转换mp-567830.cif
正在转换mp-567836.cif
正在转换mp-567840.cif
正在转换mp-567849.cif
正在转换mp-567856.cif
正在转换mp-567859.cif
正在转换mp-567871.cif
正在转换mp-567872.cif
正在转换mp-567883.cif
正在转换mp-567891.cif
正在转换mp-567903.cif
正在转换mp-567909.cif
正在转换mp-567920.cif
正在转换mp-567925.cif
正在转换mp-567933.cif
正在转换mp-567944.cif
正在转换mp-567948.cif
正在转换mp-567969.cif
正在转换mp-567974.cif
正在转换mp-567978.cif
正在转换mp-567981.cif
正在转换mp-567996.cif
正在转换mp-567997.cif
正在转换mp-568006.cif
正在转换mp-568014.cif
正在转换mp-568021.cif
正在转换mp-568042.cif
正在转换mp-568050.cif
正在转换mp-568055.cif
正在转换mp-568058.cif
正在转换mp-568059.cif
正在转换mp-568062.cif
正在转换mp-568066.cif
正在转换mp-568069.cif
正在转换mp-568075.cif
正在转换mp-568077.cif
正在转换mp-568095.cif
正在转换mp-568098.cif
正在转换mp-568113.cif
正在转换mp-568116.cif
正在转换mp-568139.cif
正在转换mp-568143.cif
正在转换mp-568155.cif
正在转换mp-568161.cif
正在转换mp-568170.cif
正在转换mp-568171.cif
正在转换mp-568182.cif
正在转换mp-568191.cif
正在转换mp-568244.cif
正在转换mp-568266.cif
正在转换mp-568273.cif
正在转换mp-568284.cif
正在转换mp-568293.cif
正在转换mp-568320.cif
正在转换mp-568333.cif
正在转换mp-568337.cif
正在转换mp-568382.cif
正在转换mp-568384.cif
正在转换mp-568398.cif
正在转换mp-568441.cif
正在转换mp-568466.cif
正在转换mp-568505.cif
正在转换mp-568516.cif
正在转换mp-569313.cif
正在转换mp-569317.cif
正在转换mp-569319.cif
正在转换mp-569320.cif
正在转换mp-569321.cif
正在转换mp-569322.cif
正在转换mp-569333.cif
正在转换mp-569334.cif
正在转换mp-569335.cif
正在转换mp-569341.cif
正在转换mp-569343.cif
正在转换mp-569344.cif
正在转换mp-569346.cif
正在转换mp-569352.cif
正在转换mp-569366.cif
正在转换mp-569376.cif
正在转换mp-569380.cif
正在转换mp-569382.cif
正在转换mp-569385.cif
正在转换mp-569396.cif
正在转换mp-569402.cif
正在转换mp-569404.cif
正在转换mp-569408.cif
正在转换mp-569410.cif
正在转换mp-569413.cif
正在转换mp-569424.cif
正在转换mp-569426.cif
正在转换mp-569440.cif
正在转换mp-569442.cif
正在转换mp-569446.cif
正在转换mp-569450.cif
正在转换mp-569458.cif
正在转换mp-569471.cif
正在转换mp-569482.cif
正在转换mp-569494.cif
正在转换mp-569496.cif
正在转换mp-569501.cif
正在转换mp-569507.cif
正在转换mp-569508.cif
正在转换mp-569511.cif
正在转换mp-569516.cif
正在转换mp-569526.cif
正在转换mp-569529.cif
正在转换mp-569535.cif
正在转换mp-569557.cif
正在转换mp-569564.cif
正在转换mp-569568.cif
正在转换mp-569571.cif
正在转换mp-569577.cif
正在转换mp-569590.cif
正在转换mp-569593.cif
正在转换mp-569597.cif
正在转换mp-569600.cif
正在转换mp-569601.cif
正在转换mp-569605.cif
正在转换mp-569607.cif
正在转换mp-569613.cif
正在转换mp-569617.cif
正在转换mp-569624.cif
正在转换mp-569630.cif
正在转换mp-569639.cif
正在转换mp-569640.cif
正在转换mp-569650.cif
正在转换mp-569653.cif
正在转换mp-569657.cif
正在转换mp-569661.cif
正在转换mp-569668.cif
正在转换mp-569671.cif
正在转换mp-569673.cif
正在转换mp-569675.cif
正在转换mp-569677.cif
正在转换mp-569683.cif
正在转换mp-569685.cif
正在转换mp-569697.cif
正在转换mp-569698.cif
正在转换mp-569724.cif
正在转换mp-569737.cif
正在转换mp-569744.cif
正在转换mp-569745.cif
正在转换mp-569748.cif
正在转换mp-569752.cif
正在转换mp-569753.cif
正在转换mp-569760.cif
正在转换mp-569768.cif
正在转换mp-569775.cif
正在转换mp-569785.cif
正在转换mp-569788.cif
正在转换mp-569790.cif
正在转换mp-569792.cif
正在转换mp-569802.cif
正在转换mp-569803.cif
正在转换mp-569807.cif
正在转换mp-569812.cif
正在转换mp-569815.cif
正在转换mp-569823.cif
正在转换mp-569833.cif
正在转换mp-569834.cif
正在转换mp-569837.cif
正在转换mp-569848.cif
正在转换mp-569850.cif
正在转换mp-569857.cif
正在转换mp-569858.cif
正在转换mp-569859.cif
正在转换mp-569860.cif
正在转换mp-569867.cif
正在转换mp-569871.cif
正在转换mp-569875.cif
正在转换mp-569876.cif
正在转换mp-569877.cif
正在转换mp-569881.cif
正在转换mp-569898.cif
正在转换mp-569912.cif
正在转换mp-569915.cif
正在转换mp-569916.cif
正在转换mp-569927.cif
正在转换mp-569931.cif
正在转换mp-569933.cif
正在转换mp-569939.cif
正在转换mp-569940.cif
正在转换mp-569943.cif
正在转换mp-569952.cif
正在转换mp-569974.cif
正在转换mp-569978.cif
正在转换mp-569981.cif
正在转换mp-570014.cif
正在转换mp-570018.cif
正在转换mp-570050.cif
正在转换mp-570051.cif
正在转换mp-570173.cif
正在转换mp-570179.cif
正在转换mp-570180.cif
正在转换mp-570181.cif
正在转换mp-570183.cif
正在转换mp-570187.cif
正在转换mp-570198.cif
正在转换mp-570199.cif
正在转换mp-570203.cif
正在转换mp-570205.cif
正在转换mp-570216.cif
正在转换mp-570217.cif
正在转换mp-570226.cif
正在转换mp-570229.cif
正在转换mp-570232.cif
正在转换mp-570236.cif
正在转换mp-570238.cif
正在转换mp-570245.cif
正在转换mp-570255.cif
正在转换mp-570258.cif
正在转换mp-570276.cif
正在转换mp-570290.cif
正在转换mp-570291.cif
正在转换mp-570301.cif
正在转换mp-570334.cif
正在转换mp-570339.cif
正在转换mp-570354.cif
正在转换mp-570377.cif
正在转换mp-570388.cif
正在转换mp-570399.cif
正在转换mp-570404.cif
正在转换mp-570409.cif
正在转换mp-570412.cif
正在转换mp-570428.cif
正在转换mp-570430.cif
正在转换mp-570431.cif
正在转换mp-570436.cif
正在转换mp-570450.cif
正在转换mp-570454.cif
正在转换mp-570457.cif
正在转换mp-570463.cif
正在转换mp-570466.cif
正在转换mp-570482.cif
正在转换mp-570483.cif
正在转换mp-570485.cif
正在转换mp-570491.cif
正在转换mp-570514.cif
正在转换mp-570528.cif
正在转换mp-570543.cif
正在转换mp-570549.cif
正在转换mp-570554.cif
正在转换mp-570558.cif
正在转换mp-570561.cif
正在转换mp-570578.cif
正在转换mp-570590.cif
正在转换mp-570592.cif
正在转换mp-570595.cif
正在转换mp-570604.cif
正在转换mp-570606.cif
正在转换mp-570611.cif
正在转换mp-570615.cif
正在转换mp-570631.cif
正在转换mp-570632.cif
正在转换mp-570637.cif
正在转换mp-570657.cif
正在转换mp-570661.cif
正在转换mp-570666.cif
正在转换mp-570670.cif
正在转换mp-570673.cif
正在转换mp-570677.cif
正在转换mp-570680.cif
正在转换mp-570683.cif
正在转换mp-570687.cif
正在转换mp-570691.cif
正在转换mp-570697.cif
正在转换mp-570698.cif
正在转换mp-570707.cif
正在转换mp-570708.cif
正在转换mp-570713.cif
正在转换mp-570744.cif
正在转换mp-570749.cif
正在转换mp-570751.cif
正在转换mp-570759.cif
正在转换mp-570761.cif
正在转换mp-570768.cif
正在转换mp-570769.cif
正在转换mp-570771.cif
正在转换mp-570774.cif
正在转换mp-570775.cif
正在转换mp-570779.cif
正在转换mp-570784.cif
正在转换mp-570786.cif
正在转换mp-570800.cif
正在转换mp-570811.cif
正在转换mp-570816.cif
正在转换mp-570822.cif
正在转换mp-570826.cif
正在转换mp-570831.cif
正在转换mp-570832.cif
正在转换mp-570835.cif
正在转换mp-570843.cif
正在转换mp-570844.cif
正在转换mp-570847.cif
正在转换mp-570853.cif
正在转换mp-570855.cif
正在转换mp-570858.cif
正在转换mp-570860.cif
正在转换mp-570863.cif
正在转换mp-570867.cif
正在转换mp-570870.cif
正在转换mp-570875.cif
正在转换mp-570887.cif
正在转换mp-570890.cif
正在转换mp-570891.cif
正在转换mp-570896.cif
正在转换mp-570899.cif
正在转换mp-570901.cif
正在转换mp-570904.cif
正在转换mp-570907.cif
正在转换mp-570910.cif
正在转换mp-570912.cif
正在转换mp-570923.cif
正在转换mp-570928.cif
正在转换mp-570931.cif
正在转换mp-570934.cif
正在转换mp-570935.cif
正在转换mp-570938.cif
正在转换mp-570948.cif
正在转换mp-570950.cif
正在转换mp-570959.cif
正在转换mp-570960.cif
正在转换mp-570961.cif
正在转换mp-570963.cif
正在转换mp-570971.cif
正在转换mp-570972.cif
正在转换mp-570991.cif
正在转换mp-570998.cif
正在转换mp-571000.cif
正在转换mp-571008.cif
正在转换mp-571016.cif
正在转换mp-571030.cif
正在转换mp-571039.cif
正在转换mp-571041.cif
正在转换mp-571044.cif
正在转换mp-571053.cif
正在转换mp-571059.cif
正在转换mp-571071.cif
正在转换mp-571075.cif
正在转换mp-571079.cif
正在转换mp-571084.cif
正在转换mp-571085.cif
正在转换mp-571090.cif
正在转换mp-571093.cif
正在转换mp-571098.cif
正在转换mp-571102.cif
正在转换mp-571107.cif
正在转换mp-571109.cif
正在转换mp-571126.cif
正在转换mp-571143.cif
正在转换mp-571144.cif
正在转换mp-571147.cif
正在转换mp-571156.cif
正在转换mp-571160.cif
正在转换mp-571162.cif
正在转换mp-571163.cif
正在转换mp-571172.cif
正在转换mp-571180.cif
正在转换mp-571183.cif
正在转换mp-571185.cif
正在转换mp-571188.cif
正在转换mp-571195.cif
正在转换mp-571203.cif
正在转换mp-571208.cif
正在转换mp-571211.cif
正在转换mp-571212.cif
正在转换mp-571216.cif
正在转换mp-571224.cif

正在转换mp-571230.cif
正在转换mp-571232.cif
正在转换mp-571233.cif
正在转换mp-571247.cif
正在转换mp-571262.cif
正在转换mp-571263.cif
正在转换mp-571271.cif
正在转换mp-571281.cif
正在转换mp-571288.cif
正在转换mp-571292.cif
正在转换mp-571296.cif
正在转换mp-571302.cif
正在转换mp-571306.cif
正在转换mp-571310.cif
正在转换mp-571314.cif
正在转换mp-571315.cif
正在转换mp-571322.cif
正在转换mp-571330.cif
正在转换mp-571331.cif
正在转换mp-571333.cif
正在转换mp-571334.cif
正在转换mp-571335.cif
正在转换mp-571339.cif
正在转换mp-571342.cif
正在转换mp-571347.cif
正在转换mp-571350.cif
正在转换mp-571352.cif
正在转换mp-571353.cif
正在转换mp-571363.cif
正在转换mp-571365.cif
正在转换mp-571367.cif
正在转换mp-571370.cif
正在转换mp-571376.cif
正在转换mp-571382.cif
正在转换mp-571384.cif
正在转换mp-571386.cif
正在转换mp-571387.cif
正在转换mp-571400.cif
正在转换mp-571402.cif
正在转换mp-571405.cif
正在转换mp-571407.cif
正在转换mp-571414.cif
正在转换mp-571418.cif
正在转换mp-571420.cif
正在转换mp-571425.cif
正在转换mp-571428.cif
正在转换mp-571433.cif
正在转换mp-571438.cif
正在转换mp-571440.cif
正在转换mp-571443.cif
正在转换mp-571453.cif
正在转换mp-571454.cif
正在转换mp-571457.cif
正在转换mp-571458.cif
正在转换mp-571468.cif
正在转换mp-571474.cif
正在转换mp-571484.cif
正在转换mp-571485.cif
正在转换mp-571491.cif
正在转换mp-571493.cif
正在转换mp-571495.cif
正在转换mp-571499.cif
正在转换mp-571500.cif
正在转换mp-571505.cif
正在转换mp-571506.cif
正在转换mp-571509.cif
正在转换mp-571512.cif
正在转换mp-571513.cif
正在转换mp-571537.cif
正在转换mp-571542.cif
正在转换mp-571544.cif
正在转换mp-571552.cif
正在转换mp-571554.cif
正在转换mp-571557.cif
正在转换mp-571561.cif
正在转换mp-571566.cif
正在转换mp-571581.cif
正在转换mp-571584.cif
正在转换mp-571586.cif
正在转换mp-571587.cif
正在转换mp-571589.cif
正在转换mp-571599.cif
正在转换mp-571606.cif
正在转换mp-571608.cif
正在转换mp-571609.cif
正在转换mp-571619.cif
正在转换mp-571622.cif
正在转换mp-571623.cif
正在转换mp-571624.cif
正在转换mp-571627.cif
正在转换mp-573677.cif
正在转换mp-574122.cif
正在转换mp-574199.cif
正在转换mp-574235.cif
正在转换mp-574239.cif
正在转换mp-574244.cif
正在转换mp-574279.cif
正在转换mp-574424.cif
正在转换mp-574438.cif
正在转换mp-574822.cif
正在转换mp-578601.cif
正在转换mp-578606.cif
正在转换mp-578615.cif
正在转换mp-578618.cif
正在转换mp-578619.cif
正在转换mp-579086.cif
正在转换mp-579496.cif
正在转换mp-579677.cif
正在转换mp-579718.cif
正在转换mp-580136.cif
正在转换mp-580140.cif
正在转换mp-580215.cif
正在转换mp-580234.cif
正在转换mp-580287.cif
正在转换mp-580329.cif
正在转换mp-580357.cif
正在转换mp-580364.cif
正在转换mp-580439.cif
正在转换mp-581143.cif
正在转换mp-581276.cif
正在转换mp-581281.cif
正在转换mp-581303.cif
正在转换mp-581471.cif
正在转换mp-581600.cif
正在转换mp-581665.cif
正在转换mp-581707.cif
正在转换mp-581712.cif
正在转换mp-581747.cif
正在转换mp-581760.cif
正在转换mp-581805.cif
正在转换mp-581833.cif
正在转换mp-581857.cif
正在转换mp-581934.cif
正在转换mp-581941.cif
正在转换mp-581968.cif
正在转换mp-582011.cif
正在转换mp-582028.cif
正在转换mp-582119.cif
正在转换mp-582142.cif
正在转换mp-582259.cif
正在转换mp-582278.cif
正在转换mp-582293.cif
正在转换mp-582295.cif
正在转换mp-1078.cif
正在转换mp-1084.cif
正在转换mp-1111.cif
正在转换mp-1301.cif
正在转换mp-1344.cif
正在转换mp-1449.cif
正在转换mp-1455.cif
正在转换mp-1465.cif
正在转换mp-1478.cif
正在转换mp-1589.cif
正在转换mp-1627.cif
正在转换mp-1695.cif
正在转换mp-1739.cif
正在转换mp-1746.cif
正在转换mp-174.cif
正在转换mp-1794.cif
正在转换mp-1919.cif
正在转换mp-1938.cif
正在转换mp-1988.cif
正在转换mp-2034.cif
正在转换mp-2038.cif
正在转换mp-2045.cif
正在转换mp-2064.cif
正在转换mp-2118.cif
正在转换mp-2124.cif
正在转换mp-2127.cif
正在转换mp-2164.cif
正在转换mp-2204.cif
正在转换mp-2280.cif
正在转换mp-2330.cif
正在转换mp-2332.cif
正在转换mp-2361.cif
正在转换mp-2365.cif
正在转换mp-2378.cif
正在转换mp-2451.cif
正在转换mp-2617.cif
正在转换mp-261.cif
正在转换mp-2649.cif
正在转换mp-2653.cif
正在转换mp-2656.cif
正在转换mp-2729.cif
正在转换mp-2885.cif
正在转换mp-2910.cif
正在转换mp-2939.cif
正在转换mp-2945.cif
正在转换mp-2959.cif
正在转换mp-3017.cif
正在转换mp-3043.cif
正在转换mp-3082.cif
正在转换mp-3103.cif
正在转换mp-3408.cif
正在转换mp-3417.cif
正在转换mp-3430.cif
正在转换mp-3463.cif
正在转换mp-3487.cif
正在转换mp-3501.cif
正在转换mp-3547.cif
正在转换mp-3597.cif
正在转换mp-3615.cif
正在转换mp-3663.cif
正在转换mp-367.cif
正在转换mp-3689.cif
正在转换mp-369.cif
正在转换mp-3792.cif
正在转换mp-3861.cif
正在转换mp-3867.cif
正在转换mp-3896.cif
正在转换mp-3941.cif
正在转换mp-3955.cif
正在转换mp-4051.cif
正在转换mp-4100.cif
正在转换mp-4169.cif
正在转换mp-4227.cif
正在转换mp-4362.cif
正在转换mp-4434.cif
正在转换mp-4693.cif
正在转换mp-4788.cif
正在转换mp-488.cif
正在转换mp-4891.cif
正在转换mp-4950.cif
正在转换mp-4967.cif
正在转换mp-496.cif
正在转换mp-5104.cif
正在转换mp-5131.cif
正在转换mp-5178.cif
正在转换mp-5259.cif
正在转换mp-5267.cif
正在转换mp-5331.cif
正在转换mp-5336.cif
正在转换mp-534.cif
正在转换mp-5364.cif
正在转换mp-5368.cif
正在转换mp-5447.cif
正在转换mp-5457.cif
正在转换mp-5468.cif
正在转换mp-5540.cif
正在转换mp-5544.cif
正在转换mp-5547.cif
正在转换mp-5566.cif
正在转换mp-5568.cif
正在转换mp-558155.cif
正在转换mp-558163.cif
正在转换mp-558189.cif
正在转换mp-558200.cif
正在转换mp-558228.cif
正在转换mp-558231.cif
正在转换mp-558273.cif
正在转换mp-558285.cif
正在转换mp-558314.cif
正在转换mp-558325.cif
正在转换mp-558336.cif
正在转换mp-558366.cif
正在转换mp-558368.cif
正在转换mp-558382.cif
正在转换mp-558383.cif
正在转换mp-558411.cif
正在转换mp-558412.cif
正在转换mp-558418.cif
正在转换mp-558434.cif
正在转换mp-558435.cif
正在转换mp-558446.cif
正在转换mp-558460.cif
正在转换mp-558494.cif
正在转换mp-5584.cif
正在转换mp-558507.cif
正在转换mp-558518.cif
正在转换mp-558533.cif
正在转换mp-558538.cif
正在转换mp-558573.cif
正在转换mp-558579.cif
正在转换mp-558580.cif
正在转换mp-558595.cif
正在转换mp-558597.cif
正在转换mp-558632.cif
正在转换mp-558636.cif
正在转换mp-558658.cif
正在转换mp-558689.cif
正在转换mp-558690.cif
正在转换mp-558696.cif
正在转换mp-558708.cif
正在转换mp-558712.cif
正在转换mp-558713.cif
正在转换mp-558718.cif
正在转换mp-558733.cif
正在转换mp-558748.cif
正在转换mp-558762.cif
正在转换mp-558811.cif
正在转换mp-558817.cif
正在转换mp-558819.cif
正在转换mp-558828.cif
正在转换mp-558831.cif
正在转换mp-558843.cif
正在转换mp-558849.cif
正在转换mp-558896.cif
正在转换mp-558960.cif
正在转换mp-559044.cif
正在转换mp-559092.cif
正在转换mp-559117.cif
正在转换mp-559146.cif
正在转换mp-559175.cif
正在转换mp-559208.cif
正在转换mp-559263.cif
正在转换mp-559278.cif
正在转换mp-559289.cif
正在转换mp-559373.cif
正在转换mp-559385.cif
正在转换mp-559389.cif
正在转换mp-559435.cif
正在转换mp-559437.cif
正在转换mp-559479.cif
正在转换mp-559482.cif
正在转换mp-559492.cif
正在转换mp-559513.cif
正在转换mp-559521.cif
正在转换mp-559545.cif
正在转换mp-559598.cif
正在转换mp-559605.cif
正在转换mp-559612.cif
正在转换mp-559618.cif
正在转换mp-559634.cif
正在转换mp-559653.cif
正在转换mp-559689.cif
正在转换mp-559691.cif
正在转换mp-559694.cif
正在转换mp-559727.cif
正在转换mp-559734.cif
正在转换mp-559741.cif
正在转换mp-559757.cif
正在转换mp-559765.cif
正在转换mp-559767.cif
正在转换mp-559773.cif
正在转换mp-559805.cif
正在转换mp-559812.cif
正在转换mp-559826.cif
正在转换mp-559847.cif
正在转换mp-559860.cif
正在转换mp-559871.cif
正在转换mp-559875.cif
正在转换mp-559893.cif
正在转换mp-559918.cif
正在转换mp-559928.cif
正在转换mp-559931.cif
正在转换mp-559933.cif
正在转换mp-559934.cif
正在转换mp-559953.cif
正在转换mp-559958.cif
正在转换mp-559959.cif
正在转换mp-559982.cif
正在转换mp-560014.cif
正在转换mp-560025.cif
正在转换mp-560029.cif
正在转换mp-560030.cif
正在转换mp-560037.cif
正在转换mp-560043.cif
正在转换mp-560067.cif
正在转换mp-560098.cif
正在转换mp-560119.cif
正在转换mp-560127.cif
正在转换mp-560151.cif
正在转换mp-560185.cif
正在转换mp-560188.cif
正在转换mp-560236.cif
正在转换mp-560300.cif
正在转换mp-560311.cif
正在转换mp-560329.cif
正在转换mp-560338.cif
正在转换mp-560380.cif
正在转换mp-560385.cif
正在转换mp-560399.cif
正在转换mp-560417.cif
正在转换mp-560468.cif
正在转换mp-560501.cif
正在转换mp-560515.cif
正在转换mp-560516.cif
正在转换mp-560547.cif
正在转换mp-560555.cif
正在转换mp-560562.cif
正在转换mp-560569.cif
正在转换mp-560610.cif
正在转换mp-560611.cif
正在转换mp-560616.cif
正在转换mp-560620.cif
正在转换mp-560623.cif
正在转换mp-560647.cif
正在转换mp-560663.cif
正在转换mp-560670.cif
正在转换mp-560671.cif
正在转换mp-560675.cif
正在转换mp-560685.cif
正在转换mp-560767.cif
正在转换mp-560805.cif
正在转换mp-560830.cif
正在转换mp-560842.cif
正在转换mp-560853.cif
正在转换mp-560860.cif
正在转换mp-560865.cif
正在转换mp-560870.cif
正在转换mp-560873.cif
正在转换mp-560874.cif
正在转换mp-560882.cif
正在转换mp-560885.cif
正在转换mp-560898.cif
正在转换mp-560904.cif
正在转换mp-560908.cif
正在转换mp-560929.cif
正在转换mp-560936.cif
正在转换mp-560950.cif
正在转换mp-560954.cif
正在转换mp-560959.cif
正在转换mp-560963.cif
正在转换mp-560964.cif
正在转换mp-560977.cif
正在转换mp-561013.cif
正在转换mp-561038.cif
正在转换mp-561051.cif
正在转换mp-561067.cif
正在转换mp-561068.cif
正在转换mp-561070.cif
正在转换mp-561075.cif
正在转换mp-561096.cif
正在转换mp-561099.cif
正在转换mp-561102.cif
正在转换mp-561104.cif
正在转换mp-561113.cif
正在转换mp-561118.cif
正在转换mp-561123.cif
正在转换mp-561126.cif
正在转换mp-561132.cif
正在转换mp-561145.cif
正在转换mp-561167.cif
正在转换mp-561173.cif
正在转换mp-561183.cif
正在转换mp-561187.cif
正在转换mp-561190.cif
正在转换mp-561196.cif
正在转换mp-561197.cif
正在转换mp-561200.cif
正在转换mp-561224.cif
正在转换mp-561242.cif
正在转换mp-561256.cif
正在转换mp-561257.cif
正在转换mp-561260.cif
正在转换mp-561277.cif
正在转换mp-561287.cif
正在转换mp-561288.cif
正在转换mp-561291.cif
正在转换mp-561294.cif
正在转换mp-561303.cif
正在转换mp-561306.cif
正在转换mp-561307.cif
正在转换mp-561309.cif
正在转换mp-561310.cif
正在转换mp-561326.cif
正在转换mp-561348.cif
正在转换mp-561353.cif
正在转换mp-561366.cif
正在转换mp-561368.cif
正在转换mp-561388.cif
正在转换mp-561400.cif
正在转换mp-561412.cif
正在转换mp-561418.cif
正在转换mp-561419.cif
正在转换mp-561423.cif
正在转换mp-561424.cif
正在转换mp-561428.cif
正在转换mp-561430.cif
正在转换mp-561442.cif
正在转换mp-561443.cif
正在转换mp-561446.cif
正在转换mp-561454.cif
正在转换mp-561456.cif
正在转换mp-561468.cif
正在转换mp-561480.cif
正在转换mp-561486.cif
正在转换mp-561489.cif
正在转换mp-561490.cif
正在转换mp-561491.cif

正在转换mp-561499.cif
正在转换mp-561501.cif
正在转换mp-561507.cif
正在转换mp-561511.cif
正在转换mp-561518.cif
正在转换mp-561531.cif
正在转换mp-561536.cif
正在转换mp-561550.cif
正在转换mp-561551.cif
正在转换mp-561558.cif
正在转换mp-561597.cif
正在转换mp-561598.cif
正在转换mp-561616.cif
正在转换mp-561623.cif
正在转换mp-561628.cif
正在转换mp-561634.cif
正在转换mp-561637.cif
正在转换mp-561691.cif
正在转换mp-561738.cif
正在转换mp-561804.cif
正在转换mp-561808.cif
正在转换mp-561825.cif
正在转换mp-561826.cif
正在转换mp-561877.cif
正在转换mp-561903.cif
正在转换mp-561909.cif
正在转换mp-561913.cif
正在转换mp-561926.cif
正在转换mp-561940.cif
正在转换mp-562054.cif
正在转换mp-562066.cif
正在转换mp-562102.cif
正在转换mp-562137.cif
正在转换mp-562155.cif
正在转换mp-562182.cif
正在转换mp-562207.cif
正在转换mp-562260.cif
正在转换mp-562283.cif
正在转换mp-562468.cif
正在转换mp-562480.cif
正在转换mp-562490.cif
正在转换mp-562517.cif
正在转换mp-562537.cif
正在转换mp-562550.cif
正在转换mp-562607.cif
正在转换mp-562610.cif
正在转换mp-562631.cif
正在转换mp-563025.cif
正在转换mp-5643.cif
正在转换mp-565192.cif
正在转换mp-565233.cif
正在转换mp-565254.cif
正在转换mp-565297.cif
正在转换mp-565302.cif
正在转换mp-565303.cif
正在转换mp-565329.cif
正在转换mp-565331.cif
正在转换mp-565348.cif
正在转换mp-565357.cif
正在转换mp-565394.cif
正在转换mp-565425.cif
正在转换mp-565426.cif
正在转换mp-565428.cif
正在转换mp-565444.cif
正在转换mp-565449.cif
正在转换mp-565466.cif
正在转换mp-565468.cif
正在转换mp-565485.cif
正在转换mp-565501.cif
正在转换mp-565503.cif
正在转换mp-565521.cif
正在转换mp-565532.cif
正在转换mp-565569.cif
正在转换mp-565574.cif
正在转换mp-565580.cif
正在转换mp-565634.cif
正在转换mp-565648.cif
正在转换mp-565657.cif
正在转换mp-565666.cif
正在转换mp-565689.cif
正在转换mp-565693.cif
正在转换mp-565699.cif
正在转换mp-565714.cif
正在转换mp-565720.cif
正在转换mp-565747.cif
正在转换mp-565766.cif
正在转换mp-565771.cif
正在转换mp-565782.cif
正在转换mp-565794.cif
正在转换mp-565795.cif
正在转换mp-565801.cif
正在转换mp-565823.cif
正在转换mp-565827.cif
正在转换mp-565846.cif
正在转换mp-565851.cif
正在转换mp-565854.cif
正在转换mp-565866.cif
正在转换mp-565879.cif
正在转换mp-565880.cif
正在转换mp-565893.cif
正在转换mp-565897.cif
正在转换mp-565901.cif
正在转换mp-565904.cif
正在转换mp-565905.cif
正在转换mp-565952.cif
正在转换mp-565953.cif
正在转换mp-565979.cif
正在转换mp-565994.cif
正在转换mp-566008.cif
正在转换mp-566012.cif
正在转换mp-566025.cif
正在转换mp-566026.cif
正在转换mp-566034.cif
正在转换mp-566084.cif
正在转换mp-566124.cif
正在转换mp-566131.cif
正在转换mp-566135.cif
正在转换mp-566186.cif
正在转换mp-566276.cif
正在转换mp-5673.cif
正在转换mp-5716.cif
正在转换mp-5724.cif
正在转换mp-5735.cif
正在转换mp-5779.cif
正在转换mp-5798.cif
正在转换mp-5807.cif
正在转换mp-5868.cif
正在转换mp-609.cif
正在转换mp-613.cif
正在转换mp-614.cif
正在转换mp-618.cif
正在转换mp-639.cif
正在转换mp-698.cif
正在转换mp-717.cif
正在转换mp-722.cif
正在转换mp-755.cif
正在转换mp-846.cif
正在转换mp-882.cif
正在转换mvc-1038.cif
正在转换mvc-1039.cif
正在转换mvc-1058.cif
正在转换mvc-107.cif
正在转换mvc-1176.cif
正在转换mvc-172.cif
正在转换mvc-1811.cif
正在转换mvc-1875.cif
正在转换mvc-192.cif
正在转换mvc-2146.cif
正在转换mvc-22.cif
正在转换mvc-2316.cif
正在转换mvc-2528.cif
正在转换mvc-2548.cif
正在转换mvc-2582.cif
正在转换mvc-27.cif
正在转换mvc-287.cif
正在转换mvc-2967.cif
正在转换mvc-2976.cif
正在转换mvc-3216.cif
正在转换mvc-3217.cif
正在转换mvc-3223.cif
正在转换mvc-3246.cif
正在转换mvc-3559.cif
正在转换mvc-3570.cif
正在转换mvc-35.cif
正在转换mvc-4103.cif
正在转换mvc-4630.cif
正在转换mvc-4660.cif
正在转换mvc-4675.cif
正在转换mvc-477.cif
正在转换mvc-483.cif
正在转换mvc-485.cif
正在转换mvc-495.cif
正在转换mvc-498.cif
正在转换mvc-5044.cif
正在转换mvc-513.cif
正在转换mvc-516.cif
正在转换mvc-522.cif
正在转换mvc-5427.cif
正在转换mvc-545.cif
正在转换mvc-5583.cif
正在转换mvc-5618.cif
正在转换mvc-5646.cif
正在转换mvc-5647.cif
正在转换mvc-5782.cif
正在转换mvc-5791.cif
正在转换mvc-5792.cif
正在转换mvc-600.cif
正在转换mvc-610.cif
正在转换mvc-657.cif
正在转换mvc-724.cif
正在转换mvc-734.cif
正在转换mvc-782.cif
正在转换mvc-793.cif
正在转换mvc-844.cif
正在转换mvc-882.cif
正在转换mvc-894.cif
正在转换mvc-920.cif
正在转换mvc-922.cif
正在转换mvc-938.cif
正在转换mvc-93.cif
正在转换mvc-940.cif
正在转换mp-10003.cif
正在转换mp-10025.cif
正在转换mp-10045.cif
正在转换mp-10203.cif
正在转换mp-10250.cif
正在转换mp-10335.cif
正在转换mp-10359.cif
正在转换mp-10440.cif
正在转换mp-10463.cif
正在转换mp-10464.cif
正在转换mp-10510.cif
正在转换mp-10720.cif
正在转换mp-10744.cif
正在转换mp-10754.cif
正在转换mp-10804.cif
正在转换mp-10844.cif
正在转换mp-10851.cif
正在转换mp-10857.cif
正在转换mp-10858.cif
正在转换mp-10878.cif
正在转换mp-10912.cif
正在转换mp-10935.cif
正在转换mp-10948.cif
正在转换mp-11000.cif
正在转换mp-11206.cif
正在转换mp-11272.cif
正在转换mp-11280.cif
正在转换mp-11332.cif
正在转换mp-11350.cif
正在转换mp-11415.cif
正在转换mp-11497.cif
正在转换mp-11610.cif
正在转换mp-11653.cif
正在转换mp-11725.cif
正在转换mp-11872.cif
正在转换mp-11875.cif
正在转换mp-11928.cif
正在转换mp-12052.cif
正在转换mp-1323.cif
正在转换mp-16496.cif
正在转换mp-16511.cif
正在转换mp-16533.cif
正在转换mp-16534.cif
正在转换mp-16783.cif
正在转换mp-16795.cif
正在转换mp-16877.cif
正在转换mp-17013.cif
正在转换mp-17023.cif
正在转换mp-17030.cif
正在转换mp-17113.cif
正在转换mp-17124.cif
正在转换mp-17158.cif
正在转换mp-17332.cif
正在转换mp-17535.cif
正在转换mp-17865.cif
正在转换mp-17906.cif
正在转换mp-17910.cif
正在转换mp-17977.cif
正在转换mp-18032.cif
正在转换mp-18074.cif
正在转换mp-18093.cif
正在转换mp-18257.cif
正在转换mp-18503.cif
正在转换mp-18511.cif
正在转换mp-18690.cif
正在转换mp-18695.cif
正在转换mp-18758.cif
正在转换mp-18792.cif
正在转换mp-18799.cif
正在转换mp-18830.cif
正在转换mp-18833.cif
正在转换mp-18847.cif
正在转换mp-18865.cif
正在转换mp-18900.cif
正在转换mp-18904.cif
正在转换mp-18913.cif
正在转换mp-18927.cif
正在转换mp-18982.cif
正在转换mp-18999.cif
正在转换mp-19066.cif
正在转换mp-19070.cif
正在转换mp-19127.cif
正在转换mp-19150.cif
正在转换mp-19159.cif
正在转换mp-19168.cif
正在转换mp-19170.cif
正在转换mp-19200.cif
正在转换mp-19227.cif
正在转换mp-19249.cif
正在转换mp-19271.cif
正在转换mp-19274.cif
正在转换mp-19303.cif
正在转换mp-19307.cif
正在转换mp-19354.cif
正在转换mp-19394.cif
正在转换mp-19413.cif
正在转换mp-19456.cif
正在转换mp-19595.cif
正在转换mp-19679.cif
正在转换mp-19719.cif
正在转换mp-19738.cif
正在转换mp-19751.cif
正在转换mp-19797.cif
正在转换mp-19800.cif
正在转换mp-19809.cif
正在转换mp-19843.cif
正在转换mp-19884.cif
正在转换mp-19930.cif
正在转换mp-19947.cif
正在转换mp-19954.cif
正在转换mp-19975.cif
正在转换mp-19989.cif
正在转换mp-20017.cif
正在转换mp-20030.cif
正在转换mp-20077.cif
正在转换mp-20087.cif
正在转换mp-20116.cif
正在转换mp-20140.cif
正在转换mp-20146.cif
正在转换mp-20154.cif
正在转换mp-20186.cif
正在转换mp-20196.cif
正在转换mp-20213.cif
正在转换mp-20246.cif
正在转换mp-20247.cif
正在转换mp-20270.cif
正在转换mp-20276.cif
正在转换mp-20278.cif
正在转换mp-20284.cif
正在转换mp-20293.cif
正在转换mp-20324.cif
正在转换mp-20328.cif
正在转换mp-20330.cif
正在转换mp-20342.cif
正在转换mp-20347.cif
正在转换mp-20373.cif
正在转换mp-20380.cif
正在转换mp-20391.cif
正在转换mp-20395.cif
正在转换mp-20412.cif
正在转换mp-20433.cif
正在转换mp-20437.cif
正在转换mp-20447.cif
正在转换mp-20456.cif
正在转换mp-20464.cif
正在转换mp-20484.cif
正在转换mp-20499.cif
正在转换mp-20513.cif
正在转换mp-20520.cif
正在转换mp-20541.cif
正在转换mp-20576.cif
正在转换mp-20623.cif
正在转换mp-20633.cif
正在转换mp-20642.cif
正在转换mp-20643.cif
正在转换mp-20674.cif
正在转换mp-20680.cif
正在转换mp-20696.cif
正在转换mp-20703.cif
正在转换mp-20704.cif
正在转换mp-20709.cif
正在转换mp-20781.cif
正在转换mp-20814.cif
正在转换mp-20877.cif
正在转换mp-20925.cif
正在转换mp-20958.cif
正在转换mp-20960.cif
正在转换mp-20982.cif
正在转换mp-21019.cif
正在转换mp-21021.cif
正在转换mp-21065.cif
正在转换mp-21141.cif
正在转换mp-21154.cif
正在转换mp-21155.cif
正在转换mp-21173.cif
正在转换mp-21181.cif
正在转换mp-21185.cif
正在转换mp-21243.cif
正在转换mp-21259.cif
正在转换mp-21268.cif
正在转换mp-21269.cif
正在转换mp-21337.cif
正在转换mp-21338.cif
正在转换mp-21346.cif
正在转换mp-21447.cif
正在转换mp-21464.cif
正在转换mp-21476.cif
正在转换mp-21873.cif
正在转换mp-21878.cif
正在转换mp-22010.cif
正在转换mp-22018.cif
正在转换mp-22037.cif
正在转换mp-22040.cif
正在转换mp-22043.cif
正在转换mp-22071.cif
正在转换mp-22089.cif
正在转换mp-22119.cif
正在转换mp-22127.cif
正在转换mp-22165.cif
正在转换mp-22206.cif
正在转换mp-22215.cif
正在转换mp-22257.cif
正在转换mp-22260.cif
正在转换mp-22305.cif
正在转换mp-22309.cif
正在转换mp-22396.cif
正在转换mp-22403.cif
正在转换mp-22413.cif
正在转换mp-22431.cif
正在转换mp-22444.cif
正在转换mp-22492.cif
正在转换mp-22546.cif
正在转换mp-22575.cif
正在转换mp-22592.cif
正在转换mp-22597.cif
正在转换mp-22613.cif
正在转换mp-22645.cif
正在转换mp-22652.cif
正在转换mp-22666.cif
正在转换mp-22690.cif
正在转换mp-22695.cif
正在转换mp-3671.cif
正在转换mp-4644.cif
正在转换mp-5924.cif
正在转换mp-6036.cif
正在转换mp-6051.cif
正在转换mp-6124.cif
正在转换mp-6179.cif
正在转换mp-6318.cif
正在转换mp-6319.cif
正在转换mp-6340.cif
正在转换mp-6424.cif
正在转换mp-6604.cif
正在转换mp-6616.cif
正在转换mp-6667.cif
正在转换mp-6685.cif
正在转换mp-6778.cif
正在转换mp-6847.cif
正在转换mp-6873.cif
正在转换mp-6909.cif
正在转换mp-6910.cif
正在转换mp-6922.cif
正在转换mp-6944.cif
正在转换mp-6945.cif
正在转换mp-6947.cif
正在转换mp-7000.cif
正在转换mp-7022.cif
正在转换mp-7024.cif
正在转换mp-7062.cif
正在转换mp-7073.cif
正在转换mp-7087.cif
正在转换mp-7228.cif
正在转换mp-7275.cif
正在转换mp-7276.cif
正在转换mp-7285.cif
正在转换mp-7305.cif
正在转换mp-7337.cif
正在转换mp-7350.cif
正在转换mp-7506.cif
正在转换mp-7567.cif
正在转换mp-7593.cif
正在转换mp-7599.cif
正在转换mp-7648.cif
正在转换mp-7685.cif
正在转换mp-7723.cif
正在转换mp-7735.cif
正在转换mp-7845.cif
正在转换mp-7846.cif
正在转换mp-7851.cif
正在转换mp-7888.cif
正在转换mp-7889.cif
正在转换mp-7923.cif
正在转换mp-8039.cif
正在转换mp-8057.cif
正在转换mp-8059.cif
正在转换mp-8090.cif
正在转换mp-8110.cif
正在转换mp-8189.cif
正在转换mp-8261.cif
正在转换mp-8268.cif
正在转换mp-8272.cif
正在转换mp-8352.cif
正在转换mp-8354.cif
正在转换mp-8408.cif
正在转换mp-8414.cif
正在转换mp-8424.cif
正在转换mp-8425.cif
正在转换mp-8454.cif
正在转换mp-8469.cif
正在转换mp-8530.cif
正在转换mp-8678.cif
正在转换mp-8768.cif
正在转换mp-8769.cif
正在转换mp-8874.cif
正在转换mp-8895.cif
正在转换mp-8909.cif
正在转换mp-8983.cif
正在转换mp-9027.cif
正在转换mp-9149.cif
正在转换mp-9266.cif
正在转换mp-9305.cif
正在转换mp-9348.cif
正在转换mp-9349.cif
正在转换mp-9394.cif
正在转换mp-9398.cif
正在转换mp-9407.cif
正在转换mp-9441.cif
正在转换mp-9442.cif
正在转换mp-9495.cif
正在转换mp-9515.cif
正在转换mp-9516.cif
正在转换mp-9544.cif
正在转换mp-9716.cif

正在转换mp-9805.cif
正在转换mp-9839.cif
正在转换mp-9847.cif
正在转换mp-9983.cif
正在转换mvc-10023.cif
正在转换mvc-10874.cif
正在转换mvc-10888.cif
正在转换mvc-10896.cif
正在转换mvc-10942.cif
正在转换mvc-10947.cif
正在转换mvc-11037.cif
正在转换mvc-11104.cif
正在转换mvc-11190.cif
正在转换mvc-11245.cif
正在转换mvc-11248.cif
正在转换mvc-11251.cif
正在转换mvc-11254.cif
正在转换mvc-11283.cif
正在转换mvc-11284.cif
正在转换mvc-11285.cif
正在转换mvc-11286.cif
正在转换mvc-11289.cif
正在转换mvc-11418.cif
正在转换mvc-11436.cif
正在转换mvc-11437.cif
正在转换mvc-11441.cif
正在转换mvc-11476.cif
正在转换mvc-11636.cif
正在转换mvc-11663.cif
正在转换mvc-11666.cif
正在转换mvc-11742.cif
正在转换mvc-11745.cif
正在转换mvc-11780.cif
正在转换mvc-11795.cif
正在转换mvc-11828.cif
正在转换mvc-11834.cif
正在转换mvc-11925.cif
正在转换mvc-1224.cif
正在转换mvc-1239.cif
正在转换mvc-12415.cif
正在转换mvc-1255.cif
正在转换mvc-1313.cif
正在转换mvc-1324.cif
正在转换mvc-1336.cif
正在转换mvc-1403.cif
正在转换mvc-1467.cif
正在转换mvc-1612.cif
正在转换mvc-16600.cif
正在转换mvc-16625.cif
正在转换mvc-16628.cif
正在转换mvc-16726.cif
正在转换mvc-16728.cif
正在转换mvc-16729.cif
正在转换mvc-16730.cif
正在转换mvc-16734.cif
正在转换mvc-16735.cif
正在转换mvc-16738.cif
正在转换mvc-16741.cif
正在转换mvc-16744.cif
正在转换mvc-16746.cif
正在转换mvc-16752.cif
正在转换mvc-16755.cif
正在转换mvc-16758.cif
正在转换mvc-16768.cif
正在转换mvc-16777.cif
正在转换mvc-16778.cif
正在转换mvc-16779.cif
正在转换mvc-16781.cif
正在转换mvc-16787.cif
正在转换mvc-16788.cif
正在转换mvc-16793.cif
正在转换mvc-16807.cif
正在转换mvc-1739.cif
正在转换mvc-3460.cif
正在转换mvc-3464.cif
正在转换mvc-3660.cif
正在转换mvc-3663.cif
正在转换mvc-3675.cif
正在转换mvc-3687.cif
正在转换mvc-3751.cif
正在转换mvc-3765.cif
正在转换mvc-3768.cif
正在转换mvc-3769.cif
正在转换mvc-3770.cif
正在转换mvc-4256.cif
正在转换mvc-4629.cif
正在转换mvc-5948.cif
正在转换mvc-6054.cif
正在转换mvc-6058.cif
正在转换mvc-6059.cif
正在转换mvc-6082.cif
正在转换mvc-6084.cif
正在转换mvc-6271.cif
正在转换mvc-6397.cif
正在转换mvc-6404.cif
正在转换mvc-6405.cif
正在转换mvc-6414.cif
正在转换mvc-6416.cif
正在转换mvc-6475.cif
正在转换mvc-6477.cif
正在转换mvc-6517.cif
正在转换mvc-6531.cif
正在转换mvc-6537.cif
正在转换mvc-6579.cif
正在转换mvc-6617.cif
正在转换mvc-6914.cif
正在转换mvc-6924.cif
正在转换mvc-7627.cif
正在转换mvc-7689.cif
正在转换mvc-7743.cif
正在转换mvc-8318.cif
正在转换mvc-8417.cif
正在转换mvc-8799.cif
正在转换mvc-898.cif
正在转换mvc-9263.cif
正在转换mvc-9265.cif
正在转换mvc-937.cif
正在转换mp-1046.cif
正在转换mp-1490.cif
正在转换mp-1658.cif
正在转换mp-1853.cif
正在转换mp-1993.cif
正在转换mp-2218.cif
正在转换mp-2315.cif
正在转换mp-2395.cif
正在转换mp-2409.cif
正在转换mp-2432.cif
正在转换mp-2503.cif
正在转换mp-2512.cif
正在转换mp-2544.cif
正在转换mp-2572.cif
正在转换mp-2588.cif
正在转换mp-2631.cif
正在转换mp-2650.cif
正在转换mp-2675.cif
正在转换mp-2754.cif
正在转换mp-27771.cif
正在转换mp-2786.cif
正在转换mp-2798.cif
正在转换mp-29509.cif
正在转换mp-2997.cif
正在转换mp-303.cif
正在转换mp-3285.cif
正在转换mp-3347.cif
正在转换mp-3652.cif
正在转换mp-3694.cif
正在转换mp-3706.cif
正在转换mp-3719.cif
正在转换mp-3770.cif
正在转换mp-3778.cif
正在转换mp-3782.cif
正在转换mp-3797.cif
正在转换mp-3831.cif
正在转换mp-3859.cif
正在转换mp-3887.cif
正在转换mp-3897.cif
正在转换mp-457.cif
正在转换mp-504594.cif
正在转换mp-518.cif
正在转换mp-554405.cif
正在转换mp-555838.cif
正在转换mp-557250.cif
正在转换mp-571377.cif
正在转换mp-684969.cif
正在转换mp-691133.cif
正在转换mp-696497.cif
正在转换mp-761037.cif
正在转换mp-765254.cif
正在转换mp-771797.cif
正在转换mp-879.cif
正在转换mp-8998.cif
正在转换mvc-2206.cif
正在转换mp-10301.cif
正在转换mp-11486.cif
正在转换mp-11964.cif
正在转换mp-12305.cif
正在转换mp-12695.cif
正在转换mp-12700.cif
正在转换mp-4325.cif
正在转换mp-5338.cif
正在转换mp-5401.cif
正在转换mp-5466.cif
正在转换mp-5601.cif
正在转换mp-5704.cif
正在转换mp-5929.cif
正在转换mp-5979.cif
正在转换mp-6018.cif
正在转换mp-6055.cif
正在转换mp-6078.cif
正在转换mp-6109.cif
正在转换mp-6238.cif
正在转换mp-6294.cif
正在转换mp-6330.cif
正在转换mp-6596.cif
正在转换mp-6600.cif
正在转换mp-6662.cif
正在转换mp-6772.cif
正在转换mp-6824.cif
正在转换mp-6892.cif
正在转换mp-7066.cif
正在转换mp-7234.cif
正在转换mp-7264.cif
正在转换mp-7324.cif
正在转换mp-7343.cif
正在转换mp-7767.cif
正在转换mp-7788.cif
正在转换mvc-5828.cif
正在转换mvc-5855.cif
正在转换mp-1001790.cif
正在转换mp-1004525.cif
正在转换mp-1005850.cif
正在转换mp-1007694.cif
正在转换mp-1008471.cif
正在转换mp-1008505.cif
正在转换mp-1008777.cif
正在转换mp-1008865.cif
正在转换mp-1008918.cif
正在转换mp-1008923.cif
正在转换mp-1008986.cif
正在转换mp-1009049.cif
正在转换mp-1009134.cif
正在转换mp-1014287.cif
正在转换mp-1017555.cif
正在转换mp-1017579.cif
正在转换mp-1018023.cif
正在转换mp-1018055.cif
正在转换mp-1024947.cif
正在转换mp-1024984.cif
正在转换mp-1024996.cif
正在转换mp-1025025.cif
正在转换mp-1025043.cif
正在转换mp-1025071.cif
正在转换mp-980204.cif
正在转换mp-980666.cif
正在转换mp-981392.cif
正在转换mp-981539.cif
正在转换mp-981699.cif
正在转换mp-981747.cif
正在转换mp-981749.cif
正在转换mp-982244.cif
正在转换mp-982261.cif
正在转换mp-982559.cif
正在转换mp-983427.cif
正在转换mp-983480.cif
正在转换mp-983555.cif
正在转换mp-983556.cif
正在转换mp-983581.cif
正在转换mp-983583.cif
正在转换mp-983586.cif
正在转换mp-983850.cif
正在转换mp-984050.cif
正在转换mp-984053.cif
正在转换mp-984055.cif
正在转换mp-984106.cif
正在转换mp-984353.cif
正在转换mp-984359.cif
正在转换mp-984682.cif
正在转换mp-985286.cif
正在转换mp-985291.cif
正在转换mp-985581.cif
正在转换mp-985608.cif
正在转换mp-985610.cif
正在转换mp-996952.cif
正在转换mp-998154.cif
正在转换mp-998201.cif
正在转换mp-998786.cif
正在转换mp-861866.cif
正在转换mp-861893.cif
正在转换mp-861894.cif
正在转换mp-861898.cif
正在转换mp-861944.cif
正在转换mp-861957.cif
正在转换mp-861962.cif
正在转换mp-861963.cif
正在转换mp-861986.cif
正在转换mp-862682.cif
正在转换mp-862762.cif
正在转换mp-862995.cif
正在转换mp-863377.cif
正在转换mp-863872.cif
正在转换mp-863896.cif
正在转换mp-864619.cif
正在转换mp-864664.cif
正在转换mp-864666.cif
正在转换mp-864674.cif
正在转换mp-864684.cif
正在转换mp-864696.cif
正在转换mp-864764.cif
正在转换mp-864783.cif
正在转换mp-864784.cif
正在转换mp-864837.cif
正在转换mp-864892.cif
正在转换mp-864902.cif
正在转换mp-864904.cif
正在转换mp-864918.cif
正在转换mp-864923.cif
正在转换mp-864932.cif
正在转换mp-864939.cif
正在转换mp-864955.cif
正在转换mp-864960.cif
正在转换mp-864963.cif
正在转换mp-864969.cif
正在转换mp-865045.cif
正在转换mp-865098.cif
正在转换mp-865200.cif
正在转换mp-865213.cif
正在转换mp-865235.cif
正在转换mp-865400.cif
正在转换mp-865450.cif
正在转换mp-865488.cif
正在转换mp-865494.cif
正在转换mp-865495.cif
正在转换mp-865500.cif
正在转换mp-865506.cif
正在转换mp-865511.cif
正在转换mp-865513.cif
正在转换mp-865514.cif
正在转换mp-865529.cif
正在转换mp-865563.cif
正在转换mp-865582.cif
正在转换mp-865591.cif
正在转换mp-865798.cif
正在转换mp-865804.cif
正在转换mp-865811.cif
正在转换mp-865861.cif
正在转换mp-865878.cif
正在转换mp-865910.cif
正在转换mp-865923.cif
正在转换mp-865931.cif
正在转换mp-865951.cif
正在转换mp-865953.cif
正在转换mp-865956.cif
正在转换mp-865957.cif
正在转换mp-866032.cif
正在转换mp-866076.cif
正在转换mp-866097.cif
正在转换mp-866102.cif
正在转换mp-866196.cif
正在转换mp-866220.cif
正在转换mp-866267.cif
正在转换mp-866298.cif
正在转换mp-866299.cif
正在转换mp-866306.cif
正在转换mp-866310.cif
正在转换mp-866312.cif
正在转换mp-866473.cif
正在转换mp-866474.cif
正在转换mp-866475.cif
正在转换mp-866509.cif
正在转换mp-866519.cif
正在转换mp-866522.cif
正在转换mp-866651.cif
正在转换mp-866663.cif
正在转换mp-866728.cif
正在转换mp-866811.cif
正在转换mp-867132.cif
正在转换mp-867143.cif
正在转换mp-867226.cif
正在转换mp-867227.cif
正在转换mp-867254.cif
正在转换mp-867255.cif
正在转换mp-867256.cif
正在转换mp-867257.cif
正在转换mp-867259.cif
正在转换mp-867262.cif
正在转换mp-867272.cif
正在转换mp-867279.cif
正在转换mp-867285.cif
正在转换mp-867313.cif
正在转换mp-867329.cif
正在转换mp-867361.cif
正在转换mp-867534.cif
正在转换mp-867680.cif
正在转换mp-867815.cif
正在转换mp-867841.cif
正在转换mp-867851.cif
正在转换mp-867874.cif
正在转换mp-867940.cif
正在转换mp-868118.cif
正在转换mp-868355.cif
正在转换mp-868359.cif
正在转换mp-868363.cif
正在转换mp-868422.cif
正在转换mp-868529.cif
正在转换mp-868631.cif
正在转换mp-868632.cif
正在转换mp-868642.cif
正在转换mp-868644.cif
正在转换mp-868654.cif
正在转换mp-961715.cif
正在转换mp-962061.cif
正在转换mp-971648.cif
正在转换mp-971718.cif
正在转换mp-971875.cif
正在转换mp-971924.cif
正在转换mp-971985.cif
正在转换mp-972069.cif
正在转换mp-972147.cif
正在转换mp-972590.cif
正在转换mp-972954.cif
正在转换mp-972961.cif
正在转换mp-972978.cif
正在转换mp-972985.cif
正在转换mp-973181.cif
正在转换mp-973191.cif
正在转换mp-973217.cif
正在转换mp-973225.cif
正在转换mp-973906.cif
正在转换mp-973953.cif
正在转换mp-973966.cif
正在转换mp-974589.cif
正在转换mp-974667.cif
正在转换mp-974862.cif
正在转换mp-974974.cif
正在转换mp-975031.cif
正在转换mp-975103.cif
正在转换mp-975106.cif
正在转换mp-975115.cif
正在转换mp-975134.cif
正在转换mp-975173.cif
正在转换mp-975359.cif
正在转换mp-975405.cif
正在转换mp-975443.cif
正在转换mp-975461.cif
正在转换mp-975605.cif
正在转换mp-975663.cif
正在转换mp-975794.cif
正在转换mp-975799.cif
正在转换mp-975834.cif
正在转换mp-975838.cif
正在转换mp-975857.cif
正在转换mp-975904.cif
正在转换mp-975912.cif
正在转换mp-975958.cif
正在转换mp-976055.cif
正在转换mp-976060.cif
正在转换mp-976064.cif
正在转换mp-976075.cif
正在转换mp-976080.cif
正在转换mp-976115.cif
正在转换mp-976122.cif
正在转换mp-976139.cif
正在转换mp-976257.cif
正在转换mp-976277.cif
正在转换mp-976281.cif
正在转换mp-976331.cif
正在转换mp-976368.cif
正在转换mp-976380.cif
正在转换mp-976405.cif
正在转换mp-976408.cif
正在转换mp-976424.cif
正在转换mp-976587.cif
正在转换mp-976707.cif
正在转换mp-976726.cif
正在转换mp-976751.cif
正在转换mp-976809.cif
正在转换mp-976818.cif
正在转换mp-976828.cif
正在转换mp-976893.cif
正在转换mp-976953.cif
正在转换mp-976955.cif
正在转换mp-976971.cif
正在转换mp-977062.cif
正在转换mp-977110.cif
正在转换mp-977113.cif
正在转换mp-977115.cif
正在转换mp-977117.cif
正在转换mp-977123.cif
正在转换mp-977351.cif
正在转换mp-978277.cif
正在转换mp-985697.cif
正在转换mp-985700.cif
正在转换mp-985702.cif
正在转换mp-985805.cif
正在转换mp-988939.cif
正在转换mp-989401.cif
正在转换mp-989459.cif
正在转换mp-989513.cif
正在转换mp-989546.cif
正在转换mp-989573.cif
正在转换mp-989576.cif
正在转换mp-989577.cif
正在转换mp-989590.cif
正在转换mp-989591.cif
正在转换mp-989592.cif
正在转换mp-780526.cif
正在转换mp-780557.cif
正在转换mp-780559.cif
正在转换mp-780591.cif
正在转换mp-780671.cif

正在转换mp-780703.cif
正在转换mp-780815.cif
正在转换mp-780823.cif
正在转换mp-780832.cif
正在转换mp-780837.cif
正在转换mp-780855.cif
正在转换mp-780874.cif
正在转换mp-780906.cif
正在转换mp-780913.cif
正在转换mp-780917.cif
正在转换mp-780921.cif
正在转换mp-781634.cif
正在转换mp-781689.cif
正在转换mp-781694.cif
正在转换mp-781696.cif
正在转换mp-781753.cif
正在转换mp-781754.cif
正在转换mp-781767.cif
正在转换mp-781783.cif
正在转换mp-781959.cif
正在转换mp-782680.cif
正在转换mp-782681.cif
正在转换mp-782697.cif
正在转换mp-782699.cif
正在转换mp-782821.cif
正在转换mp-793779.cif
正在转换mp-849078.cif
正在转换mp-849219.cif
正在转换mp-849234.cif
正在转换mp-849271.cif
正在转换mp-849352.cif
正在转换mp-849371.cif
正在转换mp-849387.cif
正在转换mp-849388.cif
正在转换mp-849404.cif
正在转换mp-849461.cif
正在转换mp-773738.cif
正在转换mp-773752.cif
正在转换mp-774043.cif
正在转换mp-774073.cif
正在转换mp-774089.cif
正在转换mp-849464.cif
正在转换mp-849466.cif
正在转换mp-849493.cif
正在转换mp-849668.cif
正在转换mp-849699.cif
正在转换mp-849937.cif
正在转换mp-850015.cif
正在转换mp-850017.cif
正在转换mp-850049.cif
正在转换mp-850065.cif
正在转换mp-850068.cif
正在转换mp-850078.cif
正在转换mp-850080.cif
正在转换mp-850329.cif
正在转换mp-850393.cif
正在转换mp-850401.cif
正在转换mp-850946.cif
正在转换mp-850958.cif
正在转换mp-850978.cif
正在转换mp-850997.cif
正在转换mp-851019.cif
正在转换mp-851034.cif
正在转换mp-853133.cif
正在转换mp-853145.cif
正在转换mp-853151.cif
正在转换mp-853189.cif
正在转换mp-853230.cif
正在转换mp-774257.cif
正在转换mp-775042.cif
正在转换mp-775076.cif
正在转换mp-775093.cif
正在转换mp-775175.cif
正在转换mp-775199.cif
正在转换mp-775295.cif
正在转换mp-775308.cif
正在转换mp-775531.cif
正在转换mp-775570.cif
正在转换mp-775608.cif
正在转换mp-775778.cif
正在转换mp-10004.cif
正在转换mp-10047.cif
正在转换mp-10057.cif
正在转换mp-10103.cif
正在转换mp-10114.cif
正在转换mp-10126.cif
正在转换mp-10129.cif
正在转换mp-10131.cif
正在转换mp-10136.cif
正在转换mp-10199.cif
正在转换mp-10240.cif
正在转换mp-10283.cif
正在转换mp-10284.cif
正在转换mp-10298.cif
正在转换mp-10302.cif
正在转换mp-10350.cif
正在转换mp-10366.cif
正在转换mp-10398.cif
正在转换mp-10430.cif
正在转换mp-10456.cif
正在转换mp-10457.cif
正在转换mp-1045.cif
正在转换mp-10469.cif
正在转换mp-10470.cif
正在转换mp-10474.cif
正在转换mp-10492.cif
正在转换mp-10500.cif
正在转换mp-10502.cif
正在转换mp-10503.cif
正在转换mp-10504.cif
正在转换mp-1050.cif
正在转换mp-10534.cif
正在转换mp-10566.cif
正在转换mp-1056.cif
正在转换mp-10584.cif
正在转换mp-10694.cif
正在转换mp-10721.cif
正在转换mp-1072.cif
正在转换mp-10746.cif
正在转换mp-10846.cif
正在转换mp-10847.cif
正在转换mp-10848.cif
正在转换mp-10849.cif
正在转换mp-10850.cif
正在转换mp-10853.cif
正在转换mp-10854.cif
正在转换mp-10856.cif
正在转换mp-10877.cif
正在转换mp-10896.cif
正在转换mp-10911.cif
正在转换mp-10922.cif
正在转换mp-10923.cif
正在转换mp-10924.cif
正在转换mp-10983.cif
正在转换mp-1098.cif
正在转换mp-10999.cif
正在转换mp-11033.cif
正在转换mp-11034.cif
正在转换mp-11037.cif
正在转换mp-11080.cif
正在转换mp-11101.cif
正在转换mp-11160.cif
正在转换mp-11176.cif
正在转换mp-11183.cif
正在转换mp-11189.cif
正在转换mp-11214.cif
正在转换mp-11225.cif
正在转换mp-11227.cif
正在转换mp-11230.cif
正在转换mp-1124.cif
正在转换mp-11270.cif
正在转换mp-11275.cif
正在转换mp-11281.cif
正在转换mp-11282.cif
正在转换mp-11285.cif
正在转换mp-11288.cif
正在转换mp-11338.cif
正在转换mp-1133.cif
正在转换mp-11340.cif
正在转换mp-11347.cif
正在转换mp-11368.cif
正在转换mp-11393.cif
正在转换mp-11431.cif
正在转换mp-11437.cif
正在转换mp-11438.cif
正在转换mp-11440.cif
正在转换mp-11441.cif
正在转换mp-11442.cif
正在转换mp-11449.cif
正在转换mp-11453.cif
正在转换mp-11456.cif
正在转换mp-11508.cif
正在转换mp-11544.cif
正在转换mp-11557.cif
正在转换mp-11560.cif
正在转换mp-11581.cif
正在转换mp-11625.cif
正在转换mp-1163.cif
正在转换mp-11658.cif
正在转换mp-11665.cif
正在转换mp-11666.cif
正在转换mp-11667.cif
正在转换mp-11668.cif
正在转换mp-1167.cif
正在转换mp-11696.cif
正在转换mp-11718.cif
正在转换mp-11734.cif
正在转换mp-11749.cif
正在转换mp-11752.cif
正在转换mp-11753.cif
正在转换mp-11764.cif
正在转换mp-11778.cif
正在转换mp-11811.cif
正在转换mp-11844.cif
正在转换mp-11851.cif
正在转换mp-11854.cif
正在转换mp-11883.cif
正在转换mp-11892.cif
正在转换mp-11904.cif
正在转换mp-11905.cif
正在转换mp-11906.cif
正在转换mp-11908.cif
正在转换mp-11912.cif
正在转换mp-11913.cif
正在转换mp-11945.cif
正在转换mp-11990.cif
正在转换mp-11991.cif
正在转换mp-12024.cif
正在转换mp-1203.cif
正在转换mp-12109.cif
正在转换mp-12231.cif
正在转换mp-12240.cif
正在转换mp-12275.cif
正在转换mp-12307.cif
正在转换mp-12315.cif
正在转换mp-12323.cif
正在转换mp-12386.cif
正在转换mp-12387.cif
正在转换mp-12398.cif
正在转换mp-12403.cif
正在转换mp-12410.cif
正在转换mp-12431.cif
正在转换mp-12464.cif
正在转换mp-12465.cif
正在转换mp-1249.cif
正在转换mp-12521.cif
正在转换mp-12543.cif
正在转换mp-12544.cif
正在转换mp-12545.cif
正在转换mp-12549.cif
正在转换mp-12569.cif
正在转换mp-12614.cif
正在转换mp-12615.cif
正在转换mp-12627.cif
正在转换mp-12633.cif
正在转换mp-12648.cif
正在转换mp-12657.cif
正在转换mp-12659.cif
正在转换mp-12678.cif
正在转换mp-12689.cif
正在转换mp-12691.cif
正在转换mp-12697.cif
正在转换mp-12704.cif
正在转换mp-12722.cif
正在转换mp-12730.cif
正在转换mp-12780.cif
正在转换mp-12784.cif
正在转换mp-12789.cif
正在转换mp-12797.cif
正在转换mp-12803.cif
正在转换mp-12815.cif
正在转换mp-12829.cif
正在转换mp-12846.cif
正在转换mp-12879.cif
正在转换mp-12889.cif
正在转换mp-12890.cif
正在转换mp-12896.cif
正在转换mp-12905.cif
正在转换mp-12906.cif
正在转换mp-12923.cif
正在转换mp-12956.cif
正在转换mp-1295.cif
正在转换mp-12960.cif
正在转换mp-12964.cif
正在转换mp-12965.cif
正在转换mp-12974.cif
正在转换mp-12975.cif
正在转换mp-12977.cif
正在转换mp-13020.cif
正在转换mp-13073.cif
正在转换mp-13139.cif
正在转换mp-13160.cif
正在转换mp-13190.cif
正在转换mp-13211.cif
正在转换mp-13230.cif
正在转换mp-13236.cif
正在转换mp-13241.cif
正在转换mp-13243.cif
正在转换mp-13271.cif
正在转换mp-13285.cif
正在转换mp-1332.cif
正在转换mp-13341.cif
正在转换mp-13342.cif
正在转换mp-13343.cif
正在转换mp-13349.cif
正在转换mp-13350.cif
正在转换mp-13352.cif
正在转换mp-13376.cif
正在转换mp-13380.cif
正在转换mp-13415.cif
正在转换mp-13416.cif
正在转换mp-1341.cif
正在转换mp-13427.cif
正在转换mp-13450.cif
正在转换mp-13459.cif
正在转换mp-13464.cif
正在转换mp-13472.cif
正在转换mp-13475.cif
正在转换mp-13483.cif
正在转换mp-13490.cif
正在转换mp-13503.cif
正在转换mp-13504.cif
正在转换mp-13511.cif
正在转换mp-13514.cif
正在转换mp-13546.cif
正在转换mp-1356.cif
正在转换mp-13570.cif
正在转换mp-13573.cif
正在转换mp-13579.cif
正在转换mp-1357.cif
正在转换mp-13580.cif
正在转换mp-13583.cif
正在转换mp-13619.cif
正在转换mp-13620.cif
正在转换mp-13630.cif
正在转换mp-13673.cif
正在转换mp-13688.cif
正在转换mp-13725.cif
正在转换mp-13815.cif
正在转换mp-13816.cif
正在转换mp-13819.cif
正在转换mp-13841.cif
正在转换mp-13854.cif
正在转换mp-13861.cif
正在转换mp-13898.cif
正在转换mp-13917.cif
正在转换mp-13920.cif
正在转换mp-13925.cif
正在转换mp-13926.cif
正在转换mp-13929.cif
正在转换mp-13931.cif
正在转换mp-13932.cif
正在转换mp-13933.cif
正在转换mp-13934.cif
正在转换mp-13935.cif
正在转换mp-13944.cif
正在转换mp-13946.cif
正在转换mp-13947.cif
正在转换mp-13967.cif
正在转换mp-13978.cif
正在转换mp-13993.cif
正在转换mp-14005.cif
正在转换mp-14006.cif
正在转换mp-14025.cif
正在转换mp-1407.cif
正在转换mp-14128.cif
正在转换mp-14168.cif
正在转换mp-14207.cif
正在转换mp-14245.cif
正在转换mp-1427.cif
正在转换mp-14283.cif
正在转换mp-14294.cif
正在转换mp-14356.cif
正在转换mp-14373.cif
正在转换mp-14387.cif
正在转换mp-14396.cif
正在转换mp-14406.cif
正在转换mp-14410.cif
正在转换mp-14422.cif
正在转换mp-14423.cif
正在转换mp-14424.cif
正在转换mp-14425.cif
正在转换mp-14445.cif
正在转换mp-14466.cif
正在转换mp-14563.cif
正在转换mp-14622.cif
正在转换mp-14638.cif
正在转换mp-1464.cif
正在转换mp-14708.cif
正在转换mp-1475.cif
正在转换mp-14763.cif
正在转换mp-14785.cif
正在转换mp-1482.cif
正在转换mp-14842.cif
正在转换mp-1484.cif
正在转换mp-14928.cif
正在转换mp-15002.cif
正在转换mp-1501.cif
正在转换mp-1521.cif
正在转换mp-15050.cif
正在转换mp-15051.cif
正在转换mp-15065.cif
正在转换mp-15095.cif
正在转换mp-15141.cif
正在转换mp-15186.cif
正在转换mp-15227.cif
正在转换mp-15237.cif
正在转换mp-1523.cif
正在转换mp-15269.cif
正在转换mp-15318.cif
正在转换mp-15323.cif
正在转换mp-15326.cif
正在转换mp-154.cif
正在转换mp-1552.cif
正在转换mp-15549.cif
正在转换mp-15588.cif
正在转换mp-1559.cif
正在转换mp-15613.cif
正在转换mp-15614.cif
正在转换mp-15626.cif
正在转换mp-1562.cif
正在转换mp-15644.cif
正在转换mp-15695.cif
正在转换mp-15698.cif
正在转换mp-15706.cif
正在转换mp-15707.cif
正在转换mp-15727.cif
正在转换mp-15812.cif
正在转换mp-15813.cif
正在转换mp-15819.cif
正在转换mp-15826.cif
正在转换mp-15827.cif
正在转换mp-15842.cif
正在转换mp-15846.cif
正在转换mp-15885.cif
正在转换mp-15886.cif
正在转换mp-15887.cif
正在转换mp-15898.cif
正在转换mp-1590.cif
正在转换mp-15964.cif
正在转换mp-15973.cif
正在转换mp-16044.cif
正在转换mp-16045.cif
正在转换mp-1604.cif
正在转换mp-16307.cif
正在转换mp-1632.cif
正在转换mp-16377.cif
正在转换mp-1637.cif
正在转换mp-1642.cif
正在转换mp-16430.cif
正在转换mp-16431.cif
正在转换mp-16478.cif
正在转换mp-16483.cif
正在转换mp-16488.cif
正在转换mp-1648.cif
正在转换mp-16491.cif
正在转换mp-16498.cif
正在转换mp-16502.cif
正在转换mp-16504.cif
正在转换mp-16507.cif
正在转换mp-16509.cif
正在转换mp-16518.cif
正在转换mp-16520.cif
正在转换mp-16528.cif
正在转换mp-16529.cif
正在转换mp-16544.cif
正在转换mp-16577.cif
正在转换mp-1659.cif
正在转换mp-16608.cif
正在转换mp-16621.cif
正在转换mp-16622.cif
正在转换mp-16623.cif
正在转换mp-16624.cif
正在转换mp-16625.cif
正在转换mp-16626.cif
正在转换mp-16627.cif
正在转换mp-16638.cif
正在转换mp-16646.cif
正在转换mp-16648.cif
正在转换mp-16652.cif
正在转换mp-16705.cif
正在转换mp-16718.cif
正在转换mp-16719.cif
正在转换mp-16721.cif
正在转换mp-16744.cif
正在转换mp-16756.cif
正在转换mp-16771.cif
正在转换mp-1677.cif
正在转换mp-16792.cif
正在转换mp-16793.cif
正在转换mp-16807.cif
正在转换mp-16818.cif
正在转换mp-16821.cif
正在转换mp-16842.cif
正在转换mp-16848.cif
正在转换mp-16852.cif
正在转换mp-16863.cif
正在转换mp-1689.cif
正在转换mp-16984.cif
正在转换mp-16995.cif
正在转换mp-17037.cif
正在转换mp-17045.cif
正在转换mp-17141.cif
正在转换mp-17167.cif
正在转换mp-17168.cif
正在转换mp-17190.cif
正在转换mp-17208.cif
正在转换mp-17220.cif
正在转换mp-17229.cif
正在转换mp-17236.cif
正在转换mp-17283.cif
正在转换mp-17288.cif
正在转换mp-17297.cif
正在转换mp-17304.cif

正在转换mp-17307.cif
正在转换mp-17308.cif
正在转换mp-17313.cif
正在转换mp-17315.cif
正在转换mp-17319.cif
正在转换mp-17349.cif
正在转换mp-17371.cif
正在转换mp-17375.cif
正在转换mp-17381.cif
正在转换mp-17382.cif
正在转换mp-17396.cif
正在转换mp-173.cif
正在转换mp-17402.cif
正在转换mp-17413.cif
正在转换mp-17418.cif
正在转换mp-17424.cif
正在转换mp-17429.cif
正在转换mp-17434.cif
正在转换mp-17439.cif
正在转换mp-17446.cif
正在转换mp-17447.cif
正在转换mp-17448.cif
正在转换mp-17449.cif
正在转换mp-17455.cif
正在转换mp-17464.cif
正在转换mp-17466.cif
正在转换mp-17473.cif
正在转换mp-17474.cif
正在转换mp-17481.cif
正在转换mp-17485.cif
正在转换mp-17490.cif
正在转换mp-17493.cif
正在转换mp-17499.cif
正在转换mp-17504.cif
正在转换mp-17513.cif
正在转换mp-1767.cif
正在转换mp-17516.cif
正在转换mp-17559.cif
正在转换mp-17562.cif
正在转换mp-17564.cif
正在转换mp-17569.cif
正在转换mp-17578.cif
正在转换mp-17638.cif
正在转换mp-17639.cif
正在转换mp-17649.cif
正在转换mp-17650.cif
正在转换mp-17651.cif
正在转换mp-17666.cif
正在转换mp-17668.cif
正在转换mp-17672.cif
正在转换mp-17673.cif
正在转换mp-17676.cif
正在转换mp-17677.cif
正在转换mp-17685.cif
正在转换mp-17693.cif
正在转换mp-17695.cif
正在转换mp-17697.cif
正在转换mp-17702.cif
正在转换mp-17704.cif
正在转换mp-17706.cif
正在转换mp-17715.cif
正在转换mp-17741.cif
正在转换mp-17746.cif
正在转换mp-17750.cif
正在转换mp-17751.cif
正在转换mp-17753.cif
正在转换mp-17761.cif
正在转换mp-17771.cif
正在转换mp-17774.cif
正在转换mp-17777.cif
正在转换mp-1777.cif
正在转换mp-17784.cif
正在转换mp-17792.cif
正在转换mp-17801.cif
正在转换mp-17803.cif
正在转换mp-17838.cif
正在转换mp-17841.cif
正在转换mp-1791.cif
正在转换mp-17989.cif
正在转换mp-1800.cif
正在转换mp-18065.cif
正在转换mp-18082.cif
正在转换mp-18100.cif
正在转换mp-18101.cif
正在转换mp-18104.cif
正在转换mp-18112.cif
正在转换mp-18127.cif
正在转换mp-18132.cif
正在转换mp-18133.cif
正在转换mp-18134.cif
正在转换mp-18135.cif
正在转换mp-18139.cif
正在转换mp-1813.cif
正在转换mp-18147.cif
正在转换mp-18148.cif
正在转换mp-1818.cif
正在转换mp-18198.cif
正在转换mp-1822.cif
正在转换mp-1823.cif
正在转换mp-1824.cif
正在转换mp-1827.cif
正在转换mp-1828.cif
正在转换mp-18302.cif
正在转换mp-18316.cif
正在转换mp-1831.cif
正在转换mp-18330.cif
正在转换mp-18347.cif
正在转换mp-1841.cif
正在转换mp-1842.cif
正在转换mp-18450.cif
正在转换mp-18451.cif
正在转换mp-1845.cif
正在转换mp-18462.cif
正在转换mp-1849.cif
正在转换mp-18542.cif
正在转换mp-1857.cif
正在转换mp-18614.cif
正在转换mp-18636.cif
正在转换mp-1865.cif
正在转换mp-1866.cif
正在转换mp-1867.cif
正在转换mp-18748.cif
正在转换mp-1878.cif
正在转换mp-1882.cif
正在转换mp-18859.cif
正在转换mp-1885.cif
正在转换mp-1886.cif
正在转换mp-1887.cif
正在转换mp-1890.cif
正在转换mp-1894.cif
正在转换mp-18959.cif
正在转换mp-18965.cif
正在转换mp-18973.cif
正在转换mp-18974.cif
正在转换mp-18975.cif
正在转换mp-1898.cif
正在转换mp-18995.cif
正在转换mp-1900.cif
正在转换mp-1901.cif
正在转换mp-1903.cif
正在转换mp-19056.cif
正在转换mp-19075.cif
正在转换mp-1910.cif
正在转换mp-1911.cif
正在转换mp-1913.cif
正在转换mp-1914.cif
正在转换mp-1915.cif
正在转换mp-1918.cif
正在转换mp-19217.cif
正在转换mp-1921.cif
正在转换mp-1924.cif
正在转换mp-19258.cif
正在转换mp-19265.cif
正在转换mp-1926.cif
正在转换mp-1927.cif
正在转换mp-1929.cif
正在转换mp-19306.cif
正在转换mp-1932.cif
正在转换mp-19337.cif
正在转换mp-1934.cif
正在转换mp-1935.cif
正在转换mp-1936.cif
正在转换mp-19375.cif
正在转换mp-1937.cif
正在转换mp-19385.cif
正在转换mp-19393.cif
正在转换mp-1939.cif
正在转换mp-19424.cif
正在转换mp-19460.cif
正在转换mp-19471.cif
正在转换mp-19477.cif
正在转换mp-1949.cif
正在转换mp-1953.cif
正在转换mp-1955.cif
正在转换mp-1956.cif
正在转换mp-19580.cif
正在转换mp-19599.cif
正在转换mp-1959.cif
正在转换mp-19603.cif
正在转换mp-19623.cif
正在转换mp-19634.cif
正在转换mp-1963.cif
正在转换mp-19642.cif
正在转换mp-19667.cif
正在转换mp-19697.cif
正在转换mp-1969.cif
正在转换mp-196.cif
正在转换mp-19700.cif
正在转换mp-19706.cif
正在转换mp-1971.cif
正在转换mp-19725.cif
正在转换mp-19728.cif
正在转换mp-1973.cif
正在转换mp-1974.cif
正在转换mp-19767.cif
正在转换mp-1976.cif
正在转换mp-1977.cif
正在转换mp-19788.cif
正在转换mp-19789.cif
正在转换mp-19792.cif
正在转换mp-19796.cif
正在转换mp-1979.cif
正在转换mp-19806.cif
正在转换mp-1980.cif
正在转换mp-1981.cif
正在转换mp-19841.cif
正在转换mp-19844.cif
正在转换mp-19866.cif
正在转换mp-19873.cif
正在转换mp-19891.cif
正在转换mp-1989.cif
正在转换mp-19905.cif
正在转换mp-19906.cif
正在转换mp-1990.cif
正在转换mp-19915.cif
正在转换mp-19922.cif
正在转换mp-19924.cif
正在转换mp-19927.cif
正在转换mp-19931.cif
正在转换mp-1994.cif
正在转换mp-19950.cif
正在转换mp-19955.cif
正在转换mp-19967.cif
正在转换mp-19986.cif
正在转换mp-19987.cif
正在转换mp-20000.cif
正在转换mp-20001.cif
正在转换mp-2000.cif
正在转换mp-20043.cif
正在转换mp-20048.cif
正在转换mp-20067.cif
正在转换mp-2006.cif
正在转换mp-20108.cif
正在转换mp-20118.cif
正在转换mp-20123.cif
正在转换mp-2012.cif
正在转换mp-2013.cif
正在转换mp-20144.cif
正在转换mp-20147.cif
正在转换mp-2014.cif
正在转换mp-20150.cif
正在转换mp-20163.cif
正在转换mp-2016.cif
正在转换mp-2017.cif
正在转换mp-20181.cif
正在转换mp-20192.cif
正在转换mp-201.cif
正在转换mp-20201.cif
正在转换mp-20226.cif
正在转换mp-20241.cif
正在转换mp-20250.cif
正在转换mp-20255.cif
正在转换mp-2025.cif
正在转换mp-2026.cif
正在转换mp-2027.cif
正在转换mp-20281.cif
正在转换mp-20308.cif
正在转换mp-2031.cif
正在转换mp-20326.cif
正在转换mp-20327.cif
正在转换mp-20335.cif
正在转换mp-2033.cif
正在转换mp-20355.cif
正在转换mp-20378.cif
正在转换mp-20383.cif
正在转换mp-2039.cif
正在转换mp-20410.cif
正在转换mp-20416.cif
正在转换mp-2041.cif
正在转换mp-20436.cif
正在转换mp-20465.cif
正在转换mp-20467.cif
正在转换mp-20471.cif
正在转换mp-20490.cif
正在转换mp-20492.cif
正在转换mp-2049.cif
正在转换mp-2050.cif
正在转换mp-20517.cif
正在转换mp-20524.cif
正在转换mp-20525.cif
正在转换mp-2052.cif
正在转换mp-2053.cif
正在转换mp-20540.cif
正在转换mp-20548.cif
正在转换mp-2054.cif
正在转换mp-2056.cif
正在转换mp-20571.cif
正在转换mp-2057.cif
正在转换mp-2058.cif
正在转换mp-2059.cif
正在转换mp-2061.cif
正在转换mp-20645.cif
正在转换mp-20648.cif
正在转换mp-20657.cif
正在转换mp-20669.cif
正在转换mp-20673.cif
正在转换mp-2067.cif
正在转换mp-20689.cif
正在转换mp-206.cif
正在转换mp-20705.cif
正在转换mp-2070.cif
正在转换mp-20733.cif
正在转换mp-20777.cif
正在转换mp-20784.cif
正在转换mp-2078.cif
正在转换mp-20792.cif
正在转换mp-20800.cif
正在转换mp-20809.cif
正在转换mp-2080.cif
正在转换mp-20819.cif
正在转换mp-2082.cif
正在转换mp-20836.cif
正在转换mp-20838.cif
正在转换mp-2083.cif
正在转换mp-20841.cif
正在转换mp-20843.cif
正在转换mp-20847.cif
正在转换mp-20868.cif
正在转换mp-2086.cif
正在转换mp-20870.cif
正在转换mp-20887.cif
正在转换mp-20888.cif
正在转换mp-2088.cif
正在转换mp-20892.cif
正在转换mp-20899.cif
正在转换mp-20901.cif
正在转换mp-20905.cif
正在转换mp-20908.cif
正在转换mp-2090.cif
正在转换mp-20916.cif
正在转换mp-20917.cif
正在转换mp-2091.cif
正在转换mp-2092.cif
正在转换mp-20932.cif
正在转换mp-20937.cif
正在转换mp-20947.cif
正在转换mp-20948.cif
正在转换mp-20949.cif
正在转换mp-2096.cif
正在转换mp-20987.cif
正在转换mp-2098.cif
正在转换mp-21010.cif
正在转换mp-21012.cif
正在转换mp-21023.cif
正在转换mp-21041.cif
正在转换mp-21044.cif
正在转换mp-2104.cif
正在转换mp-21052.cif
正在转换mp-21053.cif
正在转换mp-2105.cif
正在转换mp-21066.cif
正在转换mp-21069.cif
正在转换mp-21073.cif
正在转换mp-21081.cif
正在转换mp-2108.cif
正在转换mp-21101.cif
正在转换mp-21104.cif
正在转换mp-21124.cif
正在转换mp-21134.cif
正在转换mp-21136.cif
正在转换mp-21144.cif
正在转换mp-21153.cif
正在转换mp-21157.cif
正在转换mp-21164.cif
正在转换mp-21165.cif
正在转换mp-2116.cif
正在转换mp-21170.cif
正在转换mp-21178.cif
正在转换mp-21199.cif
正在转换mp-21205.cif
正在转换mp-2120.cif
正在转换mp-21217.cif
正在转换mp-2121.cif
正在转换mp-21222.cif
正在转换mp-21227.cif
正在转换mp-21236.cif
正在转换mp-2123.cif
正在转换mp-21248.cif
正在转换mp-2126.cif
正在转换mp-21296.cif
正在转换mp-21297.cif
正在转换mp-21306.cif
正在转换mp-2130.cif
正在转换mp-21321.cif
正在转换mp-2132.cif
正在转换mp-21336.cif
正在转换mp-21347.cif
正在转换mp-21350.cif
正在转换mp-2137.cif
正在转换mp-2142.cif
正在转换mp-2143.cif
正在转换mp-21449.cif
正在转换mp-2147.cif
正在转换mp-2149.cif
正在转换mp-21504.cif
正在转换mp-2151.cif
正在转换mp-2152.cif
正在转换mp-2154.cif
正在转换mp-2157.cif
正在转换mp-2159.cif
正在转换mp-21604.cif
正在转换mp-21613.cif
正在转换mp-21618.cif
正在转换mp-2163.cif
正在转换mp-21658.cif
正在转换mp-2165.cif
正在转换mp-21660.cif
正在转换mp-21666.cif
正在转换mp-2167.cif
正在转换mp-216.cif
正在转换mp-2170.cif
正在转换mp-2178.cif
正在转换mp-2180.cif
正在转换mp-2183.cif
正在转换mp-21851.cif
正在转换mp-21852.cif
正在转换mp-2186.cif
正在转换mp-21876.cif
正在转换mp-2187.cif
正在转换mp-21885.cif
正在转换mp-21893.cif
正在转换mp-21894.cif
正在转换mp-21895.cif
正在转换mp-218.cif
正在转换mp-21900.cif
正在转换mp-21901.cif
正在转换mp-21911.cif
正在转换mp-2191.cif
正在转换mp-2195.cif
正在转换mp-2197.cif
正在转换mp-2199.cif
正在转换mp-22014.cif
正在转换mp-22019.cif
正在转换mp-22033.cif
正在转换mp-22035.cif
正在转换mp-22036.cif
正在转换mp-22041.cif
正在转换mp-22044.cif
正在转换mp-22050.cif
正在转换mp-22051.cif
正在转换mp-2205.cif
正在转换mp-22062.cif
正在转换mp-2206.cif
正在转换mp-22084.cif
正在转换mp-22094.cif
正在转换mp-2209.cif
正在转换mp-2211.cif
正在转换mp-22129.cif
正在转换mp-2212.cif
正在转换mp-2213.cif
正在转换mp-2214.cif
正在转换mp-22150.cif
正在转换mp-22151.cif
正在转换mp-2215.cif
正在转换mp-22162.cif
正在转换mp-22164.cif
正在转换mp-22204.cif
正在转换mp-2221.cif
正在转换mp-22222.cif
正在转换mp-22227.cif
正在转换mp-22228.cif
正在转换mp-22236.cif
正在转换mp-22238.cif
正在转换mp-22247.cif
正在转换mp-22250.cif
正在转换mp-22251.cif
正在转换mp-22258.cif
正在转换mp-22259.cif
正在转换mp-22262.cif
正在转换mp-22267.cif
正在转换mp-2226.cif
正在转换mp-22275.cif
正在转换mp-22284.cif
正在转换mp-22286.cif
正在转换mp-22287.cif
正在转换mp-22293.cif
正在转换mp-22295.cif
正在转换mp-22299.cif
正在转换mp-22302.cif
正在转换mp-22307.cif
正在转换mp-22315.cif
正在转换mp-22319.cif
正在转换mp-22324.cif
正在转换mp-22326.cif
正在转换mp-22337.cif
正在转换mp-2234.cif
正在转换mp-22352.cif
正在转换mp-2235.cif
正在转换mp-22360.cif
正在转换mp-22361.cif
正在转换mp-22385.cif
正在转换mp-2238.cif
正在转换mp-22390.cif
正在转换mp-22395.cif
正在转换mp-22418.cif
正在转换mp-22425.cif
正在转换mp-22426.cif
正在转换mp-22433.cif
正在转换mp-22434.cif
正在转换mp-22438.cif
正在转换mp-22440.cif
正在转换mp-22441.cif
正在转换mp-22442.cif
正在转换mp-22451.cif
正在转换mp-22453.cif
正在转换mp-22457.cif
正在转换mp-22479.cif
正在转换mp-22482.cif
正在转换mp-22489.cif
正在转换mp-22490.cif
正在转换mp-22497.cif

正在转换mp-2249.cif
正在转换mp-22522.cif
正在转换mp-2258.cif
正在转换mp-22600.cif
正在转换mp-2260.cif
正在转换mp-22617.cif
正在转换mp-22619.cif
正在转换mp-22622.cif
正在转换mp-22625.cif
正在转换mp-22636.cif
正在转换mp-22637.cif
正在转换mp-2264.cif
正在转换mp-22658.cif
正在转换mp-22670.cif
正在转换mp-2267.cif
正在转换mp-2268.cif
正在转换mp-22708.cif
正在转换mp-22709.cif
正在转换mp-22722.cif
正在转换mp-22755.cif
正在转换mp-22758.cif
正在转换mp-22759.cif
正在转换mp-22775.cif
正在转换mp-22785.cif
正在转换mp-22794.cif
正在转换mp-22801.cif
正在转换mp-22803.cif
正在转换mp-2281.cif
正在转换mp-2283.cif
正在转换mp-22862.cif
正在转换mp-2288.cif
正在转换mp-22905.cif
正在转换mp-2290.cif
正在转换mp-2291.cif
正在转换mp-2294.cif
正在转换mp-2295.cif
正在转换mp-22968.cif
正在转换mp-23012.cif
正在转换mp-2301.cif
正在转换mp-23051.cif
正在转换mp-23085.cif
正在转换mp-23145.cif
正在转换mp-23147.cif
正在转换mp-23149.cif
正在转换mp-23175.cif
正在转换mp-23179.cif
正在转换mp-23217.cif
正在转换mp-23235.cif
正在转换mp-23283.cif
正在转换mp-23310.cif
正在转换mp-23314.cif
正在转换mp-23319.cif
正在转换mp-23326.cif
正在转换mp-23331.cif
正在转换mp-23426.cif
正在转换mp-23432.cif
正在转换mp-23519.cif
正在转换mp-23560.cif
正在转换mp-23612.cif
正在转换mp-23655.cif
正在转换mp-23656.cif
正在转换mp-23672.cif
正在转换mp-23700.cif
正在转换mp-23738.cif
正在转换mp-23740.cif
正在转换mp-23743.cif
正在转换mp-23778.cif
正在转换mp-23794.cif
正在转换mp-23798.cif
正在转换mp-23846.cif
正在转换mp-23959.cif
正在转换mp-24041.cif
正在转换mp-24113.cif
正在转换mp-24123.cif
正在转换mp-24199.cif
正在转换mp-24239.cif
正在转换mp-24336.cif
正在转换mp-2452.cif
正在转换mp-2454.cif
正在转换mp-2473.cif
正在转换mp-2480.cif
正在转换mp-2514.cif
正在转换mp-2538.cif
正在转换mp-2542.cif
正在转换mp-254.cif
正在转换mp-2571.cif
正在转换mp-2585.cif
正在转换mp-2591.cif
正在转换mp-25.cif
正在转换mp-2610.cif
正在转换mp-2622.cif
正在转换mp-2625.cif
正在转换mp-2651.cif
正在转换mp-2652.cif
正在转换mp-2681.cif
正在转换mp-2714.cif
正在转换mp-2719.cif
正在转换mp-27258.cif
正在转换mp-2733.cif
正在转换mp-2741.cif
正在转换mp-2750.cif
正在转换mp-2760.cif
正在转换mp-2772.cif
正在转换mp-2811.cif
正在转换mp-2824.cif
正在转换mp-2832.cif
正在转换mp-2836.cif
正在转换mp-2847.cif
正在转换mp-2856.cif
正在转换mp-2889.cif
正在转换mp-2932.cif
正在转换mp-2940.cif
正在转换mp-2943.cif
正在转换mp-2955.cif
正在转换mp-2956.cif
正在转换mp-2958.cif
正在转换mp-2960.cif
正在转换mp-2973.cif
正在转换mp-3009.cif
正在转换mp-3032.cif
正在转换mp-30337.cif
正在转换mp-3042.cif
正在转换mp-30438.cif
正在转换mp-30441.cif
正在转换mp-3045.cif
正在转换mp-3054.cif
正在转换mp-30623.cif
正在转换mp-30673.cif
正在转换mp-30684.cif
正在转换mp-30686.cif
正在转换mp-30730.cif
正在转换mp-3073.cif
正在转换mp-30780.cif
正在转换mp-30791.cif
正在转换mp-3079.cif
正在转换mp-3081.cif
正在转换mp-30840.cif
正在转换mp-30846.cif
正在转换mp-3084.cif
正在转换mp-30882.cif
正在转换mp-30892.cif
正在转换mp-30893.cif
正在转换mp-308.cif
正在转换mp-31043.cif
正在转换mp-31064.cif
正在转换mp-31090.cif
正在转换mp-31095.cif
正在转换mp-31097.cif
正在转换mp-31167.cif
正在转换mp-31181.cif
正在转换mp-3129.cif
正在转换mp-31385.cif
正在转换mp-31408.cif
正在转换mp-3142.cif
正在转换mp-31488.cif
正在转换mp-314.cif
正在转换mp-3151.cif
正在转换mp-3154.cif
正在转换mp-3164.cif
正在转换mp-3204.cif
正在转换mp-32873.cif
正在转换mp-3291.cif
正在转换mp-3297.cif
正在转换mp-3315.cif
正在转换mp-3318.cif
正在转换mp-3352.cif
正在转换mp-3363.cif
正在转换mp-337.cif
正在转换mp-3400.cif
正在转换mp-34078.cif
正在转换mp-34081.cif
正在转换mp-3411.cif
正在转换mp-3414.cif
正在转换mp-3416.cif
正在转换mp-34291.cif
正在转换mp-3448.cif
正在转换mp-34579.cif
正在转换mp-34763.cif
正在转换mp-35082.cif
正在转换mp-3520.cif
正在转换mp-3521.cif
正在转换mp-3529.cif
正在转换mp-3536.cif
正在转换mp-3545.cif
正在转换mp-35659.cif
正在转换mp-3569.cif
正在转换mp-35759.cif
正在转换mp-35777.cif
正在转换mp-3581.cif
正在转换mp-3582.cif
正在转换mp-3589.cif
正在转换mp-36209.cif
正在转换mp-36262.cif
正在转换mp-36508.cif
正在转换mp-36526.cif
正在转换mp-3654.cif
正在转换mp-3669.cif
正在转换mp-36751.cif
正在转换mp-3679.cif
正在转换mp-36884.cif
正在转换mp-37216.cif
正在转换mp-37458.cif
正在转换mp-3747.cif
正在转换mp-37620.cif
正在转换mp-37692.cif
正在转换mp-37722.cif
正在转换mp-3775.cif
正在转换mp-3787.cif
正在转换mp-37920.cif
正在转换mp-37949.cif
正在转换mp-3802.cif
正在转换mp-38070.cif
正在转换mp-38240.cif
正在转换mp-3824.cif
正在转换mp-38280.cif
正在转换mp-38322.cif
正在转换mp-38487.cif
正在转换mp-3857.cif
正在转换mp-38683.cif
正在转换mp-38684.cif
正在转换mp-38725.cif
正在转换mp-3880.cif
正在转换mp-38951.cif
正在转换mp-39033.cif
正在转换mp-39105.cif
正在转换mp-3925.cif
正在转换mp-392.cif
正在转换mp-393.cif
正在转换mp-3949.cif
正在转换mp-3951.cif
正在转换mp-3954.cif
正在转换mp-3975.cif
正在转换mp-3978.cif
正在转换mp-3991.cif
正在转换mp-4001.cif
正在转换mp-4002.cif
正在转换mp-4006.cif
正在转换mp-4016.cif
正在转换mp-4019.cif
正在转换mp-4022.cif
正在转换mp-4054.cif
正在转换mp-4071.cif
正在转换mp-4091.cif
正在转换mp-4096.cif
正在转换mp-4104.cif
正在转换mp-4107.cif
正在转换mp-4117.cif
正在转换mp-411.cif
正在转换mp-4157.cif
正在转换mp-4172.cif
正在转换mp-4179.cif
正在转换mp-4185.cif
正在转换mp-4194.cif
正在转换mp-4202.cif
正在转换mp-4212.cif
正在转换mp-42190.cif
正在转换mp-4243.cif
正在转换mp-4251.cif
正在转换mp-4276.cif
正在转换mp-4289.cif
正在转换mp-4298.cif
正在转换mp-4308.cif
正在转换mp-433.cif
正在转换mp-4340.cif
正在转换mp-4341.cif
正在转换mp-4353.cif
正在转换mp-4363.cif
正在转换mp-4368.cif
正在转换mp-4371.cif
正在转换mp-4376.cif
正在转换mp-4377.cif
正在转换mp-4396.cif
正在转换mp-4406.cif
正在转换mp-4417.cif
正在转换mp-4474.cif
正在转换mp-4478.cif
正在转换mp-4500.cif
正在转换mp-4502.cif
正在转换mp-4529.cif
正在转换mp-452.cif
正在转换mp-4556.cif
正在转换mp-4589.cif
正在转换mp-458.cif
正在转换mp-4591.cif
正在转换mp-4604.cif
正在转换mp-4606.cif
正在转换mp-4609.cif
正在转换mp-4622.cif
正在转换mp-4632.cif
正在转换mp-463.cif
正在转换mp-4648.cif
正在转换mp-4667.cif
正在转换mp-4672.cif
正在转换mp-468.cif
正在转换mp-4703.cif
正在转换mp-4721.cif
正在转换mp-4752.cif
正在转换mp-4753.cif
正在转换mp-4755.cif
正在转换mp-4758.cif
正在转换mp-4769.cif
正在转换mp-4779.cif
正在转换mp-4794.cif
正在转换mp-4804.cif
正在转换mp-4829.cif
正在转换mp-4855.cif
正在转换mp-4864.cif
正在转换mp-504711.cif
正在转换mp-504751.cif
正在转换mp-504801.cif
正在转换mp-504806.cif
正在转换mp-504810.cif
正在转换mp-504835.cif
正在转换mp-504894.cif
正在转换mp-504908.cif
正在转换mp-504921.cif
正在转换mp-504964.cif
正在转换mp-504970.cif
正在转换mp-505001.cif
正在转换mp-505005.cif
正在转换mp-505019.cif
正在转换mp-505142.cif
正在转换mp-505365.cif
正在转换mp-505373.cif
正在转换mp-505381.cif
正在转换mp-505489.cif
正在转换mp-505502.cif
正在转换mp-505511.cif
正在转换mp-505515.cif
正在转换mp-505517.cif
正在转换mp-505527.cif
正在转换mp-505534.cif
正在转换mp-505536.cif
正在转换mp-505538.cif
正在转换mp-505540.cif
正在转换mp-505551.cif
正在转换mp-505552.cif
正在转换mp-505554.cif
正在转换mp-505558.cif
正在转换mp-505569.cif
正在转换mp-505570.cif
正在转换mp-505589.cif
正在转换mp-505597.cif
正在转换mp-505598.cif
正在转换mp-505680.cif
正在转换mp-505683.cif
正在转换mp-505720.cif
正在转换mp-505727.cif
正在转换mp-505747.cif
正在转换mp-505767.cif
正在转换mp-505791.cif
正在转换mp-505820.cif
正在转换mp-510002.cif
正在转换mp-510028.cif
正在转换mp-510073.cif
正在转换mp-510076.cif
正在转换mp-510083.cif
正在转换mp-510084.cif
正在转换mp-510085.cif
正在转换mp-510086.cif
正在转换mp-510133.cif
正在转换mp-510152.cif
正在转换mp-510209.cif
正在转换mp-510232.cif
正在转换mp-510280.cif
正在转换mp-510367.cif
正在转换mp-510376.cif
正在转换mp-510409.cif
正在转换mp-510437.cif
正在转换mp-510441.cif
正在转换mp-510482.cif
正在转换mp-510484.cif
正在转换mp-510486.cif
正在转换mp-510503.cif
正在转换mp-510519.cif
正在转换mp-510548.cif
正在转换mp-510564.cif
正在转换mp-510574.cif
正在转换mp-510589.cif
正在转换mp-510615.cif
正在转换mp-510619.cif
正在转换mp-510646.cif
正在转换mp-510666.cif
正在转换mp-510687.cif
正在转换mp-510688.cif
正在转换mp-510691.cif
正在转换mp-510713.cif
正在转换mp-530399.cif
正在转换mp-530.cif
正在转换mp-5335.cif
正在转换mp-5376.cif
正在转换mp-5382.cif
正在转换mp-540631.cif
正在转换mp-540632.cif
正在转换mp-540634.cif
正在转换mp-540635.cif
正在转换mp-540676.cif
正在转换mp-540734.cif
正在转换mp-540783.cif
正在转换mp-540784.cif
正在转换mp-540809.cif
正在转换mp-540827.cif
正在转换mp-540834.cif
正在转换mp-5408.cif
正在转换mp-540905.cif
正在转换mp-540912.cif
正在转换mp-540924.cif
正在转换mp-540950.cif
正在转换mp-540996.cif
正在转换mp-540997.cif
正在转换mp-540998.cif
正在转换mp-541013.cif
正在转换mp-541022.cif
正在转换mp-541040.cif
正在转换mp-541047.cif
正在转换mp-541066.cif
正在转换mp-541094.cif
正在转换mp-541106.cif
正在转换mp-541155.cif
正在转换mp-541368.cif
正在转换mp-541462.cif
正在转换mp-541588.cif
正在转换mp-541671.cif
正在转换mp-541721.cif
正在转换mp-541743.cif
正在转换mp-541813.cif
正在转换mp-541817.cif
正在转换mp-541823.cif
正在转换mp-541849.cif
正在转换mp-541852.cif
正在转换mp-541853.cif
正在转换mp-541856.cif
正在转换mp-5418.cif
正在转换mp-541938.cif
正在转换mp-541963.cif
正在转换mp-541971.cif
正在转换mp-542003.cif
正在转换mp-5426.cif
正在转换mp-542028.cif
正在转换mp-542103.cif
正在转换mp-542132.cif
正在转换mp-542136.cif
正在转换mp-542154.cif
正在转换mp-542172.cif
正在转换mp-542177.cif
正在转换mp-542201.cif
正在转换mp-542432.cif
正在转换mp-542443.cif
正在转换mp-542445.cif
正在转换mp-542454.cif
正在转换mp-542455.cif
正在转换mp-542463.cif
正在转换mp-542512.cif
正在转换mp-542569.cif
正在转换mp-542680.cif
正在转换mp-542728.cif
正在转换mp-5427.cif
正在转换mp-542810.cif
正在转换mp-542816.cif
正在转换mp-542879.cif
正在转换mp-542885.cif
正在转换mp-542915.cif
正在转换mp-542928.cif
正在转换mp-542932.cif
正在转换mp-5450.cif
正在转换mp-545529.cif
正在转换mp-545544.cif
正在转换mp-545728.cif
正在转换mp-545847.cif
正在转换mp-545999.cif
正在转换mp-546011.cif
正在转换mp-546082.cif
正在转换mp-546125.cif
正在转换mp-546152.cif
正在转换mp-546266.cif
正在转换mp-546321.cif
正在转换mp-546350.cif
正在转换mp-546500.cif
正在转换mp-546621.cif
正在转换mp-546625.cif
正在转换mp-546794.cif
正在转换mp-546864.cif
正在转换mp-547125.cif
正在转换mp-547244.cif
正在转换mp-5473.cif
正在转换mp-547792.cif
正在转换mp-548469.cif
正在转换mp-549127.cif
正在转换mp-549333.cif
正在转换mp-549475.cif
正在转换mp-549487.cif
正在转换mp-549490.cif
正在转换mp-549697.cif
正在转换mp-549709.cif
正在转换mp-549728.cif
正在转换mp-549737.cif
正在转换mp-550111.cif
正在转换mp-550635.cif
正在转换mp-550685.cif
正在转换mp-550751.cif
正在转换mp-550805.cif
正在转换mp-550820.cif
正在转换mp-550925.cif
正在转换mp-550.cif
正在转换mp-551092.cif
正在转换mp-551101.cif
正在转换mp-551203.cif
正在转换mp-551243.cif
正在转换mp-551250.cif
正在转换mp-551456.cif
正在转换mp-551675.cif
正在转换mp-551816.cif

正在转换mp-551826.cif
正在转换mp-551835.cif
正在转换mp-551873.cif
正在转换mp-551900.cif
正在转换mp-552008.cif
正在转换mp-552016.cif
正在转换mp-552028.cif
正在转换mp-552098.cif
正在转换mp-552191.cif
正在转换mp-552234.cif
正在转换mp-552292.cif
正在转换mp-552537.cif
正在转换mp-552547.cif
正在转换mp-552604.cif
正在转换mp-552663.cif
正在转换mp-552738.cif
正在转换mp-552806.cif
正在转换mp-552857.cif
正在转换mp-552934.cif
正在转换mp-552963.cif
正在转换mp-552992.cif
正在转换mp-553025.cif
正在转换mp-553082.cif
正在转换mp-553242.cif
正在转换mp-553243.cif
正在转换mp-553961.cif
正在转换mp-554023.cif
正在转换mp-554041.cif
正在转换mp-554063.cif
正在转换mp-554095.cif
正在转换mp-554097.cif
正在转换mp-554098.cif
正在转换mp-554121.cif
正在转换mp-554144.cif
正在转换mp-554168.cif
正在转换mp-554199.cif
正在转换mp-554252.cif
正在转换mp-554310.cif
正在转换mp-554311.cif
正在转换mp-554327.cif
正在转换mp-554332.cif
正在转换mp-554337.cif
正在转换mp-554517.cif
正在转换mp-554542.cif
正在转换mp-554545.cif
正在转换mp-555212.cif
正在转换mp-555225.cif
正在转换mp-555228.cif
正在转换mp-555234.cif
正在转换mp-555272.cif
正在转换mp-555318.cif
正在转换mp-555434.cif
正在转换mp-555476.cif
正在转换mp-555480.cif
正在转换mp-555495.cif
正在转换mp-555509.cif
正在转换mp-555527.cif
正在转换mp-555678.cif
正在转换mp-555718.cif
正在转换mp-555736.cif
正在转换mp-555741.cif
正在转换mp-555750.cif
正在转换mp-555764.cif
正在转换mp-5557.cif
正在转换mp-555805.cif
正在转换mp-555812.cif
正在转换mp-555833.cif
正在转换mp-555836.cif
正在转换mp-555840.cif
正在转换mp-555850.cif
正在转换mp-555851.cif
正在转换mp-555852.cif
正在转换mp-555863.cif
正在转换mp-555871.cif
正在转换mp-555874.cif
正在转换mp-555880.cif
正在转换mp-555893.cif
正在转换mp-555900.cif
正在转换mp-555901.cif
正在转换mp-555903.cif
正在转换mp-555909.cif
正在转换mp-555933.cif
正在转换mp-555936.cif
正在转换mp-555942.cif
正在转换mp-555954.cif
正在转换mp-555970.cif
正在转换mp-555974.cif
正在转换mp-555977.cif
正在转换mp-555978.cif
正在转换mp-556006.cif
正在转换mp-556017.cif
正在转换mp-556024.cif
正在转换mp-556046.cif
正在转换mp-556049.cif
正在转换mp-556058.cif
正在转换mp-556065.cif
正在转换mp-556108.cif
正在转换mp-556120.cif
正在转换mp-556125.cif
正在转换mp-556134.cif
正在转换mp-556139.cif
正在转换mp-556169.cif
正在转换mp-556179.cif
正在转换mp-556185.cif
正在转换mp-556189.cif
正在转换mp-556233.cif
正在转换mp-556258.cif
正在转换mp-556264.cif
正在转换mp-556275.cif
正在转换mp-556282.cif
正在转换mp-556316.cif
正在转换mp-556369.cif
正在转换mp-556407.cif
正在转换mp-556418.cif
正在转换mp-556421.cif
正在转换mp-556422.cif
正在转换mp-556434.cif
正在转换mp-556438.cif
正在转换mp-556443.cif
正在转换mp-556450.cif
正在转换mp-556487.cif
正在转换mp-556488.cif
正在转换mp-556489.cif
正在转换mp-556500.cif
正在转换mp-556517.cif
正在转换mp-556525.cif
正在转换mp-556536.cif
正在转换mp-556546.cif
正在转换mp-556560.cif
正在转换mp-556577.cif
正在转换mp-556630.cif
正在转换mp-556631.cif
正在转换mp-556649.cif
正在转换mp-556653.cif
正在转换mp-556655.cif
正在转换mp-556661.cif
正在转换mp-556665.cif
正在转换mp-556672.cif
正在转换mp-556674.cif
正在转换mp-556679.cif
正在转换mp-556689.cif
正在转换mp-556695.cif
正在转换mp-556699.cif
正在转换mp-556705.cif
正在转换mp-556709.cif
正在转换mp-556712.cif
正在转换mp-556717.cif
正在转换mp-556719.cif
正在转换mp-556721.cif
正在转换mp-556726.cif
正在转换mp-556741.cif
正在转换mp-556744.cif
正在转换mp-556748.cif
正在转换mp-556761.cif
正在转换mp-556781.cif
正在转换mp-556791.cif
正在转换mp-556797.cif
正在转换mp-556798.cif
正在转换mp-556810.cif
正在转换mp-556814.cif
正在转换mp-556820.cif
正在转换mp-556834.cif
正在转换mp-556855.cif
正在转换mp-556866.cif
正在转换mp-556975.cif
正在转换mp-557023.cif
正在转换mp-557121.cif
正在转换mp-557391.cif
正在转换mp-557399.cif
正在转换mp-557401.cif
正在转换mp-557403.cif
正在转换mp-557407.cif
正在转换mp-557410.cif
正在转换mp-557411.cif
正在转换mp-557414.cif
正在转换mp-557417.cif
正在转换mp-557426.cif
正在转换mp-557432.cif
正在转换mp-557436.cif
正在转换mp-557437.cif
正在转换mp-557441.cif
正在转换mp-557448.cif
正在转换mp-557456.cif
正在转换mp-557457.cif
正在转换mp-557458.cif
正在转换mp-557463.cif
正在转换mp-557467.cif
正在转换mp-557468.cif
正在转换mp-557472.cif
正在转换mp-557481.cif
正在转换mp-557482.cif
正在转换mp-557483.cif
正在转换mp-557485.cif
正在转换mp-557498.cif
正在转换mp-557506.cif
正在转换mp-557517.cif
正在转换mp-557522.cif
正在转换mp-557531.cif
正在转换mp-557537.cif
正在转换mp-557540.cif
正在转换mp-557543.cif
正在转换mp-557552.cif
正在转换mp-557561.cif
正在转换mp-557569.cif
正在转换mp-557577.cif
正在转换mp-557583.cif
正在转换mp-557584.cif
正在转换mp-557615.cif
正在转换mp-557618.cif
正在转换mp-557632.cif
正在转换mp-557637.cif
正在转换mp-557640.cif
正在转换mp-557649.cif
正在转换mp-557650.cif
正在转换mp-557656.cif
正在转换mp-557662.cif
正在转换mp-557665.cif
正在转换mp-557673.cif
正在转换mp-557686.cif
正在转换mp-557689.cif
正在转换mp-557697.cif
正在转换mp-557698.cif
正在转换mp-557715.cif
正在转换mp-557728.cif
正在转换mp-557733.cif
正在转换mp-557735.cif
正在转换mp-557743.cif
正在转换mp-557744.cif
正在转换mp-557753.cif
正在转换mp-557761.cif
正在转换mp-557763.cif
正在转换mp-557773.cif
正在转换mp-557777.cif
正在转换mp-557809.cif
正在转换mp-557832.cif
正在转换mp-557839.cif
正在转换mp-557845.cif
正在转换mp-557855.cif
正在转换mp-557856.cif
正在转换mp-557871.cif
正在转换mp-557918.cif
正在转换mp-557993.cif
正在转换mp-557997.cif
正在转换mp-557998.cif
正在转换mp-558023.cif
正在转换mp-558042.cif
正在转换mp-558045.cif
正在转换mp-558050.cif
正在转换mp-558059.cif
正在转换mp-558078.cif
正在转换mp-558085.cif
正在转换mp-558099.cif
正在转换mp-558102.cif
正在转换mp-558121.cif
正在转换mp-558143.cif
正在转换mp-558162.cif
正在转换mp-558195.cif
正在转换mp-558198.cif
正在转换mp-558206.cif
正在转换mp-558219.cif
正在转换mp-558227.cif
正在转换mp-558243.cif
正在转换mp-558244.cif
正在转换mp-558248.cif
正在转换mp-558257.cif
正在转换mp-558259.cif
正在转换mp-558281.cif
正在转换mp-558298.cif
正在转换mp-558309.cif
正在转换mp-558317.cif
正在转换mp-558330.cif
正在转换mp-558332.cif
正在转换mp-558340.cif
正在转换mp-558349.cif
正在转换mp-558362.cif
正在转换mp-558378.cif
正在转换mp-558392.cif
正在转换mp-558491.cif
正在转换mp-558547.cif
正在转换mp-558674.cif
正在转换mp-558781.cif
正在转换mp-558815.cif
正在转换mp-558826.cif
正在转换mp-5588.cif
正在转换mp-558928.cif
正在转换mp-558980.cif
正在转换mp-558988.cif
正在转换mp-558990.cif
正在转换mp-558992.cif
正在转换mp-559025.cif
正在转换mp-559067.cif
正在转换mp-559084.cif
正在转换mp-559106.cif
正在转换mp-559109.cif
正在转换mp-559126.cif
正在转换mp-5602.cif
正在转换mp-559150.cif
正在转换mp-559151.cif
正在转换mp-559160.cif
正在转换mp-559184.cif
正在转换mp-559186.cif
正在转换mp-559187.cif
正在转换mp-559198.cif
正在转换mp-559200.cif
正在转换mp-559203.cif
正在转换mp-559227.cif
正在转换mp-559237.cif
正在转换mp-559243.cif
正在转换mp-559246.cif
正在转换mp-559249.cif
正在转换mp-559254.cif
正在转换mp-559257.cif
正在转换mp-559259.cif
正在转换mp-559270.cif
正在转换mp-559282.cif
正在转换mp-559284.cif
正在转换mp-559286.cif
正在转换mp-559304.cif
正在转换mp-559327.cif
正在转换mp-559336.cif
正在转换mp-559348.cif
正在转换mp-559352.cif
正在转换mp-559364.cif
正在转换mp-559377.cif
正在转换mp-559378.cif
正在转换mp-559379.cif
正在转换mp-559383.cif
正在转换mp-559388.cif
正在转换mp-559405.cif
正在转换mp-559426.cif
正在转换mp-559427.cif
正在转换mp-559442.cif
正在转换mp-559446.cif
正在转换mp-559463.cif
正在转换mp-559489.cif
正在转换mp-559514.cif
正在转换mp-559519.cif
正在转换mp-559533.cif
正在转换mp-559534.cif
正在转换mp-559539.cif
正在转换mp-559584.cif
正在转换mp-559633.cif
正在转换mp-559635.cif
正在转换mp-559643.cif
正在转换mp-559663.cif
正在转换mp-559701.cif
正在转换mp-559712.cif
正在转换mp-559724.cif
正在转换mp-561.cif
正在转换mp-5628.cif
正在转换mp-562.cif
正在转换mp-5641.cif
正在转换mp-5659.cif
正在转换mp-5670.cif
正在转换mp-5765.cif
正在转换mp-5767.cif
正在转换mp-5773.cif
正在转换mp-5821.cif
正在转换mp-5831.cif
正在转换mp-5853.cif
正在转换mp-5884.cif
正在转换mp-5925.cif
正在转换mp-5926.cif
正在转换mp-5950.cif
正在转换mp-5971.cif
正在转换mp-5984.cif
正在转换mp-6015.cif
正在转换mp-6030.cif
正在转换mp-6040.cif
正在转换mp-6058.cif
正在转换mp-6062.cif
正在转换mp-606.cif
正在转换mp-6071.cif
正在转换mp-6072.cif
正在转换mp-6074.cif
正在转换mp-6113.cif
正在转换mp-6134.cif
正在转换mp-6135.cif
正在转换mp-619.cif
正在转换mp-6253.cif
正在转换mp-625.cif
正在转换mp-6280.cif
正在转换mp-6345.cif
正在转换mp-637.cif
正在转换mp-6459.cif
正在转换mp-6486.cif
正在转换mp-6500.cif
正在转换mp-6520.cif
正在转换mp-6533.cif
正在转换mp-6586.cif
正在转换mp-6591.cif
正在转换mp-6595.cif
正在转换mp-6655.cif
正在转换mp-6686.cif
正在转换mp-6723.cif
正在转换mp-6739.cif
正在转换mp-679.cif
正在转换mp-6800.cif
正在转换mp-6820.cif
正在转换mp-682.cif
正在转换mp-683.cif
正在转换mp-6856.cif
正在转换mp-6870.cif
正在转换mp-6916.cif
正在转换mp-6939.cif
正在转换mp-6952.cif
正在转换mp-7012.cif
正在转换mp-7013.cif
正在转换mp-7080.cif
正在转换mp-7085.cif
正在转换mp-7116.cif
正在转换mp-7124.cif
正在转换mp-7127.cif
正在转换mp-723.cif
正在转换mp-7241.cif
正在转换mp-7273.cif
正在转换mp-7281.cif
正在转换mp-7302.cif
正在转换mp-7310.cif
正在转换mp-7317.cif
正在转换mp-7323.cif
正在转换mp-7332.cif
正在转换mp-7342.cif
正在转换mp-7379.cif
正在转换mp-7384.cif
正在转换mp-7385.cif
正在转换mp-738.cif
正在转换mp-746.cif
正在转换mp-754.cif
正在转换mp-7560.cif
正在转换mp-7561.cif
正在转换mp-7564.cif
正在转换mp-7571.cif
正在转换mp-7572.cif
正在转换mp-7610.cif
正在转换mp-7661.cif
正在转换mp-7693.cif
正在转换mp-7791.cif
正在转换mp-7810.cif
正在转换mp-7817.cif
正在转换mp-7818.cif
正在转换mp-787.cif
正在转换mp-793.cif
正在转换mp-799.cif
正在转换mp-812.cif
正在转换mp-844.cif
正在转换mp-855.cif
正在转换mp-8667.cif
正在转换mp-8670.cif
正在转换mp-8688.cif
正在转换mp-8689.cif
正在转换mp-8771.cif
正在转换mp-8772.cif
正在转换mp-8786.cif
正在转换mp-8787.cif
正在转换mp-878.cif
正在转换mp-8812.cif
正在转换mp-8858.cif
正在转换mp-8861.cif
正在转换mp-8864.cif
正在转换mp-888.cif
正在转换mp-8896.cif
正在转换mp-8914.cif
正在转换mp-8952.cif
正在转换mp-9039.cif
正在转换mp-9077.cif
正在转换mp-9078.cif
正在转换mp-9132.cif
正在转换mp-9143.cif
正在转换mp-9144.cif
正在转换mp-9208.cif
正在转换mp-9227.cif
正在转换mp-9278.cif
正在转换mp-9319.cif
正在转换mp-9324.cif
正在转换mp-9325.cif
正在转换mp-9353.cif
正在转换mp-9417.cif
正在转换mp-9420.cif
正在转换mp-9421.cif
正在转换mp-943.cif
正在转换mp-9440.cif
正在转换mp-9454.cif
正在转换mp-9459.cif
正在转换mp-9460.cif
正在转换mp-9486.cif
正在转换mp-950.cif

正在转换mp-9521.cif
正在转换mp-9529.cif
正在转换mp-9530.cif
正在转换mp-9545.cif
正在转换mp-9546.cif
正在转换mp-9559.cif
正在转换mp-9584.cif
正在转换mp-9625.cif
正在转换mp-9694.cif
正在转换mp-9710.cif
正在转换mp-9711.cif
正在转换mp-9726.cif
正在转换mp-9741.cif
正在转换mp-9746.cif
正在转换mp-979.cif
正在转换mp-9801.cif
正在转换mp-9816.cif
正在转换mp-9819.cif
正在转换mp-981.cif
正在转换mp-983.cif
正在转换mp-9848.cif
正在转换mp-9880.cif
正在转换mp-9888.cif
正在转换mp-9895.cif
正在转换mp-9901.cif
正在转换mp-9902.cif
正在转换mp-9909.cif
正在转换mp-9913.cif
正在转换mp-9918.cif
正在转换mp-9952.cif
正在转换mp-9976.cif
正在转换mp-9977.cif
正在转换mp-9981.cif
正在转换mvc-10960.cif
正在转换mvc-11744.cif
正在转换mvc-15272.cif
正在转换mvc-15683.cif
正在转换mvc-16026.cif
正在转换mvc-16523.cif
正在转换mvc-16742.cif
正在转换mvc-4409.cif
正在转换mvc-4467.cif
正在转换mvc-5784.cif
正在转换mp-1001113.cif
正在转换mp-1001570.cif
正在转换mp-10018.cif
正在转换mp-10021.cif
正在转换mp-10023.cif
正在转换mp-10024.cif
正在转换mp-1007760.cif
正在转换mp-1007866.cif
正在转换mp-1008283.cif
正在转换mp-1008374.cif
正在转换mp-1008394.cif
正在转换mp-1008395.cif
正在转换mp-1008498.cif
正在转换mp-1008501.cif
正在转换mp-1008634.cif
正在转换mp-1008669.cif
正在转换mp-1008681.cif
正在转换mp-1008728.cif
正在转换mp-1008733.cif
正在转换mp-1009460.cif
正在转换mp-1009490.cif
正在转换mp-1009594.cif
正在转换mp-100.cif
正在转换mp-1010048.cif
正在转换mp-1010136.cif
正在转换mp-1014013.cif
正在转换mp-1014212.cif
正在转换mp-10157.cif
正在转换mp-10172.cif
正在转换mp-10173.cif
正在转换mp-1017981.cif
正在转换mp-1018045.cif
正在转换mp-1018088.cif
正在转换mp-1018122.cif
正在转换mp-1018134.cif
正在转换mp-10190.cif
正在转换mp-101.cif
正在转换mp-10207.cif
正在转换mp-1022725.cif
正在转换mp-1023923.cif
正在转换mp-10257.cif
正在转换mp-102.cif
正在转换mp-103.cif
正在转换mp-104.cif
正在转换mp-10597.cif
正在转换mp-105.cif
正在转换mp-10617.cif
正在转换mp-10630.cif
正在转换mp-10631.cif
正在转换mp-10641.cif
正在转换mp-10649.cif
正在转换mp-10654.cif
正在转换mp-10658.cif
正在转换mp-10659.cif
正在转换mp-10660.cif
正在转换mp-10661.cif
正在转换mp-10679.cif
正在转换mp-10683.cif
正在转换mp-10740.cif
正在转换mp-10750.cif
正在转换mp-10751.cif
正在转换mp-10752.cif
正在转换mp-10753.cif
正在转换mp-10765.cif
正在转换mp-107.cif
正在转换mp-10861.cif
正在转换mp-10869.cif
正在转换mp-108.cif
正在转换mp-109.cif
正在转换mp-10.cif
正在转换mp-110.cif
正在转换mp-111.cif
正在转换mp-112.cif
正在转换mp-11334.cif
正在转换mp-11343.cif
正在转换mp-113.cif
正在转换mp-11446.cif
正在转换mp-114.cif
正在转换mp-11534.cif
正在转换mp-11698.cif
正在转换mp-117.cif
正在转换mp-118.cif
正在转换mp-119.cif
正在转换mp-11.cif
正在转换mp-12093.cif

C:\Users\mk\AppData\Roaming\Python\Python39\site-packages\pymatgen\core\periodic_table.py:212: UserWarning: No electronegativity for Ne. Setting to NaN. This has no physical meaning, and is mainly done to avoid errors caused by the code expecting a float.
  warnings.warn(
C:\Users\mk\AppData\Roaming\Python\Python39\site-packages\pymatgen\core\periodic_table.py:212: UserWarning: No electronegativity for Ar. Setting to NaN. This has no physical meaning, and is mainly done to avoid errors caused by the code expecting a float.
  warnings.warn(

正在转换mp-12103.cif
正在转换mp-121.cif
正在转换mp-122.cif
正在转换mp-123.cif
正在转换mp-124.cif
正在转换mp-12628.cif
正在转换mp-126.cif
正在转换mp-12771.cif
正在转换mp-127.cif
正在转换mp-12883.cif
正在转换mp-128.cif
正在转换mp-12957.cif
正在转换mp-129.cif
正在转换mp-130.cif
正在转换mp-131.cif
正在转换mp-132.cif
正在转换mp-133.cif
正在转换mp-134.cif
正在转换mp-135.cif
正在转换mp-136.cif
正在转换mp-137.cif
正在转换mp-139.cif
正在转换mp-13.cif
正在转换mp-140.cif
正在转换mp-141.cif
正在转换mp-142.cif
正在转换mp-143.cif
正在转换mp-144.cif
正在转换mp-145.cif
正在转换mp-146.cif
正在转换mp-147.cif
正在转换mp-149.cif
正在转换mp-14.cif
正在转换mp-150.cif
正在转换mp-151.cif
正在转换mp-153.cif
正在转换mp-156.cif
正在转换mp-157.cif
正在转换mp-159.cif
正在转换mp-160.cif
正在转换mp-16220.cif
正在转换mp-162.cif
正在转换mp-165.cif
正在转换mp-166.cif
正在转换mp-168.cif
正在转换mp-169.cif
正在转换mp-17.cif
正在转换mp-18.cif
正在转换mp-19858.cif
正在转换mp-19.cif
正在转换mp-20372.cif
正在转换mp-20483.cif
正在转换mp-20537.cif
正在转换mp-20736.cif
正在转换mp-20745.cif
正在转换mp-20.cif
正在转换mp-21377.cif
正在转换mp-21848.cif
正在转换mp-21.cif
正在转换mp-22692.cif
正在转换mp-22848.cif
正在转换mp-23152.cif
正在转换mp-23153.cif
正在转换mp-23154.cif
正在转换mp-23155.cif
正在转换mp-23156.cif
正在转换mp-23157.cif
正在转换mp-23158.cif
正在转换mp-23907.cif
正在转换mp-23.cif
正在转换mp-24504.cif
正在转换mp-24.cif
正在转换mp-26.cif
正在转换mp-27.cif
正在转换mp-28.cif
正在转换mp-2.cif
正在转换mp-30.cif
正在转换mp-32.cif
正在转换mp-33.cif
正在转换mp-34.cif
正在转换mp-35.cif
正在转换mp-36.cif
正在转换mp-37.cif
正在转换mp-38.cif
正在转换mp-39.cif
正在转换mp-41.cif
正在转换mp-42.cif
正在转换mp-44.cif
正在转换mp-45.cif
正在转换mp-46.cif
正在转换mp-47.cif
正在转换mp-49.cif
正在转换mp-4.cif
正在转换mp-50.cif
正在转换mp-51.cif
正在转换mp-53.cif
正在转换mp-542461.cif
正在转换mp-542605.cif
正在转换mp-542909.cif
正在转换mp-54.cif
正在转换mp-555760.cif
正在转换mp-557376.cif
正在转换mp-55.cif
正在转换mp-560602.cif
正在转换mp-561203.cif
正在转换mp-561367.cif
正在转换mp-567144.cif
正在转换mp-567308.cif
正在转换mp-567313.cif
正在转换mp-567332.cif
正在转换mp-567337.cif
正在转换mp-567365.cif
正在转换mp-567409.cif
正在转换mp-567597.cif
正在转换mp-567630.cif
正在转换mp-567772.cif
正在转换mp-567826.cif
正在转换mp-568087.cif
正在转换mp-568145.cif
正在转换mp-568286.cif
正在转换mp-568345.cif
正在转换mp-568410.cif
正在转换mp-568584.cif
正在转换mp-568610.cif
正在转换mp-568714.cif
正在转换mp-568938.cif
正在转换mp-569289.cif
正在转换mp-569360.cif
正在转换mp-569423.cif
正在转换mp-569517.cif
正在转换mp-569567.cif
正在转换mp-56.cif
正在转换mp-570002.cif
正在转换mp-570316.cif
正在转换mp-570384.cif
正在转换mp-570459.cif
正在转换mp-570510.cif
正在转换mp-570602.cif
正在转换mp-570747.cif
正在转换mp-570752.cif
正在转换mp-571249.cif
正在转换mp-571261.cif
正在转换mp-571520.cif
正在转换mp-573691.cif
正在转换mp-582819.cif
正在转换mp-58.cif
正在转换mp-601148.cif
正在转换mp-601273.cif
正在转换mp-604313.cif
正在转换mp-604318.cif
正在转换mp-604321.cif
正在转换mp-604325.cif
正在转换mp-604573.cif
正在转换mp-605790.cif
正在转换mp-607540.cif
正在转换mp-610917.cif
正在转换mp-611219.cif
正在转换mp-611426.cif
正在转换mp-611448.cif
正在转换mp-611517.cif
正在转换mp-611836.cif
正在转换mp-612118.cif
正在转换mp-614456.cif
正在转换mp-616440.cif
正在转换mp-62.cif
正在转换mp-632172.cif
正在转换mp-632286.cif
正在转换mp-632291.cif
正在转换mp-632401.cif
正在转换mp-634659.cif
正在转换mp-639747.cif
正在转换mp-639751.cif
正在转换mp-639755.cif
正在转换mp-639774.cif
正在转换mp-63.cif
正在转换mp-644693.cif
正在转换mp-64.cif
正在转换mp-656615.cif
正在转换mp-672233.cif
正在转换mp-672234.cif
正在转换mp-673171.cif
正在转换mp-674158.cif
正在转换mp-67.cif
正在转换mp-680372.cif
正在转换mp-684663.cif
正在转换mp-684673.cif
正在转换mp-68.cif
正在转换mp-6985.cif
正在转换mp-6986.cif
正在转换mp-69.cif
正在转换mp-7098.cif
正在转换mp-70.cif
正在转换mp-7162.cif
正在转换mp-7163.cif
正在转换mp-71.cif
正在转换mp-7236.cif
正在转换mp-7245.cif
正在转换mp-72.cif
正在转换mp-73.cif
正在转换mp-74.cif
正在转换mp-753304.cif
正在转换mp-754382.cif
正在转换mp-754417.cif
正在转换mp-75.cif
正在转换mp-76.cif
正在转换mp-7755.cif
正在转换mp-7761.cif
正在转换mp-78.cif
正在转换mp-79.cif
正在转换mp-7.cif
正在转换mp-81.cif
正在转换mp-82.cif
正在转换mp-84.cif
正在转换mp-850274.cif
正在转换mp-8566.cif
正在转换mp-85.cif
正在转换mp-862690.cif
正在转换mp-8632.cif
正在转换mp-8633.cif
正在转换mp-8634.cif
正在转换mp-8635.cif
正在转换mp-8636.cif
正在转换mp-8637.cif
正在转换mp-8638.cif
正在转换mp-8639.cif
正在转换mp-8640.cif
正在转换mp-8641.cif
正在转换mp-8642.cif
正在转换mp-8643.cif
正在转换mp-867126.cif
正在转换mp-867200.cif
正在转换mp-867202.cif
正在转换mp-867351.cif
正在转换mp-86.cif
正在转换mp-87.cif
正在转换mp-88.cif
正在转换mp-89.cif
正在转换mp-8.cif
正在转换mp-90.cif
正在转换mp-91.cif
正在转换mp-92.cif
正在转换mp-94.cif
正在转换mp-95.cif
正在转换mp-971661.cif
正在转换mp-971662.cif
正在转换mp-971769.cif
正在转换mp-972351.cif
正在转换mp-972364.cif
正在转换mp-972373.cif
正在转换mp-972981.cif
正在转换mp-973111.cif
正在转换mp-973198.cif
正在转换mp-973364.cif
正在转换mp-973571.cif
正在转换mp-973783.cif
正在转换mp-973916.cif
正在转换mp-973986.cif
正在转换mp-974400.cif
正在转换mp-974558.cif
正在转换mp-974620.cif
正在转换mp-974788.cif
正在转换mp-974920.cif
正在转换mp-975065.cif
正在转换mp-975129.cif
正在转换mp-975204.cif
正在转换mp-975272.cif
正在转换mp-975519.cif
正在转换mp-975590.cif
正在转换mp-976347.cif
正在转换mp-976411.cif
正在转换mp-979285.cif
正在转换mp-979286.cif
正在转换mp-97.cif
正在转换mp-981544.cif
正在转换mp-982370.cif
正在转换mp-982872.cif
正在转换mp-989695.cif
正在转换mp-989737.cif
正在转换mp-9924.cif
正在转换mp-998860.cif
正在转换mp-998861.cif
正在转换mp-998864.cif
正在转换mp-998866.cif
正在转换mp-998881.cif
正在转换mp-998883.cif
正在转换mp-998890.cif
正在转换mp-999200.cif
正在转换mp-999498.cif
正在转换mp-999501.cif
正在转换mp-99.cif
正在转换mp-9.cif
正在转换mp-BiVO4.cif
正在转换mp-CZTS.cif
正在转换mp-CZTSe.cif
正在转换mp-FAPbI3.cif
正在转换mp-MAPbI3-Cubic.cif
正在转换mp-cubic-CH3NH3PbBr3.cif
正在转换mp-cubic-CH3NH3PbCl3.cif
正在转换mp-cubic-FAPbI3.cif
正在转换mp-cubic-HPbI3.cif
正在转换mp-10000.cif
正在转换mp-10008.cif
正在转换mp-10010.cif
正在转换mp-10015.cif
正在转换mp-10020.cif
正在转换mp-10026.cif
正在转换mp-10030.cif
正在转换mp-10032.cif
正在转换mp-10036.cif
正在转换mp-10037.cif
正在转换mp-10038.cif
正在转换mp-10039.cif
正在转换mp-10040.cif
正在转换mp-10041.cif
正在转换mp-10046.cif
正在转换mp-1004.cif
正在转换mp-10052.cif
正在转换mp-10054.cif
正在转换mp-10060.cif
正在转换mp-10061.cif
正在转换mp-1007.cif
正在转换mp-10087.cif
正在转换mp-10092.cif
正在转换mp-10098.cif
正在转换mp-10105.cif
正在转换mp-10106.cif
正在转换mp-10108.cif
正在转换mp-10109.cif
正在转换mp-1010.cif
正在转换mp-10110.cif
正在转换mp-10113.cif
正在转换mp-10115.cif
正在转换mp-10116.cif
正在转换mp-10118.cif
正在转换mp-10120.cif
正在转换mp-10125.cif
正在转换mp-10132.cif
正在转换mp-10133.cif
正在转换mp-10134.cif
正在转换mp-10135.cif
正在转换mp-10139.cif
正在转换mp-10140.cif
正在转换mp-10141.cif
正在转换mp-10142.cif
正在转换mp-10143.cif
正在转换mp-10148.cif
正在转换mp-10149.cif
正在转换mp-10154.cif
正在转换mp-10177.cif
正在转换mp-10178.cif
正在转换mp-10179.cif
正在转换mp-1017.cif
正在转换mp-10180.cif
正在转换mp-10181.cif
正在转换mp-10183.cif
正在转换mp-10184.cif
正在转换mp-10185.cif
正在转换mp-10186.cif
正在转换mp-10187.cif
正在转换mp-10189.cif
正在转换mp-10192.cif
正在转换mp-10193.cif
正在转换mp-10194.cif
正在转换mp-10195.cif
正在转换mp-10196.cif
正在转换mp-10197.cif
正在转换mp-10198.cif
正在转换mp-1019.cif
正在转换mp-10200.cif
正在转换mp-10201.cif
正在转换mp-10204.cif
正在转换mp-10208.cif
正在转换mp-10209.cif
正在转换mp-1020.cif
正在转换mp-10212.cif
正在转换mp-10214.cif
正在转换mp-10224.cif
正在转换mp-10225.cif
正在转换mp-10229.cif
正在转换mp-10232.cif
正在转换mp-10247.cif
正在转换mp-10254.cif
正在转换mp-10256.cif
正在转换mp-1025.cif
正在转换mp-10260.cif
正在转换mp-10261.cif
正在转换mp-10264.cif
正在转换mp-10266.cif
正在转换mp-10270.cif
正在转换mp-10271.cif
正在转换mp-10274.cif
正在转换mp-10275.cif
正在转换mp-10279.cif
正在转换mp-1027.cif
正在转换mp-10280.cif
正在转换mp-10286.cif
正在转换mp-10287.cif
正在转换mp-1028.cif
正在转换mp-10300.cif
正在转换mp-1030.cif
正在转换mp-10311.cif
正在转换mp-10312.cif
正在转换mp-10316.cif
正在转换mp-1032.cif
正在转换mp-1033.cif
正在转换mp-10343.cif
正在转换mp-10351.cif
正在转换mp-10356.cif
正在转换mp-10365.cif
正在转换mp-10367.cif
正在转换mp-1036.cif
正在转换mp-10373.cif
正在转换mp-10374.cif
正在转换mp-10376.cif
正在转换mp-10379.cif
正在转换mp-1038.cif
正在转换mp-10393.cif
正在转换mp-10394.cif
正在转换mp-10405.cif
正在转换mp-1042.cif
正在转换mp-10435.cif
正在转换mp-10436.cif
正在转换mp-10441.cif
正在转换mp-10443.cif
正在转换mp-10445.cif
正在转换mp-10446.cif
正在转换mp-1044.cif
正在转换mp-10450.cif
正在转换mp-10453.cif
正在转换mp-10454.cif
正在转换mp-10455.cif
正在转换mp-1048.cif
正在转换mp-10498.cif
正在转换mp-10516.cif
正在转换mp-10521.cif
正在转换mp-10527.cif
正在转换mp-10528.cif
正在转换mp-10529.cif
正在转换mp-1052.cif
正在转换mp-10530.cif
正在转换mp-1053.cif
正在转换mp-1054.cif
正在转换mp-10554.cif
正在转换mp-1055.cif
正在转换mp-10564.cif
正在转换mp-1057.cif
正在转换mp-10581.cif
正在转换mp-1058.cif
正在转换mp-10596.cif
正在转换mp-10598.cif
正在转换mp-10601.cif
正在转换mp-10602.cif
正在转换mp-10606.cif
正在转换mp-10607.cif
正在转换mp-10608.cif
正在转换mp-10609.cif
正在转换mp-10622.cif
正在转换mp-10624.cif
正在转换mp-10626.cif
正在转换mp-10629.cif
正在转换mp-10632.cif
正在转换mp-10633.cif
正在转换mp-10634.cif
正在转换mp-10635.cif
正在转换mp-10636.cif
正在转换mp-10637.cif
正在转换mp-10646.cif
正在转换mp-10647.cif
正在转换mp-10651.cif
正在转换mp-10652.cif
正在转换mp-10666.cif
正在转换mp-10668.cif
正在转换mp-10669.cif
正在转换mp-10670.cif
正在转换mp-10674.cif
正在转换mp-10675.cif
正在转换mp-10677.cif
正在转换mp-10684.cif
正在转换mp-10685.cif
正在转换mp-10686.cif
正在转换mp-10687.cif
正在转换mp-10688.cif
正在转换mp-10692.cif
正在转换mp-10697.cif
正在转换mp-10698.cif
正在转换mp-10699.cif
正在转换mp-10700.cif
正在转换mp-10706.cif
正在转换mp-10708.cif
正在转换mp-10711.cif
正在转换mp-10712.cif
正在转换mp-10714.cif
正在转换mp-10718.cif
正在转换mp-10735.cif
正在转换mp-10736.cif
正在转换mp-10738.cif
正在转换mp-10739.cif
正在转换mp-10749.cif
正在转换mp-10755.cif
正在转换mp-10756.cif
正在转换mp-10764.cif
正在转换mp-10769.cif
正在转换mp-10797.cif
正在转换mp-10816.cif
正在转换mp-10824.cif
正在转换mp-10845.cif
正在转换mp-10860.cif
正在转换mp-10862.cif
正在转换mp-10866.cif
正在转换mp-10867.cif
正在转换mp-10868.cif
正在转换mp-10871.cif
正在转换mp-10872.cif
正在转换mp-10873.cif
正在转换mp-10879.cif
正在转换mp-10881.cif
正在转换mp-10883.cif
正在转换mp-10884.cif
正在转换mp-10885.cif
正在转换mp-10886.cif
正在转换mp-10887.cif
正在转换mp-10889.cif
正在转换mp-10890.cif
正在转换mp-10891.cif
正在转换mp-10892.cif
正在转换mp-10893.cif
正在转换mp-10894.cif
正在转换mp-10895.cif
正在转换mp-10898.cif
正在转换mp-10899.cif
正在转换mp-10901.cif
正在转换mp-10902.cif
正在转换mp-10903.cif
正在转换mp-10904.cif
正在转换mp-10905.cif
正在转换mp-10907.cif
正在转换mp-10909.cif
正在转换mp-10964.cif
正在转换mp-10965.cif
正在转换mp-10988.cif
正在转换mp-10989.cif
正在转换mp-10991.cif
正在转换mp-10992.cif
正在转换mp-10993.cif
正在转换mp-10994.cif
正在转换mp-11021.cif
正在转换mp-11038.cif
正在转换mp-11069.cif
正在转换mp-11073.cif
正在转换mp-11081.cif
正在转换mp-11091.cif
正在转换mp-11100.cif
正在转换mp-11106.cif
正在转换mp-11113.cif
正在转换mp-11155.cif
正在转换mp-11156.cif
正在转换mp-11157.cif
正在转换mp-11169.cif
正在转换mp-11171.cif
正在转换mp-11172.cif
正在转换mp-11174.cif
正在转换mp-11180.cif
正在转换mp-11190.cif
正在转换mp-11192.cif
正在转换mp-11193.cif
正在转换mp-11194.cif
正在转换mp-11201.cif
正在转换mp-11202.cif
正在转换mp-11203.cif
正在转换mp-11204.cif
正在转换mp-11212.cif
正在转换mp-11220.cif
正在转换mp-11221.cif
正在转换mp-11222.cif
正在转换mp-11226.cif
正在转换mp-11228.cif
正在转换mp-11229.cif
正在转换mp-11231.cif
正在转换mp-11233.cif

正在转换mp-11234.cif
正在转换mp-11235.cif
正在转换mp-11236.cif
正在转换mp-11237.cif
正在转换mp-11239.cif
正在转换mp-11240.cif
正在转换mp-11241.cif
正在转换mp-11242.cif
正在转换mp-11243.cif
正在转换mp-11245.cif
正在转换mp-11247.cif
正在转换mp-11248.cif
正在转换mp-11249.cif
正在转换mp-11252.cif
正在转换mp-11256.cif
正在转换mp-11260.cif
正在转换mp-11261.cif
正在转换mp-11262.cif
正在转换mp-11263.cif
正在转换mp-11266.cif
正在转换mp-11269.cif
正在转换mp-11271.cif
正在转换mp-11274.cif
正在转换mp-11276.cif
正在转换mp-11277.cif
正在转换mp-11278.cif
正在转换mp-11279.cif
正在转换mp-11283.cif
正在转换mp-11284.cif
正在转换mp-11286.cif
正在转换mp-11287.cif
正在转换mp-11290.cif
正在转换mp-11291.cif
正在转换mp-11293.cif
正在转换mp-11294.cif
正在转换mp-11295.cif
正在转换mp-11296.cif
正在转换mp-11299.cif
正在转换mp-11300.cif
正在转换mp-11301.cif
正在转换mp-11302.cif
正在转换mp-11304.cif
正在转换mp-11305.cif
正在转换mp-11307.cif
正在转换mp-11309.cif
正在转换mp-11311.cif
正在转换mp-11312.cif
正在转换mp-11313.cif
正在转换mp-11317.cif
正在转换mp-11318.cif
正在转换mp-11322.cif
正在转换mp-11328.cif
正在转换mp-11329.cif
正在转换mp-11335.cif
正在转换mp-11344.cif
正在转换mp-11345.cif
正在转换mp-11352.cif
正在转换mp-11358.cif
正在转换mp-11359.cif
正在转换mp-11360.cif
正在转换mp-11363.cif
正在转换mp-11365.cif
正在转换mp-11366.cif
正在转换mp-11367.cif
正在转换mp-11369.cif
正在转换mp-11370.cif
正在转换mp-11371.cif
正在转换mp-11372.cif
正在转换mp-11373.cif
正在转换mp-11374.cif
正在转换mp-11382.cif
正在转换mp-11383.cif
正在转换mp-11385.cif
正在转换mp-11387.cif
正在转换mp-11388.cif
正在转换mp-11392.cif
正在转换mp-11397.cif
正在转换mp-11398.cif
正在转换mp-11400.cif
正在转换mp-11401.cif
正在转换mp-11404.cif
正在转换mp-11406.cif
正在转换mp-11407.cif
正在转换mp-11411.cif
正在转换mp-11412.cif
正在转换mp-11413.cif
正在转换mp-11416.cif
正在转换mp-11417.cif
正在转换mp-11418.cif
正在转换mp-11419.cif
正在转换mp-11420.cif
正在转换mp-11435.cif
正在转换mp-11436.cif
正在转换mp-11444.cif
正在转换mp-11447.cif
正在转换mp-11452.cif
正在转换mp-11454.cif
正在转换mp-11455.cif
正在转换mp-11457.cif
正在转换mp-11460.cif
正在转换mp-11461.cif
正在转换mp-11462.cif
正在转换mp-11463.cif
正在转换mp-11464.cif
正在转换mp-11466.cif
正在转换mp-11467.cif
正在转换mp-11468.cif
正在转换mp-11469.cif
正在转换mp-11470.cif
正在转换mp-11471.cif
正在转换mp-11472.cif
正在转换mp-11473.cif
正在转换mp-11474.cif
正在转换mp-11475.cif
正在转换mp-11476.cif
正在转换mp-11477.cif
正在转换mp-11478.cif
正在转换mp-11480.cif
正在转换mp-11481.cif
正在转换mp-11482.cif
正在转换mp-11483.cif
正在转换mp-11487.cif
正在转换mp-11489.cif
正在转换mp-11490.cif
正在转换mp-11492.cif
正在转换mp-11494.cif
正在转换mp-11498.cif
正在转换mp-11500.cif
正在转换mp-11501.cif
正在转换mp-11503.cif
正在转换mp-11504.cif
正在转换mp-11506.cif
正在转换mp-11507.cif
正在转换mp-11512.cif
正在转换mp-11513.cif
正在转换mp-11514.cif
正在转换mp-11515.cif
正在转换mp-11516.cif
正在转换mp-11517.cif
正在转换mp-11519.cif
正在转换mp-11521.cif
正在转换mp-11522.cif
正在转换mp-11523.cif
正在转换mp-11525.cif
正在转换mp-11526.cif
正在转换mp-11531.cif
正在转换mp-11533.cif
正在转换mp-11535.cif
正在转换mp-11536.cif
正在转换mp-11537.cif
正在转换mp-11538.cif
正在转换mp-11539.cif
正在转换mp-11540.cif
正在转换mp-11541.cif
正在转换mp-11546.cif
正在转换mp-11547.cif
正在转换mp-11549.cif
正在转换mp-11554.cif
正在转换mp-11555.cif
正在转换mp-11556.cif
正在转换mp-11561.cif
正在转换mp-11562.cif
正在转换mp-11563.cif
正在转换mp-11564.cif
正在转换mp-11565.cif
正在转换mp-11566.cif
正在转换mp-11568.cif
正在转换mp-11569.cif
正在转换mp-11570.cif
正在转换mp-11572.cif
正在转换mp-11573.cif
正在转换mp-11575.cif
正在转换mp-11576.cif
正在转换mp-11577.cif
正在转换mp-11578.cif
正在转换mp-11580.cif
正在转换mp-11584.cif
正在转换mp-11593.cif
正在转换mp-11594.cif
正在转换mp-11596.cif
正在转换mp-11597.cif
正在转换mp-11615.cif
正在转换mp-11621.cif
正在转换mp-11644.cif
正在转换mp-11651.cif
正在转换mp-11652.cif
正在转换mp-11693.cif
正在转换mp-11697.cif
正在转换mp-11700.cif
正在转换mp-11723.cif
正在转换mp-11743.cif
正在转换mp-11750.cif
正在转换mp-11754.cif
正在转换mp-11755.cif
正在转换mp-11765.cif
正在转换mp-11769.cif
正在转换mp-11770.cif
正在转换mp-11771.cif
正在转换mp-11799.cif
正在转换mp-11800.cif
正在转换mp-11801.cif
正在转换mp-11808.cif
正在转换mp-11809.cif
正在转换mp-11816.cif
正在转换mp-11818.cif
正在转换mp-11822.cif
正在转换mp-11831.cif
正在转换mp-11833.cif
正在转换mp-11834.cif
正在转换mp-11840.cif
正在转换mp-11841.cif
正在转换mp-11843.cif
正在转换mp-11846.cif
正在转换mp-1185.cif
正在转换mp-11860.cif
正在转换mp-11870.cif
正在转换mp-11871.cif
正在转换mp-11873.cif
正在转换mp-1187.cif
正在转换mp-1189.cif
正在转换mp-11927.cif
正在转换mp-11947.cif
正在转换mp-1194.cif
正在转换mp-11971.cif
正在转换mp-11974.cif
正在转换mp-11977.cif
正在转换mp-11984.cif
正在转换mp-11987.cif
正在转换mp-12004.cif
正在转换mp-12005.cif
正在转换mp-12006.cif
正在转换mp-12009.cif
正在转换mp-1200.cif
正在转换mp-12029.cif
正在转换mp-12041.cif
正在转换mp-12049.cif
正在转换mp-12056.cif
正在转换mp-12058.cif
正在转换mp-12059.cif
正在转换mp-12060.cif
正在转换mp-12063.cif
正在转换mp-12067.cif
正在转换mp-12070.cif
正在转换mp-12071.cif
正在转换mp-12073.cif
正在转换mp-12075.cif
正在转换mp-12076.cif
正在转换mp-12077.cif
正在转换mp-12079.cif
正在转换mp-1207.cif
正在转换mp-12080.cif
正在转换mp-12082.cif
正在转换mp-12083.cif
正在转换mp-12084.cif
正在转换mp-12086.cif
正在转换mp-12087.cif
正在转换mp-12088.cif
正在转换mp-1208.cif
正在转换mp-12094.cif
正在转换mp-12097.cif
正在转换mp-12098.cif
正在转换mp-12100.cif
正在转换mp-12101.cif
正在转换mp-12104.cif
正在转换mp-12105.cif
正在转换mp-12107.cif
正在转换mp-12108.cif
正在转换mp-12117.cif
正在转换mp-12118.cif
正在转换mp-1211.cif
正在转换mp-12137.cif
正在转换mp-1219.cif
正在转换mp-1220.cif
正在转换mp-1221.cif
正在转换mp-1231.cif
正在转换mp-1234.cif
正在转换mp-12359.cif
正在转换mp-1235.cif
正在转换mp-12360.cif
正在转换mp-1236.cif
正在转换mp-12381.cif
正在转换mp-12382.cif
正在转换mp-12388.cif
正在转换mp-1240.cif
正在转换mp-12411.cif
正在转换mp-1246.cif
正在转换mp-12505.cif
正在转换mp-1250.cif
正在转换mp-1251.cif
正在转换mp-12520.cif
正在转换mp-12524.cif
正在转换mp-12527.cif
正在转换mp-1252.cif
正在转换mp-12537.cif
正在转换mp-1254.cif
正在转换mp-12550.cif
正在转换mp-12553.cif
正在转换mp-12557.cif
正在转换mp-12559.cif
正在转换mp-12561.cif
正在转换mp-12563.cif
正在转换mp-12564.cif
正在转换mp-12565.cif
正在转换mp-1256.cif
正在转换mp-12571.cif
正在转换mp-12572.cif
正在转换mp-12574.cif
正在转换mp-12580.cif
正在转换mp-12584.cif
正在转换mp-12585.cif
正在转换mp-12586.cif
正在转换mp-12593.cif
正在转换mp-12594.cif
正在转换mp-12595.cif
正在转换mp-12598.cif
正在转换mp-12599.cif
正在转换mp-1259.cif
正在转换mp-12600.cif
正在转换mp-12607.cif
正在转换mp-12608.cif
正在转换mp-12609.cif
正在转换mp-1260.cif
正在转换mp-12625.cif
正在转换mp-12631.cif
正在转换mp-12635.cif
正在转换mp-12636.cif
正在转换mp-1263.cif
正在转换mp-1264.cif
正在转换mp-12651.cif
正在转换mp-12661.cif
正在转换mp-12674.cif
正在转换mp-12675.cif
正在转换mp-12681.cif
正在转换mp-12693.cif
正在转换mp-12696.cif
正在转换mp-1269.cif
正在转换mp-12701.cif
正在转换mp-12703.cif
正在转换mp-12716.cif
正在转换mp-12718.cif
正在转换mp-12719.cif
正在转换mp-1272.cif
正在转换mp-12734.cif
正在转换mp-12736.cif
正在转换mp-12743.cif
正在转换mp-1274.cif
正在转换mp-12751.cif
正在转换mp-12752.cif
正在转换mp-12754.cif
正在转换mp-1275.cif
正在转换mp-12760.cif
正在转换mp-12761.cif
正在转换mp-12762.cif
正在转换mp-12763.cif
正在转换mp-12764.cif
正在转换mp-12772.cif
正在转换mp-12773.cif
正在转换mp-12774.cif
正在转换mp-12775.cif
正在转换mp-12777.cif
正在转换mp-12778.cif
正在转换mp-12783.cif
正在转换mp-12791.cif
正在转换mp-12793.cif
正在转换mp-12798.cif
正在转换mp-12801.cif
正在转换mp-12804.cif
正在转换mp-12806.cif
正在转换mp-1280.cif
正在转换mp-1281.cif
正在转换mp-1282.cif
正在转换mp-12854.cif
正在转换mp-12855.cif
正在转换mp-12856.cif
正在转换mp-12857.cif
正在转换mp-12872.cif
正在转换mp-12874.cif
正在转换mp-12875.cif
正在转换mp-12876.cif
正在转换mp-12884.cif
正在转换mp-12892.cif
正在转换mp-12899.cif
正在转换mp-12900.cif
正在转换mp-12901.cif
正在转换mp-1291.cif
正在转换mp-12921.cif
正在转换mp-12922.cif
正在转换mp-12940.cif
正在转换mp-1294.cif
正在转换mp-12951.cif
正在转换mp-12952.cif
正在转换mp-12961.cif
正在转换mp-12962.cif
正在转换mp-1296.cif
正在转换mp-12972.cif
正在转换mp-12979.cif
正在转换mp-12981.cif
正在转换mp-12982.cif
正在转换mp-12983.cif
正在转换mp-12985.cif
正在转换mp-12986.cif
正在转换mp-12990.cif
正在转换mp-1299.cif
正在转换mp-13018.cif
正在转换mp-1302.cif
正在转换mp-13034.cif
正在转换mp-13035.cif
正在转换mp-13036.cif
正在转换mp-13037.cif
正在转换mp-13041.cif
正在转换mp-13053.cif
正在转换mp-13069.cif
正在转换mp-13070.cif
正在转换mp-13071.cif
正在转换mp-13072.cif
正在转换mp-13074.cif
正在转换mp-13076.cif
正在转换mp-13079.cif
正在转换mp-1307.cif
正在转换mp-13082.cif
正在转换mp-13085.cif
正在转换mp-13089.cif
正在转换mp-13090.cif
正在转换mp-13092.cif
正在转换mp-13094.cif
正在转换mp-13095.cif
正在转换mp-13098.cif
正在转换mp-13100.cif
正在转换mp-1310.cif
正在转换mp-13116.cif
正在转换mp-13117.cif
正在转换mp-13118.cif
正在转换mp-13120.cif
正在转换mp-13132.cif
正在转换mp-13136.cif
正在转换mp-13137.cif
正在转换mp-13138.cif
正在转换mp-13141.cif
正在转换mp-13149.cif
正在转换mp-13154.cif
正在转换mp-13155.cif
正在转换mp-13156.cif
正在转换mp-13161.cif
正在转换mp-13164.cif
正在转换mp-13166.cif
正在转换mp-13172.cif
正在转换mp-13174.cif
正在转换mp-13175.cif
正在转换mp-13202.cif
正在转换mp-13203.cif
正在转换mp-13240.cif
正在转换mp-13254.cif
正在转换mp-13263.cif
正在转换mp-13264.cif
正在转换mp-1326.cif
正在转换mp-13272.cif
正在转换mp-13286.cif
正在转换mp-1328.cif
正在转换mp-13302.cif
正在转换mp-13303.cif
正在转换mp-13306.cif
正在转换mp-13308.cif
正在转换mp-13311.cif
正在转换mp-1331.cif
正在转换mp-13322.cif
正在转换mp-1334.cif
正在转换mp-1335.cif
正在转换mp-1336.cif
正在转换mp-1337.cif
正在转换mp-13392.cif
正在转换mp-13398.cif
正在转换mp-1339.cif
正在转换mp-13405.cif
正在转换mp-13434.cif
正在转换mp-13436.cif
正在转换mp-1343.cif
正在转换mp-13446.cif
正在转换mp-13452.cif
正在转换mp-13453.cif
正在转换mp-13463.cif
正在转换mp-13466.cif
正在转换mp-13467.cif
正在转换mp-13473.cif
正在转换mp-13480.cif
正在转换mp-13496.cif
正在转换mp-1349.cif
正在转换mp-1352.cif
正在转换mp-13535.cif
正在转换mp-13536.cif
正在转换mp-13545.cif
正在转换mp-13572.cif
正在转换mp-1358.cif
正在转换mp-1359.cif
正在转换mp-1363.cif
正在转换mp-1364.cif
正在转换mp-13679.cif
正在转换mp-1373.cif
正在转换mp-1377.cif
正在转换mp-1380.cif
正在转换mp-1383.cif
正在转换mp-1386.cif
正在转换mp-1387.cif
正在转换mp-1388.cif
正在转换mp-13911.cif
正在转换mp-13914.cif
正在转换mp-13918.cif
正在转换mp-1391.cif
正在转换mp-13955.cif
正在转换mp-1395.cif
正在转换mp-13962.cif
正在转换mp-13964.cif
正在转换mp-1399.cif
正在转换mp-1400.cif
正在转换mp-14019.cif
正在转换mp-1401.cif
正在转换mp-14024.cif
正在转换mp-1402.cif
正在转换mp-1405.cif
正在转换mp-1406.cif
正在转换mp-14089.cif
正在转换mp-1408.cif
正在转换mp-1412.cif
正在转换mp-14090.cif
正在转换mp-1416.cif
正在转换mp-1418.cif
正在转换mp-14208.cif
正在转换mp-14209.cif
正在转换mp-1423.cif
正在转换mp-1424.cif
正在转换mp-1425.cif
正在转换mp-1429.cif
正在转换mp-1431.cif

正在转换mp-1432.cif
正在转换mp-1437.cif
正在转换mp-1444.cif
正在转换mp-1447.cif
正在转换mp-1448.cif
正在转换mp-1451.cif
正在转换mp-1453.cif
正在转换mp-14549.cif
正在转换mp-1458.cif
正在转换mp-1459.cif
正在转换mp-14625.cif
正在转换mp-1471.cif
正在转换mp-1472.cif
正在转换mp-1476.cif
正在转换mp-14793.cif
正在转换mp-1481.cif
正在转换mp-1483.cif
正在转换mp-1486.cif
正在转换mp-1487.cif
正在转换mp-1491.cif
正在转换mp-1495.cif
正在转换mp-1497.cif
正在转换mp-1502.cif
正在转换mp-15123.cif
正在转换mp-1514.cif
正在转换mp-1515.cif
正在转换mp-1518.cif
正在转换mp-1525.cif
正在转换mp-1526.cif
正在转换mp-1527.cif
正在转换mp-15293.cif
正在转换mp-15297.cif
正在转换mp-1529.cif
正在转换mp-15322.cif
正在转换mp-15325.cif
正在转换mp-1532.cif
正在转换mp-1533.cif
正在转换mp-1534.cif
正在转换mp-1535.cif
正在转换mp-1539.cif
正在转换mp-1540.cif
正在转换mp-1543.cif
正在转换mp-1545.cif
正在转换mp-1546.cif
正在转换mp-1547.cif
正在转换mp-1549.cif
正在转换mp-1551.cif
正在转换mp-1553.cif
正在转换mp-1555.cif
正在转换mp-1558.cif
正在转换mp-15608.cif
正在转换mp-1560.cif
正在转换mp-1561.cif
正在转换mp-15624.cif
正在转换mp-15637.cif
正在转换mp-15638.cif
正在转换mp-15639.cif
正在转换mp-1564.cif
正在转换mp-15650.cif
正在转换mp-15651.cif
正在转换mp-15652.cif
正在转换mp-15657.cif
正在转换mp-15660.cif
正在转换mp-15669.cif
正在转换mp-15681.cif
正在转换mp-15683.cif
正在转换mp-15686.cif
正在转换mp-15691.cif
正在转换mp-15694.cif
正在转换mp-15697.cif
正在转换mp-15709.cif
正在转换mp-1570.cif
正在转换mp-1571.cif
正在转换mp-15722.cif
正在转换mp-15778.cif
正在转换mp-15779.cif
正在转换mp-15787.cif
正在转换mp-1578.cif
正在转换mp-15799.cif
正在转换mp-1579.cif
正在转换mp-15800.cif
正在转换mp-15801.cif
正在转换mp-15805.cif
正在转换mp-15809.cif
正在转换mp-1580.cif
正在转换mp-15820.cif
正在转换mp-15821.cif
正在转换mp-15822.cif
正在转换mp-15839.cif
正在转换mp-1584.cif
正在转换mp-15856.cif
正在转换mp-1585.cif
正在转换mp-1586.cif
正在转换mp-1594.cif
正在转换mp-15963.cif
正在转换mp-15968.cif
正在转换mp-15985.cif
正在转换mp-15986.cif
正在转换mp-15987.cif
正在转换mp-1601.cif
正在转换mp-1603.cif
正在转换mp-1606.cif
正在转换mp-1607.cif
正在转换mp-1608.cif
正在转换mp-1609.cif
正在转换mp-1610.cif
正在转换mp-1611.cif
正在转换mp-1620.cif
正在转换mp-16228.cif
正在转换mp-1623.cif
正在转换mp-16241.cif
正在转换mp-16245.cif
正在转换mp-16246.cif
正在转换mp-16250.cif
正在转换mp-16251.cif
正在转换mp-16254.cif
正在转换mp-16259.cif
正在转换mp-1625.cif
正在转换mp-16260.cif
正在转换mp-16261.cif
正在转换mp-16263.cif
正在转换mp-16266.cif
正在转换mp-16268.cif
正在转换mp-16271.cif
正在转换mp-16275.cif
正在转换mp-16287.cif
正在转换mp-1628.cif
正在转换mp-16290.cif
正在转换mp-16297.cif
正在转换mp-1629.cif
正在转换mp-16304.cif
正在转换mp-16305.cif
正在转换mp-1630.cif
正在转换mp-16320.cif
正在转换mp-16326.cif
正在转换mp-16328.cif
正在转换mp-16331.cif
正在转换mp-16334.cif
正在转换mp-16341.cif
正在转换mp-16342.cif
正在转换mp-16349.cif
正在转换mp-16358.cif
正在转换mp-16365.cif
正在转换mp-1636.cif
正在转换mp-16370.cif
正在转换mp-16371.cif
正在转换mp-16373.cif
正在转换mp-16378.cif
正在转换mp-1638.cif
正在转换mp-16421.cif
正在转换mp-1646.cif
正在转换mp-16471.cif
正在转换mp-16472.cif
正在转换mp-16479.cif
正在转换mp-16481.cif
正在转换mp-16482.cif
正在转换mp-16493.cif
正在转换mp-16494.cif
正在转换mp-16495.cif
正在转换mp-16497.cif
正在转换mp-1649.cif
正在转换mp-16501.cif
正在转换mp-16503.cif
正在转换mp-16513.cif
正在转换mp-16514.cif
正在转换mp-16516.cif
正在转换mp-16517.cif
正在转换mp-16519.cif
正在转换mp-16521.cif
正在转换mp-16522.cif
正在转换mp-16524.cif
正在转换mp-1652.cif
正在转换mp-16548.cif
正在转换mp-1654.cif
正在转换mp-1655.cif
正在转换mp-16564.cif
正在转换mp-16565.cif
正在转换mp-16566.cif
正在转换mp-1657.cif
正在转换mp-1660.cif
正在转换mp-1662.cif
正在转换mp-16641.cif
正在转换mp-16644.cif
正在转换mp-16645.cif
正在转换mp-1664.cif
正在转换mp-1665.cif
正在转换mp-1668.cif
正在转换mp-1670.cif
正在转换mp-1671.cif
正在转换mp-16726.cif
正在转换mp-16728.cif
正在转换mp-16730.cif
正在转换mp-16731.cif
正在转换mp-16732.cif
正在转换mp-16733.cif
正在转换mp-16734.cif
正在转换mp-16740.cif
正在转换mp-16741.cif
正在转换mp-16747.cif
正在转换mp-1674.cif
正在转换mp-16750.cif
正在转换mp-16751.cif
正在转换mp-16753.cif
正在转换mp-1682.cif
正在转换mp-1684.cif
正在转换mp-1687.cif
正在转换mp-1688.cif
正在转换mp-1692.cif
正在转换mp-1696.cif
正在转换mp-1697.cif
正在转换mp-1698.cif
正在转换mp-1703.cif
正在转换mp-1704.cif
正在转换mp-1708.cif
正在转换mp-1709.cif
正在转换mp-1718.cif
正在转换mp-1719.cif
正在转换mp-1720.cif
正在转换mp-1723.cif
正在转换mp-1725.cif
正在转换mp-1727.cif
正在转换mp-1728.cif
正在转换mp-1729.cif
正在转换mp-1730.cif
正在转换mp-1734.cif
正在转换mp-1738.cif
正在转换mp-1743.cif
正在转换mp-1748.cif
正在转换mp-1749.cif
正在转换mp-1751.cif
正在转换mp-1753.cif
正在转换mp-1756.cif
正在转换mp-1757.cif
正在转换mp-1761.cif
正在转换mp-1762.cif
正在转换mp-1766.cif
正在转换mp-1769.cif
正在转换mp-1774.cif
正在转换mp-1775.cif
正在转换mp-1780.cif
正在转换mp-1781.cif
正在转换mp-1782.cif
正在转换mp-1785.cif
正在转换mp-1786.cif
正在转换mp-1787.cif
正在转换mp-1795.cif
正在转换mp-1798.cif
正在转换mp-1799.cif
正在转换mp-1804.cif
正在转换mp-1805.cif
正在转换mp-1811.cif
正在转换mp-1825.cif
正在转换mp-1830.cif
正在转换mp-1859.cif
正在转换mp-1868.cif
正在转换mp-1871.cif
正在转换mp-18724.cif
正在转换mp-18728.cif
正在转换mp-18755.cif
正在转换mp-1877.cif
正在转换mp-18787.cif
正在转换mp-1879.cif
正在转换mp-18905.cif
正在转换mp-18919.cif
正在转换mp-1891.cif
正在转换mp-1895.cif
正在转换mp-18963.cif
正在转换mp-18972.cif
正在转换mp-1897.cif
正在转换mp-1902.cif
正在转换mp-19060.cif
正在转换mp-19069.cif
正在转换mp-19091.cif
正在转换mp-1909.cif
正在转换mp-19102.cif
正在转换mp-1912.cif
正在转换mp-1916.cif
正在转换mp-19171.cif
正在转换mp-19177.cif
正在转换mp-19210.cif
正在转换mp-19237.cif
正在转换mp-19246.cif
正在转换mp-1925.cif
正在转换mp-19284.cif
正在转换mp-1928.cif
正在转换mp-19322.cif
正在转换mp-19366.cif
正在转换mp-1940.cif
正在转换mp-19415.cif
正在转换mp-1941.cif
正在转换mp-1961.cif
正在转换mp-19712.cif
正在转换mp-19713.cif
正在转换mp-19718.cif
正在转换mp-19722.cif
正在转换mp-19723.cif
正在转换mp-19724.cif
正在转换mp-19733.cif
正在转换mp-19740.cif
正在转换mp-19741.cif
正在转换mp-19746.cif
正在转换mp-19747.cif
正在转换mp-19749.cif
正在转换mp-19754.cif
正在转换mp-19758.cif
正在转换mp-19762.cif
正在转换mp-19764.cif
正在转换mp-19768.cif
正在转换mp-19771.cif
正在转换mp-19777.cif
正在转换mp-19778.cif
正在转换mp-19782.cif
正在转换mp-19786.cif
正在转换mp-19814.cif
正在转换mp-19816.cif
正在转换mp-19817.cif
正在转换mp-19818.cif
正在转换mp-19821.cif
正在转换mp-19824.cif
正在转换mp-19832.cif
正在转换mp-19834.cif
正在转换mp-19835.cif
正在转换mp-19836.cif
正在转换mp-19838.cif
正在转换mp-19848.cif
正在转换mp-19850.cif
正在转换mp-19854.cif
正在转换mp-19856.cif
正在转换mp-19860.cif
正在转换mp-19865.cif
正在转换mp-19867.cif
正在转换mp-19868.cif
正在转换mp-19870.cif
正在转换mp-19871.cif
正在转换mp-19876.cif
正在转换mp-19877.cif
正在转换mp-19881.cif
正在转换mp-19889.cif
正在转换mp-19895.cif
正在转换mp-19899.cif
正在转换mp-19902.cif
正在转换mp-19904.cif
正在转换mp-19907.cif
正在转换mp-19911.cif
正在转换mp-19917.cif
正在转换mp-19920.cif
正在转换mp-19929.cif
正在转换mp-19939.cif
正在转换mp-19940.cif
正在转换mp-19943.cif
正在转换mp-19944.cif
正在转换mp-19946.cif
正在转换mp-19948.cif
正在转换mp-19959.cif
正在转换mp-1995.cif
正在转换mp-19961.cif
正在转换mp-19962.cif
正在转换mp-19968.cif
正在转换mp-1996.cif
正在转换mp-19977.cif
正在转换mp-19983.cif
正在转换mp-19988.cif
正在转换mp-20002.cif
正在转换mp-20010.cif
正在转换mp-20012.cif
正在转换mp-20021.cif
正在转换mp-20023.cif
正在转换mp-2002.cif
正在转换mp-20033.cif
正在转换mp-20034.cif
正在转换mp-20037.cif
正在转换mp-20049.cif
正在转换mp-20050.cif
正在转换mp-20055.cif
正在转换mp-20061.cif
正在转换mp-20074.cif
正在转换mp-20075.cif
正在转换mp-20086.cif
正在转换mp-20097.cif
正在转换mp-20103.cif
正在转换mp-20112.cif
正在转换mp-20119.cif
正在转换mp-20127.cif
正在转换mp-20131.cif
正在转换mp-20136.cif
正在转换mp-20137.cif
正在转换mp-20139.cif
正在转换mp-20145.cif
正在转换mp-20155.cif
正在转换mp-20158.cif
正在转换mp-20159.cif
正在转换mp-20160.cif
正在转换mp-20164.cif
正在转换mp-20166.cif
正在转换mp-20176.cif
正在转换mp-20180.cif
正在转换mp-20189.cif
正在转换mp-20193.cif
正在转换mp-20197.cif
正在转换mp-20206.cif
正在转换mp-20211.cif
正在转换mp-20214.cif
正在转换mp-20225.cif
正在转换mp-20227.cif
正在转换mp-20228.cif
正在转换mp-20229.cif
正在转换mp-20231.cif
正在转换mp-20235.cif
正在转换mp-20236.cif
正在转换mp-20237.cif
正在转换mp-20238.cif
正在转换mp-20240.cif
正在转换mp-20245.cif
正在转换mp-20260.cif
正在转换mp-20262.cif
正在转换mp-20263.cif
正在转换mp-20264.cif
正在转换mp-20265.cif
正在转换mp-20269.cif
正在转换mp-20273.cif
正在转换mp-20275.cif
正在转换mp-20279.cif
正在转换mp-2028.cif
正在转换mp-20290.cif
正在转换mp-20292.cif
正在转换mp-20294.cif
正在转换mp-20298.cif
正在转换mp-20304.cif
正在转换mp-20314.cif
正在转换mp-20318.cif
正在转换mp-20320.cif
正在转换mp-20325.cif
正在转换mp-20336.cif
正在转换mp-20341.cif
正在转换mp-20344.cif
正在转换mp-20346.cif
正在转换mp-20350.cif
正在转换mp-20358.cif
正在转换mp-20362.cif
正在转换mp-20363.cif
正在转换mp-20365.cif
正在转换mp-20366.cif
正在转换mp-20369.cif
正在转换mp-20370.cif
正在转换mp-20379.cif
正在转换mp-20384.cif
正在转换mp-20385.cif
正在转换mp-20388.cif
正在转换mp-20389.cif
正在转换mp-20390.cif
正在转换mp-20401.cif
正在转换mp-20408.cif
正在转换mp-20411.cif
正在转换mp-20423.cif
正在转换mp-20424.cif
正在转换mp-20425.cif
正在转换mp-20426.cif
正在转换mp-20430.cif
正在转换mp-20432.cif
正在转换mp-20438.cif
正在转换mp-20440.cif
正在转换mp-20441.cif
正在转换mp-20446.cif
正在转换mp-20453.cif
正在转换mp-20457.cif
正在转换mp-20469.cif
正在转换mp-20473.cif
正在转换mp-20476.cif
正在转换mp-20478.cif
正在转换mp-20481.cif
正在转换mp-20486.cif
正在转换mp-20491.cif
正在转换mp-20497.cif
正在转换mp-20505.cif
正在转换mp-20512.cif
正在转换mp-20516.cif
正在转换mp-20519.cif
正在转换mp-20521.cif
正在转换mp-20522.cif
正在转换mp-20523.cif
正在转换mp-20531.cif
正在转换mp-20532.cif
正在转换mp-20533.cif
正在转换mp-20536.cif
正在转换mp-20538.cif
正在转换mp-20539.cif
正在转换mp-20542.cif
正在转换mp-20543.cif
正在转换mp-20545.cif
正在转换mp-20549.cif
正在转换mp-20552.cif
正在转换mp-20555.cif
正在转换mp-20563.cif
正在转换mp-20565.cif
正在转换mp-20566.cif
正在转换mp-20567.cif
正在转换mp-20573.cif
正在转换mp-20581.cif
正在转换mp-20582.cif
正在转换mp-20586.cif
正在转换mp-20588.cif
正在转换mp-20590.cif
正在转换mp-20596.cif
正在转换mp-20599.cif
正在转换mp-20601.cif
正在转换mp-20602.cif
正在转换mp-20603.cif
正在转换mp-20608.cif
正在转换mp-20612.cif
正在转换mp-20619.cif
正在转换mp-20621.cif
正在转换mp-20626.cif
正在转换mp-20627.cif
正在转换mp-20628.cif
正在转换mp-20632.cif
正在转换mp-20635.cif
正在转换mp-20637.cif
正在转换mp-20644.cif
正在转换mp-20646.cif
正在转换mp-20649.cif
正在转换mp-20660.cif
正在转换mp-20661.cif
正在转换mp-20663.cif
正在转换mp-20664.cif
正在转换mp-20666.cif
正在转换mp-20670.cif

正在转换mp-20685.cif
正在转换mp-20686.cif
正在转换mp-20690.cif
正在转换mp-20695.cif
正在转换mp-20698.cif
正在转换mp-20708.cif
正在转换mp-20710.cif
正在转换mp-20713.cif
正在转换mp-20714.cif
正在转换mp-20721.cif
正在转换mp-20722.cif
正在转换mp-20724.cif
正在转换mp-20729.cif
正在转换mp-20730.cif
正在转换mp-20735.cif
正在转换mp-20738.cif
正在转换mp-20744.cif
正在转换mp-20746.cif
正在转换mp-20750.cif
正在转换mp-20751.cif
正在转换mp-20753.cif
正在转换mp-20757.cif
正在转换mp-20766.cif
正在转换mp-20768.cif
正在转换mp-20773.cif
正在转换mp-20774.cif
正在转换mp-20776.cif
正在转换mp-20785.cif
正在转换mp-20786.cif
正在转换mp-20787.cif
正在转换mp-20789.cif
正在转换mp-20791.cif
正在转换mp-20796.cif
正在转换mp-20801.cif
正在转换mp-20803.cif
正在转换mp-20812.cif
正在转换mp-20821.cif
正在转换mp-20822.cif
正在转换mp-20828.cif
正在转换mp-20839.cif
正在转换mp-20840.cif
正在转换mp-20842.cif
正在转换mp-20848.cif
正在转换mp-20849.cif
正在转换mp-20857.cif
正在转换mp-2085.cif
正在转换mp-20860.cif
正在转换mp-20861.cif
正在转换mp-20862.cif
正在转换mp-20864.cif
正在转换mp-20865.cif
正在转换mp-20872.cif
正在转换mp-20875.cif
正在转换mp-20880.cif
正在转换mp-20883.cif
正在转换mp-20885.cif
正在转换mp-20889.cif
正在转换mp-20895.cif
正在转换mp-20896.cif
正在转换mp-20898.cif
正在转换mp-20903.cif
正在转换mp-20906.cif
正在转换mp-20909.cif
正在转换mp-20913.cif
正在转换mp-20918.cif
正在转换mp-20920.cif
正在转换mp-20922.cif
正在转换mp-20924.cif
正在转换mp-20935.cif
正在转换mp-20939.cif
正在转换mp-2093.cif
正在转换mp-20941.cif
正在转换mp-20942.cif
正在转换mp-20943.cif
正在转换mp-20950.cif
正在转换mp-20952.cif
正在转换mp-20954.cif
正在转换mp-20963.cif
正在转换mp-20969.cif
正在转换mp-20970.cif
正在转换mp-20971.cif
正在转换mp-20972.cif
正在转换mp-20975.cif
正在转换mp-20978.cif
正在转换mp-20979.cif
正在转换mp-20983.cif
正在转换mp-20985.cif
正在转换mp-20992.cif
正在转换mp-20996.cif
正在转换mp-20998.cif
正在转换mp-20999.cif
正在转换mp-2099.cif
正在转换mp-21000.cif
正在转换mp-21001.cif
正在转换mp-21006.cif
正在转换mp-21007.cif
正在转换mp-21008.cif
正在转换mp-21014.cif
正在转换mp-21015.cif
正在转换mp-21017.cif
正在转换mp-21026.cif
正在转换mp-21028.cif
正在转换mp-21029.cif
正在转换mp-2102.cif
正在转换mp-21030.cif
正在转换mp-21031.cif
正在转换mp-21032.cif
正在转换mp-21035.cif
正在转换mp-21039.cif
正在转换mp-2103.cif
正在转换mp-21045.cif
正在转换mp-21046.cif
正在转换mp-21048.cif
正在转换mp-21054.cif
正在转换mp-21058.cif
正在转换mp-21063.cif
正在转换mp-21067.cif
正在转换mp-21068.cif
正在转换mp-21070.cif
正在转换mp-21075.cif
正在转换mp-21078.cif
正在转换mp-21082.cif
正在转换mp-21087.cif
正在转换mp-21090.cif
正在转换mp-21092.cif
正在转换mp-21093.cif
正在转换mp-21098.cif
正在转换mp-2109.cif
正在转换mp-21105.cif
正在转换mp-21111.cif
正在转换mp-21113.cif
正在转换mp-21117.cif
正在转换mp-21118.cif
正在转换mp-21130.cif
正在转换mp-21135.cif
正在转换mp-21140.cif
正在转换mp-21148.cif
正在转换mp-21156.cif
正在转换mp-21162.cif
正在转换mp-21167.cif
正在转换mp-21171.cif
正在转换mp-21175.cif
正在转换mp-21177.cif
正在转换mp-21186.cif
正在转换mp-21187.cif
正在转换mp-21194.cif
正在转换mp-21197.cif
正在转换mp-21198.cif
正在转换mp-2119.cif
正在转换mp-21202.cif
正在转换mp-21203.cif
正在转换mp-21206.cif
正在转换mp-21211.cif
正在转换mp-21214.cif
正在转换mp-21215.cif
正在转换mp-21221.cif
正在转换mp-21223.cif
正在转换mp-21224.cif
正在转换mp-21225.cif
正在转换mp-21232.cif
正在转换mp-21233.cif
正在转换mp-21235.cif
正在转换mp-21238.cif
正在转换mp-21242.cif
正在转换mp-21244.cif
正在转换mp-21245.cif
正在转换mp-21249.cif
正在转换mp-21251.cif
正在转换mp-21263.cif
正在转换mp-21271.cif
正在转换mp-21278.cif
正在转换mp-21280.cif
正在转换mp-21281.cif
正在转换mp-21284.cif
正在转换mp-21289.cif
正在转换mp-21290.cif
正在转换mp-21292.cif
正在转换mp-21294.cif
正在转换mp-21295.cif
正在转换mp-21298.cif
正在转换mp-21301.cif
正在转换mp-21308.cif
正在转换mp-21313.cif
正在转换mp-21318.cif
正在转换mp-21320.cif
正在转换mp-21328.cif
正在转换mp-21342.cif
正在转换mp-21343.cif
正在转换mp-21349.cif
正在转换mp-2134.cif
正在转换mp-21351.cif
正在转换mp-21352.cif
正在转换mp-21360.cif
正在转换mp-21364.cif
正在转换mp-21366.cif
正在转换mp-21372.cif
正在转换mp-21376.cif
正在转换mp-21379.cif
正在转换mp-21381.cif
正在转换mp-21385.cif
正在转换mp-21387.cif
正在转换mp-21388.cif
正在转换mp-21391.cif
正在转换mp-21392.cif
正在转换mp-21398.cif
正在转换mp-21399.cif
正在转换mp-21400.cif
正在转换mp-21402.cif
正在转换mp-21412.cif
正在转换mp-21415.cif
正在转换mp-21416.cif
正在转换mp-21418.cif
正在转换mp-21419.cif
正在转换mp-21420.cif
正在转换mp-21421.cif
正在转换mp-21422.cif
正在转换mp-21423.cif
正在转换mp-21426.cif
正在转换mp-21428.cif
正在转换mp-21429.cif
正在转换mp-21430.cif
正在转换mp-21431.cif
正在转换mp-21432.cif
正在转换mp-21433.cif
正在转换mp-21440.cif
正在转换mp-21456.cif
正在转换mp-21463.cif
正在转换mp-21467.cif
正在转换mp-21469.cif
正在转换mp-21471.cif
正在转换mp-21475.cif
正在转换mp-21477.cif
正在转换mp-21481.cif
正在转换mp-21482.cif
正在转换mp-21483.cif
正在转换mp-21484.cif
正在转换mp-21486.cif
正在转换mp-21494.cif
正在转换mp-21499.cif
正在转换mp-21503.cif
正在转换mp-21505.cif
正在转换mp-2179.cif
正在转换mp-2182.cif
正在转换mp-21844.cif
正在转换mp-21845.cif
正在转换mp-21847.cif
正在转换mp-21850.cif
正在转换mp-21853.cif
正在转换mp-21854.cif
正在转换mp-21859.cif
正在转换mp-21865.cif
正在转换mp-21883.cif
正在转换mp-21887.cif
正在转换mp-21890.cif
正在转换mp-21891.cif
正在转换mp-21907.cif
正在转换mp-21910.cif
正在转换mp-2192.cif
正在转换mp-22004.cif
正在转换mp-22029.cif
正在转换mp-22032.cif
正在转换mp-2203.cif
正在转换mp-22053.cif
正在转换mp-22056.cif
正在转换mp-22060.cif
正在转换mp-22065.cif
正在转换mp-22066.cif
正在转换mp-22068.cif
正在转换mp-22079.cif
正在转换mp-22085.cif
正在转换mp-22095.cif
正在转换mp-22108.cif
正在转换mp-2210.cif
正在转换mp-22120.cif
正在转换mp-22140.cif
正在转换mp-22149.cif
正在转换mp-22152.cif
正在转换mp-22154.cif
正在转换mp-22156.cif
正在转换mp-22158.cif
正在转换mp-22159.cif
正在转换mp-22177.cif
正在转换mp-22179.cif
正在转换mp-22180.cif
正在转换mp-22188.cif
正在转换mp-22191.cif
正在转换mp-22197.cif
正在转换mp-22211.cif
正在转换mp-22214.cif
正在转换mp-22221.cif
正在转换mp-22229.cif
正在转换mp-2222.cif
正在转换mp-22240.cif
正在转换mp-22270.cif
正在转换mp-22274.cif
正在转换mp-22276.cif
正在转换mp-22289.cif
正在转换mp-22297.cif
正在转换mp-22300.cif
正在转换mp-22320.cif
正在转换mp-22331.cif
正在转换mp-22332.cif
正在转换mp-22339.cif
正在转换mp-22345.cif
正在转换mp-22350.cif
正在转换mp-22367.cif
正在转换mp-22376.cif
正在转换mp-22377.cif
正在转换mp-22382.cif
正在转换mp-22389.cif
正在转换mp-22394.cif
正在转换mp-22397.cif
正在转换mp-22400.cif
正在转换mp-22419.cif
正在转换mp-22435.cif
正在转换mp-2243.cif
正在转换mp-22460.cif
正在转换mp-22461.cif
正在转换mp-22463.cif
正在转换mp-22465.cif
正在转换mp-22466.cif
正在转换mp-22469.cif
正在转换mp-22478.cif
正在转换mp-22485.cif
正在转换mp-22486.cif
正在转换mp-22488.cif
正在转换mp-22493.cif
正在转换mp-22496.cif
正在转换mp-22498.cif
正在转换mp-22502.cif
正在转换mp-22503.cif
正在转换mp-2250.cif
正在转换mp-22510.cif
正在转换mp-22513.cif
正在转换mp-22514.cif
正在转换mp-22519.cif
正在转换mp-22532.cif
正在转换mp-22537.cif
正在转换mp-22540.cif
正在转换mp-22541.cif
正在转换mp-22542.cif
正在转换mp-22556.cif
正在转换mp-22568.cif
正在转换mp-22580.cif
正在转换mp-22589.cif
正在转换mp-22595.cif
正在转换mp-22596.cif
正在转换mp-22602.cif
正在转换mp-22610.cif
正在转换mp-22611.cif
正在转换mp-22612.cif
正在转换mp-22620.cif
正在转换mp-22631.cif
正在转换mp-22639.cif
正在转换mp-2263.cif
正在转换mp-22643.cif
正在转换mp-22648.cif
正在转换mp-2265.cif
正在转换mp-22662.cif
正在转换mp-22664.cif
正在转换mp-2266.cif
正在转换mp-22672.cif
正在转换mp-22673.cif
正在转换mp-22679.cif
正在转换mp-22680.cif
正在转换mp-22682.cif
正在转换mp-22683.cif
正在转换mp-22685.cif
正在转换mp-22698.cif
正在转换mp-2269.cif
正在转换mp-22700.cif
正在转换mp-22704.cif
正在转换mp-22712.cif
正在转换mp-22713.cif
正在转换mp-22714.cif
正在转换mp-2271.cif
正在转换mp-22725.cif
正在转换mp-22731.cif
正在转换mp-2273.cif
正在转换mp-22746.cif
正在转换mp-22780.cif
正在转换mp-22782.cif
正在转换mp-22787.cif
正在转换mp-22790.cif
正在转换mp-22792.cif
正在转换mp-22793.cif
正在转换mp-22795.cif
正在转换mp-2279.cif
正在转换mp-22866.cif
正在转换mp-22873.cif
正在转换mp-2287.cif
正在转换mp-22886.cif
正在转换mp-2289.cif
正在转换mp-22902.cif
正在转换mp-22907.cif
正在转换mp-22912.cif
正在转换mp-22915.cif
正在转换mp-22921.cif
正在转换mp-22924.cif
正在转换mp-22926.cif
正在转换mp-22953.cif
正在转换mp-22960.cif
正在转换mp-22973.cif
正在转换mp-2297.cif
正在转换mp-23019.cif
正在转换mp-2302.cif
正在转换mp-23039.cif
正在转换mp-2303.cif
正在转换mp-23047.cif
正在转换mp-2305.cif
正在转换mp-2306.cif
正在转换mp-2311.cif
正在转换mp-2313.cif
正在转换mp-23159.cif
正在转换mp-2316.cif
正在转换mp-23171.cif
正在转换mp-2317.cif
正在转换mp-2318.cif
正在转换mp-23201.cif
正在转换mp-23208.cif
正在转换mp-2322.cif
正在转换mp-23234.cif
正在转换mp-2323.cif
正在转换mp-23241.cif
正在转换mp-23245.cif
正在转换mp-2324.cif
正在转换mp-23255.cif
正在转换mp-23275.cif
正在转换mp-23285.cif
正在转换mp-23300.cif
正在转换mp-23304.cif
正在转换mp-23306.cif
正在转换mp-2331.cif
正在转换mp-2333.cif
正在转换mp-2334.cif
正在转换mp-2337.cif
正在转换mp-2338.cif
正在转换mp-2339.cif
正在转换mp-2343.cif
正在转换mp-2346.cif
正在转换mp-23471.cif
正在转换mp-2347.cif
正在转换mp-2349.cif
正在转换mp-2350.cif
正在转换mp-2351.cif
正在转换mp-23533.cif
正在转换mp-2354.cif
正在转换mp-2358.cif
正在转换mp-2359.cif
正在转换mp-2360.cif
正在转换mp-2363.cif
正在转换mp-2364.cif
正在转换mp-23679.cif
正在转换mp-2367.cif
正在转换mp-2369.cif
正在转换mp-2370.cif
正在转换mp-23722.cif
正在转换mp-2373.cif
正在转换mp-2375.cif
正在转换mp-2377.cif
正在转换mp-2379.cif
正在转换mp-2381.cif
正在转换mp-2384.cif
正在转换mp-2385.cif
正在转换mp-2387.cif
正在转换mp-2388.cif
正在转换mp-2389.cif
正在转换mp-23903.cif
正在转换mp-2390.cif
正在转换mp-2391.cif
正在转换mp-2393.cif
正在转换mp-2396.cif
正在转换mp-2399.cif
正在转换mp-24011.cif
正在转换mp-2403.cif
正在转换mp-2404.cif
正在转换mp-24082.cif
正在转换mp-24095.cif
正在转换mp-24096.cif
正在转换mp-2410.cif
正在转换mp-2413.cif
正在转换mp-24147.cif
正在转换mp-24149.cif
正在转换mp-24151.cif
正在转换mp-24152.cif
正在转换mp-24153.cif
正在转换mp-24154.cif
正在转换mp-24155.cif
正在转换mp-2415.cif
正在转换mp-24161.cif
正在转换mp-2417.cif
正在转换mp-24192.cif
正在转换mp-24201.cif
正在转换mp-24208.cif
正在转换mp-2420.cif
正在转换mp-2422.cif
正在转换mp-24237.cif
正在转换mp-2423.cif
正在转换mp-2426.cif
正在转换mp-24285.cif
正在转换mp-24286.cif
正在转换mp-24287.cif
正在转换mp-24288.cif
正在转换mp-24289.cif
正在转换mp-24291.cif
正在转换mp-2430.cif
正在转换mp-2431.cif
正在转换mp-2434.cif
正在转换mp-2435.cif
正在转换mp-2439.cif
正在转换mp-24417.cif
正在转换mp-24420.cif
正在转换mp-2442.cif
正在转换mp-2443.cif
正在转换mp-2444.cif
正在转换mp-2449.cif
正在转换mp-24513.cif
正在转换mp-2458.cif
正在转换mp-2459.cif
正在转换mp-2461.cif
正在转换mp-2463.cif
正在转换mp-24650.cif
正在转换mp-24658.cif
正在转换mp-24659.cif
正在转换mp-2465.cif
正在转换mp-24669.cif
正在转换mp-2466.cif
正在转换mp-2468.cif
正在转换mp-2470.cif
正在转换mp-24719.cif
正在转换mp-24720.cif
正在转换mp-24722.cif
正在转换mp-24723.cif
正在转换mp-24724.cif
正在转换mp-24726.cif
正在转换mp-24727.cif
正在转换mp-24728.cif
正在转换mp-2474.cif
正在转换mp-2475.cif
正在转换mp-2478.cif
正在转换mp-2483.cif
正在转换mp-2484.cif
正在转换mp-2486.cif
正在转换mp-24897.cif
正在转换mp-2489.cif
正在转换mp-2491.cif
正在转换mp-2493.cif
正在转换mp-2495.cif
正在转换mp-2498.cif
正在转换mp-2499.cif
正在转换mp-2501.cif
正在转换mp-2502.cif
正在转换mp-2509.cif
正在转换mp-2510.cif

正在转换mp-2515.cif
正在转换mp-25174.cif
正在转换mp-2520.cif
正在转换mp-25229.cif
正在转换mp-2524.cif
正在转换mp-2525.cif
正在转换mp-2529.cif
正在转换mp-25317.cif
正在转换mp-2532.cif
正在转换mp-2533.cif
正在转换mp-25372.cif
正在转换mp-25378.cif
正在转换mp-2537.cif
正在转换mp-2540.cif
正在转换mp-25417.cif
正在转换mp-2541.cif
正在转换mp-2545.cif
正在转换mp-2546.cif
正在转换mp-2547.cif
正在转换mp-25489.cif
正在转换mp-2548.cif
正在转换mp-25499.cif
正在转换mp-2550.cif
正在转换mp-25517.cif
正在转换mp-25519.cif
正在转换mp-2551.cif
正在转换mp-2553.cif
正在转换mp-2554.cif
正在转换mp-2557.cif
正在转换mp-25592.cif
正在转换mp-2559.cif
正在转换mp-2560.cif
正在转换mp-2562.cif
正在转换mp-2563.cif
正在转换mp-2567.cif
正在转换mp-2568.cif
正在转换mp-2570.cif
正在转换mp-2573.cif
正在转换mp-2577.cif
正在转换mp-2579.cif
正在转换mp-2580.cif
正在转换mp-2582.cif
正在转换mp-2583.cif
正在转换mp-2592.cif
正在转换mp-2596.cif
正在转换mp-2597.cif
正在转换mp-2598.cif
正在转换mp-2599.cif
正在转换mp-2602.cif
正在转换mp-2606.cif
正在转换mp-2607.cif
正在转换mp-2611.cif
正在转换mp-2614.cif
正在转换mp-2616.cif
正在转换mp-2618.cif
正在转换mp-2619.cif
正在转换mp-2620.cif
正在转换mp-2621.cif
正在转换mp-2627.cif
正在转换mp-2628.cif
正在转换mp-2634.cif
正在转换mp-2637.cif
正在转换mp-2639.cif
正在转换mp-2640.cif
正在转换mp-2642.cif
正在转换mp-2643.cif
正在转换mp-2644.cif
正在转换mp-2645.cif
正在转换mp-2647.cif
正在转换mp-2648.cif
正在转换mp-2658.cif
正在转换mp-2661.cif
正在转换mp-2662.cif
正在转换mp-2663.cif
正在转换mp-2664.cif
正在转换mp-2665.cif
正在转换mp-2666.cif
正在转换mp-2668.cif
正在转换mp-2670.cif
正在转换mp-2673.cif
正在转换mp-2674.cif
正在转换mp-2676.cif
正在转换mp-2677.cif
正在转换mp-2678.cif
正在转换mp-2680.cif
正在转换mp-2684.cif
正在转换mp-2685.cif
正在转换mp-2688.cif
正在转换mp-2689.cif
正在转换mp-2692.cif
正在转换mp-2696.cif
正在转换mp-2700.cif
正在转换mp-2701.cif
正在转换mp-2707.cif
正在转换mp-2713.cif
正在转换mp-2720.cif
正在转换mp-2721.cif
正在转换mp-2723.cif
正在转换mp-2724.cif
正在转换mp-2725.cif
正在转换mp-2730.cif
正在转换mp-2731.cif
正在转换mp-2732.cif
正在转换mp-27335.cif
正在转换mp-2735.cif
正在转换mp-2738.cif
正在转换mp-2740.cif
正在转换mp-2743.cif
正在转换mp-2744.cif
正在转换mp-27454.cif
正在转换mp-27468.cif
正在转换mp-2746.cif
正在转换mp-27471.cif
正在转换mp-2747.cif
正在转换mp-2748.cif
正在转换mp-27490.cif
正在转换mp-2749.cif
正在转换mp-27512.cif
正在转换mp-2751.cif
正在转换mp-27527.cif
正在转换mp-2752.cif
正在转换mp-2757.cif
正在转换mp-27617.cif
正在转换mp-2762.cif
正在转换mp-2765.cif
正在转换mp-27660.cif
正在转换mp-27661.cif
正在转换mp-2767.cif
正在转换mp-2768.cif
正在转换mp-2769.cif
正在转换mp-27710.cif
正在转换mp-27731.cif
正在转换mp-2773.cif
正在转换mp-2775.cif
正在转换mp-27760.cif
正在转换mp-27762.cif
正在转换mp-27763.cif
正在转换mp-2776.cif
正在转换mp-2778.cif
正在转换mp-27797.cif
正在转换mp-2780.cif
正在转换mp-27816.cif
正在转换mp-27819.cif
正在转换mp-2781.cif
正在转换mp-27826.cif
正在转换mp-27835.cif
正在转换mp-27838.cif
正在转换mp-2783.cif
正在转换mp-27840.cif
正在转换mp-27861.cif
正在转换mp-27942.cif
正在转换mp-27945.cif
正在转换mp-27953.cif
正在转换mp-2795.cif
正在转换mp-2796.cif
正在转换mp-2797.cif
正在转换mp-27981.cif
正在转换mp-27982.cif
正在转换mp-28006.cif
正在转换mp-2800.cif
正在转换mp-2802.cif
正在转换mp-28056.cif
正在转换mp-2806.cif
正在转换mp-2807.cif
正在转换mp-2812.cif
正在转换mp-2816.cif
正在转换mp-2818.cif
正在转换mp-2819.cif
正在转换mp-28229.cif
正在转换mp-2822.cif
正在转换mp-2823.cif
正在转换mp-28246.cif
正在转换mp-28254.cif
正在转换mp-2825.cif
正在转换mp-2827.cif
正在转换mp-2828.cif
正在转换mp-2831.cif
正在转换mp-28376.cif
正在转换mp-2837.cif
正在转换mp-2839.cif
正在转换mp-2840.cif
正在转换mp-2844.cif
正在转换mp-2845.cif
正在转换mp-2849.cif
正在转换mp-2850.cif
正在转换mp-2851.cif
正在转换mp-2857.cif
正在转换mp-2861.cif
正在转换mp-28637.cif
正在转换mp-2863.cif
正在转换mp-28645.cif
正在转换mp-28665.cif
正在转换mp-2866.cif
正在转换mp-28705.cif
正在转换mp-2873.cif
正在转换mp-2877.cif
正在转换mp-2880.cif
正在转换mp-2881.cif
正在转换mp-28927.cif
正在转换mp-2893.cif
正在转换mp-28945.cif
正在转换mp-2896.cif
正在转换mp-2903.cif
正在转换mp-29056.cif
正在转换mp-29069.cif
正在转换mp-2906.cif
正在转换mp-2909.cif
正在转换mp-29131.cif
正在转换mp-29135.cif
正在转换mp-29152.cif
正在转换mp-29175.cif
正在转换mp-2917.cif
正在转换mp-29207.cif
正在转换mp-29210.cif
正在转换mp-29241.cif
正在转换mp-29242.cif
正在转换mp-29243.cif
正在转换mp-2924.cif
正在转换mp-2927.cif
正在转换mp-2929.cif
正在转换mp-2930.cif
正在转换mp-2935.cif
正在转换mp-2938.cif
正在转换mp-2947.cif
正在转换mp-29481.cif
正在转换mp-2949.cif
正在转换mp-2954.cif
正在转换mp-29551.cif
正在转换mp-29556.cif
正在转换mp-29562.cif
正在转换mp-29587.cif
正在转换mp-29588.cif
正在转换mp-29615.cif
正在转换mp-29619.cif
正在转换mp-29633.cif
正在转换mp-29635.cif
正在转换mp-29656.cif
正在转换mp-2965.cif
正在转换mp-29665.cif
正在转换mp-29674.cif
正在转换mp-29676.cif
正在转换mp-29677.cif
正在转换mp-2968.cif
正在转换mp-29719.cif
正在转换mp-2971.cif
正在转换mp-29723.cif
正在转换mp-29725.cif
正在转换mp-29727.cif
正在转换mp-29736.cif
正在转换mp-29742.cif
正在转换mp-29752.cif
正在转换mp-2976.cif
正在转换mp-2985.cif
正在转换mp-2987.cif
正在转换mp-2988.cif
正在转换mp-29896.cif
正在转换mp-2990.cif
正在转换mp-3000.cif
正在转换mp-30021.cif
正在转换mp-30028.cif
正在转换mp-30043.cif
正在转换mp-30044.cif
正在转换mp-30069.cif
正在转换mp-30079.cif
正在转换mp-30083.cif
正在转换mp-3011.cif
正在转换mp-30147.cif
正在转换mp-30175.cif
正在转换mp-30181.cif
正在转换mp-30182.cif
正在转换mp-30183.cif
正在转换mp-3018.cif
正在转换mp-30195.cif
正在转换mp-30208.cif
正在转换mp-3020.cif
正在转换mp-3021.cif
正在转换mp-30227.cif
正在转换mp-3022.cif
正在转换mp-30307.cif
正在转换mp-30317.cif
正在转换mp-30328.cif
正在转换mp-30338.cif
正在转换mp-30339.cif
正在转换mp-30340.cif
正在转换mp-30342.cif
正在转换mp-30343.cif
正在转换mp-30344.cif
正在转换mp-30347.cif
正在转换mp-30349.cif
正在转换mp-3034.cif
正在转换mp-30350.cif
正在转换mp-30351.cif
正在转换mp-30352.cif
正在转换mp-30353.cif
正在转换mp-30354.cif
正在转换mp-30358.cif
正在转换mp-30359.cif
正在转换mp-3035.cif
正在转换mp-30360.cif
正在转换mp-30363.cif
正在转换mp-30364.cif
正在转换mp-30365.cif
正在转换mp-30374.cif
正在转换mp-30375.cif
正在转换mp-30376.cif
正在转换mp-30377.cif
正在转换mp-30379.cif
正在转换mp-3037.cif
正在转换mp-30381.cif
正在转换mp-30383.cif
正在转换mp-30386.cif
正在转换mp-30387.cif
正在转换mp-30388.cif
正在转换mp-30389.cif
正在转换mp-3040.cif
正在转换mp-30392.cif
正在转换mp-30393.cif
正在转换mp-30395.cif
正在转换mp-30403.cif
正在转换mp-30404.cif
正在转换mp-30405.cif
正在转换mp-30406.cif
正在转换mp-30410.cif
正在转换mp-30413.cif
正在转换mp-30415.cif
正在转换mp-30417.cif
正在转换mp-30419.cif
正在转换mp-30423.cif
正在转换mp-30433.cif
正在转换mp-30434.cif
正在转换mp-30435.cif
正在转换mp-30449.cif
正在转换mp-30451.cif
正在转换mp-30453.cif
正在转换mp-30454.cif
正在转换mp-30455.cif
正在转换mp-30465.cif
正在转换mp-30466.cif
正在转换mp-30468.cif
正在转换mp-30469.cif
正在转换mp-30477.cif
正在转换mp-30479.cif
正在转换mp-30481.cif
正在转换mp-30482.cif
正在转换mp-30483.cif
正在转换mp-30488.cif
正在转换mp-3048.cif
正在转换mp-30490.cif
正在转换mp-30491.cif
正在转换mp-30492.cif
正在转换mp-30493.cif
正在转换mp-30495.cif
正在转换mp-30496.cif
正在转换mp-30497.cif
正在转换mp-30498.cif
正在转换mp-30500.cif
正在转换mp-30501.cif
正在转换mp-30502.cif
正在转换mp-30504.cif
正在转换mp-30506.cif
正在转换mp-30507.cif
正在转换mp-30512.cif
正在转换mp-30534.cif
正在转换mp-30536.cif
正在转换mp-3053.cif
正在转换mp-30551.cif
正在转换mp-30554.cif
正在转换mp-30555.cif
正在转换mp-3055.cif
正在转换mp-30560.cif
正在转换mp-30562.cif
正在转换mp-30563.cif
正在转换mp-30564.cif
正在转换mp-30566.cif
正在转换mp-30570.cif
正在转换mp-30571.cif
正在转换mp-30572.cif
正在转换mp-30578.cif
正在转换mp-30579.cif
正在转换mp-30581.cif
正在转换mp-30582.cif
正在转换mp-30583.cif
正在转换mp-30585.cif
正在转换mp-30586.cif
正在转换mp-30587.cif
正在转换mp-30591.cif
正在转换mp-30592.cif
正在转换mp-30593.cif
正在转换mp-30595.cif
正在转换mp-30599.cif
正在转换mp-30603.cif
正在转换mp-30604.cif
正在转换mp-30606.cif
正在转换mp-30609.cif
正在转换mp-30611.cif
正在转换mp-30613.cif
正在转换mp-3061.cif
正在转换mp-30620.cif
正在转换mp-30621.cif
正在转换mp-30625.cif
正在转换mp-30627.cif
正在转换mp-30635.cif
正在转换mp-30648.cif
正在转换mp-30651.cif
正在转换mp-30656.cif
正在转换mp-30657.cif
正在转换mp-30658.cif
正在转换mp-3065.cif
正在转换mp-30661.cif
正在转换mp-30671.cif
正在转换mp-30672.cif
正在转换mp-30682.cif
正在转换mp-30683.cif
正在转换mp-30685.cif
正在转换mp-30708.cif
正在转换mp-30717.cif
正在转换mp-30722.cif
正在转换mp-30723.cif
正在转换mp-30724.cif
正在转换mp-30726.cif
正在转换mp-30727.cif
正在转换mp-30728.cif
正在转换mp-30731.cif
正在转换mp-30732.cif
正在转换mp-30733.cif
正在转换mp-30737.cif
正在转换mp-30741.cif
正在转换mp-30743.cif
正在转换mp-30744.cif
正在转换mp-30745.cif
正在转换mp-30746.cif
正在转换mp-3077.cif
正在转换mp-30758.cif
正在转换mp-30759.cif
正在转换mp-30760.cif
正在转换mp-30761.cif
正在转换mp-30763.cif
正在转换mp-30764.cif
正在转换mp-30773.cif
正在转换mp-30774.cif
正在转换mp-30775.cif
正在转换mp-30779.cif
正在转换mp-30787.cif
正在转换mp-30788.cif
正在转换mp-30789.cif
正在转换mp-30790.cif
正在转换mp-30796.cif
正在转换mp-30797.cif
正在转换mp-30799.cif
正在转换mp-30801.cif
正在转换mp-30803.cif
正在转换mp-30805.cif
正在转换mp-30806.cif
正在转换mp-30807.cif
正在转换mp-30808.cif
正在转换mp-30811.cif
正在转换mp-30816.cif
正在转换mp-30817.cif
正在转换mp-30818.cif
正在转换mp-30819.cif
正在转换mp-30820.cif
正在转换mp-30821.cif
正在转换mp-30822.cif
正在转换mp-30825.cif
正在转换mp-30830.cif
正在转换mp-30834.cif
正在转换mp-30835.cif
正在转换mp-30837.cif
正在转换mp-30838.cif
正在转换mp-30844.cif
正在转换mp-30845.cif
正在转换mp-30848.cif
正在转换mp-30849.cif
正在转换mp-30850.cif
正在转换mp-30852.cif
正在转换mp-30854.cif
正在转换mp-30855.cif
正在转换mp-30856.cif
正在转换mp-30858.cif
正在转换mp-30861.cif
正在转换mp-30865.cif
正在转换mp-30866.cif
正在转换mp-30871.cif
正在转换mp-30872.cif
正在转换mp-30875.cif
正在转换mp-30876.cif
正在转换mp-30877.cif
正在转换mp-30878.cif
正在转换mp-30883.cif
正在转换mp-30885.cif
正在转换mp-30909.cif
正在转换mp-3092.cif
正在转换mp-3093.cif
正在转换mp-3097.cif
正在转换mp-31018.cif
正在转换mp-31055.cif
正在转换mp-31059.cif
正在转换mp-3105.cif
正在转换mp-31066.cif
正在转换mp-31072.cif
正在转换mp-31078.cif
正在转换mp-31080.cif

正在转换mp-31082.cif
正在转换mp-31083.cif
正在转换mp-31136.cif
正在转换mp-31140.cif
正在转换mp-31141.cif
正在转换mp-31142.cif
正在转换mp-31147.cif
正在转换mp-31157.cif
正在转换mp-31160.cif
正在转换mp-31168.cif
正在转换mp-31169.cif
正在转换mp-31170.cif
正在转换mp-31171.cif
正在转换mp-31178.cif
正在转换mp-31184.cif
正在转换mp-31185.cif
正在转换mp-31203.cif
正在转换mp-31204.cif
正在转换mp-31208.cif
正在转换mp-31328.cif
正在转换mp-31337.cif
正在转换mp-31339.cif
正在转换mp-31348.cif
正在转换mp-31349.cif
正在转换mp-31363.cif
正在转换mp-31379.cif
正在转换mp-31380.cif
正在转换mp-31383.cif
正在转换mp-31412.cif
正在转换mp-31413.cif
正在转换mp-31414.cif
正在转换mp-31420.cif
正在转换mp-31421.cif
正在转换mp-31422.cif
正在转换mp-31426.cif
正在转换mp-31427.cif
正在转换mp-31428.cif
正在转换mp-31434.cif
正在转换mp-31438.cif
正在转换mp-31440.cif
正在转换mp-31441.cif
正在转换mp-31442.cif
正在转换mp-31443.cif
正在转换mp-31447.cif
正在转换mp-31449.cif
正在转换mp-31452.cif
正在转换mp-31453.cif
正在转换mp-31456.cif
正在转换mp-31457.cif
正在转换mp-31458.cif
正在转换mp-31459.cif
正在转换mp-31460.cif
正在转换mp-31473.cif
正在转换mp-3148.cif
正在转换mp-31491.cif
正在转换mp-31498.cif
正在转换mp-31509.cif
正在转换mp-31510.cif
正在转换mp-31526.cif
正在转换mp-3158.cif
正在转换mp-31596.cif
正在转换mp-3173.cif
正在转换mp-3183.cif
正在转换mp-3186.cif
正在转换mp-3190.cif
正在转换mp-3191.cif
正在转换mp-3197.cif
正在转换mp-3201.cif
正在转换mp-3207.cif
正在转换mp-3210.cif
正在转换mp-3217.cif
正在转换mp-3218.cif
正在转换mp-3223.cif
正在转换mp-3239.cif
正在转换mp-3241.cif
正在转换mp-32548.cif
正在转换mp-3262.cif
正在转换mp-3263.cif
正在转换mp-3264.cif
正在转换mp-32686.cif
正在转换mp-3268.cif
正在转换mp-3271.cif
正在转换mp-3274.cif
正在转换mp-32758.cif
正在转换mp-3275.cif
正在转换mp-3278.cif
正在转换mp-32791.cif
正在转换mp-32811.cif
正在转换mp-3286.cif
正在转换mp-3292.cif
正在转换mp-3296.cif
正在转换mp-3299.cif
正在转换mp-33009.cif
正在转换mp-3301.cif
正在转换mp-3303.cif
正在转换mp-33088.cif
正在转换mp-3325.cif
正在转换mp-3328.cif
正在转换mp-3329.cif
正在转换mp-3340.cif
正在转换mp-3346.cif
正在转换mp-33500.cif
正在转换mp-33738.cif
正在转换mp-3385.cif
正在转换mp-3388.cif
正在转换mp-3390.cif
正在转换mp-3402.cif
正在转换mp-3406.cif
正在转换mp-3415.cif
正在转换mp-34240.cif
正在转换mp-3428.cif
正在转换mp-3433.cif
正在转换mp-3437.cif
正在转换mp-3441.cif
正在转换mp-3447.cif
正在转换mp-3455.cif
正在转换mp-3456.cif
正在转换mp-34611.cif
正在转换mp-3462.cif
正在转换mp-3464.cif
正在转换mp-3467.cif
正在转换mp-3469.cif
正在转换mp-3477.cif
正在转换mp-3489.cif
正在转换mp-3494.cif
正在转换mp-3497.cif
正在转换mp-3498.cif
正在转换mp-3499.cif
正在转换mp-3504.cif
正在转换mp-3507.cif
正在转换mp-3513.cif
正在转换mp-3515.cif
正在转换mp-35200.cif
正在转换mp-3522.cif
正在转换mp-3526.cif
正在转换mp-3534.cif
正在转换mp-3539.cif
正在转换mp-3553.cif
正在转换mp-3566.cif
正在转换mp-3567.cif
正在转换mp-3570.cif
正在转换mp-3574.cif
正在转换mp-3576.cif
正在转换mp-3579.cif
正在转换mp-3583.cif
正在转换mp-3585.cif
正在转换mp-3587.cif
正在转换mp-35915.cif
正在转换mp-3591.cif
正在转换mp-3603.cif
正在转换mp-3605.cif
正在转换mp-3608.cif
正在转换mp-3623.cif
正在转换mp-3630.cif
正在转换mp-3648.cif
正在转换mp-3651.cif
正在转换mp-3657.cif
正在转换mp-3676.cif
正在转换mp-3678.cif
正在转换mp-3686.cif
正在转换mp-36891.cif
正在转换mp-3693.cif
正在转换mp-3698.cif
正在转换mp-3702.cif
正在转换mp-3709.cif
正在转换mp-3710.cif
正在转换mp-3717.cif
正在转换mp-3726.cif
正在转换mp-3732.cif
正在转换mp-3734.cif
正在转换mp-3736.cif
正在转换mp-3769.cif
正在转换mp-3776.cif
正在转换mp-3791.cif
正在转换mp-3804.cif
正在转换mp-3805.cif
正在转换mp-3826.cif
正在转换mp-3827.cif
正在转换mp-3833.cif
正在转换mp-3847.cif
正在转换mp-3849.cif
正在转换mp-3854.cif
正在转换mp-3862.cif
正在转换mp-3869.cif
正在转换mp-3882.cif
正在转换mp-3893.cif
正在转换mp-3895.cif
正在转换mp-3907.cif
正在转换mp-3909.cif
正在转换mp-3927.cif
正在转换mp-3938.cif
正在转换mp-3939.cif
正在转换mp-3942.cif
正在转换mp-3944.cif
正在转换mp-3950.cif
正在转换mp-3958.cif
正在转换mp-3972.cif
正在转换mp-3985.cif
正在转换mp-3988.cif
正在转换mp-3997.cif
正在转换mp-3999.cif
正在转换mp-4007.cif
正在转换mp-4013.cif
正在转换mp-4014.cif
正在转换mp-4037.cif
正在转换mp-4041.cif
正在转换mp-4053.cif
正在转换mp-4064.cif
正在转换mp-4065.cif
正在转换mp-4072.cif
正在转换mp-4073.cif
正在转换mp-4075.cif
正在转换mp-4076.cif
正在转换mp-4079.cif
正在转换mp-4083.cif
正在转换mp-4088.cif
正在转换mp-4090.cif
正在转换mp-4105.cif
正在转换mp-4106.cif
正在转换mp-4109.cif
正在转换mp-4120.cif
正在转换mp-4131.cif
正在转换mp-4142.cif
正在转换mp-4147.cif
正在转换mp-4148.cif
正在转换mp-4150.cif
正在转换mp-4158.cif
正在转换mp-4171.cif
正在转换mp-4177.cif
正在转换mp-4181.cif
正在转换mp-4189.cif
正在转换mp-4195.cif
正在转换mp-4196.cif
正在转换mp-4206.cif
正在转换mp-4207.cif
正在转换mp-4210.cif
正在转换mp-4219.cif
正在转换mp-4228.cif
正在转换mp-4229.cif
正在转换mp-4230.cif
正在转换mp-4233.cif
正在转换mp-4238.cif
正在转换mp-4247.cif
正在转换mp-4248.cif
正在转换mp-4250.cif
正在转换mp-4259.cif
正在转换mp-4262.cif
正在转换mp-4275.cif
正在转换mp-4288.cif
正在转换mp-4291.cif
正在转换mp-4297.cif
正在转换mp-4299.cif
正在转换mp-4302.cif
正在转换mp-4304.cif
正在转换mp-4305.cif
正在转换mp-4311.cif
正在转换mp-4316.cif
正在转换mp-4322.cif
正在转换mp-4323.cif
正在转换mp-4334.cif
正在转换mp-4337.cif
正在转换mp-4343.cif
正在转换mp-4354.cif
正在转换mp-4364.cif
正在转换mp-4367.cif
正在转换mp-4370.cif
正在转换mp-4374.cif
正在转换mp-4382.cif
正在转换mp-4395.cif
正在转换mp-4402.cif
正在转换mp-4404.cif
正在转换mp-4410.cif
正在转换mp-4415.cif
正在转换mp-4416.cif
正在转换mp-4433.cif
正在转换mp-4439.cif
正在转换mp-4448.cif
正在转换mp-4450.cif
正在转换mp-4454.cif
正在转换mp-4458.cif
正在转换mp-4466.cif
正在转换mp-4469.cif
正在转换mp-4472.cif
正在转换mp-4475.cif
正在转换mp-4476.cif
正在转换mp-4483.cif
正在转换mp-4484.cif
正在转换mp-4487.cif
正在转换mp-4492.cif
正在转换mp-4494.cif
正在转换mp-4505.cif
正在转换mp-4508.cif
正在转换mp-4520.cif
正在转换mp-4521.cif
正在转换mp-4536.cif
正在转换mp-4537.cif
正在转换mp-4538.cif
正在转换mp-4539.cif
正在转换mp-4552.cif
正在转换mp-4561.cif
正在转换mp-4563.cif
正在转换mp-4583.cif
正在转换mp-4587.cif
正在转换mp-4593.cif
正在转换mp-4595.cif
正在转换mp-4596.cif
正在转换mp-4611.cif
正在转换mp-4612.cif
正在转换mp-4613.cif
正在转换mp-4614.cif
正在转换mp-4628.cif
正在转换mp-4633.cif
正在转换mp-4638.cif
正在转换mp-4652.cif
正在转换mp-4653.cif
正在转换mp-4660.cif
正在转换mp-4664.cif
正在转换mp-4668.cif
正在转换mp-4692.cif
正在转换mp-4711.cif
正在转换mp-4720.cif
正在转换mp-4725.cif
正在转换mp-4728.cif
正在转换mp-4729.cif
正在转换mp-4732.cif
正在转换mp-4738.cif
正在转换mp-4740.cif
正在转换mp-4742.cif
正在转换mp-4743.cif
正在转换mp-4744.cif
正在转换mp-4767.cif
正在转换mp-4771.cif
正在转换mp-4783.cif
正在转换mp-4785.cif
正在转换mp-4793.cif
正在转换mp-4808.cif
正在转换mp-4810.cif
正在转换mp-4813.cif
正在转换mp-4815.cif
正在转换mp-4822.cif
正在转换mp-4826.cif
正在转换mp-4828.cif
正在转换mp-4836.cif
正在转换mp-4846.cif
正在转换mp-4854.cif
正在转换mp-4856.cif
正在转换mp-4861.cif
正在转换mp-4865.cif
正在转换mp-4873.cif
正在转换mp-4878.cif
正在转换mp-4881.cif
正在转换mp-4883.cif
正在转换mp-4889.cif
正在转换mp-4893.cif
正在转换mp-4896.cif
正在转换mp-4903.cif
正在转换mp-4904.cif
正在转换mp-4908.cif
正在转换mp-4909.cif
正在转换mp-4913.cif
正在转换mp-4920.cif
正在转换mp-4922.cif
正在转换mp-4924.cif
正在转换mp-4936.cif
正在转换mp-4938.cif
正在转换mp-4939.cif
正在转换mp-4955.cif
正在转换mp-4962.cif
正在转换mp-4972.cif
正在转换mp-4973.cif
正在转换mp-4978.cif
正在转换mp-4982.cif
正在转换mp-4985.cif
正在转换mp-4989.cif
正在转换mp-4990.cif
正在转换mp-4992.cif
正在转换mp-4997.cif
正在转换mp-4999.cif
正在转换mp-5000.cif
正在转换mp-5015.cif
正在转换mp-5019.cif
正在转换mp-5022.cif
正在转换mp-5025.cif
正在转换mp-5031.cif
正在转换mp-5042.cif
正在转换mp-5054.cif
正在转换mp-5058.cif
正在转换mp-5069.cif
正在转换mp-5106.cif
正在转换mp-5109.cif
正在转换mp-5111.cif
正在转换mp-5112.cif
正在转换mp-5124.cif
正在转换mp-5129.cif
正在转换mp-5135.cif
正在转换mp-5137.cif
正在转换mp-5149.cif
正在转换mp-5154.cif
正在转换mp-5159.cif
正在转换mp-5161.cif
正在转换mp-5165.cif
正在转换mp-5166.cif
正在转换mp-5167.cif
正在转换mp-5177.cif
正在转换mp-5351.cif
正在转换mp-5353.cif
正在转换mp-5369.cif
正在转换mp-5372.cif
正在转换mp-5381.cif
正在转换mp-5383.cif
正在转换mp-5385.cif
正在转换mp-5386.cif
正在转换mp-5396.cif
正在转换mp-5399.cif
正在转换mp-5400.cif
正在转换mp-5407.cif
正在转换mp-5410.cif
正在转换mp-5419.cif
正在转换mp-5423.cif
正在转换mp-5429.cif
正在转换mp-5436.cif
正在转换mp-5438.cif
正在转换mp-5451.cif
正在转换mp-5452.cif
正在转换mp-5456.cif
正在转换mp-5486.cif
正在转换mp-5491.cif
正在转换mp-5493.cif
正在转换mp-5497.cif
正在转换mp-5498.cif
正在转换mp-5501.cif
正在转换mp-5505.cif
正在转换mp-5508.cif
正在转换mp-5510.cif
正在转换mp-5514.cif
正在转换mp-5517.cif
正在转换mp-5519.cif
正在转换mp-5528.cif
正在转换mp-5529.cif
正在转换mp-5541.cif
正在转换mp-5549.cif
正在转换mp-5553.cif
正在转换mp-5556.cif
正在转换mp-5561.cif
正在转换mp-5564.cif
正在转换mp-5577.cif
正在转换mp-5578.cif
正在转换mp-5589.cif
正在转换mp-5590.cif
正在转换mp-5591.cif
正在转换mp-5597.cif
正在转换mp-5605.cif
正在转换mp-5610.cif
正在转换mp-5620.cif
正在转换mp-5622.cif
正在转换mp-5627.cif
正在转换mp-5646.cif
正在转换mp-5660.cif
正在转换mp-5666.cif
正在转换mp-5671.cif
正在转换mp-5676.cif
正在转换mp-5677.cif
正在转换mp-5682.cif
正在转换mp-5688.cif
正在转换mp-5699.cif
正在转换mp-5702.cif
正在转换mp-5714.cif
正在转换mp-5720.cif
正在转换mp-5723.cif
正在转换mp-5729.cif
正在转换mp-5734.cif
正在转换mp-5739.cif
正在转换mp-5748.cif
正在转换mp-5752.cif
正在转换mp-5757.cif
正在转换mp-5778.cif
正在转换mp-5786.cif
正在转换mp-5796.cif
正在转换mp-5816.cif
正在转换mp-5819.cif
正在转换mp-5820.cif
正在转换mp-5835.cif
正在转换mp-5848.cif
正在转换mp-5850.cif
正在转换mp-5852.cif
正在转换mp-5866.cif
正在转换mp-5869.cif
正在转换mp-5898.cif
正在转换mp-5901.cif
正在转换mp-5910.cif
正在转换mp-5916.cif
正在转换mp-5919.cif
正在转换mp-5921.cif
正在转换mp-5934.cif
正在转换mp-5936.cif
正在转换mp-5938.cif
正在转换mp-5939.cif
正在转换mp-5940.cif
正在转换mp-5944.cif
正在转换mp-5948.cif
正在转换mp-5951.cif
正在转换mp-5976.cif
正在转换mp-5983.cif
正在转换mp-5992.cif
正在转换mp-607.cif
正在转换mp-6092.cif
正在转换mp-6098.cif
正在转换mp-6102.cif
正在转换mp-610.cif
正在转换mp-611.cif
正在转换mp-6123.cif
正在转换mp-6140.cif
正在转换mp-615.cif
正在转换mp-6188.cif
正在转换mp-6191.cif
正在转换mp-6223.cif
正在转换mp-623.cif
正在转换mp-6258.cif
正在转换mp-627.cif
正在转换mp-6286.cif
正在转换mp-631.cif
正在转换mp-632250.cif
正在转换mp-6328.cif
正在转换mp-632.cif
正在转换mp-635.cif
正在转换mp-645.cif
正在转换mp-646.cif
正在转换mp-647.cif
正在转换mp-6498.cif
正在转换mp-649.cif
正在转换mp-650.cif
正在转换mp-6544.cif
正在转换mp-6562.cif
正在转换mp-656.cif
正在转换mp-6576.cif
正在转换mp-657.cif
正在转换mp-6638.cif
正在转换mp-663.cif
正在转换mp-6646.cif
正在转换mp-668.cif
正在转换mp-669.cif
正在转换mp-670.cif
正在转换mp-673.cif
正在转换mp-6754.cif
正在转换mp-675.cif
正在转换mp-6908.cif
正在转换mp-6912.cif
正在转换mp-6914.cif
正在转换mp-6915.cif
正在转换mp-6917.cif
正在转换mp-6919.cif
正在转换mp-6926.cif
正在转换mp-6927.cif
正在转换mp-692.cif
正在转换mp-6931.cif
正在转换mp-6938.cif
正在转换mp-693.cif
正在转换mp-6940.cif
正在转换mp-6950.cif
正在转换mp-6953.cif
正在转换mp-6954.cif
正在转换mp-6957.cif
正在转换mp-6958.cif
正在转换mp-6959.cif
正在转换mp-695.cif
正在转换mp-6961.cif
正在转换mp-6962.cif
正在转换mp-6963.cif
正在转换mp-6969.cif
正在转换mp-696.cif
正在转换mp-6979.cif
正在转换mp-6982.cif
正在转换mp-6988.cif
正在转换mp-6996.cif
正在转换mp-6997.cif
正在转换mp-7002.cif
正在转换mp-7003.cif
正在转换mp-7006.cif
正在转换mp-7025.cif
正在转换mp-702.cif
正在转换mp-7032.cif
正在转换mp-7068.cif
正在转换mp-7070.cif
正在转换mp-7072.cif
正在转换mp-7086.cif
正在转换mp-7088.cif
正在转换mp-708.cif
正在转换mp-7092.cif

正在转换mp-7093.cif
正在转换mp-7097.cif
正在转换mp-7099.cif
正在转换mp-7101.cif
正在转换mp-7105.cif
正在转换mp-7107.cif
正在转换mp-7108.cif
正在转换mp-7109.cif
正在转换mp-710.cif
正在转换mp-7114.cif
正在转换mp-7120.cif
正在转换mp-7121.cif
正在转换mp-712.cif
正在转换mp-7130.cif
正在转换mp-7131.cif
正在转换mp-7132.cif
正在转换mp-7138.cif
正在转换mp-7142.cif
正在转换mp-7144.cif
正在转换mp-7157.cif
正在转换mp-7158.cif
正在转换mp-7159.cif
正在转换mp-715.cif
正在转换mp-7166.cif
正在转换mp-7167.cif
正在转换mp-7168.cif
正在转换mp-7169.cif
正在转换mp-7170.cif
正在转换mp-7171.cif
正在转换mp-7186.cif
正在转换mp-7187.cif
正在转换mp-7189.cif
正在转换mp-718.cif
正在转换mp-7192.cif
正在转换mp-7194.cif
正在转换mp-721.cif
正在转换mp-7225.cif
正在转换mp-7226.cif
正在转换mp-7239.cif
正在转换mp-7247.cif
正在转换mp-725.cif
正在转换mp-7263.cif
正在转换mp-7284.cif
正在转换mp-728.cif
正在转换mp-7291.cif
正在转换mp-7298.cif
正在转换mp-729.cif
正在转换mp-7303.cif
正在转换mp-731.cif
正在转换mp-7349.cif
正在转换mp-7359.cif
正在转换mp-7361.cif
正在转换mp-7363.cif
正在转换mp-7364.cif
正在转换mp-7365.cif
正在转换mp-7366.cif
正在转换mp-7381.cif
正在转换mp-7390.cif
正在转换mp-7396.cif
正在转换mp-739.cif
正在转换mp-7400.cif
正在转换mp-7420.cif
正在转换mp-7422.cif
正在转换mp-7424.cif
正在转换mp-7426.cif
正在转换mp-7429.cif
正在转换mp-742.cif
正在转换mp-7431.cif
正在转换mp-7432.cif
正在转换mp-7443.cif
正在转换mp-744.cif
正在转换mp-745.cif
正在转换mp-7473.cif
正在转换mp-7474.cif
正在转换mp-7479.cif
正在转换mp-747.cif
正在转换mp-7486.cif
正在转换mp-7496.cif
正在转换mp-7497.cif
正在转换mp-7498.cif
正在转换mp-749.cif
正在转换mp-7524.cif
正在转换mp-7526.cif
正在转换mp-7540.cif
正在转换mp-7541.cif
正在转换mp-7542.cif
正在转换mp-7543.cif
正在转换mp-7544.cif
正在转换mp-7554.cif
正在转换mp-7555.cif
正在转换mp-756.cif
正在转换mp-761.cif
正在转换mp-763.cif
正在转换mp-764.cif
正在转换mp-767.cif
正在转换mp-768.cif
正在转换mp-770.cif
正在转换mp-771.cif
正在转换mp-772.cif
正在转换mp-774.cif
正在转换mp-778.cif
正在转换mp-786.cif
正在转换mp-7875.cif
正在转换mp-7876.cif
正在转换mp-7877.cif
正在转换mp-7878.cif
正在转换mp-7879.cif
正在转换mp-7880.cif
正在转换mp-7881.cif
正在转换mp-7882.cif
正在转换mp-7883.cif
正在转换mp-788.cif
正在转换mp-7892.cif
正在转换mp-7898.cif
正在转换mp-7915.cif
正在转换mp-7916.cif
正在转换mp-7917.cif
正在转换mp-7918.cif
正在转换mp-7930.cif
正在转换mp-7935.cif
正在转换mp-7942.cif
正在转换mp-7947.cif
正在转换mp-7948.cif
正在转换mp-7961.cif
正在转换mp-796.cif
正在转换mp-797.cif
正在转换mp-8003.cif
正在转换mp-800.cif
正在转换mp-8018.cif
正在转换mp-801.cif
正在转换mp-8020.cif
正在转换mp-8022.cif
正在转换mp-8023.cif
正在转换mp-803.cif
正在转换mp-8044.cif
正在转换mp-8053.cif
正在转换mp-806.cif
正在转换mp-8074.cif
正在转换mp-807.cif
正在转换mp-8093.cif
正在转换mp-8094.cif
正在转换mp-8096.cif
正在转换mp-8097.cif
正在转换mp-809.cif
正在转换mp-8102.cif
正在转换mp-810.cif
正在转换mp-8119.cif
正在转换mp-811.cif
正在转换mp-8120.cif
正在转换mp-8121.cif
正在转换mp-8122.cif
正在转换mp-8123.cif
正在转换mp-8125.cif
正在转换mp-8126.cif
正在转换mp-8129.cif
正在转换mp-8137.cif
正在转换mp-813.cif
正在转换mp-8146.cif
正在转换mp-814.cif
正在转换mp-8150.cif
正在转换mp-8159.cif
正在转换mp-815.cif
正在转换mp-817.cif
正在转换mp-818.cif
正在转换mp-819.cif
正在转换mp-820.cif
正在转换mp-8219.cif
正在转换mp-8220.cif
正在转换mp-8221.cif
正在转换mp-8222.cif
正在转换mp-8236.cif
正在转换mp-8237.cif
正在转换mp-823.cif
正在转换mp-825.cif
正在转换mp-8282.cif
正在转换mp-828.cif
正在转换mp-829.cif
正在转换mp-8310.cif
正在转换mp-8312.cif
正在转换mp-8320.cif
正在转换mp-8322.cif
正在转换mp-832.cif
正在转换mp-8338.cif
正在转换mp-833.cif
正在转换mp-834.cif
正在转换mp-8365.cif
正在转换mp-8368.cif
正在转换mp-836.cif
正在转换mp-8370.cif
正在转换mp-8371.cif
正在转换mp-8372.cif
正在转换mp-8375.cif
正在转换mp-838.cif
正在转换mp-839.cif
正在转换mp-840.cif
正在转换mp-842.cif
正在转换mp-8432.cif
正在转换mp-8456.cif
正在转换mp-8475.cif
正在转换mp-8481.cif
正在转换mp-8499.cif
正在转换mp-850.cif
正在转换mp-851.cif
正在转换mp-8528.cif
正在转换mp-8539.cif
正在转换mp-853.cif
正在转换mp-8540.cif
正在转换mp-8557.cif
正在转换mp-8558.cif
正在转换mp-8577.cif
正在转换mp-8578.cif
正在转换mp-8580.cif
正在转换mp-8581.cif
正在转换mp-8583.cif
正在转换mp-858.cif
正在转换mp-8591.cif
正在转换mp-8605.cif
正在转换mp-8606.cif
正在转换mp-8628.cif
正在转换mp-862.cif
正在转换mp-863.cif
正在转换mp-8654.cif
正在转换mp-8655.cif
正在转换mp-865.cif
正在转换mp-8676.cif
正在转换mp-867.cif
正在转换mp-869.cif
正在转换mp-872.cif
正在转换mp-873.cif
正在转换mp-8758.cif
正在转换mp-875.cif
正在转换mp-8761.cif
正在转换mp-877.cif
正在转换mp-8780.cif
正在转换mp-881.cif
正在转换mp-8832.cif
正在转换mp-889.cif
正在转换mp-890.cif
正在转换mp-891.cif
正在转换mp-892.cif
正在转换mp-8937.cif
正在转换mp-893.cif
正在转换mp-8948.cif
正在转换mp-8949.cif
正在转换mp-894.cif
正在转换mp-8950.cif
正在转换mp-8951.cif
正在转换mp-8969.cif
正在转换mp-8996.cif
正在转换mp-899.cif
正在转换mp-900.cif
正在转换mp-9023.cif
正在转换mp-9024.cif
正在转换mp-9025.cif
正在转换mp-902.cif
正在转换mp-9033.cif
正在转换mp-903.cif
正在转换mp-9040.cif
正在转换mp-9042.cif
正在转换mp-9060.cif
正在转换mp-9061.cif
正在转换mp-910.cif
正在转换mp-912.cif
正在转换mp-915.cif
正在转换mp-9164.cif
正在转换mp-916.cif
正在转换mp-9177.cif
正在转换mp-919.cif
正在转换mp-921.cif
正在转换mp-9220.cif
正在转换mp-9223.cif
正在转换mp-922.cif
正在转换mp-9241.cif
正在转换mp-925.cif
正在转换mp-9264.cif
正在转换mp-926.cif
正在转换mp-9277.cif
正在转换mp-9289.cif
正在转换mp-928.cif
正在转换mp-929.cif
正在转换mp-930.cif
正在转换mp-9312.cif
正在转换mp-931.cif
正在转换mp-932.cif
正在转换mp-9339.cif
正在转换mp-933.cif
正在转换mp-9343.cif
正在转换mp-934.cif
正在转换mp-9350.cif
正在转换mp-9351.cif
正在转换mp-9357.cif
正在转换mp-9369.cif
正在转换mp-936.cif
正在转换mp-9439.cif
正在转换mp-944.cif
正在转换mp-946.cif
正在转换mp-9472.cif
正在转换mp-9473.cif
正在转换mp-9487.cif
正在转换mp-948.cif
正在转换mp-949.cif
正在转换mp-951.cif
正在转换mp-9527.cif
正在转换mp-952.cif
正在转换mp-953.cif
正在转换mp-9549.cif
正在转换mp-954.cif
正在转换mp-9550.cif
正在转换mp-9556.cif
正在转换mp-956.cif
正在转换mp-9578.cif
正在转换mp-957.cif
正在转换mp-9586.cif
正在转换mp-9587.cif
正在转换mp-958.cif
正在转换mp-9615.cif
正在转换mp-965.cif
正在转换mp-9690.cif
正在转换mp-969.cif
正在转换mp-9721.cif
正在转换mp-972256.cif
正在转换mp-972.cif
正在转换mp-973.cif
正在转换mp-9743.cif
正在转换mp-9744.cif
正在转换mp-9752.cif
正在转换mp-977.cif
正在转换mp-982.cif
正在转换mp-9833.cif
正在转换mp-9834.cif
正在转换mp-985.cif
正在转换mp-986.cif
正在转换mp-987.cif
正在转换mp-9908.cif
正在转换mp-990.cif
正在转换mp-9916.cif
正在转换mp-991.cif
正在转换mp-9923.cif
正在转换mp-9926.cif
正在转换mp-9927.cif
正在转换mp-992.cif
正在转换mp-9930.cif
正在转换mp-9935.cif
正在转换mp-9937.cif
正在转换mp-9938.cif
正在转换mp-9939.cif
正在转换mp-993.cif
正在转换mp-9945.cif
正在转换mp-994.cif
正在转换mp-9951.cif
正在转换mp-9953.cif
正在转换mp-9954.cif
正在转换mp-9956.cif
正在转换mp-9957.cif
正在转换mp-9958.cif
正在转换mp-9960.cif
正在转换mp-9961.cif
正在转换mp-9964.cif
正在转换mp-9967.cif
正在转换mp-9968.cif
正在转换mp-9969.cif
正在转换mp-996.cif
正在转换mp-9970.cif
正在转换mp-9971.cif
正在转换mp-9972.cif
正在转换mp-9973.cif
正在转换mp-9978.cif
正在转换mp-9985.cif
正在转换mp-9987.cif
正在转换mp-9988.cif
正在转换mp-9989.cif
正在转换mp-9998.cif
正在转换mp-9999.cif
正在转换mvc-10882.cif
正在转换mvc-11038.cif
正在转换mvc-11047.cif
正在转换mvc-11070.cif
正在转换mvc-11152.cif
正在转换mvc-11155.cif
正在转换mvc-11196.cif
正在转换mvc-11198.cif
正在转换mvc-11224.cif
正在转换mvc-11225.cif
正在转换mvc-11226.cif
正在转换mvc-11235.cif
正在转换mvc-11548.cif
正在转换mvc-11693.cif
正在转换mvc-11732.cif
正在转换mvc-11775.cif
正在转换mvc-13133.cif
正在转换mvc-13140.cif
正在转换mvc-13350.cif
正在转换mvc-13598.cif
正在转换mvc-13742.cif
正在转换mvc-13808.cif
正在转换mvc-13927.cif
正在转换mvc-14600.cif
正在转换mvc-14991.cif
正在转换mvc-15239.cif
正在转换mvc-15448.cif
正在转换mvc-15474.cif
正在转换mvc-15475.cif
正在转换mvc-15476.cif
正在转换mvc-15603.cif
正在转换mvc-15604.cif
正在转换mvc-15677.cif
正在转换mvc-15707.cif
正在转换mvc-15840.cif
正在转换mvc-15843.cif
正在转换mvc-15849.cif
正在转换mvc-15856.cif
正在转换mvc-16021.cif
正在转换mvc-16067.cif
正在转换mvc-16079.cif
正在转换mvc-16089.cif
正在转换mvc-7053.cif
正在转换mvc-7055.cif
正在转换mvc-7056.cif
正在转换mvc-7057.cif
正在转换mvc-7058.cif
正在转换mp-1059.cif
正在转换mp-1061.cif
正在转换mp-1062.cif
正在转换mp-1065.cif
正在转换mp-1069.cif
正在转换mp-1073.cif
正在转换mp-1076.cif
正在转换mp-1077.cif
正在转换mp-1081.cif
正在转换mp-1082.cif
正在转换mp-1083.cif
正在转换mp-1085.cif
正在转换mp-1086.cif
正在转换mp-1088.cif
正在转换mp-1089.cif
正在转换mp-1090.cif
正在转换mp-1092.cif
正在转换mp-1093.cif
正在转换mp-1097.cif
正在转换mp-1099.cif
正在转换mp-1101.cif
正在转换mp-1108.cif
正在转换mp-1112.cif
正在转换mp-1113.cif
正在转换mp-1114.cif
正在转换mp-1120.cif
正在转换mp-1121.cif
正在转换mp-1123.cif
正在转换mp-1127.cif
正在转换mp-1128.cif
正在转换mp-1129.cif
正在转换mp-1132.cif
正在转换mp-1135.cif
正在转换mp-1139.cif
正在转换mp-1144.cif
正在转换mp-1145.cif
正在转换mp-1148.cif
正在转换mp-1152.cif
正在转换mp-1156.cif
正在转换mp-1157.cif
正在转换mp-1159.cif
正在转换mp-1161.cif
正在转换mp-1164.cif
正在转换mp-1169.cif
正在转换mp-1172.cif
正在转换mp-1174.cif
正在转换mp-1176.cif
正在转换mp-1179.cif
正在转换mp-1180.cif
正在转换mp-266.cif
正在转换mp-269.cif
正在转换mp-274.cif
正在转换mp-276.cif
正在转换mp-280.cif
正在转换mp-281.cif
正在转换mp-284.cif
正在转换mp-291.cif
正在转换mp-292.cif
正在转换mp-295.cif
正在转换mp-300.cif
正在转换mp-305.cif
正在转换mp-309.cif
正在转换mp-310.cif
正在转换mp-312.cif
正在转换mp-313.cif
正在转换mp-316.cif
正在转换mp-317.cif
正在转换mp-318.cif
正在转换mp-319.cif
正在转换mp-321.cif
正在转换mp-328.cif
正在转换mp-331.cif
正在转换mp-333.cif
正在转换mp-335.cif
正在转换mp-336.cif
正在转换mp-339.cif
正在转换mp-342.cif
正在转换mp-343.cif
正在转换mp-345.cif
正在转换mp-348.cif
正在转换mp-350.cif
正在转换mp-351.cif
正在转换mp-353.cif
正在转换mp-357.cif
正在转换mp-363.cif
正在转换mp-364.cif
正在转换mp-372.cif
正在转换mp-374.cif
正在转换mp-376.cif
正在转换mp-378.cif
正在转换mp-379.cif
正在转换mp-381.cif
正在转换mp-387.cif
正在转换mp-388.cif
正在转换mp-389.cif
正在转换mp-391.cif
正在转换mp-394.cif
正在转换mp-395.cif
正在转换mp-398.cif
正在转换mp-400.cif
正在转换mp-404.cif
正在转换mp-410.cif
正在转换mp-413.cif
正在转换mp-416.cif
正在转换mp-417.cif
正在转换mp-419.cif
正在转换mp-421.cif
正在转换mp-423.cif
正在转换mp-426.cif
正在转换mp-427.cif
正在转换mp-428.cif
正在转换mp-429.cif
正在转换mp-432.cif
正在转换mp-434.cif
正在转换mp-435.cif
正在转换mp-436.cif
正在转换mp-437.cif
正在转换mp-442.cif
正在转换mp-443.cif
正在转换mp-445.cif
正在转换mp-446.cif
正在转换mp-447.cif
正在转换mp-448.cif
正在转换mp-450.cif
正在转换mp-451.cif
正在转换mp-454.cif
正在转换mp-460.cif
正在转换mp-464.cif
正在转换mp-472.cif
正在转换mp-474.cif
正在转换mp-475.cif
正在转换mp-477.cif

正在转换mp-480.cif
正在转换mp-481.cif
正在转换mp-485.cif
正在转换mp-4870.cif
正在转换mp-4907.cif
正在转换mp-492.cif
正在转换mp-495.cif
正在转换mp-4971.cif
正在转换mp-4975.cif
正在转换mp-4988.cif
正在转换mp-4998.cif
正在转换mp-5005.cif
正在转换mp-5012.cif
正在转换mp-5024.cif
正在转换mp-5036.cif
正在转换mp-503.cif
正在转换mp-5040.cif
正在转换mp-5046.cif
正在转换mp-5050.cif
正在转换mp-5063.cif
正在转换mp-506.cif
正在转换mp-5078.cif
正在转换mp-5079.cif
正在转换mp-507.cif
正在转换mp-5080.cif
正在转换mp-5082.cif
正在转换mp-5091.cif
正在转换mp-5094.cif
正在转换mp-5116.cif
正在转换mp-511.cif
正在转换mp-5121.cif
正在转换mp-5132.cif
正在转换mp-513.cif
正在转换mp-514.cif
正在转换mp-5156.cif
正在转换mp-515.cif
正在转换mp-5160.cif
正在转换mp-517.cif
正在转换mp-5185.cif
正在转换mp-519.cif
正在转换mp-5214.cif
正在转换mp-522.cif
正在转换mp-5241.cif
正在转换mp-5248.cif
正在转换mp-5251.cif
正在转换mp-526.cif
正在转换mp-527.cif
正在转换mp-5285.cif
正在转换mp-529.cif
正在转换mp-5305.cif
正在转换mp-5306.cif
正在转换mp-5321.cif
正在转换mp-5322.cif
正在转换mp-535.cif
正在转换mp-536.cif
正在转换mp-537.cif
正在转换mp-538.cif
正在转换mp-540.cif
正在转换mp-541.cif
正在转换mp-542.cif
正在转换mp-544.cif
正在转换mp-545.cif
正在转换mp-546.cif
正在转换mp-548.cif
正在转换mp-549.cif
正在转换mp-551.cif
正在转换mp-555.cif
正在转换mp-558.cif
正在转换mp-559.cif
正在转换mp-560.cif
正在转换mp-564.cif
正在转换mp-565.cif
正在转换mp-568.cif
正在转换mp-569.cif
正在转换mp-570.cif
正在转换mp-571.cif
正在转换mp-572.cif
正在转换mp-574.cif
正在转换mp-578.cif
正在转换mp-579.cif
正在转换mp-580.cif
正在转换mp-582.cif
正在转换mp-583.cif
正在转换mp-585.cif
正在转换mp-589.cif
正在转换mp-592.cif
正在转换mp-594.cif
正在转换mp-600.cif
正在转换mp-601.cif
正在转换mp-603.cif
正在转换mp-170.cif
正在转换mp-171.cif
正在转换mp-177.cif
正在转换mp-178.cif
正在转换mp-179.cif
正在转换mp-182.cif
正在转换mp-183.cif
正在转换mp-190.cif
正在转换mp-191.cif
正在转换mp-193.cif
正在转换mp-195.cif
正在转换mp-203.cif
正在转换mp-204.cif
正在转换mp-208.cif
正在转换mp-213.cif
正在转换mp-214.cif
正在转换mp-215.cif
正在转换mp-217.cif
正在转换mp-219.cif
正在转换mp-220.cif
正在转换mp-232.cif
正在转换mp-237.cif
正在转换mp-238.cif
正在转换mp-242.cif
正在转换mp-246.cif
正在转换mp-248.cif
正在转换mp-249.cif
正在转换mp-250.cif
正在转换mp-251.cif
正在转换mp-253.cif
正在转换mp-255.cif
正在转换mp-256.cif
正在转换mp-257.cif
正在转换mp-258.cif
正在转换mp-259.cif
正在转换mp-260.cif
正在转换mp-265.cif
正在转换mp-7565.cif
正在转换mp-7568.cif
正在转换mp-7570.cif
正在转换mp-7573.cif
正在转换mp-7574.cif
正在转换mp-7576.cif
正在转换mp-7577.cif
正在转换mp-7586.cif
正在转换mp-7590.cif
正在转换mp-7591.cif
正在转换mp-7592.cif
正在转换mp-7600.cif
正在转换mp-7632.cif
正在转换mp-7655.cif
正在转换mp-7660.cif
正在转换mp-7692.cif
正在转换mp-7698.cif
正在转换mp-7704.cif
正在转换mp-7707.cif
正在转换mp-7711.cif
正在转换mp-7753.cif
正在转换mp-7754.cif
正在转换mp-7759.cif
正在转换mp-7777.cif
正在转换mp-7778.cif
正在转换mp-7779.cif
正在转换mp-7790.cif
正在转换mp-7804.cif
正在转换mp-7821.cif
正在转换mp-7823.cif
正在转换mp-7829.cif
正在转换mp-7830.cif
正在转换mp-7832.cif
正在转换mp-7857.cif
正在转换mp-7861.cif
正在转换mp-7874.cif
正在转换mp-1006883.cif
正在转换mp-1008349.cif
正在转换mp-1009264.cif
正在转换mp-1010953.cif
正在转换mp-12766.cif
正在转换mp-18427.cif
正在转换mp-542488.cif
正在转换mp-570557.cif
正在转换mp-622209.cif
正在转换mp-672232.cif
正在转换mp-7250.cif
正在转换mp-864931.cif
正在转换mp-865960.cif
正在转换mp-977283.cif
正在转换mp-977426.cif
正在转换mp-978271.cif
正在转换mp-978276.cif
正在转换mp-978288.cif
正在转换mp-999188.cif
正在转换mp-999378.cif
正在转换mp-999394.cif
正在转换mp-999396.cif
正在转换mp-999437.cif
正在转换mp-1000.cif
正在转换mp-10163.cif
正在转换mp-10167.cif
正在转换mp-10182.cif
正在转换mp-10226.cif
正在转换mp-1022.cif
正在转换mp-10314.cif
正在转换mp-10322.cif
正在转换mp-1039.cif
正在转换mp-10401.cif
正在转换mp-10402.cif
正在转换mp-10408.cif
正在转换mp-10550.cif
正在转换mp-10572.cif
正在转换mp-10616.cif
正在转换mp-10623.cif
正在转换mp-10644.cif
正在转换mp-10667.cif
正在转换mp-10695.cif
正在转换mp-10748.cif
正在转换mp-10778.cif
正在转换mp-10779.cif
正在转换mp-10780.cif
正在转换mp-10782.cif
正在转换mp-10783.cif
正在转换mp-10784.cif
正在转换mp-10785.cif
正在转换mp-1087.cif
正在转换mp-10930.cif
正在转换mp-10933.cif
正在转换mp-10969.cif
正在转换mp-10996.cif
正在转换mp-11020.cif
正在转换mp-11022.cif
正在转换mp-1102.cif
正在转换mp-1105.cif
正在转换mp-11107.cif
正在转换mp-11175.cif
正在转换mp-11178.cif
正在转换mp-11219.cif
正在转换mp-11327.cif
正在转换mp-1153.cif
正在转换mp-11695.cif
正在转换mp-11703.cif
正在转换mp-11719.cif
正在转换mp-11740.cif
正在转换mp-11775.cif
正在转换mp-11824.cif
正在转换mp-11836.cif
正在转换mp-11869.cif
正在转换mp-11917.cif
正在转换mp-1216.cif
正在转换mp-1224.cif
正在转换mp-12317.cif
正在转换mp-12442.cif
正在转换mp-12444.cif
正在转换mp-12509.cif
正在转换mp-12516.cif
正在转换mp-12532.cif
正在转换mp-1253.cif
正在转换mp-12558.cif
正在转换mp-12620.cif
正在转换mp-1266.cif
正在转换mp-12902.cif
正在转换mp-12903.cif
正在转换mp-12904.cif
正在转换mp-12908.cif
正在转换mp-12953.cif
正在转换mp-12954.cif
正在转换mp-13031.cif
正在转换mp-13097.cif
正在转换mp-1315.cif
正在转换mp-13206.cif
正在转换mp-13275.cif
正在转换mp-13276.cif
正在转换mp-13277.cif
正在转换mp-1327.cif
正在转换mp-13312.cif
正在转换mp-13313.cif
正在转换mp-13396.cif
正在转换mp-1342.cif
正在转换mp-13610.cif
正在转换mp-13660.cif
正在转换mp-13694.cif
正在转换mp-13695.cif
正在转换mp-13949.cif
正在转换mp-13971.cif
正在转换mp-13972.cif
正在转换mp-13974.cif
正在转换mp-13975.cif
正在转换mp-13984.cif
正在转换mp-14017.cif
正在转换mp-14018.cif
正在转换mp-14088.cif
正在转换mp-14091.cif
正在转换mp-14092.cif
正在转换mp-14093.cif
正在转换mp-14115.cif
正在转换mp-14116.cif
正在转换mp-1413.cif
正在转换mp-1415.cif
正在转换mp-14205.cif
正在转换mp-14206.cif
正在转换mp-14437.cif
正在转换mp-1479.cif
正在转换mp-14983.cif
正在转换mp-1500.cif
正在转换mp-1519.cif
正在转换mp-1522.cif
正在转换mp-1541.cif
正在转换mp-1548.cif
正在转换mp-1550.cif
正在转换mp-15684.cif
正在转换mp-15685.cif
正在转换mp-1569.cif
正在转换mp-15703.cif
正在转换mp-15724.cif
正在转换mp-15776.cif
正在转换mp-15777.cif
正在转换mp-15782.cif
正在转换mp-15783.cif
正在转换mp-15785.cif
正在转换mp-15786.cif
正在转换mp-15788.cif
正在转换mp-15789.cif
正在转换mp-15790.cif
正在转换mp-15791.cif
正在转换mp-15794.cif
正在转换mp-15795.cif
正在转换mp-15796.cif
正在转换mp-15797.cif
正在转换mp-1591.cif
正在转换mp-1597.cif
正在转换mp-1598.cif
正在转换mp-16032.cif
正在转换mp-16033.cif
正在转换mp-16036.cif
正在转换mp-16037.cif
正在转换mp-16236.cif
正在转换mp-16238.cif
正在转换mp-16337.cif
正在转换mp-1672.cif
正在转换mp-16742.cif
正在转换mp-16763.cif
正在转换mp-16764.cif
正在转换mp-1747.cif
正在转换mp-1776.cif
正在转换mp-1779.cif
正在转换mp-1783.cif
正在转换mp-1820.cif
正在转换mp-1837.cif
正在转换mp-1852.cif
正在转换mp-1873.cif
正在转换mp-18793.cif
正在转换mp-1880.cif
正在转换mp-18921.cif
正在转换mp-18957.cif
正在转换mp-189.cif
正在转换mp-19045.cif
正在转换mp-19140.cif
正在转换mp-19149.cif
正在转换mp-19167.cif
正在转换mp-19225.cif
正在转换mp-19252.cif
正在转换mp-19340.cif
正在转换mp-19359.cif
正在转换mp-19378.cif
正在转换mp-19391.cif
正在转换mp-19414.cif
正在转换mp-1958.cif
正在转换mp-1960.cif
正在转换mp-19716.cif
正在转换mp-1975.cif
正在转换mp-19765.cif
正在转换mp-19795.cif
正在转换mp-19799.cif
正在转换mp-19830.cif
正在转换mp-19833.cif
正在转换mp-19851.cif
正在转换mp-19896.cif
正在转换mp-20025.cif
正在转换mp-20072.cif
正在转换mp-2008.cif
正在转换mp-20132.cif
正在转换mp-20185.cif
正在转换mp-20187.cif
正在转换mp-20261.cif
正在转换mp-20289.cif
正在转换mp-20458.cif
正在转换mp-20459.cif
正在转换mp-2068.cif
正在转换mp-2071.cif
正在转换mp-2072.cif
正在转换mp-20731.cif
正在转换mp-2074.cif
正在转换mp-20782.cif
正在转换mp-20790.cif
正在转换mp-20832.cif
正在转换mp-21022.cif
正在转换mp-2114.cif
正在转换mp-21228.cif
正在转换mp-21272.cif
正在转换mp-2133.cif
正在转换mp-21374.cif
正在转换mp-2172.cif
正在转换mp-2176.cif
正在转换mp-21855.cif
正在转换mp-22003.cif
正在转换mp-22205.cif
正在转换mp-22255.cif
正在转换mp-22261.cif
正在转换mp-22304.cif
正在转换mp-22313.cif
正在转换mp-2242.cif
正在转换mp-22473.cif
正在转换mp-22483.cif
正在转换mp-2251.cif
正在转换mp-2252.cif
正在转换mp-22607.cif
正在转换mp-22660.cif
正在转换mp-22691.cif
正在转换mp-22849.cif
正在转换mp-22859.cif
正在转换mp-22867.cif
正在转换mp-2286.cif
正在转换mp-22870.cif
正在转换mp-22877.cif
正在转换mp-22880.cif
正在转换mp-22881.cif
正在转换mp-22882.cif
正在转换mp-22885.cif
正在转换mp-22888.cif
正在转换mp-22897.cif
正在转换mp-22898.cif
正在转换mp-22903.cif
正在转换mp-22909.cif
正在转换mp-22913.cif
正在转换mp-22914.cif
正在转换mp-22916.cif
正在转换mp-22922.cif
正在转换mp-22925.cif
正在转换mp-22934.cif
正在转换mp-22936.cif
正在转换mp-22937.cif
正在转换mp-22939.cif
正在转换mp-22945.cif
正在转换mp-22947.cif
正在转换mp-22951.cif
正在转换mp-22956.cif
正在转换mp-22958.cif
正在转换mp-22964.cif
正在转换mp-22965.cif
正在转换mp-22975.cif
正在转换mp-22978.cif
正在转换mp-22981.cif
正在转换mp-22987.cif
正在转换mp-23008.cif
正在转换mp-23009.cif
正在转换mp-23021.cif
正在转换mp-23033.cif
正在转换mp-23036.cif
正在转换mp-23040.cif
正在转换mp-23046.cif
正在转换mp-23052.cif
正在转换mp-23056.cif
正在转换mp-23058.cif
正在转换mp-23059.cif
正在转换mp-23067.cif
正在转换mp-23068.cif
正在转换mp-23070.cif
正在转换mp-23072.cif
正在转换mp-2314.cif
正在转换mp-23162.cif
正在转换mp-23177.cif
正在转换mp-23183.cif
正在转换mp-23189.cif
正在转换mp-2319.cif
正在转换mp-23202.cif
正在转换mp-23211.cif
正在转换mp-23218.cif
正在转换mp-23221.cif
正在转换mp-23240.cif
正在转换mp-23251.cif
正在转换mp-23262.cif
正在转换mp-23268.cif
正在转换mp-23292.cif
正在转换mp-23295.cif
正在转换mp-23297.cif
正在转换mp-23309.cif
正在转换mp-23350.cif
正在转换mp-23353.cif
正在转换mp-23472.cif
正在转换mp-23475.cif
正在转换mp-23485.cif
正在转换mp-23513.cif
正在转换mp-2352.cif
正在转换mp-23703.cif
正在转换mp-23710.cif
正在转换mp-2371.cif
正在转换mp-23737.cif
正在转换mp-23804.cif
正在转换mp-23818.cif
正在转换mp-23859.cif
正在转换mp-23860.cif
正在转换mp-23861.cif
正在转换mp-23862.cif
正在转换mp-23870.cif
正在转换mp-23879.cif
正在转换mp-23933.cif
正在转换mp-23956.cif
正在转换mp-239.cif
正在转换mp-2400.cif
正在转换mp-24012.cif
正在转换mp-24066.cif
正在转换mp-24084.cif
正在转换mp-241.cif
正在转换mp-24204.cif
正在转换mp-24205.cif
正在转换mp-24292.cif
正在转换mp-24422.cif
正在转换mp-24423.cif
正在转换mp-24424.cif
正在转换mp-2455.cif
正在转换mp-24721.cif
正在转换mp-2472.cif
正在转换mp-24850.cif
正在转换mp-24905.cif
正在转换mp-2490.cif
正在转换mp-25047.cif
正在转换mp-25118.cif
正在转换mp-2516.cif
正在转换mp-252.cif
正在转换mp-2530.cif
正在转换mp-2534.cif
正在转换mp-25475.cif
正在转换mp-2558.cif
正在转换mp-2605.cif
正在转换mp-2624.cif
正在转换mp-2654.cif
正在转换mp-2659.cif
正在转换mp-2672.cif
正在转换mp-2691.cif
正在转换mp-2695.cif
正在转换mp-2697.cif
正在转换mp-2706.cif
正在转换mp-27138.cif
正在转换mp-27193.cif
正在转换mp-27194.cif
正在转换mp-27207.cif
正在转换mp-27246.cif
正在转换mp-27294.cif
正在转换mp-27304.cif
正在转换mp-27315.cif
正在转换mp-27396.cif
正在转换mp-27397.cif
正在转换mp-27420.cif
正在转换mp-27421.cif
正在转换mp-27438.cif
正在转换mp-27439.cif
正在转换mp-27455.cif

正在转换mp-27529.cif
正在转换mp-27549.cif
正在转换mp-27562.cif
正在转换mp-27616.cif
正在转换mp-27632.cif
正在转换mp-27637.cif
正在转换mp-27639.cif
正在转换mp-27666.cif
正在转换mp-27691.cif
正在转换mp-27702.cif
正在转换mp-27703.cif
正在转换mp-27716.cif
正在转换mp-27724.cif
正在转换mp-27725.cif
正在转换mp-27743.cif
正在转换mp-27770.cif
正在转换mp-27823.cif
正在转换mp-27827.cif
正在转换mp-27829.cif
正在转换mp-27831.cif
正在转换mp-27832.cif
正在转换mp-27833.cif
正在转换mp-27834.cif
正在转换mp-27839.cif
正在转换mp-27849.cif
正在转换mp-2784.cif
正在转换mp-27850.cif
正在转换mp-27869.cif
正在转换mp-27871.cif
正在转换mp-27910.cif
正在转换mp-27934.cif
正在转换mp-2793.cif
正在转换mp-27947.cif
正在转换mp-27972.cif
正在转换mp-27975.cif
正在转换mp-27976.cif
正在转换mp-27980.cif
正在转换mp-27984.cif
正在转换mp-27999.cif
正在转换mp-28013.cif
正在转换mp-28044.cif
正在转换mp-28065.cif
正在转换mp-28066.cif
正在转换mp-28067.cif
正在转换mp-28069.cif
正在转换mp-28084.cif
正在转换mp-28099.cif
正在转换mp-28110.cif
正在转换mp-28145.cif
正在转换mp-28163.cif
正在转换mp-28166.cif
正在转换mp-28171.cif
正在转换mp-28174.cif
正在转换mp-28233.cif
正在转换mp-28237.cif
正在转换mp-28266.cif
正在转换mp-28302.cif
正在转换mp-28306.cif
正在转换mp-28448.cif
正在转换mp-28458.cif
正在转换mp-28479.cif
正在转换mp-28483.cif
正在转换mp-28554.cif
正在转换mp-28591.cif
正在转换mp-28599.cif
正在转换mp-28602.cif
正在转换mp-28627.cif
正在转换mp-286.cif
正在转换mp-28797.cif
正在转换mp-288.cif
正在转换mp-28928.cif
正在转换mp-28929.cif
正在转换mp-28944.cif
正在转换mp-2894.cif
正在转换mp-29027.cif
正在转换mp-29055.cif
正在转换mp-29091.cif
正在转换mp-29132.cif
正在转换mp-29133.cif
正在转换mp-29138.cif
正在转换mp-29149.cif
正在转换mp-29208.cif
正在转换mp-29209.cif
正在转换mp-29254.cif
正在转换mp-29327.cif
正在转换mp-29342.cif
正在转换mp-29403.cif
正在转换mp-29443.cif
正在转换mp-29484.cif
正在转换mp-29496.cif
正在转换mp-29504.cif
正在转换mp-29521.cif
正在转换mp-29584.cif
正在转换mp-29585.cif
正在转换mp-2961.cif
正在转换mp-2964.cif
正在转换mp-29662.cif
正在转换mp-29666.cif
正在转换mp-29889.cif
正在转换mp-30031.cif
正在转换mp-30034.cif
正在转换mp-30041.cif
正在转换mp-30247.cif
正在转换mp-30250.cif
正在转换mp-30273.cif
正在转换mp-30274.cif
正在转换mp-30291.cif
正在转换mp-30315.cif
正在转换mp-30373.cif
正在转换mp-3038.cif
正在转换mp-3056.cif
正在转换mp-30952.cif
正在转换mp-30988.cif
正在转换mp-31002.cif
正在转换mp-31049.cif
正在转换mp-3104.cif
正在转换mp-31166.cif
正在转换mp-31451.cif
正在转换mp-31454.cif
正在转换mp-3159.cif
正在转换mp-315.cif
正在转换mp-3161.cif
正在转换mp-3167.cif
正在转换mp-3211.cif
正在转换mp-3236.cif
正在转换mp-32479.cif
正在转换mp-32497.cif
正在转换mp-32780.cif
正在转换mp-3332.cif
正在转换mp-341.cif
正在转换mp-3432.cif
正在转换mp-3481.cif
正在转换mp-3486.cif
正在转换mp-3525.cif
正在转换mp-3532.cif
正在转换mp-3551.cif
正在转换mp-3556.cif
正在转换mp-3595.cif
正在转换mp-3613.cif
正在转换mp-361.cif
正在转换mp-3637.cif
正在转换mp-3642.cif
正在转换mp-3664.cif
正在转换mp-3668.cif
正在转换mp-3718.cif
正在转换mp-3731.cif
正在转换mp-3748.cif
正在转换mp-375.cif
正在转换mp-3762.cif
正在转换mp-3772.cif
正在转换mp-3785.cif
正在转换mp-3821.cif
正在转换mp-3834.cif
正在转换mp-3839.cif
正在转换mp-3915.cif
正在转换mp-3931.cif
正在转换mp-3970.cif
正在转换mp-3982.cif
正在转换mp-3992.cif
正在转换mp-4009.cif
正在转换mp-4024.cif
正在转换mp-4025.cif
正在转换mp-4026.cif
正在转换mp-4030.cif
正在转换mp-4043.cif
正在转换mp-4081.cif
正在转换mp-4123.cif
正在转换mp-4124.cif
正在转换mp-4126.cif
正在转换mp-4175.cif
正在转换mp-4182.cif
正在转换mp-4226.cif
正在转换mp-422.cif
正在转换mp-4240.cif
正在转换mp-4280.cif
正在转换mp-4326.cif
正在转换mp-4359.cif
正在转换mp-4405.cif
正在转换mp-4452.cif
正在转换mp-4495.cif
正在转换mp-4519.cif
正在转换mp-4524.cif
正在转换mp-4666.cif
正在转换mp-467.cif
正在转换mp-471.cif
正在转换mp-4730.cif
正在转换mp-4763.cif
正在转换mp-4764.cif
正在转换mp-4809.cif
正在转换mp-4824.cif
正在转换mp-4886.cif
正在转换mp-4887.cif
正在转换mp-4899.cif
正在转换mp-4961.cif
正在转换mp-4964.cif
正在转换mp-4979.cif
正在转换mp-5020.cif
正在转换mp-5033.cif
正在转换mp-5072.cif
正在转换mp-5077.cif
正在转换mp-5175.cif
正在转换mp-5213.cif
正在转换mp-5238.cif
正在转换mp-5273.cif
正在转换mp-5342.cif
正在转换mp-5350.cif
正在转换mp-5380.cif
正在转换mp-5414.cif
正在转换mp-5459.cif
正在转换mp-5475.cif
正在转换mp-5513.cif
正在转换mp-5518.cif
正在转换mp-5598.cif
正在转换mp-5621.cif
正在转换mp-5634.cif
正在转换mp-5694.cif
正在转换mp-5782.cif
正在转换mp-5795.cif
正在转换mp-5808.cif
正在转换mp-5858.cif
正在转换mp-5860.cif
正在转换mp-5878.cif
正在转换mp-588.cif
正在转换mp-5928.cif
正在转换mp-5955.cif
正在转换mp-5962.cif
正在转换mp-5967.cif
正在转换mp-6408.cif
正在转换mp-643.cif
正在转换mp-648.cif
正在转换mp-684.cif
正在转换mp-6949.cif
正在转换mp-6951.cif
正在转换mp-6978.cif
正在转换mp-6980.cif
正在转换mp-7017.cif
正在转换mp-7041.cif
正在转换mp-704645.cif
正在转换mp-7046.cif
正在转换mp-7061.cif
正在转换mp-7067.cif
正在转换mp-706.cif
正在转换mp-7077.cif
正在转换mp-7089.cif
正在转换mp-7090.cif
正在转换mp-7113.cif
正在转换mp-7188.cif
正在转换mp-720.cif
正在转换mp-7375.cif
正在转换mp-7392.cif
正在转换mp-7394.cif
正在转换mp-7430.cif
正在转换mp-7435.cif
正在转换mp-7437.cif
正在转换mp-7439.cif
正在转换mp-7467.cif
正在转换mp-7472.cif
正在转换mp-7476.cif
正在转换mp-7477.cif
正在转换mp-7478.cif
正在转换mp-7480.cif
正在转换mp-7482.cif
正在转换mp-7523.cif
正在转换mp-7547.cif
正在转换mp-7562.cif
正在转换mp-7575.cif
正在转换mp-7604.cif
正在转换mp-7608.cif
正在转换mp-7639.cif
正在转换mp-7642.cif
正在转换mp-7643.cif
正在转换mp-7650.cif
正在转换mp-766.cif
正在转换mp-7684.cif
正在转换mp-7752.cif
正在转换mp-7768.cif
正在转换mp-7769.cif
正在转换mp-7773.cif
正在转换mp-7774.cif
正在转换mp-7801.cif
正在转换mp-7808.cif
正在转换mp-7824.cif
正在转换mp-7863.cif
正在转换mp-7906.cif
正在转换mp-7907.cif
正在转换mp-7908.cif
正在转换mp-7909.cif
正在转换mp-7910.cif
正在转换mp-7914.cif
正在转换mp-7921.cif
正在转换mp-7922.cif
正在转换mp-7928.cif
正在转换mp-7929.cif
正在转换mp-7936.cif
正在转换mp-7937.cif
正在转换mp-7938.cif
正在转换mp-7939.cif
正在转换mp-7950.cif
正在转换mp-7956.cif
正在转换mp-7958.cif
正在转换mp-7959.cif
正在转换mp-7973.cif
正在转换mp-7974.cif
正在转换mp-7979.cif
正在转换mp-7984.cif
正在转换mp-8013.cif
正在转换mp-8014.cif
正在转换mp-8016.cif
正在转换mp-8017.cif
正在转换mp-8041.cif
正在转换mp-8128.cif
正在转换mp-8152.cif
正在转换mp-8175.cif
正在转换mp-8176.cif
正在转换mp-8177.cif
正在转换mp-8181.cif
正在转换mp-8188.cif
正在转换mp-8192.cif
正在转换mp-8226.cif
正在转换mp-8255.cif
正在转换mp-8256.cif
正在转换mp-8276.cif
正在转换mp-8277.cif
正在转换mp-8278.cif
正在转换mp-8279.cif
正在转换mp-8280.cif
正在转换mp-8281.cif
正在转换mp-8289.cif
正在转换mp-8290.cif
正在转换mp-8291.cif
正在转换mp-8298.cif
正在转换mp-8299.cif
正在转换mp-8300.cif
正在转换mp-8311.cif
正在转换mp-8348.cif
正在转换mp-8393.cif
正在转换mp-8409.cif
正在转换mp-8411.cif
正在转换mp-8426.cif
正在转换mp-8429.cif
正在转换mp-8430.cif
正在转换mp-8446.cif
正在转换mp-8452.cif
正在转换mp-8470.cif
正在转换mp-8547.cif
正在转换mp-856.cif
正在转换mp-8579.cif
正在转换mp-8584.cif
正在转换mp-8621.cif
正在转换mp-8622.cif
正在转换mp-8623.cif
正在转换mp-8703.cif
正在转换mp-8751.cif
正在转换mp-8752.cif
正在转换mp-8753.cif
正在转换mp-8756.cif
正在转换mp-8789.cif
正在转换mp-8799.cif
正在转换mp-8818.cif
正在转换mp-8830.cif
正在转换mp-8962.cif
正在转换mp-8994.cif
正在转换mp-9006.cif
正在转换mp-9008.cif
正在转换mp-9010.cif
正在转换mp-9035.cif
正在转换mp-9036.cif
正在转换mp-9076.cif
正在转换mp-9124.cif
正在转换mp-9146.cif
正在转换mp-9158.cif
正在转换mp-9166.cif
正在转换mp-9195.cif
正在转换mp-9198.cif
正在转换mp-9200.cif
正在转换mp-9250.cif
正在转换mp-9254.cif
正在转换mp-9263.cif
正在转换mp-9273.cif
正在转换mp-9274.cif
正在转换mp-9295.cif
正在转换mp-9306.cif
正在转换mp-9307.cif
正在转换mp-9321.cif
正在转换mp-9362.cif
正在转换mp-9363.cif
正在转换mp-9364.cif
正在转换mp-9365.cif
正在转换mp-9366.cif
正在转换mp-9367.cif
正在转换mp-9368.cif
正在转换mp-9370.cif
正在转换mp-9382.cif
正在转换mp-9383.cif
正在转换mp-9385.cif
正在转换mp-9437.cif
正在转换mp-947.cif
正在转换mp-9488.cif
正在转换mp-9517.cif
正在转换mp-9518.cif
正在转换mp-9562.cif
正在转换mp-9564.cif
正在转换mp-9565.cif
正在转换mp-9566.cif
正在转换mp-9567.cif
正在转换mp-9569.cif
正在转换mp-9570.cif
正在转换mp-9571.cif
正在转换mp-9573.cif
正在转换mp-9581.cif
正在转换mp-9582.cif
正在转换mp-9583.cif
正在转换mp-9631.cif
正在转换mp-9687.cif
正在转换mp-971.cif
正在转换mp-9731.cif
正在转换mp-9732.cif
正在转换mp-9774.cif
正在转换mp-9775.cif
正在转换mp-9778.cif
正在转换mp-9799.cif
正在转换mp-9821.cif
正在转换mp-9845.cif
正在转换mp-9846.cif
正在转换mp-9872.cif
正在转换mp-9881.cif
正在转换mp-9899.cif
正在转换mp-9912.cif
正在转换mp-9915.cif
正在转换mp-9919.cif
正在转换mp-9920.cif
正在转换mp-10532.cif
正在转换mp-10998.cif
正在转换mp-11595.cif
正在转换mp-12264.cif
正在转换mp-1270.cif
正在转换mp-13292.cif
正在转换mp-1443.cif
正在转换mp-1788.cif
正在转换mp-17891.cif
正在转换mp-1840.cif
正在转换mp-1858.cif
正在转换mp-1875.cif
正在转换mp-1999.cif
正在转换mp-20091.cif
正在转换mp-2160.cif
正在转换mp-2184.cif
正在转换mp-22072.cif
正在转换mp-22101.cif
正在转换mp-22399.cif
正在转换mp-2245.cif
正在转换mp-2272.cif
正在转换mp-22871.cif
正在转换mp-22874.cif
正在转换mp-2309.cif
正在转换mp-23282.cif
正在转换mp-23332.cif
正在转换mp-23397.cif
正在转换mp-23498.cif
正在转换mp-2412.cif
正在转换mp-2565.cif
正在转换mp-27502.cif
正在转换mp-27553.cif
正在转换mp-2782.cif
正在转换mp-28070.cif
正在转换mp-28164.cif
正在转换mp-28177.cif
正在转换mp-28189.cif
正在转换mp-28222.cif
正在转换mp-28230.cif
正在转换mp-28232.cif
正在转换mp-28241.cif
正在转换mp-28247.cif
正在转换mp-28253.cif
正在转换mp-28261.cif
正在转换mp-28264.cif
正在转换mp-28268.cif
正在转换mp-28270.cif
正在转换mp-28304.cif
正在转换mp-28313.cif
正在转换mp-28319.cif
正在转换mp-28323.cif
正在转换mp-28324.cif
正在转换mp-28328.cif
正在转换mp-28329.cif
正在转换mp-28345.cif
正在转换mp-28347.cif
正在转换mp-28355.cif
正在转换mp-28360.cif
正在转换mp-28361.cif
正在转换mp-28364.cif
正在转换mp-28365.cif
正在转换mp-28368.cif
正在转换mp-28369.cif
正在转换mp-28371.cif
正在转换mp-28374.cif
正在转换mp-28375.cif
正在转换mp-28383.cif
正在转换mp-28395.cif
正在转换mp-28400.cif
正在转换mp-28419.cif
正在转换mp-28420.cif
正在转换mp-28423.cif
正在转换mp-28431.cif
正在转换mp-28447.cif
正在转换mp-28460.cif
正在转换mp-28485.cif
正在转换mp-28487.cif
正在转换mp-28488.cif
正在转换mp-28490.cif
正在转换mp-28505.cif
正在转换mp-28508.cif
正在转换mp-28513.cif
正在转换mp-28514.cif
正在转换mp-28517.cif
正在转换mp-28518.cif
正在转换mp-28520.cif
正在转换mp-28529.cif
正在转换mp-28534.cif
正在转换mp-28538.cif
正在转换mp-28545.cif
正在转换mp-28550.cif
正在转换mp-28557.cif
正在转换mp-28558.cif
正在转换mp-28564.cif
正在转换mp-28567.cif
正在转换mp-28568.cif
正在转换mp-28577.cif
正在转换mp-28580.cif
正在转换mp-28586.cif
正在转换mp-28592.cif
正在转换mp-28595.cif
正在转换mp-28603.cif
正在转换mp-28611.cif
正在转换mp-28630.cif
正在转换mp-28653.cif
正在转换mp-28657.cif
正在转换mp-28658.cif
正在转换mp-28670.cif
正在转换mp-28671.cif
正在转换mp-28688.cif
正在转换mp-28695.cif
正在转换mp-28711.cif
正在转换mp-28712.cif
正在转换mp-28716.cif
正在转换mp-28721.cif
正在转换mp-28734.cif
正在转换mp-28741.cif
正在转换mp-28760.cif
正在转换mp-28766.cif
正在转换mp-28768.cif
正在转换mp-28772.cif
正在转换mp-28782.cif

正在转换mp-28793.cif
正在转换mp-28796.cif
正在转换mp-28802.cif
正在转换mp-28810.cif
正在转换mp-28815.cif
正在转换mp-28818.cif
正在转换mp-28828.cif
正在转换mp-2883.cif
正在转换mp-28875.cif
正在转换mp-28879.cif
正在转换mp-28899.cif
正在转换mp-28900.cif
正在转换mp-28916.cif
正在转换mp-28921.cif
正在转换mp-28931.cif
正在转换mp-28952.cif
正在转换mp-28955.cif
正在转换mp-28962.cif
正在转换mp-28967.cif
正在转换mp-28969.cif
正在转换mp-28978.cif
正在转换mp-28982.cif
正在转换mp-28983.cif
正在转换mp-28989.cif
正在转换mp-29008.cif
正在转换mp-29011.cif
正在转换mp-29012.cif
正在转换mp-29033.cif
正在转换mp-29048.cif
正在转换mp-29083.cif
正在转换mp-29110.cif
正在转换mp-29127.cif
正在转换mp-29236.cif
正在转换mp-29244.cif
正在转换mp-29245.cif
正在转换mp-29260.cif
正在转换mp-29274.cif
正在转换mp-29297.cif
正在转换mp-29308.cif
正在转换mp-29362.cif
正在转换mp-29364.cif
正在转换mp-29365.cif
正在转换mp-29396.cif
正在转换mp-29415.cif
正在转换mp-29419.cif
正在转换mp-29431.cif
正在转换mp-29455.cif
正在转换mp-29456.cif
正在转换mp-29463.cif
正在转换mp-29469.cif
正在转换mp-29474.cif
正在转换mp-29520.cif
正在转换mp-29537.cif
正在转换mp-29582.cif
正在转换mp-29590.cif
正在转换mp-29591.cif
正在转换mp-29628.cif
正在转换mp-29638.cif
正在转换mp-29641.cif
正在转换mp-29644.cif
正在转换mp-29696.cif
正在转换mp-29711.cif
正在转换mp-29763.cif
正在转换mp-29794.cif
正在转换mp-29826.cif
正在转换mp-29829.cif
正在转换mp-29848.cif
正在转换mp-29857.cif
正在转换mp-29862.cif
正在转换mp-29880.cif
正在转换mp-29898.cif
正在转换mp-29946.cif
正在转换mp-29959.cif
正在转换mp-29976.cif
正在转换mp-29993.cif
正在转换mp-30032.cif
正在转换mp-30100.cif
正在转换mp-30126.cif
正在转换mp-30156.cif
正在转换mp-30159.cif
正在转换mp-30160.cif
正在转换mp-30161.cif
正在转换mp-30237.cif
正在转换mp-30241.cif
正在转换mp-30242.cif
正在转换mp-30243.cif
正在转换mp-30245.cif
正在转换mp-30284.cif
正在转换mp-30293.cif
正在转换mp-30294.cif
正在转换mp-30298.cif
正在转换mp-30456.cif
正在转换mp-30478.cif
正在转换mp-30532.cif
正在转换mp-30533.cif
正在转换mp-30675.cif
正在转换mp-30828.cif
正在转换mp-30841.cif
正在转换mp-30914.cif
正在转换mp-30996.cif
正在转换mp-31076.cif
正在转换mp-31077.cif
正在转换mp-31081.cif
正在转换mp-31179.cif
正在转换mp-3118.cif
正在转换mp-31213.cif
正在转换mp-31268.cif
正在转换mp-31303.cif
正在转换mp-31367.cif
正在转换mp-3138.cif
正在转换mp-31468.cif
正在转换mp-31519.cif
正在转换mp-31521.cif
正在转换mp-31540.cif
正在转换mp-31584.cif
正在转换mp-31624.cif
正在转换mp-31626.cif
正在转换mp-31645.cif
正在转换mp-31649.cif
正在转换mp-3172.cif
正在转换mp-3196.cif
正在转换mp-3200.cif
正在转换mp-3245.cif
正在转换mp-32493.cif
正在转换mp-3252.cif
正在转换mp-3317.cif
正在转换mp-3334.cif
正在转换mp-3335.cif
正在转换mp-33690.cif
正在转换mp-3370.cif
正在转换mp-3378.cif
正在转换mp-34036.cif
正在转换mp-34126.cif
正在转换mp-34185.cif
正在转换mp-34292.cif
正在转换mp-3435.cif
正在转换mp-34375.cif
正在转换mp-34680.cif
正在转换mp-34730.cif
正在转换mp-34842.cif
正在转换mp-3488.cif
正在转换mp-35031.cif
正在转换mp-3503.cif
正在转换mp-35162.cif
正在转换mp-35185.cif
正在转换mp-35236.cif
正在转换mp-35248.cif
正在转换mp-35264.cif
正在转换mp-35267.cif
正在转换mp-35269.cif
正在转换mp-35281.cif
正在转换mp-35320.cif
正在转换mp-3540.cif
正在转换mp-35482.cif
正在转换mp-35493.cif
正在转换mp-35512.cif
正在转换mp-35527.cif
正在转换mp-35530.cif
正在转换mp-35589.cif
正在转换mp-35596.cif
正在转换mp-35630.cif
正在转换mp-3563.cif
正在转换mp-35647.cif
正在转换mp-35746.cif
正在转换mp-3575.cif
正在转换mp-35785.cif
正在转换mp-35787.cif
正在转换mp-35876.cif
正在转换mp-35899.cif
正在转换mp-35906.cif
正在转换mp-35909.cif
正在转换mp-35929.cif
正在转换mp-3592.cif
正在转换mp-3593.cif
正在转换mp-36007.cif
正在转换mp-36028.cif
正在转换mp-36100.cif
正在转换mp-3611.cif
正在转换mp-3612.cif
正在转换mp-36223.cif
正在转换mp-36252.cif
正在转换mp-3626.cif
正在转换mp-36305.cif
正在转换mp-36447.cif
正在转换mp-36592.cif
正在转换mp-36765.cif
正在转换mp-36821.cif
正在转换mp-36864.cif
正在转换mp-36866.cif
正在转换mp-3688.cif
正在转换mp-36912.cif
正在转换mp-36915.cif
正在转换mp-36988.cif
正在转换mp-37030.cif
正在转换mp-37108.cif
正在转换mp-37199.cif
正在转换mp-37233.cif
正在转换mp-37263.cif
正在转换mp-3727.cif
正在转换mp-37315.cif
正在转换mp-37399.cif
正在转换mp-37405.cif
正在转换mp-37430.cif
正在转换mp-37436.cif
正在转换mp-37449.cif
正在转换mp-37498.cif
正在转换mp-37520.cif
正在转换mp-37614.cif
正在转换mp-37657.cif
正在转换mp-37859.cif
正在转换mp-3788.cif
正在转换mp-37923.cif
正在转换mp-37947.cif
正在转换mp-3795.cif
正在转换mp-37995.cif
正在转换mp-38008.cif
正在转换mp-3838.cif
正在转换mp-3870.cif
正在转换mp-3872.cif
正在转换mp-3884.cif
正在转换mp-3889.cif
正在转换mp-3917.cif
正在转换mp-3919.cif
正在转换mp-3943.cif
正在转换mp-3952.cif
正在转换mp-3956.cif
正在转换mp-3963.cif
正在转换mp-3967.cif
正在转换mp-401.cif
正在转换mp-4038.cif
正在转换mp-4048.cif
正在转换mp-4049.cif
正在转换mp-4056.cif
正在转换mp-4068.cif
正在转换mp-4092.cif
正在转换mp-4103.cif
正在转换mp-4112.cif
正在转换mp-4138.cif
正在转换mp-4155.cif
正在转换mp-4163.cif
正在转换mp-4180.cif
正在转换mp-4192.cif
正在转换mp-4199.cif
正在转换mp-4252.cif
正在转换mp-4274.cif
正在转换mp-4287.cif
正在转换mp-4309.cif
正在转换mp-4321.cif
正在转换mp-4351.cif
正在转换mp-4356.cif
正在转换mp-4394.cif
正在转换mp-4408.cif
正在转换mp-4426.cif
正在转换mp-4471.cif
正在转换mp-4535.cif
正在转换mp-4574.cif
正在转换mp-4582.cif
正在转换mp-4598.cif
正在转换mp-4602.cif
正在转换mp-4626.cif
正在转换mp-4673.cif
正在转换mp-4682.cif
正在转换mp-4699.cif
正在转换mp-4710.cif
正在转换mp-4748.cif
正在转换mp-4789.cif
正在转换mp-4812.cif
正在转换mp-4818.cif
正在转换mp-4819.cif
正在转换mp-4867.cif
正在转换mp-4876.cif
正在转换mp-4906.cif
正在转换mp-4937.cif
正在转换mp-4959.cif
正在转换mp-4991.cif
正在转换mp-4995.cif
正在转换mp-5001.cif
正在转换mp-5004.cif
正在转换mp-5052.cif
正在转换mp-5055.cif
正在转换mp-5114.cif
正在转换mp-5126.cif
正在转换mp-5168.cif
正在转换mp-5193.cif
正在转换mp-5279.cif
正在转换mp-6693.cif
正在转换mp-6721.cif
正在转换mp-6730.cif
正在转换mp-6853.cif
正在转换mp-7198.cif
正在转换mp-7220.cif
正在转换mp-7238.cif
正在转换mp-7290.cif
正在转换mp-7368.cif
正在转换mp-8075.cif
正在转换mp-8076.cif
正在转换mp-8084.cif
正在转换mp-8130.cif
正在转换mp-8258.cif
正在转换mp-8324.cif
正在转换mp-8351.cif
正在转换mp-8389.cif
正在转换mp-8436.cif
正在转换mp-8439.cif
正在转换mp-8491.cif
正在转换mp-8496.cif
正在转换mp-8507.cif
正在转换mp-8516.cif
正在转换mp-8568.cif
正在转换mp-8586.cif
正在转换mp-8590.cif
正在转换mp-8652.cif
正在转换mp-8673.cif
正在转换mp-8686.cif
正在转换mp-8709.cif
正在转换mp-9095.cif
正在转换mvc-1853.cif
正在转换mvc-2192.cif
正在转换mvc-2362.cif
正在转换mvc-2377.cif
正在转换mvc-2633.cif
正在转换mvc-3226.cif
正在转换mvc-3343.cif
正在转换mvc-3358.cif
正在转换mvc-3378.cif
正在转换mvc-3385.cif
正在转换mvc-3391.cif
正在转换mvc-3437.cif
正在转换mvc-3489.cif
正在转换mvc-3512.cif
正在转换mvc-3604.cif
正在转换mvc-3613.cif
正在转换mvc-3616.cif
正在转换mvc-3619.cif
正在转换mvc-3620.cif
正在转换mvc-3621.cif
正在转换mvc-3668.cif
正在转换mvc-3670.cif
正在转换mvc-3737.cif
正在转换mvc-3750.cif
正在转换mvc-3783.cif
正在转换mvc-3826.cif
正在转换mvc-3850.cif
正在转换mvc-3874.cif
正在转换mvc-3953.cif
正在转换mvc-3956.cif
正在转换mvc-3959.cif
正在转换mvc-3961.cif
正在转换mvc-3962.cif
正在转换mvc-3964.cif
正在转换mvc-3968.cif
正在转换mvc-3970.cif
正在转换mvc-3973.cif
正在转换mvc-3975.cif
正在转换mvc-3976.cif
正在转换mvc-3984.cif
正在转换mvc-3987.cif
正在转换mvc-3995.cif
正在转换mvc-3998.cif
正在转换mvc-4002.cif
正在转换mvc-4008.cif
正在转换mvc-4105.cif
正在转换mvc-4117.cif
正在转换mvc-4141.cif
正在转换mvc-4146.cif
正在转换mvc-4159.cif
正在转换mvc-4195.cif
正在转换mvc-4204.cif
正在转换mvc-4255.cif
正在转换mvc-4871.cif
正在转换mvc-4881.cif
正在转换mvc-4910.cif
正在转换mvc-4926.cif
正在转换mvc-4931.cif
正在转换mvc-4967.cif
正在转换mvc-4985.cif
正在转换mvc-5003.cif
正在转换mvc-5007.cif
正在转换mvc-5021.cif
正在转换mvc-5037.cif
正在转换mvc-5039.cif
正在转换mvc-5112.cif
正在转换mvc-5116.cif
正在转换mvc-5117.cif
正在转换mvc-5128.cif
正在转换mvc-5130.cif
正在转换mvc-5134.cif
正在转换mvc-5136.cif
正在转换mvc-5137.cif
正在转换mvc-5138.cif
正在转换mvc-5346.cif
正在转换mvc-6799.cif
正在转换mvc-776.cif
正在转换mvc-8003.cif
正在转换mvc-8027.cif
正在转换mvc-8041.cif
正在转换mvc-8049.cif
正在转换mvc-8058.cif
正在转换mvc-8059.cif
正在转换mvc-8063.cif
正在转换mvc-8085.cif
正在转换mvc-8104.cif
正在转换mvc-8132.cif
正在转换mvc-8151.cif
正在转换mvc-8312.cif
正在转换mvc-8314.cif
正在转换mvc-8347.cif
正在转换mvc-8423.cif
正在转换mvc-8582.cif
正在转换mvc-8589.cif
正在转换mvc-8631.cif
正在转换mvc-8643.cif
正在转换mvc-8677.cif
正在转换mp-10080.cif
正在转换mp-10096.cif
正在转换mp-10097.cif
正在转换mp-10233.cif
正在转换mp-10234.cif
正在转换mp-10299.cif
正在转换mp-10340.cif
正在转换mp-10349.cif
正在转换mp-10368.cif
正在转换mp-10392.cif
正在转换mp-10461.cif
正在转换mp-11110.cif
正在转换mp-11112.cif
正在转换mp-11613.cif
正在转换mp-11772.cif
正在转换mp-11773.cif
正在转换mp-12022.cif
正在转换mp-12171.cif
正在转换mp-12180.cif
正在转换mp-12221.cif
正在转换mp-12245.cif
正在转换mp-12271.cif
正在转换mp-12362.cif
正在转换mp-12384.cif
正在转换mp-12441.cif
正在转换mp-12485.cif
正在转换mp-12881.cif
正在转换mp-13003.cif
正在转换mp-13042.cif
正在转换mp-13096.cif
正在转换mp-13194.cif
正在转换mp-13195.cif
正在转换mp-13196.cif
正在转换mp-13252.cif
正在转换mp-13282.cif
正在转换mp-13283.cif
正在转换mp-13654.cif
正在转换mp-13664.cif
正在转换mp-13740.cif
正在转换mp-13801.cif
正在转换mp-13803.cif
正在转换mp-13840.cif
正在转换mp-13843.cif
正在转换mp-13863.cif
正在转换mp-13866.cif
正在转换mp-13923.cif
正在转换mp-13981.cif
正在转换mp-14026.cif
正在转换mp-14058.cif
正在转换mp-14145.cif
正在转换mp-14150.cif
正在转换mp-14161.cif
正在转换mp-14243.cif
正在转换mp-14252.cif
正在转换mp-14324.cif
正在转换mp-14345.cif
正在转换mp-14368.cif
正在转换mp-14374.cif
正在转换mp-14415.cif
正在转换mp-14416.cif
正在转换mp-14420.cif
正在转换mp-14430.cif
正在转换mp-14482.cif
正在转换mp-14495.cif
正在转换mp-14531.cif
正在转换mp-14532.cif
正在转换mp-14550.cif
正在转换mp-14551.cif
正在转换mp-14587.cif
正在转换mp-14643.cif
正在转换mp-14780.cif
正在转换mp-14782.cif
正在转换mp-14794.cif
正在转换mp-14871.cif
正在转换mp-14921.cif
正在转换mp-14963.cif
正在转换mp-14964.cif
正在转换mp-15011.cif
正在转换mp-15012.cif
正在转换mp-15013.cif
正在转换mp-15081.cif
正在转换mp-15113.cif
正在转换mp-15170.cif
正在转换mp-15179.cif
正在转换mp-15236.cif
正在转换mp-15248.cif
正在转换mp-15257.cif
正在转换mp-15312.cif
正在转换mp-15514.cif
正在转换mp-15572.cif
正在转换mp-15833.cif
正在转换mp-16097.cif
正在转换mp-16136.cif
正在转换mp-16137.cif
正在转换mp-16152.cif
正在转换mp-16280.cif
正在转换mp-16281.cif
正在转换mp-16293.cif
正在转换mp-16296.cif
正在转换mp-16380.cif
正在转换mp-16432.cif
正在转换mp-17114.cif
正在转换mp-17119.cif
正在转换mp-17123.cif
正在转换mp-17149.cif
正在转换mp-17389.cif
正在转换mp-17486.cif
正在转换mp-17538.cif
正在转换mp-17577.cif
正在转换mp-17599.cif
正在转换mp-17678.cif
正在转换mp-17698.cif
正在转换mp-17747.cif
正在转换mp-17827.cif
正在转换mp-17829.cif
正在转换mp-17875.cif
正在转换mp-17892.cif
正在转换mp-17912.cif
正在转换mp-17972.cif
正在转换mp-18008.cif
正在转换mp-8708.cif
正在转换mp-8725.cif
正在转换mp-8727.cif
正在转换mp-8794.cif
正在转换mp-8869.cif
正在转换mp-9007.cif
正在转换mp-9028.cif
正在转换mp-9071.cif
正在转换mp-9092.cif
正在转换mp-9186.cif
正在转换mp-9203.cif
正在转换mp-9323.cif
正在转换mp-9338.cif
正在转换mp-9392.cif

正在转换mp-9410.cif
正在转换mp-9478.cif
正在转换mp-9535.cif
正在转换mp-9607.cif
正在转换mp-9628.cif
正在转换mp-9698.cif
正在转换mp-9722.cif
正在转换mp-9745.cif
正在转换mp-9747.cif
正在转换mp-9751.cif
正在转换mp-9765.cif
正在转换mp-9784.cif
正在转换mp-9788.cif
正在转换mp-9789.cif
正在转换mp-9870.cif
正在转换mvc-11484.cif
正在转换mvc-11633.cif
正在转换mvc-11639.cif
正在转换mvc-11649.cif
正在转换mvc-11968.cif
正在转换mvc-11972.cif
正在转换mvc-11991.cif
正在转换mvc-12607.cif
正在转换mvc-12655.cif
正在转换mvc-12722.cif
正在转换mvc-12789.cif
正在转换mvc-12973.cif
正在转换mvc-13126.cif
正在转换mvc-13143.cif
正在转换mvc-13298.cif
正在转换mvc-13319.cif
正在转换mvc-13423.cif
正在转换mvc-13424.cif
正在转换mvc-13441.cif
正在转换mvc-13511.cif
正在转换mvc-13644.cif
正在转换mvc-13647.cif
正在转换mvc-13703.cif
正在转换mvc-13994.cif
正在转换mvc-14045.cif
正在转换mvc-14154.cif
正在转换mvc-14155.cif
正在转换mvc-14364.cif
正在转换mvc-14409.cif
正在转换mvc-14565.cif
正在转换mvc-14606.cif
正在转换mvc-14777.cif
正在转换mvc-14992.cif
正在转换mvc-15049.cif
正在转换mvc-15067.cif
正在转换mvc-15084.cif
正在转换mvc-15346.cif
正在转换mvc-15354.cif
正在转换mvc-15492.cif
正在转换mvc-15602.cif
正在转换mvc-15619.cif
正在转换mvc-15649.cif
正在转换mvc-15853.cif
正在转换mvc-15868.cif
正在转换mvc-15871.cif
正在转换mvc-15901.cif
正在转换mvc-15905.cif
正在转换mvc-15909.cif
正在转换mvc-15985.cif
正在转换mvc-15987.cif
正在转换mvc-16093.cif
正在转换mvc-16098.cif
正在转换mvc-16173.cif
正在转换mvc-16179.cif
正在转换mvc-16303.cif
正在转换mvc-16397.cif
正在转换mvc-16451.cif
正在转换mvc-16454.cif
正在转换mvc-16466.cif
正在转换mvc-16508.cif
正在转换mvc-16516.cif
正在转换mvc-16575.cif
正在转换mvc-8680.cif
正在转换mvc-9356.cif
正在转换mvc-9650.cif
正在转换mvc-9651.cif
正在转换mvc-9661.cif
正在转换mvc-9927.cif
正在转换mvc-9931.cif
正在转换mp-18309.cif
正在转换mp-18310.cif
正在转换mp-18332.cif
正在转换mp-18361.cif
正在转换mp-18433.cif
正在转换mp-18458.cif
正在转换mp-18480.cif
正在转换mp-18481.cif
正在转换mp-18498.cif
正在转换mp-18501.cif
正在转换mp-18502.cif
正在转换mp-18510.cif
正在转换mp-18575.cif
正在转换mp-18577.cif
正在转换mp-18585.cif
正在转换mp-18594.cif
正在转换mp-18596.cif
正在转换mp-18629.cif
正在转换mp-18633.cif
正在转换mp-18635.cif
正在转换mp-18642.cif
正在转换mp-18651.cif
正在转换mp-18652.cif
正在转换mp-18685.cif
正在转换mp-18705.cif
正在转换mp-18727.cif
正在转换mp-18735.cif
正在转换mp-18786.cif
正在转换mp-18795.cif
正在转换mp-18797.cif
正在转换mp-18806.cif
正在转换mp-18815.cif
正在转换mp-18831.cif
正在转换mp-18843.cif
正在转换mp-18853.cif
正在转换mp-18869.cif
正在转换mp-18883.cif
正在转换mp-18890.cif
正在转换mp-18894.cif
正在转换mp-18911.cif
正在转换mp-18915.cif
正在转换mp-18925.cif
正在转换mp-18929.cif
正在转换mp-18936.cif
正在转换mp-18990.cif
正在转换mp-19034.cif
正在转换mp-19036.cif
正在转换mp-19077.cif
正在转换mp-19136.cif
正在转换mp-19139.cif
正在转换mp-19145.cif
正在转换mp-19153.cif
正在转换mp-19166.cif
正在转换mp-19185.cif
正在转换mp-19224.cif
正在转换mp-19256.cif
正在转换mp-19259.cif
正在转换mp-19321.cif
正在转换mp-19343.cif
正在转换mp-19349.cif
正在转换mp-19397.cif
正在转换mp-19582.cif
正在转换mp-19592.cif
正在转换mp-19604.cif
正在转换mp-19608.cif
正在转换mp-19611.cif
正在转换mp-19612.cif
正在转换mp-19619.cif
正在转换mp-19640.cif
正在转换mp-19688.cif
正在转换mp-19707.cif
正在转换mp-19784.cif
正在转换mp-19965.cif
正在转换mp-20011.cif
正在转换mp-20078.cif
正在转换mp-20079.cif
正在转换mp-20191.cif
正在转换mp-20199.cif
正在转换mp-20254.cif
正在转换mp-20376.cif
正在转换mp-20450.cif
正在转换mp-20489.cif
正在转换mp-20507.cif
正在转换mp-20778.cif
正在转换mp-20845.cif
正在转换mp-20863.cif
正在转换mp-20940.cif
正在转换mp-21266.cif
正在转换mp-21872.cif
正在转换mp-22070.cif
正在转换mp-22212.cif
正在转换mp-22569.cif
正在转换mp-22634.cif
正在转换mp-22930.cif
正在转换mp-22989.cif
正在转换mp-22994.cif
正在转换mp-23063.cif
正在转换mp-23093.cif
正在转换mp-23096.cif
正在转换mp-23100.cif
正在转换mp-23125.cif
正在转换mp-23131.cif
正在转换mp-23170.cif
正在转换mp-23181.cif
正在转换mp-23195.cif
正在转换mp-23316.cif
正在转换mp-23339.cif
正在转换mp-23341.cif
正在转换mp-23347.cif
正在转换mp-23348.cif
正在转换mp-23390.cif
正在转换mp-23391.cif
正在转换mp-23392.cif
正在转换mp-23413.cif
正在转换mp-23419.cif
正在转换mp-23434.cif
正在转换mp-23503.cif
正在转换mp-23522.cif
正在转换mp-23691.cif
正在转换mp-23705.cif
正在转换mp-23706.cif
正在转换mp-23730.cif
正在转换mp-23774.cif
正在转换mp-23827.cif
正在转换mp-23828.cif
正在转换mp-23843.cif
正在转换mp-23914.cif
正在转换mp-23925.cif
正在转换mp-23963.cif
正在转换mp-24034.cif
正在转换mp-24044.cif
正在转换mp-24052.cif
正在转换mp-24165.cif
正在转换mp-24240.cif
正在转换mp-24266.cif
正在转换mp-24328.cif
正在转换mp-24342.cif
正在转换mp-24375.cif
正在转换mp-24411.cif
正在转换mp-24412.cif
正在转换mp-24461.cif
正在转换mp-24559.cif
正在转换mp-24847.cif
正在转换mp-24873.cif
正在转换mp-24993.cif
正在转换mp-24996.cif
正在转换mp-25002.cif
正在转换mp-25019.cif
正在转换mp-25029.cif
正在转换mp-25034.cif
正在转换mp-25044.cif
正在转换mp-25048.cif
正在转换mp-25050.cif
正在转换mp-25088.cif
正在转换mp-25095.cif
正在转换mp-25103.cif
正在转换mp-25127.cif
正在转换mp-25131.cif
正在转换mp-25139.cif
正在转换mp-25144.cif
正在转换mp-25400.cif
正在转换mp-25474.cif
正在转换mp-27377.cif
正在转换mp-27400.cif
正在转换mp-27581.cif
正在转换mp-28218.cif
正在转换mp-28219.cif
正在转换mp-28224.cif
正在转换mp-28263.cif
正在转换mp-28315.cif
正在转换mp-28800.cif
正在转换mp-28809.cif
正在转换mp-28830.cif
正在转换mp-28855.cif
正在转换mp-28859.cif
正在转换mp-28883.cif
正在转换mp-28911.cif
正在转换mp-28950.cif
正在转换mp-29080.cif
正在转换mp-29136.cif
正在转换mp-29168.cif
正在转换mp-29169.cif
正在转换mp-29170.cif
正在转换mp-29359.cif
正在转换mp-29370.cif
正在转换mp-29376.cif
正在转换mp-29379.cif
正在转换mp-29391.cif
正在转换mp-29397.cif
正在转换mp-29405.cif
正在转换mp-29413.cif
正在转换mp-29417.cif
正在转换mp-29468.cif
正在转换mp-29476.cif
正在转换mp-29524.cif
正在转换mp-29596.cif
正在转换mp-29598.cif
正在转换mp-29636.cif
正在转换mp-29637.cif
正在转换mp-29692.cif
正在转换mp-29693.cif
正在转换mp-29699.cif
正在转换mp-29745.cif
正在转换mp-29775.cif
正在转换mp-29792.cif
正在转换mp-29816.cif
正在转换mp-29835.cif
正在转换mp-29850.cif
正在转换mp-29890.cif
正在转换mp-29892.cif
正在转换mp-29909.cif
正在转换mp-29910.cif
正在转换mp-29920.cif
正在转换mp-29927.cif
正在转换mp-29975.cif
正在转换mp-29977.cif
正在转换mp-30005.cif
正在转换mp-30067.cif
正在转换mp-30091.cif
正在转换mp-30102.cif
正在转换mp-30167.cif
正在转换mp-30231.cif
正在转换mp-30239.cif
正在转换mp-30252.cif
正在转换mp-30253.cif
正在转换mp-30303.cif
正在转换mp-30304.cif
正在转换mp-30311.cif
正在转换mp-30520.cif
正在转换mp-30569.cif
正在转换mp-30900.cif
正在转换mp-30904.cif
正在转换mp-30949.cif
正在转换mp-30959.cif
正在转换mp-30975.cif
正在转换mp-31096.cif
正在转换mp-31110.cif
正在转换mp-31112.cif
正在转换mp-31117.cif
正在转换mp-31118.cif
正在转换mp-31119.cif
正在转换mp-31120.cif
正在转换mp-31121.cif
正在转换mp-31132.cif
正在转换mp-31150.cif
正在转换mp-31250.cif
正在转换mp-31263.cif
正在转换mp-31276.cif
正在转换mp-31548.cif
正在转换mp-31578.cif
正在转换mp-31703.cif
正在转换mp-31750.cif
正在转换mp-31798.cif
正在转换mp-31837.cif
正在转换mp-31859.cif
正在转换mp-31918.cif
正在转换mp-31922.cif
正在转换mp-31960.cif
正在转换mp-32013.cif
正在转换mp-32407.cif
正在转换mp-32408.cif
正在转换mp-32411.cif
正在转换mp-32456.cif
正在转换mp-32472.cif
正在转换mp-32482.cif
正在转换mp-32760.cif
正在转换mp-33444.cif
正在转换mp-33508.cif
正在转换mp-33753.cif
正在转换mp-33803.cif
正在转换mp-33948.cif
正在转换mp-34322.cif
正在转换mp-35078.cif
正在转换mp-35249.cif
正在转换mp-36053.cif
正在转换mp-36779.cif
正在转换mp-37207.cif
正在转换mp-37747.cif
正在转换mp-38418.cif
正在转换mp-39215.cif
正在转换mp-39387.cif
正在转换mp-39511.cif
正在转换mp-39712.cif
正在转换mp-39888.cif
正在转换mp-40186.cif
正在转换mp-10013.cif
正在转换mp-10044.cif
正在转换mp-1005.cif
正在转换mp-10063.cif
正在转换mp-10064.cif
正在转换mp-10074.cif
正在转换mp-10086.cif
正在转换mp-1008.cif
正在转换mp-10102.cif
正在转换mp-10159.cif
正在转换mp-10161.cif
正在转换mp-10164.cif
正在转换mp-10165.cif
正在转换mp-10166.cif
正在转换mp-10175.cif
正在转换mp-10219.cif
正在转换mp-10255.cif
正在转换mp-10281.cif
正在转换mp-10293.cif
正在转换mp-1037.cif
正在转换mp-10381.cif
正在转换mp-10421.cif
正在转换mp-10422.cif
正在转换mp-10423.cif
正在转换mp-10426.cif
正在转换mp-10437.cif
正在转换mp-1043.cif
正在转换mp-10497.cif
正在转换mp-10525.cif
正在转换mp-10531.cif
正在转换mp-10615.cif
正在转换mp-10618.cif
正在转换mp-10627.cif
正在转换mp-10653.cif
正在转换mp-1066.cif
正在转换mp-10671.cif
正在转换mp-1067.cif
正在转换mp-10680.cif
正在转换mp-1070.cif
正在转换mp-10716.cif
正在转换mp-10729.cif
正在转换mp-10732.cif
正在转换mp-10733.cif
正在转换mp-10759.cif
正在转换mp-1075.cif
正在转换mp-10760.cif
正在转换mp-10763.cif
正在转换mp-10777.cif
正在转换mp-10910.cif
正在转换mp-10918.cif
正在转换mp-10931.cif
正在转换mp-10932.cif
正在转换mp-10952.cif
正在转换mp-10955.cif
正在转换mp-10967.cif
正在转换mp-1096.cif
正在转换mp-10971.cif
正在转换mp-10981.cif
正在转换mp-1100.cif
正在转换mp-11019.cif
正在转换mp-11023.cif
正在转换mp-11104.cif
正在转换mp-11108.cif
正在转换mp-11147.cif
正在转换mp-11191.cif
正在转换mp-11254.cif
正在转换mp-11255.cif
正在转换mp-11257.cif
正在转换mp-11258.cif
正在转换mp-11259.cif
正在转换mp-11267.cif
正在转换mp-11306.cif
正在转换mp-11361.cif
正在转换mp-11390.cif
正在转换mp-1140.cif
正在转换mp-11484.cif
正在转换mp-11491.cif
正在转换mp-11496.cif
正在转换mp-1150.cif
正在转换mp-11520.cif
正在转换mp-11548.cif
正在转换mp-11552.cif
正在转换mp-11571.cif
正在转换mp-11601.cif
正在转换mp-11675.cif
正在转换mp-11687.cif
正在转换mp-11705.cif
正在转换mp-1175.cif
正在转换mp-11806.cif
正在转换mp-11807.cif
正在转换mp-11819.cif
正在转换mp-11830.cif
正在转换mp-11882.cif
正在转换mp-1199.cif
正在转换mp-12007.cif
正在转换mp-12008.cif
正在转换mp-12015.cif
正在转换mp-12065.cif
正在转换mp-12072.cif
正在转换mp-1209.cif
正在转换mp-12110.cif
正在转换mp-12128.cif
正在转换mp-12129.cif
正在转换mp-1222.cif
正在转换mp-12277.cif
正在转换mp-12283.cif
正在转换mp-1232.cif
正在转换mp-12335.cif
正在转换mp-1241.cif
正在转换mp-12433.cif
正在转换mp-1245.cif
正在转换mp-12602.cif
正在转换mp-12603.cif
正在转换mp-12621.cif
正在转换mp-12668.cif
正在转换mp-12669.cif
正在转换mp-12670.cif
正在转换mp-12671.cif
正在转换mp-12673.cif
正在转换mp-12725.cif
正在转换mp-12779.cif
正在转换mp-12894.cif
正在转换mp-12992.cif
正在转换mp-13032.cif
正在转换mp-13033.cif
正在转换mp-13060.cif
正在转换mp-13061.cif
正在转换mp-13063.cif

正在转换mp-13064.cif
正在转换mp-13065.cif
正在转换mp-13066.cif
正在转换mp-13067.cif
正在转换mp-13068.cif
正在转换mp-13099.cif
正在转换mp-13108.cif
正在转换mp-13119.cif
正在转换mp-13147.cif
正在转换mp-13151.cif
正在转换mp-13181.cif
正在转换mp-13274.cif
正在转换mp-13305.cif
正在转换mp-1330.cif
正在转换mp-13314.cif
正在转换mp-13650.cif
正在转换mp-1378.cif
正在转换mp-1379.cif
正在转换mp-13903.cif
正在转换mp-13907.cif
正在转换mp-13915.cif
正在转换mp-1394.cif
正在转换mp-13983.cif
正在转换mp-14000.cif
正在转换mp-14099.cif
正在转换mp-14105.cif
正在转换mp-1410.cif
正在转换mp-14222.cif
正在转换mp-1438.cif
正在转换mp-14769.cif
正在转换mp-14791.cif
正在转换mp-1492.cif
正在转换mp-1505.cif
正在转换mp-1542.cif
正在转换mp-15622.cif
正在转换mp-1565.cif
正在转换mp-15668.cif
正在转换mp-1567.cif
正在转换mp-15687.cif
正在转换mp-15701.cif
正在转换mp-15702.cif
正在转换mp-15704.cif
正在转换mp-1575.cif
正在转换mp-15780.cif
正在转换mp-1595.cif
正在转换mp-15988.cif
正在转换mp-1599.cif
正在转换mp-16258.cif
正在转换mp-16313.cif
正在转换mp-16314.cif
正在转换mp-16315.cif
正在转换mp-16318.cif
正在转换mp-16319.cif
正在转换mp-16321.cif
正在转换mp-16327.cif
正在转换mp-16329.cif
正在转换mp-16343.cif
正在转换mp-1635.cif
正在转换mp-16364.cif
正在转换mp-16372.cif
正在转换mp-16376.cif
正在转换mp-1639.cif
正在转换mp-16613.cif
正在转换mp-16735.cif
正在转换mp-1678.cif
正在转换mp-1681.cif
正在转换mp-1699.cif
正在转换mp-1700.cif
正在转换mp-1735.cif
正在转换mp-1836.cif
正在转换mp-18717.cif
正在转换mp-18745.cif
正在转换mp-18746.cif
正在转换mp-18747.cif
正在转换mp-18752.cif
正在转换mp-18756.cif
正在转换mp-18767.cif
正在转换mp-1876.cif
正在转换mp-18770.cif
正在转换mp-18782.cif
正在转换mp-18828.cif
正在转换mp-18839.cif
正在转换mp-1883.cif
正在转换mp-18841.cif
正在转换mp-18854.cif
正在转换mp-18895.cif
正在转换mp-188.cif
正在转换mp-18912.cif
正在转换mp-1892.cif
正在转换mp-18943.cif
正在转换mp-18966.cif
正在转换mp-18978.cif
正在转换mp-19006.cif
正在转换mp-19009.cif
正在转换mp-19027.cif
正在转换mp-19053.cif
正在转换mp-19062.cif
正在转换mp-19101.cif
正在转换mp-19118.cif
正在转换mp-19128.cif
正在转换mp-19164.cif
正在转换mp-19181.cif
正在转换mp-19183.cif
正在转换mp-19184.cif
正在转换mp-19191.cif
正在转换mp-19253.cif
正在转换mp-19257.cif
正在转换mp-19275.cif
正在转换mp-19279.cif
正在转换mp-19311.cif
正在转换mp-19312.cif
正在转换mp-19317.cif
正在转换mp-19325.cif
正在转换mp-19338.cif
正在转换mp-1933.cif
正在转换mp-19353.cif
正在转换mp-19390.cif
正在转换mp-19412.cif
正在转换mp-19419.cif
正在转换mp-1950.cif
正在转换mp-1954.cif
正在转换mp-19726.cif
正在转换mp-19735.cif
正在转换mp-19787.cif
正在转换mp-19791.cif
正在转换mp-19804.cif
正在转换mp-19805.cif
正在转换mp-19807.cif
正在转换mp-19811.cif
正在转换mp-19820.cif
正在转换mp-19847.cif
正在转换mp-19857.cif
正在转换mp-1986.cif
正在转换mp-19880.cif
正在转换mp-19886.cif
正在转换mp-19909.cif
正在转换mp-19928.cif
正在转换mp-19953.cif
正在转换mp-19963.cif
正在转换mp-19971.cif
正在转换mp-20020.cif
正在转换mp-20027.cif
正在转换mp-20042.cif
正在转换mp-20064.cif
正在转换mp-20110.cif
正在转换mp-2011.cif
正在转换mp-20162.cif
正在转换mp-20173.cif
正在转换mp-20174.cif
正在转换mp-2018.cif
正在转换mp-20207.cif
正在转换mp-20233.cif
正在转换mp-20291.cif
正在转换mp-20329.cif
正在转换mp-20333.cif
正在转换mp-20337.cif
正在转换mp-20338.cif
正在转换mp-20343.cif
正在转换mp-20354.cif
正在转换mp-20485.cif
正在转换mp-20510.cif
正在转换mp-20554.cif
正在转换mp-2060.cif
正在转换mp-20639.cif
正在转换mp-2063.cif
正在转换mp-2065.cif
正在转换mp-20679.cif
正在转换mp-20684.cif
正在转换mp-20711.cif
正在转换mp-20717.cif
正在转换mp-20725.cif
正在转换mp-20759.cif
正在转换mp-2077.cif
正在转换mp-20793.cif
正在转换mp-20808.cif
正在转换mp-20859.cif
正在转换mp-20866.cif
正在转换mp-20878.cif
正在转换mp-20879.cif
正在转换mp-20893.cif
正在转换mp-20928.cif
正在转换mp-20930.cif
正在转换mp-20933.cif
正在转换mp-20984.cif
正在转换mp-20997.cif
正在转换mp-21043.cif
正在转换mp-21050.cif
正在转换mp-21080.cif
正在转换mp-21122.cif
正在转换mp-21128.cif
正在转换mp-21132.cif
正在转换mp-21133.cif
正在转换mp-21139.cif
正在转换mp-21143.cif
正在转换mp-2117.cif
正在转换mp-21237.cif
正在转换mp-21255.cif
正在转换mp-21293.cif
正在转换mp-21339.cif
正在转换mp-21405.cif
正在转换mp-21410.cif
正在转换mp-21425.cif
正在转换mp-21492.cif
正在转换mp-2150.cif
正在转换mp-2175.cif
正在转换mp-21862.cif
正在转换mp-21863.cif
正在转换mp-21875.cif
正在转换mp-21888.cif
正在转换mp-21889.cif
正在转换mp-21899.cif
正在转换mp-22009.cif
正在转换mp-22026.cif
正在转换mp-22027.cif
正在转换mp-22064.cif
正在转换mp-22087.cif
正在转换mp-22142.cif
正在转换mp-22145.cif
正在转换mp-2217.cif
正在转换mp-22232.cif
正在转换mp-22253.cif
正在转换mp-22256.cif
正在转换mp-22263.cif
正在转换mp-2228.cif
正在转换mp-2229.cif
正在转换mp-22318.cif
正在转换mp-22351.cif
正在转换mp-22374.cif
正在转换mp-22384.cif
正在转换mp-22386.cif
正在转换mp-223.cif
正在转换mp-22464.cif
正在转换mp-2247.cif
正在转换mp-22535.cif
正在转换mp-22539.cif
正在转换mp-22566.cif
正在转换mp-22604.cif
正在转换mp-22689.cif
正在转换mp-22736.cif
正在转换mp-22761.cif
正在转换mp-22784.cif
正在转换mp-22786.cif
正在转换mp-2278.cif
正在转换mp-22791.cif
正在转换mp-227.cif
正在转换mp-22811.cif
正在转换mp-22851.cif
正在转换mp-22857.cif
正在转换mp-22858.cif
正在转换mp-22875.cif
正在转换mp-22894.cif
正在转换mp-22895.cif
正在转换mp-22899.cif
正在转换mp-22901.cif
正在转换mp-22919.cif
正在转换mp-2293.cif
正在转换mp-22967.cif
正在转换mp-22972.cif
正在转换mp-22979.cif
正在转换mp-22980.cif
正在转换mp-22995.cif
正在转换mp-229.cif
正在转换mp-23074.cif
正在转换mp-23080.cif
正在转换mp-23097.cif
正在转换mp-23167.cif
正在转换mp-23173.cif
正在转换mp-23197.cif
正在转换mp-23222.cif
正在转换mp-23227.cif
正在转换mp-23231.cif
正在转换mp-23244.cif
正在转换mp-23289.cif
正在转换mp-23293.cif
正在转换mp-23299.cif
正在转换mp-23301.cif
正在转换mp-23302.cif
正在转换mp-23303.cif
正在转换mp-23383.cif
正在转换mp-233.cif
正在转换mp-2341.cif
正在转换mp-2348.cif
正在转换mp-23499.cif
正在转换mp-23505.cif
正在转换mp-23729.cif
正在转换mp-23795.cif
正在转换mp-23803.cif
正在转换mp-23891.cif
正在转换mp-23940.cif
正在转换mp-23949.cif
正在转换mp-24093.cif
正在转换mp-24150.cif
正在转换mp-2437.cif
正在转换mp-24419.cif
正在转换mp-24428.cif
正在转换mp-24517.cif
正在转换mp-2462.cif
正在转换mp-2469.cif
正在转换mp-2482.cif
正在转换mp-24840.cif
正在转换mp-24851.cif
正在转换mp-24852.cif
正在转换mp-24853.cif
正在转换mp-24864.cif
正在转换mp-24865.cif
正在转换mp-24866.cif
正在转换mp-2488.cif
正在转换mp-24913.cif
正在转换mp-24914.cif
正在转换mp-24915.cif
正在转换mp-24927.cif
正在转换mp-24931.cif
正在转换mp-24942.cif
正在转换mp-24946.cif
正在转换mp-24947.cif
正在转换mp-24964.cif
正在转换mp-24992.cif
正在转换mp-25010.cif
正在转换mp-25011.cif
正在转换mp-25016.cif
正在转换mp-25097.cif
正在转换mp-25119.cif
正在转换mp-25121.cif
正在转换mp-25137.cif
正在转换mp-25138.cif
正在转换mp-2522.cif
正在转换mp-2536.cif
正在转换mp-25476.cif
正在转换mp-25503.cif
正在转换mp-25542.cif
正在转换mp-25546.cif
正在转换mp-25547.cif
正在转换mp-25571.cif
正在转换mp-25587.cif
正在转换mp-25593.cif
正在转换mp-25596.cif
正在转换mp-25615.cif
正在转换mp-25647.cif
正在转换mp-2564.cif
正在转换mp-2600.cif
正在转换mp-2615.cif
正在转换mp-2630.cif
正在转换mp-26477.cif
正在转换mp-267.cif
正在转换mp-2686.cif
正在转换mp-2705.cif
正在转换mp-27243.cif
正在转换mp-27263.cif
正在转换mp-2726.cif
正在转换mp-2728.cif
正在转换mp-27410.cif
正在转换mp-27418.cif
正在转换mp-27484.cif
正在转换mp-27496.cif
正在转换mp-27536.cif
正在转换mp-2756.cif
正在转换mp-27635.cif
正在转换mp-27636.cif
正在转换mp-2763.cif
正在转换mp-27658.cif
正在转换mp-27677.cif
正在转换mp-27705.cif
正在转换mp-27726.cif
正在转换mp-27729.cif
正在转换mp-27801.cif
正在转换mp-27923.cif
正在转换mp-27962.cif
正在转换mp-27986.cif
正在转换mp-279.cif
正在转换mp-2801.cif
正在转换mp-28051.cif
正在转换mp-2805.cif
正在转换mp-2808.cif
正在转换mp-28250.cif
正在转换mp-282.cif
正在转换mp-2838.cif
正在转换mp-2853.cif
正在转换mp-28593.cif
正在转换mp-28722.cif
正在转换mp-28786.cif
正在转换mp-28895.cif
正在转换mp-29009.cif
正在转换mp-29151.cif
正在转换mp-29153.cif
正在转换mp-2918.cif
正在转换mp-29196.cif
正在转换mp-29352.cif
正在转换mp-29624.cif
正在转换mp-29653.cif
正在转换mp-29678.cif
正在转换mp-29733.cif
正在转换mp-29738.cif
正在转换mp-29761.cif
正在转换mp-29771.cif
正在转换mp-29798.cif
正在转换mp-29806.cif
正在转换mp-29868.cif
正在转换mp-29873.cif
正在转换mp-29929.cif
正在转换mp-29930.cif
正在转换mp-2998.cif
正在转换mp-30004.cif
正在转换mp-30009.cif
正在转换mp-30040.cif
正在转换mp-30042.cif
正在转换mp-30055.cif
正在转换mp-30080.cif
正在转换mp-30148.cif
正在转换mp-30200.cif
正在转换mp-30244.cif
正在转换mp-30251.cif
正在转换mp-30356.cif
正在转换mp-30390.cif
正在转换mp-30418.cif
正在转换mp-30428.cif
正在转换mp-30452.cif
正在转换mp-30457.cif
正在转换mp-30459.cif
正在转换mp-30460.cif
正在转换mp-30485.cif
正在转换mp-30494.cif
正在转换mp-30521.cif
正在转换mp-30580.cif
正在转换mp-30600.cif
正在转换mp-3062.cif
正在转换mp-30725.cif
正在转换mp-30739.cif
正在转换mp-30765.cif
正在转换mp-30766.cif
正在转换mp-3078.cif
正在转换mp-30836.cif
正在转换mp-30847.cif
正在转换mp-30867.cif
正在转换mp-30921.cif
正在转换mp-30922.cif
正在转换mp-30965.cif
正在转换mp-3098.cif
正在转换mp-30999.cif
正在转换mp-31056.cif
正在转换mp-31058.cif
正在转换mp-31138.cif
正在转换mp-31145.cif
正在转换mp-31148.cif
正在转换mp-31173.cif
正在转换mp-31175.cif
正在转换mp-31186.cif
正在转换mp-31187.cif
正在转换mp-31256.cif
正在转换mp-31326.cif
正在转换mp-31330.cif
正在转换mp-31347.cif
正在转换mp-31368.cif
正在转换mp-3136.cif
正在转换mp-31402.cif
正在转换mp-31455.cif
正在转换mp-31507.cif
正在转换mp-31623.cif
正在转换mp-322.cif
正在转换mp-32403.cif
正在转换mp-32554.cif
正在转换mp-32641.cif
正在转换mp-32669.cif
正在转换mp-32684.cif
正在转换mp-32750.cif
正在转换mp-32829.cif
正在转换mp-32868.cif
正在转换mp-32880.cif
正在转换mp-32884.cif
正在转换mp-32994.cif
正在转换mp-33018.cif
正在转换mp-33029.cif
正在转换mp-3307.cif
正在转换mp-33107.cif
正在转换mp-33154.cif
正在转换mp-33218.cif
正在转换mp-33234.cif
正在转换mp-3323.cif
正在转换mp-33322.cif
正在转换mp-33333.cif
正在转换mp-33363.cif
正在转换mp-33365.cif
正在转换mp-33526.cif
正在转换mp-33588.cif
正在转换mp-33618.cif
正在转换mp-33667.cif
正在转换mp-33683.cif
正在转换mp-33723.cif
正在转换mp-3376.cif
正在转换mp-33797.cif
正在转换mp-33857.cif
正在转换mp-33880.cif
正在转换mp-33882.cif
正在转换mp-33916.cif
正在转换mp-33985.cif
正在转换mp-33997.cif
正在转换mp-34023.cif
正在转换mp-34121.cif
正在转换mp-34127.cif
正在转换mp-34134.cif
正在转换mp-34169.cif
正在转换mp-34232.cif
正在转换mp-34289.cif
正在转换mp-34293.cif
正在转换mp-34337.cif
正在转换mp-34380.cif
正在转换mp-34381.cif
正在转换mp-34418.cif
正在转换mp-34460.cif
正在转换mp-34465.cif
正在转换mp-34467.cif
正在转换mp-34477.cif
正在转换mp-34489.cif
正在转换mp-344.cif
正在转换mp-34663.cif
正在转换mp-34688.cif
正在转换mp-34735.cif
正在转换mp-34857.cif
正在转换mp-34903.cif
正在转换mp-34932.cif
正在转换mp-34976.cif
正在转换mp-34982.cif
正在转换mp-35015.cif
正在转换mp-35152.cif
正在转换mp-35171.cif
正在转换mp-35205.cif
正在转换mp-35216.cif
正在转换mp-35220.cif
正在转换mp-35308.cif
正在转换mp-35311.cif
正在转换mp-3535.cif
正在转换mp-35388.cif
正在转换mp-35404.cif
正在转换mp-35417.cif
正在转换mp-35539.cif
正在转换mp-358.cif
正在转换mp-362.cif
正在转换mp-370.cif
正在转换mp-3716.cif
正在转换mp-3740.cif
正在转换mp-380.cif
正在转换mp-3813.cif
正在转换mp-3829.cif
正在转换mp-4008.cif
正在转换mp-4152.cif
正在转换mp-4170.cif
正在转换mp-4174.cif
正在转换mp-4255.cif
正在转换mp-4266.cif
正在转换mp-4342.cif
正在转换mp-4366.cif
正在转换mp-4510.cif
正在转换mp-4541.cif
正在转换mp-4551.cif
正在转换mp-4559.cif
正在转换mp-4573.cif
正在转换mp-4636.cif
正在转换mp-470.cif
正在转换mp-4756.cif
正在转换mp-4817.cif
正在转换mp-4823.cif
正在转换mp-4840.cif
正在转换mp-486.cif

正在转换mp-4897.cif
正在转换mp-493.cif
正在转换mp-494.cif
正在转换mp-4953.cif
正在转换mp-5075.cif
正在转换mp-5090.cif
正在转换mp-516.cif
正在转换mp-5190.cif
正在转换mp-5197.cif
正在转换mp-5229.cif
正在转换mp-5246.cif
正在转换mp-5256.cif
正在转换mp-5425.cif
正在转换mp-5495.cif
正在转换mp-5538.cif
正在转换mp-5606.cif
正在转换mp-5615.cif
正在转换mp-5640.cif
正在转换mp-5663.cif
正在转换mp-5693.cif
正在转换mp-573.cif
正在转换mp-5749.cif
正在转换mp-5760.cif
正在转换mp-5770.cif
正在转换mp-5777.cif
正在转换mp-5811.cif
正在转换mp-5827.cif
正在转换mp-5841.cif
正在转换mp-5862.cif
正在转换mp-5893.cif
正在转换mp-5920.cif
正在转换mp-6070.cif
正在转换mp-608.cif
正在转换mp-6166.cif
正在转换mp-634.cif
正在转换mp-6624.cif
正在转换mp-6625.cif
正在转换mp-6781.cif
正在转换mp-6933.cif
正在转换mp-6948.cif
正在转换mp-6972.cif
正在转换mp-7015.cif
正在转换mp-7140.cif
正在转换mp-7173.cif
正在转换mp-7204.cif
正在转换mp-7223.cif
正在转换mp-7240.cif
正在转换mp-7243.cif
正在转换mp-7329.cif
正在转换mp-7433.cif
正在转换mp-7434.cif
正在转换mp-7502.cif
正在转换mp-7548.cif
正在转换mp-7582.cif
正在转换mp-7583.cif
正在转换mp-7589.cif
正在转换mp-7598.cif
正在转换mp-760.cif
正在转换mp-7700.cif
正在转换mp-7724.cif
正在转换mp-7725.cif
正在转换mp-7739.cif
正在转换mp-7748.cif
正在转换mp-776.cif
正在转换mp-7770.cif
正在转换mp-7771.cif
正在转换mp-7795.cif
正在转换mp-7811.cif
正在转换mp-7826.cif
正在转换mp-7885.cif
正在转换mp-7891.cif
正在转换mp-7895.cif
正在转换mp-7897.cif
正在转换mp-7905.cif
正在转换mp-7940.cif
正在转换mp-7955.cif
正在转换mp-7983.cif
正在转换mp-8002.cif
正在转换mp-8037.cif
正在转换mp-8062.cif
正在转换mp-8134.cif
正在转换mp-8136.cif
正在转换mp-8145.cif
正在转换mp-8179.cif
正在转换mp-8196.cif
正在转换mp-8211.cif
正在转换mp-8231.cif
正在转换mp-8234.cif
正在转换mp-830.cif
正在转换mp-8360.cif
正在转换mp-8373.cif
正在转换mp-8406.cif
正在转换mp-8453.cif
正在转换mp-8612.cif
正在转换mp-8682.cif
正在转换mp-870.cif
正在转换mp-871.cif
正在转换mp-8781.cif
正在转换mp-883.cif
正在转换mp-8860.cif
正在转换mp-8880.cif
正在转换mp-8881.cif
正在转换mp-8882.cif
正在转换mp-8883.cif
正在转换mp-8884.cif
正在转换mp-8927.cif
正在转换mp-8938.cif
正在转换mp-8939.cif
正在转换mp-8976.cif
正在转换mp-9056.cif
正在转换mp-9122.cif
正在转换mp-917.cif
正在转换mp-9194.cif
正在转换mp-9211.cif
正在转换mp-9252.cif
正在转换mp-9257.cif
正在转换mp-9281.cif
正在转换mp-9304.cif
正在转换mp-9379.cif
正在转换mp-9453.cif
正在转换mp-945.cif
正在转换mp-9490.cif
正在转换mp-9514.cif
正在转换mp-9568.cif
正在转换mp-9574.cif
正在转换mp-9575.cif
正在转换mp-9579.cif
正在转换mp-9580.cif
正在转换mp-9630.cif
正在转换mp-964.cif
正在转换mp-9791.cif
正在转换mp-9897.cif
正在转换mp-9898.cif
正在转换mp-9911.cif
正在转换mp-9922.cif
正在转换mp-9925.cif
正在转换mp-9942.cif
正在转换mp-998.cif
正在转换mvc-10016.cif
正在转换mvc-10883.cif
正在转换mvc-10923.cif
正在转换mvc-11024.cif
正在转换mvc-11052.cif
正在转换mvc-11084.cif
正在转换mvc-11142.cif
正在转换mvc-11162.cif
正在转换mvc-11229.cif
正在转换mvc-11231.cif
正在转换mvc-11360.cif
正在转换mvc-11549.cif
正在转换mvc-11552.cif
正在转换mvc-11554.cif
正在转换mvc-11555.cif
正在转换mvc-11697.cif
正在转换mvc-11699.cif
正在转换mvc-11730.cif
正在转换mvc-11768.cif
正在转换mvc-12771.cif
正在转换mvc-13408.cif
正在转换mvc-13410.cif
正在转换mvc-13426.cif
正在转换mvc-13436.cif
正在转换mvc-13442.cif
正在转换mvc-13445.cif
正在转换mvc-13450.cif
正在转换mvc-13455.cif
正在转换mvc-13461.cif
正在转换mvc-13470.cif
正在转换mvc-13472.cif
正在转换mvc-13487.cif
正在转换mvc-13497.cif
正在转换mvc-13651.cif
正在转换mvc-13729.cif
正在转换mvc-13730.cif
正在转换mvc-13744.cif
正在转换mvc-13747.cif
正在转换mvc-13757.cif
正在转换mvc-13772.cif
正在转换mvc-13850.cif
正在转换mvc-13886.cif
正在转换mvc-13902.cif
正在转换mvc-13905.cif
正在转换mvc-13931.cif
正在转换mvc-13934.cif
正在转换mvc-13940.cif
正在转换mvc-13983.cif
正在转换mvc-14178.cif
正在转换mvc-14574.cif
正在转换mvc-14626.cif
正在转换mvc-14665.cif
正在转换mvc-14678.cif
正在转换mvc-14685.cif
正在转换mvc-14713.cif
正在转换mvc-14714.cif
正在转换mvc-14721.cif
正在转换mvc-14725.cif
正在转换mvc-14726.cif
正在转换mvc-14755.cif
正在转换mvc-14834.cif
正在转换mvc-14934.cif
正在转换mvc-14940.cif
正在转换mvc-15141.cif
正在转换mvc-15230.cif
正在转换mvc-15351.cif
正在转换mvc-15365.cif
正在转换mvc-15370.cif
正在转换mvc-15374.cif
正在转换mvc-15452.cif
正在转换mvc-15458.cif
正在转换mvc-15521.cif
正在转换mvc-15523.cif
正在转换mvc-15532.cif
正在转换mvc-15578.cif
正在转换mvc-15684.cif
正在转换mvc-15694.cif
正在转换mvc-15700.cif
正在转换mvc-15702.cif
正在转换mvc-15728.cif
正在转换mvc-15736.cif
正在转换mvc-15815.cif
正在转换mvc-15833.cif
正在转换mvc-15834.cif
正在转换mvc-15842.cif
正在转换mvc-15847.cif
正在转换mvc-15848.cif
正在转换mvc-15850.cif
正在转换mvc-15858.cif
正在转换mvc-15860.cif
正在转换mvc-15861.cif
正在转换mvc-15885.cif
正在转换mvc-15886.cif
正在转换mvc-15887.cif
正在转换mvc-15907.cif
正在转换mvc-15946.cif
正在转换mvc-16068.cif
正在转换mvc-16070.cif
正在转换mvc-16073.cif
正在转换mvc-16081.cif
正在转换mvc-16085.cif
正在转换mvc-16090.cif
正在转换mvc-16091.cif
正在转换mvc-16207.cif
正在转换mvc-16214.cif
正在转换mvc-16231.cif
正在转换mvc-16803.cif
正在转换mvc-16808.cif
正在转换mvc-16811.cif
正在转换mvc-2078.cif
正在转换mvc-2137.cif
正在转换mvc-3478.cif
正在转换mvc-5676.cif
正在转换mvc-5756.cif
正在转换mvc-6936.cif
正在转换mvc-7049.cif
正在转换mvc-7051.cif
正在转换mvc-7052.cif
正在转换mvc-7054.cif
正在转换mvc-7194.cif
正在转换mvc-7198.cif
正在转换mvc-7203.cif
正在转换mvc-7206.cif
正在转换mvc-7210.cif
正在转换mvc-7216.cif
正在转换mvc-7227.cif
正在转换mvc-7237.cif
正在转换mvc-7240.cif
正在转换mvc-7244.cif
正在转换mvc-7248.cif
正在转换mvc-7260.cif
正在转换mvc-7665.cif
正在转换mvc-7666.cif
正在转换mvc-7667.cif
正在转换mvc-7668.cif
正在转换mvc-7669.cif
正在转换mvc-7673.cif
正在转换mvc-7674.cif
正在转换mvc-7676.cif
正在转换mvc-7677.cif
正在转换mvc-7682.cif
正在转换mvc-7687.cif
正在转换mvc-7688.cif
正在转换mvc-7692.cif
正在转换mp-10069.cif
正在转换mp-10089.cif
正在转换mp-10091.cif
正在转换mp-10094.cif
正在转换mp-10155.cif
正在转换mp-10191.cif
正在转换mp-10223.cif
正在转换mp-10246.cif
正在转换mp-10251.cif
正在转换mp-10289.cif
正在转换mp-10333.cif
正在转换mp-10334.cif
正在转换mp-10336.cif
正在转换mp-10337.cif
正在转换mp-10342.cif
正在转换mp-10390.cif
正在转换mp-10413.cif
正在转换mp-10419.cif
正在转换mp-10434.cif
正在转换mp-10444.cif
正在转换mp-10477.cif
正在转换mp-1047.cif
正在转换mp-10481.cif
正在转换mp-10486.cif
正在转换mp-10487.cif
正在转换mp-10495.cif
正在转换mp-1049.cif
正在转换mp-10509.cif
正在转换mp-10518.cif
正在转换mp-10519.cif
正在转换mp-1051.cif
正在转换mp-10520.cif
正在转换mp-10523.cif
正在转换mp-10533.cif
正在转换mp-10543.cif
正在转换mp-10547.cif
正在转换mp-10555.cif
正在转换mp-10556.cif
正在转换mp-10560.cif
正在转换mp-10620.cif
正在转换mp-10621.cif
正在转换mp-10662.cif
正在转换mp-10731.cif
正在转换mp-10762.cif
正在转换mp-10776.cif
正在转换mp-10796.cif
正在转换mp-10802.cif
正在转换mp-10811.cif
正在转换mp-10821.cif
正在转换mp-10834.cif
正在转换mp-10835.cif
正在转换mp-10876.cif
正在转换mp-10928.cif
正在转换mp-10950.cif
正在转换mp-10953.cif
正在转换mp-10960.cif
正在转换mp-10963.cif
正在转换mp-10966.cif
正在转换mp-10970.cif
正在转换mp-10985.cif
正在转换mp-10990.cif
正在转换mp-11009.cif
正在转换mp-11010.cif
正在转换mp-11011.cif
正在转换mp-11014.cif
正在转换mp-11016.cif
正在转换mp-11018.cif
正在转换mp-1106.cif
正在转换mp-1109.cif
正在转换mp-11132.cif
正在转换mp-11151.cif
正在转换mp-11166.cif
正在转换mp-11168.cif
正在转换mp-1125.cif
正在转换mp-1146.cif
正在转换mp-1147.cif
正在转换mp-11499.cif
正在转换mp-11551.cif
正在转换mp-11582.cif
正在转换mp-11583.cif
正在转换mp-11605.cif
正在转换mp-11606.cif
正在转换mp-11607.cif
正在转换mp-11634.cif
正在转换mp-11639.cif
正在转换mp-11641.cif
正在转换mp-11654.cif
正在转换mp-11674.cif
正在转换mp-1168.cif
正在转换mp-11691.cif
正在转换mp-11692.cif
正在转换mp-11706.cif
正在转换mp-1239.cif
正在转换mp-11713.cif
正在转换mp-11715.cif
正在转换mp-11736.cif
正在转换mp-11737.cif
正在转换mp-11738.cif
正在转换mp-11792.cif
正在转换mp-11793.cif
正在转换mp-11794.cif
正在转换mp-11820.cif
正在转换mp-11902.cif
正在转换mp-11918.cif
正在转换mp-11919.cif
正在转换mp-11923.cif
正在转换mp-11924.cif
正在转换mp-11925.cif
正在转换mp-12011.cif
正在转换mp-12012.cif
正在转换mp-12016.cif
正在转换mp-12023.cif
正在转换mp-12046.cif
正在转换mp-12047.cif
正在转换mp-12177.cif
正在转换mp-12178.cif
正在转换mp-12181.cif
正在转换mp-12263.cif
正在转换mp-12265.cif
正在转换mp-12266.cif
正在转换mp-12364.cif
正在转换mp-12365.cif
正在转换mp-12368.cif
正在转换mp-12385.cif
正在转换mp-12418.cif
正在转换mp-12422.cif
正在转换mp-12427.cif
正在转换mp-1243.cif
正在转换mp-12453.cif
正在转换mp-12454.cif
正在转换mp-12455.cif
正在转换mp-12457.cif
正在转换mp-12459.cif
正在转换mp-1247.cif
正在转换mp-12480.cif
正在转换mp-12535.cif
正在转换mp-12622.cif
正在转换mp-12623.cif
正在转换mp-12630.cif
正在转换mp-12637.cif
正在转换mp-12640.cif
正在转换mp-12641.cif
正在转换mp-12642.cif
正在转换mp-12644.cif
正在转换mp-12645.cif
正在转换mp-12647.cif
正在转换mp-1267.cif
正在转换mp-12729.cif
正在转换mp-12741.cif
正在转换mp-12807.cif
正在转换mp-12814.cif
正在转换mp-12838.cif
正在转换mp-12843.cif
正在转换mp-1287.cif
正在转换mp-1288.cif
正在转换mp-12912.cif
正在转换mp-12927.cif
正在转换mp-12929.cif
正在转换mp-12944.cif
正在转换mp-12955.cif
正在转换mp-12958.cif
正在转换mp-12978.cif
正在转换mp-12984.cif
正在转换mp-13000.cif
正在转换mp-13001.cif
正在转换mp-13109.cif
正在转换mp-13133.cif
正在转换mp-13148.cif
正在转换mp-13163.cif
正在转换mp-13189.cif
正在转换mp-1321.cif
正在转换mp-13326.cif
正在转换mp-13327.cif
正在转换mp-13334.cif
正在转换mp-13336.cif
正在转换mp-13351.cif
正在转换mp-13356.cif
正在转换mp-1340.cif
正在转换mp-13445.cif
正在转换mp-1345.cif
正在转换mp-1346.cif
正在转换mp-1347.cif
正在转换mp-13530.cif
正在转换mp-13538.cif
正在转换mp-13541.cif
正在转换mp-13568.cif
正在转换mp-13589.cif
正在转换mp-13641.cif
正在转换mp-13658.cif
正在转换mp-13666.cif
正在转换mp-13743.cif
正在转换mp-13744.cif
正在转换mp-13797.cif
正在转换mp-13798.cif
正在转换mp-13811.cif
正在转换mp-13820.cif
正在转换mp-13829.cif
正在转换mp-13836.cif
正在转换mp-13852.cif
正在转换mp-13853.cif
正在转换mp-13868.cif
正在转换mp-13900.cif
正在转换mp-13922.cif
正在转换mp-13961.cif
正在转换mp-1397.cif
正在转换mp-13982.cif
正在转换mp-13985.cif
正在转换mp-13986.cif
正在转换mp-13995.cif
正在转换mp-14036.cif
正在转换mp-14037.cif
正在转换mp-14038.cif
正在转换mp-14039.cif
正在转换mp-14083.cif
正在转换mp-14100.cif
正在转换mp-14142.cif
正在转换mp-14152.cif
正在转换mp-14175.cif
正在转换mp-14241.cif
正在转换mp-14242.cif
正在转换mp-14249.cif
正在转换mp-14254.cif
正在转换mp-14285.cif
正在转换mp-14288.cif
正在转换mp-14289.cif
正在转换mp-14292.cif
正在转换mp-14304.cif
正在转换mp-14305.cif
正在转换mp-14307.cif
正在转换mp-14333.cif
正在转换mp-14334.cif
正在转换mp-14363.cif
正在转换mp-14395.cif
正在转换mp-14398.cif
正在转换mp-1439.cif
正在转换mp-14433.cif
正在转换mp-14434.cif
正在转换mp-14435.cif
正在转换mp-14444.cif
正在转换mp-14447.cif
正在转换mp-14448.cif
正在转换mp-14476.cif
正在转换mp-14588.cif
正在转换mp-14620.cif

正在转换mp-14623.cif
正在转换mp-14624.cif
正在转换mp-14628.cif
正在转换mp-14634.cif
正在转换mp-14635.cif
正在转换mp-14636.cif
正在转换mp-14651.cif
正在转换mp-14653.cif
正在转换mp-14659.cif
正在转换mp-14726.cif
正在转换mp-14787.cif
正在转换mp-14796.cif
正在转换mp-14797.cif
正在转换mp-14951.cif
正在转换mp-14969.cif
正在转换mp-15026.cif
正在转换mp-15074.cif
正在转换mp-15109.cif
正在转换mp-1513.cif
正在转换mp-15144.cif
正在转换mp-15147.cif
正在转换mp-15155.cif
正在转换mp-15214.cif
正在转换mp-15216.cif
正在转换mp-15217.cif
正在转换mp-15219.cif
正在转换mp-15220.cif
正在转换mp-15221.cif
正在转换mp-15222.cif
正在转换mp-15252.cif
正在转换mp-15339.cif
正在转换mp-15349.cif
正在转换mp-1536.cif
正在转换mp-15472.cif
正在转换mp-1554.cif
正在转换mp-15556.cif
正在转换mp-15567.cif
正在转换mp-15571.cif
正在转换mp-15573.cif
正在转换mp-15621.cif
正在转换mp-15642.cif
正在转换mp-15643.cif
正在转换mp-15649.cif
正在转换mp-15661.cif
正在转换mp-15733.cif
正在转换mp-15736.cif
正在转换mp-15743.cif
正在转换mp-15802.cif
正在转换mp-15803.cif
正在转换mp-15844.cif
正在转换mp-15845.cif
正在转换mp-15895.cif
正在转换mp-15896.cif
正在转换mp-15900.cif
正在转换mp-15939.cif
正在转换mp-15953.cif
正在转换mp-15954.cif
正在转换mp-15998.cif
正在转换mp-15999.cif
正在转换mp-16031.cif
正在转换mp-16053.cif
正在转换mp-16060.cif
正在转换mp-16096.cif
正在转换mp-16116.cif
正在转换mp-16124.cif
正在转换mp-16179.cif
正在转换mp-16180.cif
正在转换mp-16225.cif
正在转换mp-16252.cif
正在转换mp-16253.cif
正在转换mp-16264.cif
正在转换mp-16267.cif
正在转换mp-16272.cif
正在转换mp-16338.cif
正在转换mp-16363.cif
正在转换mp-16454.cif
正在转换mp-16455.cif
正在转换mp-16484.cif
正在转换mp-16684.cif
正在转换mp-16932.cif
正在转换mp-1694.cif
正在转换mp-1705.cif
正在转换mp-1707.cif
正在转换mp-17207.cif
正在转换mp-17228.cif
正在转换mp-1726.cif
正在转换mp-17336.cif
正在转换mp-1745.cif
正在转换mp-1771.cif
正在转换mp-17830.cif
正在转换mp-18006.cif
正在转换mp-1806.cif
正在转换mp-1819.cif
正在转换mp-181.cif
正在转换mp-18222.cif
正在转换mp-1848.cif
正在转换mp-18691.cif
正在转换mp-18718.cif
正在转换mp-18720.cif
正在转换mp-18721.cif
正在转换mp-18723.cif
正在转换mp-18726.cif
正在转换mp-18730.cif
正在转换mp-18732.cif
正在转换mp-18733.cif
正在转换mp-18734.cif
正在转换mp-18741.cif
正在转换mp-18749.cif
正在转换mp-18750.cif
正在转换mp-18751.cif
正在转换mp-18753.cif
正在转换mp-18754.cif
正在转换mp-18759.cif
正在转换mp-18761.cif
正在转换mp-18762.cif
正在转换mp-18764.cif
正在转换mp-18765.cif
正在转换mp-18766.cif
正在转换mp-18772.cif
正在转换mp-18775.cif
正在转换mp-18779.cif
正在转换mp-18781.cif
正在转换mp-18784.cif
正在转换mp-18788.cif
正在转换mp-18798.cif
正在转换mp-18800.cif
正在转换mp-18803.cif
正在转换mp-18805.cif
正在转换mp-18807.cif
正在转换mp-18809.cif
正在转换mp-18812.cif
正在转换mp-18814.cif
正在转换mp-18816.cif
正在转换mp-18817.cif
正在转换mp-18819.cif
正在转换mp-18825.cif
正在转换mp-18829.cif
正在转换mp-18834.cif
正在转换mp-18835.cif
正在转换mp-18837.cif
正在转换mp-18840.cif
正在转换mp-18849.cif
正在转换mp-18852.cif
正在转换mp-18860.cif
正在转换mp-18863.cif
正在转换mp-18868.cif
正在转换mp-18870.cif
正在转换mp-18875.cif
正在转换mp-18876.cif
正在转换mp-18878.cif
正在转换mp-18879.cif
正在转换mp-18880.cif
正在转换mp-18881.cif
正在转换mp-18893.cif
正在转换mp-18898.cif
正在转换mp-18901.cif
正在转换mp-18906.cif
正在转换mp-18939.cif
正在转换mp-18940.cif
正在转换mp-18946.cif
正在转换mp-18949.cif
正在转换mp-18950.cif
正在转换mp-18953.cif
正在转换mp-18956.cif
正在转换mp-18960.cif
正在转换mp-18962.cif
正在转换mp-18967.cif
正在转换mp-18968.cif
正在转换mp-18971.cif
正在转换mp-18977.cif
正在转换mp-18988.cif
正在转换mp-18991.cif
正在转换mp-18992.cif
正在转换mp-18993.cif
正在转换mp-19000.cif
正在转换mp-19003.cif
正在转换mp-19013.cif
正在转换mp-19019.cif
正在转换mp-19021.cif
正在转换mp-19022.cif
正在转换mp-19023.cif
正在转换mp-19026.cif
正在转换mp-19029.cif
正在转换mp-19044.cif
正在转换mp-19048.cif
正在转换mp-19054.cif
正在转换mp-19055.cif
正在转换mp-19059.cif
正在转换mp-19065.cif
正在转换mp-19076.cif
正在转换mp-19082.cif
正在转换mp-19086.cif
正在转换mp-19090.cif
正在转换mp-19093.cif
正在转换mp-19097.cif
正在转换mp-19098.cif
正在转换mp-19105.cif
正在转换mp-19107.cif
正在转换mp-19109.cif
正在转换mp-19111.cif
正在转换mp-19112.cif
正在转换mp-19120.cif
正在转换mp-19121.cif
正在转换mp-19123.cif
正在转换mp-19125.cif
正在转换mp-19126.cif
正在转换mp-19131.cif
正在转换mp-19133.cif
正在转换mp-19137.cif
正在转换mp-19138.cif
正在转换mp-19142.cif
正在转换mp-19147.cif
正在转换mp-19148.cif
正在转换mp-19156.cif
正在转换mp-19157.cif
正在转换mp-19169.cif
正在转换mp-19174.cif
正在转换mp-19182.cif
正在转换mp-19188.cif
正在转换mp-19197.cif
正在转换mp-19198.cif
正在转换mp-19202.cif
正在转换mp-19213.cif
正在转换mp-19214.cif
正在转换mp-19215.cif
正在转换mp-19218.cif
正在转换mp-19219.cif
正在转换mp-1922.cif
正在转换mp-19230.cif
正在转换mp-19238.cif
正在转换mp-19239.cif
正在转换mp-19241.cif
正在转换mp-19243.cif
正在转换mp-19245.cif
正在转换mp-19247.cif
正在转换mp-19299.cif
正在转换mp-19308.cif
正在转换mp-19313.cif
正在转换mp-19318.cif
正在转换mp-19362.cif
正在转换mp-19363.cif
正在转换mp-19365.cif
正在转换mp-19376.cif
正在转换mp-19380.cif
正在转换mp-19386.cif
正在转换mp-19388.cif
正在转换mp-19395.cif
正在转换mp-19399.cif
正在转换mp-19403.cif
正在转换mp-19410.cif
正在转换mp-19417.cif
正在转换mp-19422.cif
正在转换mp-19448.cif
正在转换mp-1944.cif
正在转换mp-19803.cif
正在转换mp-1985.cif
正在转换mp-19885.cif
正在转换mp-19912.cif
正在转换mp-20059.cif
正在转换mp-20082.cif
正在转换mp-20088.cif
正在转换mp-20114.cif
正在转换mp-20133.cif
正在转换mp-20135.cif
正在转换mp-20212.cif
正在转换mp-2030.cif
正在转换mp-20310.cif
正在转换mp-20352.cif
正在转换mp-20396.cif
正在转换mp-20397.cif
正在转换mp-20402.cif
正在转换mp-20414.cif
正在转换mp-2042.cif
正在转换mp-20461.cif
正在转换mp-20466.cif
正在转换mp-2075.cif
正在转换mp-20474.cif
正在转换mp-20480.cif
正在转换mp-20493.cif
正在转换mp-20495.cif
正在转换mp-20496.cif
正在转换mp-20511.cif
正在转换mp-20535.cif
正在转换mp-20546.cif
正在转换mp-20559.cif
正在转换mp-20605.cif
正在转换mp-20620.cif
正在转换mp-20647.cif
正在转换mp-20652.cif
正在转换mp-20683.cif
正在转换mp-20692.cif
正在转换mp-20694.cif
正在转换mp-20697.cif
正在转换mp-20716.cif
正在转换mp-2079.cif
正在转换mp-20805.cif
正在转换mp-20815.cif
正在转换mp-20938.cif
正在转换mp-20944.cif
正在转换mp-20980.cif
正在转换mp-20991.cif
正在转换mp-21037.cif
正在转换mp-21040.cif
正在转换mp-21084.cif
正在转换mp-21099.cif
正在转换mp-21112.cif
正在转换mp-21137.cif
正在转换mp-21166.cif
正在转换mp-21190.cif
正在转换mp-21231.cif
正在转换mp-21246.cif
正在转换mp-21282.cif
正在转换mp-21286.cif
正在转换mp-21299.cif
正在转换mp-21309.cif
正在转换mp-2131.cif
正在转换mp-21378.cif
正在转换mp-21445.cif
正在转换mp-21459.cif
正在转换mp-21489.cif
正在转换mp-21497.cif
正在转换mp-21498.cif
正在转换mp-21510.cif
正在转换mp-21511.cif
正在转换mp-21515.cif
正在转换mp-21858.cif
正在转换mp-21866.cif
正在转换mp-21868.cif
正在转换mp-21879.cif
正在转换mp-21892.cif
正在转换mp-22039.cif
正在转换mp-22052.cif
正在转换mp-22083.cif
正在转换mp-22114.cif
正在转换mp-22130.cif
正在转换mp-22168.cif
正在转换mp-22170.cif
正在转换mp-22171.cif
正在转换mp-22184.cif
正在转换mp-22186.cif
正在转换mp-22189.cif
正在转换mp-22230.cif
正在转换mp-2225.cif
正在转换mp-22303.cif
正在转换mp-22312.cif
正在转换mp-22323.cif
正在转换mp-22356.cif
正在转换mp-22375.cif
正在转换mp-22450.cif
正在转换mp-22512.cif
正在转换mp-22538.cif
正在转换mp-22583.cif
正在转换mp-22587.cif
正在转换mp-22605.cif
正在转换mp-22629.cif
正在转换mp-22671.cif
正在转换mp-226.cif
正在转换mp-22702.cif
正在转换mp-22720.cif
正在转换mp-22735.cif
正在转换mp-22745.cif
正在转换mp-22747.cif
正在转换mp-22750.cif
正在转换mp-22756.cif
正在转换mp-22766.cif
正在转换mp-22854.cif
正在转换mp-22869.cif
正在转换mp-22872.cif
正在转换mp-22889.cif
正在转换mp-22908.cif
正在转换mp-22955.cif
正在转换mp-22961.cif
正在转换mp-22963.cif
正在转换mp-22982.cif
正在转换mp-22997.cif
正在转换mp-22999.cif
正在转换mp-23005.cif
正在转换mp-23018.cif
正在转换mp-23034.cif
正在转换mp-23043.cif
正在转换mp-23045.cif
正在转换mp-23053.cif
正在转换mp-23054.cif
正在转换mp-23066.cif
正在转换mp-23083.cif
正在转换mp-23084.cif
正在转换mp-23091.cif
正在转换mp-23092.cif
正在转换mp-23101.cif
正在转换mp-23104.cif
正在转换mp-2310.cif
正在转换mp-23110.cif
正在转换mp-23126.cif
正在转换mp-23127.cif
正在转换mp-23137.cif
正在转换mp-23138.cif
正在转换mp-23140.cif
正在转换mp-23160.cif
正在转换mp-23169.cif
正在转换mp-23185.cif
正在转换mp-23212.cif
正在转换mp-23215.cif
正在转换mp-23237.cif
正在转换mp-23260.cif
正在转换mp-23270.cif
正在转换mp-23287.cif
正在转换mp-23291.cif
正在转换mp-23315.cif
正在转换mp-23318.cif
正在转换mp-23349.cif
正在转换mp-23354.cif
正在转换mp-23360.cif
正在转换mp-23361.cif
正在转换mp-23395.cif
正在转换mp-23407.cif
正在转换mp-2340.cif
正在转换mp-23411.cif
正在转换mp-23417.cif
正在转换mp-23418.cif
正在转换mp-23446.cif
正在转换mp-23450.cif
正在转换mp-23474.cif
正在转换mp-23486.cif
正在转换mp-23488.cif
正在转换mp-23495.cif
正在转换mp-23507.cif
正在转换mp-23508.cif
正在转换mp-23520.cif
正在转换mp-23534.cif
正在转换mp-23535.cif
正在转换mp-23536.cif
正在转换mp-23539.cif
正在转换mp-23541.cif
正在转换mp-23550.cif
正在转换mp-23556.cif
正在转换mp-23562.cif
正在转换mp-23571.cif
正在转换mp-23582.cif
正在转换mp-23611.cif
正在转换mp-23657.cif
正在转换mp-23664.cif
正在转换mp-23675.cif
正在转换mp-23684.cif
正在转换mp-23702.cif
正在转换mp-23704.cif
正在转换mp-23709.cif
正在转换mp-23711.cif
正在转换mp-23712.cif
正在转换mp-23713.cif
正在转换mp-23714.cif
正在转换mp-23715.cif
正在转换mp-23719.cif
正在转换mp-23720.cif
正在转换mp-23736.cif
正在转换mp-23763.cif
正在转换mp-23764.cif
正在转换mp-23771.cif
正在转换mp-23790.cif
正在转换mp-23837.cif
正在转换mp-23844.cif
正在转换mp-23850.cif
正在转换mp-23875.cif
正在转换mp-23884.cif
正在转换mp-23904.cif
正在转换mp-23918.cif
正在转换mp-23939.cif
正在转换mp-23945.cif
正在转换mp-23955.cif
正在转换mp-23966.cif
正在转换mp-23969.cif
正在转换mp-2398.cif
正在转换mp-24007.cif
正在转换mp-2402.cif
正在转换mp-24030.cif
正在转换mp-24064.cif
正在转换mp-24074.cif
正在转换mp-24075.cif
正在转换mp-24076.cif
正在转换mp-24090.cif
正在转换mp-24119.cif
正在转换mp-24121.cif
正在转换mp-24124.cif
正在转换mp-24227.cif
正在转换mp-24338.cif
正在转换mp-243.cif
正在转换mp-24409.cif
正在转换mp-24433.cif
正在转换mp-24522.cif
正在转换mp-2457.cif
正在转换mp-24589.cif
正在转换mp-2460.cif
正在转换mp-24645.cif
正在转换mp-24841.cif
正在转换mp-24844.cif
正在转换mp-24846.cif
正在转换mp-24854.cif
正在转换mp-24856.cif
正在转换mp-24858.cif
正在转换mp-24860.cif
正在转换mp-24868.cif
正在转换mp-24879.cif
正在转换mp-24880.cif
正在转换mp-24899.cif
正在转换mp-24908.cif
正在转换mp-24932.cif
正在转换mp-24934.cif
正在转换mp-24935.cif
正在转换mp-24938.cif
正在转换mp-24939.cif
正在转换mp-24940.cif
正在转换mp-24943.cif
正在转换mp-24948.cif
正在转换mp-24955.cif
正在转换mp-24967.cif
正在转换mp-24968.cif
正在转换mp-24969.cif
正在转换mp-24971.cif
正在转换mp-24973.cif
正在转换mp-24974.cif
正在转换mp-24977.cif
正在转换mp-25003.cif
正在转换mp-25004.cif
正在转换mp-25005.cif

正在转换mp-25006.cif
正在转换mp-25008.cif
正在转换mp-25012.cif
正在转换mp-25013.cif
正在转换mp-25014.cif
正在转换mp-25032.cif
正在转换mp-25046.cif
正在转换mp-25100.cif
正在转换mp-25110.cif
正在转换mp-25113.cif
正在转换mp-2511.cif
正在转换mp-25122.cif
正在转换mp-2513.cif
正在转换mp-25142.cif
正在转换mp-25145.cif
正在转换mp-25176.cif
正在转换mp-2517.cif
正在转换mp-25262.cif
正在转换mp-25301.cif
正在转换mp-25305.cif
正在转换mp-25420.cif
正在转换mp-25484.cif
正在转换mp-25501.cif
正在转换mp-25502.cif
正在转换mp-25508.cif
正在转换mp-25533.cif
正在转换mp-25545.cif
正在转换mp-25556.cif
正在转换mp-25562.cif
正在转换mp-25569.cif
正在转换mp-25572.cif
正在转换mp-25576.cif
正在转换mp-25578.cif
正在转换mp-25579.cif
正在转换mp-25582.cif
正在转换mp-25595.cif
正在转换mp-25600.cif
正在转换mp-25605.cif
正在转换mp-25619.cif
正在转换mp-25620.cif
正在转换mp-25633.cif
正在转换mp-2576.cif
正在转换mp-2584.cif
正在转换mp-2589.cif
正在转换mp-2604.cif
正在转换mp-2623.cif
正在转换mp-2632.cif
正在转换mp-2633.cif
正在转换mp-2682.cif
正在转换mp-27125.cif
正在转换mp-27126.cif
正在转换mp-2715.cif
正在转换mp-27167.cif
正在转换mp-27171.cif
正在转换mp-27173.cif
正在转换mp-27175.cif
正在转换mp-27176.cif
正在转换mp-27180.cif
正在转换mp-27205.cif
正在转换mp-27227.cif
正在转换mp-27230.cif
正在转换mp-27234.cif
正在转换mp-27251.cif
正在转换mp-27253.cif
正在转换mp-27254.cif
正在转换mp-27255.cif
正在转换mp-27265.cif
正在转换mp-27280.cif
正在转换mp-27281.cif
正在转换mp-27291.cif
正在转换mp-27300.cif
正在转换mp-27303.cif
正在转换mp-27333.cif
正在转换mp-27345.cif
正在转换mp-27367.cif
正在转换mp-27369.cif
正在转换mp-27370.cif
正在转换mp-27373.cif
正在转换mp-27385.cif
正在转换mp-27386.cif
正在转换mp-2739.cif
正在转换mp-27401.cif
正在转换mp-27404.cif
正在转换mp-27409.cif
正在转换mp-27413.cif
正在转换mp-27436.cif
正在转换mp-27453.cif
正在转换mp-27456.cif
正在转换mp-27461.cif
正在转换mp-27474.cif
正在转换mp-27478.cif
正在转换mp-27480.cif
正在转换mp-27487.cif
正在转换mp-27488.cif
正在转换mp-27500.cif
正在转换mp-27508.cif
正在转换mp-27517.cif
正在转换mp-27552.cif
正在转换mp-27563.cif
正在转换mp-27577.cif
正在转换mp-27606.cif
正在转换mp-27608.cif
正在转换mp-27678.cif
正在转换mp-2789.cif
正在转换mp-2826.cif
正在转换mp-2852.cif
正在转换mp-2874.cif
正在转换mp-2898.cif
正在转换mp-2908.cif
正在转换mp-2926.cif
正在转换mp-2970.cif
正在转换mp-2979.cif
正在转换mp-3006.cif
正在转换mp-3010.cif
正在转换mp-3019.cif
正在转换mp-3041.cif
正在转换mp-304.cif
正在转换mp-3070.cif
正在转换mp-3074.cif
正在转换mp-3107.cif
正在转换mp-3125.cif
正在转换mp-3143.cif
正在转换mp-3144.cif
正在转换mp-3179.cif
正在转换mp-3188.cif
正在转换mp-3203.cif
正在转换mp-3205.cif
正在转换mp-3228.cif
正在转换mp-3237.cif
正在转换mp-3248.cif
正在转换mp-3316.cif
正在转换mp-3319.cif
正在转换mp-3324.cif
正在转换mp-3336.cif
正在转换mp-3338.cif
正在转换mp-3349.cif
正在转换mp-3379.cif
正在转换mp-3395.cif
正在转换mp-3407.cif
正在转换mp-3419.cif
正在转换mp-3427.cif
正在转换mp-3439.cif
正在转换mp-3442.cif
正在转换mp-3443.cif
正在转换mp-3444.cif
正在转换mp-3466.cif
正在转换mp-3496.cif
正在转换mp-3519.cif
正在转换mp-3527.cif
正在转换mp-352.cif
正在转换mp-3546.cif
正在转换mp-356.cif
正在转换mp-3602.cif
正在转换mp-3606.cif
正在转换mp-3622.cif
正在转换mp-3632.cif
正在转换mp-3633.cif
正在转换mp-3647.cif
正在转换mp-3650.cif
正在转换mp-3653.cif
正在转换mp-3666.cif
正在转换mp-3677.cif
正在转换mp-3682.cif
正在转换mp-3701.cif
正在转换mp-3707.cif
正在转换mp-3721.cif
正在转换mp-3739.cif
正在转换mp-3751.cif
正在转换mp-3756.cif
正在转换mp-3759.cif
正在转换mp-3771.cif
正在转换mp-3777.cif
正在转换mp-3807.cif
正在转换mp-382.cif
正在转换mp-3830.cif
正在转换mp-384.cif
正在转换mp-3879.cif
正在转换mp-3881.cif
正在转换mp-3901.cif
正在转换mp-3904.cif
正在转换mp-3922.cif
正在转换mp-3930.cif
正在转换mp-3933.cif
正在转换mp-3934.cif
正在转换mp-3953.cif
正在转换mp-3996.cif
正在转换mp-402.cif
正在转换mp-4044.cif
正在转换mp-4052.cif
正在转换mp-409.cif
正在转换mp-4122.cif
正在转换mp-4156.cif
正在转换mp-415.cif
正在转换mp-4165.cif
正在转换mp-4187.cif
正在转换mp-4190.cif
正在转换mp-4198.cif
正在转换mp-4200.cif
正在转换mp-4236.cif
正在转换mp-4249.cif
正在转换mp-4264.cif
正在转换mp-4284.cif
正在转换mp-430.cif
正在转换mp-4324.cif
正在转换mp-4338.cif
正在转换mp-4344.cif
正在转换mp-4360.cif
正在转换mp-4385.cif
正在转换mp-4419.cif
正在转换mp-4431.cif
正在转换mp-4453.cif
正在转换mp-4468.cif
正在转换mp-4482.cif
正在转换mp-4497.cif
正在转换mp-4514.cif
正在转换mp-4515.cif
正在转换mp-4527.cif
正在转换mp-4530.cif
正在转换mp-4531.cif
正在转换mp-4533.cif
正在转换mp-4534.cif
正在转换mp-4549.cif
正在转换mp-4558.cif
正在转换mp-4578.cif
正在转换mp-4584.cif
正在转换mp-4590.cif
正在转换mp-4624.cif
正在转换mp-4627.cif
正在转换mp-4649.cif
正在转换mp-4656.cif
正在转换mp-4661.cif
正在转换mp-4675.cif
正在转换mp-4690.cif
正在转换mp-4691.cif
正在转换mp-4697.cif
正在转换mp-4709.cif
正在转换mp-4718.cif
正在转换mp-4733.cif
正在转换mp-4747.cif
正在转换mp-476.cif
正在转换mp-4770.cif
正在转换mp-4784.cif
正在转换mp-4790.cif
正在转换mp-4798.cif
正在转换mp-4820.cif
正在转换mp-4842.cif
正在转换mp-484.cif
正在转换mp-487.cif
正在转换mp-4888.cif
正在转换mp-4900.cif
正在转换mp-4930.cif
正在转换mp-4941.cif
正在转换mp-5014.cif
正在转换mp-502.cif
正在转换mp-5061.cif
正在转换mp-5076.cif
正在转换mp-5081.cif
正在转换mp-5122.cif
正在转换mp-5127.cif
正在转换mp-5141.cif
正在转换mp-5145.cif
正在转换mp-5146.cif
正在转换mp-5189.cif
正在转换mp-5222.cif
正在转换mp-5280.cif
正在转换mp-5282.cif
正在转换mp-5309.cif
正在转换mp-5327.cif
正在转换mp-5348.cif
正在转换mp-5370.cif
正在转换mp-5377.cif
正在转换mp-5387.cif
正在转换mp-539.cif
正在转换mp-5402.cif
正在转换mp-5431.cif
正在转换mp-5461.cif
正在转换mp-5470.cif
正在转换mp-5478.cif
正在转换mp-5496.cif
正在转换mp-5503.cif
正在转换mp-552.cif
正在转换mp-5558.cif
正在转换mp-557.cif
正在转换mp-5586.cif
正在转换mp-5594.cif
正在转换mp-5618.cif
正在转换mp-5625.cif
正在转换mp-5632.cif
正在转换mp-5637.cif
正在转换mp-5639.cif
正在转换mp-563.cif
正在转换mp-5652.cif
正在转换mp-5679.cif
正在转换mp-5709.cif
正在转换mp-5737.cif
正在转换mp-5756.cif
正在转换mp-5769.cif
正在转换mp-576.cif
正在转换mp-5784.cif
正在转换mp-5794.cif
正在转换mp-5813.cif
正在转换mp-5836.cif
正在转换mp-5839.cif
正在转换mp-5854.cif
正在转换mp-5874.cif
正在转换mp-5899.cif
正在转换mp-5942.cif
正在转换mp-5966.cif
正在转换mp-5985.cif
正在转换mp-5999.cif
正在转换mp-6013.cif
正在转换mp-6023.cif
正在转换mp-6026.cif
正在转换mp-6037.cif
正在转换mp-604.cif
正在转换mp-6050.cif
正在转换mp-6065.cif
正在转换mp-6066.cif
正在转换mp-6080.cif
正在转换mp-6110.cif
正在转换mp-6119.cif
正在转换mp-6122.cif
正在转换mp-6126.cif
正在转换mp-6138.cif
正在转换mp-6145.cif
正在转换mp-6167.cif
正在转换mp-6181.cif
正在转换mp-6192.cif
正在转换mp-6215.cif
正在转换mp-6228.cif
正在转换mp-6231.cif
正在转换mp-624.cif
正在转换mp-6252.cif
正在转换mp-6254.cif
正在转换mp-6259.cif
正在转换mp-6265.cif
正在转换mp-6278.cif
正在转换mp-6304.cif
正在转换mp-6325.cif
正在转换mp-6332.cif
正在转换mp-6356.cif
正在转换mp-6376.cif
正在转换mp-6384.cif
正在转换mp-6388.cif
正在转换mp-6391.cif
正在转换mp-6402.cif
正在转换mp-6406.cif
正在转换mp-6428.cif
正在转换mp-6440.cif
正在转换mp-6449.cif
正在转换mp-6450.cif
正在转换mp-6468.cif
正在转换mp-6474.cif
正在转换mp-6476.cif
正在转换mp-6478.cif
正在转换mp-6492.cif
正在转换mp-6494.cif
正在转换mp-6504.cif
正在转换mp-6509.cif
正在转换mp-6511.cif
正在转换mp-6526.cif
正在转换mp-6560.cif
正在转换mp-6573.cif
正在转换mp-6609.cif
正在转换mp-6613.cif
正在转换mp-6621.cif
正在转换mp-6632.cif
正在转换mp-6633.cif
正在转换mp-6647.cif
正在转换mp-6653.cif
正在转换mp-6660.cif
正在转换mp-6680.cif
正在转换mp-6687.cif
正在转换mp-6692.cif
正在转换mp-6704.cif
正在转换mp-676.cif
正在转换mp-6782.cif
正在转换mp-6798.cif
正在转换mp-6799.cif
正在转换mp-6809.cif
正在转换mp-6829.cif
正在转换mp-6841.cif
正在转换mp-6855.cif
正在转换mp-690.cif
正在转换mp-6929.cif
正在转换mp-6942.cif
正在转换mp-6955.cif
正在转换mp-6960.cif
正在转换mp-6977.cif
正在转换mp-697.cif
正在转换mp-6983.cif
正在转换mp-6984.cif
正在转换mp-6987.cif
正在转换mp-6989.cif
正在转换mp-7020.cif
正在转换mp-7027.cif
正在转换mp-7028.cif
正在转换mp-7035.cif
正在转换mp-7048.cif
正在转换mp-7049.cif
正在转换mp-7064.cif
正在转换mp-7079.cif
正在转换mp-7084.cif
正在转换mp-7094.cif
正在转换mp-7117.cif
正在转换mp-7118.cif
正在转换mp-7129.cif
正在转换mp-7137.cif
正在转换mp-7139.cif
正在转换mp-713.cif
正在转换mp-7147.cif
正在转换mp-7148.cif
正在转换mp-7180.cif
正在转换mp-7191.cif
正在转换mp-7193.cif
正在转换mp-7199.cif
正在转换mp-7206.cif
正在转换mp-7210.cif
正在转换mp-7219.cif
正在转换mp-7249.cif
正在转换mp-7251.cif
正在转换mp-7257.cif
正在转换mp-7258.cif
正在转换mp-7277.cif
正在转换mp-7288.cif
正在转换mp-730.cif
正在转换mp-7352.cif
正在转换mp-7355.cif
正在转换mp-7372.cif
正在转换mp-7373.cif
正在转换mp-7374.cif
正在转换mp-7378.cif
正在转换mp-7386.cif
正在转换mp-7387.cif
正在转换mp-7388.cif
正在转换mp-7404.cif
正在转换mp-741.cif
正在转换mp-7440.cif
正在转换mp-7441.cif
正在转换mp-7444.cif
正在转换mp-7446.cif
正在转换mp-7447.cif
正在转换mp-7456.cif
正在转换mp-7457.cif
正在转换mp-7461.cif
正在转换mp-7462.cif
正在转换mp-7469.cif
正在转换mp-7470.cif
正在转换mp-7492.cif
正在转换mp-7499.cif
正在转换mp-7500.cif
正在转换mp-7505.cif
正在转换mp-7534.cif
正在转换mp-753.cif
正在转换mp-7566.cif
正在转换mp-7580.cif
正在转换mp-7595.cif
正在转换mp-7596.cif
正在转换mp-7601.cif
正在转换mp-7603.cif
正在转换mp-7607.cif
正在转换mp-7609.cif
正在转换mp-7615.cif
正在转换mp-7621.cif
正在转换mp-7622.cif
正在转换mp-7644.cif
正在转换mp-7657.cif
正在转换mp-7667.cif
正在转换mp-7670.cif
正在转换mp-7688.cif
正在转换mp-7703.cif
正在转换mp-7709.cif
正在转换mp-7714.cif
正在转换mp-7716.cif
正在转换mp-7756.cif
正在转换mp-7762.cif
正在转换mp-7765.cif
正在转换mp-7784.cif
正在转换mp-7787.cif
正在转换mp-7798.cif
正在转换mp-7800.cif
正在转换mp-7812.cif
正在转换mp-7831.cif
正在转换mp-7841.cif
正在转换mp-7844.cif
正在转换mp-7853.cif
正在转换mp-7858.cif
正在转换mp-7899.cif
正在转换mp-7904.cif
正在转换mp-7911.cif
正在转换mp-7931.cif
正在转换mp-7941.cif
正在转换mp-7943.cif
正在转换mp-7944.cif
正在转换mp-7951.cif
正在转换mp-7980.cif
正在转换mp-7982.cif
正在转换mp-7986.cif
正在转换mp-7998.cif
正在转换mp-8000.cif
正在转换mp-8007.cif
正在转换mp-8042.cif
正在转换mp-8058.cif
正在转换mp-8081.cif
正在转换mp-8085.cif
正在转换mp-8086.cif
正在转换mp-8098.cif
正在转换mp-8127.cif
正在转换mp-8147.cif
正在转换mp-8153.cif
正在转换mp-8161.cif
正在转换mp-8180.cif
正在转换mp-8184.cif
正在转换mp-8187.cif
正在转换mp-8190.cif
正在转换mp-8200.cif
正在转换mp-8201.cif
正在转换mp-8203.cif

正在转换mp-8207.cif
正在转换mp-8208.cif
正在转换mp-8212.cif
正在转换mp-8218.cif
正在转换mp-8230.cif
正在转换mp-8235.cif
正在转换mp-8248.cif
正在转换mp-8249.cif
正在转换mp-8253.cif
正在转换mp-8257.cif
正在转换mp-8262.cif
正在转换mp-8263.cif
正在转换mp-8267.cif
正在转换mp-8269.cif
正在转换mp-8275.cif
正在转换mp-8285.cif
正在转换mp-8347.cif
正在转换mp-8355.cif
正在转换mp-8377.cif
正在转换mp-8378.cif
正在转换mp-8382.cif
正在转换mp-8388.cif
正在转换mp-8395.cif
正在转换mp-8422.cif
正在转换mp-8449.cif
正在转换mp-8450.cif
正在转换mp-8459.cif
正在转换mp-8479.cif
正在转换mp-8483.cif
正在转换mp-8484.cif
正在转换mp-8500.cif
正在转换mp-8514.cif
正在转换mp-8515.cif
正在转换mp-8543.cif
正在转换mp-8603.cif
正在转换mp-8609.cif
正在转换mp-8610.cif
正在转换mp-8611.cif
正在转换mp-8615.cif
正在转换mp-8624.cif
正在转换mp-8630.cif
正在转换mp-8645.cif
正在转换mp-8683.cif
正在转换mp-8697.cif
正在转换mp-8704.cif
正在转换mp-8713.cif
正在转换mp-8765.cif
正在转换mp-8845.cif
正在转换mp-886.cif
正在转换mp-8872.cif
正在转换mp-8891.cif
正在转换mp-8900.cif
正在转换mp-8926.cif
正在转换mp-8930.cif
正在转换mp-8931.cif
正在转换mp-8943.cif
正在转换mp-8972.cif
正在转换mp-8973.cif
正在转换mp-8979.cif
正在转换mp-9003.cif
正在转换mp-9029.cif
正在转换mp-9055.cif
正在转换mp-9059.cif
正在转换mp-9062.cif
正在转换mp-9063.cif
正在转换mp-9064.cif
正在转换mp-9066.cif
正在转换mp-9068.cif
正在转换mp-9069.cif
正在转换mp-9075.cif
正在转换mp-9115.cif
正在转换mp-9145.cif
正在转换mp-9157.cif
正在转换mp-9159.cif
正在转换mp-9172.cif
正在转换mp-9173.cif
正在转换mp-9178.cif
正在转换mp-9197.cif
正在转换mp-9212.cif
正在转换mp-9245.cif
正在转换mp-9248.cif
正在转换mp-9258.cif
正在转换mp-9259.cif
正在转换mp-927.cif
正在转换mp-9619.cif
正在转换mp-9634.cif
正在转换mp-9635.cif
正在转换mp-963.cif
正在转换mp-9650.cif
正在转换mp-9655.cif
正在转换mp-9656.cif
正在转换mp-9657.cif
正在转换mp-9664.cif
正在转换mp-9665.cif
正在转换mp-9666.cif
正在转换mp-9668.cif
正在转换mp-9672.cif
正在转换mp-9673.cif
正在转换mp-9676.cif
正在转换mp-9692.cif
正在转换mp-9693.cif
正在转换mp-9702.cif
正在转换mp-9705.cif
正在转换mp-9712.cif
正在转换mp-9718.cif
正在转换mp-9720.cif
正在转换mp-9723.cif
正在转换mp-9740.cif
正在转换mp-9750.cif
正在转换mp-9753.cif
正在转换mp-9755.cif
正在转换mp-9757.cif
正在转换mp-9759.cif
正在转换mp-9764.cif
正在转换mp-9780.cif
正在转换mp-9782.cif
正在转换mp-9783.cif
正在转换mp-9785.cif
正在转换mp-978.cif
正在转换mp-9793.cif
正在转换mp-9794.cif
正在转换mp-9797.cif
正在转换mp-9798.cif
正在转换mp-9808.cif
正在转换mp-9812.cif
正在转换mp-9815.cif
正在转换mp-9843.cif
正在转换mp-9844.cif
正在转换mp-9849.cif
正在转换mp-9850.cif
正在转换mp-9851.cif
正在转换mp-9852.cif
正在转换mp-9853.cif
正在转换mp-9854.cif
正在转换mp-9855.cif
正在转换mp-9868.cif
正在转换mp-988.cif
正在转换mp-9890.cif
正在转换mp-9900.cif
正在转换mp-9903.cif
正在转换mp-9905.cif
正在转换mp-9910.cif
正在转换mp-9946.cif
正在转换mp-9993.cif
正在转换mvc-133.cif
正在转换mvc-10002.cif
正在转换mvc-10004.cif
正在转换mvc-10006.cif
正在转换mvc-10011.cif
正在转换mvc-1037.cif
正在转换mvc-1040.cif
正在转换mvc-10442.cif
正在转换mvc-10443.cif
正在转换mvc-1049.cif
正在转换mvc-1055.cif
正在转换mvc-1057.cif
正在转换mvc-1060.cif
正在转换mvc-10699.cif
正在转换mvc-10708.cif
正在转换mvc-10714.cif
正在转换mvc-10720.cif
正在转换mvc-1075.cif
正在转换mvc-1077.cif
正在转换mvc-10843.cif
正在转换mvc-10871.cif
正在转换mvc-10873.cif
正在转换mvc-10887.cif
正在转换mvc-10890.cif
正在转换mvc-10891.cif
正在转换mvc-10908.cif
正在转换mvc-1092.cif
正在转换mvc-10945.cif
正在转换mvc-10962.cif
正在转换mvc-1099.cif
正在转换mvc-11011.cif
正在转换mvc-11034.cif
正在转换mvc-1104.cif
正在转换mvc-11093.cif
正在转换mvc-1109.cif
正在转换mvc-11115.cif
正在转换mvc-11131.cif
正在转换mvc-11133.cif
正在转换mvc-11134.cif
正在转换mvc-11253.cif
正在转换mvc-11256.cif
正在转换mvc-11260.cif
正在转换mvc-11265.cif
正在转换mvc-11266.cif
正在转换mvc-11269.cif
正在转换mvc-11271.cif
正在转换mvc-11272.cif
正在转换mvc-11273.cif
正在转换mvc-11275.cif
正在转换mvc-11277.cif
正在转换mvc-11278.cif
正在转换mvc-1132.cif
正在转换mvc-1136.cif
正在转换mvc-1141.cif
正在转换mvc-11482.cif
正在转换mvc-1148.cif
正在转换mvc-11553.cif
正在转换mvc-11560.cif
正在转换mvc-11612.cif
正在转换mvc-1161.cif
正在转换mvc-11622.cif
正在转换mvc-11624.cif
正在转换mvc-11628.cif
正在转换mvc-11634.cif
正在转换mvc-11640.cif
正在转换mvc-11645.cif
正在转换mvc-11651.cif
正在转换mvc-11654.cif
正在转换mvc-11661.cif
正在转换mvc-11662.cif
正在转换mvc-1166.cif
正在转换mvc-11739.cif
正在转换mvc-11740.cif
正在转换mvc-11741.cif
正在转换mvc-11777.cif
正在转换mvc-11781.cif
正在转换mvc-11791.cif
正在转换mvc-11818.cif
正在转换mvc-11848.cif
正在转换mvc-11912.cif
正在转换mvc-1192.cif
正在转换mvc-11931.cif
正在转换mvc-11949.cif
正在转换mvc-1194.cif
正在转换mvc-11952.cif
正在转换mvc-11960.cif
正在转换mvc-11964.cif
正在转换mvc-11965.cif
正在转换mvc-11970.cif
正在转换mvc-11981.cif
正在转换mvc-11982.cif
正在转换mvc-11984.cif
正在转换mvc-11986.cif
正在转换mvc-11989.cif
正在转换mvc-11995.cif
正在转换mvc-11999.cif
正在转换mvc-1200.cif
正在转换mvc-12012.cif
正在转换mvc-12022.cif
正在转换mvc-12044.cif
正在转换mvc-12050.cif
正在转换mvc-12077.cif
正在转换mvc-12083.cif
正在转换mvc-12120.cif
正在转换mvc-12125.cif
正在转换mvc-12126.cif
正在转换mvc-12139.cif
正在转换mvc-12181.cif
正在转换mvc-12183.cif
正在转换mvc-12231.cif
正在转换mvc-12238.cif
正在转换mvc-12244.cif
正在转换mvc-12340.cif
正在转换mvc-12347.cif
正在转换mvc-12368.cif
正在转换mvc-12369.cif
正在转换mvc-12383.cif
正在转换mvc-12404.cif
正在转换mvc-12546.cif
正在转换mvc-12553.cif
正在转换mvc-12570.cif
正在转换mvc-12572.cif
正在转换mvc-12576.cif
正在转换mvc-12583.cif
正在转换mvc-12584.cif
正在转换mvc-12591.cif
正在转换mvc-12592.cif
正在转换mvc-1259.cif
正在转换mvc-12603.cif
正在转换mvc-1260.cif
正在转换mvc-12619.cif
正在转换mvc-12627.cif
正在转换mvc-12662.cif
正在转换mvc-12664.cif
正在转换mvc-12697.cif
正在转换mvc-12706.cif
正在转换mvc-12728.cif
正在转换mvc-12731.cif
正在转换mvc-12733.cif
正在转换mvc-12752.cif
正在转换mvc-12753.cif
正在转换mvc-12760.cif
正在转换mvc-12762.cif
正在转换mvc-12825.cif
正在转换mvc-12846.cif
正在转换mvc-1293.cif
正在转换mvc-12941.cif
正在转换mvc-12948.cif
正在转换mvc-1294.cif
正在转换mvc-12953.cif
正在转换mvc-12954.cif
正在转换mvc-1296.cif
正在转换mvc-1298.cif
正在转换mvc-1300.cif
正在转换mvc-1304.cif
正在转换mvc-13217.cif
正在转换mvc-1330.cif
正在转换mvc-13402.cif
正在转换mvc-13425.cif
正在转换mvc-13532.cif
正在转换mvc-13533.cif
正在转换mvc-13696.cif
正在转换mvc-13890.cif
正在转换mvc-13971.cif
正在转换mvc-13972.cif
正在转换mvc-13997.cif
正在转换mvc-14005.cif
正在转换mvc-14025.cif
正在转换mvc-14026.cif
正在转换mvc-14034.cif
正在转换mvc-14038.cif
正在转换mvc-14043.cif
正在转换mvc-14048.cif
正在转换mvc-14054.cif
正在转换mvc-14055.cif
正在转换mvc-14096.cif
正在转换mvc-14106.cif
正在转换mvc-14149.cif
正在转换mvc-14150.cif
正在转换mvc-14169.cif
正在转换mvc-14177.cif
正在转换mvc-14182.cif
正在转换mvc-14214.cif
正在转换mvc-14215.cif
正在转换mvc-14217.cif
正在转换mvc-14219.cif
正在转换mvc-14220.cif
正在转换mvc-14221.cif
正在转换mvc-14224.cif
正在转换mvc-14225.cif
正在转换mvc-15.cif
正在转换mvc-14229.cif
正在转换mvc-14231.cif
正在转换mvc-14232.cif
正在转换mvc-14233.cif
正在转换mvc-14279.cif
正在转换mvc-14286.cif
正在转换mvc-14287.cif
正在转换mvc-14293.cif
正在转换mvc-14324.cif
正在转换mvc-14335.cif
正在转换mvc-14381.cif
正在转换mvc-14383.cif
正在转换mvc-14389.cif
正在转换mvc-14411.cif
正在转换mvc-14442.cif
正在转换mvc-14450.cif
正在转换mvc-14455.cif
正在转换mvc-14482.cif
正在转换mvc-14538.cif
正在转换mvc-14586.cif
正在转换mvc-14589.cif
正在转换mvc-14740.cif
正在转换mvc-14742.cif
正在转换mvc-14765.cif
正在转换mvc-14876.cif
正在转换mvc-14927.cif
正在转换mvc-14941.cif
正在转换mvc-14949.cif
正在转换mvc-14952.cif
正在转换mvc-14963.cif
正在转换mvc-14972.cif
正在转换mvc-15000.cif
正在转换mvc-15001.cif
正在转换mvc-15005.cif
正在转换mvc-15009.cif
正在转换mvc-15159.cif
正在转换mvc-15303.cif
正在转换mvc-15350.cif
正在转换mvc-15363.cif
正在转换mvc-15376.cif
正在转换mvc-15380.cif
正在转换mvc-15400.cif
正在转换mvc-15440.cif
正在转换mvc-15446.cif
正在转换mvc-15449.cif
正在转换mvc-15495.cif
正在转换mvc-15503.cif
正在转换mvc-15544.cif
正在转换mvc-15550.cif
正在转换mvc-15566.cif
正在转换mvc-15567.cif
正在转换mvc-15590.cif
正在转换mvc-15601.cif
正在转换mvc-15814.cif
正在转换mvc-15827.cif
正在转换mvc-15941.cif
正在转换mvc-15960.cif
正在转换mvc-15986.cif
正在转换mvc-15992.cif
正在转换mvc-15993.cif
正在转换mvc-16044.cif
正在转换mvc-16045.cif
正在转换mvc-16050.cif
正在转换mvc-16051.cif
正在转换mvc-16054.cif
正在转换mvc-16055.cif
正在转换mvc-16057.cif
正在转换mvc-16058.cif
正在转换mvc-16059.cif
正在转换mvc-16060.cif
正在转换mvc-16083.cif
正在转换mvc-16094.cif
正在转换mvc-16102.cif
正在转换mvc-16105.cif
正在转换mvc-16164.cif
正在转换mvc-1620.cif
正在转换mvc-16211.cif
正在转换mvc-16216.cif
正在转换mvc-1621.cif
正在转换mvc-16228.cif
正在转换mvc-16230.cif
正在转换mvc-16234.cif
正在转换mvc-1623.cif
正在转换mvc-16241.cif
正在转换mvc-16254.cif
正在转换mvc-16274.cif
正在转换mvc-16291.cif
正在转换mvc-16295.cif
正在转换mvc-16304.cif
正在转换mvc-16307.cif
正在转换mvc-16497.cif
正在转换mvc-16567.cif
正在转换mvc-1657.cif
正在转换mvc-16583.cif
正在转换mvc-1659.cif
正在转换mvc-1660.cif
正在转换mvc-1666.cif
正在转换mvc-16771.cif
正在转换mvc-16798.cif
正在转换mvc-16800.cif
正在转换mvc-16805.cif
正在转换mvc-16809.cif
正在转换mvc-16816.cif
正在转换mvc-16834.cif
正在转换mvc-16835.cif
正在转换mvc-175.cif
正在转换mvc-1.cif
正在转换mvc-2085.cif
正在转换mvc-2092.cif
正在转换mvc-2119.cif
正在转换mvc-2126.cif
正在转换mvc-2129.cif
正在转换mvc-2157.cif
正在转换mvc-2186.cif
正在转换mvc-239.cif
正在转换mvc-2426.cif
正在转换mvc-2430.cif
正在转换mvc-2447.cif
正在转换mvc-2453.cif
正在转换mvc-2461.cif
正在转换mvc-2488.cif
正在转换mvc-2489.cif
正在转换mvc-2513.cif
正在转换mvc-2529.cif
正在转换mvc-2534.cif
正在转换mvc-2537.cif
正在转换mvc-253.cif
正在转换mvc-2541.cif
正在转换mvc-2577.cif
正在转换mvc-2597.cif
正在转换mvc-2609.cif
正在转换mvc-2612.cif
正在转换mvc-2614.cif
正在转换mvc-2834.cif
正在转换mvc-2851.cif
正在转换mvc-2854.cif
正在转换mvc-2863.cif
正在转换mvc-2868.cif
正在转换mvc-2898.cif
正在转换mvc-2903.cif
正在转换mvc-2921.cif
正在转换mvc-2922.cif
正在转换mvc-2939.cif
正在转换mvc-2940.cif
正在转换mvc-2941.cif
正在转换mvc-2945.cif
正在转换mvc-2949.cif
正在转换mvc-2955.cif
正在转换mvc-2970.cif
正在转换mvc-2979.cif
正在转换mvc-2985.cif
正在转换mvc-2990.cif
正在转换mvc-2992.cif
正在转换mvc-2994.cif
正在转换mvc-3003.cif
正在转换mvc-3029.cif
正在转换mvc-3049.cif
正在转换mvc-3081.cif
正在转换mvc-3091.cif
正在转换mvc-3099.cif
正在转换mvc-3102.cif
正在转换mvc-3128.cif
正在转换mvc-3135.cif
正在转换mvc-3157.cif
正在转换mvc-3192.cif
正在转换mvc-3195.cif
正在转换mvc-3211.cif

正在转换mvc-3213.cif
正在转换mvc-3218.cif
正在转换mvc-3227.cif
正在转换mvc-3228.cif
正在转换mvc-3229.cif
正在转换mvc-3230.cif
正在转换mvc-3232.cif
正在转换mvc-3234.cif
正在转换mvc-3236.cif
正在转换mvc-3237.cif
正在转换mvc-3242.cif
正在转换mvc-3243.cif
正在转换mvc-3245.cif
正在转换mvc-3248.cif
正在转换mvc-3255.cif
正在转换mvc-3257.cif
正在转换mvc-3264.cif
正在转换mvc-3265.cif
正在转换mvc-3267.cif
正在转换mvc-3271.cif
正在转换mvc-3277.cif
正在转换mvc-3279.cif
正在转换mvc-3283.cif
正在转换mvc-3291.cif
正在转换mvc-3299.cif
正在转换mvc-3317.cif
正在转换mvc-3319.cif
正在转换mvc-3340.cif
正在转换mvc-3341.cif
正在转换mvc-3346.cif
正在转换mvc-3347.cif
正在转换mvc-3380.cif
正在转换mvc-3394.cif
正在转换mvc-3446.cif
正在转换mvc-3477.cif
正在转换mvc-3497.cif
正在转换mvc-3511.cif
正在转换mvc-3519.cif
正在转换mvc-3525.cif
正在转换mvc-3556.cif
正在转换mvc-3569.cif
正在转换mvc-3578.cif
正在转换mvc-3677.cif
正在转换mvc-36.cif
正在转换mvc-3716.cif
正在转换mvc-3728.cif
正在转换mvc-3752.cif
正在转换mvc-3762.cif
正在转换mvc-3793.cif
正在转换mvc-3799.cif
正在转换mvc-3800.cif
正在转换mvc-3803.cif
正在转换mvc-3807.cif
正在转换mvc-3809.cif
正在转换mvc-3853.cif
正在转换mvc-3865.cif
正在转换mvc-3875.cif
正在转换mvc-3947.cif
正在转换mvc-3950.cif
正在转换mvc-3978.cif
正在转换mvc-3982.cif
正在转换mvc-3983.cif
正在转换mvc-3985.cif
正在转换mvc-3986.cif
正在转换mvc-3988.cif
正在转换mvc-4120.cif
正在转换mvc-4130.cif
正在转换mvc-4135.cif
正在转换mvc-4245.cif
正在转换mvc-4246.cif
正在转换mvc-4274.cif
正在转换mvc-4299.cif
正在转换mvc-4323.cif
正在转换mvc-4364.cif
正在转换mvc-4413.cif
正在转换mvc-4415.cif
正在转换mvc-4456.cif
正在转换mvc-446.cif
正在转换mvc-4601.cif
正在转换mvc-4606.cif
正在转换mvc-4608.cif
正在转换mvc-4609.cif
正在转换mvc-4610.cif
正在转换mvc-4611.cif
正在转换mvc-4613.cif
正在转换mvc-4616.cif
正在转换mvc-4658.cif
正在转换mvc-4659.cif
正在转换mvc-4661.cif
正在转换mvc-4662.cif
正在转换mvc-4668.cif
正在转换mvc-4676.cif
正在转换mvc-4678.cif
正在转换mvc-4682.cif
正在转换mvc-4689.cif
正在转换mvc-4692.cif
正在转换mvc-4703.cif
正在转换mvc-4706.cif
正在转换mvc-4769.cif
正在转换mvc-4795.cif
正在转换mvc-4822.cif
正在转换mvc-4829.cif
正在转换mvc-484.cif
正在转换mvc-4854.cif
正在转换mvc-4875.cif
正在转换mvc-4908.cif
正在转换mvc-4949.cif
正在转换mvc-4955.cif
正在转换mvc-499.cif
正在转换mvc-5000.cif
正在转换mvc-5033.cif
正在转换mvc-507.cif
正在转换mvc-5126.cif
正在转换mvc-5168.cif
正在转换mvc-5170.cif
正在转换mvc-5179.cif
正在转换mvc-5180.cif
正在转换mvc-5182.cif
正在转换mvc-5183.cif
正在转换mvc-5272.cif
正在转换mvc-528.cif
正在转换mvc-5304.cif
正在转换mvc-532.cif
正在转换mvc-5445.cif
正在转换mvc-5448.cif
正在转换mvc-5491.cif
正在转换mvc-5517.cif
正在转换mvc-5559.cif
正在转换mvc-5566.cif
正在转换mvc-5694.cif
正在转换mvc-5761.cif
正在转换mvc-5788.cif
正在转换mvc-583.cif
正在转换mvc-5865.cif
正在转换mvc-5883.cif
正在转换mvc-5884.cif
正在转换mvc-588.cif
正在转换mvc-5897.cif
正在转换mvc-594.cif
正在转换mvc-5956.cif
正在转换mvc-5957.cif
正在转换mvc-5960.cif
正在转换mvc-5979.cif
正在转换mvc-5984.cif
正在转换mvc-5993.cif
正在转换mvc-5997.cif
正在转换mvc-6033.cif
正在转换mvc-6035.cif
正在转换mvc-6052.cif
正在转换mvc-6055.cif
正在转换mvc-6057.cif
正在转换mvc-605.cif
正在转换mvc-6066.cif
正在转换mvc-6068.cif
正在转换mvc-6071.cif
正在转换mvc-6074.cif
正在转换mvc-6075.cif
正在转换mvc-6076.cif
正在转换mvc-6081.cif
正在转换mvc-6087.cif
正在转换mvc-6093.cif
正在转换mvc-609.cif
正在转换mvc-6101.cif
正在转换mvc-6108.cif
正在转换mvc-6148.cif
正在转换mvc-6159.cif
正在转换mvc-615.cif
正在转换mvc-619.cif
正在转换mvc-620.cif
正在转换mvc-622.cif
正在转换mvc-6291.cif
正在转换mvc-62.cif
正在转换mvc-6390.cif
正在转换mvc-6391.cif
正在转换mvc-6393.cif
正在转换mvc-6394.cif
正在转换mvc-6396.cif
正在转换mvc-6399.cif
正在转换mvc-6400.cif
正在转换mvc-6401.cif
正在转换mvc-6402.cif
正在转换mvc-6403.cif
正在转换mvc-6406.cif
正在转换mvc-6407.cif
正在转换mvc-6408.cif
正在转换mvc-6409.cif
正在转换mvc-6410.cif
正在转换mvc-6413.cif
正在转换mvc-6415.cif
正在转换mvc-6417.cif
正在转换mvc-6418.cif
正在转换mvc-6432.cif
正在转换mvc-6495.cif
正在转换mvc-6497.cif
正在转换mvc-649.cif
正在转换mvc-6512.cif
正在转换mvc-6513.cif
正在转换mvc-6532.cif
正在转换mvc-6540.cif
正在转换mvc-6541.cif
正在转换mvc-6542.cif
正在转换mvc-6545.cif
正在转换mvc-6547.cif
正在转换mvc-6554.cif
正在转换mvc-6570.cif
正在转换mvc-6576.cif
正在转换mvc-6590.cif
正在转换mvc-659.cif
正在转换mvc-6611.cif
正在转换mvc-6615.cif
正在转换mvc-664.cif
正在转换mvc-6654.cif
正在转换mvc-6670.cif
正在转换mvc-66.cif
正在转换mvc-672.cif
正在转换mvc-673.cif
正在转换mvc-677.cif
正在转换mvc-688.cif
正在转换mvc-6900.cif
正在转换mvc-6910.cif
正在转换mvc-6911.cif
正在转换mvc-6912.cif
正在转换mvc-6915.cif
正在转换mvc-6916.cif
正在转换mvc-6917.cif
正在转换mvc-6918.cif
正在转换mvc-6919.cif
正在转换mvc-6920.cif
正在转换mvc-6923.cif
正在转换mvc-6925.cif
正在转换mvc-6927.cif
正在转换mvc-6928.cif
正在转换mvc-692.cif
正在转换mvc-6932.cif
正在转换mvc-6933.cif
正在转换mvc-6934.cif
正在转换mvc-6935.cif
正在转换mvc-6939.cif
正在转换mvc-6940.cif
正在转换mvc-6944.cif
正在转换mvc-6953.cif
正在转换mvc-725.cif
正在转换mvc-7276.cif
正在转换mvc-7287.cif
正在转换mvc-7303.cif
正在转换mvc-7308.cif
正在转换mvc-7315.cif
正在转换mvc-7317.cif
正在转换mvc-7329.cif
正在转换mvc-7347.cif
正在转换mvc-748.cif
正在转换mvc-763.cif
正在转换mvc-7741.cif
正在转换mvc-7764.cif
正在转换mvc-78.cif
正在转换mvc-8064.cif
正在转换mvc-8086.cif
正在转换mvc-8087.cif
正在转换mvc-8098.cif
正在转换mvc-8123.cif
正在转换mvc-8202.cif
正在转换mvc-8236.cif
正在转换mvc-916.cif
正在转换mvc-8242.cif
正在转换mvc-8330.cif
正在转换mvc-8339.cif
正在转换mvc-8344.cif
正在转换mvc-8350.cif
正在转换mvc-8358.cif
正在转换mvc-8359.cif
正在转换mvc-8363.cif
正在转换mvc-8366.cif
正在转换mvc-8370.cif
正在转换mvc-8371.cif
正在转换mvc-8376.cif
正在转换mvc-8393.cif
正在转换mvc-8396.cif
正在转换mvc-8400.cif
正在转换mvc-8411.cif
正在转换mvc-8422.cif
正在转换mvc-8471.cif
正在转换mvc-8472.cif
正在转换mvc-8473.cif
正在转换mvc-8747.cif
正在转换mvc-8751.cif
正在转换mvc-8773.cif
正在转换mvc-8781.cif
正在转换mvc-8786.cif
正在转换mvc-8795.cif
正在转换mvc-8797.cif
正在转换mvc-9126.cif
正在转换mvc-9127.cif
正在转换mvc-9128.cif
正在转换mvc-9161.cif
正在转换mvc-919.cif
正在转换mvc-91.cif
正在转换mvc-921.cif
正在转换mvc-924.cif
正在转换mvc-926.cif
正在转换mvc-928.cif
正在转换mvc-929.cif
正在转换mvc-932.cif
正在转换mvc-945.cif
正在转换mvc-947.cif
正在转换mvc-9645.cif
正在转换mvc-98.cif
正在转换mvc-9977.cif
正在转换mvc-9979.cif
正在转换mvc-9980.cif
正在转换mvc-9981.cif
正在转换mvc-9983.cif
正在转换mvc-9986.cif
正在转换mvc-9987.cif
正在转换mvc-9990.cif
正在转换mvc-9991.cif
正在转换mvc-9992.cif
正在转换mvc-9993.cif
正在转换mvc-9994.cif
正在转换mvc-9995.cif
正在转换mvc-9996.cif
正在转换mp-19328.cif
正在转换mp-20171.cif
正在转换mp-21315.cif
正在转换mp-24906.cif
正在转换mp-34047.cif
正在转换mvc-15835.cif
正在转换mvc-15846.cif
正在转换mvc-5693.cif
正在转换mvc-5801.cif
正在转换mvc-7747.cif
正在转换mp-14232.cif
正在转换mp-15336.cif
正在转换mp-16184.cif
正在转换mp-17148.cif
正在转换mp-18165.cif
正在转换mp-18378.cif
正在转换mp-22618.cif
正在转换mp-27275.cif
正在转换mp-27564.cif
正在转换mp-27670.cif
正在转换mp-27719.cif
正在转换mp-28146.cif
正在转换mp-28235.cif
正在转换mp-28380.cif
正在转换mp-29225.cif
正在转换mp-29454.cif
正在转换mp-3635.cif
正在转换mp-541686.cif
正在转换mp-542637.cif
正在转换mp-549158.cif
正在转换mp-556168.cif
正在转换mp-556916.cif
正在转换mp-557929.cif
正在转换mp-558706.cif
正在转换mp-569204.cif
正在转换mp-569813.cif
正在转换mp-571103.cif
正在转换mp-650442.cif
正在转换mp-7535.cif
正在转换mp-8001.cif
正在转换mp-8840.cif
正在转换mp-9047.cif
正在转换mp-9680.cif
正在转换mp-9682.cif
正在转换mp-983565.cif
正在转换mp-22721.cif
正在转换mp-22762.cif
正在转换mp-22770.cif
正在转换mp-22776.cif
正在转换mp-22817.cif
正在转换mp-22891.cif
正在转换mp-23011.cif
正在转换mp-23022.cif
正在转换mp-23186.cif
正在转换mp-23196.cif
正在转换mp-23199.cif
正在转换mp-23259.cif
正在转换mp-23330.cif
正在转换mp-23421.cif
正在转换mp-23438.cif
正在转换mp-23482.cif
正在转换mp-23516.cif
正在转换mp-23547.cif
正在转换mp-23548.cif
正在转换mp-23683.cif
正在转换mp-23758.cif
正在转换mp-23768.cif
正在转换mp-23807.cif
正在转换mp-23885.cif
正在转换mp-23887.cif
正在转换mp-23950.cif
正在转换mp-24019.cif
正在转换mp-24091.cif
正在转换mp-24130.cif
正在转换mp-25015.cif
正在转换mp-25099.cif
正在转换mp-25102.cif
正在转换mp-25201.cif
正在转换mp-25208.cif
正在转换mp-25385.cif
正在转换mp-25405.cif
正在转换mp-25449.cif
正在转换mp-25471.cif
正在转换mp-25516.cif
正在转换mp-25524.cif
正在转换mp-27585.cif
正在转换mp-27672.cif
正在转换mp-27721.cif
正在转换mp-27862.cif
正在转换mp-27872.cif
正在转换mp-27873.cif
正在转换mp-27888.cif
正在转换mp-27916.cif
正在转换mp-27985.cif
正在转换mp-28015.cif
正在转换mp-28068.cif
正在转换mp-28144.cif
正在转换mp-28212.cif
正在转换mp-28450.cif
正在转换mp-28495.cif
正在转换mp-28781.cif
正在转换mp-28835.cif
正在转换mp-29392.cif
正在转换mp-29617.cif
正在转换mp-29620.cif
正在转换mp-29621.cif
正在转换mp-29634.cif
正在转换mp-29646.cif
正在转换mp-29731.cif
正在转换mp-29764.cif
正在转换mp-29836.cif
正在转换mp-30053.cif
正在转换mp-30057.cif
正在转换mp-30085.cif
正在转换mp-30134.cif
正在转换mp-30177.cif
正在转换mp-30189.cif
正在转换mp-30602.cif
正在转换mp-30889.cif
正在转换mp-30902.cif
正在转换mp-30903.cif
正在转换mp-30907.cif
正在转换mp-30985.cif
正在转换mp-31017.cif
正在转换mp-31093.cif
正在转换mp-31094.cif
正在转换mp-31143.cif
正在转换mp-31209.cif
正在转换mp-31219.cif
正在转换mp-31362.cif
正在转换mp-31411.cif
正在转换mp-31462.cif
正在转换mp-31467.cif
正在转换mp-31515.cif
正在转换mp-31529.cif
正在转换mp-31628.cif
正在转换mp-31632.cif
正在转换mp-31793.cif
正在转换mp-31801.cif
正在转换mp-31906.cif
正在转换mp-31927.cif
正在转换mp-32011.cif
正在转换mp-32328.cif
正在转换mp-32329.cif
正在转换mp-32432.cif
正在转换mp-32679.cif
正在转换mp-32761.cif
正在转换mp-32813.cif
正在转换mp-32861.cif
正在转换mp-32905.cif
正在转换mp-32927.cif
正在转换mp-32939.cif
正在转换mp-32959.cif
正在转换mp-33056.cif
正在转换mp-33216.cif
正在转换mp-33312.cif
正在转换mp-33320.cif
正在转换mp-33332.cif
正在转换mp-33339.cif
正在转换mp-33392.cif
正在转换mp-33461.cif
正在转换mp-33546.cif
正在转换mp-33560.cif
正在转换mp-33658.cif
正在转换mp-33737.cif
正在转换mp-33990.cif
正在转换mp-34009.cif
正在转换mp-34042.cif
正在转换mp-34175.cif
正在转换mp-34433.cif
正在转换mp-34765.cif
正在转换mp-34987.cif
正在转换mp-35143.cif
正在转换mp-35208.cif
正在转换mp-35555.cif
正在转换mp-35612.cif
正在转换mp-35687.cif
正在转换mp-546707.cif
正在转换mp-546787.cif
正在转换mp-546810.cif
正在转换mp-546877.cif
正在转换mp-546910.cif
正在转换mp-546920.cif
正在转换mp-546973.cif
正在转换mp-547017.cif
正在转换mp-547029.cif
正在转换mp-547622.cif
正在转换mp-547898.cif
正在转换mp-547956.cif
正在转换mp-548403.cif

正在转换mp-548598.cif
正在转换mp-548658.cif
正在转换mp-548691.cif
正在转换mp-548824.cif
正在转换mp-549166.cif
正在转换mp-549207.cif
正在转换mp-549308.cif
正在转换mp-549389.cif
正在转换mp-549565.cif
正在转换mp-549590.cif
正在转换mp-549687.cif
正在转换mp-549706.cif
正在转换mp-549869.cif
正在转换mp-549970.cif
正在转换mp-550008.cif
正在转换mp-550314.cif
正在转换mp-550320.cif
正在转换mp-550433.cif
正在转换mp-550436.cif
正在转换mp-550474.cif
正在转换mp-550498.cif
正在转换mp-550506.cif
正在转换mp-550579.cif
正在转换mp-550593.cif
正在转换mp-550679.cif
正在转换mp-550759.cif
正在转换mp-550893.cif
正在转换mp-550895.cif
正在转换mp-550908.cif
正在转换mp-551135.cif
正在转换mp-551176.cif
正在转换mp-551267.cif
正在转换mp-551283.cif
正在转换mp-551437.cif
正在转换mp-551561.cif
正在转换mp-551601.cif
正在转换mp-551690.cif
正在转换mp-551702.cif
正在转换mp-551736.cif
正在转换mp-551740.cif
正在转换mp-551741.cif
正在转换mp-551758.cif
正在转换mp-551798.cif
正在转换mp-551848.cif
正在转换mp-551886.cif
正在转换mp-551918.cif
正在转换mp-552056.cif
正在转换mp-552169.cif
正在转换mp-552176.cif
正在转换mp-552200.cif
正在转换mp-552552.cif
正在转换mp-552588.cif
正在转换mp-552623.cif
正在转换mp-552674.cif
正在转换mp-552941.cif
正在转换mp-552966.cif
正在转换mp-553432.cif
正在转换mp-553875.cif
正在转换mp-553881.cif
正在转换mp-553932.cif
正在转换mp-553939.cif
正在转换mp-553942.cif
正在转换mp-553946.cif
正在转换mp-553952.cif
正在转换mp-553990.cif
正在转换mp-553991.cif
正在转换mp-554025.cif
正在转换mp-554032.cif
正在转换mp-554048.cif
正在转换mp-554051.cif
正在转换mp-554059.cif
正在转换mp-554072.cif
正在转换mp-554082.cif
正在转换mp-554109.cif
正在转换mp-554116.cif
正在转换mp-554134.cif
正在转换mp-554139.cif
正在转换mp-554140.cif
正在转换mp-554159.cif
正在转换mp-554201.cif
正在转换mp-554212.cif
正在转换mp-554243.cif
正在转换mp-554245.cif
正在转换mp-554320.cif
正在转换mp-554328.cif
正在转换mp-554352.cif
正在转换mp-554355.cif
正在转换mp-554396.cif
正在转换mp-554397.cif
正在转换mp-554451.cif
正在转换mp-554457.cif
正在转换mp-554462.cif
正在转换mp-554465.cif
正在转换mp-554479.cif
正在转换mp-554528.cif
正在转换mp-554553.cif
正在转换mp-554593.cif
正在转换mp-554601.cif
正在转换mp-554602.cif
正在转换mp-554609.cif
正在转换mp-554623.cif
正在转换mp-554626.cif
正在转换mp-554638.cif
正在转换mp-554645.cif
正在转换mp-554649.cif
正在转换mp-554663.cif
正在转换mp-554665.cif
正在转换mp-554669.cif
正在转换mp-554675.cif
正在转换mp-554678.cif
正在转换mp-554688.cif
正在转换mp-554702.cif
正在转换mp-554719.cif
正在转换mp-554722.cif
正在转换mp-554751.cif
正在转换mp-554758.cif
正在转换mp-554766.cif
正在转换mp-554768.cif
正在转换mp-554769.cif
正在转换mp-554781.cif
正在转换mp-554813.cif
正在转换mp-554818.cif
正在转换mp-554826.cif
正在转换mp-554827.cif
正在转换mp-554831.cif
正在转换mp-554845.cif
正在转换mp-554867.cif
正在转换mp-554868.cif
正在转换mp-554885.cif
正在转换mp-554941.cif
正在转换mp-554948.cif
正在转换mp-554949.cif
正在转换mp-554959.cif
正在转换mp-554971.cif
正在转换mp-554973.cif
正在转换mp-554994.cif
正在转换mp-555001.cif
正在转换mp-555014.cif
正在转换mp-555021.cif
正在转换mp-555036.cif
正在转换mp-555044.cif
正在转换mp-555064.cif
正在转换mp-555066.cif
正在转换mp-555069.cif
正在转换mp-555077.cif
正在转换mp-555098.cif
正在转换mp-555147.cif
正在转换mp-555156.cif
正在转换mp-555159.cif
正在转换mp-555170.cif
正在转换mp-555202.cif
正在转换mp-555251.cif
正在转换mp-555256.cif
正在转换mp-555257.cif
正在转换mp-555267.cif
正在转换mp-555271.cif
正在转换mp-555296.cif
正在转换mp-555320.cif
正在转换mp-555345.cif
正在转换mp-555369.cif
正在转换mp-555370.cif
正在转换mp-555391.cif
正在转换mp-555425.cif
正在转换mp-555458.cif
正在转换mp-555464.cif
正在转换mp-555474.cif
正在转换mp-555477.cif
正在转换mp-555483.cif
正在转换mp-555491.cif
正在转换mp-555506.cif
正在转换mp-555520.cif
正在转换mp-555529.cif
正在转换mp-555544.cif
正在转换mp-555552.cif
正在转换mp-555561.cif
正在转换mp-555569.cif
正在转换mp-555574.cif
正在转换mp-555585.cif
正在转换mp-555586.cif
正在转换mp-555676.cif
正在转换mp-555716.cif
正在转换mp-555731.cif
正在转换mp-555735.cif
正在转换mp-555740.cif
正在转换mp-555785.cif
正在转换mp-555792.cif
正在转换mp-555843.cif
正在转换mp-555857.cif
正在转换mp-556004.cif
正在转换mp-556005.cif
正在转换mp-556027.cif
正在转换mp-556034.cif
正在转换mp-556045.cif
正在转换mp-556066.cif
正在转换mp-556084.cif
正在转换mp-556095.cif
正在转换mp-556111.cif
正在转换mp-556132.cif
正在转换mp-556161.cif
正在转换mp-556163.cif
正在转换mp-556164.cif
正在转换mp-556167.cif
正在转换mp-556176.cif
正在转换mp-556225.cif
正在转换mp-556242.cif
正在转换mp-556253.cif
正在转换mp-556284.cif
正在转换mp-556296.cif
正在转换mp-556353.cif
正在转换mp-556376.cif
正在转换mp-556395.cif
正在转换mp-556472.cif
正在转换mp-556498.cif
正在转换mp-556565.cif
正在转换mp-556646.cif
正在转换mp-556662.cif
正在转换mp-556757.cif
正在转换mp-556777.cif
正在转换mp-556788.cif
正在转换mp-556806.cif
正在转换mp-556815.cif
正在转换mp-556839.cif
正在转换mp-556843.cif
正在转换mp-556850.cif
正在转换mp-556856.cif
正在转换mp-556870.cif
正在转换mp-556872.cif
正在转换mp-556880.cif
正在转换mp-556888.cif
正在转换mp-556891.cif
正在转换mp-556892.cif
正在转换mp-556927.cif
正在转换mp-556961.cif
正在转换mp-556978.cif
正在转换mp-556985.cif
正在转换mp-556994.cif
正在转换mp-556995.cif
正在转换mp-557001.cif
正在转换mp-557032.cif
正在转换mp-557035.cif
正在转换mp-557054.cif
正在转换mp-557056.cif
正在转换mp-557070.cif
正在转换mp-557118.cif
正在转换mp-557125.cif
正在转换mp-557134.cif
正在转换mp-557137.cif
正在转换mp-557142.cif
正在转换mp-557146.cif
正在转换mp-557232.cif
正在转换mp-557233.cif
正在转换mp-557244.cif
正在转换mp-557251.cif
正在转换mp-557274.cif
正在转换mp-557320.cif
正在转换mp-557321.cif
正在转换mp-557328.cif
正在转换mp-557375.cif
正在转换mp-557450.cif
正在转换mp-557465.cif
正在转换mp-557466.cif
正在转换mp-557510.cif
正在转换mp-557515.cif
正在转换mp-557624.cif
正在转换mp-557653.cif
正在转换mp-557724.cif
正在转换mp-557737.cif
正在转换mp-557754.cif
正在转换mp-557825.cif
正在转换mp-557837.cif
正在转换mp-557861.cif
正在转换mp-557862.cif
正在转换mp-557865.cif
正在转换mp-557890.cif
正在转换mp-557914.cif
正在转换mp-27349.cif
正在转换mp-27388.cif
正在转换mp-27390.cif
正在转换mp-27437.cif
正在转换mp-27684.cif
正在转换mp-27688.cif
正在转换mp-27689.cif
正在转换mp-27698.cif
正在转换mp-27707.cif
正在转换mp-27714.cif
正在转换mp-27747.cif
正在转换mp-27752.cif
正在转换mp-27757.cif
正在转换mp-27758.cif
正在转换mp-27768.cif
正在转换mp-27769.cif
正在转换mp-27774.cif
正在转换mp-27782.cif
正在转换mp-27791.cif
正在转换mp-27821.cif
正在转换mp-27824.cif
正在转换mp-27851.cif
正在转换mp-27852.cif
正在转换mp-27853.cif
正在转换mp-27898.cif
正在转换mp-27904.cif
正在转换mp-27919.cif
正在转换mp-27927.cif
正在转换mp-27971.cif
正在转换mp-28007.cif
正在转换mp-28020.cif
正在转换mp-28022.cif
正在转换mp-28040.cif
正在转换mp-28123.cif
正在转换mp-28124.cif
正在转换mp-28160.cif
正在转换mp-28452.cif
正在转换mp-28542.cif
正在转换mp-28549.cif
正在转换mp-28562.cif
正在转换mp-28607.cif
正在转换mp-28614.cif
正在转换mp-28628.cif
正在转换mp-28629.cif
正在转换mp-28641.cif
正在转换mp-28661.cif
正在转换mp-28687.cif
正在转换mp-28710.cif
正在转换mp-28731.cif
正在转换mp-28770.cif
正在转换mp-28778.cif
正在转换mp-28827.cif
正在转换mp-28842.cif
正在转换mp-28863.cif
正在转换mp-28954.cif
正在转换mp-28968.cif
正在转换mp-28998.cif
正在转换mp-29005.cif
正在转换mp-29205.cif
正在转换mp-29239.cif
正在转换mp-29331.cif
正在转换mp-29341.cif
正在转换mp-29355.cif
正在转换mp-29501.cif
正在转换mp-29514.cif
正在转换mp-29515.cif
正在转换mp-29570.cif
正在转换mp-29343.cif
正在转换mp-29877.cif
正在转换mp-29937.cif
正在转换mp-29979.cif
正在转换mp-29982.cif
正在转换mp-30045.cif
正在转换mp-30060.cif
正在转换mp-30129.cif
正在转换mp-30151.cif
正在转换mp-30176.cif
正在转换mp-30209.cif
正在转换mp-30232.cif
正在转换mp-31011.cif
正在转换mp-31503.cif
正在转换mp-1029.cif
正在转换mp-1138.cif
正在转换mp-1201.cif
正在转换mp-1317.cif
正在转换mp-1367.cif
正在转换mp-1592.cif
正在转换mp-16366.cif
正在转换mp-19717.cif
正在转换mp-20194.cif
正在转换mp-20740.cif
正在转换mp-2231.cif
正在转换mp-23116.cif
正在转换mp-23193.cif
正在转换mp-2612.cif
正在转换mp-2758.cif
正在转换mp-2920.cif
正在转换mp-3614.cif
正在转换mp-408.cif
正在转换mp-504.cif
正在转换mp-541837.cif
正在转换mp-924129.cif
正在转换mp-938.cif
正在转换mp-978534.cif
正在转换mp-773747.cif
正在转换mp-773900.cif
正在转换mp-849938.cif
正在转换mp-850112.cif
正在转换mp-774141.cif
正在转换mp-774250.cif
正在转换mp-774353.cif
正在转换mp-774449.cif
正在转换mp-774609.cif
正在转换mp-774874.cif
正在转换mp-775041.cif
正在转换mp-775045.cif
正在转换mp-775051.cif
正在转换mp-775075.cif
正在转换mp-775077.cif
正在转换mp-775089.cif
正在转换mp-775092.cif
正在转换mp-775127.cif
正在转换mp-775135.cif
正在转换mp-775180.cif
正在转换mp-775200.cif
正在转换mp-775204.cif
正在转换mp-775235.cif
正在转换mp-775237.cif
正在转换mp-775343.cif
正在转换mp-775471.cif
正在转换mp-775518.cif
正在转换mp-775524.cif
正在转换mp-775540.cif
正在转换mp-775542.cif
正在转换mp-775605.cif
正在转换mp-775762.cif
正在转换mp-775922.cif
正在转换mp-17407.cif
正在转换mp-17708.cif
正在转换mp-2173.cif
正在转换mp-22231.cif
正在转换mp-24081.cif
正在转换mp-24097.cif
正在转换mp-24591.cif
正在转换mp-25643.cif
正在转换mp-27772.cif
正在转换mp-27880.cif
正在转换mp-27911.cif
正在转换mp-28846.cif
正在转换mp-29234.cif
正在转换mp-29555.cif
正在转换mp-30971.cif
正在转换mp-31013.cif
正在转换mp-31516.cif
正在转换mp-31621.cif
正在转换mp-32311.cif
正在转换mp-545481.cif
正在转换mp-554765.cif
正在转换mp-559650.cif
正在转换mp-560750.cif
正在转换mp-561493.cif
正在转换mp-567437.cif
正在转换mp-567471.cif
正在转换mp-567720.cif
正在转换mp-687234.cif
正在转换mp-761477.cif
正在转换mp-782689.cif
正在转换auid-03fec0c512bac318.cif
正在转换auid-05a68ed01a5b30c3.cif
正在转换auid-0683da26e7287939.cif
正在转换auid-076cc18d3c55cc12.cif
正在转换auid-0803adda26e9979d.cif
正在转换auid-082dad475e7458ba.cif
正在转换auid-08fddff07384ab0a.cif
正在转换auid-098e04ce83619270.cif
正在转换auid-0b6059082d2a7223.cif
正在转换auid-0b832a8494c17aa8.cif
正在转换auid-0cf6d1b30646a51a.cif
正在转换auid-0fddba3aba588b7e.cif
正在转换auid-100925ba172c32dd.cif
正在转换auid-10a3867a6e611bc4.cif
正在转换auid-1260a057535c3fca.cif
正在转换auid-14c8738be2c5fc11.cif
正在转换auid-15a097986b7bd004.cif
正在转换auid-1670e08e57751e37.cif
正在转换auid-16a983ce24974eb3.cif
正在转换auid-18b10b7ce314291f.cif
正在转换auid-18f67dbf0c0d1679.cif
正在转换auid-195d648041cfa604.cif
正在转换auid-19c47f300ee6bf7c.cif
正在转换auid-19e276dfa7ea0cda.cif
正在转换auid-1a8e7b7b5bf25a3b.cif
正在转换auid-1b04c23a20c9d8b1.cif
正在转换auid-1ccadd5aa16a1e16.cif
正在转换auid-1ec22e6288de6ac3.cif
正在转换auid-1eee76d3d225eeb8.cif
正在转换auid-207b5e1d48a78944.cif
正在转换auid-240ef1a12683b029.cif
正在转换auid-24bd027869ace399.cif
正在转换auid-26c7fbf94bf273be.cif
正在转换auid-29ada9d928c7f6e5.cif
正在转换auid-2a707b83714f6ad6.cif
正在转换auid-2a7e21e560cd7b69.cif
正在转换auid-2b2ce70ce231fb2f.cif
正在转换auid-2c66b3df8357f922.cif
正在转换auid-2d6050eeb3a348f0.cif
正在转换auid-2e838f5db1e948ea.cif
正在转换auid-2f3cf9110d84ce5e.cif
正在转换auid-321a9700892c1831.cif
正在转换auid-32ed97c3c63599db.cif
正在转换auid-32ef38a3e281cb9c.cif
正在转换auid-32f8a17621d51903.cif
正在转换auid-358425e7585e7270.cif
正在转换auid-38025cdad559ce5d.cif
正在转换auid-382a9f0aa73a7046.cif
正在转换auid-3a24c7c96bb32f2a.cif
正在转换auid-3a6f2bcc5301a8e4.cif
正在转换auid-3c44d87a2a962752.cif
正在转换auid-40717e3d7159037f.cif
正在转换auid-439622bf8124d854.cif
正在转换auid-445d82e9331ad9bd.cif
正在转换auid-4599bd1591d33dbb.cif
正在转换auid-46e921d4b2fc289d.cif
正在转换auid-489dce3d22c92c97.cif
正在转换auid-49ec49c5dfefae81.cif
正在转换auid-4c08eb436b19a25c.cif
正在转换auid-4cc41ca80be1f273.cif
正在转换auid-4cc6afbc7675c1b7.cif
正在转换auid-4f65dc0d8929995a.cif
正在转换auid-4f6d765ef6bdeb98.cif
正在转换auid-54d4a95f0c696527.cif
正在转换auid-57779bd8e87bf895.cif
正在转换auid-5780b92127724f5f.cif
正在转换auid-58e66e6bac95f4a2.cif
正在转换auid-59aa8a3bf6249207.cif
正在转换auid-5a187c8d8780c074.cif
正在转换auid-5b65fe5e75a86171.cif
正在转换auid-5ba9a572f843d1a7.cif

正在转换auid-5bf4946516d0fb98.cif
正在转换auid-5c573546a4b2ee4d.cif
正在转换auid-60bfcebab5884c75.cif
正在转换auid-65186a43b061c035.cif
正在转换auid-67a3796ffade08ed.cif
正在转换auid-69086bf64f788551.cif
正在转换auid-6a949e2275c6dcc3.cif
正在转换auid-6b1f0c7dab7cefa8.cif
正在转换auid-6c7266c4b1bd6514.cif
正在转换auid-6e748e9c72c3cd34.cif
正在转换auid-6ef15344dfaaecc6.cif
正在转换auid-6f948484d7a8281f.cif
正在转换auid-7022a4856a717be3.cif
正在转换auid-72211a89c04cc348.cif
正在转换auid-73d66c7119debc14.cif
正在转换auid-745943a327295213.cif
正在转换auid-763c96648fc02fb3.cif
正在转换auid-7e7515d4f30e5583.cif
正在转换auid-7f30422b3bb1e606.cif
正在转换auid-7f9394aee8b9c8da.cif
正在转换auid-7fe65ec76fbda62d.cif
正在转换auid-8085efd9718a0b17.cif
正在转换auid-829ff58f040b6094.cif
正在转换auid-82af6e0d8947f675.cif
正在转换auid-8358049021974337.cif
正在转换auid-842fd3c9afd84f2b.cif
正在转换auid-844ecf4f30764eff.cif
正在转换auid-88759a44d6581274.cif
正在转换auid-8c2729927d56398d.cif
正在转换auid-8e163f5c95afabe7.cif
正在转换auid-8fa3a6af4e33660b.cif
正在转换auid-90f8fb98d9d8d360.cif
正在转换auid-9128ee956441fa75.cif
正在转换auid-9247f8cfaae200fd.cif
正在转换auid-9305665ef511315c.cif
正在转换auid-95132812acd06f01.cif
正在转换auid-97347a1db57ee851.cif
正在转换auid-98cf795897c7c220.cif
正在转换auid-9901c0c0c5c0e2e4.cif
正在转换auid-9a9a86c849c4eb79.cif
正在转换auid-9c945c9aff2859af.cif
正在转换auid-9d0138e80b5dad47.cif
正在转换auid-9e88fd6db696df71.cif
正在转换auid-9ee0ad2df8095c37.cif
正在转换auid-a2b5de03bd40da00.cif
正在转换auid-a469eb2fd70a7ee6.cif
正在转换auid-a74417181febe863.cif
正在转换auid-a8dfae0cd7c48ffa.cif
正在转换auid-a90cd8872a3f333d.cif
正在转换auid-a93411409205b74f.cif
正在转换auid-aa63f8a0bdd90b2a.cif
正在转换auid-ac23863c5ddca7af.cif
正在转换auid-adee7a44bdbc8f30.cif
正在转换auid-ae5aafc194bc7418.cif
正在转换auid-aea224c3850a94f1.cif
正在转换auid-af52737689b30584.cif
正在转换auid-af935b6a1a84ce36.cif
正在转换auid-aff465dd7c319c10.cif
正在转换auid-b476964ae1d5c483.cif
正在转换auid-b486d07955990a30.cif
正在转换auid-b4e88005f5552dc5.cif
正在转换auid-b58bdaceebacfc98.cif
正在转换auid-b652221ff5797705.cif
正在转换auid-b78f9fd97c4185ee.cif
正在转换auid-b8b58dfad8fd3327.cif
正在转换auid-b990df8d6002ff44.cif
正在转换auid-bc89b605d5b79b3e.cif
正在转换auid-c3eb476ff512b434.cif
正在转换auid-c4874c9c352c7b06.cif
正在转换auid-c4c121ef3efe3454.cif
正在转换auid-c9bd52b4a1df59c6.cif
正在转换auid-cab00cb3a21d3065.cif
正在转换auid-cbdc77b9f4752b05.cif
正在转换auid-cd091c0e2c2e7357.cif
正在转换auid-cff93666edeb72a6.cif
正在转换auid-d0d3bf36b069d001.cif
正在转换auid-d47615464fc13683.cif
正在转换auid-d769615bc7f0fbbf.cif
正在转换auid-d81fe705e4f8b6bf.cif
正在转换auid-d88bed6bf0cdd5b4.cif
正在转换auid-da4c7ae4b9d13ffa.cif
正在转换auid-da77bbbb7ae0c767.cif
正在转换auid-dca6ae17d9ef0891.cif
正在转换auid-dcf44ad12ec955bd.cif
正在转换auid-ddb781150d3706f9.cif
正在转换auid-dfa625ed0a7e8b8e.cif
正在转换auid-e3a095e3638d0729.cif
正在转换auid-e3cb28329f720d9d.cif
正在转换auid-e4e6d7d5acaefbd8.cif
正在转换auid-e57b624c5d21be6e.cif
正在转换auid-e751377e399e581f.cif
正在转换auid-e810a6c38790649e.cif
正在转换auid-e92754e5bfebaa71.cif
正在转换auid-ec55a9470151b170.cif
正在转换auid-ecad71bcd8f3ed8b.cif
正在转换auid-ecc0c52076f16e43.cif
正在转换auid-ee5a5b16a51d240d.cif
正在转换auid-ef54da13758bd91b.cif
正在转换auid-f11a81f9dd5dd806.cif
正在转换auid-f25538422c969c5b.cif
正在转换auid-f2eb110d28652752.cif
正在转换auid-f36327d48d20a71a.cif
正在转换auid-f399edf2c4b9e273.cif
正在转换auid-f4c653733521c1eb.cif
正在转换auid-f4e7bf3d80ad3a02.cif
正在转换auid-f5e60fdd7c03a1d0.cif
正在转换auid-f622e1fae3e806c3.cif
正在转换auid-f641259adfac01de.cif
正在转换auid-f7620040ff7d7114.cif
正在转换auid-f87f1bc5bdc36bb2.cif
正在转换auid-f95b055be2ca6813.cif
正在转换auid-fa608d20989ef069.cif
正在转换auid-fab0d34361d01100.cif
正在转换auid-fc2455ebccfc5c79.cif
正在转换auid-fc3a2c49e0281fa2.cif
正在转换auid-fc93c02532a69346.cif
正在转换auid-fe5e7fb4c7192a2b.cif
正在转换auid-ff354e11b6061baa.cif
正在转换auid-ffaa3b58edf4336a.cif
正在转换auid-002d4c7bb9f089e3.cif
正在转换auid-0059706acecf5809.cif
正在转换auid-00f3042ad4d23232.cif
正在转换auid-00fccafc3f45cfc9.cif
正在转换auid-012d1273b2e8826e.cif
正在转换auid-01f2f0589c372ad0.cif
正在转换auid-022fe116842b0508.cif
正在转换auid-02f46c04c6d2f2ca.cif
正在转换auid-0307387d7f7ef84f.cif
正在转换auid-03cf31e52e5c22f0.cif
正在转换auid-03f276ac34cf1c8b.cif
正在转换auid-04ac1cd8c7064f18.cif
正在转换auid-04e492904b6e9abd.cif
正在转换auid-05635998770445e9.cif
正在转换auid-06002e105e92128c.cif
正在转换auid-067506e599625ce8.cif
正在转换auid-070576d6cd280b9b.cif
正在转换auid-075a8133a1d77f03.cif
正在转换auid-0831163c93fc5260.cif
正在转换auid-09f5503e08d08da1.cif
正在转换auid-0a2426a5c7e451aa.cif
正在转换auid-0b9c5a67a9a7550d.cif
正在转换auid-0b9eebdcc00c4d14.cif
正在转换auid-0be8c5e4383c71ab.cif
正在转换auid-0c3dd26d8712cbc3.cif
正在转换auid-0d1836d57cf05d86.cif
正在转换auid-0e8889e81808ca60.cif
正在转换auid-0eb33366d5d5b0f6.cif
正在转换auid-0fa6c5b00d4ae098.cif
正在转换auid-0fad223e4bbad709.cif
正在转换auid-0fafd6ce03dea9c5.cif
正在转换auid-102e34374905260a.cif
正在转换auid-10937e0cb020e7ad.cif
正在转换auid-11521b616a11a740.cif
正在转换auid-118b3feac326756d.cif
正在转换auid-123dc37c585b0191.cif
正在转换auid-1290ca258de8162a.cif
正在转换auid-13a4995d9dd91296.cif
正在转换auid-13d4addefe4ca6e5.cif
正在转换auid-13e85d131cdc5854.cif
正在转换auid-13f1b22abe0a25c3.cif
正在转换auid-147e8df9cc65d8fa.cif
正在转换auid-14bca5911ac710b3.cif
正在转换auid-14fff095da2a8e6b.cif
正在转换auid-159107f2ce76b170.cif
正在转换auid-15abb4e251e4e664.cif
正在转换auid-15de1d4160828e34.cif
正在转换auid-16b1dd27ca5ed066.cif
正在转换auid-16b5ff58a983f4c0.cif
正在转换auid-1833d147e6670957.cif
正在转换auid-19326ad0eca05464.cif
正在转换auid-193ecfeb9f487e67.cif
正在转换auid-197e9ba5c91e6eb4.cif
正在转换auid-19f16e19898c897d.cif
正在转换auid-19f8f0d0612c6071.cif
正在转换auid-1adcf5eec65c977c.cif
正在转换auid-1d2669bbe6cb5a85.cif
正在转换auid-1dbb531a78f2b1ca.cif
正在转换auid-1f7cc8bc3a048764.cif
正在转换auid-1fb4bc7c3dccc08a.cif
正在转换auid-20804ab14b3aeb2d.cif
正在转换auid-210e49f429c9d02e.cif
正在转换auid-2114850192fa70e4.cif
正在转换auid-213e6e1bc86e49c8.cif
正在转换auid-23a9719ef393dc14.cif
正在转换auid-23d49546bf47fde1.cif
正在转换auid-24fb712555cc0a88.cif
正在转换auid-25f1488f780e262c.cif
正在转换auid-261ffba4adb3c373.cif
正在转换auid-270f2b43092a9d9d.cif
正在转换auid-2878515cd0d44d2a.cif
正在转换auid-28f3095820996c69.cif
正在转换auid-2926997209056b43.cif
正在转换auid-29ad1b504a383ed5.cif
正在转换auid-2aea6266508a15f8.cif
正在转换auid-2b024ae2e0c0f113.cif
正在转换auid-2b7682ddc543feae.cif
正在转换auid-2c06b258bfc39967.cif
正在转换auid-2c351558cf5c6c1a.cif
正在转换auid-2dd9adcb15930992.cif
正在转换auid-2defbc5ca47dbc32.cif
正在转换auid-2f4442986b07d2f2.cif
正在转换auid-2fbc7e928d2e431c.cif
正在转换auid-2fedcbce2d6cf8bf.cif
正在转换auid-30fced5699ece685.cif
正在转换auid-3166a98569e34e4a.cif
正在转换auid-3399dc6ee4b906b6.cif
正在转换auid-339aa9c8ca195d32.cif
正在转换auid-339bc28a53407edd.cif
正在转换auid-3462a91aa455034e.cif
正在转换auid-35391744d6c62872.cif
正在转换auid-35a99ac7dd0875c0.cif
正在转换auid-362588d117c7e029.cif
正在转换auid-36f249867423c14e.cif
正在转换auid-3720f67da98d7ffd.cif
正在转换auid-373c417319c70003.cif
正在转换auid-398f6847099f8010.cif
正在转换auid-39ce8dd4f60ceb4a.cif
正在转换auid-39e9adae8d0ac6e9.cif
正在转换auid-3a709166bb315577.cif
正在转换auid-3a85f6850ac67aad.cif
正在转换auid-3ae3aad7d6bc257a.cif
正在转换auid-3ae6e6d271edde23.cif
正在转换auid-3bb5b0ddbf816325.cif
正在转换auid-3c29cfbed5a7ef90.cif
正在转换auid-3c42f54e425c4296.cif
正在转换auid-3c80d86600299ee7.cif
正在转换auid-3dd7caa058655992.cif
正在转换auid-3e36a73184d05946.cif
正在转换auid-3e397f67231ae04e.cif
正在转换auid-3f0721ff5c474b8f.cif
正在转换auid-3f0d72bfcb455c58.cif
正在转换auid-41e00f006168c010.cif
正在转换auid-4299169bdfa8c00c.cif
正在转换auid-44753fbbae332202.cif
正在转换auid-44a5c71a70fc7b8a.cif
正在转换auid-45a22fff738a5f7a.cif
正在转换auid-4601e21f755b2371.cif
正在转换auid-463d86602ffda551.cif
正在转换auid-47512f19fd213888.cif
正在转换auid-48e9c4ced87c2bc3.cif
正在转换auid-48ea29c8355d0bcb.cif
正在转换auid-4923fc32022a2a71.cif
正在转换auid-4935d13c102a9400.cif
正在转换auid-4a0b819763a35f0c.cif
正在转换auid-4ad3941704c00fd3.cif
正在转换auid-4aeb5944ab134c21.cif
正在转换auid-4c0add21464973c7.cif
正在转换auid-4c2cccf92c4bf909.cif
正在转换auid-4c304cd6c9f076fe.cif
正在转换auid-4c88dd88102b40f0.cif
正在转换auid-4df1d4b0c6666833.cif
正在转换auid-4e3e0fd3ac0575fb.cif
正在转换auid-4e46582794dd99f6.cif
正在转换auid-4eab805aab5ad3eb.cif
正在转换auid-4ec5eac6611c2ebc.cif
正在转换auid-4ed7999d982bd1ae.cif
正在转换auid-4fc5826a9b125338.cif
正在转换auid-4ff2589e11cacd8f.cif
正在转换auid-5019ecb2ff110ba4.cif
正在转换auid-508028becbbd7b7c.cif
正在转换auid-5095a93845afb303.cif
正在转换auid-52f1f96152837fbe.cif
正在转换auid-5318e80e2b4b1429.cif
正在转换auid-539ced2f100bd4cc.cif
正在转换auid-54e13589c17318a0.cif
正在转换auid-559e6ba1a2342067.cif
正在转换auid-56153e7b9c9f981e.cif
正在转换auid-574c461c3108c0aa.cif
正在转换auid-57c70ab6b6abce31.cif
正在转换auid-584e32dc1a840c4e.cif
正在转换auid-58a8ce9ce38dd240.cif
正在转换auid-58b25c4f1e9becf0.cif
正在转换auid-58f6b346b7be1eac.cif
正在转换auid-5a2927c6f1c5763e.cif
正在转换auid-5a55bcceac7692c2.cif
正在转换auid-5a7e8acc79612c54.cif
正在转换auid-5e36116f011e67bc.cif
正在转换auid-5f43edd149b9b57a.cif
正在转换auid-6153773305fe7f52.cif
正在转换auid-64c501e65fb0417c.cif
正在转换auid-6505043484eb283d.cif
正在转换auid-65f92f7df0edf923.cif
正在转换auid-67f4fd087f108e46.cif
正在转换auid-68f7883548b0a563.cif
正在转换auid-68ffb3fd295be6d7.cif

正在转换auid-6a07a4c0fa21b6ce.cif
正在转换auid-6a2ecef24e000f73.cif
正在转换auid-6af8bbb13200e24d.cif
正在转换auid-6e6a154b6dc00650.cif
正在转换auid-6ea18cda1db70a64.cif
正在转换auid-701150b50c6b654a.cif
正在转换auid-704853530eae2f6a.cif
正在转换auid-7593bdbfbdc87fef.cif
正在转换auid-78a8e81f9e5510e2.cif
正在转换auid-79651bf48cb62b55.cif
正在转换auid-7b34a6baf43d9c86.cif
正在转换auid-7bb003367536a8bd.cif
正在转换auid-7c440f3a8ffd2d85.cif
正在转换auid-7eb2a4def34b5f41.cif
正在转换auid-7ed41328aab999d7.cif
正在转换auid-7f4703506ba20a7d.cif
正在转换auid-7f80dfbfaee7b273.cif
正在转换auid-80c0b63de13d7982.cif
正在转换auid-8137d12b7e89953e.cif
正在转换auid-816fff491461ded3.cif
正在转换auid-82c2708b3b065b21.cif
正在转换auid-841528eb09177f92.cif
正在转换auid-8c4b50de046e30f3.cif
正在转换auid-8ca8ef9a71d34360.cif
正在转换auid-8cccd8ff8d42664e.cif
正在转换auid-8d972632d0b6de5f.cif
正在转换auid-8e155fad5de45ca7.cif
正在转换auid-8fac56df40fcce68.cif
正在转换auid-9051fd353611add8.cif
正在转换auid-90bb44f4f372f69e.cif
正在转换auid-932ae9c0f36ef16f.cif
正在转换auid-93e9b4cb5a618729.cif
正在转换auid-955f0a490e49ce19.cif
正在转换auid-9642deded5535cee.cif
正在转换auid-96e9d57d67de9ed7.cif
正在转换auid-97d41858336a2e6b.cif
正在转换auid-9a7dbf7c8eaba4a3.cif
正在转换auid-9a8865e0ae1a44cc.cif
正在转换auid-9a90b59c22baaa87.cif
正在转换auid-9abd8cb6aa45d78d.cif
正在转换auid-9c57dde313780d63.cif
正在转换auid-9c65d32acb87fce8.cif
正在转换auid-9d3a026c64f73021.cif
正在转换auid-9d55223c92757ffb.cif
正在转换auid-9db8b7f4aeae57b5.cif
正在转换auid-9ea672dac8dae1fb.cif
正在转换auid-9eaa8aa1b5d45a15.cif
正在转换auid-9ec5dfad23fc444c.cif
正在转换auid-9ec9a803e7d35258.cif
正在转换auid-9f396c10cf2ab153.cif
正在转换auid-9f4796bc0e0c0844.cif
正在转换auid-9f83158132a6810b.cif
正在转换auid-9f9938ee0b3f4d72.cif
正在转换auid-9fd86cf37ab1b4ff.cif
正在转换auid-a00b84c3567a0a88.cif
正在转换auid-a0d3c94b7eca9b34.cif
正在转换auid-a523615f5b2c816b.cif
正在转换auid-a58451350de5cfa7.cif
正在转换auid-a62316c28211f271.cif
正在转换auid-a6f38dc4d94bc565.cif
正在转换auid-a73aca30cc76a816.cif
正在转换auid-a82345a07e3ab5b0.cif
正在转换auid-a86c713f574eb54d.cif
正在转换auid-a8e7883e4bbdf233.cif
正在转换auid-a9050572f1e2d058.cif
正在转换auid-a994acba34b5b46f.cif
正在转换auid-ab1dcf9a2c4a805f.cif
正在转换auid-ab72697d06ad0e06.cif
正在转换auid-ac58b49bd43db641.cif
正在转换auid-ad7962569075640a.cif
正在转换auid-adc79acc430f3a4f.cif
正在转换auid-ae8f505a690d35c5.cif
正在转换auid-aed194b9b2ef3fb8.cif
正在转换auid-af7a893fe7fabf29.cif
正在转换auid-b021b009924d0089.cif
正在转换auid-b0cd6bc2b58bb6d6.cif
正在转换auid-b18d14b1d7fb25fc.cif
正在转换auid-b1d665b7615c8c60.cif
正在转换auid-b1f85bb2671bbacb.cif
正在转换auid-b44d2690aff294db.cif
正在转换auid-b47b2ba03b9c0286.cif
正在转换auid-b523cecdd934b116.cif
正在转换auid-b62202df123e7708.cif
正在转换auid-b88a7640ac4cb72a.cif
正在转换auid-b978a07ef71bc858.cif
正在转换auid-b9eec334da523c25.cif
正在转换auid-ba7d764992eda0e0.cif
正在转换auid-babd68b0c02caa9f.cif
正在转换auid-bae3770d49059a29.cif
正在转换auid-bb30cc5c819b3550.cif
正在转换auid-bb50e7dcb660ead4.cif
正在转换auid-bc08d31d0d58a90c.cif
正在转换auid-bc0ec32103325e32.cif
正在转换auid-bc321ac79045193f.cif
正在转换auid-bd34921fb1e150dc.cif
正在转换auid-bd3cbc1b144451cb.cif
正在转换auid-bd5301d5da8dd297.cif
正在转换auid-bd9931e9edce7537.cif
正在转换auid-be94679aa019e711.cif
正在转换auid-bfce06a926282138.cif
正在转换auid-c19f78ee66774928.cif
正在转换auid-c2717c26fa92767a.cif
正在转换auid-c2b401b4334f3d1c.cif
正在转换auid-c2cf3c8b77413143.cif
正在转换auid-c349acd8e3fe7815.cif
正在转换auid-c3a8a0c86c1ddd36.cif
正在转换auid-c3c2cd9ae9f27012.cif
正在转换auid-c3d010f8be054251.cif
正在转换auid-c43daad53fef117b.cif
正在转换auid-c4571f7d8562a493.cif
正在转换auid-c53128090a1ac095.cif
正在转换auid-c54a9af6b124ac02.cif
正在转换auid-c5ae94b92d3bfb8c.cif
正在转换auid-c67a2145f0aadccf.cif
正在转换auid-c692b87d8d293eca.cif
正在转换auid-c6fad31b6f0ff135.cif
正在转换auid-c71cea1669df1c89.cif
正在转换auid-c789751652cd9608.cif
正在转换auid-c9a7df601372ac8e.cif
正在转换auid-c9de308749af9fe6.cif
正在转换auid-ca5609a8710ba652.cif
正在转换auid-cb2d02cf1151021c.cif
正在转换auid-cb39ec8412adc71c.cif
正在转换auid-cb8ed69f97d43f50.cif
正在转换auid-cba4b6199b8df60d.cif
正在转换auid-cc1feda5df533b5b.cif
正在转换auid-cca16069a81e962e.cif
正在转换auid-cca31c4ef3abd326.cif
正在转换auid-d09c554dec422310.cif
正在转换auid-d23cab2d2cdcc55c.cif
正在转换auid-d2520891ea83dbe7.cif
正在转换auid-d3063b6ec12d1f99.cif
正在转换auid-d348e0fe0d2fd812.cif
正在转换auid-d45327fe7af0d2b4.cif
正在转换auid-d5928a885a1e5d50.cif
正在转换auid-d5d9110a89136bfe.cif
正在转换auid-d5dfe8792cd25f46.cif
正在转换auid-d87ec32af4e54054.cif
正在转换auid-d92b19138fd11235.cif
正在转换auid-d9b52fd9be355955.cif
正在转换auid-daae53fb5ef5b143.cif
正在转换auid-db1332be1aa6c233.cif
正在转换auid-db25d510c106c8a6.cif
正在转换auid-dc00715b794ac2f7.cif
正在转换auid-dc4ad86e0fd9f524.cif
正在转换auid-dd8aa771037c855d.cif
正在转换auid-dda0f5150a82671f.cif
正在转换auid-df7e16c188e4e2d7.cif
正在转换auid-dfb538f160f33c79.cif
正在转换auid-e152dd46a2c1a718.cif
正在转换auid-e17d9ee3ac4e6b84.cif
正在转换auid-e21a61c319e3b86f.cif
正在转换auid-e3b199e105d4def0.cif
正在转换auid-e41e7f3b5fd47e88.cif
正在转换auid-e48338f55fcb5a7f.cif
正在转换auid-e4921a75d5621c35.cif
正在转换auid-e4e79495e172bf14.cif
正在转换auid-e53604abe2a3df26.cif
正在转换auid-e5b38018c9f50e0f.cif
正在转换auid-e6c62c898db7cf5e.cif
正在转换auid-e73e5e26c4d3307e.cif
正在转换auid-e785eb4898e32b70.cif
正在转换auid-ea54b898d1f3aa10.cif
正在转换auid-ebafc104f1ea7ca5.cif
正在转换auid-ebb9c020336c841a.cif
正在转换auid-ec436ce724747a8b.cif
正在转换auid-ec58c4029cdc72f3.cif
正在转换auid-ecf2a6e21f055818.cif
正在转换auid-ee8e50fc84dc8b9a.cif
正在转换auid-f05fdfe7d4a18b90.cif
正在转换auid-f0ca3eb35cdb581b.cif
正在转换auid-f161a85a51e343f6.cif
正在转换auid-f253ce682e43c99f.cif
正在转换auid-f2ee31f9b9df77f7.cif
正在转换auid-f44806e91a3bfcc9.cif
正在转换auid-f63056ef75897310.cif
正在转换auid-f7cbb581fd98e8b8.cif
正在转换auid-f890a71dfb4b4832.cif
正在转换auid-f900d4a5aaf7351c.cif
正在转换auid-f90129ce7f9ceea2.cif
正在转换auid-f927853acbe4cdb6.cif
正在转换auid-f94cbd188cf3997a.cif
正在转换auid-fb09e50ad334f6c6.cif
正在转换auid-fb1f1a28dac571e2.cif
正在转换auid-fc86d3e03c940d65.cif
正在转换auid-fcf5a8d99245d70c.cif
正在转换auid-fd17bab66422916d.cif
正在转换auid-fe388d7223d5b386.cif
正在转换auid-ff24b43d03428e12.cif
正在转换auid-07fa6136ca0c0dc9.cif
正在转换auid-0a97559689e723da.cif
正在转换auid-0c5442db8e98e6f5.cif
正在转换auid-0d824de6ca67f350.cif
正在转换auid-0e5b845393a048bc.cif
正在转换auid-117ad2eb9730801f.cif
正在转换auid-1ce22d99656f7fe9.cif
正在转换auid-1e44d386be1b3bf8.cif
正在转换auid-20a15b411e3967a4.cif
正在转换auid-210e87a8213b6613.cif
正在转换auid-21152ba439c4120c.cif
正在转换auid-217586ea736f24f5.cif
正在转换auid-2256a5907aca2967.cif
正在转换auid-23fcdf13d9f5402b.cif
正在转换auid-2675d5d311246267.cif
正在转换auid-294c823f8471065d.cif
正在转换auid-2b66a8d7529d78f4.cif
正在转换auid-2e35fe1614a089f0.cif
正在转换auid-30a22b0903ae6d94.cif
正在转换auid-3704f71ac11b6b90.cif
正在转换auid-39035f9c02097334.cif
正在转换auid-399ba2cefa6c5d91.cif
正在转换auid-3e584362d5c3cdf6.cif
正在转换auid-3eaf68dd483bf4f4.cif
正在转换auid-3f7f56578188a4ec.cif
正在转换auid-48636ce97bce5c11.cif
正在转换auid-4bb67398aa8c1fe3.cif
正在转换auid-4ddc7fe387cb8e04.cif
正在转换auid-4e2bece43e1642d9.cif
正在转换auid-4f8f208fcb6b4c84.cif
正在转换auid-50d15abcc5f123a4.cif
正在转换auid-518df3c886cc21e0.cif
正在转换auid-51cee402e6ec27e7.cif
正在转换auid-53550f2afa49e3a6.cif
正在转换auid-53c47ef938a4a27d.cif
正在转换auid-53d315ab6129c247.cif
正在转换auid-543084aab5436b29.cif
正在转换auid-550853e0c665eed2.cif
正在转换auid-550fdac275587b1f.cif
正在转换auid-55281b2cf38596fa.cif
正在转换auid-5cdcb4d2b9081058.cif
正在转换auid-5f2cb68de972fc42.cif
正在转换auid-61c6e05f0d993d89.cif
正在转换auid-6237c8b4331d4da7.cif
正在转换auid-64938400f113294c.cif
正在转换auid-670b30d241f30b23.cif
正在转换auid-6f592815bdce5be3.cif
正在转换auid-72f1654c5977a507.cif
正在转换auid-731af777e331f205.cif
正在转换auid-73c93606507bc21f.cif
正在转换auid-7de28b9823374023.cif
正在转换auid-7ed9767b5b0b9787.cif
正在转换auid-805cf4b4df17bcc8.cif
正在转换auid-82c1c9b180336e46.cif
正在转换auid-8aa24605d1c8b0a5.cif
正在转换auid-8ae4f5f0368a5602.cif
正在转换auid-8cc76b7553174982.cif
正在转换auid-8fc36983eb169e01.cif
正在转换auid-904e5950bdb8ce93.cif
正在转换auid-97077ad09ea36e11.cif
正在转换auid-9a8b71ab6e71cc3e.cif
正在转换auid-a2d5ed4c4c004e80.cif
正在转换auid-a373ff1f27ae5a6f.cif
正在转换auid-a53ad6a58b2af370.cif
正在转换auid-a8c4a17743126012.cif
正在转换auid-a96b9756e3a48fa7.cif
正在转换auid-acef3f20f51c8862.cif
正在转换auid-ad8c5390167aea3c.cif
正在转换auid-b0389a237a2fa81a.cif
正在转换auid-b04eeaed0da8ea2e.cif
正在转换auid-b367a6e276c61372.cif
正在转换auid-b461e6dc75ff9668.cif
正在转换auid-b713692bb8847fdb.cif
正在转换auid-b91c4a3212a1039f.cif
正在转换auid-b983fb596ec49ad8.cif
正在转换auid-bc77dafe6d7d59ac.cif
正在转换auid-bf6537ac153cd273.cif
正在转换auid-bfc278ef7f5a04c5.cif
正在转换auid-bfc4807c12448d46.cif
正在转换auid-c14432408fef8fa4.cif
正在转换auid-c2a16935a0102341.cif
正在转换auid-c2a8c0d1eddbcabb.cif
正在转换auid-c34d4af56aa1d173.cif
正在转换auid-ceb0647b7d7e2449.cif
正在转换auid-cf122f6e75dcae03.cif
正在转换auid-d22852ce9b6149ea.cif
正在转换auid-d46984d968de8f46.cif
正在转换auid-dbb3593fa38e6dae.cif
正在转换auid-dfcd0ae848f85314.cif
正在转换auid-e2eb4e902948efbc.cif
正在转换auid-e524fd80aed3f609.cif
正在转换auid-e6720214f662b898.cif
正在转换auid-e69760f264762bd2.cif
正在转换auid-e726903c112b6a8f.cif
正在转换auid-ebf796aa5f553604.cif
正在转换auid-ed271f1de35b0bf4.cif
正在转换auid-ed8e955d1e653983.cif
正在转换auid-f01f633b05ce1f7e.cif
正在转换auid-f0fa8ca03c10dae9.cif
正在转换auid-f29a5b2f91cf10db.cif
正在转换auid-f3c620c207ee75a7.cif
正在转换auid-f3ca6f7d61369a45.cif
正在转换auid-f43fc3e4e7f71b7a.cif
正在转换auid-f5361db68f3c3b42.cif
正在转换auid-f776c228b2fc41fe.cif
正在转换auid-fbb3ad4c7b256fec.cif
正在转换auid-fd963afd88c88307.cif
正在转换auid-ffb784f7e36f6fdc.cif
正在转换auid-000020b00f104aa3.cif
正在转换auid-007ee12a9e7f4435.cif
正在转换auid-00deab59ffec9a7c.cif

正在转换auid-01b090647a84c57b.cif
正在转换auid-020d2830e16427d3.cif
正在转换auid-026677e2ec67f7de.cif
正在转换auid-0305b4d9de320bdf.cif
正在转换auid-0731b0c9fa95dc41.cif
正在转换auid-07bde2f3accdd54e.cif
正在转换auid-08a4b8f5e5ab2bb8.cif
正在转换auid-08a90c67762de1f9.cif
正在转换auid-09261cbdfe28997d.cif
正在转换auid-0b3e3fa7c8352c77.cif
正在转换auid-0b6726cadc3374cc.cif
正在转换auid-0d219391efdf3ea3.cif
正在转换auid-0dd5dfe7390def0d.cif
正在转换auid-0f1660a0572e5e45.cif
正在转换auid-0f5e30a5732fd5e8.cif
正在转换auid-0fd1e0cf8d171d64.cif
正在转换auid-0fd20cf5eb963639.cif
正在转换auid-118cee95a95b6c66.cif
正在转换auid-11e80fa7a8d66990.cif
正在转换auid-11fc7b2b8362eaee.cif
正在转换auid-126cccf8d4841563.cif
正在转换auid-132bc7b3fe7922d1.cif
正在转换auid-1426073e589f1343.cif
正在转换auid-164b46c19888db4b.cif
正在转换auid-16b2be77a7cb8b6c.cif
正在转换auid-1766394b418b4868.cif
正在转换auid-17683b81cb25009f.cif
正在转换auid-176b542c04647d09.cif
正在转换auid-1ad2842e4456bb23.cif
正在转换auid-1c57a1ec702c6f43.cif
正在转换auid-1ca9c9280582ca96.cif
正在转换auid-1fa12d18173cd2c4.cif
正在转换auid-1fda4e3f87b0b99c.cif
正在转换auid-21acfa143cab3095.cif
正在转换auid-228e718e55b4a44f.cif
正在转换auid-24cf9100d3d2a129.cif
正在转换auid-25141ba1a756f99b.cif
正在转换auid-252475a167bdc9b1.cif
正在转换auid-25f87875ab0b8562.cif
正在转换auid-27efad8b2a20d608.cif
正在转换auid-27f8ee313e77474b.cif
正在转换auid-287fdaab52565869.cif
正在转换auid-297b6105e105572c.cif
正在转换auid-2db1fa0d22fa5c32.cif
正在转换auid-2dbf51c4a0cec8d7.cif
正在转换auid-2fdfd285fb55146e.cif
正在转换auid-303d4c1390f8981d.cif
正在转换auid-30fed8a3f9f59dfb.cif
正在转换auid-3113bb672a4f3693.cif
正在转换auid-31852e526eaf79ba.cif
正在转换auid-31bb129a01f6861f.cif
正在转换auid-3603d107db6eaf35.cif
正在转换auid-3765c15d0e7060f0.cif
正在转换auid-37ecb9a7c72dc854.cif
正在转换auid-38aed9320f1aef7b.cif
正在转换auid-38f5f85759ea52ca.cif
正在转换auid-39d91c7b5b9dd5fa.cif
正在转换auid-39e0bb8ba259c279.cif
正在转换auid-3a78ea29bb45ae5d.cif
正在转换auid-3b8cd87c1a9b7bfb.cif
正在转换auid-3c42218a73305ebe.cif
正在转换auid-3d418651415b9794.cif
正在转换auid-3d7f3e84eb56b09d.cif
正在转换auid-3e2f8ae314a3befe.cif
正在转换auid-3f8e80d961f0914d.cif
正在转换auid-41c5df1609bd5c6d.cif
正在转换auid-4207891efda442a9.cif
正在转换auid-42443d48c40dab50.cif
正在转换auid-4283c895c5f4c83e.cif
正在转换auid-4343a9fea4576ff3.cif
正在转换auid-434620b50f16fa80.cif
正在转换auid-435d5f8e3293d0b7.cif
正在转换auid-45780b505f4e4864.cif
正在转换auid-46ab09d79e52588b.cif
正在转换auid-47964f0f94e3b859.cif
正在转换auid-48344c402f44fa42.cif
正在转换auid-4c030b9e635340d9.cif
正在转换auid-4cdc27d08297839c.cif
正在转换auid-4e288d6261c8f80c.cif
正在转换auid-4e8f4d9e7ddd7d17.cif
正在转换auid-50dbf63cbe8daf30.cif
正在转换auid-52c07a59b01e1c1a.cif
正在转换auid-52eeb810743d8fda.cif
正在转换auid-54cd3a271354a8bb.cif
正在转换auid-557bbb06987c7b90.cif
正在转换auid-565e6b5f0401a973.cif
正在转换auid-5777749a5eb996a3.cif
正在转换auid-578147a0b4eca0df.cif
正在转换auid-58a4f9f29b3c7b18.cif
正在转换auid-5958f9d7c3ba34e3.cif
正在转换auid-5aa1fd306d691642.cif
正在转换auid-5b8c072fa5781ab1.cif
正在转换auid-5b98b587c6f8fe72.cif
正在转换auid-5c517a72816ef139.cif
正在转换auid-5d0a25f149d68b28.cif
正在转换auid-5d1c57b9aca0385c.cif
正在转换auid-5e1b9e090ffa3af4.cif
正在转换auid-5e2f6515b3b57edb.cif
正在转换auid-5e66697941ccec70.cif
正在转换auid-5e9a238fbe242b26.cif
正在转换auid-5fd2bb5bfa5ac2d5.cif
正在转换auid-623e74391b80c40c.cif
正在转换auid-644904c8ba466537.cif
正在转换auid-64ccd3e4b645033d.cif
正在转换auid-65a2f3bbcf38a63b.cif
正在转换auid-65dda71d4e240891.cif
正在转换auid-65e18aedc40a3e1c.cif
正在转换auid-67693061f7877be2.cif
正在转换auid-67ef0d63d19da256.cif
正在转换auid-6989df2fdb39566e.cif
正在转换auid-6b9e53b40891e029.cif
正在转换auid-6e9a0a22c35d9cfe.cif
正在转换auid-6f9bb6078f088b2d.cif
正在转换auid-7128014402ebeb4b.cif
正在转换auid-71d949068f4e5fbc.cif
正在转换auid-72e2b1e95d557742.cif
正在转换auid-738b49c2ba08bf4d.cif
正在转换auid-73ea5f99a9270e5f.cif
正在转换auid-775ce2eb453fdade.cif
正在转换auid-775fe0cd3c08fce1.cif
正在转换auid-7847c6ed9819fe69.cif
正在转换auid-789fd28de8f94aa6.cif
正在转换auid-79531f2698e5879e.cif
正在转换auid-79c7522364db975f.cif
正在转换auid-79df385de0271c78.cif
正在转换auid-7dd914cce8697837.cif
正在转换auid-7dfd80fedb622f0e.cif
正在转换auid-7e861a78be57d73f.cif
正在转换auid-805f4e88592a5b47.cif
正在转换auid-84b95345281cc347.cif
正在转换auid-84de22deb0245db9.cif
正在转换auid-85590e6561e6fe51.cif
正在转换auid-85734206dc4295db.cif
正在转换auid-87eb1c3fca9d1960.cif
正在转换auid-8872c7ce9660b255.cif
正在转换auid-8ac5438d20e0af9f.cif
正在转换auid-8b222f9d7984203e.cif
正在转换auid-8be4e54937abd9b8.cif
正在转换auid-8cf51c5196ec1348.cif
正在转换auid-8dcce8b2ab64f9d0.cif
正在转换auid-8df1b0ffbacf27c0.cif
正在转换auid-8e21f3ee77729e0a.cif
正在转换auid-8fb8a77aa85869d7.cif
正在转换auid-909a7b63ed55ad94.cif
正在转换auid-911b2f1edf5bffaf.cif
正在转换auid-9151855ae54ddaeb.cif
正在转换auid-91c473c68355d2cc.cif
正在转换auid-92105bd02d5db2d7.cif
正在转换auid-94f6713d0a92392f.cif
正在转换auid-95575c1d16914e9c.cif
正在转换auid-962ade3462663eba.cif
正在转换auid-97ac12c2361a6181.cif
正在转换auid-9893817569d8a7b5.cif
正在转换auid-99546ae4724bce9e.cif
正在转换auid-99dba6d3e609e120.cif
正在转换auid-99fca5d13f7aaf33.cif
正在转换auid-9a32e9afc342d80f.cif
正在转换auid-9a9c57d3d831eb74.cif
正在转换auid-9b9e51d0468d8d34.cif
正在转换auid-9c1b7118b69ab3c2.cif
正在转换auid-9ca82e268d2a9203.cif
正在转换auid-9cbc0af1cea9c919.cif
正在转换auid-9d56c87f1da0dcb7.cif
正在转换auid-9d6d5b70ac38f17d.cif
正在转换auid-9e0dfdf4744c7743.cif
正在转换auid-a09de310e486fa15.cif
正在转换auid-a102d0bebbc66c02.cif
正在转换auid-a193724678f1f81e.cif
正在转换auid-a1f78bd74e2f04c3.cif
正在转换auid-a1fcb4a8ecefeeaf.cif
正在转换auid-a2abadbf22b919ec.cif
正在转换auid-a6216c1aaeed6ed2.cif
正在转换auid-a719eb8f82ffe08f.cif
正在转换auid-a8308077c3c0cf17.cif
正在转换auid-a8601f028ae6e626.cif
正在转换auid-a90c6c6c1814aa2f.cif
正在转换auid-a93750afd8b38644.cif
正在转换auid-a97a4a6ecbf6f3c4.cif
正在转换auid-a9ad252c1b29ae3d.cif
正在转换auid-ac25cf5f39e62ee9.cif
正在转换auid-ad6b468b231689a7.cif
正在转换auid-b161d69025859d43.cif
正在转换auid-b1787168070e09fa.cif
正在转换auid-b398a5314b2c1323.cif
正在转换auid-b3a0c66a95a2d8fb.cif
正在转换auid-b544fc1a144d846f.cif
正在转换auid-b6ec6c91b48c93a8.cif
正在转换auid-ba28eaa01c03dbf5.cif
正在转换auid-babee23f5bf72a14.cif
正在转换auid-bc2c922d0152e312.cif
正在转换auid-bd7260038727e9e7.cif
正在转换auid-bd946b8453c07eb3.cif
正在转换auid-c041a070b23a5c4a.cif
正在转换auid-c107e486c8c8d4a7.cif
正在转换auid-c18d55b9f24cba50.cif
正在转换auid-c2dc73ad13a444b8.cif
正在转换auid-c3019878238c6333.cif
正在转换auid-c30ecf8f6d4206eb.cif
正在转换auid-c37842a48a136a1b.cif
正在转换auid-c515a5d49015261a.cif
正在转换auid-c897b0e31b8c5e98.cif
正在转换auid-ca041aaf7f268358.cif
正在转换auid-cc29a796c8a2cb9b.cif
正在转换auid-cf4a126ce386be36.cif
正在转换auid-d0e905b50d1c8cf0.cif
正在转换auid-d2cf0486a76ea5cc.cif
正在转换auid-d4350bca67f26900.cif
正在转换auid-d6169d00211274ea.cif
正在转换auid-d8a1b3c58603314a.cif
正在转换auid-d9855a631d03fa9a.cif
正在转换auid-db9b7b530f5ae65b.cif
正在转换auid-dc6fbd92b0d29218.cif
正在转换auid-dc877e36999748ce.cif
正在转换auid-ddb9eb530ec397e1.cif
正在转换auid-dead181070a9821a.cif
正在转换auid-df029c2b2852cd6f.cif
正在转换auid-dfa06e81eb8e1660.cif
正在转换auid-e04c7e1b5b96a327.cif
正在转换auid-e076de4b6ea1bc8e.cif
正在转换auid-e14c153bc6afc98d.cif
正在转换auid-e3298c3dd863dcea.cif
正在转换auid-e48d1300bf84bd7e.cif
正在转换auid-e4a7234b4b45f168.cif
正在转换auid-e544b8ae65024039.cif
正在转换auid-e6d661e507a75498.cif
正在转换auid-eadaee620008c507.cif
正在转换auid-eb2db2cbbfbfe6a3.cif
正在转换auid-eb5c3b3b590d872a.cif
正在转换auid-eb7e72986822bdec.cif
正在转换auid-ebbe89816ae552d7.cif
正在转换auid-ec2b8f5480f7e5e4.cif
正在转换auid-edc924264094e604.cif
正在转换auid-ee43928865e1e88e.cif
正在转换auid-eff0c46ef26f85f8.cif
正在转换auid-f08097af32ed3ba5.cif
正在转换auid-f0c2141ccb29792d.cif
正在转换auid-f0f72520a17c424a.cif
正在转换auid-f5039d7d52cd907c.cif
正在转换auid-f64e44e26b521180.cif
正在转换auid-f684a09dcefe255e.cif
正在转换auid-f7bbe7bf83ff5787.cif
正在转换auid-f80d4d4ecbcb2db6.cif
正在转换auid-f80fe6ded20ef991.cif
正在转换auid-f836af63650d706b.cif
正在转换auid-f846db9587446a6e.cif
正在转换auid-f8e0640f58f78b3f.cif
正在转换auid-fa4bbf5295b0f753.cif
正在转换auid-fb41ce58854c85fb.cif
正在转换auid-fb82f23a960d57ea.cif
正在转换auid-fc77c4b54ef09858.cif
正在转换auid-fd2735cac577063a.cif
正在转换auid-fd37d4de1d5a6ce1.cif
正在转换auid-fe571d81626d8d2c.cif
正在转换auid-ffbc71e4b57f56df.cif
正在转换auid-fffc7f59c1781f86.cif
正在转换auid-01b8499b8bba44df.cif
正在转换auid-0259d68674b800c3.cif
正在转换auid-025c052d1b8b448d.cif
正在转换auid-0361058f418da352.cif
正在转换auid-040dcf0f4b801f44.cif
正在转换auid-049884ed595b76a8.cif
正在转换auid-07c62c8bd8fa649a.cif
正在转换auid-0854524a232dd993.cif
正在转换auid-096390b5d0c5a937.cif
正在转换auid-0a44732ba00c89d3.cif
正在转换auid-0b6e45fb13939cfa.cif
正在转换auid-0d241770ce679cf2.cif
正在转换auid-0d41c566b96e2b8b.cif
正在转换auid-0e6577fdf0994d19.cif
正在转换auid-0e9a68c674b93c49.cif
正在转换auid-111939e70d2bc122.cif
正在转换auid-115eb92b97906ada.cif
正在转换auid-118e55383622ad35.cif
正在转换auid-1209817bd8581391.cif
正在转换auid-12f587b708c648f0.cif
正在转换auid-134f09989090f022.cif
正在转换auid-14bfbd7aeac6a39d.cif
正在转换auid-161a646146669ff6.cif
正在转换auid-18c521390914a2e9.cif
正在转换auid-1ef7eb9f1e5ca47d.cif
正在转换auid-216ee2c244ebf461.cif
正在转换auid-21b0bf08eb0d1b8a.cif
正在转换auid-23e0fa909c87f303.cif
正在转换auid-24dd1482da0a0b50.cif
正在转换auid-252fe0d8f76d79bc.cif
正在转换auid-259a9b99b84fff4f.cif
正在转换auid-28aeabb68cea2d9d.cif
正在转换auid-29763d28a6c4de03.cif
正在转换auid-29b96b91e46e74a5.cif
正在转换auid-2bf2603e574aa6bf.cif
正在转换auid-2d8d5cd47234f604.cif
正在转换auid-2ec3a1f018c3ef88.cif
正在转换auid-2f36d8e6ad9e8324.cif
正在转换auid-35bcc55fc8729f56.cif
正在转换auid-35c80ba58e42c695.cif
正在转换auid-35f6314d696a7f79.cif
正在转换auid-3705a26784feff0d.cif
正在转换auid-3ab008e9f00045f6.cif
正在转换auid-3ab379fa84871cea.cif
正在转换auid-3ea755faf545710b.cif
正在转换auid-4458862d1576aeee.cif
正在转换auid-44a80cda756583ef.cif
正在转换auid-458e2ed5331b51fa.cif
正在转换auid-4651fdc8cdcfcea1.cif
正在转换auid-466c68f6ef7e7fb0.cif

正在转换auid-47ba0a2f499e3280.cif
正在转换auid-47e01f025dc07f4f.cif
正在转换auid-4847d00fc9e06a73.cif
正在转换auid-4d57b3ccfc824cee.cif
正在转换auid-4d5be3d2f685d96d.cif
正在转换auid-4f232edae68c66f6.cif
正在转换auid-4f8afb4278cdfb6a.cif
正在转换auid-507f69ef94195926.cif
正在转换auid-510ab96beb30be54.cif
正在转换auid-514120a99947825e.cif
正在转换auid-527b009f61a18513.cif
正在转换auid-53b2199a1a1ab6a4.cif
正在转换auid-551e9f720c677f7e.cif
正在转换auid-565359baba634d02.cif
正在转换auid-56f12a8f55d2d5c8.cif
正在转换auid-58f895bfe3cb3358.cif
正在转换auid-59925140d2438af9.cif
正在转换auid-5cc700524d2ff2f6.cif
正在转换auid-5d61f392ed2e4183.cif
正在转换auid-5ea7e5cde267594b.cif
正在转换auid-608e2c773bf3ec18.cif
正在转换auid-6257a4af60bcf039.cif
正在转换auid-64a588f9e2139526.cif
正在转换auid-66a252f2f9f22234.cif
正在转换auid-66beabbe92890a0a.cif
正在转换auid-67123b909d73ad4d.cif
正在转换auid-68524ba70cab53db.cif
正在转换auid-689ad13d53919f00.cif
正在转换auid-6a0602c7c4adc479.cif
正在转换auid-6a39ad04de3671c4.cif
正在转换auid-6a71e8a0a800068e.cif
正在转换auid-6abefcf9fd93bfff.cif
正在转换auid-6b160bd31e2b76cc.cif
正在转换auid-6caf9cb387dd5948.cif
正在转换auid-6eaf117d930185e5.cif
正在转换auid-6f91a8a63f24332f.cif
正在转换auid-71eeeb037dbbc0b5.cif
正在转换auid-722aeee300213986.cif
正在转换auid-758a5d8ab257f973.cif
正在转换auid-7627eda711140c99.cif
正在转换auid-77803eb3b3d7cf46.cif
正在转换auid-798f9523a6008a87.cif
正在转换auid-79dc247a7fa65b0a.cif
正在转换auid-7da89ea59ebbc7be.cif
正在转换auid-7e02a6c8ee011211.cif
正在转换auid-7e62a3bd5a575423.cif
正在转换auid-7e7229f7ff39ce83.cif
正在转换auid-7ebc02ca6b514248.cif
正在转换auid-7ece861a9a2c5ee0.cif
正在转换auid-7fe1b1522e35e4f6.cif
正在转换auid-80c10bcea48c9956.cif
正在转换auid-817747a6faea6459.cif
正在转换auid-82c8ded576d052a4.cif
正在转换auid-8427c8ab8d1f3a5c.cif
正在转换auid-85692350089208c1.cif
正在转换auid-8579c11066cd1cbf.cif
正在转换auid-87444db32ef79fea.cif
正在转换auid-87d33a0c651883fb.cif
正在转换auid-882e7b8c121890cc.cif
正在转换auid-8bc7e1a16279abff.cif
正在转换auid-8d35a7534368d3f2.cif
正在转换auid-91edabd16d230bd0.cif
正在转换auid-93442a16299dfccf.cif
正在转换auid-95eec2c3452d733b.cif
正在转换auid-96a415d11ce3b89b.cif
正在转换auid-972f708db170f65b.cif
正在转换auid-97e1d4ef8ecc0250.cif
正在转换auid-97e8bf5f934518ef.cif
正在转换auid-988ed8341eae67d2.cif
正在转换auid-989ff069f6f320e2.cif
正在转换auid-99ca4a9ac65183a2.cif
正在转换auid-9ae670af5d5362af.cif
正在转换auid-9d40b6e343a3bc6d.cif
正在转换auid-9ffb88b9041ab447.cif
正在转换auid-a138b38344ab0a3e.cif
正在转换auid-a4100216e767fa4b.cif
正在转换auid-a43d9214b85010bb.cif
正在转换auid-a70f446e276db80c.cif
正在转换auid-a73472af7bd14c51.cif
正在转换auid-a78da003c0b76d1f.cif
正在转换auid-a8777b0e4ab48003.cif
正在转换auid-aaef948532b38817.cif
正在转换auid-ab71b3c24dfb8581.cif
正在转换auid-acbd908a1c3fe7bf.cif
正在转换auid-af47f305c35b1c93.cif
正在转换auid-af6e210d3bc024c1.cif
正在转换auid-b264e1dc80500aed.cif
正在转换auid-b42cc96b3f2cdfd4.cif
正在转换auid-b4c1151be8c51f78.cif
正在转换auid-b53502f61cd928c2.cif
正在转换auid-b70cd3a6f42425de.cif
正在转换auid-bb3c1cf37c4263ba.cif
正在转换auid-bc329eea5cc758d6.cif
正在转换auid-be117d98ef391723.cif
正在转换auid-be1fd8b67f610757.cif
正在转换auid-be75cfb40cfc21ee.cif
正在转换auid-c04a329e050ee0ff.cif
正在转换auid-c3e77da927ff6895.cif
正在转换auid-c425880ddc5b327d.cif
正在转换auid-c4e37a76f3e05dfe.cif
正在转换auid-c57894384032eab4.cif
正在转换auid-c72cbf93860cef87.cif
正在转换auid-c84c4960777e24fc.cif
正在转换auid-ca4f37ce6f4fdd81.cif
正在转换auid-cb56846ff81a9dca.cif
正在转换auid-cb9cd516a1599ef5.cif
正在转换auid-cbe3eb49601b2e71.cif
正在转换auid-cced4155ba142bcb.cif
正在转换auid-cdee195b951f5d51.cif
正在转换auid-ce038afcf4745823.cif
正在转换auid-ce9f0765df4441f6.cif
正在转换auid-ceda76f745d5abea.cif
正在转换auid-cf9445bc3c26a060.cif
正在转换auid-d15d6a8275be2258.cif
正在转换auid-d17b2a4b5b4acab8.cif
正在转换auid-d241a65cef55982d.cif
正在转换auid-d2be049155731b1c.cif
正在转换auid-d31ed60ccdf72526.cif
正在转换auid-d4eddbd6a353d061.cif
正在转换auid-d54bc3d76ca2666e.cif
正在转换auid-d5e3702a2914fa73.cif
正在转换auid-d5ee9d59237d3c9f.cif
正在转换auid-d6089b612ce3be26.cif
正在转换auid-d6c00bdb3395f0d9.cif
正在转换auid-dbbcb5f17ee68157.cif
正在转换auid-dc3d058fe0b4a09a.cif
正在转换auid-dccafa5713d82c5d.cif
正在转换auid-dcdbdf7f35126e05.cif
正在转换auid-dd0b7b1667ada500.cif
正在转换auid-dddf72b887a54b04.cif
正在转换auid-de2b1cbce4d40206.cif
正在转换auid-ded465e25e30a779.cif
正在转换auid-e024c5d5fa227c98.cif
正在转换auid-e06eaa067c25c593.cif
正在转换auid-e0eebc0fd0228f19.cif
正在转换auid-e19746777f9b231a.cif
正在转换auid-e2ed9509173b5bd3.cif
正在转换auid-e38b4fe985f23098.cif
正在转换auid-e3c7544c55e489cf.cif
正在转换auid-e443d14f58697cd5.cif
正在转换auid-e47bc9fc98270798.cif
正在转换auid-e5e5bc6dd985dbbd.cif
正在转换auid-e608457e90ad26d4.cif
正在转换auid-e7989324da127123.cif
正在转换auid-e83fcfda7036bb8c.cif
正在转换auid-e874a1849e3bf5a3.cif
正在转换auid-e97e1b25692fbff9.cif
正在转换auid-eb3233c97aa937bc.cif
正在转换auid-eb601e2feb7c0ee0.cif
正在转换auid-eb883d8930ba2379.cif
正在转换auid-ec1207ffc1fcf84b.cif
正在转换auid-ed69d82a5c696d48.cif
正在转换auid-ee5f7cf6ce652beb.cif
正在转换auid-ee7d5d0d5ebbe87c.cif
正在转换auid-f15338112b2fd7d7.cif
正在转换auid-f1e317c2e2098833.cif
正在转换auid-f20bba5b264f87f7.cif
正在转换auid-f262c3e067226330.cif
正在转换auid-f3784a3c014d8369.cif
正在转换auid-f46f9a96820f3787.cif
正在转换auid-f57ee37b2a05c277.cif
正在转换auid-f5fc0bf7cf4e3d9d.cif
正在转换auid-f75482c114e035fe.cif
正在转换auid-f928a09d4cefb18b.cif
正在转换auid-f99e7760b413214f.cif
正在转换auid-fc7c95386f5d33fe.cif
正在转换auid-fcbd7e787cc17595.cif
正在转换auid-fd829c42e087046e.cif
正在转换auid-fdd8fc9216814388.cif
正在转换auid-fe585cf75d88e536.cif
正在转换auid-ffe74a746a97b383.cif
正在转换auid-026c7fcf1e128c81.cif
正在转换auid-0d981561287a94ca.cif
正在转换auid-0e500d1162d6dbf3.cif
正在转换auid-111625377218fa99.cif
正在转换auid-1231b2a9a63936a1.cif
正在转换auid-18d412c6947b5394.cif
正在转换auid-197aa3382a97da04.cif
正在转换auid-1e9c395571b63133.cif
正在转换auid-1f3c8b35c5f6e194.cif
正在转换auid-1fbb6798cd67e45f.cif
正在转换auid-21d39af22404468d.cif
正在转换auid-234b77ac4b359ba4.cif
正在转换auid-254e34a75f6fecf3.cif
正在转换auid-2612c14721530c80.cif
正在转换auid-27070fbb5351e884.cif
正在转换auid-2a27e2ebd6b4868d.cif
正在转换auid-2b5a2f98595aa351.cif
正在转换auid-2fb519205b6bf9c7.cif
正在转换auid-35681d52298f761a.cif
正在转换auid-3d07a3bf142b1c4c.cif
正在转换auid-3d11e6940e3c114b.cif
正在转换auid-480bfd089266b3ee.cif
正在转换auid-48b5e2b1f0449fa4.cif
正在转换auid-4a05e1e8b1cf71ef.cif
正在转换auid-4ab1505801b1fd5b.cif
正在转换auid-4c468a67193ad698.cif
正在转换auid-4d13f06b9fe563ef.cif
正在转换auid-4fcc753033fa4cea.cif
正在转换auid-51d343df38a560d5.cif
正在转换auid-52e34f56c9d272f9.cif
正在转换auid-557a13fe4fdbe60e.cif
正在转换auid-5d748f5a07ca112b.cif
正在转换auid-5da96bce418c70e5.cif
正在转换auid-5dd7b5b33c867cbe.cif
正在转换auid-5fc27ec2c2c009c9.cif
正在转换auid-64067954580b61a8.cif
正在转换auid-65f011ae67c40813.cif
正在转换auid-678ac5ec61a3e01f.cif
正在转换auid-6ae4803854fb0624.cif
正在转换auid-6e5e137f8e066ee4.cif
正在转换auid-71c6ada23823af1a.cif
正在转换auid-77397d097fcfec92.cif
正在转换auid-792431e0088c473d.cif
正在转换auid-7cd8b1adc44c5eae.cif
正在转换auid-7d97d1fc48aa25f9.cif
正在转换auid-7e80e02a348399d9.cif
正在转换auid-7efce6cad0843df1.cif
正在转换auid-82e0eec87747a5a5.cif
正在转换auid-866e27ae9214f390.cif
正在转换auid-8837be380d7be0fd.cif
正在转换auid-8970bc24c3d2aa64.cif
正在转换auid-8ccdcb75a21977dc.cif
正在转换auid-8cce3d9047c1bc4a.cif
正在转换auid-8db51c1d706a3e3c.cif
正在转换auid-8f0e30312785be9b.cif
正在转换auid-9195181420450af9.cif
正在转换auid-92e9abed90449e0f.cif
正在转换auid-99c443f9b72fbe7f.cif
正在转换auid-a024be6659874b1d.cif
正在转换auid-a24e731fda2c64b3.cif
正在转换auid-a6925b6045973ef8.cif
正在转换auid-aadb37c0874c4cb9.cif
正在转换auid-ab9bd99d71b3bfbf.cif
正在转换auid-af306558a1258225.cif
正在转换auid-b5460f89684f8388.cif
正在转换auid-bdb01954b68ec179.cif
正在转换auid-be1dd8e30cf4cc5c.cif
正在转换auid-c422afb3ea6a5582.cif
正在转换auid-c47587f2603d8251.cif
正在转换auid-c5b59f4f5d3ed1f3.cif
正在转换auid-c5fb1281be44f09a.cif
正在转换auid-c978e99d27550cde.cif
正在转换auid-cc8a192cfc2e7dc8.cif
正在转换auid-d357ec5bdf72cea1.cif
正在转换auid-d7ec42e0f8a55cc8.cif
正在转换auid-de4eca44c5399ad5.cif
正在转换auid-de94ce32d96089fb.cif
正在转换auid-e018cb9ac26dfd16.cif
正在转换auid-e524ec6e2e6bd4f0.cif
正在转换auid-e6656db8689e44cd.cif
正在转换auid-e808a9f7f78da3fd.cif
正在转换auid-e8b85ad4a6f08fec.cif
正在转换auid-e9b1b839c274d61e.cif
正在转换auid-ea89b3a71b387869.cif
正在转换auid-eee09b25a22a4f17.cif
正在转换auid-f1d779aa173a26d0.cif
正在转换auid-f3792a244e4d1817.cif
正在转换auid-f7d44cbaac8493b6.cif
正在转换auid-f98a034b18ff62b3.cif
正在转换auid-fd255f51b5216810.cif
正在转换auid-fe840962426841a6.cif
正在转换auid-0307fcdbe3c1af37.cif
正在转换auid-0365e54cfb6e5b94.cif
正在转换auid-0e103daf3ef973e1.cif
正在转换auid-13936973bdbe8f10.cif
正在转换auid-13faffa6fc77edea.cif
正在转换auid-14cbd0a1a9fdaedf.cif
正在转换auid-1527abd54b82b045.cif
正在转换auid-16be6196ccc749be.cif
正在转换auid-16c4f5651622c484.cif
正在转换auid-189b527d43825a39.cif
正在转换auid-2a365acc3741d5a0.cif
正在转换auid-2a953897596a5199.cif
正在转换auid-2ac91ae22336487b.cif
正在转换auid-2b061c1d905245cb.cif
正在转换auid-2cab042f82e3ea9b.cif
正在转换auid-2d7882896dec9501.cif
正在转换auid-2f57f4155f5e574d.cif
正在转换auid-2f741a6dcfcb7b8e.cif
正在转换auid-376a1442c180a4ba.cif
正在转换auid-3a2aaf7ad73917b9.cif
正在转换auid-3d0938d16b06dd83.cif
正在转换auid-43b595fd82d39146.cif
正在转换auid-47d960d6eed097f7.cif
正在转换auid-496801efa5e4c478.cif
正在转换auid-4a33fc9489f99edd.cif
正在转换auid-4a6e3cd71a670c5f.cif
正在转换auid-4d9e0b5232baf4d5.cif
正在转换auid-5d7905f490ca1983.cif
正在转换auid-6088dd9c246ce8a3.cif
正在转换auid-634ebb6a3805c8bf.cif
正在转换auid-68d4df7dbaec6070.cif
正在转换auid-69f207ad2e0dde93.cif
正在转换auid-6a1c8b311b67919a.cif
正在转换auid-6aefdacd84f9ab75.cif
正在转换auid-6c48a4ce1cfbf556.cif
正在转换auid-6e950813df41764b.cif
正在转换auid-6ee62e8057c3c036.cif
正在转换auid-6f2721255735c3be.cif
正在转换auid-70a7c58b10406268.cif
正在转换auid-732c8e37e6078af3.cif
正在转换auid-74c92373c7dfe82a.cif
正在转换auid-75ae9d54ffc91eb3.cif
正在转换auid-75f99360540093cd.cif
正在转换auid-772c89ffa3ff1525.cif
正在转换auid-79aeabb34bbbcf1b.cif
正在转换auid-7a2ffe206a8215b1.cif
正在转换auid-7bb75c9409b8a7e5.cif
正在转换auid-8138a4b4bc9bd3c8.cif
正在转换auid-8553ae62d840cf8c.cif
正在转换auid-856b8ce2ef67d88b.cif
正在转换auid-877b0a7b7e6e3896.cif
正在转换auid-89113daacf109e71.cif
正在转换auid-8a9a6eb8afe93806.cif
正在转换auid-8b04aaa21d14d691.cif
正在转换auid-8b308c470b3eeb97.cif
正在转换auid-8c15f480ba144a72.cif
正在转换auid-906a1802aa0fd288.cif
正在转换auid-98c8706649faef4e.cif
正在转换auid-9beb7c1694729eb9.cif
正在转换auid-9bebb422dab10a9d.cif
正在转换auid-a0543a940790b00d.cif
正在转换auid-a3719f8fbd2079fa.cif
正在转换auid-a5e7fda7dceaca59.cif
正在转换auid-aa58771b29a0f9d9.cif
正在转换auid-b1238bb9339f8b65.cif
正在转换auid-b4a296a21280e257.cif
正在转换auid-b9d97acd1be1fda7.cif
正在转换auid-c65069cc143a9253.cif
正在转换auid-ca7b42d6793077a0.cif
正在转换auid-cbbbe3cd887ffc49.cif
正在转换auid-cdefa918b5d315fd.cif
正在转换auid-cf9c575aff18d566.cif
正在转换auid-d9206ea8fb324d05.cif
正在转换auid-de4fa2e51cf8b278.cif
正在转换auid-dffcbde23e6f5102.cif
正在转换auid-e01cc61ea6a2d193.cif
正在转换auid-e106f1e549fca059.cif
正在转换auid-e600cd3d378c433c.cif
正在转换auid-efa9362cdf4fc0de.cif
正在转换auid-f12f90351dfc122b.cif
正在转换auid-f169118a1bcbeef8.cif
正在转换auid-f18d0a8a676a19ad.cif
正在转换auid-f5a4e91d5d778696.cif
正在转换auid-f7da8a72756474e0.cif
正在转换auid-f8a56e8cd71924a9.cif
正在转换auid-f8a83adb73185b23.cif
正在转换auid-f96360a1f16bb9f0.cif
正在转换auid-fa029935a73828d1.cif
正在转换auid-fa17362551f253d4.cif
正在转换auid-fa451f19533593d2.cif
正在转换auid-fe1963ef5564a6c3.cif
正在转换auid-ff2d7e619c68f4d8.cif
正在转换auid-ffe4839a89aca4be.cif
正在转换auid-002fa9de2ad8a1d6.cif

正在转换auid-01821d20060131cf.cif
正在转换auid-0200a1fb61472924.cif
正在转换auid-02bb30635887cc67.cif
正在转换auid-06b9db1b0fb10b01.cif
正在转换auid-0714e8a92618487c.cif
正在转换auid-07c15cd1b0766ee0.cif
正在转换auid-0869150b9ca7721b.cif
正在转换auid-08f4d32714343974.cif
正在转换auid-0acad9dcdd24cf95.cif
正在转换auid-0bae94816487610a.cif
正在转换auid-0c3de84270e4e8c1.cif
正在转换auid-0c7e9e3d1cb96ed3.cif
正在转换auid-0dfe148fb44e5b7c.cif
正在转换auid-1011f0152b0f6d58.cif
正在转换auid-1053c17ff686f2ef.cif
正在转换auid-1205a8f77ddd2ab1.cif
正在转换auid-123c2cf0612bb9b5.cif
正在转换auid-135ed645feff435b.cif
正在转换auid-1477bdc772c30c31.cif
正在转换auid-14bfeb1ed3294174.cif
正在转换auid-150a2a560184e4cd.cif
正在转换auid-184533f15db1021b.cif
正在转换auid-189ae4e8f12fc3cf.cif
正在转换auid-18a43f6d28411b79.cif
正在转换auid-1a754174a19ccee6.cif
正在转换auid-1ab3699fc6b87f2d.cif
正在转换auid-1c656d70c91b503f.cif
正在转换auid-1d2903b87ee02a8f.cif
正在转换auid-1f87f1004b800533.cif
正在转换auid-20783edc145ab9ce.cif
正在转换auid-210a634bad6e1820.cif
正在转换auid-22b607f2c5c30fcf.cif
正在转换auid-24549959da481255.cif
正在转换auid-2567fab396c783d2.cif
正在转换auid-2602e4021af97fb8.cif
正在转换auid-276d4864fa49fc20.cif
正在转换auid-27e8e998da8a8223.cif
正在转换auid-28a5e7618b445eb3.cif
正在转换auid-2b33682ada37da71.cif
正在转换auid-2c2cff956b1b0400.cif
正在转换auid-2cf73e7ff8bcd655.cif
正在转换auid-2f29160edb166c52.cif
正在转换auid-33e93a4c801e8743.cif
正在转换auid-37376a2e7e670c40.cif
正在转换auid-37e5cb95c7f36e14.cif
正在转换auid-387329ab3c720c17.cif
正在转换auid-3995c684bfae2fc0.cif
正在转换auid-3add47972f76c04b.cif
正在转换auid-3b4a5349f3775f53.cif
正在转换auid-3d99996ad9d14e12.cif
正在转换auid-3dcdb64f36151fb0.cif
正在转换auid-3e25a5491501caab.cif
正在转换auid-3f2ae40144a6d9af.cif
正在转换auid-3fa1a916a909bc9a.cif
正在转换auid-4173d46ca3c164dd.cif
正在转换auid-424b9661b9b25c20.cif
正在转换auid-428dcd9fe3fc14a6.cif
正在转换auid-45751f69eabed11c.cif
正在转换auid-4633cb0a17f4d1b4.cif
正在转换auid-46fdb39097ccc633.cif
正在转换auid-47254be1d97718e6.cif
正在转换auid-475b4fe1952ad698.cif
正在转换auid-4841053b3f91e13e.cif
正在转换auid-491eb24c7b98f7c6.cif
正在转换auid-4994647d3360e7d1.cif
正在转换auid-4a06a57939144c95.cif
正在转换auid-4b15fc0c2ea4462c.cif
正在转换auid-4b8ce2070848dad4.cif
正在转换auid-4bf2c4f803331a9a.cif
正在转换auid-4d281bbafe9a0bea.cif
正在转换auid-4d2d80c96f417231.cif
正在转换auid-4ed37b1c2374d33c.cif
正在转换auid-4f2211f779f51a18.cif
正在转换auid-4f9396d1cc5ee339.cif
正在转换auid-5078704bc68868bf.cif
正在转换auid-51bacc535270c791.cif
正在转换auid-54349962d97602f0.cif
正在转换auid-544aaed9b19d5b10.cif
正在转换auid-57721c3b0004ef38.cif
正在转换auid-57a1f950faf6c026.cif
正在转换auid-59648f64f33244fd.cif
正在转换auid-5a30a9466fed40b9.cif
正在转换auid-5af69f2ba4b9f397.cif
正在转换auid-5bf04006dcb49c35.cif
正在转换auid-5c142f56f050f658.cif
正在转换auid-5d5fee1a67eaa6bd.cif
正在转换auid-5de69bd71f068023.cif
正在转换auid-5f640225630b3336.cif
正在转换auid-5f9747b7124cda54.cif
正在转换auid-5fbfd27dfa09e8c1.cif
正在转换auid-5fd6519fa8a72367.cif
正在转换auid-615b0de9a3981154.cif
正在转换auid-624f5599a0c035cd.cif
正在转换auid-629d31d4273cb4b9.cif
正在转换auid-62c128426fce64bd.cif
正在转换auid-631b9db7ba299276.cif
正在转换auid-676c5079c1829095.cif
正在转换auid-68aa8214d5f90fbb.cif
正在转换auid-6917fb4322ccb2a3.cif
正在转换auid-6a7e48cfa726d6de.cif
正在转换auid-6aef4ce2f791fc3a.cif
正在转换auid-6b3655cad651b97c.cif
正在转换auid-6c61499ffe3849ff.cif
正在转换auid-6cc6104409e352bd.cif
正在转换auid-6efdb896133931ce.cif
正在转换auid-6f18dc30f0130389.cif
正在转换auid-6f8fc47df4bb7c3c.cif
正在转换auid-6ff46580c54f5f32.cif
正在转换auid-718d9603b1342c0c.cif
正在转换auid-723601f21bc88c0c.cif
正在转换auid-73c906136724f28b.cif
正在转换auid-741b602b280623be.cif
正在转换auid-75823c22948cb88a.cif
正在转换auid-78c9ac8806554af4.cif
正在转换auid-793e32fdb62ed00b.cif
正在转换auid-79c6226781b6a60f.cif
正在转换auid-7b65582c7af97627.cif
正在转换auid-7c954704493c49ec.cif
正在转换auid-7d886bc53299a6b0.cif
正在转换auid-7e3c7511c35fd38c.cif
正在转换auid-7f9842a401a36545.cif
正在转换auid-828ece8a73bd470a.cif
正在转换auid-87c3bb30ad5a0d7c.cif
正在转换auid-87ee37384beb8fd6.cif
正在转换auid-87f3afb4e01a73b2.cif
正在转换auid-88e419a57d5c9027.cif
正在转换auid-897bbb5fb0981028.cif
正在转换auid-8a98e2c0052a7958.cif
正在转换auid-8b538982fb3a6042.cif
正在转换auid-8be8fe62a35f3338.cif
正在转换auid-8e08273a1e9db536.cif
正在转换auid-908e9548a8d8ec68.cif
正在转换auid-90cfa5258ba19c28.cif
正在转换auid-919dee83585f7ba9.cif
正在转换auid-924d65ab101dafbb.cif
正在转换auid-92e4c008d8f0fede.cif
正在转换auid-9315233bebc0a75e.cif
正在转换auid-94a2a60f5bb3794c.cif
正在转换auid-94cfddd8f913f44c.cif
正在转换auid-94d332b7d6cfb646.cif
正在转换auid-952beaea8d1cd253.cif
正在转换auid-956870e6b3045781.cif
正在转换auid-966ddd72e372f823.cif
正在转换auid-96e1895b0a63d6fd.cif
正在转换auid-98d25a4396cb4948.cif
正在转换auid-9aaf89c345a545ca.cif
正在转换auid-9b45073eab8c4db0.cif
正在转换auid-9c7d2576ff71ab42.cif
正在转换auid-9ef7141e482b9147.cif
正在转换auid-9f7b2cb0aabc6b83.cif
正在转换auid-a045f8cc47e476ec.cif
正在转换auid-a1cb6129174b99f4.cif
正在转换auid-a210012f427e370f.cif
正在转换auid-a2fda04f6c01a4d0.cif
正在转换auid-a458f111c074f4a0.cif
正在转换auid-a4ec57e8cd012c32.cif
正在转换auid-a58aa0cbb99a08b5.cif
正在转换auid-a642edea174fb39c.cif
正在转换auid-a712f0bf2f753398.cif
正在转换auid-a97390cdc7259736.cif
正在转换auid-a9bc5b90bdc858ed.cif
正在转换auid-ab1479b5a737ee1c.cif
正在转换auid-ab4710103e7d0969.cif
正在转换auid-abd8ca38a3135199.cif
正在转换auid-ac517d4167d6d32c.cif
正在转换auid-ace68267ecbd0254.cif
正在转换auid-acfca316ccd79648.cif
正在转换auid-ae4e56598c46b200.cif
正在转换auid-ae5cf6695e4ad7c0.cif
正在转换auid-aea3235d2a4c97ef.cif
正在转换auid-afaa470b2f814083.cif
正在转换auid-b2502725f9d26a7d.cif
正在转换auid-b25412d1a9c96119.cif
正在转换auid-b29bfc5619725330.cif
正在转换auid-b3efa6f2adf55f87.cif
正在转换auid-b57fb6a7efd7de71.cif
正在转换auid-b6e5839b4a70831c.cif
正在转换auid-b8eb9929698e4a4a.cif
正在转换auid-b983876dc58596c6.cif
正在转换auid-b9d7b3e25f251def.cif
正在转换auid-ba4375a0b0147dd8.cif
正在转换auid-bb0127c13bd2ab2c.cif
正在转换auid-bb13770e8fbe317c.cif
正在转换auid-bb3b663da95ccf2e.cif
正在转换auid-bc0a20dbc9a82c08.cif
正在转换auid-bd74d547e5d5cf65.cif
正在转换auid-bd90cf4ce8e73856.cif
正在转换auid-bea94f5caba7e749.cif
正在转换auid-bf735aaaedebe52d.cif
正在转换auid-c0f3e5c783d4cfa1.cif
正在转换auid-c16a5ed61bb93c82.cif
正在转换auid-c1cec4da27099a53.cif
正在转换auid-c5829e1c39c4eef8.cif
正在转换auid-c5fadaed29478e89.cif
正在转换auid-c65acbf9be929a7c.cif
正在转换auid-c93e2751b49f3d06.cif
正在转换auid-c961a34b3c182860.cif
正在转换auid-ca6fd42bc9257e8e.cif
正在转换auid-cb710e39819568f6.cif
正在转换auid-cd8038c027a5f845.cif
正在转换auid-cd99365af1122162.cif
正在转换auid-ceef6b144638ed14.cif
正在转换auid-d126201b7f850855.cif
正在转换auid-d26f4c0eaaa4c7f4.cif
正在转换auid-d276ba037315fe3b.cif
正在转换auid-d354790c7985173d.cif
正在转换auid-d56a5ebd63d10625.cif
正在转换auid-d6660a198c9b5fff.cif
正在转换auid-d937de3370f038a2.cif
正在转换auid-da3e0705ce5f6c5c.cif
正在转换auid-db22f8ecac7cb6af.cif
正在转换auid-dd982fe2c5f9954e.cif
正在转换auid-de72791d7b9e1cfa.cif
正在转换auid-df6a9d7ff414f2ca.cif
正在转换auid-e045f525e05a5c41.cif
正在转换auid-e11ce34c1f80e1fc.cif
正在转换auid-e3d805d786bc8c0c.cif
正在转换auid-e533c54ff51cb7df.cif
正在转换auid-e5db758f6f7e1d3e.cif
正在转换auid-e6e9876629ce24c6.cif
正在转换auid-ea91cb2ae4a034ee.cif
正在转换auid-ebbdd39174a1e7e2.cif
正在转换auid-ec7639ca8c58d507.cif
正在转换auid-ee12dabbc9e5c7eb.cif
正在转换auid-f1c149344c1f8461.cif
正在转换auid-f4d341dc184d1453.cif
正在转换auid-f5e4f03b779690b6.cif
正在转换auid-f617c2e8db6d3ea6.cif
正在转换auid-f7a5bde59c46b854.cif
正在转换auid-fa2da9af51489bf7.cif
正在转换auid-fa58c7a8b6d08c96.cif
正在转换auid-fbc2099587f812dc.cif
正在转换auid-ff8d0fe87b9004ba.cif
正在转换auid-05239cc95e99b7e6.cif
正在转换auid-02cd0697b9db7e20.cif
正在转换auid-013e6e258dba760f.cif
正在转换auid-02187f5ffbdeb1aa.cif
正在转换auid-0288425ea91adb33.cif
正在转换auid-05891035b35255d7.cif
正在转换auid-05b53331e84dff7d.cif
正在转换auid-064046dc6a1cf07f.cif
正在转换auid-0698ee28253ca506.cif
正在转换auid-06d2ad5e60cf58e4.cif
正在转换auid-076b8bab4765c32b.cif
正在转换auid-07fa82584de0b960.cif
正在转换auid-08310a9b76fa0dc7.cif
正在转换auid-086e00c4547b9824.cif
正在转换auid-08d41a6211eabedc.cif
正在转换auid-09bc6e200be40912.cif
正在转换auid-09fd60137bb90863.cif
正在转换auid-0bba0d7476d3d56b.cif
正在转换auid-0bce5497f90d595d.cif
正在转换auid-0ce20a7c47fa72e3.cif
正在转换auid-0d242ed2726333e6.cif
正在转换auid-0d257cbb61affde9.cif
正在转换auid-0e158ccda0bbbaeb.cif
正在转换auid-12a73d556448efed.cif
正在转换auid-14b3e05aed2da76d.cif
正在转换auid-16adbad68b919299.cif
正在转换auid-1703f3faef06bbcb.cif
正在转换auid-1877812743531615.cif
正在转换auid-18bf9e2fba397613.cif
正在转换auid-18d70ec1276e293a.cif
正在转换auid-19d14cbdd0bdd168.cif
正在转换auid-1bf78952923a7d28.cif
正在转换auid-1d4b324478547fa3.cif
正在转换auid-1d850d1ba55d4201.cif
正在转换auid-1de8724fc64c3acc.cif
正在转换auid-1eaa183d1d6298f3.cif
正在转换auid-1f60a915999ba225.cif
正在转换auid-1f854293a8a0d4e1.cif
正在转换auid-2034d303d2d373f5.cif
正在转换auid-20f47a3c60817f81.cif
正在转换auid-20fe2cf2aae3774f.cif
正在转换auid-213bae7213ea5fe5.cif
正在转换auid-21b5e5957efe2c9c.cif
正在转换auid-21cc3ed15b15fc3e.cif
正在转换auid-221b7d054f999ebf.cif
正在转换auid-22ab43391f8aed49.cif
正在转换auid-2357855057bd5b6a.cif
正在转换auid-247367a145e8206d.cif
正在转换auid-25a4fb4d22b93422.cif
正在转换auid-266fbc1b2ac51f29.cif
正在转换auid-26a67cd754282dda.cif
正在转换auid-26e79021b7041a46.cif
正在转换auid-27c02739b542fb6f.cif
正在转换auid-29a90a088cdacf37.cif
正在转换auid-2a9f0aad47b9cee9.cif
正在转换auid-2addb4f521fcf1d5.cif
正在转换auid-2b303c8f5b9bef67.cif
正在转换auid-2c4f6e82ed7eddba.cif
正在转换auid-2cadde0784b97aee.cif
正在转换auid-2d9d01045bc8ca0f.cif
正在转换auid-2e1a93b9ffd92eb7.cif
正在转换auid-2ed024adc9777bed.cif
正在转换auid-2efcc140db692c20.cif
正在转换auid-309001db71a237d9.cif
正在转换auid-32e60fa843cf1a3e.cif
正在转换auid-345e5e764246de96.cif
正在转换auid-3498d845630ee1f6.cif
正在转换auid-368e991505515c64.cif
正在转换auid-36c1085a005c7ab1.cif
正在转换auid-370ab75a0a90ed73.cif
正在转换auid-377e02e6ed3d538c.cif
正在转换auid-38fe4ae25b2407f4.cif
正在转换auid-3a04429a0b13c5ba.cif
正在转换auid-3b304cfd02898902.cif
正在转换auid-3b4a4a68b33f7fa6.cif
正在转换auid-3b6607571600450e.cif
正在转换auid-3d0925b6ae5bfdc8.cif
正在转换auid-3d21a04dceb718ef.cif

正在转换auid-3d2aecf19ab4ec7d.cif
正在转换auid-3d778e9666a9f3ab.cif
正在转换auid-3e706628d4654aed.cif
正在转换auid-3f6b94dd181c38c2.cif
正在转换auid-3f9d963e597e2f41.cif
正在转换auid-3fa44c3f955170d5.cif
正在转换auid-4031cf187fbb42a9.cif
正在转换auid-404cf1be34705a20.cif
正在转换auid-40ee408f220875df.cif
正在转换auid-4160dedce30360b3.cif
正在转换auid-4287bcc84991c056.cif
正在转换auid-43284d5413f52f7c.cif
正在转换auid-432f5842ff000957.cif
正在转换auid-459d86edefe7ee64.cif
正在转换auid-4605fab75e2c693f.cif
正在转换auid-4638ccccec747ca3.cif
正在转换auid-46b1c772dbd25c18.cif
正在转换auid-46f7466ff4a3f3bf.cif
正在转换auid-46fa0417b97f7192.cif
正在转换auid-479e7e34b3a495cb.cif
正在转换auid-48d577dcabb27933.cif
正在转换auid-4a12043589a41efa.cif
正在转换auid-4a852842f37a3f03.cif
正在转换auid-4b249594b8890b14.cif
正在转换auid-4b4e8ea2b4205afd.cif
正在转换auid-4c6a534e7e2c81f2.cif
正在转换auid-4d1b5173827334d7.cif
正在转换auid-4ef36892c832100a.cif
正在转换auid-4ef70d0a8e6fe9a6.cif
正在转换auid-4f67d3506bef8668.cif
正在转换auid-4fc86684091e5110.cif
正在转换auid-51031c24e28b3c15.cif
正在转换auid-51d842abe6d04db1.cif
正在转换auid-51de706d83ef2009.cif
正在转换auid-51ff19b7c51eca01.cif
正在转换auid-52a6c21c9d4d83dd.cif
正在转换auid-52de2744fb222bff.cif
正在转换auid-544046909658be0d.cif
正在转换auid-54892d6f6e8fd5bf.cif
正在转换auid-548b0ceb3382ed02.cif
正在转换auid-54c97458265995fa.cif
正在转换auid-55052f108af09766.cif
正在转换auid-55ee22bed0757335.cif
正在转换auid-565713e82bc158d1.cif
正在转换auid-567488c7c4e23060.cif
正在转换auid-56aceb0efb7a491e.cif
正在转换auid-591cb9ca8aa5580b.cif
正在转换auid-5a269a82a97a34e2.cif
正在转换auid-5b1461536274cf9e.cif
正在转换auid-5bc154138f6142d8.cif
正在转换auid-5c6b54c2cdf77d96.cif
正在转换auid-5ced0dac114be47d.cif
正在转换auid-5f238e242b62b340.cif
正在转换auid-6062a6d1a047b50d.cif
正在转换auid-60a3978c7fe9f280.cif
正在转换auid-62175f9ac582c1c1.cif
正在转换auid-636476eb9f66705e.cif
正在转换auid-637cbc6f1f6b86ea.cif
正在转换auid-638b602c63f1a193.cif
正在转换auid-6451bdbd53ea4343.cif
正在转换auid-646985d1441b682c.cif
正在转换auid-64d9a98231f8873a.cif
正在转换auid-651cba2157cfb1ec.cif
正在转换auid-65ce5ff7106703ca.cif
正在转换auid-65d2a910d70cbc98.cif
正在转换auid-67181d290e5e1f95.cif
正在转换auid-68a98f1802e96743.cif
正在转换auid-693881e136df49d8.cif
正在转换auid-69c5faf194abe12f.cif
正在转换auid-6aba392510db7d60.cif
正在转换auid-6ac6dea19e1259e9.cif
正在转换auid-6bc1952611f6fd5e.cif
正在转换auid-6bc26a924ea91521.cif
正在转换auid-6c21ea0b117d1a7a.cif
正在转换auid-6cf0713ae91f1bb3.cif
正在转换auid-6cf3cd5430e26501.cif
正在转换auid-6dafbe8f9942185f.cif
正在转换auid-6e265dc0f787a634.cif
正在转换auid-6f61941e631bdef1.cif
正在转换auid-6f94c521d0b4ced3.cif
正在转换auid-702dc337c43d6c55.cif
正在转换auid-722cd1867d0c00d6.cif
正在转换auid-72cd314504695db3.cif
正在转换auid-76a0a477412a0872.cif
正在转换auid-778043fc91c2bc60.cif
正在转换auid-7a5b697ec8f0721f.cif
正在转换auid-7b703b65f1ae9e7b.cif
正在转换auid-7bac7b61e8397c99.cif
正在转换auid-7bfb7c0a140ff726.cif
正在转换auid-7c05e5a67ac28e76.cif
正在转换auid-7db795bd59a83f8f.cif
正在转换auid-7dfdb8aa263d845d.cif
正在转换auid-7e77de5acbceb681.cif
正在转换auid-7f53734282982d7e.cif
正在转换auid-7fa8db7e9ea41a0b.cif
正在转换auid-801e54a13787639b.cif
正在转换auid-825e40ff23fc5b73.cif
正在转换auid-82613d0139ff687c.cif
正在转换auid-82b40d050fc8572e.cif
正在转换auid-83ccc5b88659ec81.cif
正在转换auid-841e4c84058ca949.cif
正在转换auid-84d3f0b93522d2c5.cif
正在转换auid-85d9a51179ff4fdc.cif
正在转换auid-86035cae16555a20.cif
正在转换auid-8657d2ac01ef3fb6.cif
正在转换auid-87996f68f10c8ac3.cif
正在转换auid-894d4c5454ca2582.cif
正在转换auid-8964a0ea6ce00b9f.cif
正在转换auid-8ddb6be7830c283a.cif
正在转换auid-8e04bd60cb0ffb9f.cif
正在转换auid-8e5e0d17c44574ad.cif
正在转换auid-8fbfaad9613acfdd.cif
正在转换auid-909d81217f5bc67c.cif
正在转换auid-9261f31b8a9efc74.cif
正在转换auid-92eaef706307f117.cif
正在转换auid-9317c127f2a5a10e.cif
正在转换auid-935296c6d38d39fb.cif
正在转换auid-9417f6a618790569.cif
正在转换auid-946e4249b643f7d8.cif
正在转换auid-94faa7f56504af48.cif
正在转换auid-9666ee6b98ded30a.cif
正在转换auid-9678657e34b59d4e.cif
正在转换auid-96ce7185f36d7b56.cif
正在转换auid-97528ed96839c42d.cif
正在转换auid-990690c7c79ad824.cif
正在转换auid-9bfb5285b3d5a737.cif
正在转换auid-9c28b0f52f408f61.cif
正在转换auid-9d269f572d40bfc6.cif
正在转换auid-9da64a23437ef525.cif
正在转换auid-9dda00b1d4acd3f4.cif
正在转换auid-9ddae43dbefb8f4a.cif
正在转换auid-9e1a4ec11a9e0c86.cif
正在转换auid-9e1f9ae49af97ccb.cif
正在转换auid-9f2046b75ffcfe84.cif
正在转换auid-9f703bea9e9ab82c.cif
正在转换auid-9f8e737df21e486e.cif
正在转换auid-a0984177c53f1acf.cif
正在转换auid-a0d75513bcae7131.cif
正在转换auid-a1b56428ef2331c4.cif
正在转换auid-a207497ffe863d40.cif
正在转换auid-a2eb917c4c763593.cif
正在转换auid-a362ba020e165ff1.cif
正在转换auid-a3825e7b325a4e33.cif
正在转换auid-a48c2fe7d2001448.cif
正在转换auid-a4c23493ab82308f.cif
正在转换auid-a5017fea78c9ebf3.cif
正在转换auid-a57421a66b914183.cif
正在转换auid-a59d5b61a84119e5.cif
正在转换auid-a5a1fd6c6bfac509.cif
正在转换auid-a62eb847dc230326.cif
正在转换auid-a649c3e1f13421c8.cif
正在转换auid-a6984819f46f64d5.cif
正在转换auid-a6a4026a8da7b536.cif
正在转换auid-a71a53b9ded368c5.cif
正在转换auid-a8327da241fa9b7e.cif
正在转换auid-a857fbee783da22e.cif
正在转换auid-a929e4d0b1314641.cif
正在转换auid-aa8d3b22396bfade.cif
正在转换auid-ab4bc90f813ee2e5.cif
正在转换auid-ab9175c27a203b3b.cif
正在转换auid-ae25afd22077c0ab.cif
正在转换auid-af2458800fe4adcd.cif
正在转换auid-af8bc043d1cd493c.cif
正在转换auid-b0342d6d04a02751.cif
正在转换auid-b07f33e6706c1bd3.cif
正在转换auid-b084a46d4fd1ce83.cif
正在转换auid-b10f4f94d8a49490.cif
正在转换auid-b166a952f11a2f2b.cif
正在转换auid-b2b68c8495746617.cif
正在转换auid-b3b1e4191ce5a7c4.cif
正在转换auid-b491aec822a55ce2.cif
正在转换auid-b4bce9d7d3f7ff4d.cif
正在转换auid-b5213d77b4aa9d49.cif
正在转换auid-b5b76376ea0ba0b6.cif
正在转换auid-b6694ff17b55d64c.cif
正在转换auid-b70f450e29ae9364.cif
正在转换auid-b8326cebd0f49ab6.cif
正在转换auid-b87f9d9cd8f13b3b.cif
正在转换auid-b96db93178ea4465.cif
正在转换auid-b9d4a1e89546c3aa.cif
正在转换auid-ba38a7e89e63a4b7.cif
正在转换auid-ba6eace5b3ba0b2f.cif
正在转换auid-bb76132ea581aa20.cif
正在转换auid-bc689d981532fe9c.cif
正在转换auid-be93943c03f618c2.cif
正在转换auid-bf8eb4727e4ef621.cif
正在转换auid-bfca7f602035062c.cif
正在转换auid-c0cd1f40c80d1ddd.cif
正在转换auid-c14616ebe4191be1.cif
正在转换auid-c14ddf809852e068.cif
正在转换auid-c1b2b09e74efe692.cif
正在转换auid-c2524b8e23186e38.cif
正在转换auid-c2cf428849bb3fe2.cif
正在转换auid-c4458e6420ba758c.cif
正在转换auid-c46586633839a5e6.cif
正在转换auid-c54d41e38291a692.cif
正在转换auid-c5c2047343ec4fa6.cif
正在转换auid-c61ec68ac37ae281.cif
正在转换auid-c666f786856c910c.cif
正在转换auid-c9b62bad70743adc.cif
正在转换auid-c9d4377cc07017db.cif
正在转换auid-ca6d8179e3b9649d.cif
正在转换auid-cad514de8d7b79d0.cif
正在转换auid-cb365633e991caad.cif
正在转换auid-cba74cf68c13ebe1.cif
正在转换auid-ce1748a89fef90fe.cif
正在转换auid-ce44097956a5c77d.cif
正在转换auid-cfcff7698d39e0f3.cif
正在转换auid-d08777d67b8faf3c.cif
正在转换auid-d09dd7f2b68205a7.cif
正在转换auid-d1376c3325d8073b.cif
正在转换auid-d16cc1d30696d0f2.cif
正在转换auid-d19815fba3267109.cif
正在转换auid-d26523aa990e3386.cif
正在转换auid-d467b2ad5f145be9.cif
正在转换auid-d52936393034aef4.cif
正在转换auid-d5438061b2e74dad.cif
正在转换auid-d5e2e041bacd10dd.cif
正在转换auid-d6c058ffd85db7ab.cif
正在转换auid-d71cc05094b8bf23.cif
正在转换auid-d76d0779e786d867.cif
正在转换auid-d7c8aa637a3aed06.cif
正在转换auid-d8df320d0a818514.cif
正在转换auid-d9f14aea7257e7df.cif
正在转换auid-ddf081b3cf11cc45.cif
正在转换auid-de342d7cc5532c48.cif
正在转换auid-df62f65f0ffe544e.cif
正在转换auid-e17dc0b7a7f6e5ce.cif
正在转换auid-e20b7f7d30cfe155.cif
正在转换auid-e2100a60639827c4.cif
正在转换auid-e223c9e3c9e057f9.cif
正在转换auid-e2481553394d6cde.cif
正在转换auid-e38b28753804e038.cif
正在转换auid-e39a4a80bc91969f.cif
正在转换auid-e452f8ecaa576368.cif
正在转换auid-e8563de4bce2f481.cif
正在转换auid-eb9335e3d5510a98.cif
正在转换auid-eccf49971f16792f.cif
正在转换auid-ed977fc286255686.cif
正在转换auid-edeab50c62c6f7e8.cif
正在转换auid-edfc0cf28a255a02.cif
正在转换auid-ee575409e445e72c.cif
正在转换auid-ee748ce0cc4bd4fe.cif
正在转换auid-eed13b86d6bbef58.cif
正在转换auid-ef0fcf1bc3751761.cif
正在转换auid-ef4b95753ac9abb3.cif
正在转换auid-f1c3375b6f2b93d5.cif
正在转换auid-f1c584629e73a235.cif
正在转换auid-f1c8f9b531d12416.cif
正在转换auid-f44812d277474436.cif
正在转换auid-f4b666247de730c0.cif
正在转换auid-f5b9bcc1d3383bb6.cif
正在转换auid-f6306da1ab6da719.cif
正在转换auid-f6856ede036fe53e.cif
正在转换auid-f8f440144eb5dbfc.cif
正在转换auid-fa34895fd1ac095d.cif
正在转换auid-faa5a3abb6e88359.cif
正在转换auid-fc5bd3f876cf40e9.cif
正在转换auid-fc6f2667321a20a8.cif
正在转换auid-fc9b19266bb137a8.cif
正在转换auid-fcecee1aa40e551e.cif
正在转换auid-fd2581089ae2b96e.cif
正在转换auid-fd95455f272fe478.cif
正在转换auid-fe090b56eb7d1809.cif
正在转换auid-fe3bbc9796ee2a72.cif
正在转换auid-fee4c708d6d84c84.cif
正在转换auid-00a6f28f4223c38e.cif
正在转换auid-00dd4ee8b2d73bda.cif
正在转换auid-031faaa9f2d1e033.cif
正在转换auid-046c832aa3c3244d.cif
正在转换auid-04d532270efb670f.cif
正在转换auid-0732ce46bba34756.cif
正在转换auid-0740fcd31ad64b22.cif
正在转换auid-08dd2246a2026905.cif
正在转换auid-0a2125b43725e77d.cif
正在转换auid-0a2b89292fd6410c.cif
正在转换auid-0bde856b45e751cc.cif
正在转换auid-0dd66af34b67aa21.cif
正在转换auid-0fc1a2c065a1a1af.cif
正在转换auid-12b178cf9969164f.cif
正在转换auid-14379b4c594e35e7.cif
正在转换auid-17576ab0f299f43a.cif
正在转换auid-17b01ed51c510f33.cif
正在转换auid-17c320369b80fde4.cif
正在转换auid-1a893df8bb161f2c.cif
正在转换auid-1c813b5687e73447.cif
正在转换auid-1e00c70776da1250.cif
正在转换auid-1e8c70f662a3fd07.cif
正在转换auid-1f104e2f24efa89a.cif
正在转换auid-20a6db5caadf84f9.cif
正在转换auid-210f601d9c3f63b5.cif
正在转换auid-2117ba53713d1039.cif
正在转换auid-21e97f5d3c385c31.cif
正在转换auid-22d8d584e60528f6.cif
正在转换auid-232617c8deda167e.cif
正在转换auid-24d286f63e02efd3.cif
正在转换auid-26c146ddbb2732c5.cif
正在转换auid-2c98a3a5bc405137.cif
正在转换auid-2d9b25a13ece5a0c.cif
正在转换auid-2e7aed3cba5c3d26.cif
正在转换auid-2e7e8242f353c9b4.cif
正在转换auid-2f6a0ba43d825bd3.cif
正在转换auid-30d3350c09e2e6bd.cif
正在转换auid-32b6a2491dc051f9.cif
正在转换auid-32ca0a12b5f25e59.cif
正在转换auid-346475cfb84e3fc6.cif
正在转换auid-34b2780c6df047e6.cif
正在转换auid-356731382f7a33f1.cif
正在转换auid-36387d866371f3fd.cif
正在转换auid-37189b26c6d88951.cif
正在转换auid-3749a88e1dd10cf7.cif
正在转换auid-3a755950b41098fe.cif
正在转换auid-3a8c6207d225c13d.cif
正在转换auid-3adf2ce10a1d3f96.cif
正在转换auid-3f42dad70d3bd00b.cif
正在转换auid-42d08a4e6c31d48e.cif
正在转换auid-43e893c243cb3029.cif
正在转换auid-4836777a449c8009.cif
正在转换auid-48873d115f3412fc.cif
正在转换auid-48c1f31c474a590e.cif
正在转换auid-49314fb50fe5f576.cif
正在转换auid-4a43fec91be38c2a.cif
正在转换auid-4c6d3fb5693f5676.cif
正在转换auid-4cd03df8a30f5dfb.cif
正在转换auid-4d310c682b287402.cif
正在转换auid-4d4dc2b0193e01e5.cif

正在转换auid-4f67048a27a86efd.cif
正在转换auid-504b9cc758b85b0b.cif
正在转换auid-52ddc666974948a8.cif
正在转换auid-549437edfb9b8d4b.cif
正在转换auid-564419ad66d91082.cif
正在转换auid-56800889451c7945.cif
正在转换auid-56aa266086fc3805.cif
正在转换auid-57c1fbcd1c742b68.cif
正在转换auid-58f1ae3fb1e404ee.cif
正在转换auid-5a4563fa8a7ab6a6.cif
正在转换auid-5b0757339f1fc9d6.cif
正在转换auid-5cb21415fa9aab88.cif
正在转换auid-5d2fb9710e0c51d4.cif
正在转换auid-5e9b0d0e5016866f.cif
正在转换auid-5fa5dab4be0ae6d7.cif
正在转换auid-60602246fd418245.cif
正在转换auid-60befa4f48d94988.cif
正在转换auid-60cf8b656bdeea3d.cif
正在转换auid-6111458d2ef542a2.cif
正在转换auid-61114c251912f533.cif
正在转换auid-619c7a441288610c.cif
正在转换auid-61e20f2f6accbddd.cif
正在转换auid-6294a82f3fedd54f.cif
正在转换auid-63160a96fe16f5f0.cif
正在转换auid-6367acc17172eb17.cif
正在转换auid-64559d59746a61d9.cif
正在转换auid-64fe7bb3f42e5ce7.cif
正在转换auid-67066a6592ec0440.cif
正在转换auid-67e4364b6a52c772.cif
正在转换auid-6900e7b04c9cbcea.cif
正在转换auid-6975681558eb6cdc.cif
正在转换auid-69fac6ab450163a5.cif
正在转换auid-6b5a6c9ae52d41a3.cif
正在转换auid-6c4a357378baf236.cif
正在转换auid-6c701cf3dc72d476.cif
正在转换auid-6e1d40b778485f35.cif
正在转换auid-6e7ca5b910833bbb.cif
正在转换auid-71a0075c04dc13f3.cif
正在转换auid-72463dd18a8fd83c.cif
正在转换auid-7341bf3004fb4ae7.cif
正在转换auid-746f4076de888012.cif
正在转换auid-75438246a732a103.cif
正在转换auid-7574263cf38f9c2d.cif
正在转换auid-75dbc289b5be23c0.cif
正在转换auid-7805e14fb0b53ca9.cif
正在转换auid-78a9dd88f68adc46.cif
正在转换auid-7a9038de83fff6bf.cif
正在转换auid-7ad24d44b882c39c.cif
正在转换auid-7b7f919191e3fb3c.cif
正在转换auid-7cdcbf4fd83a8681.cif
正在转换auid-7e203f96a56965b4.cif
正在转换auid-7f2a13f0b6a2f7be.cif
正在转换auid-811b598ae5377b7b.cif
正在转换auid-816e0950b079a7db.cif
正在转换auid-822a7588042f9e71.cif
正在转换auid-8401b5be62cc6b7c.cif
正在转换auid-856c1f0f50bdd702.cif
正在转换auid-864f2b6c7ce32372.cif
正在转换auid-86da8e94b57e2bb2.cif
正在转换auid-87516c6653025aff.cif
正在转换auid-8843f7b0c40219cf.cif
正在转换auid-88ca7d55b9ec2013.cif
正在转换auid-8a6423b1f506ff98.cif
正在转换auid-8aecd51e00b97b3a.cif
正在转换auid-8afde8f751b6aae6.cif
正在转换auid-8c5011c882aac59e.cif
正在转换auid-8f0da5d68c43ded5.cif
正在转换auid-9089ea2636f2e3b2.cif
正在转换auid-912cd1cff7b1044b.cif
正在转换auid-941ae5bfdf0f7a00.cif
正在转换auid-94660e5968ec385b.cif
正在转换auid-95bd1aac30ec7a47.cif
正在转换auid-9886dac17c429525.cif
正在转换auid-99a9718b69d2d490.cif
正在转换auid-9a98f4a4b3f53a59.cif
正在转换auid-9b8856db83e076a8.cif
正在转换auid-9c9d2f23535e2961.cif
正在转换auid-9d2b075b178d94ca.cif
正在转换auid-9dab9f22d93a749f.cif
正在转换auid-9dd4d8c3ac2dc991.cif
正在转换auid-9e82ebd6c0eab17d.cif
正在转换auid-9f3c65fa123a9d62.cif
正在转换auid-a0eb547aa54852c7.cif
正在转换auid-a103777155bcb54a.cif
正在转换auid-a10c1cac4d1d6978.cif
正在转换auid-a1e91095913f16c3.cif
正在转换auid-a202589d5d2ca2e6.cif
正在转换auid-a260c7670f649fef.cif
正在转换auid-a27680163eb83a43.cif
正在转换auid-a47595f4f42056e4.cif
正在转换auid-a52f90ac8b43ef34.cif
正在转换auid-a8d4fd569cce4600.cif
正在转换auid-a995537aee9be53c.cif
正在转换auid-ab061f2e0b2562ce.cif
正在转换auid-ad61a4e59d186388.cif
正在转换auid-ada97c721e03617b.cif
正在转换auid-ae413833f5129114.cif
正在转换auid-ae9a7f0653c227d8.cif
正在转换auid-afe46eb797a99ed1.cif
正在转换auid-b419c0fccc0fe176.cif
正在转换auid-b5aa1612ca8856f1.cif
正在转换auid-b79a13c2e34fb8a5.cif
正在转换auid-ba2938a01bd2c98a.cif
正在转换auid-ba9d3e459f7adaf5.cif
正在转换auid-bb301cd94cbfd3f9.cif
正在转换auid-bc97161f250b6c1d.cif
正在转换auid-be58b9f5819f395a.cif
正在转换auid-be8dcdaf3d5b71ae.cif
正在转换auid-bf00ccba0dbf1494.cif
正在转换auid-c0384b8f019394cc.cif
正在转换auid-c1b450b7b0e637db.cif
正在转换auid-c2b98630ab957ecb.cif
正在转换auid-c65d8d9596a0d4c0.cif
正在转换auid-c7963fb0d41e80b5.cif
正在转换auid-c9fd91d1ff70dd06.cif
正在转换auid-cd22e0d75d9681c1.cif
正在转换auid-d021c3ece6cc6578.cif
正在转换auid-d079673c15cacefb.cif
正在转换auid-d1c5346be7fd2d90.cif
正在转换auid-d28c5371ec80d3c4.cif
正在转换auid-d49713b60138f075.cif
正在转换auid-d4df957d3ada5c83.cif
正在转换auid-d4ecb5249d666033.cif
正在转换auid-d57b07f1ad747820.cif
正在转换auid-d92fe61de0ac3f3a.cif
正在转换auid-db000d02167109ff.cif
正在转换auid-db08ad90e08cc447.cif
正在转换auid-db93f8a9a57e60f2.cif
正在转换auid-de6b922183f26702.cif
正在转换auid-deba9ebc6e356712.cif
正在转换auid-deed5f8df03d647c.cif
正在转换auid-dfe286ed0578d568.cif
正在转换auid-e1d6c8847a357991.cif
正在转换auid-e225b8f63e3da497.cif
正在转换auid-e234ae60b552082c.cif
正在转换auid-e2c36a42f9dfef1e.cif
正在转换auid-e3da7de123b776f6.cif
正在转换auid-e540a0d6cec9208d.cif
正在转换auid-e7a77b5ea676b637.cif
正在转换auid-ea25687b49447357.cif
正在转换auid-ea8e48a908aa89ff.cif
正在转换auid-eb064947e9229014.cif
正在转换auid-ec2438f50fc672d8.cif
正在转换auid-ec2f1bb67dd15d51.cif
正在转换auid-ec951e12343e42b6.cif
正在转换auid-ee5119e303892b21.cif
正在转换auid-ee744879af28cf8a.cif
正在转换auid-ee8fb1380add45c0.cif
正在转换auid-ef7d1c92c05360b0.cif
正在转换auid-f06464e1fad73f1e.cif
正在转换auid-f22211f9e2e38bf9.cif
正在转换auid-f2f6cf00606361b7.cif
正在转换auid-f3e7da4824facd63.cif
正在转换auid-f481b8e436a726b1.cif
正在转换auid-f5139f063fbcfabc.cif
正在转换auid-f5ca27808aa6082d.cif
正在转换auid-f8c859f0a4eb8e5b.cif
正在转换auid-fb27e4369d4aefc3.cif
正在转换auid-fd08ab47e8b4714c.cif
正在转换auid-fdbae04298e334a8.cif
正在转换auid-006482a62b41f65c.cif
正在转换auid-011779371f0ffb55.cif
正在转换auid-018fd5e5deba0db4.cif
正在转换auid-01d8ba5a132c8ca6.cif
正在转换auid-01e53bf4e6d1da18.cif
正在转换auid-0227e44cb32a211f.cif
正在转换auid-0278f76ed4fa180a.cif
正在转换auid-03d3c8e89dc76364.cif
正在转换auid-040fb24b4e39fde0.cif
正在转换auid-041b540442edaf37.cif
正在转换auid-043d9ec9fb563dc4.cif
正在转换auid-04fd4b888c0b4754.cif
正在转换auid-05bfc9e045e8776e.cif
正在转换auid-069c8b747f95e53e.cif
正在转换auid-06a2cde13cbce998.cif
正在转换auid-06af49413a52773b.cif
正在转换auid-07f19b9beb23c1ef.cif
正在转换auid-08e6debe1fd88923.cif
正在转换auid-08f2091be515f798.cif
正在转换auid-093ea717d67ab1fb.cif
正在转换auid-0944a2b793502b6f.cif
正在转换auid-09b1d7b694706e4d.cif
正在转换auid-09bc6e9fc9f9f38e.cif
正在转换auid-09bce0e3fbd2c235.cif
正在转换auid-0a5af3e4d7e7d48f.cif
正在转换auid-0af1fc7b650c3a59.cif
正在转换auid-0b5e4829903aa39f.cif
正在转换auid-0b8447b195ff1482.cif
正在转换auid-0bfcfb67ed6db870.cif
正在转换auid-0c003f73e0745f4e.cif
正在转换auid-0c169bd5fd9f70fe.cif
正在转换auid-0c4093c1c1625b24.cif
正在转换auid-0cf8cc02bf0407b1.cif
正在转换auid-0d9c1adea28a2787.cif
正在转换auid-0edbdfe2b4ac9cc8.cif
正在转换auid-0ef2902e9e83dea2.cif
正在转换auid-0f5edabedf6dd10a.cif
正在转换auid-1092d7c089fe19fd.cif
正在转换auid-1110935bf807d2ea.cif
正在转换auid-11d89d7fcdbcb7ec.cif
正在转换auid-12865828f2db7a06.cif
正在转换auid-13dc0a934d2dbc5e.cif
正在转换auid-14010098b57b8e63.cif
正在转换auid-144d517242dea501.cif
正在转换auid-14f0fc3458bd94eb.cif
正在转换auid-150b508ee7c3b5d8.cif
正在转换auid-15b9d48f237f92fc.cif
正在转换auid-160b07c74ce071c3.cif
正在转换auid-1653c3e02ef279ac.cif
正在转换auid-1668cfe369e766d6.cif
正在转换auid-16d660c3fc35f959.cif
正在转换auid-170dcdd74d781bec.cif
正在转换auid-173d88d16ca2c23b.cif
正在转换auid-1742f07f2ff6961e.cif
正在转换auid-174998614fe65170.cif
正在转换auid-175670d1e3cb0058.cif
正在转换auid-1816f886ab2dbfdc.cif
正在转换auid-18303d8428978f58.cif
正在转换auid-18b12eaee349ce7d.cif
正在转换auid-18f3088540644890.cif
正在转换auid-19a7530917ecba48.cif
正在转换auid-1a26aae716de8a5d.cif
正在转换auid-1a2ea48cc35a7ae1.cif
正在转换auid-1a99150fc089e2b8.cif
正在转换auid-1c71be2ad9a47520.cif
正在转换auid-1cb1eaa89ef9b7fe.cif
正在转换auid-1d77c7cbe3f651e5.cif
正在转换auid-1d86df4e647e6d03.cif
正在转换auid-1dbce8b33246c786.cif
正在转换auid-1e1a758f1cf97dfa.cif
正在转换auid-1ede23f8ef132b5e.cif
正在转换auid-1ef3b0201969ba5a.cif
正在转换auid-1f274feb72ecc677.cif
正在转换auid-1f6abd21d7454046.cif
正在转换auid-1fbb68b374faf509.cif
正在转换auid-210058313b9a44f4.cif
正在转换auid-210460c8c76636ac.cif
正在转换auid-2259e69097e3d354.cif
正在转换auid-2381ddd895fa9780.cif
正在转换auid-238f9ff712ae6bd3.cif
正在转换auid-23d4041c31346195.cif
正在转换auid-23f7ee2e019b3620.cif
正在转换auid-24bcd7ec722533c5.cif
正在转换auid-24f0ced4e2eb3efb.cif
正在转换auid-25587b5420d2df86.cif
正在转换auid-25fd895436c3b450.cif
正在转换auid-26b47f7a10e96b89.cif
正在转换auid-274657e4348f60fa.cif
正在转换auid-2785ae1f765004e4.cif
正在转换auid-27e05c04bf88e5d7.cif
正在转换auid-27e15661e4a11720.cif
正在转换auid-2884fddafcefe0ed.cif
正在转换auid-289adb8eefca111b.cif
正在转换auid-28d7847e43ec84cd.cif
正在转换auid-292f0ffc3f05aeae.cif
正在转换auid-29314e59196c4f6b.cif
正在转换auid-2985e9da260a5862.cif
正在转换auid-29c032bd7459ad66.cif
正在转换auid-2a778a3eb64b9e32.cif
正在转换auid-2ace8695bd6fbbb5.cif
正在转换auid-2acf1c9b7e1b8200.cif
正在转换auid-2b619f120f3d7d07.cif
正在转换auid-2e4b3ea14e191925.cif
正在转换auid-2eec399a03ae406c.cif
正在转换auid-2ef6e3034d29febc.cif
正在转换auid-2effd538e8825974.cif
正在转换auid-2fabbbedb81eb047.cif
正在转换auid-304712c628d5ac7b.cif
正在转换auid-3077d1f982571843.cif
正在转换auid-30f16be0558fd072.cif
正在转换auid-314c4c69805df9e0.cif
正在转换auid-3166e4b33276b29f.cif
正在转换auid-31be4990e44f5e94.cif
正在转换auid-31fa5a07a8bb82fc.cif
正在转换auid-333087f9f332f6d8.cif
正在转换auid-33912dc996507a44.cif
正在转换auid-33c9db920f2ad607.cif
正在转换auid-33f780ffe9fc6f8b.cif
正在转换auid-340261a94681ddc2.cif
正在转换auid-341730c79b48c5b3.cif
正在转换auid-342bfd4fee888cbb.cif
正在转换auid-346301fa00574851.cif
正在转换auid-34cd3620524a1376.cif
正在转换auid-3570f21abb434c09.cif
正在转换auid-36353c3818c2330e.cif
正在转换auid-370c78950ba6fcd7.cif
正在转换auid-371ffe642066fd5e.cif
正在转换auid-3836ab59c91c8768.cif
正在转换auid-387a8d6d82118a8b.cif
正在转换auid-38ac023dd37bdddf.cif
正在转换auid-38dc555bfd7e4e37.cif
正在转换auid-3905895430a3de2d.cif
正在转换auid-39806ad9ee3677e5.cif
正在转换auid-3a43db76dbcd1a59.cif
正在转换auid-3aaec0cf9b4253c0.cif
正在转换auid-3be339c6e198bdbf.cif
正在转换auid-3c4f0fd5aa3168bc.cif
正在转换auid-3d8f30df4251285e.cif
正在转换auid-3e03a25b0d512f6b.cif
正在转换auid-3e3f966a583d727e.cif
正在转换auid-3e6833d671c7c855.cif
正在转换auid-3efd7ae1271fc79b.cif
正在转换auid-3faae4eca53ebbc2.cif
正在转换auid-3fd2ef6b7e5d9dc0.cif
正在转换auid-404a43ddcdbb2763.cif
正在转换auid-41078035a92ab2d2.cif
正在转换auid-415d3951557e5a4e.cif
正在转换auid-422f1168867e88ea.cif
正在转换auid-430e3cb7cc662703.cif
正在转换auid-43113f3fcd056932.cif
正在转换auid-4336bc89f47968a0.cif
正在转换auid-43a2d89bc133f7aa.cif
正在转换auid-43e9b39bde073fb7.cif

正在转换auid-4414efa147660035.cif
正在转换auid-44832d5951923260.cif
正在转换auid-44fd39f9478adba3.cif
正在转换auid-45d68190d0079ae3.cif
正在转换auid-46cfcf53db21492d.cif
正在转换auid-47421480cd7fcc2a.cif
正在转换auid-478e79743d8cba9d.cif
正在转换auid-47fdacfff2d383d4.cif
正在转换auid-48b2887ac28d99ed.cif
正在转换auid-48c31ed924117453.cif
正在转换auid-49be3be40074d710.cif
正在转换auid-4a28a6a68206b6f2.cif
正在转换auid-4a92fb9bc28e663e.cif
正在转换auid-4aa75afe09f18609.cif
正在转换auid-4ae1cbf84a51c8d4.cif
正在转换auid-4b0977e212c4675d.cif
正在转换auid-4b23cd9516a63130.cif
正在转换auid-4b25a12aa2b1e36c.cif
正在转换auid-4b3fb863c3cc4757.cif
正在转换auid-4b4cabdae8f0ef4c.cif
正在转换auid-4b8bbea852cf7bc8.cif
正在转换auid-4c1fea3d50fa7abd.cif
正在转换auid-4c38227214566fcb.cif
正在转换auid-4ccbe0edec6e9cfa.cif
正在转换auid-4ccef930e5db205a.cif
正在转换auid-4d4c28d2c4f18d28.cif
正在转换auid-4d8c12fb9a01baf4.cif
正在转换auid-4e424ca662c49f46.cif
正在转换auid-4eabf2ce7546f280.cif
正在转换auid-4eb2c0ee667cc156.cif
正在转换auid-4f2eb669838c5ca9.cif
正在转换auid-4f78c7fd59cdafb9.cif
正在转换auid-4faeb0661e17a7a1.cif
正在转换auid-4fc76157068e78bf.cif
正在转换auid-503ca37eece6e987.cif
正在转换auid-5054684db4c65945.cif
正在转换auid-505676f0d70fb662.cif
正在转换auid-5143f56f0e2792c1.cif
正在转换auid-5164f9162e34c3fa.cif
正在转换auid-520caa9e17fd0146.cif
正在转换auid-522545a88bf7d85b.cif
正在转换auid-5276d9be5f5b3003.cif
正在转换auid-529e12cc754677fb.cif
正在转换auid-5464edf57d9db4ec.cif
正在转换auid-55ab80aca9e59929.cif
正在转换auid-55ee69478ddf4cf8.cif
正在转换auid-5618f9ee5e7e1dd7.cif
正在转换auid-56a2cad46a46721e.cif
正在转换auid-573ec353e276372a.cif
正在转换auid-577e39ae9605252b.cif
正在转换auid-58419ed8f7aa670e.cif
正在转换auid-5913d9e44df4be4a.cif
正在转换auid-59ac1c4a80ae105e.cif
正在转换auid-5a82b18d3bbaef50.cif
正在转换auid-5ae5fb2106697a36.cif
正在转换auid-5c07070d586e4ab3.cif
正在转换auid-5c397b5de5ec1855.cif
正在转换auid-5cb2ffad9329f652.cif
正在转换auid-5d21db3193143934.cif
正在转换auid-5d5fa2e397c979a5.cif
正在转换auid-5d759994f3a8f47c.cif
正在转换auid-5e642f8dfc435ece.cif
正在转换auid-5ebfcc61ec6bf5e9.cif
正在转换auid-5ef6e0b43156bc12.cif
正在转换auid-5fe02f34de17b5cc.cif
正在转换auid-5fe875d811f23fd6.cif
正在转换auid-609332ef5b79adaa.cif
正在转换auid-60a1c29f240ebd6b.cif
正在转换auid-60dace37225fbdbb.cif
正在转换auid-60e25fa15a84fdfa.cif
正在转换auid-615439d9b0e8109b.cif
正在转换auid-61bd8e1ae65f83e0.cif
正在转换auid-61fa18f754e09ab1.cif
正在转换auid-627136758f336c3d.cif
正在转换auid-62920544557d7c91.cif
正在转换auid-62f0534263841e53.cif
正在转换auid-62f9534752ac0b06.cif
正在转换auid-63aa1bd5ffe313a0.cif
正在转换auid-641692c55ec70910.cif
正在转换auid-644191528a45ad8e.cif
正在转换auid-6454035d9b2e6c02.cif
正在转换auid-64be1c6d0657e732.cif
正在转换auid-655d22ee6fab2aac.cif
正在转换auid-666888ac7f0d43e7.cif
正在转换auid-66ac4471a2e4e227.cif
正在转换auid-67a8dd2a37418e12.cif
正在转换auid-68256d90fde0d797.cif
正在转换auid-6841ac6a6071c781.cif
正在转换auid-6989448b1d1df0d3.cif
正在转换auid-69c2bc5a49b38ae7.cif
正在转换auid-6b330532dfc88f1a.cif
正在转换auid-6b59c02e118dabce.cif
正在转换auid-6c7fdef7aa921fea.cif
正在转换auid-6d13be9ad29f8ce7.cif
正在转换auid-6e4f67c780d73161.cif
正在转换auid-6e5530a622816951.cif
正在转换auid-6ebc1bda8d4b27a5.cif
正在转换auid-6f5fbfb5838fc091.cif
正在转换auid-707a0609f1fe0bee.cif
正在转换auid-71c246722c0817df.cif
正在转换auid-7289677ccdef1e90.cif
正在转换auid-737790b9fe337ce0.cif
正在转换auid-73b10ba342923df5.cif
正在转换auid-74db784e21c8ff62.cif
正在转换auid-74e13721563c72a6.cif
正在转换auid-755714cb00f70c57.cif
正在转换auid-7631a00511d9c839.cif
正在转换auid-764698cc6dc757a7.cif
正在转换auid-77f01cde0bf40778.cif
正在转换auid-7862ed1a47f2ce18.cif
正在转换auid-788c06fff6168356.cif
正在转换auid-79d7e898f11449d4.cif
正在转换auid-7a19dd006abf806f.cif
正在转换auid-7a4572e31f81e481.cif
正在转换auid-7ab0151f2da5f9b4.cif
正在转换auid-7adbda860bfb7efd.cif
正在转换auid-7b98e52e34f6efc5.cif
正在转换auid-7b9d2f8b1c6626be.cif
正在转换auid-7bda5613da6fd86f.cif
正在转换auid-7c57b96a4f661818.cif
正在转换auid-7c93d7e96dd1584d.cif
正在转换auid-7cfa56cdd16f1f8c.cif
正在转换auid-7e1e039bf9eda415.cif
正在转换auid-7e32983f95612777.cif
正在转换auid-7e689c5b79005c56.cif
正在转换auid-7fa18cc60c6eb4c6.cif
正在转换auid-7fc99b84ddeecd12.cif
正在转换auid-7ffddf4da7eb73e5.cif
正在转换auid-8020f4a74509695c.cif
正在转换auid-80ae7ded6074cb83.cif
正在转换auid-80e87143a367df7c.cif
正在转换auid-812a3d07329a3273.cif
正在转换auid-815c8af250e5fa91.cif
正在转换auid-8291fa24e8994116.cif
正在转换auid-82ac6a4081c242ce.cif
正在转换auid-82f747380b14b05d.cif
正在转换auid-835e6aef724704ec.cif
正在转换auid-8365e14c80e25f3f.cif
正在转换auid-85859e6d9b306e72.cif
正在转换auid-85a320d2bb74d58e.cif
正在转换auid-85c6f9eea85f9435.cif
正在转换auid-8695bafc1f81c477.cif
正在转换auid-86bbfbfd80155825.cif
正在转换auid-86e687c753dcabd4.cif
正在转换auid-874fe8b65e4628c4.cif
正在转换auid-87d40479e72c6e2c.cif
正在转换auid-87de054ac5c416e2.cif
正在转换auid-88c9d3f2935dab08.cif
正在转换auid-88feefd5fe99bbd6.cif
正在转换auid-897458902d61d8ff.cif
正在转换auid-89afd4f171dc20d5.cif
正在转换auid-8a15d2eba9cb921e.cif
正在转换auid-8a2d2cbca1cc54a5.cif
正在转换auid-8adb88ab4fad2b8e.cif
正在转换auid-8be2681708cfd94e.cif
正在转换auid-8dabcb48f268317b.cif
正在转换auid-8dc49f1c21a4c8a7.cif
正在转换auid-8f14d2ed1bf939a7.cif
正在转换auid-8f475d6abb1733ce.cif
正在转换auid-8fec49bc7dcfb0e0.cif
正在转换auid-900ca8566845920a.cif
正在转换auid-904bc942f4d94258.cif
正在转换auid-909b9444919bf931.cif
正在转换auid-91151dea9d10b41c.cif
正在转换auid-917a6688bb421fb1.cif
正在转换auid-91ae136175f6fce3.cif
正在转换auid-91eb3c1f1c6cab16.cif
正在转换auid-928f8c13f47ae015.cif
正在转换auid-9308bd5e978a50cc.cif
正在转换auid-945f7a08d89515e2.cif
正在转换auid-9490612e39f5032a.cif
正在转换auid-94d54b0297754fbd.cif
正在转换auid-9588d1e68e659bda.cif
正在转换auid-96183781ef9ea544.cif
正在转换auid-96e9f77fb739310b.cif
正在转换auid-97b0654631cae0ad.cif
正在转换auid-97d8f0f26b8dac2a.cif
正在转换auid-97e7cffa1cdce7b2.cif
正在转换auid-97ef682a2b644841.cif
正在转换auid-98885ae4767d8f87.cif
正在转换auid-98db856610f75f98.cif
正在转换auid-98f4d24f911df176.cif
正在转换auid-9972a10220b96cad.cif
正在转换auid-9a526d83af7b0015.cif
正在转换auid-9adcb090368889c7.cif
正在转换auid-9b0e66ccf732c27d.cif
正在转换auid-9b78df3c58c7fbe6.cif
正在转换auid-9be150c053fec5d6.cif
正在转换auid-9c16c8628c0472b7.cif
正在转换auid-9c7f1a37a713447f.cif
正在转换auid-9ccff23d902712db.cif
正在转换auid-9d16e8b6dc21a127.cif
正在转换auid-9d66abf570e46084.cif
正在转换auid-9d9515b5fbb592b3.cif
正在转换auid-9f1bdc6ee1549127.cif
正在转换auid-9f82d10b5ccc4d06.cif
正在转换auid-9faae1005d26f6fd.cif
正在转换auid-9fdf2a30939644f2.cif
正在转换auid-9feb994b870db183.cif
正在转换auid-a0358a31912df15b.cif
正在转换auid-a0dcc2d287c642c5.cif
正在转换auid-a0fb629928623f18.cif
正在转换auid-a1101382b6a7028f.cif
正在转换auid-a18d0a2000ba1afa.cif
正在转换auid-a1a3541a2280215c.cif
正在转换auid-a2faa1eac047e5a2.cif
正在转换auid-a3007ce68728a2a6.cif
正在转换auid-a3b4058f276a0edf.cif
正在转换auid-a3b49978c917c069.cif
正在转换auid-a3bfc9ebc9dd951d.cif
正在转换auid-a477d162cf07c31e.cif
正在转换auid-a51d05cac520cef9.cif
正在转换auid-a574edfa16522376.cif
正在转换auid-a62136d04eeb3fab.cif
正在转换auid-a6d367d30b15bce2.cif
正在转换auid-a77b81570bcfbb1c.cif
正在转换auid-a7b21ea3e0e7b5a5.cif
正在转换auid-a7cc4d5b480fcacb.cif
正在转换auid-a89374e9d1e8d33d.cif
正在转换auid-a8bb64b8aca87b00.cif
正在转换auid-a8c4df51f0ab918c.cif
正在转换auid-a9335c01246dc922.cif
正在转换auid-a9b207fd169102e2.cif
正在转换auid-aab7a9589402bdc1.cif
正在转换auid-ab2b7d26c0fe9b3b.cif
正在转换auid-ab63f89390904158.cif
正在转换auid-abcc421ab961c2b5.cif
正在转换auid-ac17727faaa6b4ad.cif
正在转换auid-ac9f5d5d7b370ec4.cif
正在转换auid-acc023c8c9fde277.cif
正在转换auid-ad5b8c29680d4f4b.cif
正在转换auid-ad5dcc13352398db.cif
正在转换auid-ae0301285834d81f.cif
正在转换auid-ae8fccd77e04673e.cif
正在转换auid-af228f70e5b22eb6.cif
正在转换auid-af79de5cebf181e3.cif
正在转换auid-afd81f4495e5bc00.cif
正在转换auid-b0c8e15a29d114d6.cif
正在转换auid-b16745ffe58a7a6c.cif
正在转换auid-b17c9221a94d6058.cif
正在转换auid-b1910106bb0a8c03.cif
正在转换auid-b1db3c968eb8262a.cif
正在转换auid-b2aafc2fd4d18dab.cif
正在转换auid-b42d0fa6b1f19ca6.cif
正在转换auid-b436b275755cac02.cif
正在转换auid-b7fb44ab11e3be9f.cif
正在转换auid-b8aaa93c28a6f81d.cif
正在转换auid-b8b7a3889eb0a5a9.cif
正在转换auid-b8fbc68f82f1f5c1.cif
正在转换auid-b977b634f180b369.cif
正在转换auid-ba0ad71bbc2a0105.cif
正在转换auid-ba24c7eeb3f5e889.cif
正在转换auid-bae1e14492891174.cif
正在转换auid-bb051df5e4aee000.cif
正在转换auid-bb6d0e78c2e52ae5.cif
正在转换auid-bbd858668637f840.cif
正在转换auid-bd608be349ba4865.cif
正在转换auid-bdbe4bd481406e7f.cif
正在转换auid-be0bbbd2d38c66ac.cif
正在转换auid-be651bcefbd280dd.cif
正在转换auid-be777a1870cfbdac.cif
正在转换auid-beb4536093129a7a.cif
正在转换auid-bf651ca6bac29540.cif
正在转换auid-c004ea3f2a22a412.cif
正在转换auid-c00a44964cd1bb18.cif
正在转换auid-c138923ad4d16dd1.cif
正在转换auid-c45f3fcdac8f858a.cif
正在转换auid-c479ad22412fb269.cif
正在转换auid-c5cec7ae8054022f.cif
正在转换auid-c5f92260a6180974.cif
正在转换auid-c68423b1e857aa36.cif
正在转换auid-c6c4878146f018d0.cif
正在转换auid-c6f8ea06d5fd21d1.cif
正在转换auid-c722534e024c55d9.cif
正在转换auid-c765cda1da7ba418.cif
正在转换auid-c798179dc6290b1f.cif
正在转换auid-c8c5081c9f420aac.cif
正在转换auid-c8f21b13ee7be34f.cif
正在转换auid-c99856b38c86e60d.cif
正在转换auid-c9f24d4c6598f1c7.cif
正在转换auid-ca4a90fe808dc1ec.cif
正在转换auid-cae0ee69954a0115.cif
正在转换auid-cbfbab2eb3309371.cif
正在转换auid-cc0400eff8fe0db1.cif
正在转换auid-cc4211a290a25fa1.cif
正在转换auid-ce97af01d37aae5e.cif
正在转换auid-cf2891cdda6b3a8d.cif
正在转换auid-cf620e5c0bd08199.cif
正在转换auid-cfaa76b5baad27a8.cif
正在转换auid-d09e318e89a6c678.cif
正在转换auid-d0e29b1995583497.cif
正在转换auid-d1c1a53a4921df6a.cif
正在转换auid-d205be01721029cf.cif
正在转换auid-d212085e6cf8ac9a.cif
正在转换auid-d2880b5ade8196b0.cif
正在转换auid-d31cf6de87d66e24.cif
正在转换auid-d36c675c3c1fc9df.cif
正在转换auid-d412ef8cf239d04a.cif
正在转换auid-d488f05fc2f44a84.cif
正在转换auid-d495e4bb1a6bfeae.cif
正在转换auid-d4df6ea88748b0ba.cif
正在转换auid-d58e353229ef2ed6.cif
正在转换auid-d61948b4d8d80e8e.cif
正在转换auid-d6ac84b28087e292.cif
正在转换auid-d6c5de6c5ca06357.cif
正在转换auid-d844408739705e09.cif
正在转换auid-d85d6fa9fdb69218.cif
正在转换auid-d904f0439e189b4e.cif
正在转换auid-d91d272fb0cffb0d.cif
正在转换auid-d9f74f02782d77a5.cif
正在转换auid-d9fd7659ff3d9866.cif
正在转换auid-dadf8be2b1d74718.cif
正在转换auid-db1c7aac1c260f12.cif
正在转换auid-dbb16ab8c07b4425.cif
正在转换auid-dbbfc6b77650a42c.cif
正在转换auid-dc14905a1f53f51a.cif
正在转换auid-dc4aeeccf1389cb8.cif

正在转换auid-dcb4d0788427812e.cif
正在转换auid-ddc2b354afc5c534.cif
正在转换auid-de22d50a77f94f01.cif
正在转换auid-de7ed18b5a79f464.cif
正在转换auid-de85529fb5d5128e.cif
正在转换auid-ded24d3091b02196.cif
正在转换auid-df14a57d47577f84.cif
正在转换auid-df17b44ab7f7d4e6.cif
正在转换auid-df99dfdfe0635f3f.cif
正在转换auid-dfdadd74697abeb9.cif
正在转换auid-e09e8042da9851b0.cif
正在转换auid-e0d9dcf730a58c2c.cif
正在转换auid-e156f03e1adb3b8e.cif
正在转换auid-e2068f1cfdee12d0.cif
正在转换auid-e21375a8ac0e166d.cif
正在转换auid-e2377725a00f6897.cif
正在转换auid-e37fe32db1fe34db.cif
正在转换auid-e47a775bf378f8d6.cif
正在转换auid-e4a5de8bc06743fe.cif
正在转换auid-e4e6532bf1063fbf.cif
正在转换auid-e4ef82cbffb7a8b3.cif
正在转换auid-e4f64fa182042bf5.cif
正在转换auid-e5110e54ce3ece7b.cif
正在转换auid-e555c5021816b9c0.cif
正在转换auid-e55a54f59e18281e.cif
正在转换auid-e6332421df9b4f9c.cif
正在转换auid-e7be4d46e5f1e2a4.cif
正在转换auid-e7d669b7ab257576.cif
正在转换auid-e80b07222b63d7fd.cif
正在转换auid-e9bf029dddc3cff1.cif
正在转换auid-ea31c1157d625c28.cif
正在转换auid-ea8b6262500b637f.cif
正在转换auid-eadfa0f50791e0a3.cif
正在转换auid-ec473888e877c5bb.cif
正在转换auid-ed08650e85b53d93.cif
正在转换auid-ed65411243fcc8dd.cif
正在转换auid-ed8094838e64f737.cif
正在转换auid-ed9c7f501b1d27cf.cif
正在转换auid-edce6ee05f33613a.cif
正在转换auid-ee4035bcb6369edf.cif
正在转换auid-eebce6aa28822cd9.cif
正在转换auid-eed4113d513b07af.cif
正在转换auid-eedd2202fc371f52.cif
正在转换auid-ef864418bea971b1.cif
正在转换auid-f0c5069834c2f37f.cif
正在转换auid-f155694dccf5acf4.cif
正在转换auid-f20ecf1ffd36610e.cif
正在转换auid-f21a4c0a1ec3642c.cif
正在转换auid-f2b93adc63180ce9.cif
正在转换auid-f38c8aa164460184.cif
正在转换auid-f3db0eac77e3a5a1.cif
正在转换auid-f44394ff84df9a5e.cif
正在转换auid-f45d2b96634cef66.cif
正在转换auid-f4d8d65dbba4fc42.cif
正在转换auid-f5375dde92c2eed0.cif
正在转换auid-f8b04ee7d341cbc5.cif
正在转换auid-f9d6ce19a8a26487.cif
正在转换auid-f9f012c781a9012b.cif
正在转换auid-fa2fc93f48c9e8d7.cif
正在转换auid-fa36fc0774964f79.cif
正在转换auid-faa07322c9ee11ed.cif
正在转换auid-faac4a061fb3fcf3.cif
正在转换auid-fac4d81fbc1b4ebd.cif
正在转换auid-faf2220912e12035.cif
正在转换auid-fb21734746ce9f4b.cif
正在转换auid-fb8526b89362f49b.cif
正在转换auid-fe23849e197c701b.cif
正在转换auid-fe717cffe0714527.cif
正在转换auid-fe8eb6d337a4fb06.cif
正在转换auid-00862f1db3e521a7.cif
正在转换auid-0122803de28f1b96.cif
正在转换auid-024dbd42d8d1aa36.cif
正在转换auid-02a11bbf6fe88518.cif
正在转换auid-03fde1c9ea600502.cif
正在转换auid-041f0041d824aead.cif
正在转换auid-06f88a69eca65143.cif
正在转换auid-072a667016ead53f.cif
正在转换auid-084c813b134d1fec.cif
正在转换auid-09c2a520da1a24b6.cif
正在转换auid-0ac349a4a469cec4.cif
正在转换auid-0b23fa34b08b8c2a.cif
正在转换auid-0b8d951bf928a04c.cif
正在转换auid-0bcb9d1a7333ede7.cif
正在转换auid-0d1b5f41aca30ac8.cif
正在转换auid-0d6dfc1ac707ce30.cif
正在转换auid-0f22823c087b7a93.cif
正在转换auid-0fd187544f7496e0.cif
正在转换auid-1286a94c276b4933.cif
正在转换auid-13e3400485bec40d.cif
正在转换auid-15f2a4d98841c462.cif
正在转换auid-1688d8cbf888afdc.cif
正在转换auid-1746d8289256ee4e.cif
正在转换auid-179ef7d59b434d2e.cif
正在转换auid-17b2430371864872.cif
正在转换auid-184fc9db0426abac.cif
正在转换auid-18d0f278fb956e4b.cif
正在转换auid-199d49ebbdbe7338.cif
正在转换auid-19dc9c3117449905.cif
正在转换auid-1a61dd9eb8322144.cif
正在转换auid-1b723a365bba648a.cif
正在转换auid-1cf2b73be2086e6a.cif
正在转换auid-1f667f8449ec31e2.cif
正在转换auid-1fbe2953daa8a6c2.cif
正在转换auid-1fdf67b81cde7fcd.cif
正在转换auid-20cbcc06801b9f89.cif
正在转换auid-2174e8dd78c62cbb.cif
正在转换auid-2190cc27df32ca15.cif
正在转换auid-21fac478ee19e18e.cif
正在转换auid-22ef7635da6672f8.cif
正在转换auid-2452db3d47679154.cif
正在转换auid-25ad3ac429694c76.cif
正在转换auid-28b788349bc818cb.cif
正在转换auid-29151626dd26b7e5.cif
正在转换auid-2a7e943b5db0d428.cif
正在转换auid-2b11a39a0717b5a8.cif
正在转换auid-2c6f446bc0852974.cif
正在转换auid-2e965f2c6671b75f.cif
正在转换auid-31242f4c71697ba8.cif
正在转换auid-3132500ab75ee050.cif
正在转换auid-313e3be214763c38.cif
正在转换auid-314533c9c6c19b61.cif
正在转换auid-31bc6b5198a41c5b.cif
正在转换auid-33283b133ec403ac.cif
正在转换auid-33d61f9dde108f5d.cif
正在转换auid-341c96c4f0c1cde0.cif
正在转换auid-3433a409133a38b7.cif
正在转换auid-3441342db79fb01d.cif
正在转换auid-34cfb581d9fcb2c6.cif
正在转换auid-3558b249d8961c89.cif
正在转换auid-3607008140ad53e5.cif
正在转换auid-382dbe8a8795834a.cif
正在转换auid-38b00512b4d3bd02.cif
正在转换auid-39681cd1983a7e86.cif
正在转换auid-397163b1a9792257.cif
正在转换auid-397dd28557fe1889.cif
正在转换auid-39c0dcce2b3560f1.cif
正在转换auid-3c52785ecd633147.cif
正在转换auid-3d65bb50901f99f5.cif
正在转换auid-3e94c119fce8fb25.cif
正在转换auid-3f7129b882e4c57b.cif
正在转换auid-4193a4230701c0eb.cif
正在转换auid-4202876fe52c8633.cif
正在转换auid-42f99d6eb1eee18b.cif
正在转换auid-4388dc23c427d58b.cif
正在转换auid-439232b5472c9b9c.cif
正在转换auid-4446e90cb76c2ba8.cif
正在转换auid-4598bb1935da8840.cif
正在转换auid-46f373672b1b1858.cif
正在转换auid-480eda0b99470a58.cif
正在转换auid-48320d59e966a25e.cif
正在转换auid-484df07a386590d0.cif
正在转换auid-49907a351cf33590.cif
正在转换auid-49cfa0e03552d5d8.cif
正在转换auid-49d91cab52612e0a.cif
正在转换auid-49fc1f8f49024f85.cif
正在转换auid-4a761a174433643f.cif
正在转换auid-4b7d5eb85b6b8f46.cif
正在转换auid-4c31e866d0eb802e.cif
正在转换auid-4cc44a3bc19f4487.cif
正在转换auid-4debd081eb5d6b02.cif
正在转换auid-4ef3e4550e01959b.cif
正在转换auid-4f3ef58fb8e766af.cif
正在转换auid-4fb296963266d58f.cif
正在转换auid-4fc39f1fd4611dd0.cif
正在转换auid-5062c9c2da65175f.cif
正在转换auid-5072e51b76f84441.cif
正在转换auid-507eea4f31aeaea1.cif
正在转换auid-509c32047a0cb8e5.cif
正在转换auid-50aac6887fc48e1c.cif
正在转换auid-52054b99e0898be5.cif
正在转换auid-521feaa61846db54.cif
正在转换auid-539755c4fc302081.cif
正在转换auid-5438808648c2a83f.cif
正在转换auid-5488dc6e0ff52d22.cif
正在转换auid-5542f51c6e6f6cf2.cif
正在转换auid-55b6a32da6bb8360.cif
正在转换auid-56731afe2fa0f32e.cif
正在转换auid-57184f22fa6402d3.cif
正在转换auid-5748ffaaa503801d.cif
正在转换auid-5753bcd8b2aff097.cif
正在转换auid-589fab850e3c8f45.cif
正在转换auid-58c275d2879a1553.cif
正在转换auid-5a4561ebd5870903.cif
正在转换auid-5aa6cf2a5883b45e.cif
正在转换auid-5ae8bbada3b2d2ae.cif
正在转换auid-5aeb4825f9e703f9.cif
正在转换auid-5baaa0259ebe8937.cif
正在转换auid-5cf73ab4e7c78b33.cif
正在转换auid-60678966e0e8ea5e.cif
正在转换auid-60e3a8179b4d8a6a.cif
正在转换auid-60ea14cf85c558e5.cif
正在转换auid-61206fa6660b0ca3.cif
正在转换auid-623bbbe5bd1ab26a.cif
正在转换auid-631c26581e0b4b99.cif
正在转换auid-64179da922dae098.cif
正在转换auid-6497bb489d80792b.cif
正在转换auid-652fdf131d193229.cif
正在转换auid-6540c16055e57be2.cif
正在转换auid-6542f1feabb04cb1.cif
正在转换auid-659aac601416ec87.cif
正在转换auid-666d6d7441711bf6.cif
正在转换auid-679a0955df30bbd2.cif
正在转换auid-67e5685e2d1f2320.cif
正在转换auid-68c387cbae0909f7.cif
正在转换auid-6964952bb1695de7.cif
正在转换auid-6ab1abcee99e859f.cif
正在转换auid-6b9b528a7aadc04b.cif
正在转换auid-6bd5cecb5a5c0c45.cif
正在转换auid-6c43bcb5a1fe71fa.cif
正在转换auid-6db2fe4861bcce9f.cif
正在转换auid-6e73fe701142c601.cif
正在转换auid-6ea029aa9f04d9c9.cif
正在转换auid-6f6b7021144d29b0.cif
正在转换auid-6fab1b7348901e80.cif
正在转换auid-6fc990d5b0d7a32c.cif
正在转换auid-708b567aa5fa9ce7.cif
正在转换auid-71c06ded50e35071.cif
正在转换auid-727230d8a67a3153.cif
正在转换auid-73427dbb490ff87b.cif
正在转换auid-73c909f4c91ae6c5.cif
正在转换auid-75a5074064a26a28.cif
正在转换auid-75e9a214380d64ce.cif
正在转换auid-75fffc8d659bd9bf.cif
正在转换auid-764c823708e409e9.cif
正在转换auid-766ad73614342b31.cif
正在转换auid-77c954442f9bcf78.cif
正在转换auid-79c1ccbc441a360c.cif
正在转换auid-7a2dad7935fb5fe2.cif
正在转换auid-7a64493502adceb6.cif
正在转换auid-7ad34927180d9cf9.cif
正在转换auid-7b1156eadbdf2e4c.cif
正在转换auid-7c4a508f3342974b.cif
正在转换auid-7c7316219d02c234.cif
正在转换auid-7cb363a7865ed687.cif
正在转换auid-7de7142b46801813.cif
正在转换auid-7ed9a411efcbaa9c.cif
正在转换auid-80161c0c63f809e1.cif
正在转换auid-80df06a6d6011454.cif
正在转换auid-81dfd9be8da926e8.cif
正在转换auid-832db5e20c14bee6.cif
正在转换auid-8537042a0337d976.cif
正在转换auid-8592cf8c06d5f24a.cif
正在转换auid-85ca839146d322fc.cif
正在转换auid-8668745591bff8e9.cif
正在转换auid-876b17362fd6dca0.cif
正在转换auid-8842a3a243410e4e.cif
正在转换auid-88b4277032972301.cif
正在转换auid-88cb12a889f78f8d.cif
正在转换auid-88dfc5eadd8b2177.cif
正在转换auid-8a1512e20ea00a38.cif
正在转换auid-8a2eba4761d701a0.cif
正在转换auid-8baf2e70e18c2e0e.cif
正在转换auid-8c51586443535a0c.cif
正在转换auid-8da468d665d877e0.cif
正在转换auid-8db5db046ccb2365.cif
正在转换auid-8dfd8c6ab1ca8cc3.cif
正在转换auid-8e971f47d70f8b07.cif
正在转换auid-8f79886f785c125d.cif
正在转换auid-9122b91ad109cb8f.cif
正在转换auid-91f9c560c9974759.cif
正在转换auid-922809010776b117.cif
正在转换auid-9247c7ce0a6d8ba8.cif
正在转换auid-92a24a35ae5ce4ab.cif
正在转换auid-93ea24b33f1d93ed.cif
正在转换auid-94ef15c6fd494c2c.cif
正在转换auid-95cf5dbcded094f6.cif
正在转换auid-962a60960b88f7e9.cif
正在转换auid-96564ae399a173c3.cif
正在转换auid-97b02a7cfe209548.cif
正在转换auid-97c17d3a7d2e3f1f.cif
正在转换auid-97db5ce0bb2c11ae.cif
正在转换auid-98bb767255545655.cif
正在转换auid-99ecb4d72048797d.cif
正在转换auid-99f4e6efa92a67c5.cif
正在转换auid-9b5d611322119f0a.cif
正在转换auid-9c0038ccb67440b1.cif
正在转换auid-9e9b8d38fcfcec11.cif
正在转换auid-9eb70a65647af891.cif
正在转换auid-9f297363e433a44a.cif
正在转换auid-9fae54c423c14caa.cif
正在转换auid-9ffac295c693b993.cif
正在转换auid-a057a8fb466a53b1.cif
正在转换auid-a13d6cc4b01aeda9.cif
正在转换auid-a19795aec1e36eae.cif
正在转换auid-a23ce39b61a5a9ce.cif

正在转换auid-a2b2c17642029dc1.cif
正在转换auid-a38faaf500ff7f76.cif
正在转换auid-a3e237c01ac9344a.cif
正在转换auid-a50f5ac144f0bcb1.cif
正在转换auid-a64865b738acdca0.cif
正在转换auid-a81daf64d6ecf2b6.cif
正在转换auid-a83b3f742e5573f8.cif
正在转换auid-a85db85bc9de16a1.cif
正在转换auid-aa12329c15f755c2.cif
正在转换auid-aacc612c086c3f74.cif
正在转换auid-ab44b9b478001296.cif
正在转换auid-ab53fafcf4124d5c.cif
正在转换auid-ad1e9857a00bfcdf.cif
正在转换auid-addcfb7052f26de8.cif
正在转换auid-ae52006d43ff232b.cif
正在转换auid-ae5d4cf262521f94.cif
正在转换auid-af1fa05c43a2ff6d.cif
正在转换auid-af576b56be87b88b.cif
正在转换auid-b114ce40f909756e.cif
正在转换auid-b178a22156057694.cif
正在转换auid-b20312769497572d.cif
正在转换auid-b22f7570236395aa.cif
正在转换auid-b2a63477f9af95ed.cif
正在转换auid-b3544dd73ea7d5fa.cif
正在转换auid-b5694e5a900a3402.cif
正在转换auid-b5a68a2db2255256.cif
正在转换auid-b6eb0643a4f5a30d.cif
正在转换auid-b7e15a169b383ede.cif
正在转换auid-b7e42b76c4e83a6b.cif
正在转换auid-b83d1b865b5ac15c.cif
正在转换auid-b85828806bd06277.cif
正在转换auid-b9ee3c08772f885f.cif
正在转换auid-bbb2894158e10655.cif
正在转换auid-bc98ab0465b46d53.cif
正在转换auid-bd6111f7604b86b8.cif
正在转换auid-be8fc06bcdb68e9b.cif
正在转换auid-bff6b909c4aeea57.cif
正在转换auid-bff7bd8ed9bc3be0.cif
正在转换auid-c085ea032f1127c7.cif
正在转换auid-c18d0fbbf182d228.cif
正在转换auid-c1b7f418ed21fd5b.cif
正在转换auid-c2c037d5a2852ea9.cif
正在转换auid-c2e62374d4ff9f5f.cif
正在转换auid-c39fb621ecf816c5.cif
正在转换auid-c3b23541472194fc.cif
正在转换auid-c4ca5197e053932d.cif
正在转换auid-c587295e941fdca3.cif
正在转换auid-c720c37cc1425461.cif
正在转换auid-c81a40868154f14a.cif
正在转换auid-c826ca691d923fae.cif
正在转换auid-ca4f570fcd33a41c.cif
正在转换auid-cba3e9cfe5624b0c.cif
正在转换auid-cbaf0f596a075c7d.cif
正在转换auid-cd0ba43560001fbc.cif
正在转换auid-d02830c340b6f1b5.cif
正在转换auid-d0fb0d220259433f.cif
正在转换auid-d1215bd849f0dd71.cif
正在转换auid-d134af6b0bde3354.cif
正在转换auid-d1516a6f9b32f450.cif
正在转换auid-d1de5897109649aa.cif
正在转换auid-d230af0b67bab10e.cif
正在转换auid-d6efa1c7df441561.cif
正在转换auid-d8558ced4c149cd3.cif
正在转换auid-d8f3314acc4c20d7.cif
正在转换auid-d9481dc4bbdd060e.cif
正在转换auid-dbdb689a71613c5a.cif
正在转换auid-dc6313b5f55160fc.cif
正在转换auid-dc9b0e76f2f5e01d.cif
正在转换auid-dcd5acd1540e188f.cif
正在转换auid-dcf93ce9735d851a.cif
正在转换auid-e018ae9625e1f9de.cif
正在转换auid-e0c0b8d9e2040b42.cif
正在转换auid-e217f11ba13cc434.cif
正在转换auid-e2290715e8c50bf7.cif
正在转换auid-e28ec23ea82ea571.cif
正在转换auid-e2dae4fba145879b.cif
正在转换auid-e487944ec9361c72.cif
正在转换auid-e5135dea7f87bbf3.cif
正在转换auid-e710f1452cf5131f.cif
正在转换auid-e76ee008360f0ffe.cif
正在转换auid-e88d7080b008b69c.cif
正在转换auid-e8ad42064b80e4e8.cif
正在转换auid-e9c558da30cc0b0e.cif
正在转换auid-ea4e13db196c88cf.cif
正在转换auid-ea821aa5c732d780.cif
正在转换auid-eb9ec909985a952d.cif
正在转换auid-edb577043bff211d.cif
正在转换auid-f0c728db5116c074.cif
正在转换auid-f27654caf7c7c84e.cif
正在转换auid-f2e9f10f400e5823.cif
正在转换auid-f4e323428628ae72.cif
正在转换auid-f64910d617d016cd.cif
正在转换auid-f654fee054457253.cif
正在转换auid-f6afd2f50af4e521.cif
正在转换auid-f6e5994aee924b46.cif
正在转换auid-f798aa734295c56f.cif
正在转换auid-f7bf2007640b466b.cif
正在转换auid-f8c58af10748ef5f.cif
正在转换auid-f9ba08cf2692fa30.cif
正在转换auid-fa345b6acef6e780.cif
正在转换auid-fa3e9b71b1a7f347.cif
正在转换auid-fa80758131f14289.cif
正在转换auid-fa80a021d1999d35.cif
正在转换auid-fb3c1d113516a87a.cif
正在转换auid-fc079abb25d36012.cif
正在转换auid-fc1c5dd54dc8f765.cif
正在转换auid-fccec860832c8fa1.cif
正在转换auid-fd5360b7b3488e42.cif
正在转换auid-fe29f93047c50dd1.cif
正在转换auid-ff1732eecc0b49aa.cif
正在转换auid-ff9d50f2332e6203.cif
正在转换auid-0128a56e28f9b264.cif
正在转换auid-01f12ee5f76cac19.cif
正在转换auid-026efcfa8ac124a5.cif
正在转换auid-02afa3c98f17094e.cif
正在转换auid-0304ce19f06c3fd5.cif
正在转换auid-03234419890fe903.cif
正在转换auid-04508693b1cf45e9.cif
正在转换auid-045a401f97c3cf35.cif
正在转换auid-0479390025285365.cif
正在转换auid-05c5b048d5c12e30.cif
正在转换auid-060e228a37a8efa7.cif
正在转换auid-08502d5b49d87f58.cif
正在转换auid-0984c4670ca3c690.cif
正在转换auid-0b953124151aedab.cif
正在转换auid-0c9a2a820750fb5d.cif
正在转换auid-0ca0d7e833190e0e.cif
正在转换auid-119f5af74eb46eab.cif
正在转换auid-11e1caf6865cf961.cif
正在转换auid-11e5abd93578c0b4.cif
正在转换auid-129df439e00e1007.cif
正在转换auid-12a2bfe7c9b708f1.cif
正在转换auid-14318e5f229b449e.cif
正在转换auid-1662096e5a28358f.cif
正在转换auid-16996d4289b8e099.cif
正在转换auid-16a18157d9c31989.cif
正在转换auid-188d6b1074a5ce43.cif
正在转换auid-18d9bc27964f9d11.cif
正在转换auid-18fb49af8c5e9386.cif
正在转换auid-1d1fd0db79c6e5b3.cif
正在转换auid-1e1411de9a715ff5.cif
正在转换auid-1ebc390cfeaf7293.cif
正在转换auid-1fd10a385fac7ce5.cif
正在转换auid-2013bf87bbf88e7e.cif
正在转换auid-20b12c5ce020f3fb.cif
正在转换auid-218ac104f02bc4e2.cif
正在转换auid-219615cac97baae6.cif
正在转换auid-2222a045d0140ee3.cif
正在转换auid-22428ac514d75540.cif
正在转换auid-2322ba19f636a797.cif
正在转换auid-239a80dc7b412a19.cif
正在转换auid-23e60803faaf30a0.cif
正在转换auid-24304c6faf3d0e3c.cif
正在转换auid-282a4691671a3e23.cif
正在转换auid-285fd04b13df8ca3.cif
正在转换auid-2962ff4b7c29ebd1.cif
正在转换auid-29d1cfbe7a942947.cif
正在转换auid-2ace8ef00cd87c14.cif
正在转换auid-2e98bf147f84de76.cif
正在转换auid-2ec9a07d333f57bc.cif
正在转换auid-313ea3cd068c27d6.cif
正在转换auid-34946d9ce4d1de89.cif
正在转换auid-3675cac6a82b8b36.cif
正在转换auid-3872e5522702d538.cif
正在转换auid-3994d3edbf1f221f.cif
正在转换auid-39af3f4330823891.cif
正在转换auid-39dba407fdeb7173.cif
正在转换auid-3bb4b7d9e0daa579.cif
正在转换auid-3e0233fa33f55405.cif
正在转换auid-3e33f96b94b2a3eb.cif
正在转换auid-3fbe0b5a9d12156e.cif
正在转换auid-41d56ec33d496c66.cif
正在转换auid-41fe050aa4c5fb82.cif
正在转换auid-423a646ad43f5917.cif
正在转换auid-442cd8637ab7d828.cif
正在转换auid-445f720ecb371ea6.cif
正在转换auid-44a7dece9d8d857d.cif
正在转换auid-44b5f7c58a6ac4da.cif
正在转换auid-464a7d540986d95a.cif
正在转换auid-4780ea76d6343344.cif
正在转换auid-48fab77700dd07f6.cif
正在转换auid-490710701372c23f.cif
正在转换auid-4b063265cb9ced17.cif
正在转换auid-4b13639fa54f1773.cif
正在转换auid-4eadc3b85cc226b6.cif
正在转换auid-4f4a53999f9bc2a6.cif
正在转换auid-515d32f8d54fcf5f.cif
正在转换auid-51671dc80dcee45d.cif
正在转换auid-518c4083019f3190.cif
正在转换auid-52148dfcc0bebf36.cif
正在转换auid-522ec4f3194763a2.cif
正在转换auid-5292d2b4c372f1c0.cif
正在转换auid-52da893c958828a4.cif
正在转换auid-54dad9105351a3da.cif
正在转换auid-55b71cbb362428c6.cif
正在转换auid-572af2de9e54ce92.cif
正在转换auid-58196119cfae1e4c.cif
正在转换auid-58555482669a4cdf.cif
正在转换auid-592173cf6a302e04.cif
正在转换auid-5aefdf281b65705f.cif
正在转换auid-5b07f522dcbf68dd.cif
正在转换auid-5effbf440a0d1117.cif
正在转换auid-601f583a1150da60.cif
正在转换auid-61e99f357b13209d.cif
正在转换auid-64998285d64123dc.cif
正在转换auid-65db3b75e088185a.cif
正在转换auid-669bd2cfb187cda4.cif
正在转换auid-66b41b14113d5eb9.cif
正在转换auid-6a0d57b1e27af072.cif
正在转换auid-6bc32510548fb632.cif
正在转换auid-6bdfdf88d3782ad8.cif
正在转换auid-6cdeb890ad7441c3.cif
正在转换auid-6d351599c86a0cb7.cif
正在转换auid-6f1a2e231844ab22.cif
正在转换auid-6f7965fd3e1fba72.cif
正在转换auid-6fd2711f5679034c.cif
正在转换auid-6fd44ff25277a2be.cif
正在转换auid-7084649208618fea.cif
正在转换auid-71306837517be192.cif
正在转换auid-720babd42843fee6.cif
正在转换auid-7327cd2c3e6c61db.cif
正在转换auid-74cd9ad75298921f.cif
正在转换auid-770cbee008afb637.cif
正在转换auid-7881fe6698110031.cif
正在转换auid-7bf48058da191996.cif
正在转换auid-7d92b2a174c5374a.cif
正在转换auid-7e129f7adb532af3.cif
正在转换auid-7fad1d1cd855e478.cif
正在转换auid-807d09f6b6f12533.cif
正在转换auid-8180fdab6654d1f8.cif
正在转换auid-81bf29f9a290720c.cif
正在转换auid-82d2b8ca54fd1132.cif
正在转换auid-83330e9c606b3c0e.cif
正在转换auid-84c54a3b4e0105e3.cif
正在转换auid-84d2955b9d201198.cif
正在转换auid-84f03f4a1f992271.cif
正在转换auid-865c4f1161c9ed9f.cif
正在转换auid-869800e1a8cd90dc.cif
正在转换auid-8976c1cc6067ffb1.cif
正在转换auid-8a10f81b529ee797.cif
正在转换auid-8b94dc75c3dd8927.cif
正在转换auid-8c10cf99b344654c.cif
正在转换auid-8d9b37f8ad6a735d.cif
正在转换auid-8e51b31b2a247051.cif
正在转换auid-9101420bf55097f4.cif
正在转换auid-91b7460c9aaf16fc.cif
正在转换auid-91bfdc44fdc630df.cif
正在转换auid-92625d8fa8e78c73.cif
正在转换auid-932da84430c6fddf.cif
正在转换auid-939ff06696e2e345.cif
正在转换auid-941a293795bcbe48.cif
正在转换auid-942a39ada6260cdc.cif
正在转换auid-9455662dba75ef8b.cif
正在转换auid-94fab560599750f4.cif
正在转换auid-95a67f1fc470e294.cif
正在转换auid-9613023b44c6a12d.cif
正在转换auid-9640fb5201071220.cif
正在转换auid-96609fa0bb9dd40d.cif
正在转换auid-96925f628cd76453.cif
正在转换auid-96954e50aece5a43.cif
正在转换auid-96e6fd45ec6348dc.cif
正在转换auid-96f5631d16758f2a.cif
正在转换auid-971514e967edd296.cif
正在转换auid-979c4cbec62d4e42.cif
正在转换auid-979d023a02c26286.cif
正在转换auid-97f81a4e792cbd2d.cif
正在转换auid-989c5b590837693a.cif
正在转换auid-9b6b28d33379e181.cif
正在转换auid-9baf27fc656317a8.cif
正在转换auid-9f0ccc2eae30fd92.cif
正在转换auid-9f23bae8a22e8bd5.cif
正在转换auid-a0d9a6180171e4c3.cif
正在转换auid-a16e8c6bd68bfbd6.cif
正在转换auid-a17485a6cc61528c.cif
正在转换auid-a18263618f21343b.cif
正在转换auid-a1905922ce8c11cb.cif
正在转换auid-a390dc485938a040.cif
正在转换auid-a423e97e9097d398.cif
正在转换auid-a49d01bacf8099e7.cif
正在转换auid-a5df41c2e84007b4.cif
正在转换auid-a6eed46fe8574541.cif
正在转换auid-a7cb3572ba9c48bf.cif
正在转换auid-aa3d02d0ac9fa15f.cif
正在转换auid-aaff54e8fff208f9.cif
正在转换auid-abf921c5a8083eec.cif
正在转换auid-adbd4a7a21764aca.cif
正在转换auid-addb148a4c36bb93.cif
正在转换auid-ae0f545c25d3d931.cif
正在转换auid-af5d282011745315.cif
正在转换auid-b14d4bcd7e0bc036.cif
正在转换auid-b306bc75da3e9dff.cif
正在转换auid-b32abb0a105f4fef.cif
正在转换auid-b69594d7cb98d329.cif
正在转换auid-b6b2cdaf0bec0488.cif
正在转换auid-b7611407a984a806.cif
正在转换auid-b8b1734ee517020b.cif
正在转换auid-b9d18ef72aa67ccf.cif
正在转换auid-bb700403afd1bd41.cif
正在转换auid-bc2816fc69858b16.cif
正在转换auid-bd1fe6f73218d66a.cif
正在转换auid-be07f59c2c1607f8.cif
正在转换auid-c0537e4540086331.cif
正在转换auid-c0eaa5983a1dbf32.cif
正在转换auid-c0ffe1916982025d.cif
正在转换auid-c107cae5548d778b.cif
正在转换auid-c2035ad5d3817773.cif
正在转换auid-c31f1732cc969949.cif
正在转换auid-c367ce5885b6a0a5.cif
正在转换auid-c3e14695b821b548.cif
正在转换auid-c52eac006b53bd53.cif
正在转换auid-c585a38eee2232bb.cif
正在转换auid-c81ba38d0d2d6925.cif
正在转换auid-c922854ec9610bd2.cif
正在转换auid-cbd0340cb7cbe86f.cif
正在转换auid-ccb40ab5aa195d7b.cif
正在转换auid-cdd3a2fb614b7d6a.cif
正在转换auid-ceefa8fd07c7a31a.cif
正在转换auid-cf1277e5cae3f730.cif
正在转换auid-d075430566bcde39.cif
正在转换auid-d0ad1d1afa478bde.cif
正在转换auid-d110ba5ef6ca70cf.cif
正在转换auid-d11e56c75caa2e05.cif
正在转换auid-d266d751df332511.cif
正在转换auid-d34875f2f58efaf4.cif
正在转换auid-d5d4e861bf6f9e76.cif
正在转换auid-d60d5854bfb1bcc0.cif
正在转换auid-d8359f563ef4d643.cif
正在转换auid-d8ae03047e1061ec.cif
正在转换auid-d8ae86492f197506.cif
正在转换auid-d8ea6420c3c6fee0.cif
正在转换auid-dc4c7cf72b30c2b1.cif
正在转换auid-dd6f20bdf7da4aeb.cif
正在转换auid-de374333538300f3.cif
正在转换auid-df6aac9dbac279dc.cif
正在转换auid-e05fa4f51fb96287.cif
正在转换auid-e75ae8b23e4e7e15.cif
正在转换auid-e773ce633486abaf.cif
正在转换auid-e85b284e51c742b7.cif
正在转换auid-ebb928984fea0336.cif
正在转换auid-ebccf4a107e823c2.cif
正在转换auid-ec8f04f277b626db.cif
正在转换auid-edbd1ff9cbd3c34b.cif
正在转换auid-ee29da5e4edc452b.cif
正在转换auid-ef4c4e7acdaa85cd.cif
正在转换auid-efdee50bc5cb502c.cif
正在转换auid-f0d69bd96dea9394.cif
正在转换auid-f1142c09f1f6bc1f.cif
正在转换auid-f320167580606dd0.cif
正在转换auid-f3fc6b745d3032cf.cif
正在转换auid-f4163077baaeee11.cif
正在转换auid-f4f3f6f96813489f.cif
正在转换auid-f6da9c67bd08be4a.cif
正在转换auid-f933956256728629.cif
正在转换auid-f9c4932bb98e1585.cif
正在转换auid-faa002e9623a2ab3.cif
正在转换auid-fb2567b62fecf279.cif
正在转换auid-fb6cb7523ab038e5.cif
正在转换auid-fbb07d2a8ef3871d.cif
正在转换auid-fca16359b2c3d6f2.cif
正在转换auid-ff650c494a4fc3b6.cif
正在转换auid-ffbbd91d88cc9a4a.cif
正在转换auid-ffc21ee9c9e9bed1.cif
正在转换auid-0042b23d19404464.cif
正在转换auid-022fe6792618f8b4.cif
正在转换auid-061cc73a3b6e09d1.cif
正在转换auid-06f720e7fc71b6b1.cif
正在转换auid-0a538b9b92ec625c.cif
正在转换auid-0c2410c45c81b51c.cif
正在转换auid-0c7aa49f12d926c8.cif
正在转换auid-0cf50d56971c5d9c.cif
正在转换auid-0d25877ce7ec660d.cif
正在转换auid-0d7ded83ee7cb523.cif
正在转换auid-117a6f68b95d0937.cif
正在转换auid-126eb03a5f1489d3.cif
正在转换auid-12fb19fb8e4595fa.cif
正在转换auid-139da0dcba23868a.cif
正在转换auid-13f0a3bfe22166e3.cif
正在转换auid-140bdaa38feb8a77.cif
正在转换auid-15f87a227b7bc605.cif
正在转换auid-15fd4fe18a27717f.cif
正在转换auid-16b78dd3f4052d02.cif
正在转换auid-1739f4eeb8cd7705.cif
正在转换auid-17c60808819c7561.cif
正在转换auid-17e284219c3e16ef.cif
正在转换auid-1803d07336d3ee33.cif
正在转换auid-18e65c3e13038772.cif
正在转换auid-1ae903b57ffb8673.cif
正在转换auid-1c3425306ebaa3ab.cif
正在转换auid-1ccd37d934d0cdc5.cif
正在转换auid-1cee33b1b22e2b17.cif

正在转换auid-2075d83b86d11393.cif
正在转换auid-219e4ae67bdd26a5.cif
正在转换auid-22eda5e6b2671935.cif
正在转换auid-2354e9dba8319f82.cif
正在转换auid-2430cecb5ed949e0.cif
正在转换auid-2501b691830ff5bf.cif
正在转换auid-25ac9ace1dd4fc8f.cif
正在转换auid-285fc82a670cd9c6.cif
正在转换auid-288ccec29d525bd5.cif
正在转换auid-28cf37033b0d58a6.cif
正在转换auid-299ccfa463aff773.cif
正在转换auid-29c673724e09566c.cif
正在转换auid-2bd70939b561659b.cif
正在转换auid-2d0f6cb109288afb.cif
正在转换auid-2eac04b712d62a72.cif
正在转换auid-32886ff4441e7a5c.cif
正在转换auid-3386413c54e25c43.cif
正在转换auid-34e4e120203aa298.cif
正在转换auid-3501ae0fc5147843.cif
正在转换auid-35d93ab143d53637.cif
正在转换auid-37f1acc8eac85a34.cif
正在转换auid-37f4cc26d94abd5b.cif
正在转换auid-394080bb08b45a25.cif
正在转换auid-3a127c3d34a3c0cd.cif
正在转换auid-3ac186748b49696b.cif
正在转换auid-3b5b2ab560447541.cif
正在转换auid-3e71c6709250122f.cif
正在转换auid-3eb87977283d2b85.cif
正在转换auid-4144f34be8c9bf6d.cif
正在转换auid-41491021eafaa99d.cif
正在转换auid-418d67e87061fae6.cif
正在转换auid-48055fe2b96c7e6b.cif
正在转换auid-496db13ceaaabe42.cif
正在转换auid-4b9bde633c720438.cif
正在转换auid-4e788f914af52aac.cif
正在转换auid-4edb50a6c06d97c0.cif
正在转换auid-4f2096086c324cdd.cif
正在转换auid-4f32e509db805b62.cif
正在转换auid-4fc5118eb06a834a.cif
正在转换auid-515ec52183a350f6.cif
正在转换auid-522cd70353e49cd4.cif
正在转换auid-5357607d178f720f.cif
正在转换auid-53b02f1b60860f2b.cif
正在转换auid-55989595592561b8.cif
正在转换auid-55fbb21a88ea0db4.cif
正在转换auid-59558166b50850e6.cif
正在转换auid-5a0c2362f380e763.cif
正在转换auid-5d7c431ff54ff2c8.cif
正在转换auid-5de7254e61b7dc73.cif
正在转换auid-5e1f6e605fdc63a4.cif
正在转换auid-5ede7d2c90d081ed.cif
正在转换auid-5fdbf468aef8003e.cif
正在转换auid-6123c4c6de291b73.cif
正在转换auid-63d948bd91b396c3.cif
正在转换auid-6470d596b9632bf0.cif
正在转换auid-6526a10250b946c7.cif
正在转换auid-6755540fea418ecd.cif
正在转换auid-68a700a9cae149a6.cif
正在转换auid-69b14d3b4ca66535.cif
正在转换auid-6a6287f374ecbe90.cif
正在转换auid-6aade5a561ba5894.cif
正在转换auid-6ab698894d4e604e.cif
正在转换auid-6cbffdeb2f9a8948.cif
正在转换auid-6e85668f5722a215.cif
正在转换auid-6f8a406a92fb25c8.cif
正在转换auid-70c4efa76de25b00.cif
正在转换auid-71bde7d022ce7388.cif
正在转换auid-71d8a410d8874370.cif
正在转换auid-729aa96840e0ed0c.cif
正在转换auid-7351f06dee3f4551.cif
正在转换auid-7401c844ad456ec7.cif
正在转换auid-7583649de51dd0c7.cif
正在转换auid-769317c400c4e07b.cif
正在转换auid-77181c175fe2c18f.cif
正在转换auid-785df33de31db60d.cif
正在转换auid-7945fef9ede53dbb.cif
正在转换auid-7ae3d5257f780ebe.cif
正在转换auid-7f5169eeaab4f0df.cif
正在转换auid-803731032eebcf27.cif
正在转换auid-828e551760167c2d.cif
正在转换auid-84090d38d072d7ca.cif
正在转换auid-84120d24a13c7685.cif
正在转换auid-847fab5ea7046ff6.cif
正在转换auid-86e9dd7707d845ef.cif
正在转换auid-86f75c8367da7f15.cif
正在转换auid-8876edf8472b163d.cif
正在转换auid-893eccd647bdb857.cif
正在转换auid-89c874b339ff85aa.cif
正在转换auid-8d9c625bb8b4418f.cif
正在转换auid-903d822bf99c4182.cif
正在转换auid-91c3d23b1fcd8401.cif
正在转换auid-94c6e75d0a37a2ea.cif
正在转换auid-94edb9a05b6c242e.cif
正在转换auid-957e94081c3b749f.cif
正在转换auid-986035125d435ce0.cif
正在转换auid-98b609a27aa661f3.cif
正在转换auid-9a4b9e65f69233e3.cif
正在转换auid-9a96c13fd7b4a2d7.cif
正在转换auid-9abc92861805a3da.cif
正在转换auid-9ce0ec8820a93746.cif
正在转换auid-9ed9487473c83c22.cif
正在转换auid-a0fce62f730ea9c3.cif
正在转换auid-a216f6a02b2bf4eb.cif
正在转换auid-a34f0c97925c4015.cif
正在转换auid-a3ccd204f619ee61.cif
正在转换auid-a3dc0bcf25af7b7f.cif
正在转换auid-a42022aa74d2c4db.cif
正在转换auid-a6282d802536d3ae.cif
正在转换auid-a7bbbe180d565b93.cif
正在转换auid-a90fa8e5000ef563.cif
正在转换auid-aadf79c6d8f6c385.cif
正在转换auid-abb47b2c44f4f5aa.cif
正在转换auid-ac6e62f6ad8c6da9.cif
正在转换auid-ac986c608cb1153a.cif
正在转换auid-ad10864366c1f764.cif
正在转换auid-ada32dbf452f4dbb.cif
正在转换auid-ae214a952d889ddf.cif
正在转换auid-aff9b7e632fbf45b.cif
正在转换auid-b24fe26dd381df76.cif
正在转换auid-b296fb5f63b7ae0b.cif
正在转换auid-b5c683fa6d309c12.cif
正在转换auid-b63d71bfb173b0e6.cif
正在转换auid-b8bb526d18bd9d3f.cif
正在转换auid-b8f9bde0de77dfe1.cif
正在转换auid-b9d4415df603ba0e.cif
正在转换auid-bac1d70773dd7557.cif
正在转换auid-bd40068d1ec99748.cif
正在转换auid-bedebe0276d912ed.cif
正在转换auid-bf0124feceaf03b3.cif
正在转换auid-c02a5eb5cf7a6717.cif
正在转换auid-c0cd6aca3b5eecb7.cif
正在转换auid-c34ce3c041bf0746.cif
正在转换auid-c3cad31bf0d381d8.cif
正在转换auid-c46b1553e0452076.cif
正在转换auid-c5b167eb2a993312.cif
正在转换auid-c5b9f95d5d005b5e.cif
正在转换auid-c5d79a4bed20c12a.cif
正在转换auid-c6c764af90dcabc7.cif
正在转换auid-c72dc945085583db.cif
正在转换auid-c7a474df93e4714c.cif
正在转换auid-c7ad583e63b2323d.cif
正在转换auid-c7f680bff249fe20.cif
正在转换auid-c900ea7c4884a4e8.cif
正在转换auid-cb30da7897ee4329.cif
正在转换auid-cb97564460e03b75.cif
正在转换auid-cdd3ea48f29a886a.cif
正在转换auid-cf3c56b45008241f.cif
正在转换auid-d039c17fb2fb3963.cif
正在转换auid-d0cb24b534b6fb8f.cif
正在转换auid-d11f93d17730bbaa.cif
正在转换auid-d264498bd1f8dd16.cif
正在转换auid-d3a6840b211c65d6.cif
正在转换auid-d3fadf718d640c12.cif
正在转换auid-d4fcf9c1ae74b26c.cif
正在转换auid-d5738ad4af58bbb2.cif
正在转换auid-d627cedf7b3ee8bb.cif
正在转换auid-d9354a61c89edf83.cif
正在转换auid-d958ddee18b8755a.cif
正在转换auid-de48f28ef655b10e.cif
正在转换auid-df1e904b3a8488d3.cif
正在转换auid-df79fb2d61475fc9.cif
正在转换auid-e055b0f942c6d3fd.cif
正在转换auid-e094072ed28613bb.cif
正在转换auid-e3e5f65785f46e4a.cif
正在转换auid-e4789c89a6d853d2.cif
正在转换auid-e4b4d28eef2c1bfb.cif
正在转换auid-e67acdd53be2fcc2.cif
正在转换auid-e68db4de5e24550c.cif
正在转换auid-e861b70b38ed3ca2.cif
正在转换auid-e8d624cd0b6bc65f.cif
正在转换auid-eaabb2d56374a73c.cif
正在转换auid-ee4ecd0db86f1d28.cif
正在转换auid-ef40dc6471cb17a6.cif
正在转换auid-f38dd53d86c1a504.cif
正在转换auid-f3d71eff6cda7a03.cif
正在转换auid-f4c3d6ee46f067f1.cif
正在转换auid-f507b4a7ef929b6e.cif
正在转换auid-f576ba0b6b5b4d7f.cif
正在转换auid-f70d2c3ef1813d72.cif
正在转换auid-f7901c58c5e59f05.cif
正在转换auid-f7a29095ce246b21.cif
正在转换auid-f8b398dab20f7599.cif
正在转换auid-f953d184a2a80fea.cif
正在转换auid-f959458e4421dc9f.cif
正在转换auid-fb60e2649042b78f.cif
正在转换auid-fb9efb42f9c96a84.cif
正在转换auid-fbf144ef5851efef.cif
正在转换auid-fd60dc30303e1fe9.cif
正在转换auid-fd9dc14127d1eaa0.cif
正在转换auid-fdef7befb80a652a.cif
正在转换auid-fe1cb7ceb32813b2.cif
正在转换auid-ffc86b1c5650bf62.cif
正在转换auid-00780a595630be70.cif
正在转换auid-039f162410b7c2da.cif
正在转换auid-06cab152c01b7f53.cif
正在转换auid-0811087005ba3b2e.cif
正在转换auid-0881c37e709852d5.cif
正在转换auid-098f1db1064ea69a.cif
正在转换auid-09f985c5f8ab10ce.cif
正在转换auid-0a32ad07a6d00790.cif
正在转换auid-0aa9b81a210c6f75.cif
正在转换auid-0b0d64a2f43dd3b0.cif
正在转换auid-0b36f29f6b3ca7d4.cif
正在转换auid-0b77bc85f2273e89.cif
正在转换auid-0b9c46abcdfd9d36.cif
正在转换auid-0c88ad1f8f3e60b3.cif
正在转换auid-0ed9f040b5ecb6eb.cif
正在转换auid-0f59d0afdeef8c36.cif
正在转换auid-103371a3d59e8507.cif
正在转换auid-104d856443ddf095.cif
正在转换auid-119fffef450e4e3d.cif
正在转换auid-12ef11c65c5f75c2.cif
正在转换auid-138ab7d967f60b28.cif
正在转换auid-145282f33f7f7975.cif
正在转换auid-147ec0002379d115.cif
正在转换auid-151f3b74547a9282.cif
正在转换auid-1583aea93904a76e.cif
正在转换auid-15893c4d39728efd.cif
正在转换auid-179013c219b4b2c2.cif
正在转换auid-18e23109fc5eff1b.cif
正在转换auid-1924c3bfb66ead52.cif
正在转换auid-199b53b5757db41e.cif
正在转换auid-1a0585aa9f16582f.cif
正在转换auid-1aac41f4c4c77cbe.cif
正在转换auid-1b89db45b210562f.cif
正在转换auid-1b8fe4e420d238df.cif
正在转换auid-1bb6aaee4b056d17.cif
正在转换auid-1cebfb02866f3564.cif
正在转换auid-1d5a8880b16b39b4.cif
正在转换auid-1e52c6be708f2121.cif
正在转换auid-1fb6dba36ca19b3f.cif
正在转换auid-1fcdbf5654a695bb.cif
正在转换auid-20b4911a9c473b29.cif
正在转换auid-20f94798ea135adb.cif
正在转换auid-222f52a2788b17ed.cif
正在转换auid-25c201b2b860e483.cif
正在转换auid-2686f6939809655b.cif
正在转换auid-2690e7bc6ce14d9b.cif
正在转换auid-274e17befd9d0c23.cif
正在转换auid-275702033d521c01.cif
正在转换auid-275ebf76d5f13cd7.cif
正在转换auid-2768059a07405ef7.cif
正在转换auid-2846c2f957f7fb64.cif
正在转换auid-286cc32f4888d8e8.cif
正在转换auid-290e733013e54d2a.cif
正在转换auid-296ecc4c40195c7d.cif
正在转换auid-29d525bcc68a3951.cif
正在转换auid-2a4febc7560072ff.cif
正在转换auid-2b44f9adfcadcacf.cif
正在转换auid-2b53cb1cbb83ad92.cif
正在转换auid-2bc534df50372c44.cif
正在转换auid-2c54016f0ee09d26.cif
正在转换auid-2ca5f8607e0fb1e3.cif
正在转换auid-2ddfa798ab0ce1c0.cif
正在转换auid-2e9397951e66293b.cif
正在转换auid-2f65aee4b7f60b88.cif
正在转换auid-3076d6fcd2b95f7b.cif
正在转换auid-30dc7afc354fad1a.cif
正在转换auid-3134faaf8fcc76f0.cif
正在转换auid-31becb392a8565b2.cif
正在转换auid-32367c3374860166.cif
正在转换auid-35581d83fbae12ab.cif
正在转换auid-3558265eb117a1a0.cif
正在转换auid-360d955d3f63f783.cif
正在转换auid-361a722f605be556.cif
正在转换auid-37641952ff1f67c8.cif
正在转换auid-392fb219c0e49939.cif
正在转换auid-39bb6940c1050f21.cif
正在转换auid-3b9fa353a47b6744.cif
正在转换auid-3c79be9d957d49be.cif
正在转换auid-3d6fbc5dd9dab0a1.cif
正在转换auid-3e182df9d1231c68.cif
正在转换auid-3e49b6181b30b5f7.cif
正在转换auid-3f6f5ea6c2d8ef3c.cif
正在转换auid-3fbcf32abfd3635b.cif
正在转换auid-402b0198ecab93af.cif
正在转换auid-4042211017bf0ba3.cif
正在转换auid-40b2e57de7b9af5e.cif
正在转换auid-40d09c4f67aa6c0f.cif
正在转换auid-4193d0e0cd21193d.cif
正在转换auid-42b59a50eb7cbb17.cif
正在转换auid-438770598cdd6a49.cif
正在转换auid-4436515621366576.cif
正在转换auid-4446bd1348879d5e.cif
正在转换auid-44524d3d0b9929c8.cif
正在转换auid-449ba81825067388.cif
正在转换auid-46aac61de45cdc95.cif
正在转换auid-47876beb3b9f2d1c.cif
正在转换auid-48a8ca4730f70be5.cif
正在转换auid-48d266664a11d8dc.cif
正在转换auid-4a439bc1480c0c73.cif
正在转换auid-4af5877f63f3e09a.cif
正在转换auid-4b7bd4097d5173bb.cif
正在转换auid-4b94cac40472b9f9.cif
正在转换auid-4bf8a7a3b08d4f0e.cif
正在转换auid-4dea5c936491d62d.cif
正在转换auid-4e3a8f49b3626258.cif
正在转换auid-4fe685bdda0f129e.cif
正在转换auid-5029d0e196fc5e5b.cif
正在转换auid-51d6fbd3d91ecc9a.cif
正在转换auid-52e4168b1fc705fa.cif
正在转换auid-53bfba108ef57fb5.cif
正在转换auid-53df24a5eafa3223.cif
正在转换auid-54444b946edb0e20.cif
正在转换auid-5478472f0a26db50.cif
正在转换auid-54824be7ff39e456.cif
正在转换auid-553e0178d253c05c.cif
正在转换auid-559298ac1fd7dc52.cif
正在转换auid-55ee3530b8881486.cif
正在转换auid-579482aab2b885c1.cif
正在转换auid-57adb827a2ade6db.cif
正在转换auid-5853d146af760f1f.cif
正在转换auid-58ce1bfa8cb8c748.cif
正在转换auid-5a680f0b64b4ee4d.cif
正在转换auid-5a8d9d9e7014211d.cif
正在转换auid-5bf67b478744565f.cif
正在转换auid-5c1cbaa0568f2636.cif
正在转换auid-5c93e5610452aecf.cif
正在转换auid-5c9816bb644220f1.cif
正在转换auid-5d58b68034774cc8.cif
正在转换auid-5dd12ac01f5a0f45.cif
正在转换auid-5fda0c23ddafed36.cif
正在转换auid-605a97e7dd9ebc91.cif
正在转换auid-614c8ce5d29099c4.cif
正在转换auid-63868212ee17f1ff.cif
正在转换auid-65012125dbeda6e7.cif
正在转换auid-6572cb8cc9f30adc.cif
正在转换auid-662565ccc4bfa974.cif
正在转换auid-66586b054338a805.cif
正在转换auid-666426405d2a2a96.cif
正在转换auid-66af776b61d84f45.cif
正在转换auid-66ea9556a70c85d3.cif
正在转换auid-684b779d33829226.cif
正在转换auid-695281eafbb1dff1.cif
正在转换auid-6b71ac39bdc67eba.cif
正在转换auid-6dc051c729540a89.cif
正在转换auid-6dfebeb3441f687d.cif
正在转换auid-6e666320011383ea.cif

正在转换auid-6ef3ef87a79ac072.cif
正在转换auid-6f7ade6fb3e03baa.cif
正在转换auid-701e9d1767b1b13c.cif
正在转换auid-71dd5fc4d4ec7a92.cif
正在转换auid-72335a5e687f8f7b.cif
正在转换auid-7278d1304f4c5289.cif
正在转换auid-7298198780f73ad1.cif
正在转换auid-735391e48700a2bf.cif
正在转换auid-7359dcb5c0aaea7c.cif
正在转换auid-736aa21dd97ee96f.cif
正在转换auid-73c96804d7cf0fe7.cif
正在转换auid-758991bfd68d6892.cif
正在转换auid-75d9e0c25ffd25c8.cif
正在转换auid-7615c9782295e2bc.cif
正在转换auid-761da6bd474c0f86.cif
正在转换auid-7627a69cda9a7397.cif
正在转换auid-762b40fb1962488f.cif
正在转换auid-76857169968a1018.cif
正在转换auid-777a65cc14658fc9.cif
正在转换auid-78d6fb9bc904df67.cif
正在转换auid-79627967d68ef11c.cif
正在转换auid-7a4c4f988c4c2a73.cif
正在转换auid-7b4116e397df6ff3.cif
正在转换auid-7b959de6e955db4d.cif
正在转换auid-7bf05738d3737d76.cif
正在转换auid-7c9664fb42c1dc7c.cif
正在转换auid-7d8943f5a96aecb7.cif
正在转换auid-7dc79d9480ad6eec.cif
正在转换auid-7e5e9d5504793e3d.cif
正在转换auid-7ee75ce15308f15c.cif
正在转换auid-7f09015b61091a02.cif
正在转换auid-804567f30e923bc2.cif
正在转换auid-80f32d84c7b1ce83.cif
正在转换auid-81296bc6c756ec73.cif
正在转换auid-81a8cb14dbac42a0.cif
正在转换auid-81e5050193acbfed.cif
正在转换auid-82091fbf46da9487.cif
正在转换auid-82eb971696cb267f.cif
正在转换auid-83c3e0e46f782046.cif
正在转换auid-83da0fa542a9f526.cif
正在转换auid-84a74a1b141478bd.cif
正在转换auid-85ccef4d7318bcef.cif
正在转换auid-8682fe198830788f.cif
正在转换auid-868690079b1847be.cif
正在转换auid-8936413b3352b751.cif
正在转换auid-897437be28813b5d.cif
正在转换auid-8bab878098534662.cif
正在转换auid-8bc121f7e03454af.cif
正在转换auid-8cca93b282fbd575.cif
正在转换auid-8cdb53e964c560cc.cif
正在转换auid-8d50ed6367ac1c9f.cif
正在转换auid-8d653e030e56a253.cif
正在转换auid-8e8cab3dcf82394f.cif
正在转换auid-8f81e31b3c5adba7.cif
正在转换auid-9012cc151ce11474.cif
正在转换auid-92efdfb6abbf5637.cif
正在转换auid-931a329a235a2e04.cif
正在转换auid-93e558410da9508e.cif
正在转换auid-9401cadfb8dcf4d7.cif
正在转换auid-944609b413fc346d.cif
正在转换auid-956d40a3212694a9.cif
正在转换auid-96af6cf26d50c31c.cif
正在转换auid-96e829a4360bd92b.cif
正在转换auid-97405ab0d3351c4d.cif
正在转换auid-9759c489222977b2.cif
正在转换auid-97dc846e9fce94c9.cif
正在转换auid-994716fadc16ecbb.cif
正在转换auid-99fec0bbb6ab4098.cif
正在转换auid-9a9c164876d3c7f6.cif
正在转换auid-9d7a62a7371aae5a.cif
正在转换auid-9d9f2ef0f49bc2c5.cif
正在转换auid-9e8fd1250b471453.cif
正在转换auid-9f2a49c346237e63.cif
正在转换auid-9fa9712431ecb61b.cif
正在转换auid-9fc1fd8291d60d53.cif
正在转换auid-a0bf0c867a9b1edb.cif
正在转换auid-a0f89eac8d63951b.cif
正在转换auid-a2365863ca05a5f1.cif
正在转换auid-a31c3b4b828410e9.cif
正在转换auid-a32f69e2dfade29e.cif
正在转换auid-a3c0edcad795e90f.cif
正在转换auid-a436af8653728bfd.cif
正在转换auid-a4b3dba883f0d60c.cif
正在转换auid-a5586e41e7556fb1.cif
正在转换auid-a6408d176f7292f8.cif
正在转换auid-a7558f2204332ea9.cif
正在转换auid-a9ebd0e71015fe53.cif
正在转换auid-aa2b13802bcb081f.cif
正在转换auid-aad65a42371a19c5.cif
正在转换auid-abcb424e98e14047.cif
正在转换auid-ae032fc2b74344c5.cif
正在转换auid-ae36862b0d9a1d83.cif
正在转换auid-ae6b4cc5162f5691.cif
正在转换auid-b0607279ee18e67e.cif
正在转换auid-b088e8cee8ada56c.cif
正在转换auid-b1ff0f8b7d810ec0.cif
正在转换auid-b33bda25614a1b16.cif
正在转换auid-b3ed8eecc3dea7b6.cif
正在转换auid-b40c6d91f372a4ca.cif
正在转换auid-b42f5388371c48fb.cif
正在转换auid-b434e9afceaca6e0.cif
正在转换auid-b49248eed231502a.cif
正在转换auid-b4d7fba5568f5d42.cif
正在转换auid-b54757a1796d6c8d.cif
正在转换auid-b56e46a92883bd55.cif
正在转换auid-b647193bc40375e9.cif
正在转换auid-b79a9aacf51d056b.cif
正在转换auid-b7b7d9c52fb6e472.cif
正在转换auid-b7d449e56af5b5ef.cif
正在转换auid-b87f502ff6e7bacf.cif
正在转换auid-bbef50eeff897b8d.cif
正在转换auid-bc03b3a6be8c14ce.cif
正在转换auid-bc421bca968d3519.cif
正在转换auid-be68ef1778925ef0.cif
正在转换auid-bfb645ff4e8bd8d8.cif
正在转换auid-bfc02448aa29f856.cif
正在转换auid-c2a6711d52a36054.cif
正在转换auid-c2b87cd3f84a28f5.cif
正在转换auid-c2ff4bd52f1e68ac.cif
正在转换auid-c64800694fddc001.cif
正在转换auid-c6bc772c33a2e02b.cif
正在转换auid-c7f1ac3628e05f36.cif
正在转换auid-cb0e444cb9bc0f33.cif
正在转换auid-cd022ba5b4452932.cif
正在转换auid-cdad59819df03ab5.cif
正在转换auid-ce3171d34910cafe.cif
正在转换auid-ce4fa7dc47e3b241.cif
正在转换auid-ce7bc600f1479892.cif
正在转换auid-cf22eff9e40ea43b.cif
正在转换auid-cfe6098d0352de18.cif
正在转换auid-d2b21452d801a4fc.cif
正在转换auid-d2ca489601e1150c.cif
正在转换auid-d482718f2f7fbe26.cif
正在转换auid-d54bfa68b8d798ee.cif
正在转换auid-d6d04e2a6c93ee6a.cif
正在转换auid-d8d542b341a78a59.cif
正在转换auid-d9c06192fa13985f.cif
正在转换auid-d9daf3441096f99f.cif
正在转换auid-daa8471e320d9f70.cif
正在转换auid-db7bd7bba59a593b.cif
正在转换auid-dcfbd14519d9a3cb.cif
正在转换auid-dd8be0cd5fe76b03.cif
正在转换auid-df147a1a21695d2c.cif
正在转换auid-e151c4bb0d95d15f.cif
正在转换auid-e1b14245ec008aa8.cif
正在转换auid-e2e2e1830425b05e.cif
正在转换auid-e3e86f5f404c3072.cif
正在转换auid-e40675d81e703cf9.cif
正在转换auid-e4c0365cbfb181fd.cif
正在转换auid-e54774e2ef3f87ef.cif
正在转换auid-e6b8d09142ecc72e.cif
正在转换auid-e7536fa5006b1502.cif
正在转换auid-e7c91ea2eca337a7.cif
正在转换auid-e8251c3e0308c895.cif
正在转换auid-e9c5bfc62df5eaa2.cif
正在转换auid-eb4aa4ffb5bccd40.cif
正在转换auid-ebab98d11ab79e34.cif
正在转换auid-ebac533ca696554c.cif
正在转换auid-ec3a7d67db141a72.cif
正在转换auid-ed4a5b779873cdbb.cif
正在转换auid-ed5988c8bfcd9b57.cif
正在转换auid-ee54919a26ebda10.cif
正在转换auid-f14471fcf6176fa7.cif
正在转换auid-f147105203c1e730.cif
正在转换auid-f2c663c40463298e.cif
正在转换auid-f3e8a232dd958cc4.cif
正在转换auid-f42fe9341dd448d8.cif
正在转换auid-f4f50470e9e05b7e.cif
正在转换auid-f506f8f3e1178c68.cif
正在转换auid-f5548ff853eb8452.cif
正在转换auid-f557696c35e3bfb3.cif
正在转换auid-f575f5d72d944a8f.cif
正在转换auid-f5b67d170dc7a6b3.cif
正在转换auid-f6b11d1785f323f5.cif
正在转换auid-f7a4458ba065a858.cif
正在转换auid-f96b84db47c7dfa6.cif
正在转换auid-f9a08b7e70f1383c.cif
正在转换auid-f9a43f8464c1a1ac.cif
正在转换auid-fb56e9f7aa0b82bf.cif
正在转换auid-fc0364f7ea2a333c.cif
正在转换auid-fd59019cb7c0bef2.cif
正在转换auid-fd85febc214ed178.cif
正在转换auid-fdfff990becb519b.cif
正在转换auid-feb55a10a6536064.cif
正在转换auid-fedd2486b3c7fc51.cif
正在转换auid-ff1774e3cb5c7897.cif
正在转换auid-01877081e09cd249.cif
正在转换auid-08e4c8fbf78cf701.cif
正在转换auid-08e51cb0ecf91547.cif
正在转换auid-119667975e040d0a.cif
正在转换auid-13d692910d3175b3.cif
正在转换auid-24221bed5d9379ab.cif
正在转换auid-251ae7c74af3ece6.cif
正在转换auid-31892565d66feda1.cif
正在转换auid-31afea613f0cc9e2.cif
正在转换auid-34a64d1d860bab4c.cif
正在转换auid-38d56ca6fa1e6af2.cif
正在转换auid-3a9de139429c8f35.cif
正在转换auid-3d7107be6007a6d2.cif
正在转换auid-3ea10a9802ea62f1.cif
正在转换auid-40d086d7055f78d9.cif
正在转换auid-4212a70623855aa9.cif
正在转换auid-44f1c76f82c6f930.cif
正在转换auid-4912c7171bd11827.cif
正在转换auid-4e8b29e887a4da60.cif
正在转换auid-54cdc891b97be31e.cif
正在转换auid-57239d9daf2788c9.cif
正在转换auid-5998c48a52a302ec.cif
正在转换auid-5afd5c9c82984ebd.cif
正在转换auid-5feb229d6cfe6eaa.cif
正在转换auid-6173b042d316097b.cif
正在转换auid-61dfe4f02561342b.cif
正在转换auid-67891012acf49acd.cif
正在转换auid-68282b5e83a57465.cif
正在转换auid-6d700e1f7b1fba41.cif
正在转换auid-72f0a9cf84eedd48.cif
正在转换auid-784485d47105d195.cif
正在转换auid-79c9b7010dec6bf4.cif
正在转换auid-79f66df3dddbad60.cif
正在转换auid-7ebca95eec585cf4.cif
正在转换auid-827156012ac03fef.cif
正在转换auid-82ecf8c73ca9c1b6.cif
正在转换auid-8d6badddacbe5d66.cif
正在转换auid-8e7ac356cec96737.cif
正在转换auid-8fc8c03605d0d5d3.cif
正在转换auid-91f99acf2b654660.cif
正在转换auid-937d6d5d27f9a66a.cif
正在转换auid-94427a1c27d39b4b.cif
正在转换auid-9792aad83013169a.cif
正在转换auid-9a835396cfb89e24.cif
正在转换auid-9ca6067af0914ffb.cif
正在转换auid-9fea1ae31ce15779.cif
正在转换auid-a310d1499eab6112.cif
正在转换auid-a54b2931b2517dc6.cif
正在转换auid-a556088e9f7c17f5.cif
正在转换auid-a8b7eefeac02203c.cif
正在转换auid-a925712b91f3173b.cif
正在转换auid-a94a2c22da87d538.cif
正在转换auid-a9e89d912bf83c91.cif
正在转换auid-ad2c632e673c27dc.cif
正在转换auid-b297b7735b5866dd.cif
正在转换auid-b9acaebdc9ea0efa.cif
正在转换auid-bd93ce0af695431d.cif
正在转换auid-c08e379a8292c415.cif
正在转换auid-c836faac8e57bcc2.cif
正在转换auid-c88e7be7137c2d54.cif
正在转换auid-cb3c046a8ae3dce7.cif
正在转换auid-cb71411ee9d26a1e.cif
正在转换auid-cfa7bd3b1ae75730.cif
正在转换auid-d3298289c8ba7e54.cif
正在转换auid-d544934a8c38ebb9.cif
正在转换auid-d5dfef08bb846056.cif
正在转换auid-d84524111a5d7958.cif
正在转换auid-df1b5b22f24afd14.cif
正在转换auid-e026745f2416fa81.cif
正在转换auid-e1596e9dad0ab6b7.cif
正在转换auid-e1b23d45a8f00133.cif
正在转换auid-e1f87d1b571422fa.cif
正在转换auid-e47987767a4a91cd.cif
正在转换auid-e502c33373b0fd43.cif
正在转换auid-e6a597428372e07a.cif
正在转换auid-e898845ccc1bf448.cif
正在转换auid-f61cd388b70be460.cif
正在转换auid-f6d92cd8f78a2fb2.cif
正在转换auid-fa36ff8a23abab82.cif
正在转换auid-fbdfda672c55f50e.cif
正在转换auid-fe485c29b9d9e791.cif
正在转换auid-28761783ef4a6566.cif
正在转换auid-0591821ae202a71c.cif
正在转换auid-082a79ba47e7ac6a.cif
正在转换auid-08febe8a32fde6b7.cif
正在转换auid-0ac16c865e96c150.cif
正在转换auid-0af629f3a2e690bc.cif
正在转换auid-152004f20d29e98d.cif
正在转换auid-16285f8d83fbc384.cif
正在转换auid-18a015a683b0b122.cif
正在转换auid-18ad1efd7642b7db.cif
正在转换auid-1a0351f9a6254bbf.cif
正在转换auid-21c919ba37cd3cde.cif
正在转换auid-226c5515814dc0ac.cif
正在转换auid-26d210d427d7af2e.cif
正在转换auid-2a72725e9cbb4c24.cif
正在转换auid-33bdf479b538bb89.cif
正在转换auid-33fb20e59b0586de.cif
正在转换auid-3506bd447e24f007.cif
正在转换auid-369bc4ba935566c4.cif
正在转换auid-37455da096dccb2d.cif
正在转换auid-39772e25ed87f242.cif
正在转换auid-3a74ac4e2c87c7e1.cif
正在转换auid-401ca02dae611a10.cif
正在转换auid-442427fc35dd81ae.cif
正在转换auid-4522887cfdf55111.cif
正在转换auid-4c21fcb66201417a.cif
正在转换auid-4c5fae0de8435b22.cif
正在转换auid-4ff938dee7e82c48.cif
正在转换auid-506068fe2d2ddb86.cif
正在转换auid-50ae10d5d535d88e.cif
正在转换auid-588178e14369fe5c.cif
正在转换auid-5b08ce9e1d84d0dd.cif
正在转换auid-5dacc9b8bbfcc14d.cif
正在转换auid-5f5963b57165a841.cif
正在转换auid-600224c9c36396e9.cif
正在转换auid-607a351d33de0e59.cif
正在转换auid-61dd2da2d64dd081.cif
正在转换auid-636ce22f46edb45d.cif
正在转换auid-65a676f67a62fc8f.cif
正在转换auid-681261323eede7f8.cif

正在转换auid-7089fde80a58659f.cif
正在转换auid-729a119b77d6db24.cif
正在转换auid-739099d985a7713b.cif
正在转换auid-73dc808d460b1b2d.cif
正在转换auid-777961b26b934e05.cif
正在转换auid-78b29d2b576c3bc4.cif
正在转换auid-79ac0ba55e465f41.cif
正在转换auid-7fd4e513889441e3.cif
正在转换auid-802d9753a4aedfde.cif
正在转换auid-805041681f5788ff.cif
正在转换auid-853e5580be6d5d07.cif
正在转换auid-8a234b995ebfcb1c.cif
正在转换auid-8b1eda0605cd2a69.cif
正在转换auid-8bcfc5f6f4552934.cif
正在转换auid-8c0fd818d4473cfa.cif
正在转换auid-8fe9cea719af5773.cif
正在转换auid-90b9d7aa30bf6757.cif
正在转换auid-9492ca0a7c81e08c.cif
正在转换auid-962f8c0f012448b0.cif
正在转换auid-9734e69a3e1a5652.cif
正在转换auid-9b63d90b1e9ec6b0.cif
正在转换auid-9bf2389d3648b43a.cif
正在转换auid-9e48c7ab60e474c8.cif
正在转换auid-9e7e50b05daa3c46.cif
正在转换auid-a08f93b6dbe395fe.cif
正在转换auid-a2004b5a8727c31b.cif
正在转换auid-a30765e207575fbf.cif
正在转换auid-a32b5a5817ba42c0.cif
正在转换auid-a4d4f11c1480b1f6.cif
正在转换auid-a5444cc82a4ec986.cif
正在转换auid-a5aadff88b3b20a6.cif
正在转换auid-a5f4a898923487b9.cif
正在转换auid-a823bf316b3eae13.cif
正在转换auid-aa40d406b4fc9155.cif
正在转换auid-ab513b543795c5de.cif
正在转换auid-abc40d1ada10cbc0.cif
正在转换auid-bf879070fe642d4e.cif
正在转换auid-c4b2518adc870729.cif
正在转换auid-c533bd39d40a87a7.cif
正在转换auid-c84f1b4641d88298.cif
正在转换auid-c9e02b3d3ce176dc.cif
正在转换auid-cc199c8d9423dcbe.cif
正在转换auid-d041c5f677c5c924.cif
正在转换auid-d1fb9f0aeddb390b.cif
正在转换auid-d23e8abc6e209cfe.cif
正在转换auid-d27b29e8528d5da2.cif
正在转换auid-d494f2cd110fe3a7.cif
正在转换auid-d639d1bcc5b32ee5.cif
正在转换auid-ddadeab89844edd3.cif
正在转换auid-e0627aaf5b0640a9.cif
正在转换auid-e44c826ed0d88100.cif
正在转换auid-e5759c33604c6481.cif
正在转换auid-e6a20ac0d8441ab3.cif
正在转换auid-ea87cb9a9999bb53.cif
正在转换auid-eea5e68672041d7e.cif
正在转换auid-eec63e2095df3b31.cif
正在转换auid-f1ebdcb1f68f344f.cif
正在转换auid-f40796dc4e119bae.cif
正在转换auid-f7a6bfb58a9c90ad.cif
正在转换auid-ff3c29320b83293d.cif
正在转换auid-005cd1216ec7ceaa.cif
正在转换auid-005fa88aae77965a.cif
正在转换auid-00e544a9d8a8dcbd.cif
正在转换auid-024caf5b1964f6d4.cif
正在转换auid-0489cbb449497a40.cif
正在转换auid-049f4b2c7aa3db64.cif
正在转换auid-050eca42692d71b4.cif
正在转换auid-056f57a425ba9d28.cif
正在转换auid-068f28f263b1960c.cif
正在转换auid-06bda258960e55ca.cif
正在转换auid-06d5673547c25181.cif
正在转换auid-07d7ef0ccc65fa9e.cif
正在转换auid-08c8d7cc69a19e94.cif
正在转换auid-0966322cdb768d00.cif
正在转换auid-097960e278df3a3d.cif
正在转换auid-0a401faed4ceb435.cif
正在转换auid-0b5fc36ae7e6788a.cif
正在转换auid-0bf2c9d86d51cda8.cif
正在转换auid-0c5c86b1440a67df.cif
正在转换auid-0c7e110f39d34d2a.cif
正在转换auid-0cefab724eab4c77.cif
正在转换auid-1251e5ff4360912a.cif
正在转换auid-12e8fc31218a4d4d.cif
正在转换auid-12f1789897edf547.cif
正在转换auid-133dc7a4b3dc27b6.cif
正在转换auid-136171b74d538e40.cif
正在转换auid-13b953a90dda12e9.cif
正在转换auid-13f370bbd77b32cd.cif
正在转换auid-15182c0301da8a67.cif
正在转换auid-155258e9f310512e.cif
正在转换auid-164282dcd4b16eab.cif
正在转换auid-16dbe5ef505149be.cif
正在转换auid-17456e146b1f072e.cif
正在转换auid-174b79863b5a903c.cif
正在转换auid-17518cebbfc5e88d.cif
正在转换auid-18eb68d115ad143b.cif
正在转换auid-19302460f6d86368.cif
正在转换auid-1a021c6e5f2e4896.cif
正在转换auid-1a33b94156566e3f.cif
正在转换auid-1b92aabb9d931a0f.cif
正在转换auid-1c724df5411e74ef.cif
正在转换auid-1cf1faf9ff7ee4fd.cif
正在转换auid-1e1aae2ad79272b1.cif
正在转换auid-1e37d84128bdaf5c.cif
正在转换auid-1e462e5abb2a145f.cif
正在转换auid-1e8f1fa7c6fb2c62.cif
正在转换auid-1eae510bea3a08d5.cif
正在转换auid-207c4974afc53878.cif
正在转换auid-209b94276844d153.cif
正在转换auid-20a5d17fbb5f95bc.cif
正在转换auid-212ed8ebd333017c.cif
正在转换auid-21496b6db94cc412.cif
正在转换auid-21715748c6a6c357.cif
正在转换auid-2197676dd9453689.cif
正在转换auid-21c50f8badf52bf9.cif
正在转换auid-21d5ab38e31b1c41.cif
正在转换auid-22024fd870537fb1.cif
正在转换auid-22ef9eebdbc82bc7.cif
正在转换auid-2307c87b95472eb4.cif
正在转换auid-25029e30a4282ea0.cif
正在转换auid-25cb05d73e79f0ea.cif
正在转换auid-2609297bb8c8cb8b.cif
正在转换auid-262a6d1bec876a0c.cif
正在转换auid-262f9455757dabcc.cif
正在转换auid-26a2808a03ae36c8.cif
正在转换auid-287fca1fd3f7749e.cif
正在转换auid-28e73b2b997293a9.cif
正在转换auid-29e61484eeacb1dd.cif
正在转换auid-2b0641ff1b3b317f.cif
正在转换auid-2bf7c8f84069b9e2.cif
正在转换auid-2c4c12a95d55da64.cif
正在转换auid-2c5e895960516f4d.cif
正在转换auid-2c727a417554d77d.cif
正在转换auid-2cd85ba7bbd1f1cb.cif
正在转换auid-2fffc74f34cc3b5e.cif
正在转换auid-300d6d635859298d.cif
正在转换auid-3094312a94d33f40.cif
正在转换auid-309f8c975fd74a21.cif
正在转换auid-312db871fbb5019c.cif
正在转换auid-318235e032453cb5.cif
正在转换auid-31b28ceac6d5a33a.cif
正在转换auid-31de6dc6dac7f8fd.cif
正在转换auid-3337e0e5402af725.cif
正在转换auid-36a1c21d7cb22520.cif
正在转换auid-37089e13f78b3414.cif
正在转换auid-373b8d8dbcf83967.cif
正在转换auid-3879cae12b01a327.cif
正在转换auid-398876886ce67311.cif
正在转换auid-3b69ab08a61a32a2.cif
正在转换auid-3be72cc888d537e4.cif
正在转换auid-3c46dd50e230090a.cif
正在转换auid-3c869a9b16a03778.cif
正在转换auid-3cdb248ace2222ae.cif
正在转换auid-3e3df8b30b2252ac.cif
正在转换auid-3ec9e6a96309a42c.cif
正在转换auid-3f5b62eac53615e8.cif
正在转换auid-3f84157cc40888a4.cif
正在转换auid-40230b70f1d1880e.cif
正在转换auid-4039d749d01f4388.cif
正在转换auid-42312b1e285be0c0.cif
正在转换auid-4325c51f7ee164de.cif
正在转换auid-43749408342929e4.cif
正在转换auid-43d490f89eb6652a.cif
正在转换auid-46c51b92c06d73a6.cif
正在转换auid-46e9eab82e4979c4.cif
正在转换auid-47fbe737e7e3a6d8.cif
正在转换auid-48d388f0a03ca990.cif
正在转换auid-4a310a5e114aa2ec.cif
正在转换auid-4bc889409706f6c9.cif
正在转换auid-4d4abae2f4b73d9f.cif
正在转换auid-4d5e26bef6ec8e57.cif
正在转换auid-4e92a97d00063003.cif
正在转换auid-4f5233714f58623e.cif
正在转换auid-507ef982d9d1656f.cif
正在转换auid-50f15fbf3e5cc1f8.cif
正在转换auid-514cb2a822877327.cif
正在转换auid-518b336131b87b56.cif
正在转换auid-5378e8992444a902.cif
正在转换auid-53a80ba46526b70e.cif
正在转换auid-5429b8273b4f3f87.cif
正在转换auid-542ecdac7c461f6c.cif
正在转换auid-5454c55f3452ccca.cif
正在转换auid-54fc19c47931d799.cif
正在转换auid-55c1ec73d9271b46.cif
正在转换auid-56aee959efe753e8.cif
正在转换auid-575fd4ca5f3f8b3b.cif
正在转换auid-57649a22f127dcca.cif
正在转换auid-579e5c2902aba774.cif
正在转换auid-588d9f5bebef7297.cif
正在转换auid-590722c92dd51bf5.cif
正在转换auid-5977f33d0c9a9d41.cif
正在转换auid-59f52a3972a651fc.cif
正在转换auid-5a253e894a9e871e.cif
正在转换auid-5a3b04f28d1f5abc.cif
正在转换auid-5a9d1a2b008d9d75.cif
正在转换auid-5b1824b830cec4bd.cif
正在转换auid-5d18285d8264ee3b.cif
正在转换auid-5ed89f53968238c9.cif
正在转换auid-5fff9676ece993d5.cif
正在转换auid-60dd2b910444c911.cif
正在转换auid-614dc8a198b5318b.cif
正在转换auid-64286a82480d0cbb.cif
正在转换auid-6473d569e2d8341a.cif
正在转换auid-64f9111a23c731d6.cif
正在转换auid-656210135a96a310.cif
正在转换auid-65c573a6f69b3b33.cif
正在转换auid-688f6e9898255d12.cif
正在转换auid-696ce072377181e2.cif
正在转换auid-69ba2067147174a6.cif
正在转换auid-6a03ce999c66ce4f.cif
正在转换auid-6a4d3ea7cb418ede.cif
正在转换auid-6b2f6a97f65fc339.cif
正在转换auid-6c74a2e9dc48b1a3.cif
正在转换auid-6ce63a859654602b.cif
正在转换auid-6d05f0e242f0636b.cif
正在转换auid-6db4ab11f9b90d57.cif
正在转换auid-6e335b72aabf8607.cif
正在转换auid-6e7923ace11c6059.cif
正在转换auid-6ef525ad74195362.cif
正在转换auid-6f8b6aba17d83806.cif
正在转换auid-6fdad8be300faa5e.cif
正在转换auid-700ea1ad99589034.cif
正在转换auid-712433f69d86fd34.cif
正在转换auid-716f00c9e6b4c485.cif
正在转换auid-71f046b12e801319.cif
正在转换auid-722327fc2f5736d3.cif
正在转换auid-72ce6ce0248867f7.cif
正在转换auid-73c75adef3713def.cif
正在转换auid-73e6ed6f304615c3.cif
正在转换auid-740b9ddbc2fbf476.cif
正在转换auid-743d40aba9f20924.cif
正在转换auid-74d50f6989b3ffed.cif
正在转换auid-75105640dcc6d6b3.cif
正在转换auid-759c08ce2277e208.cif
正在转换auid-75da6a2ea77edb80.cif
正在转换auid-772e6612eef1f3d3.cif
正在转换auid-7753a7b491676bfb.cif
正在转换auid-78dfcccbbe50d852.cif
正在转换auid-78f113b09cc26682.cif
正在转换auid-7abc37fc2490763c.cif
正在转换auid-7b1ec4ac1aa6438c.cif
正在转换auid-7b289df08c9f4b17.cif
正在转换auid-7bf9c7c52a93d34a.cif
正在转换auid-7e502e2a7aeee42f.cif
正在转换auid-7e54630ba32d68a6.cif
正在转换auid-7eabdbeaea4291cb.cif
正在转换auid-7f0c8c42ed3a3163.cif
正在转换auid-7f3d0416ff4f1333.cif
正在转换auid-8052bba21e1925ba.cif
正在转换auid-83444db7e4f73624.cif
正在转换auid-83984cce9b9f48a4.cif
正在转换auid-839fc1348babf202.cif
正在转换auid-840be588ed1db9a8.cif
正在转换auid-84cd779dee719b45.cif
正在转换auid-85dde1abb4a7a24a.cif
正在转换auid-873360e044764703.cif
正在转换auid-8909fa716549b0b8.cif
正在转换auid-8a28388796387bd1.cif
正在转换auid-8a6a109778cf23b5.cif
正在转换auid-8bb0093424867d8a.cif
正在转换auid-8c06df1612fa5f11.cif
正在转换auid-8c9147ea3fc77a90.cif
正在转换auid-8ccb8aa7cfd7efa4.cif
正在转换auid-8ead62d544b300f3.cif
正在转换auid-8ec0e6059de8866c.cif
正在转换auid-8f99ad858d77c72c.cif
正在转换auid-8fab14faa2441f50.cif
正在转换auid-90e505e51f551f82.cif
正在转换auid-91a56d1a081f402d.cif
正在转换auid-91bd79e6cab2fef4.cif
正在转换auid-9281df1db7a11033.cif
正在转换auid-935c9c1922d7177f.cif
正在转换auid-94562cb5164af938.cif
正在转换auid-949b39fa074c0c2d.cif
正在转换auid-94ac86abae15b318.cif
正在转换auid-94d23169a3edb54d.cif
正在转换auid-971b968dbd110703.cif
正在转换auid-9764acc6a2392828.cif
正在转换auid-97cfb7b3d971d954.cif
正在转换auid-97d061f124ec3613.cif
正在转换auid-9acc95b6ef7b959a.cif
正在转换auid-9c541fb40c586484.cif
正在转换auid-9dc43e2c051dad1c.cif
正在转换auid-9df7497c5de2f7f7.cif
正在转换auid-9f51940d2892a6dd.cif
正在转换auid-9fd31945a1545473.cif
正在转换auid-a0d82d8a1a9a0263.cif
正在转换auid-a0eb0703a9aa3d93.cif
正在转换auid-a16769e214bc9e1c.cif
正在转换auid-a396e9d3cd63e8df.cif
正在转换auid-a4413e5e119cae41.cif
正在转换auid-a6ac4967ddf1ea2e.cif
正在转换auid-a6be0902f6c015aa.cif
正在转换auid-a7001511e5d29662.cif
正在转换auid-a77d89d8bd3c0d43.cif
正在转换auid-a7fb676f61ef57d1.cif
正在转换auid-aa0c595d09e3e85b.cif
正在转换auid-aa200d63949dc908.cif
正在转换auid-aa6c91b015472e11.cif
正在转换auid-ab4a4804dbb6c758.cif
正在转换auid-ab9613c181249d77.cif

正在转换auid-ab99f6466296a555.cif
正在转换auid-acbfea8c74fc9f4c.cif
正在转换auid-ad5547f15fa37f1c.cif
正在转换auid-ade748058f9e0336.cif
正在转换auid-b069d7222605acaf.cif
正在转换auid-b117c08dd43ac161.cif
正在转换auid-b2dd7308caac691c.cif
正在转换auid-b36f1cc08f3da3fe.cif
正在转换auid-b55478d4cf3f5677.cif
正在转换auid-b56a455123642ac0.cif
正在转换auid-b65240448ffdd7bd.cif
正在转换auid-b6addbc2476548ef.cif
正在转换auid-b754c5f84aa8a9dd.cif
正在转换auid-b914bbecc8bf1585.cif
正在转换auid-ba2743318139b75a.cif
正在转换auid-ba2edf205f0ef9ad.cif
正在转换auid-bc166ade7a110e7b.cif
正在转换auid-bc85291baffcba97.cif
正在转换auid-bce435bb23c2316a.cif
正在转换auid-bd38504b235a95ad.cif
正在转换auid-bd51f1424f37283b.cif
正在转换auid-bdd29f2602264495.cif
正在转换auid-be0024774c814dbb.cif
正在转换auid-beda509f21ce71e7.cif
正在转换auid-bf9ce6514500110d.cif
正在转换auid-c0990522c54cbe05.cif
正在转换auid-c09dc168df373ec2.cif
正在转换auid-c27827a2ca140239.cif
正在转换auid-c2d6eb635e09f9d5.cif
正在转换auid-c33f9456bebccdd2.cif
正在转换auid-c67ba165759c0f3a.cif
正在转换auid-c6917abaa5e1b2a4.cif
正在转换auid-c6aba478f58a49e6.cif
正在转换auid-c724059f93f9dbc1.cif
正在转换auid-c83d52a8fc2940e9.cif
正在转换auid-c952a091e251b113.cif
正在转换auid-c9f9bd7ec447f7fa.cif
正在转换auid-ca16f943e317a15e.cif
正在转换auid-cad84f9fc9a966c6.cif
正在转换auid-cb0798e54a875c59.cif
正在转换auid-cb2f68179112ee16.cif
正在转换auid-cbd131b2648fcda7.cif
正在转换auid-ccc9ae21873d8274.cif
正在转换auid-ccd6d6a2c75d6ed2.cif
正在转换auid-cd0728d0cb447a71.cif
正在转换auid-cdb506ff491d7964.cif
正在转换auid-ce0831647ef8905c.cif
正在转换auid-ce0f1d3a4058668a.cif
正在转换auid-cf08c178232a228d.cif
正在转换auid-d16948f11dd1802a.cif
正在转换auid-d1ead0ad34879517.cif
正在转换auid-d27ceb6549f7c122.cif
正在转换auid-d28c6f4aeee54863.cif
正在转换auid-d31aa88b835760ed.cif
正在转换auid-d430209c1a940198.cif
正在转换auid-d47af6ef523320fa.cif
正在转换auid-d522617745b7d3a5.cif
正在转换auid-d59693f1ad62ff06.cif
正在转换auid-d734df7a6e113241.cif
正在转换auid-d81d95247a5c1953.cif
正在转换auid-d840bc261783e9b1.cif
正在转换auid-d8723ffed9a02783.cif
正在转换auid-d8adba03309783be.cif
正在转换auid-d8b95b60493f3d0f.cif
正在转换auid-da171bac2829ffd6.cif
正在转换auid-db0ecc9fc4041032.cif
正在转换auid-db29ed21b7b18347.cif
正在转换auid-db8d4ddc9c99ed54.cif
正在转换auid-dc8e65444a6c6df3.cif
正在转换auid-dcc74250cad3a6d1.cif
正在转换auid-ddcbddd6f9d6752f.cif
正在转换auid-e0faa2c6eb4dba8f.cif
正在转换auid-e11b284add48083c.cif
正在转换auid-e11f5e54ea00e77c.cif
正在转换auid-e1837a18b1eb17aa.cif
正在转换auid-e1fc31459de4b953.cif
正在转换auid-e336905d5a374f9d.cif
正在转换auid-e392ffaffae76741.cif
正在转换auid-e3e919cdb4b56425.cif
正在转换auid-e4a91fd9377a08bf.cif
正在转换auid-e54e4d78852e4240.cif
正在转换auid-e59931377d2e6900.cif
正在转换auid-e59cfcc1fbfe8cc2.cif
正在转换auid-e7cbf7a0d3cc0caf.cif
正在转换auid-e80f1e3cd321bace.cif
正在转换auid-e9394ca8518c81dc.cif
正在转换auid-e9549c1713a78eb9.cif
正在转换auid-ea23f4a934524fcb.cif
正在转换auid-ea310658d792b15e.cif
正在转换auid-eb16dc434b5b27c1.cif
正在转换auid-ecb1cb9bbf5e2b36.cif
正在转换auid-eced79d584088219.cif
正在转换auid-eda65684b3a21c7f.cif
正在转换auid-ee2110f54f02effd.cif
正在转换auid-ee77684690fb6b2d.cif
正在转换auid-ef258a6de52cf2ab.cif
正在转换auid-efdafd2ef6d7d1dc.cif
正在转换auid-f150618ddfa9ec74.cif
正在转换auid-f15af8376333f6a3.cif
正在转换auid-f48f60a94ef526c0.cif
正在转换auid-f4ef6c7fb77037e5.cif
正在转换auid-f52e967729d338d4.cif
正在转换auid-f663ea2fcc26e175.cif
正在转换auid-f6bb2ba69b3a90ae.cif
正在转换auid-f73aa274b6d99dbb.cif
正在转换auid-f740450b66606c5f.cif
正在转换auid-f742cddeefde3425.cif
正在转换auid-f7fcdaf2fbc3b34f.cif
正在转换auid-f9201e19bcde5070.cif
正在转换auid-f9d6913c1c594b46.cif
正在转换auid-f9efaaba9249ac20.cif
正在转换auid-fb3350fa5e236062.cif
正在转换auid-fbb4dbf5706b60ee.cif
正在转换auid-fbb8fc43192932d8.cif
正在转换auid-fe1c2f51d5722606.cif
正在转换auid-febdce4593c89393.cif
正在转换auid-ffa9fc3654b3b332.cif
正在转换mp-1064508.cif
正在转换mp-1065428.cif
正在转换mp-1066774.cif
正在转换mp-1067281.cif
正在转换mp-1071468.cif
正在转换mp-1072345.cif
正在转换mp-1077197.cif
正在转换mp-1077558.cif
正在转换mp-1091362.cif
正在转换mp-12467.cif
正在转换mp-30734.cif
正在转换mp-4901.cif
正在转换mp-567351.cif
正在转换mp-567685.cif
正在转换mp-568366.cif
正在转换mp-568944.cif
正在转换mp-571634.cif
正在转换mp-7822.cif
正在转换mp-8306.cif
正在转换mp-867301.cif
正在转换mp-8793.cif
正在转换mp-1025473.cif
正在转换mp-1069676.cif
正在转换mp-1077015.cif
正在转换mp-1079567.cif
正在转换mp-1079867.cif
正在转换mp-12612.cif
正在转换mp-504574.cif
正在转换mp-569037.cif
正在转换mp-8331.cif
正在转换WS21T.cif
正在转换auid-00de515b4d913464.cif
正在转换auid-01833ed0bc73d87b.cif
正在转换auid-026e249a883ba158.cif
正在转换auid-02eb1aca01bfa034.cif
正在转换auid-044c62695be4e867.cif
正在转换auid-04d3437b6910ea5c.cif
正在转换auid-0535c39171ea5e02.cif
正在转换auid-057c6cf61058e4a6.cif
正在转换auid-05e1233fcaaaac75.cif
正在转换auid-06021e991ec0dd0e.cif
正在转换auid-062e0b3d312db9a8.cif
正在转换auid-0630152bff918bb3.cif
正在转换auid-06583ed68bd59af3.cif
正在转换auid-06b996b1837a5528.cif
正在转换auid-074c053b16d76259.cif
正在转换auid-090bf5032c09fb4b.cif
正在转换auid-09172cee4c8b0b5d.cif
正在转换auid-093428e235beac28.cif
正在转换auid-0996d6b853f91c80.cif
正在转换auid-09b66d804e066dcf.cif
正在转换auid-0b5a310f95f9b61d.cif
正在转换auid-0c655078c5923e38.cif
正在转换auid-0ce8b63aa2bb0b25.cif
正在转换auid-0dfdda857671a96f.cif
正在转换auid-0f19a693554e5fff.cif
正在转换auid-0f2c7cf34f6bfcce.cif
正在转换auid-0fa1454f7856a931.cif
正在转换auid-0fdcf5fe586b2796.cif
正在转换auid-1187a13e307b1467.cif
正在转换auid-118f69a01c59d058.cif
正在转换auid-1210f770b209ce8b.cif
正在转换auid-121ff7eceb1b4176.cif
正在转换auid-12213c407aab2f2f.cif
正在转换auid-1234258cc44eba4e.cif
正在转换auid-1315339252ce2c09.cif
正在转换auid-133395d8eda36d69.cif
正在转换auid-14b22d762b37212b.cif
正在转换auid-162e5f44aaafade9.cif
正在转换auid-167e6085aae98ce2.cif
正在转换auid-176fa29ebafe4cd1.cif
正在转换auid-178827188b3d68c5.cif
正在转换auid-178e4e7a12da99e1.cif
正在转换auid-17a75f7f34bf79ac.cif
正在转换auid-17ef93c8356fca27.cif
正在转换auid-19848e01620e9bb3.cif
正在转换auid-199e4673c122ef69.cif
正在转换auid-1a5ba2287dda4855.cif
正在转换auid-1a7c1b71683aa503.cif
正在转换auid-1b6f1bf622070c7a.cif
正在转换auid-1bae10701ff8c94b.cif
正在转换auid-1c85f63a841ce1b6.cif
正在转换auid-1d0172fe5c9690b2.cif
正在转换auid-1d2d1c54d9fb7554.cif
正在转换auid-1d92171064f51560.cif
正在转换auid-1da3cca9213f948a.cif
正在转换auid-1dbf0973609ef426.cif
正在转换auid-1e27c11ed3ecc127.cif
正在转换auid-1ead6f5c10847635.cif
正在转换auid-1efce37a7dbbee49.cif
正在转换auid-1f0c2d0281c99cae.cif
正在转换auid-1fcb53cf2e5e0aa0.cif
正在转换auid-22bcb8961539e3de.cif
正在转换auid-23102d93904823d3.cif
正在转换auid-2376d4cf46f8a7a5.cif
正在转换auid-24c385733d8de9de.cif
正在转换auid-2579f8859f077821.cif
正在转换auid-2753e7b2180f0a21.cif
正在转换auid-27e1e0bb0dc929a7.cif
正在转换auid-27ea0332e686ba6b.cif
正在转换auid-2807ad70749f1bbd.cif
正在转换auid-28fc186e4dc75187.cif
正在转换auid-29e2cbc30d3ad9c5.cif
正在转换auid-2a1f31f79be2f707.cif
正在转换auid-2a2a20a1151d6073.cif
正在转换auid-2a6c3ff3fb609cac.cif
正在转换auid-2c010e66a7d3cc56.cif
正在转换auid-2c59959cc2a68d67.cif
正在转换auid-2d7d69f0c2041daa.cif
正在转换auid-2d92d69c74a9f4ca.cif
正在转换auid-2ec1175f4875013e.cif
正在转换auid-2ef8625ccec7776b.cif
正在转换auid-2f9909b46e9cd64d.cif
正在转换auid-2fba16b1103b264b.cif
正在转换auid-300d0aefad214689.cif
正在转换auid-302e14055b933cfb.cif
正在转换auid-304b258606cb7cd4.cif
正在转换auid-30a395f89737363c.cif
正在转换auid-30d7c980694729a0.cif
正在转换auid-30ecbf54c00c9b3a.cif
正在转换auid-31b1262a53fa47b6.cif
正在转换auid-32424d2ea3ed289f.cif
正在转换auid-3290938c314bd43b.cif
正在转换auid-32fec1075c3e0abd.cif
正在转换auid-3311d34ca864f2a4.cif
正在转换auid-33593a8058c298ad.cif
正在转换auid-33665009db21c4d4.cif
正在转换auid-344bd10f777abd3c.cif
正在转换auid-352938f9e1442542.cif
正在转换auid-3536662f7dc624fc.cif
正在转换auid-3537e780fad4835c.cif
正在转换auid-35687229c87fd0c1.cif
正在转换auid-35c8f7eaf5e394cb.cif
正在转换auid-35d6fecec10e311f.cif
正在转换auid-36500cbca5544c13.cif
正在转换auid-36f5deaa0e2d854b.cif
正在转换auid-3793ce8311016565.cif
正在转换auid-3793ea5c1f2c4491.cif
正在转换auid-37e015a0a6bb60e8.cif
正在转换auid-388c852a2f4d9745.cif
正在转换auid-393709f444b8e50b.cif
正在转换auid-3a74362d0df8c0d8.cif
正在转换auid-3b6362dd20d91d61.cif
正在转换auid-3b71293ffbf9333e.cif
正在转换auid-3b7d4c3705a9f721.cif
正在转换auid-3cec61ae47f81e8d.cif
正在转换auid-3db990b0946271bc.cif
正在转换auid-3f2c4cb5e1b18c0c.cif
正在转换auid-3f66c69bda2a2911.cif
正在转换auid-3fac95ca9708dffb.cif
正在转换auid-3fdbd50dbc8b9ab7.cif
正在转换auid-408f9a200f7d74af.cif
正在转换auid-40a4046781a326e1.cif
正在转换auid-40c926b67563e4c3.cif
正在转换auid-40f48e1c5424acdf.cif
正在转换auid-413ed8eb9cd8dbe9.cif
正在转换auid-416243ab8d47200c.cif
正在转换auid-417314368d5881ea.cif
正在转换auid-425aeec82388e08d.cif
正在转换auid-42ed4e62ead22e99.cif
正在转换auid-435b44f4521b1ac7.cif
正在转换auid-43b0a66ae0e4a616.cif
正在转换auid-441205b0ce89cb2b.cif
正在转换auid-44f476eb62e06c07.cif
正在转换auid-452c202f3c71db29.cif
正在转换auid-4589a156160a4e5f.cif
正在转换auid-459f9d8e57bfa82d.cif
正在转换auid-45ee28dbe4851ba9.cif
正在转换auid-46119946a55c152a.cif
正在转换auid-4618038c38a8c591.cif
正在转换auid-46e208ed07b6729d.cif
正在转换auid-4738ca675e236b45.cif
正在转换auid-4750a9cf44b0a78c.cif
正在转换auid-486d24b581931f5a.cif
正在转换auid-48e7ffd291b94a24.cif
正在转换auid-497f44a39e67a57c.cif
正在转换auid-497f44b11acbd3f0.cif
正在转换auid-4b054effc8ea7a7c.cif
正在转换auid-4b945f5d1ac72d68.cif
正在转换auid-4c070585478cd07b.cif
正在转换auid-4c220dbbe931b7d7.cif
正在转换auid-4ce972eb4082a024.cif
正在转换auid-4d12bbdbfc60ec25.cif
正在转换auid-4d608270403b0d3f.cif
正在转换auid-4dd1221e11c42a33.cif
正在转换auid-4de4f4a408fda42c.cif
正在转换auid-4ff36377aa6ecc2c.cif
正在转换auid-5018d0eb61558b6f.cif
正在转换auid-503ade5d4082304c.cif
正在转换auid-506c3edeb0ec3650.cif
正在转换auid-50d4b914c20ec9fe.cif
正在转换auid-5121c1916c4e1bf1.cif
正在转换auid-51b8f139b6f5653e.cif
正在转换auid-51ff82f462c0f6f6.cif
正在转换auid-522bd2d522aa571d.cif

正在转换auid-5230de283a59c72f.cif
正在转换auid-52495c4f43a1ada2.cif
正在转换auid-525ee3521eacce28.cif
正在转换auid-53594dee987c96d8.cif
正在转换auid-5478a1d40d9c581a.cif
正在转换auid-54a87e4fb210cf73.cif
正在转换auid-54b6e6f6ea7d8d62.cif
正在转换auid-54b7254c9296ae10.cif
正在转换auid-54cd3246b378e7e0.cif
正在转换auid-54de0464da79258b.cif
正在转换auid-54e39c07823f68e3.cif
正在转换auid-551cd16d05ed0e2d.cif
正在转换auid-554936cdb6ebc000.cif
正在转换auid-55a190bc8b3140fb.cif
正在转换auid-563abbf786416183.cif
正在转换auid-56605fa6a7de2b7a.cif
正在转换auid-57309fe70e09c5c1.cif
正在转换auid-573e4d7fa46d9392.cif
正在转换auid-5788573995fa102e.cif
正在转换auid-585c5a5351ec6134.cif
正在转换auid-5885873e97c84774.cif
正在转换auid-5895963acbf0fbc3.cif
正在转换auid-594dc98d5a801749.cif
正在转换auid-5959766ed0fbc431.cif
正在转换auid-59852c8b569af254.cif
正在转换auid-5a1a4756045f8344.cif
正在转换auid-5bab89ea307a6273.cif
正在转换auid-5c3884cd24f75114.cif
正在转换auid-5c63a87d667405ac.cif
正在转换auid-5c95eaaf3af26dce.cif
正在转换auid-5cb748aae9ed30a4.cif
正在转换auid-5e43957a32e7bee4.cif
正在转换auid-5ecb4fe58ab3dec3.cif
正在转换auid-5edb8d7e1068bfdd.cif
正在转换auid-5fb1d899aa21e016.cif
正在转换auid-5fd441ba7254361e.cif
正在转换auid-5ff8cf9b391c58aa.cif
正在转换auid-5ffb5760b51496da.cif
正在转换auid-5ffd17cd9608ab2e.cif
正在转换auid-60b3e83a7c7ef058.cif
正在转换auid-60c944dc6285e2cc.cif
正在转换auid-60fcf76980fc0a9a.cif
正在转换auid-61250b55273e40fa.cif
正在转换auid-6126deea52c8160e.cif
正在转换auid-62799d1ad211efc6.cif
正在转换auid-6328e84c2e9c0651.cif
正在转换auid-636d6994a160a24f.cif
正在转换auid-638135e2a7b46a3d.cif
正在转换auid-63d0d6d98a4352d7.cif
正在转换auid-640cb39d64b4710e.cif
正在转换auid-64250de0829705aa.cif
正在转换auid-64c0bc06831081d2.cif
正在转换auid-64c106dd0c34e78b.cif
正在转换auid-6594d80fa1db7fe6.cif
正在转换auid-65a68145406614b5.cif
正在转换auid-65e48152ec8b3395.cif
正在转换auid-678eddef08f29c30.cif
正在转换auid-679e3b5a7ccf407b.cif
正在转换auid-67e066eb88eef0ec.cif
正在转换auid-68230bf89725b7ef.cif
正在转换auid-6830e72f00f176bc.cif
正在转换auid-683f6c313753730d.cif
正在转换auid-6855fb426d4824fa.cif
正在转换auid-695e2126eaba95c3.cif
正在转换auid-6b79d823a5d2a273.cif
正在转换auid-6c353c8f52354958.cif
正在转换auid-6d17b40c71cb2854.cif
正在转换auid-6d3eb4bd9505127e.cif
正在转换auid-6e280c38c72d62a9.cif
正在转换auid-6ee4b6c123e1abbc.cif
正在转换auid-6fcda856c4739a6d.cif
正在转换auid-6fdffad808986662.cif
正在转换auid-70b4cd84128529e5.cif
正在转换auid-715fb02138f6e684.cif
正在转换auid-7218a334150080f4.cif
正在转换auid-72ae9299960ebea8.cif
正在转换auid-7370fe52d5a87894.cif
正在转换auid-73a74f569187be7f.cif
正在转换auid-742ededff3350b1c.cif
正在转换auid-7509130a05f23fe7.cif
正在转换auid-7725a23aa20b6f52.cif
正在转换auid-775d8c72caf06e97.cif
正在转换auid-779c6112de795911.cif
正在转换auid-77cc415aafb64c0d.cif
正在转换auid-7858e9bab3194e31.cif
正在转换auid-78c75bba9cd58a11.cif
正在转换auid-7930639fedc62074.cif
正在转换auid-7a2693292fd5d1dc.cif
正在转换auid-7a45abc6afa4c0e8.cif
正在转换auid-7b493e156c50710e.cif
正在转换auid-7b94e494e26706d2.cif
正在转换auid-7cedb15a182d72a3.cif
正在转换auid-7d4936b1e1e77917.cif
正在转换auid-7db303c6bde7d76a.cif
正在转换auid-7f793c108d5951b9.cif
正在转换auid-7f93378724e46246.cif
正在转换auid-8251ccc5326b7543.cif
正在转换auid-829cc13894248f99.cif
正在转换auid-83145fb09889f3dc.cif
正在转换auid-8378f10c11cc8a99.cif
正在转换auid-83b7956e42ac0dae.cif
正在转换auid-841fa07bc620e3eb.cif
正在转换auid-8460279265a3c85f.cif
正在转换auid-846cc312b697cf05.cif
正在转换auid-85283bf395a7a88c.cif
正在转换auid-855a412c54468669.cif
正在转换auid-858a550973b99266.cif
正在转换auid-85c4857d1cb9e179.cif
正在转换auid-85f2db8f7e3461cf.cif
正在转换auid-86339a0e01e12c98.cif
正在转换auid-86f975575ba6bab2.cif
正在转换auid-8723ef5ca7be1d06.cif
正在转换auid-87ea4ed5f695efe1.cif
正在转换auid-899e4e2229bc5113.cif
正在转换auid-89bac1efbaacb022.cif
正在转换auid-8a0c9ed0cc7b6ed1.cif
正在转换auid-8a3dceae84c528d7.cif
正在转换auid-8b22d4f64d73236f.cif
正在转换auid-8b253b75f9bfd666.cif
正在转换auid-8b85bd8d907c8488.cif
正在转换auid-8bdfa60ef252daf8.cif
正在转换auid-8beba2cb8eaae501.cif
正在转换auid-8c1a46f82cc51130.cif
正在转换auid-8c1c7070c92cb41a.cif
正在转换auid-8ccb9656dc330e4b.cif
正在转换auid-8cd8d7f5d77f3ac9.cif
正在转换auid-8dfe097e25f7073d.cif
正在转换auid-8e763a59f448c72b.cif
正在转换auid-8f76f8c6db51322a.cif
正在转换auid-8fbb0c1ffd3c76be.cif
正在转换auid-90008fce4c064410.cif
正在转换auid-90a192fe297e4697.cif
正在转换auid-90f5f356fd4abcba.cif
正在转换auid-923207c0f8d3dd05.cif
正在转换auid-924695ef8b035157.cif
正在转换auid-9281e48005aaab47.cif
正在转换auid-92bf7cec9feb794b.cif
正在转换auid-93012053941b937b.cif
正在转换auid-931552eb23708ece.cif
正在转换auid-944882537dc9c7e4.cif
正在转换auid-94dd7ee888e61848.cif
正在转换auid-96861b94bfcb7128.cif
正在转换auid-9704ea065d1d895f.cif
正在转换auid-97f0dad65df94067.cif
正在转换auid-98c634c5efc90553.cif
正在转换auid-99100efa760499d0.cif
正在转换auid-991d8636825601b4.cif
正在转换auid-99e17d6460473a52.cif
正在转换auid-9a786daec6779cb0.cif
正在转换auid-9ad5bcea066b25fb.cif
正在转换auid-9b5b5d94c1552530.cif
正在转换auid-9c10411def517534.cif
正在转换auid-9c41ee61f38cdde2.cif
正在转换auid-9c742b4c5221f4ad.cif
正在转换auid-9d4435e75b6599af.cif
正在转换auid-9deb57db1af9ebdc.cif
正在转换auid-9e0843169a15441c.cif
正在转换auid-9fa6488a50fcfb91.cif
正在转换auid-9fe24579b9fb1175.cif
正在转换auid-9fe9527e49f5feb3.cif
正在转换auid-a02ccc16f8423b29.cif
正在转换auid-a07cc9a8fa93d36c.cif
正在转换auid-a0ed04d804214f9a.cif
正在转换auid-a1b0774c084e4562.cif
正在转换auid-a1d4361c9ef6184d.cif
正在转换auid-a2f7c77f301150e2.cif
正在转换auid-a2fa57dc11dc4eda.cif
正在转换auid-a3e0271acdfe7368.cif
正在转换auid-a5f693c5c54ce4ad.cif
正在转换auid-a6ba5862a3433546.cif
正在转换auid-a6dd2fae50f42cec.cif
正在转换auid-a738e7975d8bba8d.cif
正在转换auid-a73eaccb45447d23.cif
正在转换auid-a7ce3ccf8849561f.cif
正在转换auid-a7f93ce7d083a901.cif
正在转换auid-a832ab135a29225b.cif
正在转换auid-a8418fa87e386f92.cif
正在转换auid-a84f1ae6303832b8.cif
正在转换auid-a8b669240a542a9e.cif
正在转换auid-a9bda407ea26c59d.cif
正在转换auid-a9e0a70fb01efef1.cif
正在转换auid-ab8a69ab92d4db7b.cif
正在转换auid-acb298d8041b6785.cif
正在转换auid-acda48d3e8fbf752.cif
正在转换auid-ad452b69252aabb8.cif
正在转换auid-ad66182a13534811.cif
正在转换auid-ad75e3bb05c7dcb3.cif
正在转换auid-adc5c61a85b1c62e.cif
正在转换auid-ae1161016bf65887.cif
正在转换auid-ae336e2a73f5f125.cif
正在转换auid-ae5246273347123b.cif
正在转换auid-af681f2cea6216bc.cif
正在转换auid-b25d98b38efb9ba7.cif
正在转换auid-b2def555ab15e77e.cif
正在转换auid-b352cff299cead04.cif
正在转换auid-b364445cd8af52b0.cif
正在转换auid-b3a522e9ec10bcaa.cif
正在转换auid-b3b087b1512b451e.cif
正在转换auid-b3e15121de2b7dcf.cif
正在转换auid-b4e0ad3c3b2bc890.cif
正在转换auid-b51687dcdd55e0b3.cif
正在转换auid-b573a8c36a91e8cf.cif
正在转换auid-b5c7d7e7d63f608f.cif
正在转换auid-b603e9e5f00cce0c.cif
正在转换auid-b67006fac95c1b67.cif
正在转换auid-b6aa5550d52b26d0.cif
正在转换auid-b756c6c63c0a91db.cif
正在转换auid-b84576ea3e357509.cif
正在转换auid-b878cbbf801bc373.cif
正在转换auid-b8ce7df94ae6c705.cif
正在转换auid-b90e0e62c4c0f940.cif
正在转换auid-ba087164933c3809.cif
正在转换auid-ba35890aeef36751.cif
正在转换auid-ba96a6574fe7a5c8.cif
正在转换auid-badd2b3331cb2e04.cif
正在转换auid-bb3a9b7c63793d44.cif
正在转换auid-bb99294028a12537.cif
正在转换auid-bbabb90d490cc5d1.cif
正在转换auid-bc4591d7f6e7c4ca.cif
正在转换auid-bd8720e030e81d06.cif
正在转换auid-bd99d41ecab61194.cif
正在转换auid-bdea0b45cc9d9a10.cif
正在转换auid-be54c0cf6785e457.cif
正在转换auid-bee240494423f8a7.cif
正在转换auid-bf6450224f4c21e1.cif
正在转换auid-bf8be7620bba69a2.cif
正在转换auid-c07468f1698c993e.cif
正在转换auid-c1b7169b9619942b.cif
正在转换auid-c2e121f6382fff2c.cif
正在转换auid-c2f5769e77291a13.cif
正在转换auid-c313f362b2d8319c.cif
正在转换auid-c32e0d6dbc92455e.cif
正在转换auid-c3c7abe9e21e9a33.cif
正在转换auid-c3ea719993906b7d.cif
正在转换auid-c481306b3fcde240.cif
正在转换auid-c4cbe548b9dd2562.cif
正在转换auid-c5053d43d487fd2c.cif
正在转换auid-c55ca8224dbb2fe2.cif
正在转换auid-c58a0faf0435de6d.cif
正在转换auid-c5a072338693add4.cif
正在转换auid-c6122521ed6dab65.cif
正在转换auid-c64ae31b8462c036.cif
正在转换auid-c653dcdfd395eee3.cif
正在转换auid-c68c4edb0a271dc1.cif
正在转换auid-c6bfbf780e3e9949.cif
正在转换auid-c703575417f496a1.cif
正在转换auid-c70425710d14d5a2.cif
正在转换auid-c72f1667e9b40066.cif
正在转换auid-c77b3d719c75c7c8.cif
正在转换auid-c780b6a60cb7d4f3.cif
正在转换auid-c78b1fe6d4927e3e.cif
正在转换auid-c7eef974b8cc0270.cif
正在转换auid-c8a9915f6e9b1a76.cif
正在转换auid-c9a9bf0abad02beb.cif
正在转换auid-ca932948628f93a6.cif
正在转换auid-cafea6fb6f88b0ad.cif
正在转换auid-cbcb1f5eab87914f.cif
正在转换auid-cc0ca7a75b1e4de2.cif
正在转换auid-cc3d5f8164b3c369.cif
正在转换auid-cc570c1d265b882c.cif
正在转换auid-ccb8d0cb5ebd3ce0.cif
正在转换auid-ccd8672aff6f45a2.cif
正在转换auid-cdb555c9e7885dae.cif
正在转换auid-cdc6f121da3bc0f3.cif
正在转换auid-ce0ab15f07beeb26.cif
正在转换auid-ce8c2047e41fd508.cif
正在转换auid-ce9de409534993b7.cif
正在转换auid-cf5e72401090d2b3.cif
正在转换auid-cf7811d68e5bca54.cif
正在转换auid-cfafc98dc25cfa2f.cif
正在转换auid-cfd9ebbb8ad3b0fc.cif
正在转换auid-d01c40c80ad365bb.cif
正在转换auid-d054b7bb594d5330.cif
正在转换auid-d0a220104c0743c2.cif
正在转换auid-d0ce0c9050862cac.cif
正在转换auid-d196382feff72cdd.cif
正在转换auid-d1eb3dddaaef9dc5.cif
正在转换auid-d20cbb69a9bedf63.cif
正在转换auid-d21f1e10ce5d738e.cif
正在转换auid-d22e21f808255401.cif
正在转换auid-d248d050b1211a11.cif
正在转换auid-d38884b088cc6d10.cif
正在转换auid-d392debd7782d921.cif
正在转换auid-d537ef0156cd1004.cif
正在转换auid-d5c55b3f0c3d0035.cif
正在转换auid-d659a88473162f00.cif
正在转换auid-d6652deaff6e9a3e.cif
正在转换auid-d691a7714c299422.cif
正在转换auid-d6ad1cd01ced7536.cif
正在转换auid-d6ca150d56ddfabd.cif
正在转换auid-d90157bc2920fd78.cif
正在转换auid-d9aa30e181ce33fe.cif
正在转换auid-da7b5287cc03ab1c.cif
正在转换auid-dadfe47f6fcaad33.cif
正在转换auid-daf92e2357e58847.cif
正在转换auid-db9249669c6e0874.cif
正在转换auid-dc47af6e4d5cdcde.cif
正在转换auid-dcb3b42c77b44cd0.cif
正在转换auid-dcea950bc78ce484.cif
正在转换auid-dcff8e22d26f065d.cif
正在转换auid-dd66ad7ff9c21ac6.cif
正在转换auid-dd68f404ee51bc29.cif
正在转换auid-dd92457db7e5771d.cif
正在转换auid-ddc76ee65f268a7f.cif
正在转换auid-dddb50368019d417.cif
正在转换auid-de609093c725c369.cif
正在转换auid-deecfdd88b2ba5d9.cif
正在转换auid-dfaae8cd975ba349.cif

正在转换auid-e01617b71c5271eb.cif
正在转换auid-e17460645c26419e.cif
正在转换auid-e1ab88486202b08c.cif
正在转换auid-e1fff85011148576.cif
正在转换auid-e3872ce4c31acedb.cif
正在转换auid-e3f0a6a50df4682f.cif
正在转换auid-e434a4eceb5016be.cif
正在转换auid-e467b10a92efc996.cif
正在转换auid-e4e5ad04309aec34.cif
正在转换auid-e51e3834c06b8cf4.cif
正在转换auid-e639b92e29d3c9f9.cif
正在转换auid-e64123565b2e8069.cif
正在转换auid-e64effe1776238aa.cif
正在转换auid-e7598cffdecd67db.cif
正在转换auid-e7ff4141841146ef.cif
正在转换auid-e9448c8163049cd5.cif
正在转换auid-e9d41c1a29cee474.cif
正在转换auid-ea3c77b449c79844.cif
正在转换auid-ea6362b69af1ac59.cif
正在转换auid-eaab119c618cb263.cif
正在转换auid-eac06ee2f94270dc.cif
正在转换auid-eafa66a64c2639c8.cif
正在转换auid-eb5ff9bc8ddd0c00.cif
正在转换auid-ebbbc4a6a233885f.cif
正在转换auid-ec3eed7d4ae4e9fc.cif
正在转换auid-ec63b8eae8b57de3.cif
正在转换auid-ecc6107bdd6c63a8.cif
正在转换auid-ecd5d66b93e90285.cif
正在转换auid-ed5b32346f55a197.cif
正在转换auid-ed82fe2feff921c8.cif
正在转换auid-edd9affe258d7a51.cif
正在转换auid-eeb1fb49f189fa33.cif
正在转换auid-f026573eb2562566.cif
正在转换auid-f09beada309bff8d.cif
正在转换auid-f0b3e01ea9da9801.cif
正在转换auid-f0ce8d0673164e8a.cif
正在转换auid-f0f4a0277f74fd69.cif
正在转换auid-f16b8b0707d6d33f.cif
正在转换auid-f27c8a0d56009335.cif
正在转换auid-f2a5bc37e3a7908e.cif
正在转换auid-f2bc8e50b56b6ace.cif
正在转换auid-f2ee1c4da21485dc.cif
正在转换auid-f3436c80c102be07.cif
正在转换auid-f3fbc6d7630ca360.cif
正在转换auid-f4b0c5fe58a63652.cif
正在转换auid-f5f58f9dc9920f7a.cif
正在转换auid-f640640ac27ab6ec.cif
正在转换auid-f6526aa9bcf7cef1.cif
正在转换auid-f6efe19bf18c37b4.cif
正在转换auid-f76ae887ba7a6b6d.cif
正在转换auid-f884704855042153.cif
正在转换auid-f91fcf62c212df15.cif
正在转换auid-f98b0d6349b274aa.cif
正在转换auid-f9e5734d3afe146a.cif
正在转换auid-faa22188872db4e5.cif
正在转换auid-fb090943e85c6232.cif
正在转换auid-fb194759ddaf49ea.cif
正在转换auid-fb8dd2ba7953287b.cif
正在转换auid-fc033d0c971116f1.cif
正在转换auid-fc6b4a05c46f007d.cif
正在转换auid-fca8840c7e5e4194.cif
正在转换auid-fdd96c8a5feb711c.cif
正在转换auid-fe0166580b2b7e3d.cif
正在转换auid-feaf5fd75e01f3fe.cif
正在转换auid-ff332664489e2b5f.cif
正在转换auid-ff42e1ffb1ae4b18.cif
正在转换auid-fff8045c77b6396f.cif
正在转换auid-2813acfb92a9ea01.cif
正在转换auid-010918b5163550d6.cif
正在转换auid-02c93fef51139167.cif
正在转换auid-0316adb811547b14.cif
正在转换auid-035edcec638843b2.cif
正在转换auid-037b8d4fa57bdfd3.cif
正在转换auid-03b152867b2949ba.cif
正在转换auid-0475379befd0e67f.cif
正在转换auid-04964a651630e565.cif
正在转换auid-049bb46104c3c46e.cif
正在转换auid-0520eb545c837067.cif
正在转换auid-05869143e27dddda.cif
正在转换auid-07c08de0e259e2b8.cif
正在转换auid-081617f43a8b446f.cif
正在转换auid-0930caf8bcc37d90.cif
正在转换auid-09ca5b0c4fee8847.cif
正在转换auid-09e1b7a75229e855.cif
正在转换auid-0ab1a1ec6b678209.cif
正在转换auid-0ab3bf9bae47c56c.cif
正在转换auid-0b46ec159a3dd5b9.cif
正在转换auid-0b61edd815715276.cif
正在转换auid-0b7481d8bc042b91.cif
正在转换auid-0bcfe52302489718.cif
正在转换auid-0db4fff4355702e0.cif
正在转换auid-0db85fd5afd8d4f2.cif
正在转换auid-0f454bf8557e4651.cif
正在转换auid-0f7fdb8f09d02528.cif
正在转换auid-0fb4ffc5f24c977c.cif
正在转换auid-1087422bb3642a22.cif
正在转换auid-10aa7dbbed3a4be1.cif
正在转换auid-114c258503f80036.cif
正在转换auid-117b59cae7588a07.cif
正在转换auid-11a6f42666699406.cif
正在转换auid-14c7f24f483e1a61.cif
正在转换auid-14e02da2b569ca28.cif
正在转换auid-159a33f6e337587b.cif
正在转换auid-1648bbfd705e374b.cif
正在转换auid-1668eefc383c54d1.cif
正在转换auid-16cd433967aa0c47.cif
正在转换auid-1791a873c1d8d8a0.cif
正在转换auid-17b1556e414518a2.cif
正在转换auid-1a4c8d93e5bde21e.cif
正在转换auid-1a9c7a52cd4872f6.cif
正在转换auid-1b9773566bcbc09d.cif
正在转换auid-1c95a1f04efea0ed.cif
正在转换auid-1f7ac8e0d71639a2.cif
正在转换auid-1f8bd1379cca0f35.cif
正在转换auid-206a71c993607802.cif
正在转换auid-209feebc27d78b35.cif
正在转换auid-20e5d11edfa5528b.cif
正在转换auid-20e7700f7939e2b5.cif
正在转换auid-212245422991715d.cif
正在转换auid-21b1d680ae048f79.cif
正在转换auid-223943b2e007bd71.cif
正在转换auid-23032fd4b02409aa.cif
正在转换auid-25870373c5ea966d.cif
正在转换auid-27841a54646050e1.cif
正在转换auid-27d89ed6b0b8d634.cif
正在转换auid-289f6a437bc16260.cif
正在转换auid-296417bd6f946fd2.cif
正在转换auid-2a2cde41e65d0333.cif
正在转换auid-2a6adcb0ef60b1b2.cif
正在转换auid-2a89a54a74c61f2e.cif
正在转换auid-2af434d546e7d7f5.cif
正在转换auid-2b847325538ebcd8.cif
正在转换auid-2d04165867e5a38a.cif
正在转换auid-2d7e31dba7893acf.cif
正在转换auid-2dfdeffebf0f4854.cif
正在转换auid-2e3f5a18d06898ab.cif
正在转换auid-2e772bf1901fde34.cif
正在转换auid-2e9ac76c05cc9b03.cif
正在转换auid-2ef16e45c94ce36b.cif
正在转换auid-2fd50172ffe30812.cif
正在转换auid-3025d840e8963087.cif
正在转换auid-32084079d9665883.cif
正在转换auid-32f3e913f70a63c8.cif
正在转换auid-3311d66fe496bc45.cif
正在转换auid-33854643c118bfdc.cif
正在转换auid-33d183b243a407c8.cif
正在转换auid-33d8eec5e318fdf0.cif
正在转换auid-33ea8065d4d66edf.cif
正在转换auid-33f0af7c21c8ae75.cif
正在转换auid-34e2cabbbb58196e.cif
正在转换auid-34f31ffb6b6f4b14.cif
正在转换auid-36c5053dd0b0ddc8.cif
正在转换auid-373c2d0722527cb3.cif
正在转换auid-37433e18a7e9e963.cif
正在转换auid-379486ae17dc8c60.cif
正在转换auid-37e90aff5105cf35.cif
正在转换auid-392cc047a4a3f48f.cif
正在转换auid-397c918daee41899.cif
正在转换auid-3a5a39eb041b3633.cif
正在转换auid-3a762df724b81c05.cif
正在转换auid-3bc14ffab2a64512.cif
正在转换auid-3c68d29fb91f9307.cif
正在转换auid-3cfcb163239d41c8.cif
正在转换auid-3d44e856a80f2fb6.cif
正在转换auid-3df2e355d0f34354.cif
正在转换auid-3e84976870b56b42.cif
正在转换auid-41a7b22a0b3ed920.cif
正在转换auid-426828f03e48beba.cif
正在转换auid-42c7b1b98e381d9c.cif
正在转换auid-4339b06993fdd168.cif
正在转换auid-43c0e0e329deae86.cif
正在转换auid-4428df25bbb71826.cif
正在转换auid-453de17e36c1e2d9.cif
正在转换auid-45b81e23c3728234.cif
正在转换auid-465f3cc78a9db842.cif
正在转换auid-46b56999cf573636.cif
正在转换auid-46f1a3576ed4d8aa.cif
正在转换auid-4717099722c34962.cif
正在转换auid-486ef1a80347c0e0.cif
正在转换auid-4931662fdeccf1c3.cif
正在转换auid-49dc742d3438c080.cif
正在转换auid-4b000ed14c60a222.cif
正在转换auid-4c48352dc4971fe9.cif
正在转换auid-4c686dc3085415cc.cif
正在转换auid-4d36f4f09ace7ce4.cif
正在转换auid-4e09946f50a04b36.cif
正在转换auid-4e26aa8efe06fc11.cif
正在转换auid-4e2cea9aaa6f9f00.cif
正在转换auid-5068f5f28f2134a5.cif
正在转换auid-5085e5b57106cd4a.cif
正在转换auid-518363230491e21d.cif
正在转换auid-523d5fa88e04fecb.cif
正在转换auid-5268cbfec8eccd0f.cif
正在转换auid-52d954eb4e77a2e1.cif
正在转换auid-548699a2c3bd8934.cif
正在转换auid-54ee2b03d728789b.cif
正在转换auid-5552502917e4be75.cif
正在转换auid-5570981b555cc1ca.cif
正在转换auid-5581cdfb1757373f.cif
正在转换auid-55e03f8bad7e2316.cif
正在转换auid-56b3f3916a33ed97.cif
正在转换auid-578728533ce2b927.cif
正在转换auid-57eb370e018e4510.cif
正在转换auid-58d465b0d127a7e9.cif
正在转换auid-5a476dd63c4cf6d6.cif
正在转换auid-5b1b330df213c306.cif
正在转换auid-5df65c2b3c021c4f.cif
正在转换auid-5e4a8c875abac6f7.cif
正在转换auid-5f6e75dc54ebe038.cif
正在转换auid-5f7769f0561f00f6.cif
正在转换auid-608cae250d900bf9.cif
正在转换auid-60dc1241000ea502.cif
正在转换auid-60e9413f64b2b266.cif
正在转换auid-6180d7d0483a2018.cif
正在转换auid-6210d9f0ea646316.cif
正在转换auid-6329b990643f5f1b.cif
正在转换auid-6370acc5037d47d5.cif
正在转换auid-637bafd5d44d0fac.cif
正在转换auid-64d9c676f20c4637.cif
正在转换auid-657ce95c08073451.cif
正在转换auid-659b981b28f4fbc5.cif
正在转换auid-66c8e33bf484ef69.cif
正在转换auid-6711a46df1bf8c71.cif
正在转换auid-6759e12ee37c0590.cif
正在转换auid-685879afd894efab.cif
正在转换auid-68a867946ad933af.cif
正在转换auid-694d4f70fdd9f38f.cif
正在转换auid-69c57f31652eaf6e.cif
正在转换auid-6aa6bc2892827f08.cif
正在转换auid-6aae7264c06979cb.cif
正在转换auid-6bc60d2f7f9f216e.cif
正在转换auid-6bcf1d94592064cc.cif
正在转换auid-6c35929a62c3fd66.cif
正在转换auid-6cab801730fc837c.cif
正在转换auid-6dcf0d7409f591bb.cif
正在转换auid-6f0ba199008ce5e0.cif
正在转换auid-7099888fd361d1ed.cif
正在转换auid-70b9dd077b8560cc.cif
正在转换auid-72194c836641debf.cif
正在转换auid-72b7f55954d261da.cif
正在转换auid-72c2c85d5b688e5f.cif
正在转换auid-73c98af845096acf.cif
正在转换auid-7402aa5316251bf9.cif
正在转换auid-741277f4cc2b0e3a.cif
正在转换auid-7451d6290fc8a28d.cif
正在转换auid-746c75606e13cca5.cif
正在转换auid-74be83330c3b3fbb.cif
正在转换auid-770cee53438e232e.cif
正在转换auid-778eff3a8c8655a1.cif
正在转换auid-78266f2b283ed01f.cif
正在转换auid-78f6d119fcd26dc0.cif
正在转换auid-7905469cb38593be.cif
正在转换auid-794fa54d0f9d1255.cif
正在转换auid-7951dece890dd1a3.cif
正在转换auid-7aa8c1800d3a4bc7.cif
正在转换auid-7ab262ae3f0458a0.cif
正在转换auid-7b0106b78d1d2613.cif
正在转换auid-7b4bfd006a0814e1.cif
正在转换auid-7bc6bd705726b0d5.cif
正在转换auid-7c6f767b5d02e213.cif
正在转换auid-7cf1f62c78dda1b0.cif
正在转换auid-7d8ce61461a6bbdd.cif
正在转换auid-7e23a5f602a7d248.cif
正在转换auid-7f46a5a72d91f098.cif
正在转换auid-7fc5371dc7a8ca36.cif
正在转换auid-801ca2ccd430da4a.cif
正在转换auid-801e56a3bb9c4ade.cif
正在转换auid-8020909c4763ce15.cif
正在转换auid-809699469465a67d.cif
正在转换auid-825b9f8e313cbc42.cif
正在转换auid-82ebe85e934f1eb6.cif
正在转换auid-831a3285c5c85a7b.cif
正在转换auid-844de44f2df33e2c.cif
正在转换auid-84844a5ea8ec2d82.cif
正在转换auid-848e051a9af0b42d.cif
正在转换auid-84e65354583848ef.cif
正在转换auid-84e7c2e4e70bbb9d.cif
正在转换auid-8512a992df7a2a07.cif
正在转换auid-857784642c02c567.cif
正在转换auid-85b1b81f357198ac.cif
正在转换auid-86fa19b2ab96ebee.cif
正在转换auid-884ea902b2c4e91d.cif
正在转换auid-88a2839b802aab98.cif
正在转换auid-8a519d8278da4082.cif
正在转换auid-8aabc11d03ef0d5b.cif
正在转换auid-8b786e528cb59131.cif
正在转换auid-8d68ef14766e35f0.cif
正在转换auid-8d7e33486a1d5dcf.cif
正在转换auid-8e8bb2326c86a400.cif
正在转换auid-8f5f7a7766e9c9bb.cif
正在转换auid-8fa0a817263bab69.cif
正在转换auid-8fc91acbae6ce6a2.cif
正在转换auid-8fd28030fe186dcb.cif
正在转换auid-9063f4b918d3e141.cif
正在转换auid-9153a09e597f3111.cif
正在转换auid-918d098fe76e8aac.cif
正在转换auid-922e8d6de2e8f744.cif
正在转换auid-92ebdb28e1c2ca14.cif
正在转换auid-92fe670d45be0055.cif
正在转换auid-9306439554daa177.cif
正在转换auid-9377f3e9879b7a61.cif
正在转换auid-9410d0e6ecfaccea.cif
正在转换auid-944d16b260b373cc.cif
正在转换auid-9623411f2bb8a181.cif
正在转换auid-96f0b26bffffdf02.cif

正在转换auid-973746f8f52902e2.cif
正在转换auid-9846535191c38f8d.cif
正在转换auid-9926da0d2aaadfef.cif
正在转换auid-99d1a155b6fd881a.cif
正在转换auid-99fee4f76b3d45b6.cif
正在转换auid-9a23031bd0cfca43.cif
正在转换auid-9b3ff576faa0aade.cif
正在转换auid-9b48c45532ea20cc.cif
正在转换auid-9c78a8549ac597de.cif
正在转换auid-9cb8e0ef56419d1b.cif
正在转换auid-9cd29fbad6d96a44.cif
正在转换auid-9d1732f4bbe2b39e.cif
正在转换auid-9d21ff88f120f4c7.cif
正在转换auid-9d3516a347958c90.cif
正在转换auid-9d6fbc8cf755fdb3.cif
正在转换auid-9dcee62643a808ed.cif
正在转换auid-9e22ed0d5718f0d4.cif
正在转换auid-9eaa0d4dcda2a8d7.cif
正在转换auid-9ed4d0f7bc9eac0e.cif
正在转换auid-9f99751379845698.cif
正在转换auid-9fec3da8e6b84ecf.cif
正在转换auid-9ff8d426baa79275.cif
正在转换auid-a0e9cf2478809681.cif
正在转换auid-a4a24f1a3d75b38a.cif
正在转换auid-a4e7b9a18f6ba858.cif
正在转换auid-a4f77ea9d7585916.cif
正在转换auid-a4fed8cb653b90e2.cif
正在转换auid-a4ffaa7b74ac48f0.cif
正在转换auid-a6399d3dcebb2fa0.cif
正在转换auid-a64f0ef682311ad6.cif
正在转换auid-a69f8050a7d11eda.cif
正在转换auid-a70e750727f474fe.cif
正在转换auid-a85355d0d6d994ff.cif
正在转换auid-a856c9c029db47e1.cif
正在转换auid-aaca0476fb874696.cif
正在转换auid-ab4ad59ce2929782.cif
正在转换auid-ab922961e97e0912.cif
正在转换auid-ac4760bf880620d4.cif
正在转换auid-ac7531f37d2af61b.cif
正在转换auid-ad71f90705459162.cif
正在转换auid-adadacf71ba7f0b2.cif
正在转换auid-ae746e0bcc8a60d1.cif
正在转换auid-aed2e596151af3ab.cif
正在转换auid-af2abc1846cd7452.cif
正在转换auid-af5619d5440431e3.cif
正在转换auid-af7578f8f021858c.cif
正在转换auid-afadf13943ddde16.cif
正在转换auid-b03c25879d93615e.cif
正在转换auid-b049e0663b783e58.cif
正在转换auid-b0c79b63ac73f10a.cif
正在转换auid-b0e433b1723df5b9.cif
正在转换auid-b1c3f2fc052163af.cif
正在转换auid-b1f86ef8c524034f.cif
正在转换auid-b22b5cf8c5a3f0ec.cif
正在转换auid-b236adc09c8a551c.cif
正在转换auid-b269ba41129c9a80.cif
正在转换auid-b2a1966e556a8bff.cif
正在转换auid-b2f227e2eeaba3cb.cif
正在转换auid-b38d236b08251bcf.cif
正在转换auid-b41388938f96a594.cif
正在转换auid-b4966c84f77259a8.cif
正在转换auid-b5b7eb5679095d00.cif
正在转换auid-b5f50904aa50d6c8.cif
正在转换auid-b647f0fc79727927.cif
正在转换auid-b6778659ecdec799.cif
正在转换auid-b710897a18553a27.cif
正在转换auid-b79abbd8d52ac7a8.cif
正在转换auid-b828a5549f0e2d1e.cif
正在转换auid-b8926fa64a23be37.cif
正在转换auid-b892a188371bdd17.cif
正在转换auid-b8bd3fd56d95b0de.cif
正在转换auid-b97cb2623d85479f.cif
正在转换auid-ba418252b9509204.cif
正在转换auid-ba5b396699e9c415.cif
正在转换auid-bacd2a03102e8021.cif
正在转换auid-bad997d4ee5fb5a6.cif
正在转换auid-bbb7280973a80167.cif
正在转换auid-bc0e94b7ab813016.cif
正在转换auid-bc1523b2961eb527.cif
正在转换auid-bc2c83c21b1677f0.cif
正在转换auid-bc581276a7868395.cif
正在转换auid-bd2452a7fded3dd7.cif
正在转换auid-bd6712b7e493e95f.cif
正在转换auid-bd7d26772f465c42.cif
正在转换auid-c033b4af1f573169.cif
正在转换auid-c12ca7105d6b3cdd.cif
正在转换auid-c1c41c21cbdada00.cif
正在转换auid-c1df752f636ca45f.cif
正在转换auid-c337548f7bfdcbbb.cif
正在转换auid-c3b4924dfa106d2a.cif
正在转换auid-c458ebfd30fd84d4.cif
正在转换auid-c495cdc080e04ab1.cif
正在转换auid-c4a9e2161a2f11e3.cif
正在转换auid-c4eee22da6bbbe34.cif
正在转换auid-c5e8b70ad3d19c2e.cif
正在转换auid-c6044de52a9d0597.cif
正在转换auid-c60f5e4c484c103f.cif
正在转换auid-c6242b799c3a01aa.cif
正在转换auid-c681dc3da92332a1.cif
正在转换auid-c7282e6db43ec794.cif
正在转换auid-c757f8da9e6a372a.cif
正在转换auid-c7f5d5a05b544106.cif
正在转换auid-c87de3c22c9ed4fd.cif
正在转换auid-c8a2795454d1cd08.cif
正在转换auid-c8bfa8f9f692c802.cif
正在转换auid-c964a40cac1504e3.cif
正在转换auid-c9aa5699cb5f516f.cif
正在转换auid-c9bbb40a314d3e44.cif
正在转换auid-c9ed35c309640616.cif
正在转换auid-ca01bd40862262fe.cif
正在转换auid-cbefa0298c62966d.cif
正在转换auid-cd79f440b26e762e.cif
正在转换auid-cdeac7e9e52f9d55.cif
正在转换auid-ce354e671169f624.cif
正在转换auid-cec5a7f0a93b45ff.cif
正在转换auid-cecfadba4f6f4bf7.cif
正在转换auid-cf2bc3cf26cc2576.cif
正在转换auid-cf59bba913f7bd9b.cif
正在转换auid-cf878db6974d4390.cif
正在转换auid-cfebb2b09182726b.cif
正在转换auid-d00db27d263014e2.cif
正在转换auid-d2028482c39ca2ee.cif
正在转换auid-d2136f9d93cb6b7d.cif
正在转换auid-d260d32db1f3566b.cif
正在转换auid-d365b526c6c7f965.cif
正在转换auid-d3a79dc7bf86f0e1.cif
正在转换auid-d3d245ab46e072bb.cif
正在转换auid-d40747690d2db433.cif
正在转换auid-d40e2e30abf46513.cif
正在转换auid-d4c2e5c73b007d4c.cif
正在转换auid-d5953a20c73ab532.cif
正在转换auid-d5dc1fa11190e8c7.cif
正在转换auid-d5dd62b9a825abd7.cif
正在转换auid-d6236cacdbf1fc29.cif
正在转换auid-d64f2480f6b4bf60.cif
正在转换auid-d67a98efc7985b9e.cif
正在转换auid-d6e7683d4f067634.cif
正在转换auid-d825bfbc623c2ecc.cif
正在转换auid-d9cb3cc777d38960.cif
正在转换auid-da1b0fab8a3c0b1c.cif
正在转换auid-dab27d17250b4100.cif
正在转换auid-db0fb6769a82ceb1.cif
正在转换auid-db1c01c0ae57a7dd.cif
正在转换auid-db3690db121cd871.cif
正在转换auid-dc0b7d5e321f3fa0.cif
正在转换auid-dd1786a3c6ca5a9b.cif
正在转换auid-dd6f97510ce9e84d.cif
正在转换auid-dea0cc4e2ca59aeb.cif
正在转换auid-dea39103b76c8009.cif
正在转换auid-df4ecf643e17d857.cif
正在转换auid-df7fbbecf0585f76.cif
正在转换auid-e056cc527fcd1451.cif
正在转换auid-e0b4b76611ddea28.cif
正在转换auid-e49cc9027c0f3e09.cif
正在转换auid-e59e5a31eec3585e.cif
正在转换auid-e682b45f81eb56e6.cif
正在转换auid-e68590fe82102f77.cif
正在转换auid-e6c74b5a48108a82.cif
正在转换auid-e6c963a0bd61b876.cif
正在转换auid-e855d53d38a04e3d.cif
正在转换auid-e993703d919f5e78.cif
正在转换auid-e9bb33177343d1d5.cif
正在转换auid-ea6516e2d54c7bef.cif
正在转换auid-ea7454f3320905ee.cif
正在转换auid-eabc7fd98bae68d7.cif
正在转换auid-eac85b5d29654fce.cif
正在转换auid-eaf75b35e437167b.cif
正在转换auid-eb1232ef6fa33bab.cif
正在转换auid-ebb63856d9d099f4.cif
正在转换auid-ec6dc8f8df88a634.cif
正在转换auid-eca869388c8c5229.cif
正在转换auid-ecc487c54cbdd774.cif
正在转换auid-ecce932514b09cf3.cif
正在转换auid-ed0702a0d651cdb0.cif
正在转换auid-ed09029c34a6e00b.cif
正在转换auid-ed269682b37cfbc4.cif
正在转换auid-ed2f6ac827fd7abb.cif
正在转换auid-eda32299651ffef0.cif
正在转换auid-ee5ee7c8886bb8c9.cif
正在转换auid-efcfe9a499279588.cif
正在转换auid-f030a6fffe4dcd36.cif
正在转换auid-f170c647f9925932.cif
正在转换auid-f1e14ccec2df5a45.cif
正在转换auid-f21771d6722bccd5.cif
正在转换auid-f2cfc09c92edfafa.cif
正在转换auid-f3ed00c022ba9010.cif
正在转换auid-f51c155269bff6c6.cif
正在转换auid-f5f80b17d9dadc81.cif
正在转换auid-f83928ac33d2abf9.cif
正在转换auid-f8ff392074a6b5a9.cif
正在转换auid-f9067ba147859887.cif
正在转换auid-f922124353e32a3c.cif
正在转换auid-f99c06fd20399d0e.cif
正在转换auid-f9f56060ee69ea87.cif
正在转换auid-fa03fbb5d2dd2cfa.cif
正在转换auid-fb6211f348b722c9.cif
正在转换auid-fc7436dc8a119705.cif
正在转换auid-fcc41599429b40f2.cif
正在转换auid-fd56dbf811ff57bb.cif
正在转换auid-fe314c743578cd6e.cif
正在转换auid-fe8c2e3d8f922f08.cif
正在转换auid-ff3f4f79259e86c5.cif
正在转换auid-31b1d88dce00a03e.cif
正在转换auid-00d76a48b27296e1.cif
正在转换auid-013762125986d977.cif
正在转换auid-02d5b518f5b2f5de.cif
正在转换auid-02fa07e52818999d.cif
正在转换auid-03733513c120e840.cif
正在转换auid-0420a5614022931a.cif
正在转换auid-043153396469e8b4.cif
正在转换auid-045956e7cb930d24.cif
正在转换auid-04871b0003e858ba.cif
正在转换auid-04b86edbb759a07d.cif
正在转换auid-07044cf44063ef12.cif
正在转换auid-0739787fb1a830ea.cif
正在转换auid-076e9461aaa77c3a.cif
正在转换auid-07bea73cc9a15e73.cif
正在转换auid-0a90a72a25d05f33.cif
正在转换auid-0ad0145dda527705.cif
正在转换auid-0b5abc88696ea61d.cif
正在转换auid-0df86205a6b7ddc7.cif
正在转换auid-0ebb3e18eec63d82.cif
正在转换auid-0efcfd8bf898e3e6.cif
正在转换auid-0f65660c36816601.cif
正在转换auid-0f6868f27399548f.cif
正在转换auid-0f90b4967f524f85.cif
正在转换auid-10d81f3ede98c67e.cif
正在转换auid-1189f3072ee7101a.cif
正在转换auid-12a5c539a0962028.cif
正在转换auid-12f4b0d584b03ed1.cif
正在转换auid-1491319eaeb96494.cif
正在转换auid-1812393ede8a7a8a.cif
正在转换auid-1953af8de44ea7aa.cif
正在转换auid-19573e131d0ff94b.cif
正在转换auid-1c8c2a849560a1d4.cif
正在转换auid-1cb6e17834df46b1.cif
正在转换auid-1d397e7103760709.cif
正在转换auid-1e0c059fa9524559.cif
正在转换auid-1e1e9274d59f6d97.cif
正在转换auid-1e5b972a08db5a29.cif
正在转换auid-1e7aeab40e9a4aa0.cif
正在转换auid-1ea6f5b0b6d41230.cif
正在转换auid-20690b3a5f48622a.cif
正在转换auid-21823a02663ce3c7.cif
正在转换auid-22ff7dd99b62fec8.cif
正在转换auid-250f71b89bbe88e5.cif
正在转换auid-26652009ee90bd98.cif
正在转换auid-26c250428210ea38.cif
正在转换auid-26cc9792b1ac9ce2.cif
正在转换auid-26d488b3b023778d.cif
正在转换auid-26db70c77edc0fee.cif
正在转换auid-27b4c1d7c84e5086.cif
正在转换auid-287f982e8c7fdc7f.cif
正在转换auid-2975a83611622fdc.cif
正在转换auid-2aa001cbc41cda87.cif
正在转换auid-2c2cfbd854d27e27.cif
正在转换auid-2d1366ac71e7584a.cif
正在转换auid-2e70d44ee4e6bdab.cif
正在转换auid-2e9adb812a78ead2.cif
正在转换auid-2f0fe23f8e686ac0.cif
正在转换auid-2f95056fc23fa81b.cif
正在转换auid-2fcc562e4ed95e9a.cif
正在转换auid-30157a8e933a4b2a.cif
正在转换auid-31468b388668f147.cif
正在转换auid-32c8afe5c6bf44f1.cif
正在转换auid-33d07bfaf2ac8801.cif
正在转换auid-350ae8dfec04fdfc.cif
正在转换auid-350d63eebe48eb43.cif
正在转换auid-35d6258e4cd2ecd5.cif
正在转换auid-3a4483637d354d99.cif
正在转换auid-3a7f9682d496d3d0.cif
正在转换auid-3acb721dbc8c6f62.cif
正在转换auid-3bf8580f47be88d0.cif
正在转换auid-3ce9c9333a9a7f77.cif
正在转换auid-3dd7493c9eb3908c.cif
正在转换auid-3df5ad7753d5fbff.cif
正在转换auid-3e20856935b5b757.cif
正在转换auid-402a6c10db161afd.cif
正在转换auid-409d46a5db8d08f5.cif
正在转换auid-40c0334757b0f06e.cif
正在转换auid-412d4288536bd147.cif
正在转换auid-425417b37e7b30b4.cif
正在转换auid-42f4c164754a09e8.cif
正在转换auid-446f392c90093c74.cif
正在转换auid-4587b6f544439693.cif
正在转换auid-46df7dd3035f0544.cif
正在转换auid-4708fc449cf4c6e9.cif
正在转换auid-480da5575e53df58.cif
正在转换auid-484d8a349b41f984.cif
正在转换auid-489feebb85de4225.cif
正在转换auid-4902988698dc25bb.cif
正在转换auid-4a3e632b01e375e8.cif
正在转换auid-4aa9e21eb113cfae.cif
正在转换auid-4af83ee9a24a4a8b.cif
正在转换auid-4b14dd815aa65382.cif
正在转换auid-4bd79cf897330510.cif
正在转换auid-4ce0ca124721b4f7.cif
正在转换auid-4e04e212c103466d.cif
正在转换auid-4fe2a35eaf534e88.cif
正在转换auid-52aeb3faee0c0146.cif
正在转换auid-530fbbb5e9f84987.cif
正在转换auid-542ad142494c959e.cif
正在转换auid-548dab9259fc81d0.cif

正在转换auid-55998de3df747d54.cif
正在转换auid-56bf3e658f4c7138.cif
正在转换auid-57439cb891bd1c57.cif
正在转换auid-59f48bc16b45e762.cif
正在转换auid-5a7ee2b08b2ce7c9.cif
正在转换auid-5a9d493ef25f1062.cif
正在转换auid-5ab907fb2d158528.cif
正在转换auid-5c43dfea10971c6d.cif
正在转换auid-5c7220f87ea2446c.cif
正在转换auid-5d194a3a6a638566.cif
正在转换auid-5d636bcddb400277.cif
正在转换auid-5ef02e7c6cb2b80e.cif
正在转换auid-60c823991a75cb41.cif
正在转换auid-6155ab5bd2474ae1.cif
正在转换auid-6336340913ac499b.cif
正在转换auid-63c57117bdd65651.cif
正在转换auid-63cd3c8110bb3001.cif
正在转换auid-63f5dfc983050aaf.cif
正在转换auid-64d105df3cf12b8d.cif
正在转换auid-64d2fb25e9b19f08.cif
正在转换auid-65dacc022be27848.cif
正在转换auid-66895ba56daaf0ff.cif
正在转换auid-66e52890ab680009.cif
正在转换auid-68065a29867eb92a.cif
正在转换auid-69146f88f7f7ee27.cif
正在转换auid-6923851e1d2213f8.cif
正在转换auid-69312751e66e6dec.cif
正在转换auid-695f5f4110250a9e.cif
正在转换auid-6969fd2945fc4385.cif
正在转换auid-6aad611fca1daa07.cif
正在转换auid-6b5ebdcba266fda4.cif
正在转换auid-6be865614e24ebae.cif
正在转换auid-6e2dbdbf373b78e2.cif
正在转换auid-6e52ca088dd01dcc.cif
正在转换auid-6e780c05c3bb4f30.cif
正在转换auid-6ee297eb08ef1f61.cif
正在转换auid-71001dcfb0ffd23a.cif
正在转换auid-7145b94b82a6ec73.cif
正在转换auid-71b397a113254945.cif
正在转换auid-727b2687f4b2ad6c.cif
正在转换auid-72adbf8e1d9254f9.cif
正在转换auid-72bdb248b9f05f3b.cif
正在转换auid-72c481fac017e032.cif
正在转换auid-7375dcd9331fbda2.cif
正在转换auid-75316ed73052be97.cif
正在转换auid-758d5d8a646c185c.cif
正在转换auid-75b338f1e3230e83.cif
正在转换auid-75ddcad8c09f2561.cif
正在转换auid-775164721c95e627.cif
正在转换auid-787c6b57e40ea50f.cif
正在转换auid-7a037adb6ab2c284.cif
正在转换auid-7a105a9d9fbafef6.cif
正在转换auid-7a11bc962464294f.cif
正在转换auid-7b67d6f383435a9f.cif
正在转换auid-7b79f4751370597b.cif
正在转换auid-7d550c109dbc97e7.cif
正在转换auid-7e6a33a9a027d7cd.cif
正在转换auid-7e7fb227b8e9b896.cif
正在转换auid-7f4b939b45ed4664.cif
正在转换auid-7fa0556f39ec1abc.cif
正在转换auid-815b5ab9441a5057.cif
正在转换auid-819a4e44b226e198.cif
正在转换auid-81fbc188081e7131.cif
正在转换auid-83087ab6243df552.cif
正在转换auid-84bb231f71ca7526.cif
正在转换auid-8593ef6b3be9ded7.cif
正在转换auid-876ed8ce9d8e44c9.cif
正在转换auid-87c1a056cc0bd704.cif
正在转换auid-888d196103d4ba6f.cif
正在转换auid-888e933cd00a2e22.cif
正在转换auid-88e457b1a9267668.cif
正在转换auid-890bf6c5b750d467.cif
正在转换auid-8a9917824417fd38.cif
正在转换auid-8b0e1d32b54ef04a.cif
正在转换auid-8c406a0129498b5f.cif
正在转换auid-8cd5be6c5da50960.cif
正在转换auid-8dd97c071d6484fd.cif
正在转换auid-8e728cd79c152119.cif
正在转换auid-8fae6611fcbd5a28.cif
正在转换auid-91d3ffc03189952f.cif
正在转换auid-93bea71ef54c1f40.cif
正在转换auid-959c74f12f7cd735.cif
正在转换auid-96e5044b928be27c.cif
正在转换auid-973251c683150d15.cif
正在转换auid-98cabe97941c907b.cif
正在转换auid-98df7460cc6b8283.cif
正在转换auid-99a9e16461551fff.cif
正在转换auid-9abeff692a01696c.cif
正在转换auid-9ac60379a71ef868.cif
正在转换auid-9babc10f79062b0f.cif
正在转换auid-a09f77602b8f9326.cif
正在转换auid-a0eed8ed81c0d688.cif
正在转换auid-a33552384f61d310.cif
正在转换auid-a33ac588d0f0f011.cif
正在转换auid-a3645c3869bdc349.cif
正在转换auid-a39f70ff4d97e4ac.cif
正在转换auid-a4bdf4cfcda6a912.cif
正在转换auid-a5cbbcec1c74e417.cif
正在转换auid-a61af583dad5eb1c.cif
正在转换auid-a6c2d5e563e47f6a.cif
正在转换auid-a7877052163c8e31.cif
正在转换auid-a808108b71e67c1e.cif
正在转换auid-a8e07fe0b8317d1b.cif
正在转换auid-a94113f7bad111da.cif
正在转换auid-a98e9094c4738ff0.cif
正在转换auid-ab49786c0ae93d76.cif
正在转换auid-ad756743dc4c86e6.cif
正在转换auid-aedd787f70e78615.cif
正在转换auid-b0b89b5e75697cc5.cif
正在转换auid-b1c8b5ac95aad410.cif
正在转换auid-b2f6e46530495ffe.cif
正在转换auid-b6237a8d04367f87.cif
正在转换auid-b681892bb8d22586.cif
正在转换auid-b712db6237e6876e.cif
正在转换auid-b7556e9f10434b7c.cif
正在转换auid-b853a6245a88475e.cif
正在转换auid-b8ca63674a6e1b54.cif
正在转换auid-b8f082ea159bed40.cif
正在转换auid-bb5152f00827cbbb.cif
正在转换auid-bb88c9266f6ae49a.cif
正在转换auid-bc99b30edaab9a69.cif
正在转换auid-bcad7874eca088ae.cif
正在转换auid-bcf06e7aa0404d9c.cif
正在转换auid-bd298f46fe4b750b.cif
正在转换auid-be4461ec866ef4c9.cif
正在转换auid-bf2656345ac06158.cif
正在转换auid-c01ee436b6f8fd76.cif
正在转换auid-c0621e70926204dd.cif
正在转换auid-c10c4151528785a9.cif
正在转换auid-c1336ce6e376472d.cif
正在转换auid-c2d2b5c100ca1d2d.cif
正在转换auid-c31d81d4b97100d8.cif
正在转换auid-c639923082edc26a.cif
正在转换auid-c8732c0c6570f32c.cif
正在转换auid-c9451b7e08b5c71a.cif
正在转换auid-ca3213489493f96f.cif
正在转换auid-cb11ed1258d61b58.cif
正在转换auid-cb9845514dc6063f.cif
正在转换auid-cbf292a6e17933e3.cif
正在转换auid-cc5cf004e141b516.cif
正在转换auid-ccee75b0c0fc075b.cif
正在转换auid-cd5ac2c13947feb5.cif
正在转换auid-cedde7c9f4049fa1.cif
正在转换auid-cfa4733f61944ca4.cif
正在转换auid-d0713a35a717bcf3.cif
正在转换auid-d182e8a81295af05.cif
正在转换auid-d3224995f7e14977.cif
正在转换auid-d4d266a17613cf96.cif
正在转换auid-d603511e52aba1ad.cif
正在转换auid-d6498364163ee3de.cif
正在转换auid-d76f9b3c4e78b228.cif
正在转换auid-d79fc5c2a1beba38.cif
正在转换auid-d7d3b3733b07a757.cif
正在转换auid-d7ebcc97f59b46ea.cif
正在转换auid-d9bf6341116b9e2d.cif
正在转换auid-d9cf01076eb782ee.cif
正在转换auid-d9e973cb4b99ca9b.cif
正在转换auid-da0e19c21024be1e.cif
正在转换auid-dadb7dccb4a80fbe.cif
正在转换auid-df7b1f931c91c67c.cif
正在转换auid-df840653fc1195a4.cif
正在转换auid-e05ab56860bbd238.cif
正在转换auid-e08e7c1c6bf0cad2.cif
正在转换auid-e3e9f63ccc818b59.cif
正在转换auid-e47609a0512e4c54.cif
正在转换auid-e49ba41c6982d9cc.cif
正在转换auid-e4c464a767555a5b.cif
正在转换auid-e539f86ce6b1d433.cif
正在转换auid-e58fe480d7188c3c.cif
正在转换auid-e5c309d4737f2233.cif
正在转换auid-e69c4c137a643ff1.cif
正在转换auid-e71088653f297c07.cif
正在转换auid-e7802f996f11e7cf.cif
正在转换auid-e804243d10857c7d.cif
正在转换auid-e82e380ce4c3e311.cif
正在转换auid-e84d4186f7bd6ca6.cif
正在转换auid-e8a26d73eeb48375.cif
正在转换auid-e8bc55a8e993bf7e.cif
正在转换auid-e97260c1e57f43ed.cif
正在转换auid-e9d946b9be8e6fee.cif
正在转换auid-e9e9092370d2c744.cif
正在转换auid-eb940c414f4441f8.cif
正在转换auid-ee1a28b43cade327.cif
正在转换auid-ee47accd0e310b5f.cif
正在转换auid-ef3ba73d97fc6570.cif
正在转换auid-efb1e6db1675b128.cif
正在转换auid-f1b68ffcc83ace09.cif
正在转换auid-f270c3131c6decf1.cif
正在转换auid-f2a3e6318ec64d74.cif
正在转换auid-f2c27bbd903046b8.cif
正在转换auid-f3a9eb342e7150ea.cif
正在转换auid-f4e1b40b468f6107.cif
正在转换auid-f5f2333a09a8ce6d.cif
正在转换auid-f6830755671836c4.cif
正在转换auid-f695978616098181.cif
正在转换auid-f82533a14925bd97.cif
正在转换auid-f82c9d37f67333b5.cif
正在转换auid-f9e8df5adcab1d93.cif
正在转换auid-fb9a834bda9f2cda.cif
正在转换auid-fbf3942245339d3d.cif
正在转换auid-fd08e3678fea3b2f.cif
正在转换auid-fd9228f201f525a4.cif
正在转换auid-ff1acf8da99f6f9f.cif
正在转换auid-ff94ff91ef08dfd6.cif
正在转换auid-ffabed32404750d8.cif
正在转换auid-00755a3c9eda5f53.cif
正在转换auid-0297c61e4b5a5416.cif
正在转换auid-040256309e19694f.cif
正在转换auid-0458393207dc0218.cif
正在转换auid-0459a8601ca097d0.cif
正在转换auid-067aa63b08541c70.cif
正在转换auid-0892395a9769a8d3.cif
正在转换auid-0b34a23383707614.cif
正在转换auid-0b69317839f7a850.cif
正在转换auid-0cc642d37fc003a1.cif
正在转换auid-0cd5a40bc02490b7.cif
正在转换auid-0e5d80ea20712bd3.cif
正在转换auid-113a7259558e5931.cif
正在转换auid-11a2c36177c85e88.cif
正在转换auid-11a37e6d352d424d.cif
正在转换auid-126dd9e3313330d3.cif
正在转换auid-146d3caf1397e201.cif
正在转换auid-16589d94e7b4b10e.cif
正在转换auid-16d6a042104372ef.cif
正在转换auid-17dbad642189c1ca.cif
正在转换auid-18e6f2669a99e00b.cif
正在转换auid-1a502e4fda4f3e13.cif
正在转换auid-1b596e2d95a1f8c6.cif
正在转换auid-1bf2ad0a037b7b3c.cif
正在转换auid-1e0272d1aa255e44.cif
正在转换auid-1e03cb7978cef9ba.cif
正在转换auid-1e44c6338066fd59.cif
正在转换auid-1eca31920e465755.cif
正在转换auid-219a4a1a431fe164.cif
正在转换auid-21c29c5fb1d5422f.cif
正在转换auid-21f4d6cad2dc536c.cif
正在转换auid-22fdf462748776cd.cif
正在转换auid-27bd2989b5a4b4bf.cif
正在转换auid-28863ea29181e74f.cif
正在转换auid-28ec8432fa49203c.cif
正在转换auid-2a2f0c36e5abb8df.cif
正在转换auid-2d46c9292f6864d2.cif
正在转换auid-2db864f4f041976c.cif
正在转换auid-2dc5a60d10be5bd8.cif
正在转换auid-2e01593ed21801a7.cif
正在转换auid-2e6aa0cf810e2cff.cif
正在转换auid-2ec00e743ef19960.cif
正在转换auid-2f6725d6ce084bdc.cif
正在转换auid-2f6a34ac65d4a749.cif
正在转换auid-31f6689eed748fcf.cif
正在转换auid-34716b84eb628e8f.cif
正在转换auid-37552e0f4244ef87.cif
正在转换auid-3c371810966c596c.cif
正在转换auid-3db64fd9afa2f3e9.cif
正在转换auid-3e99d7477c89dc30.cif
正在转换auid-3f2cac427cfb772f.cif
正在转换auid-438d6435b5489df5.cif
正在转换auid-439224902165bedf.cif
正在转换auid-43f5fee00aa0fe80.cif
正在转换auid-452857eb869cf2f1.cif
正在转换auid-455c25dfe0c528e8.cif
正在转换auid-490b4aff219ce8ce.cif
正在转换auid-496b5d0176828d5a.cif
正在转换auid-4b77ce15b528a28f.cif
正在转换auid-4cd1cce16601855d.cif
正在转换auid-4d0c316c1a5b5d9c.cif
正在转换auid-4d43c3a3551f6bc8.cif
正在转换auid-4eac6f5615c1de04.cif
正在转换auid-4f21c0bf3b6f1bc3.cif
正在转换auid-4f3781d256f053d2.cif
正在转换auid-501df0000c1f2212.cif
正在转换auid-50ee219b66cf2c00.cif
正在转换auid-53b4f63b4e0c2fdf.cif
正在转换auid-548ff3b471460c60.cif
正在转换auid-54a64e4e4fccf9ba.cif
正在转换auid-569146546c90bace.cif
正在转换auid-56c5e44fa7d70d2b.cif
正在转换auid-572393f0b47bb728.cif
正在转换auid-578a57e6b3fd0ce7.cif
正在转换auid-579a6a48e8663128.cif
正在转换auid-584e5b7bae76272e.cif
正在转换auid-5db8e20d6ae4f13d.cif
正在转换auid-5e0965417d998125.cif
正在转换auid-5ec3f41de2a9d380.cif
正在转换auid-5efa82dc60bb798d.cif
正在转换auid-607ea69e3b0051ea.cif
正在转换auid-60ad59a6e54a763d.cif
正在转换auid-613b04043042909d.cif
正在转换auid-617a49b88393cb28.cif
正在转换auid-624604d0e4b04c1e.cif
正在转换auid-62afc00159530627.cif
正在转换auid-65f85c1d4f612ea2.cif
正在转换auid-669d9ec32b07b2b2.cif
正在转换auid-670ccc7b116aef22.cif

正在转换auid-67b7741206c85adc.cif
正在转换auid-67e67d5e8577cae0.cif
正在转换auid-6838dec738f6ce0e.cif
正在转换auid-68a25cb6c6a30928.cif
正在转换auid-68ad59b46f1e5f67.cif
正在转换auid-68ec838ec4bb8862.cif
正在转换auid-6ba23d56c1cccaa1.cif
正在转换auid-6c5d8799828b0e3a.cif
正在转换auid-6e2679d0561ff461.cif
正在转换auid-6fe575e2053b5138.cif
正在转换auid-715f4cf9eb4580f7.cif
正在转换auid-731809eaf8aaa362.cif
正在转换auid-7324eba58a218fc8.cif
正在转换auid-7451e56b44ebaeb9.cif
正在转换auid-7454ec1d77a92fb0.cif
正在转换auid-7542efd920ddf9db.cif
正在转换auid-75c72aa18f4c1251.cif
正在转换auid-75f65309f3e6f4a3.cif
正在转换auid-77159987fc05b27d.cif
正在转换auid-77f4d531a803cdb1.cif
正在转换auid-785dd60ba2509f81.cif
正在转换auid-78f5deeb4f882a3f.cif
正在转换auid-7983cac2a7c536f6.cif
正在转换auid-7a8ad6a8524a1afb.cif
正在转换auid-7e67539da6c8504a.cif
正在转换auid-7eebdcb8901afaf9.cif
正在转换auid-7fe7f024eb510215.cif
正在转换auid-81daf6bd168ad44e.cif
正在转换auid-834e172678ce6cc5.cif
正在转换auid-84fd36e9016c87b1.cif
正在转换auid-85639ad630ec6ace.cif
正在转换auid-857775e9c7a233f3.cif
正在转换auid-8612a45798b3df52.cif
正在转换auid-8684bb0b1e611cef.cif
正在转换auid-86abd6d2fbd557bb.cif
正在转换auid-86dd5bea0dc281c0.cif
正在转换auid-8837c1081b09ecd5.cif
正在转换auid-8882944e45d441dd.cif
正在转换auid-8901e590d0dd75e7.cif
正在转换auid-895a9d5b5e94dcaf.cif
正在转换auid-8d4d7d480c29f817.cif
正在转换auid-8dbd1f6f8b98734c.cif
正在转换auid-8f6a3345c668dada.cif
正在转换auid-90534260eaec01ac.cif
正在转换auid-90d1640c52b6124e.cif
正在转换auid-918ab7b32e13aec9.cif
正在转换auid-92059b3ab0120fa0.cif
正在转换auid-925577e98e6dc6e4.cif
正在转换auid-932d5435c5c47674.cif
正在转换auid-943136436cbb5143.cif
正在转换auid-974d616e8a4e9bc0.cif
正在转换auid-9bd5199fed52cfe0.cif
正在转换auid-9cdbfb7c343edb06.cif
正在转换auid-9cdf4123526be0a1.cif
正在转换auid-9ec923ee89647ccd.cif
正在转换auid-a151fbb5da01a96b.cif
正在转换auid-a1cebe351895b8a2.cif
正在转换auid-a1f53d39ae254d13.cif
正在转换auid-a48a13efd55d2416.cif
正在转换auid-a497785db028f0d6.cif
正在转换auid-a4c7b7f8ae7370ff.cif
正在转换auid-a6256a3a0288ff0d.cif
正在转换auid-a86130ca588bf4f1.cif
正在转换auid-aa63e72e3b2af5a9.cif
正在转换auid-ab1f282150ae40ec.cif
正在转换auid-abcdaa681357753d.cif
正在转换auid-ac002e1555056518.cif
正在转换auid-ad2b531066eb5430.cif
正在转换auid-ae2cc2c99887a70a.cif
正在转换auid-aeb8367166ecff49.cif
正在转换auid-af73edab0d0a650b.cif
正在转换auid-b06a31715828a992.cif
正在转换auid-b0e3adaabedc3b47.cif
正在转换auid-b25397c2304ee296.cif
正在转换auid-b2f419bb39b0a3e6.cif
正在转换auid-b3d31828c8d7e642.cif
正在转换auid-b3daa46ca2b197a2.cif
正在转换auid-b485330408c66f4c.cif
正在转换auid-b4a5dc99aa49e8da.cif
正在转换auid-b5fa0a42b1c88a1a.cif
正在转换auid-b92aca4c0d5d8c0d.cif
正在转换auid-ba18c6cbb8171e3e.cif
正在转换auid-ba44555144d98b7b.cif
正在转换auid-bddc835152c3f5dc.cif
正在转换auid-be8d3a26e56a111b.cif
正在转换auid-bfff98608e92143f.cif
正在转换auid-c441dfc73a349900.cif
正在转换auid-c71550024e2c4843.cif
正在转换auid-c821581a9d2bb43c.cif
正在转换auid-c92344f2aa6f208c.cif
正在转换auid-c9b48abccc1233de.cif
正在转换auid-cc8d452002ad05a3.cif
正在转换auid-cf372f969b7aafdd.cif
正在转换auid-d016f95c907a2e0e.cif
正在转换auid-d0479986c688bca4.cif
正在转换auid-d0fd236a1b262241.cif
正在转换auid-d3bb3e429dc56874.cif
正在转换auid-d3f1ceae204cde68.cif
正在转换auid-d47d9fea63eccf69.cif
正在转换auid-d5fc46380f20a41b.cif
正在转换auid-d7b0022cf8475e2b.cif
正在转换auid-d7bc84ddf12307cb.cif
正在转换auid-d8b6b57db28f267a.cif
正在转换auid-d942d17ae4d197e3.cif
正在转换auid-d944ca74c21d4946.cif
正在转换auid-dab1d8ec2d4d77f8.cif
正在转换auid-dbcb362d5ee15ad1.cif
正在转换auid-dd75209a66939dc6.cif
正在转换auid-ddda9a0d1d7c0f6b.cif
正在转换auid-de5a9fd8278dbb1b.cif
正在转换auid-deb1bfd5c3ad5920.cif
正在转换auid-deb1c5ab8cef144f.cif
正在转换auid-df129aa76146d006.cif
正在转换auid-e0238c89cf29c9ce.cif
正在转换auid-e08aa4d42b9b8a8c.cif
正在转换auid-e09492551407e098.cif
正在转换auid-e1967150a0852c25.cif
正在转换auid-e2764a8457b0d800.cif
正在转换auid-e32b7644d4676d54.cif
正在转换auid-e34be6380269e2c6.cif
正在转换auid-e538758f14fab274.cif
正在转换auid-e5519c476f86c4ee.cif
正在转换auid-e5991461c7ae837e.cif
正在转换auid-e5adc395f3760128.cif
正在转换auid-e639e3600bac0936.cif
正在转换auid-e66831d57485dd17.cif
正在转换auid-e770c55f606a5598.cif
正在转换auid-e806f5b2b87ef4f1.cif
正在转换auid-e8ac58da2d95a7f8.cif
正在转换auid-e94c64a5282de739.cif
正在转换auid-e97c77e71ed9d44b.cif
正在转换auid-e9961fd858545b24.cif
正在转换auid-e9f948e1508de461.cif
正在转换auid-ea45bb593776abdf.cif
正在转换auid-eb1fd0817ba3c05a.cif
正在转换auid-eb48a3d4daa14977.cif
正在转换auid-eba71156ef255a12.cif
正在转换auid-ec27475d9ed347b8.cif
正在转换auid-ecd1c4e327b1f72d.cif
正在转换auid-ed320b5290af9929.cif
正在转换auid-ed93731b7dc29131.cif
正在转换auid-ee77226bc7d9e081.cif
正在转换auid-f038e7e9ed4f9f9b.cif
正在转换auid-f2eb1a987f2f1308.cif
正在转换auid-f32ef1e56a935809.cif
正在转换auid-f37643a8bd723628.cif
正在转换auid-f3b15ac16a74cae1.cif
正在转换auid-f4e00cfd6a382a84.cif
正在转换auid-f571da22abd3a930.cif
正在转换auid-f5ef370c3286d107.cif
正在转换auid-f70a4bcfac5ec554.cif
正在转换auid-f8c068d45c67f32c.cif
正在转换auid-f8d28f792cec3977.cif
正在转换auid-f8d601dee554746c.cif
正在转换auid-f8da8094e760242a.cif
正在转换auid-fa0577a02694140d.cif
正在转换auid-fad2d292235bc2ea.cif
正在转换auid-fb026b7f51f47680.cif
正在转换auid-fe80cd7000847a64.cif
正在转换auid-ff356eeafbf48f12.cif
正在转换auid-ffac25019eb7eb9d.cif
正在转换auid-009ffbdc2904eba8.cif
正在转换auid-03cea42bd2d5388f.cif
正在转换auid-05c8a6c4100746cd.cif
正在转换auid-08a3a823d1ab341c.cif
正在转换auid-0976afd7a0e66816.cif
正在转换auid-1218d73fc2500966.cif
正在转换auid-13eb5601f5721f7c.cif
正在转换auid-14a30f1bd3a09e25.cif
正在转换auid-18db76dd3feb43f0.cif
正在转换auid-19eea082f0ef70bf.cif
正在转换auid-1cba39ab948b7fdc.cif
正在转换auid-1e67d55381b5a1e8.cif
正在转换auid-205153c111b44d92.cif
正在转换auid-26bf29b0f5c36578.cif
正在转换auid-2c5e8064a7b9276c.cif
正在转换auid-2c7b4e7780bdf7cb.cif
正在转换auid-340b35921733ada3.cif
正在转换auid-353f3bc6d4c2b008.cif
正在转换auid-37399e791134cc0a.cif
正在转换auid-3dc8c3381dfb2ebb.cif
正在转换auid-417b5024c95b1f14.cif
正在转换auid-437f7d64ed3ab2f2.cif
正在转换auid-472e0c71faba2c6d.cif
正在转换auid-53683879ae56739d.cif
正在转换auid-576ad563c3d61d9d.cif
正在转换auid-5d189e71c2112608.cif
正在转换auid-62e535190f56bbe0.cif
正在转换auid-666fc7b8ccadb643.cif
正在转换auid-790b00593523034a.cif
正在转换auid-7f0837f7c153d3f1.cif
正在转换auid-7fefa4c12756ba65.cif
正在转换auid-8317a87f57ef5faf.cif
正在转换auid-847c0ea2fe721ccd.cif
正在转换auid-8811293f8164ae26.cif
正在转换auid-8ae0780996986877.cif
正在转换auid-8d81d7088ce18e59.cif
正在转换auid-8f104064a4fd9730.cif
正在转换auid-93c0277aa281069d.cif
正在转换auid-9b7ebe364d679771.cif
正在转换auid-9ff31eb70d902ac8.cif
正在转换auid-aa5257884d8e2878.cif
正在转换auid-aa97f35118c29a72.cif
正在转换auid-aab966ddf500c14a.cif
正在转换auid-b87d8fb401771e8f.cif
正在转换auid-c90b8af0bcc0ead2.cif
正在转换auid-c980746041a437fb.cif
正在转换auid-ca4c8efeec6351cf.cif
正在转换auid-d509e2a982421d7d.cif
正在转换auid-d569604cc6ced64e.cif
正在转换auid-d7750ea1523daef1.cif
正在转换auid-dd48e14fad759389.cif
正在转换auid-deca15fe686b2905.cif
正在转换auid-e2610adc3c9f67fd.cif
正在转换auid-e2a2416893cd335c.cif
正在转换auid-ecbc6c3ca1c12c02.cif
正在转换auid-eef1932df630e191.cif
正在转换auid-f34271028a2ab401.cif
正在转换auid-fb72d0867d8761e7.cif
正在转换auid-fcd1432c93ae27ed.cif
正在转换auid-0059f0aeac8087b5.cif
正在转换auid-00d527add58c05be.cif
正在转换auid-01887fbeb40a26f1.cif
正在转换auid-01932a564573c82c.cif
正在转换auid-01d22015163dc689.cif
正在转换auid-025f21119485edd4.cif
正在转换auid-02672a172c721383.cif
正在转换auid-033f8c9ed7c38935.cif
正在转换auid-0350e25a95f54a05.cif
正在转换auid-04e7cd2bf3f8e70e.cif
正在转换auid-053d701228100fee.cif
正在转换auid-055754be62c6da12.cif
正在转换auid-0571ba2df6c01631.cif
正在转换auid-0579419b1ee988e0.cif
正在转换auid-05d57875a479409f.cif
正在转换auid-05f4a9b0e565746e.cif
正在转换auid-05f995df4d679a8f.cif
正在转换auid-069ddbd2b5c80af6.cif
正在转换auid-06a4398746572828.cif
正在转换auid-06bc4a43b3a0239a.cif
正在转换auid-06c5c5e6fc6b1131.cif
正在转换auid-06f40fa0ed319313.cif
正在转换auid-0701aa153cbd6bd3.cif
正在转换auid-07152e9b1e9e1f22.cif
正在转换auid-074a78492ec5e025.cif
正在转换auid-076eb2f8b868b145.cif
正在转换auid-08478cd98f40a08f.cif
正在转换auid-084fc87e0a92fca2.cif
正在转换auid-085beee1ba7fb48f.cif
正在转换auid-08fb3c2ce4db9b14.cif
正在转换auid-0910b0c6a51a1821.cif
正在转换auid-09c793d3d2c042f2.cif
正在转换auid-0a3f78ad40a3dec8.cif
正在转换auid-0a624dc9b5b85218.cif
正在转换auid-0ad0aa8cf5ca3d1d.cif
正在转换auid-0b0d348af663fbea.cif
正在转换auid-0b1d0956e8882c8f.cif
正在转换auid-0c9976b50f8a7762.cif
正在转换auid-0d0284a804819d9d.cif
正在转换auid-0d2ff8a3a033b5a0.cif
正在转换auid-0d78debb900545e1.cif
正在转换auid-0da395a4676323c3.cif
正在转换auid-0dc32360be2e0a91.cif
正在转换auid-0e02faac24db1ad5.cif
正在转换auid-0ecddce86f41fba9.cif
正在转换auid-0ef0b64310a08b0a.cif
正在转换auid-0ef3da4b1b5d1fd7.cif
正在转换auid-0f4ceb426e4b846c.cif
正在转换auid-0fcc50bd0c5cd5c4.cif
正在转换auid-10961e23c0ee6185.cif
正在转换auid-109a9effa502931d.cif
正在转换auid-10da53fb7105442b.cif
正在转换auid-10ea1659250aff01.cif
正在转换auid-10f40343e2c5daf1.cif
正在转换auid-10f4f6ce1afd4182.cif
正在转换auid-110776b5f8765e20.cif
正在转换auid-113a915ebfdd913a.cif

正在转换auid-11c8c39421dd862c.cif
正在转换auid-1207ff454999c0db.cif
正在转换auid-1264add5ef30e589.cif
正在转换auid-130b3ae564ddb52f.cif
正在转换auid-134bc7289b6adbb3.cif
正在转换auid-136d351765cf6708.cif
正在转换auid-1449509eed889fc3.cif
正在转换auid-14a3de9c6b3bd077.cif
正在转换auid-14b311d8e1a4bb3f.cif
正在转换auid-14c2b356ca2dcd2a.cif
正在转换auid-14f5b02751581988.cif
正在转换auid-14ff767d0d06fe57.cif
正在转换auid-16adaaa4caa8322a.cif
正在转换auid-16af07f8b1f34da4.cif
正在转换auid-16e798939e849c1b.cif
正在转换auid-16f301d8210e1e3f.cif
正在转换auid-179af6593a6099eb.cif
正在转换auid-1826f7eebcf24ad2.cif
正在转换auid-1853318547923003.cif
正在转换auid-18b014ca3e7290c8.cif
正在转换auid-1907622643b59d8c.cif
正在转换auid-1912c419a6e30a0d.cif
正在转换auid-199b1ef69d5f03aa.cif
正在转换auid-1a1ff9a8646fc9e7.cif
正在转换auid-1a6418400dea0462.cif
正在转换auid-1aa516a6fd0c2903.cif
正在转换auid-1cef85807cf4daaf.cif
正在转换auid-1cff7ca67344fe45.cif
正在转换auid-1d099b292c095fe1.cif
正在转换auid-1d4f15415472c83a.cif
正在转换auid-1e203f1bd2027a45.cif
正在转换auid-1e8030315818316b.cif
正在转换auid-1eb170feeca1e7ea.cif
正在转换auid-1eb4efc008e1d0f4.cif
正在转换auid-1ee7258c9accc6d9.cif
正在转换auid-1f611f3063511c4a.cif
正在转换auid-1fe2d821b6c38971.cif
正在转换auid-2029fd4061d7dc25.cif
正在转换auid-206f8bbcbc58e70f.cif
正在转换auid-2096523e1907a05b.cif
正在转换auid-215ea8a430289712.cif
正在转换auid-21cf641003047aad.cif
正在转换auid-22299c132abeaefd.cif
正在转换auid-225ca0716f33710d.cif
正在转换auid-22a9d6e1663bd25b.cif
正在转换auid-230f96afe8f881b2.cif
正在转换auid-2468068776d2df14.cif
正在转换auid-247f42250c6da9c3.cif
正在转换auid-24a240f9dd7318a2.cif
正在转换auid-24def82d91a3809e.cif
正在转换auid-25f75b6910ff29e2.cif
正在转换auid-2603a2d2397c7033.cif
正在转换auid-271d1a93cd40bf9a.cif
正在转换auid-2780f4a57bf3d677.cif
正在转换auid-29011af382be705a.cif
正在转换auid-2950049380294216.cif
正在转换auid-296642d2b2b7068c.cif
正在转换auid-29ad6d4803713ca5.cif
正在转换auid-2a04c9fc786c9051.cif
正在转换auid-2aaaad99e8666901.cif
正在转换auid-2ac7439d1f845379.cif
正在转换auid-2b0302d5aec2b02e.cif
正在转换auid-2b429a0ed21a7d6a.cif
正在转换auid-2bd6c9febdcf86d7.cif
正在转换auid-2c3e60e0e5791ac6.cif
正在转换auid-2cc8a403b92eb8af.cif
正在转换auid-2d4a14d6621f0acf.cif
正在转换auid-2da5d520f9ff8f90.cif
正在转换auid-2da800d7a5fd3186.cif
正在转换auid-2dd9fb50bcccfa6b.cif
正在转换auid-2e2b58d91697b055.cif
正在转换auid-2f1cd896beb43dbc.cif
正在转换auid-2f355f35e904abef.cif
正在转换auid-3054af12818023cd.cif
正在转换auid-30adddd0b8cce648.cif
正在转换auid-30f5b41d009aafd0.cif
正在转换auid-310dcbc1d7251be5.cif
正在转换auid-316fa355f90a5c12.cif
正在转换auid-3174cb5ab731eafe.cif
正在转换auid-31d4fe2875c2a912.cif
正在转换auid-31e2c26cd81e5e41.cif
正在转换auid-320aaa49881195bf.cif
正在转换auid-329255223fa6b5ab.cif
正在转换auid-32cda247e3765f4c.cif
正在转换auid-343e88192e612154.cif
正在转换auid-345bff562fa4292b.cif
正在转换auid-35666d422e8436e9.cif
正在转换auid-35a61d19a2f53b85.cif
正在转换auid-35f8aee49c9cb09e.cif
正在转换auid-36ad10b8d58fe7ea.cif
正在转换auid-374775079befc808.cif
正在转换auid-3773e6b0a9e198fe.cif
正在转换auid-3781593dc6f06301.cif
正在转换auid-37c8190339e75056.cif
正在转换auid-37f2ced252a75f5a.cif
正在转换auid-3805c2196765d4f7.cif
正在转换auid-38cf48679716474b.cif
正在转换auid-398e3031a91c6036.cif
正在转换auid-39983bd0e63cb821.cif
正在转换auid-39a76c17bb01fa96.cif
正在转换auid-39c3c6376abf03b3.cif
正在转换auid-39d556f763be11fb.cif
正在转换auid-3b7b19bb87b8f578.cif
正在转换auid-3b82b4b1b9be7f91.cif
正在转换auid-3bcbcbb1c6081652.cif
正在转换auid-3c88c9c281a5c65f.cif
正在转换auid-3cb8c6a14e39d445.cif
正在转换auid-3dcf875d48c4d6f2.cif
正在转换auid-3e71a9fa6048692f.cif
正在转换auid-3e75aa303cea0fa3.cif
正在转换auid-3f83918c8a5084a9.cif
正在转换auid-417cd51c9b402086.cif
正在转换auid-417f95d67a0c19da.cif
正在转换auid-41a3cb633cae180a.cif
正在转换auid-41f557dfe180ede9.cif
正在转换auid-422c6ae3866466f3.cif
正在转换auid-426dcde52954fcda.cif
正在转换auid-446297b786ff13e7.cif
正在转换auid-449999a7b6af0f30.cif
正在转换auid-44af0faf94de4835.cif
正在转换auid-454615463753c703.cif
正在转换auid-4593462360103ceb.cif
正在转换auid-45f7c75edc18820a.cif
正在转换auid-4606c148494f3644.cif
正在转换auid-468b9437ba31a983.cif
正在转换auid-468e1ea376efec8a.cif
正在转换auid-470af644e1473009.cif
正在转换auid-472feb00657bd64f.cif
正在转换auid-4773bd1fd7c148c9.cif
正在转换auid-47970ed21d9f538b.cif
正在转换auid-49cd0c31c6b53af0.cif
正在转换auid-4a18314040af2cdc.cif
正在转换auid-4a58fa10a13a3ec7.cif
正在转换auid-4acec750997f3e81.cif
正在转换auid-4ae6489da481f806.cif
正在转换auid-4b1efa24e6b44302.cif
正在转换auid-4b7bafa46280d08b.cif
正在转换auid-4bba3b8a6f5fedfe.cif
正在转换auid-4cd970af43fc5c56.cif
正在转换auid-4ce90c268a82a602.cif
正在转换auid-4e37faac27ba0866.cif
正在转换auid-4eb0c1fb8ed4883d.cif
正在转换auid-4fd931cfef8bdecc.cif
正在转换auid-4fdcde44772ee6ea.cif
正在转换auid-5010a82c59c1e3fa.cif
正在转换auid-507476ca2f65ec80.cif
正在转换auid-5127bb17d6e3bfc8.cif
正在转换auid-5150984e834dd3d4.cif
正在转换auid-52b0e8ab99b08e82.cif
正在转换auid-52cefbe540b79e21.cif
正在转换auid-530a7eedc0eb1f8e.cif
正在转换auid-5398f2a8bfa8c852.cif
正在转换auid-546b3eec07158134.cif
正在转换auid-551a1bfc4ea23bde.cif
正在转换auid-55300b2b8150bc4f.cif
正在转换auid-554c2295dba2e9ca.cif
正在转换auid-5566835045330e6d.cif
正在转换auid-556a4b21b948bc3e.cif
正在转换auid-55b73a532cb723a8.cif
正在转换auid-5678168dde9e7885.cif
正在转换auid-578d8cb7b1781892.cif
正在转换auid-579b603755a51f07.cif
正在转换auid-57c36f567601b183.cif
正在转换auid-589179edf9fe34e0.cif
正在转换auid-58b9c321e6f32fd3.cif
正在转换auid-58e34ace0994452f.cif
正在转换auid-5953ceb110a3e98b.cif
正在转换auid-5970d907ac371a95.cif
正在转换auid-59a0572c31c25ece.cif
正在转换auid-5a06b57104b1de0d.cif
正在转换auid-5a10934fa4ae1687.cif
正在转换auid-5a55dd7a65393fa3.cif
正在转换auid-5ab090c2e4061f95.cif
正在转换auid-5b1c1a19e68d1940.cif
正在转换auid-5b535a6263f20bdf.cif
正在转换auid-5b58c522c23fd38d.cif
正在转换auid-5b606515ab009571.cif
正在转换auid-5b7b1b03da32a2fa.cif
正在转换auid-5c0b9ee5b96d322e.cif
正在转换auid-5c5ba1c4b6489811.cif
正在转换auid-5d06db6dcfdcd77b.cif
正在转换auid-5d2410d8ad18f978.cif
正在转换auid-5d834a02ae82512a.cif
正在转换auid-5db763dad7801a95.cif
正在转换auid-5db7c9b21b935e20.cif
正在转换auid-5e7908d7a5c22b29.cif
正在转换auid-5eebe3edd2875ce8.cif
正在转换auid-5f0ed35028941f87.cif
正在转换auid-5f3b14232c244fee.cif
正在转换auid-60e9f031586c6944.cif
正在转换auid-613595bc7472257b.cif
正在转换auid-6220f7976ce7ac3b.cif
正在转换auid-6242abdd8c52895f.cif
正在转换auid-62a0c0a39739300a.cif
正在转换auid-62a5ccd58802cb56.cif
正在转换auid-62c14a66b449622f.cif
正在转换auid-630063fe5c1a5159.cif
正在转换auid-63a7003cf4d965bb.cif
正在转换auid-63b3df15ed3e1c9b.cif
正在转换auid-63f30f3ec4bb7543.cif
正在转换auid-640b7e18fe53599a.cif
正在转换auid-641a11e83816323e.cif
正在转换auid-644d4759fd74b145.cif
正在转换auid-655bad2f6ab2e83d.cif
正在转换auid-65b3ee47d717e8e0.cif
正在转换auid-6682d0cd23a847a3.cif
正在转换auid-66a5ca5a930d76fc.cif
正在转换auid-66f25c8caa6769a3.cif
正在转换auid-675e102e2940c993.cif
正在转换auid-6762a2bebb6d9f28.cif
正在转换auid-6813833bc25e4171.cif
正在转换auid-683350a2720d70ea.cif
正在转换auid-6a43a1316c7cff91.cif
正在转换auid-6aa8f46d0dad4a10.cif
正在转换auid-6af3a2eb117ea84e.cif
正在转换auid-6b25cb0256f273a4.cif
正在转换auid-6bab7a18875f6678.cif
正在转换auid-6c16f7deda47e073.cif
正在转换auid-6c3de55bf25d104d.cif
正在转换auid-6cdee7f4deef8ff9.cif
正在转换auid-6d2a8fe7055b48e3.cif
正在转换auid-6f67c7aed0f2d034.cif
正在转换auid-6f8a5c831481301f.cif
正在转换auid-6f96aed40ff551c0.cif
正在转换auid-6ff6e6a15fad23b3.cif
正在转换auid-7168e732ea4c406c.cif
正在转换auid-71a40f174ab7d2b6.cif
正在转换auid-723de6ebf21c1c47.cif
正在转换auid-7278131e2d3c4e8b.cif
正在转换auid-72e6de1c68c6dfdc.cif
正在转换auid-73e4bc0aae9b85b1.cif
正在转换auid-73ebe7e4b390c2d2.cif
正在转换auid-742541443008749d.cif
正在转换auid-742b36d992123b75.cif
正在转换auid-7469bb21e8789a67.cif
正在转换auid-74c2123742c985e4.cif
正在转换auid-7505cb6e94877d28.cif
正在转换auid-75963c994d5f914c.cif
正在转换auid-75e27831326aca67.cif
正在转换auid-762731dc887f4521.cif
正在转换auid-774d52bdf9d3b6d2.cif
正在转换auid-77c60673cbcbab41.cif
正在转换auid-77ddccf1e0b4ae93.cif
正在转换auid-780b05501c5b5352.cif
正在转换auid-7967ca417c7e02f4.cif
正在转换auid-79926d38ad962e93.cif
正在转换auid-79da49d24450706d.cif
正在转换auid-79eab585bd24be24.cif
正在转换auid-7a9e30ff1d743870.cif
正在转换auid-7c7bf7c0b3c41745.cif
正在转换auid-7ce6eb30fc8698fe.cif
正在转换auid-7dbc068b847a5126.cif
正在转换auid-7dd362a5eb2298a3.cif
正在转换auid-7e39c0cdaa3a52c6.cif
正在转换auid-7f654be3202ca093.cif
正在转换auid-7f811e94c1708cf1.cif
正在转换auid-7fc336b910576e08.cif
正在转换auid-8017f2a5716ada09.cif
正在转换auid-8054645754e712ed.cif
正在转换auid-80b51c554ead9e35.cif
正在转换auid-80d7e3de62d6592e.cif
正在转换auid-80e59296ae90c3e5.cif
正在转换auid-80fc76699de6cef8.cif
正在转换auid-81200c06eba50521.cif
正在转换auid-81a208ef84d40af7.cif
正在转换auid-81c7668e5d656dc8.cif
正在转换auid-8204b98ab4f4d6aa.cif
正在转换auid-847600c806e7ea61.cif
正在转换auid-847876766173ac5d.cif
正在转换auid-85278fe800dc17c5.cif
正在转换auid-8675d58a704f9fef.cif
正在转换auid-868e26d4723091f3.cif
正在转换auid-883a23b457db89c8.cif
正在转换auid-888ad4eeb6e4f434.cif
正在转换auid-88c2933e53c49be0.cif
正在转换auid-895e3050a51b0460.cif
正在转换auid-89a3d85ccf6cb94c.cif
正在转换auid-89d40fc3f4b9d8f3.cif
正在转换auid-8ab584226f41d7b7.cif
正在转换auid-8b0ad31f35cb8f27.cif
正在转换auid-8b5c1bb38d80281a.cif

正在转换auid-8b891c6ed969981d.cif
正在转换auid-8bb438cd1bf3e873.cif
正在转换auid-8ca7882a5938877f.cif
正在转换auid-8cbdeeb36aafe03d.cif
正在转换auid-8cd8130eebb29e1b.cif
正在转换auid-8cd88d37e5936953.cif
正在转换auid-8d425e1bcb0e21eb.cif
正在转换auid-8d8be79c846e583c.cif
正在转换auid-8db88ee9ba02acb2.cif
正在转换auid-8e61634dffff7ea0.cif
正在转换auid-8e7d30e5707590db.cif
正在转换auid-8ee85ee8789bc11a.cif
正在转换auid-8f2a1bb95ac61b8f.cif
正在转换auid-8ff5829ed3bf7c95.cif
正在转换auid-9003ee1161d3f9c4.cif
正在转换auid-9015af76351fb0aa.cif
正在转换auid-9034f1dd0e901cb5.cif
正在转换auid-90aca6518cb97661.cif
正在转换auid-90dca193be105681.cif
正在转换auid-90e68d11d652e79a.cif
正在转换auid-9121c489f212ed80.cif
正在转换auid-91b9293ebeef8161.cif
正在转换auid-91e82e5f47cec0d4.cif
正在转换auid-920204c873f3be82.cif
正在转换auid-923030a1a669f5db.cif
正在转换auid-92904fe44c32a243.cif
正在转换auid-92d029df22270fda.cif
正在转换auid-92dfda6ec3dc1b8b.cif
正在转换auid-932647fedbe33136.cif
正在转换auid-93c44f49c5f831b1.cif
正在转换auid-93f4b85b62e1c90a.cif
正在转换auid-943152b68fa885a9.cif
正在转换auid-94a12ec77e6bdac1.cif
正在转换auid-94f41fce032e8cf6.cif
正在转换auid-94f8dd1731a84755.cif
正在转换auid-963f93996cf1187a.cif
正在转换auid-96e442d81368a0d0.cif
正在转换auid-96ffef7911430b13.cif
正在转换auid-9714967674207549.cif
正在转换auid-980d474b203ffd71.cif
正在转换auid-985012dd0903089d.cif
正在转换auid-9864689a4c473dd1.cif
正在转换auid-98b56b9a62e2c2a7.cif
正在转换auid-993873ba9b92e68b.cif
正在转换auid-9972f882e053297f.cif
正在转换auid-9c17c15c38a63216.cif
正在转换auid-9ea944366a3766cf.cif
正在转换auid-9fc739e112688884.cif
正在转换auid-a02b938f4475a351.cif
正在转换auid-a062b04e53d4c483.cif
正在转换auid-a0ad042aed5b2cef.cif
正在转换auid-a0e2b640fc78605b.cif
正在转换auid-a1295f907978f940.cif
正在转换auid-a1d76023e1fe8009.cif
正在转换auid-a214967cb8c87518.cif
正在转换auid-a24714844784b3d2.cif
正在转换auid-a27b3a6dd281085e.cif
正在转换auid-a2f0dc85e42d02e7.cif
正在转换auid-a37d04e5a075bf16.cif
正在转换auid-a45b465269c51707.cif
正在转换auid-a4bf5eecf1c68cc8.cif
正在转换auid-a53eb61541b6aeb5.cif
正在转换auid-a5778bb74ad5ba56.cif
正在转换auid-a6ca367587cad330.cif
正在转换auid-a8896769605088a5.cif
正在转换auid-a8e126fccdfad3e3.cif
正在转换auid-a92b22d1e4f60477.cif
正在转换auid-a95f0a243c967296.cif
正在转换auid-a973417342789675.cif
正在转换auid-a992f8c2114db372.cif
正在转换auid-a9eae9fb3e264a21.cif
正在转换auid-a9fb90033bab1b15.cif
正在转换auid-a9ff6c5b178cf4be.cif
正在转换auid-aa1cd44e8c45c12c.cif
正在转换auid-aa403f09d8c3c79a.cif
正在转换auid-aa9787aa3a9fe4d8.cif
正在转换auid-ab09e8abcc53ddf7.cif
正在转换auid-ab72266068b3ff42.cif
正在转换auid-abb68f71822ebf08.cif
正在转换auid-abda3c3d1d1bfe7f.cif
正在转换auid-ac097d246295f30c.cif
正在转换auid-ac8feda2a39c6821.cif
正在转换auid-acd0e8bd0591d9f2.cif
正在转换auid-ad49c9742fc55d99.cif
正在转换auid-ad9073401c25c13d.cif
正在转换auid-ae4ca7a1fe331967.cif
正在转换auid-aea18c3962928432.cif
正在转换auid-af1359170f265f2c.cif
正在转换auid-b01f52b3b4c83746.cif
正在转换auid-b061ae84a1b4d0d6.cif
正在转换auid-b0d0cdf5027422cb.cif
正在转换auid-b118fce5c31c3e39.cif
正在转换auid-b299326dbd90c172.cif
正在转换auid-b2a5dbd57c8529d5.cif
正在转换auid-b2f3cfe8563e5964.cif
正在转换auid-b3386c4a0876ef25.cif
正在转换auid-b34da81726b632f0.cif
正在转换auid-b4427bf73ce59adf.cif
正在转换auid-b47dd579f3f37cf4.cif
正在转换auid-b56dd82f4a4aec77.cif
正在转换auid-b7759bedb7672cc7.cif
正在转换auid-b82756c009270804.cif
正在转换auid-b83295dba9108e60.cif
正在转换auid-b83be47dc29db010.cif
正在转换auid-b93b443d4164dbaf.cif
正在转换auid-ba518b4b30d49a5a.cif
正在转换auid-bb207fcda34e375f.cif
正在转换auid-bb7c6921760dfa5e.cif
正在转换auid-bba7a2d7730e142e.cif
正在转换auid-bc3d8412a51387fc.cif
正在转换auid-bc4297e63fb1fa94.cif
正在转换auid-bd4fcf5dce1ad38b.cif
正在转换auid-bd748861d48c2242.cif
正在转换auid-bda761a1a5bdc850.cif
正在转换auid-bdb0741bd85e4f7d.cif
正在转换auid-bdd958748b7f9c5e.cif
正在转换auid-be463c4328d8717c.cif
正在转换auid-be70c544ee929911.cif
正在转换auid-bed1448b5dc51f0d.cif
正在转换auid-bf1bd5d517b07921.cif
正在转换auid-bf57be1b7cfb6f1b.cif
正在转换auid-bff329557fad29be.cif
正在转换auid-c09bdede834933dd.cif
正在转换auid-c13622b3f624a03e.cif
正在转换auid-c167e24126ca9802.cif
正在转换auid-c179b81f59200908.cif
正在转换auid-c332f6f43a439f62.cif
正在转换auid-c3b0d3a443555936.cif
正在转换auid-c54797a6eff476b3.cif
正在转换auid-c567edfdb4158be2.cif
正在转换auid-c576bf108bec3185.cif
正在转换auid-c6e8be97391983c4.cif
正在转换auid-c732189d8716c450.cif
正在转换auid-c73765e496d36f1c.cif
正在转换auid-c860bd32974de0b0.cif
正在转换auid-c9c838133da0cae1.cif
正在转换auid-ca64bcb6959232bd.cif
正在转换auid-ca9b84f73fbd67c3.cif
正在转换auid-cb6dab5f74b7a8d9.cif
正在转换auid-cb6eb37044dc0745.cif
正在转换auid-cb7323ec8ea73c81.cif
正在转换auid-cb954d7a8dcb2760.cif
正在转换auid-cc5e0b1d0b1677da.cif
正在转换auid-cc795e1efbe0f57f.cif
正在转换auid-cc87c23604b29b1f.cif
正在转换auid-ccaa22e46b8c85c5.cif
正在转换auid-cd351773c1643d69.cif
正在转换auid-cd68a4de6d2fa7d1.cif
正在转换auid-cd792ae3f3ccee90.cif
正在转换auid-ce1b9c64e52b7ee0.cif
正在转换auid-ce31ff36ab78f0ed.cif
正在转换auid-ce753e940a84f92a.cif
正在转换auid-ce7a305aa42c47d5.cif
正在转换auid-ced3cd9003cc32cf.cif
正在转换auid-ced800c340089acf.cif
正在转换auid-ceeb933e1ece670f.cif
正在转换auid-cf487f1386c2cbfb.cif
正在转换auid-cf7542c8f9bf8858.cif
正在转换auid-cfbd957bcac66766.cif
正在转换auid-d12f28462f02b966.cif
正在转换auid-d1307a1d88cfa4c5.cif
正在转换auid-d1679666850d8d4f.cif
正在转换auid-d186aa77f30000c1.cif
正在转换auid-d197c591ebd8d6ac.cif
正在转换auid-d1c204594acdecec.cif
正在转换auid-d2b799c99d204962.cif
正在转换auid-d2d6baf32b0e1f00.cif
正在转换auid-d2efc2f92f7fe056.cif
正在转换auid-d32dccb2e6f65602.cif
正在转换auid-d39e3301d55da0b3.cif
正在转换auid-d3a11025c0827f68.cif
正在转换auid-d3c412f77c50256c.cif
正在转换auid-d49303bbc755c345.cif
正在转换auid-d56d85826395f9cc.cif
正在转换auid-d72cb276daa0a865.cif
正在转换auid-d7a08e12960f2c5a.cif
正在转换auid-d7a0b9b1e8f68652.cif
正在转换auid-d7bca78eb94e6235.cif
正在转换auid-d86f33ece111b6f6.cif
正在转换auid-d8f36771f659a266.cif
正在转换auid-d9d3ae17e3e5dc7a.cif
正在转换auid-d9d637352978fd63.cif
正在转换auid-d9f7d1972dbd0382.cif
正在转换auid-daa30b1d5e191780.cif
正在转换auid-dae93da945bfbb8c.cif
正在转换auid-db0dde2b91024ec6.cif
正在转换auid-db7008b3e167d238.cif
正在转换auid-dba48a0936c88d2c.cif
正在转换auid-dbcdf672379deb34.cif
正在转换auid-dc8c7683c14e7852.cif
正在转换auid-dd16013c892b0c8f.cif
正在转换auid-dd4ba0a9b6c1e670.cif
正在转换auid-dd795c2bbb365418.cif
正在转换auid-dd977e2139d7f27c.cif
正在转换auid-de2d3d2943b47896.cif
正在转换auid-df70ee4df4a9d8e5.cif
正在转换auid-dfd7bddb0a1162a3.cif
正在转换auid-e021006b66d0026e.cif
正在转换auid-e099703ad8f7cd7b.cif
正在转换auid-e0a4cc10f84c9c0d.cif
正在转换auid-e0cfc18ac4bfce1a.cif
正在转换auid-e0fe1184537061ae.cif
正在转换auid-e16f1de524f68a6c.cif
正在转换auid-e1859146ad6a7ade.cif
正在转换auid-e1ec2553190388b1.cif
正在转换auid-e22054f85d923900.cif
正在转换auid-e41dbcad0964c269.cif
正在转换auid-e458302b9dd08640.cif
正在转换auid-e4d768b3cb7b2b08.cif
正在转换auid-e4daeeccf26c4c6c.cif
正在转换auid-e5383913d43c5ad5.cif
正在转换auid-e63c448eef2dd7e4.cif
正在转换auid-e77faffaea633983.cif
正在转换auid-e7c758d55f6293ca.cif
正在转换auid-e85844450508665a.cif
正在转换auid-e892ffca1776f1ec.cif
正在转换auid-e96311e5e56ed828.cif
正在转换auid-e9fcd2a400d92d61.cif
正在转换auid-ea0ebe0f0c85fdc0.cif
正在转换auid-ea4e183362fbcb46.cif
正在转换auid-ea8191da9d40457e.cif
正在转换auid-ea95e997016f77e7.cif
正在转换auid-eaa68c3695517ebc.cif
正在转换auid-eb5ef52b184bb5c8.cif
正在转换auid-eb65a84470c23d89.cif
正在转换auid-ec6e856717c0c526.cif
正在转换auid-ecc9c29f08ea50a7.cif
正在转换auid-eed3d5dba8b010cf.cif
正在转换auid-ef7a4292be7995b9.cif
正在转换auid-efdf111eba6979dc.cif
正在转换auid-f042d11f69a3fc83.cif
正在转换auid-f10b9c741a86146f.cif
正在转换auid-f14dae06cc2e1983.cif
正在转换auid-f1519d5bdc348eef.cif
正在转换auid-f18bf0fa0f7a1520.cif
正在转换auid-f20ef4ff55e36f01.cif
正在转换auid-f236f7b326673fd5.cif
正在转换auid-f2a2b163b3e8dc3c.cif
正在转换auid-f32d12abe6b04a6a.cif
正在转换auid-f3aefecc68852f16.cif
正在转换auid-f3baa0e28fb40703.cif
正在转换auid-f3c7c1f7451fc185.cif
正在转换auid-f3f8c32c855c71f9.cif
正在转换auid-f401bdcf4a5c764d.cif
正在转换auid-f44b2639997c87f2.cif
正在转换auid-f451c75eb80b5e66.cif
正在转换auid-f466528042d07bc0.cif
正在转换auid-f51afb3cfb095cc3.cif
正在转换auid-f54bec1c89347f9f.cif
正在转换auid-f5b8f6e19e7195a8.cif
正在转换auid-f5bc1dc8b628a651.cif
正在转换auid-f5e92f4a13bdd159.cif
正在转换auid-f703ee390cad3731.cif
正在转换auid-f722f3ff7dbc892f.cif
正在转换auid-f7b7495963a1533c.cif
正在转换auid-fa067b92267d4a5e.cif
正在转换auid-fa62d946b4b3389c.cif
正在转换auid-fb3fd76c2dcb85db.cif
正在转换auid-fbb55cc6d3ec1e54.cif
正在转换auid-fc2b531e7663cc85.cif
正在转换auid-fc35c09674a2a56b.cif
正在转换auid-fc49302e06768db4.cif
正在转换auid-fc6e318f3a2a9a3d.cif
正在转换auid-fcc505df6e82e26f.cif
正在转换auid-fccf76c538cc89b4.cif
正在转换auid-fda0b6bd676dc036.cif
正在转换auid-fdbd0e635e6779e0.cif
正在转换auid-fe234bf83f4b3556.cif
正在转换auid-fef235f7454aed91.cif
正在转换auid-ffc5aafeb3f9a228.cif
正在转换ICSD-52578.cif
正在转换ICSD-605236.cif

In [88]:
from jarvis.db.figshare import data
d = data('c2db') #choose a name of dataset from above
# See available keys
print (d[0].keys())
# Dataset size
print(len(d))

# Visualize an atoms object
from jarvis.core.atoms import Atoms
a = Atoms.from_dict(d[0]['atoms'])
#You can visualize this in VESTA or other similar packages
print(a)

# If pandas framework needed
import pandas as pd
df = pd.DataFrame(d)
df

Obtaining C2DB dataset 3.5k...
Reference:https://iopscience.iop.org/article/10.1088/2053-1583/aacfc1
Loading the zipfile...
Loading completed.
dict_keys(['atoms', 'id', 'gap', 'etot', 'wf', 'efermi', 'raman_info'])
3520
Zr3B2O2F2
1.0
3.7341229819477553 5.460501282401788e-18 0.0
-1.8670614909738783 3.2339413276830418 0.0
1.4830761653530787e-15 2.568725157093662e-15 24.220471835400282
Zr B O F
3 2 2 2
Cartesian
1.374138114444527 2.877695551999523 12.098343203252039
1.3756067425558371 0.7195607400799698 14.711248146761886
1.375415992474701 0.719459317091375 9.4856255606332
-0.4924337572052535 1.7990378905801798 12.926834754826505
-0.49241395697299783 1.7991377276263572 11.269716797718484
1.3757326045524525 2.8747727299930346 14.779204330584662
1.3756463347490644 2.8746164825811986 9.417898250052753
1.3761590794763872 0.7149668958017052 16.599642443522672
1.3758467553112452 0.714784707375304 7.5972085323080405

,atoms,id,gap,etot,wf,efermi,raman_info
0,"{'lattice_mat': [[3.7341229819477553, 5.460501...",B2F2O2Zr3-1ca00ae0eaaa,0.000000,-67.495078,7.100709,-1.168506,{}
1,"{'lattice_mat': [[3.800165180232585, -7.193926...",B2H2Se2Zr3-3943d0244e23,0.000000,-53.658956,3.096349,1.889724,{}
2,"{'lattice_mat': [[3.550709871477004, 9.6522081...",C2H2O2Y3-cbf305eb62b1,0.000000,-59.490937,1.842956,1.746327,{}
3,"{'lattice_mat': [[2.8504238307461645, 2.600005...",H2N2O2Mo3-bbf1fbcbad33,0.000000,-72.561761,2.463148,4.183828,{}
4,"{'lattice_mat': [[3.2980568455118657, -1.13497...",C2F2Hf3-f3d4a4a7dde4,0.000000,-57.516002,2.944220,2.951826,"{'amplitudes_vvwl': [-0.037825777837672436, -0..."
...,...,...,...,...,...,...,...
3515,"{'lattice_mat': [[4.462777731397675, -1.137820...",SrCl2-67727fec854b,5.738033,-12.648659,5.070851,-2.528958,{}
3516,"{'lattice_mat': [[4.137627623490549, -3.696495...",CaCl2-643810e6bb76,5.783509,-12.845676,5.264197,-2.598479,"{'amplitudes_vvwl': [0.002877139946418325, 0.0..."
3517,"{'lattice_mat': [[3.6729257165600755, 5.860520...",MgCl2-85b63b2e4472,5.941182,-10.848958,5.278431,-2.407717,"{'amplitudes_vvwl': [0.009285703169579794, 0.0..."
3518,"{'lattice_mat': [[4.199186615592249, 1.1307210...",SrF2-c99805c05244,6.020623,-15.863755,5.014490,-3.637958,{}
3519,"{'lattice_mat': [[3.887701498032534, -1.528341...",CaF2-9632fda9fd46,6.450905,-16.348899,5.266086,-3.860679,{}

In [92]:
from jarvis.db.figshare import data
d = data('c2db') 

from jarvis.core.atoms import Atoms
a = Atoms.from_dict(d[0]['atoms'])

df = pd.DataFrame(d)
df

Obtaining C2DB dataset 3.5k...
Reference:https://iopscience.iop.org/article/10.1088/2053-1583/aacfc1
Loading the zipfile...
Loading completed.

,atoms,id,gap,etot,wf,efermi,raman_info
0,"{'lattice_mat': [[3.7341229819477553, 5.460501...",B2F2O2Zr3-1ca00ae0eaaa,0.000000,-67.495078,7.100709,-1.168506,{}
1,"{'lattice_mat': [[3.800165180232585, -7.193926...",B2H2Se2Zr3-3943d0244e23,0.000000,-53.658956,3.096349,1.889724,{}
2,"{'lattice_mat': [[3.550709871477004, 9.6522081...",C2H2O2Y3-cbf305eb62b1,0.000000,-59.490937,1.842956,1.746327,{}
3,"{'lattice_mat': [[2.8504238307461645, 2.600005...",H2N2O2Mo3-bbf1fbcbad33,0.000000,-72.561761,2.463148,4.183828,{}
4,"{'lattice_mat': [[3.2980568455118657, -1.13497...",C2F2Hf3-f3d4a4a7dde4,0.000000,-57.516002,2.944220,2.951826,"{'amplitudes_vvwl': [-0.037825777837672436, -0..."
...,...,...,...,...,...,...,...
3515,"{'lattice_mat': [[4.462777731397675, -1.137820...",SrCl2-67727fec854b,5.738033,-12.648659,5.070851,-2.528958,{}
3516,"{'lattice_mat': [[4.137627623490549, -3.696495...",CaCl2-643810e6bb76,5.783509,-12.845676,5.264197,-2.598479,"{'amplitudes_vvwl': [0.002877139946418325, 0.0..."
3517,"{'lattice_mat': [[3.6729257165600755, 5.860520...",MgCl2-85b63b2e4472,5.941182,-10.848958,5.278431,-2.407717,"{'amplitudes_vvwl': [0.009285703169579794, 0.0..."
3518,"{'lattice_mat': [[4.199186615592249, 1.1307210...",SrF2-c99805c05244,6.020623,-15.863755,5.014490,-3.637958,{}
3519,"{'lattice_mat': [[3.887701498032534, -1.528341...",CaF2-9632fda9fd46,6.450905,-16.348899,5.266086,-3.860679,{}